### ISSUE TITLE
HUD Aviators don't block flashes on flash protection mode.

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#10034]
Basically the title. Would expect it to protect you from flashes in flash protection mode but it just does not seem to. Your screen will go white as usual when subjected to a flash.

Figure this probably isn't intended as the HUD sunglasses provide full flash protection.

Tested this by just flashing myself with the aviators in flash protection mode.

**Comment by GMR25** [comment]
Applies to Thermal Aviators when switched off as well. Realized this during testing, thought it was intended due to the relation to thermals but this offers some interesting clarification.

**Comment by WickedCybs** [comment]
Referenced it in the sunglasses PR by mistake. Anyway, the Aviators Fix PR will solve this.

**Comment by Doxxmedearly** [comment]
Resolved per above
