### ISSUE TITLE
Pumpkin Pie recipe is bugged

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#10077]
The recipe on the wiki is wrong, and the recipe in-game does not work https://github.com/Aurorastation/Aurora.3/blob/05268f8f62fe92ba10c3352dd96b777c82476dbf/code/modules/cooking/recipes/recipes_pastries.dm

Putting the three reagents in an oven does not cook anything. If it's meant to be put into a bowl, that just makes carmelized sugar.

**Comment by JohnWildkins** [comment]
The wiki recipe is indeed incorrect, however the recipe does function.

Note that `/decl/recipe/pie/pumpkin` inherits from `/decl/recipe/pie`, which requires a flat dough. Combining the three ingredients plus the flat dough does, indeed, create a pumpkin pie.
