### ISSUE TITLE
Cult Constructs lose health when dealt halloss/taser/stunbolt damage

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#101]

**Comment by skull132** [comment]
I wonder if I want to keep this or not... It'd make them _slightly_ less formidable, despite them being very formidable regardless.

**Comment by OneOneThreeEight** [comment]
I'd disagree. You're already making a mistake in trying to tase something that's the equivalent of a cyborg, albeit somewhat more evil.

**Comment by LordLag** [comment]
Asking if there has been any more reports of constructs suffering from stun damage

**Comment by Kaedwuff** [comment]
I was a harvester yesterday and walked into the AI core, the turrets set to stun fired on me about 500 times while I was farting around, didn't do anything.

**Comment by LordLag** [comment]
I believe this has been resolved somewhere down the line.
