### ISSUE TITLE
Medical Borg: Scalpel Bug

### ISSUE THREAD

**Issue by Lordnesh** [Aurorastation/Aurora.3#10128]
Game ID: b9n-ceIm
Admin: Mattatlas
Steps taken: admin reset module
Description: I was performing surgery as medical borg, when I interrupted the process (I don't remember). As a result, my scalpel became stuck in the patient. I yanked it out, and a scalpel appeared on the floor. However, I could no longer equip the scalpel. Nor could I pick up the scalpel from the ground.

Admin reset me, and that fixed the issue. However, there was a bloody scalpel stuck on my screen still. Right where it appeared in the inventory screen.

**Comment by Pratepresidenten** [comment]
You should be able to fix "Detatched" modules by dropping them. Did you try this?

**Comment by Lordnesh** [comment]
> You should be able to fix "Detatched" modules by dropping them. Did you try this?

You mean "dropping" it to clear the slot? Yes. I had a bloody scalpel still in my inventory, even with the one on the floor.
