### ISSUE TITLE
IPCs overheat in exosuits

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#10124]
IPCs will overheat in an exosuit with a closed lid, even if oxygen is turned on. Thus if an IPC wants to pilot an exosuit, they require a full rig with a suit cooler.

**Comment by Ben10083** [comment]
Can confirm this is still a issue.

**Comment by Ben10083** [comment]
Same as https://github.com/Aurorastation/Aurora.3/issues/2148

But I recommend keeping this one as the previous issues refers to an outdated system.
