### ISSUE TITLE
New IPC battery gauge is missing a red battery.

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#10133]
If you run your battery to orange, it'll disappear once it reaches red. Meaning it'll look as though you have a full charge but your battery is sitting at next to nothing.
![2020-09-30 (3)](https://user-images.githubusercontent.com/56227386/94689791-41c86180-036a-11eb-885c-b6abaca32ee7.png)

**Comment by Geevies** [comment]
ha ha stinky robutt
