### ISSUE TITLE
Organs teleported out by magician items, when re implanted, take continuous rising organ damage

### ISSUE THREAD

**Issue by wolfwood88** [Aurorastation/Aurora.3#1014]
Saw this happen on two seperate occasions, once with lungs, once with kidneys. Tried to fix the issue by using peridaxon, using a trauma kit on the lungs, transplanting the organ from a monkey, and necrotic organ repair. All fixes did not work, and organ damage continued to rise in the patient no matter what.

**Comment by skull132** [comment]
What items, specifically, cause this?

**Comment by Alberyk** [comment]
Wizard teleporting scroll.

**Comment by Arrow768** [comment]
From my understanding it is intentional behaviour if this happens when trying to re-implant monkey organs into a human.

**Comment by wolfwood88** [comment]
I have seen it with both transplants from monkeys. But in this instance, it was re implantation of their OWN organ, and still had this effect.

**Comment by Geevies** [comment]
Think this has been fixed.
