### ISSUE TITLE
Persons name dissapeared, they did not appear on tile, was un able to use certain actions with them, and could not treat them properly with cryo

### ISSUE THREAD

**Issue by wolfwood88** [Aurorastation/Aurora.3#1015]
One person got an excessive amount of damage from a slime, came in to medical, had no name show up, could not interact with them by left clicking them (Couldnt hug or shake to wake up). When I tried to treat them, cryo healed all of their toxins, but their health never improved. Here is an image of the end result, they were left in for a while even after their toxins were fixed just to make sure this was an issue. 
http://imgur.com/ANx8m36 

They initally had over 80 toxin damage, which if all caused by slimes would kill a player, why they didnt die may be part of the glitch. Also note that the cryo pod only registers them as NULL.

**Comment by Alberyk** [comment]
By the way, in the same round, everything went bork, like the follow verb and mob processing.

Game id: bY2EVf
