### ISSUE TITLE
Xenobotany cannot open crates with their tools ordered from Cargo

### ISSUE THREAD

**Issue by Nerrathiel** [Aurorastation/Aurora.3#10156]
Up 'till recently Xenobotany had Hydroponics access as an absolutely ghetto way of being able to order things from cargo that Xenobotany uses during their work.

Recently, Hydro access got removed from Xenobotanists, however, this has caused an issue where Xenobotany players can no longer open crates with their supplies ordered from cargo.

As such, it is needed to add an OR Xenobotany Access requirement to hydroponics-locked cargo crates.

Xenobotany access id is 55 (Source https://github.com/Aurorastation/Aurora.3/blob/43c5919307c6dc75003d7ea8d05237178e3e7c77/code/game/jobs/access_datum.dm )

**Comment by Geevies** [comment]
fixed
