### ISSUE TITLE
PDA security records can't be accessed while buckled

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#10166]
Basically the title. Noticed that if I used the security record function that sec cartridges (Think its R.O.B.U.S.T) give while sitting down, I could go into the menu which lists all crew members which was expected. Actually clicking on a name did not actually open up the record, though. I had to unbuckle and then click on the name to get it to open.

**Comment by WickedCybs** [comment]
I tried replicating this on a standard chair and it didn't work, oddly enough. I first noted this issue while sitting in a shuttle seat, so I will be seeing if it exclusive to those then.

**Comment by alsoandanswer** [comment]
This might be addressed in upcoming PDA update

**Comment by JohnWildkins** [comment]
Duplicate of #4526
