### ISSUE TITLE
Space lube cannot be removed/does not fade away once it has been sprayed on a tile

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1016]

**Comment by skull132** [comment]
How manieth time is this bug being reported. Seriously. Do a quick issue search before reporting something:
https://github.com/Aurorastation/Aurora.3/issues/615
https://github.com/Aurorastation/Aurora.3/issues/1011

Also, intended functionality, not a bug. But it's being "adjusted" in PR #1013 .
