### ISSUE TITLE
Spawning without my box on "Nothing" option

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#1019]
I spawn in and my box isn't in, saying: "Failed to locate a storage object on your mob, either you spawned with no arms and no backpack or this is a bug." and it's happened twice in a row, so I am not completely certain if it's a common bug that'll happen to everyone, or a more complex bug that I'm unlucky enough to have twice in a row.

**Comment by dragoslava** [comment]
@skull132  @DronzTheWolf  is this still happening? Only reason I believe is somehow they dont got a backpack
