### ISSUE TITLE
Prescription glasses from loadout don't work

### ISSUE THREAD

**Issue by Playbahnosh** [Aurorastation/Aurora.3#10211]
The prescription glasses from the loadout eyewear section are in fact _not_ prescription glasses, even though they are called such. When spawned with them, they do not correct myopia (nearsightedness). However, the ones from the "prescription glasses" box in the medical sublevel, those work without issues.

**Comment by Playbahnosh** [comment]
Why was this closed?

**Comment by JohnWildkins** [comment]
fixed by #10308
