### ISSUE TITLE
Repaired door in old maint kitchen\maint bar

### ISSUE THREAD

**Issue by IndirectCell** [Aurorastation/Aurora.3#10262]
![bilde](https://user-images.githubusercontent.com/60559077/96131343-59baec00-0ef9-11eb-850d-0893b25d63fe.png)

The door appears to not function as a door as i can walk over it, it does respond to robot controlls like opening and stuff, maybe its on the wrong layer of the map.

**Comment by IndirectCell** [comment]
Err problem is seperate to what i just said, the door exist, but its on the two lower tiles horisontal, and not vertical.

![bilde](https://user-images.githubusercontent.com/60559077/96131733-dcdc4200-0ef9-11eb-8281-6b5368d70af3.png)

you can see me hitting the door in picture, without interacting with it, just moveing into it and it opens from east side, like i said, horisontal door with a vertical door image.

**Comment by Playbahnosh** [comment]
something similar happened once when the double-door in medical was replaced. You can simply walk over the door sprite on the upper tile, only the lower tile triggered the door. There are some pathing issues with newly built double doors.
