### ISSUE TITLE
Cutting the hair off the hide sheet creates steel sheets

### ISSUE THREAD

**Issue by r4iser** [Aurorastation/Aurora.3#10280]
Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.
* When you **cut out the hair off the hide sheet, it creates Steel sheets**. The steel sheet looks like leather, but its steel sheet.

* Reproduce: *
Use any blades into Hide Sheet. It will create metal sheets.

**Comment by Geevies** [comment]
now this is pogchamp
