### ISSUE TITLE
Broken Accent Icons

### ISSUE THREAD

**Issue by Triogenix** [Aurorastation/Aurora.3#10306]
It appears for me and atleast one other, accent icons appear to broken as in they do not properly correspond to what the accent actually is. Example being Diona Rootsong having the icon of the Gadpathurian Accent(as seen in the screenshot) or earthers having European accents(not pictured).
![Screenshot_15](https://user-images.githubusercontent.com/73185699/96609615-b1c26b80-12c8-11eb-92ad-0f5145f80d97.png)

**Comment by JohnWildkins** [comment]
confirmed, working on a fix rn
