### ISSUE TITLE
NTNet program causes end of technology

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#10327]
If you're using the NTNet utility program in science and you disable wireless ntnet, you kill all NTNet connectivity both wired and wireless.
Doing this also kills your connection to the program so you cannot undo the damage.

**Comment by Arrow768** [comment]
> Doing this also kills your connection to the program so you cannot undo the damage.

It is possible to undo this using the NTNet Hub in the tcoms area.

**Comment by Arrow768** [comment]
Apparently the relay itself is not configurable
