### ISSUE TITLE
Unable to perform organ transplants as medical borg

### ISSUE THREAD

**Issue by Lordnesh** [Aurorastation/Aurora.3#10321]
As the title says, I attempted to perform an organ transplant as a medical borg. I was able to pick up the organ (even grabbing it from inside an organ cooler), but was unable to click on the patient to transplant the new organ.

**Comment by mikomyazaki** [comment]
Tried to fix this same bug on Baystation some time ago... but couldn't come up with a good fix.

This was one implementation of a fix - https://github.com/Baystation12/Baystation12/pull/27605
