### ISSUE TITLE
Adhomian watch readout issue.

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#10373]
When the Adhomian watch is examined, it gives you the time and date on Adhomai. It seems like the Adhomian day is not displaying properly though. Examining it will give a message along the lines of "You check your adhomian watch, glancing over at the watch face, reading the time to be '10. Today's date is 'th day of Sil'nrry-rhazzimy 3620". It seems the day is lacking, as it never gets numbered.

**Comment by Alberyk** [comment]
It seems to happen at random or depending on the day, I will try to find out what is the issue with it.

**Comment by WickedCybs** [comment]
Forgot to add an additional thing. It seems they can't be worn in the face slot either, and the description mentions being able to be worn around the neck.
