### ISSUE TITLE
Ninjasuit gloves aren't resistant to handcuffs

### ISSUE THREAD

**Issue by printer16** [Aurorastation/Aurora.3#1039]
Many other hardsuits are, you would think a high tech ninja hardsuit would be designed to resist handcuffs as well. I think they were at one point, but they got insulated gloves instead so they didn't get shocked, but lost their handcuff resistance as an oversight.

**Comment by OneOneThreeEight** [comment]
Not a bug if the gloves are equipped. Reasoning behind it is that it's too thick to wrap handcuffs around, it runs the check for the gloves.

Btw the ninja gloves are already insulated, iirc.
