### ISSUE TITLE
Duty Officers can see channels they shouldn't be able to

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#104]
Duty Officers can see admin PMs between other players (But not ahelps)
Dead chat when in the lobby, or in game and not dead (Can't talk in deadsay in these circumstances, however)
Remote LOOC

**Comment by skull132** [comment]
(R)LOOC was fixed in #95 . Also tested on the server, and the fix is active.

**Comment by skull132** [comment]
All reported issues fixed in #114 .
