### ISSUE TITLE
Defusing welder tanks is circumvented by welding the tank again

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#1041]
Title, pretty much. Admin defusing a welding tank does not defuse it if the attempted welder-ee attempts it for a second time.

**Comment by SoundScopes** [comment]
This was intentional to stop admins defusing tanks and forgetting about them.

If someone is attempting a welderbomb you should defuse then wind to stop people trying again

**Comment by skull132** [comment]
There's an issue in being able to bypass this. You can spam click the tank
a good few times, which a griefer sometimes does to compensate for click
lag, and it starts multiple parallel timers. The first gets through and is
blocked, the others are then unblocked.
