### ISSUE TITLE
Borg open hatch sprite sometimes sticks forever

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#10456]
Game ID: b9X-csna

When borgs come in for upgrades, sometimes the open hatch sprite, and speech bubbles sometimes remain stuck. Ive tried a number of fixes, but generally it cant be fixed outside of replacing the entire borg.

The hatch sprite bug is not persistent, it doesnt always happen when you open a borg.

**Comment by JohnWildkins** [comment]
duplicate of #9576
