### ISSUE TITLE
People committing suicide with a gun does not produce admin logs.

### ISSUE THREAD

**Issue by incognitojesus** [Aurorastation/Aurora.3#1046]
What it says on the tin. Somebody can commit suicide by shooting themselves in the mouth, and it doesn't produce admin logs.

**Comment by Alberyk** [comment]
By the way, they didn't stick the gun into their mouth, he just shot himself by clicking on his spessmen with a gun on harm intent.

**Comment by Geevies** [comment]
Fixed.
