### ISSUE TITLE
Wizard angry statue spell attacks the subject of the spell

### ISSUE THREAD

**Issue by TheTailson** [Aurorastation/Aurora.3#10485]
The spell used to turn a crewmember into a statue that attacks others works fine for the first minute or so. When the spell effect begins to wear off, the statue will attack the person who was turned into a statue. Because the statue hits so hard, and because the effect takes so long to wear off, the subject of the spell will invariably die.

I doubt this is supposed to happen! Can an exception be put in to prevent the statue from attacking "itself"?

![image](https://user-images.githubusercontent.com/30989747/98444961-d2822200-210c-11eb-88d3-73dc3853d15c.png)

**Comment by Doxxmedearly** [comment]
Wizard is no longer an available gamemode. Closing.
