### ISSUE TITLE
Trays in hydroponics not using added water or nutrience

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#105]
You can fill the trays with water and nutrients however the number doesn't seem to go down. The tray will flash for additional water but when added, nothing changes. Here's a screenshot: https://gyazo.com/05dccd3dcb4a26344316160765675a9a 

Perhaps related to issue #61?

**Comment by skull132** [comment]
Same issue, I imagine. I'll close this in lieu of issue #61.
