### ISSUE TITLE
Medical doesn't have access to NTCC Odin Hospital, but everyone has access to the baby chemistry windoor there.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#10535]
AS above. Even CMO doesn't have access to Odin medical anywhere, but everyone and their assistant might have access to the windoor.

**Comment by Melariara** [comment]
Oh also, borgs don't have access on Odin. Unsure if that's a bug or not.

**Comment by Playbahnosh** [comment]
> Oh also, borgs don't have access on Odin. Unsure if that's a bug or not.

Borgs aren't even supposed to leave the station. "Stationbound" and all that. I think they don't explode en route to the Odin to prevent griefing.

**Comment by Doxxmedearly** [comment]
Tested on most recent branch, access seems to be working correctly. Not sure if this was for the Odin prior to the remap. Resubmit if for some reason this isn't true. Also yes, stationbounds should not have any rights on the Odin.
