### ISSUE TITLE
Maintainance drones cannot enter Robotic Storage units

### ISSUE THREAD

**Issue by Joonasm** [Aurorastation/Aurora.3#10542]
As a maintanance drone, neither dropping and dragging yourself or right clicking and choosing enter let you go into a Robotic storage unit. I would assume they are meant to be able to as the drone fabricators both have a storage unit in the same room

**Comment by mikomyazaki** [comment]
Seems to be a deliberate choice by someone 6 years ago.
`/obj/machinery/cryopod/robot` has:
`disallow_occupant_types = list(/mob/living/silicon/robot/drone)`
