### ISSUE TITLE
Ta get set to TTS Accent

### ISSUE THREAD

**Issue by Myphicbowser** [Aurorastation/Aurora.3#10560]
So its a minor issue, but with the new species change accent fix, it seems that spawning as a Ta sets you to the TTS Accent which is against the lore

Steps to Replicate is real easy
1. Create a Ta by being a Vaurca Worker with Zo'ra citizenship and Consular Officer Role selected
2. Select an Accent that is not TTS
3. Spawn in and speak to see it being set to TTS

Now I think this happens because the Vaurca Breeder is a species that you get changed to once everything else lines up yah know? But I'm not a coder so I could be wrong
Hope I did this right

**Comment by Doxxmedearly** [comment]
This is likely due to their accent being reset to default when they spawn in, as that is when the species gets set. In set_species() it reverts to default accent.
