### ISSUE TITLE
pAIs Escape jars by folding in

### ISSUE THREAD

**Issue by Joonasm** [Aurorastation/Aurora.3#10574]
![image](https://user-images.githubusercontent.com/62698555/99329846-bb1f0380-2887-11eb-868b-ae82320fa577.png)
As a pAI if you fold in while inside a jar you drop out of it while leaving your sprite inside.
 Opening the jar just makes sprite disappear and doesn't seem to result in additional weirdness

**Comment by mikomyazaki** [comment]
@alsoandanswer
