### ISSUE TITLE
Middle clicking a toolbox with a hardsuit mounted RCD clones, and breaks the RCD.

### ISSUE THREAD

**Issue by SirCatnip** [Aurorastation/Aurora.3#1060]
So, you miss a door trying to deconstruct it with your suit mounted RCD, and hit a toolbox, all of the sudden, "You place the RCD into the electrical toolbox" comes up.

After that, a new, empty RCD is spawned inside the toolbox, and the one in the suit becomes non-functional, spitting out "Insufficient resources", no matter how much power etc. your suit has. I tried switching suit cells, taking it out and back in, everything, no dice.

**Comment by Geevies** [comment]
Fixed.
