### ISSUE TITLE
Expedition shuttle appears to be bugged

### ISSUE THREAD

**Issue by AstraZemin** [Aurorastation/Aurora.3#10631]
On two separate rounds, the expedition shuttle has failed to launch. The issue was ahelped the first time we encountered it, Pratepresidenten told us to make a bug report. Since it appears to be a frequent issue, I'm making one now. Sorry if I can't give more details.

**Comment by Arrow768** [comment]
Do you have any game ids of the rounds where this issue occurred?

**Comment by AstraZemin** [comment]
I think the last time it was bugged was b0f-csyQ

**Comment by FieryTech** [comment]
If I can add my input on this issue:
- The console of the shuttle told us that the destination is obstructed, or doesn't exist.
- The ICARUS report was generated, and the away site as well, nothing strange on that.
- Pratepresidenten tried to smash the away site landing zone, but nothing.

**Comment by fernerr** [comment]
The specific map has been identified, the landing zone is not aligned correctly so there's not enough room for it.

**Comment by fernerr** [comment]
The map has been removed from the selection for now, let us know if the issue comes up again.
