### ISSUE TITLE
Robotic simplemobs (Such as mining drones, again) get a bloody overlay when injured

### ISSUE THREAD

**Issue by ChevyChevron** [Aurorastation/Aurora.3#10644]
Remember that time I submitted a report about mining drones bleeding when you stab them, and it turned out they had been overlooked following a change to simplemobs?  Pretty sure that happened again.

**Comment by Doxxmedearly** [comment]
Seems to have been fixed in the PR that changed how simple mob blood was handled. Testing showed no blood overlay. Resubmit a report if it continues to happen.
