### ISSUE TITLE
Unable to be heard on radios while cuffed

### ISSUE THREAD

**Issue by Myphicbowser** [Aurorastation/Aurora.3#10662]
So I am terrible at this so to keep it simple, while Handcuffed your voice does not go through radios or intercoms at all, which means the Interrogation room is useless unless they want to have you uncuffed, which for some antags is impossible, that's all I got, just stymies Security a bit and makes them less likely to take you in

**Comment by Doxxmedearly** [comment]
Intentional that you can't use radios or headsets while cuffed. Do you mean even when on "listening" mode your voice can't be heard?
