### ISSUE TITLE
The component pouch fanny pack in the loadout spawns with toxin vials and has 14 slots.

### ISSUE THREAD

**Issue by Menown** [Aurorastation/Aurora.3#10692]
When you select the component pouch in the loadout, you effectively get another satchel, for your belt slot, and a supply of toxins and other useful shit as opposed to the normal empty pouch you get with the other fannypacks. It also possesses an insane amount of space compared to other fannypacks.

**Comment by JohnWildkins** [comment]
Fixed by #10702
