### ISSUE TITLE
Trying to apply any of the new posters just makes them invisble

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1078]
![untitled3](https://cloud.githubusercontent.com/assets/19973802/19825687/e3a33c10-9dd8-11e6-9682-207c998552bf.png)

So far two of the new posters I've stuck to walls on the test server are invisible and exist only through descriptions and names.

So far all the old posters that have been with us forever still work.

**Comment by skull132** [comment]
@Alberyk
