### ISSUE TITLE
Unable to compile via Dream Maker

### ISSUE THREAD

**Issue by ChevyChevron** [Aurorastation/Aurora.3#10788]
Downloading files directly from the master branch created the following issue:
`loading aurorastation.dme
loading interface\skin.dmf
code\controllers\subsystems\job.dm:854:error: ?.: bad variable definition
code\modules\integrated_electronics\subtypes\input.dm:303:error: ?.: bad variable definition
code\modules\integrated_electronics\subtypes\input.dm:302:warning: A: variable defined but not used
code\modules\organs\organ.dm:272:error: ?.: bad variable definition
code\modules\mob\living\carbon\human\human_attackhand.dm:478:error: ?.: bad variable definition
code\modules\mob\living\living.dm:389:error: ?.: bad variable definition
code\modules\mob\living\living.dm:388:warning: shooter: variable defined but not used
aurorastation.dmb - 5 errors, 2 warnings (12/12/20 6:37 am)`
As I compile using Dream Maker, it does not produce the DMB file if it detects an error.  I have no idea what is going on here, but I'm reasonably sure it isn't my fault.

**Comment by Geevies** [comment]
latest byondarino's busted, downgrade and etc yes
