### ISSUE TITLE
Personal AI Candidacy Ignores Character Setup Enable Option

### ISSUE THREAD

**Issue by Talkarcabbage** [Aurorastation/Aurora.3#108]
Candidacy for personal AI role being set to YES in the character options screen does not enable it as a ghost; it must be enabled using the toggle specialrole candidacy option. This persists through restarts and character changes. 

Posibrain Candidacy appears to function normally.

If someone else has also observed this bug and has more information, or has not seen it, please contribute a reply.

**Comment by NanakoAC** [comment]
Ive been working on pAIs a bit anyway, ill see if i can deal with this

**Comment by NanakoAC** [comment]
fixed by #666
