### ISSUE TITLE
Additives to BPM do not seem to be combining correctly? Double heart beat sound. 

### ISSUE THREAD

**Issue by Sharkatk** [Aurorastation/Aurora.3#10806]
I have noticed recently that if you combine thing's that should add to the heart rate, it seems to be adding a lot higher than it used to. 
Even drinking two different types of coffee now that didn't used to cause heart damage is causing it now if you drink more than 15 units combined. And it is causing a stacking heart beat sound, instead of one consistent heart beat. It is playing two loops at the same time. Drinking more types combined may make it even worse. 
Holopain and sprint exhaustion was enough to send the BPM to over 250+

Wanted to make a report just in cause something went wrong cause it could potentially be a problem if other sources are doing the same thing with heart rate.

**Comment by Doxxmedearly** [comment]
Coffee no longer raises BPM. Other sources are meant to stack. Resolved.
