### ISSUE TITLE
Unathi can spam the devour command to eat animals faster

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1080]
I believe if a Unathi uses the devour command several times while eating an animal, it'll start several individual actions, giving messages at a faster rate and eating the animal at a faster rate as well.

Probably makes it possible to eat a Plains Tyrant with some creativity.

**Comment by skull132** [comment]
@NanakoAC A quick fix would be needed, maybe into Dev.

**Comment by NanakoAC** [comment]
fixed by #1098
