### ISSUE TITLE
shell too hot ;-;

### ISSUE THREAD

**Issue by FayeLovesU** [Aurorastation/Aurora.3#10805]
I recently got my shell whitelist, and after talking to a few other shell players I believe I may have found a bug? For some reason, every article of clothing will automatically put my shell into _at least_ the yellowish green "uncomfortably hot" cooling notice. From what I have been told, I should only be getting that hot passively when wearing armor. This issue was present when I got the whitelist, and I have never had a round where it was not present. I am not running or doing anything that, to my knowledge, would increase her heat output.

The two outfits I have for her currently are:

- pink flower pin
- elyran holographic suit, feminine
- black boots, knee
and
- pink flower pin
- boot, dark work boots,
- cardigan
- skirt, swept skirt.

note: these are not the only two outfits i have experienced this heating issue with, but these are the only two i have in my loadouts. if this is intentional / an error on my end, i am sorry for the frivolous report!

**Comment by niennab** [comment]
I worked with Faye a bit in trying to diagnose the issue and I can confirm that shells are not supposed to be default yellow hot, nor have I ever seem them get any chat indications of their heat passively and so something is wrong.

**Comment by Doxxmedearly** [comment]
Discussed with OP, issue resolved.
