### ISSUE TITLE
Fortune cookie recipe does not produce fortune cookies as a borg

### ISSUE THREAD

**Issue by Recoherent87** [Aurorastation/Aurora.3#10810]
Trying to make a fortune cookie according to the recipe on the wiki (which was cross-referenced with the actual code) only results in a baked dough slice. Paper and sugar are not used up. This was repeated ~6 times with the same result. Setting the oven to "cookie" mode, to see if it was conflicting with the custom cookies, just resulted in a really sugary cookie.

**Comment by sheeplets** [comment]
Fortune cookies need a piece of paper with something written on them. I don't understand why, but that's the only way I've managed to get them to work.

**Comment by MarinaGryphon** [comment]
> Fortune cookies need a piece of paper with something written on them. I don't understand why, but that's the only way I've managed to get them to work.

I could see about adding a list of pregenerated fortune cookie texts to be used if there's nothing written on them? But like, a blank fortune cookie would be pretty...

*unfortunate*

:sunglasses:

**Comment by Doxxmedearly** [comment]
As stated, it's not a bug, but it is kinda silly. #12030 will allow blank pages to be used.
