### ISSUE TITLE
Adding sugar to an oven tray, inserting it into the oven, and then removing it from the oven causes the measured sugar to disappear

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#10813]
No idea if this applies to other reagents. Minor fucky-wucky.

**Comment by MarinaGryphon** [comment]
Is there a message of the sugar melting, or something?

**Comment by sheeplets** [comment]
Nothing. In and out in a matter of seconds, the sugar just disappears.
