### ISSUE TITLE
Roboticists and other staff can't interface/use cybersuits made by robotics after researching illegal tech

### ISSUE THREAD

**Issue by Kaizrr** [Aurorastation/Aurora.3#10832]
Kinda wacky that I can make these cybersuits after asking security to research illegal tech in hopes of letting security use said suit and they turn out to be locked for everyone on the station including the creator. I'm guessing it's because these are antag items and are coded to only be useable or interacted with by high tech antags. (Ninjas and the likes).

**Comment by Doxxmedearly** [comment]
Not a bug. Feel free to make a suggestion on the forums to change this.
