### ISSUE TITLE
Switch shoe layer is not working

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#10860]
Essentially the title. Trying to switch the layer no longer works.

**Comment by WickedCybs** [comment]
It's easier to see this in action with pants and black boots. Try hitting switch shoe layer, usually part of the boot will go under the pant sprite, but it just does not change at all.

**Comment by Sgtsammac** [comment]
Can confirm I've had this issue as well when using the CE Jumpsuit and workboots.
