### ISSUE TITLE
Water on-station exists from beyond the heat death of the universe.

### ISSUE THREAD

**Issue by Aticius** [Aurorastation/Aurora.3#10863]
Water, when poured from a container into another container, instantly freezes, turning into ice. Consuming water gives a bugged thermal taste of "last_thermal_energy", allowing you to literally taste the Heat Death of the Universe.

**Comment by sheeplets** [comment]
Also applies to the taste of packed rice bowls for some reason

**Comment by Jiamil** [comment]
Chocolate candy and muffin also give this message:
You can taste last_thermal_energy.

**Comment by Aticius** [comment]
This is apparently related to a sneaky test merge of this PR: https://github.com/Aurorastation/Aurora.3/pull/10538

**Comment by MarinaGryphon** [comment]
Should now be fixed in the PR.

**Comment by Doxxmedearly** [comment]
No longer an issue
