### ISSUE TITLE
Somehow possible to teleport up two stories in a wheelchair

### ISSUE THREAD

**Issue by ChevyChevron** [Aurorastation/Aurora.3#10877]
Round ID: b0Q-aA64
A friend of mine was working in cargo and using a wheelchair for giggles.  Toward the end of the shift, they tried to take the stairs up to transfer but somehow upon going up one z-level, they wound up stuck in the QM's office.
Only things I can think of that may be at all relevant to the circumstances: The wheelchair had been ridden up the elevator prior to this, the elevator was going up to the surface when it happened, the person in question was holding a corgi.
I highly doubt this can be reproduced, but it's a pretty significant glitch I think.

**Comment by SleepyGemmy** [comment]
happened again, on the Horizon. round ID: ckB-cQ4C.
