### ISSUE TITLE
Porting character saves to a DB

### ISSUE THREAD

**Issue by Mahzel** [Aurorastation/Aurora.3#109]
Porting character saves to a DB will allow future improvements,  capabilities and stats gathering.

**Comment by Mahzel** [comment]
Putting jobs alternate title's a bit tricky, but the rest is mainly done and commited. Still, testing need to be done. Don't want to mess up players characters :( Feel free to pull from my dev branch to test it out.

**Comment by skull132** [comment]
I am looking at how Paradise did it. They take the list (`datum/preferences/var/player_alt_titles`) in a client's preferences datum, and convert it to a text string with `list2params()` and then store that text string in a mediumtext column. When they pull it, they just set the var to equal `params2list(query.item[whatever])`.

**Comment by skull132** [comment]
For reference:
* The pulling of the data: https://github.com/ParadiseSS13/Paradise/blob/628b9a0aa60dd5902b587890e3d89313b8e8303c/code/modules/client/preferences_mysql.dm#L223
* The column declaration: https://github.com/ParadiseSS13/Paradise/blob/628b9a0aa60dd5902b587890e3d89313b8e8303c/SQL/paradise_schema.sql#L78
* The variable used and converted (in our code): https://github.com/Aurorastation/Aurora.3/blob/master/code/modules/client/preferences.dm#L118
* And how the list looks like when populated with data: http://puu.sh/nNdLU/87eb3faf95.png

**Comment by skull132** [comment]
Implemented fully in #350 .
