### ISSUE TITLE
Folks starting a downstream of you have a question.

### ISSUE THREAD

**Issue by KodiakJackson** [Aurorastation/Aurora.3#10906]
Some friends and I are starting a downstream of you guys because we really love the work that you've done but want to throw in our own spice here and there. We cannot seem to figure out for the life of us how to change the lobby music, as we wanted to use our own. We followed the Readme's in the sound and music folder to no avail.

**Comment by Geevies** [comment]
i believe we've solved this in #code_dungeon, feel free to DM me on discord at `Geeves#8863` if you have more questions
