### ISSUE TITLE
Unexpected Dismemberment Sprite Outcoms

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#1095]
http://i.imgur.com/XrLyTeu.png?1

Dismembering an IPC leaves phantom limbs - easily visible when severing the head.

Dismembering a human's right arm leaves a phantom right arm, but properly severs the hand from this phantom limb.

**Comment by FirinMaLazors** [comment]
Dismembering a human's right arm removes the arm properly.
Dismembering an IPC's right arm removes the arm properly.  Also the left leg.  Tested on multiple brands.
