### ISSUE TITLE
Traitors cannot access Traitor menu (Now with extra bug)

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#10959]
- Traitors cannot access their Tator menu via chat client
- pAI messaging just comes up with a blank box.

**Comment by Karolis2011** [comment]
You you mean Uplink meniu? I can easily access it. Tested at 8580005634


https://user-images.githubusercontent.com/11229891/104217985-c08e6980-5444-11eb-8f26-fc02b5054e36.mp4
