### ISSUE TITLE
Malf abilities updating

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#10965]
Had a round of malf were me and Aboshebab had a mess of trouble figuring out how to let my borg make a cyborgifier. It took us a long time to figure out that the real issue was that my tab had not updated with the synthetic takeover.

For a long while we couldn't determine if I had even researched it, and finally Abo asked me to return to my core and voila. It would be very helpful if the tab could auto-update when you finish a research, and if there was a clearer 'guide' to how one can build the cyborgifizer

**Comment by SleepyGemmy** [comment]
malf isn't a thing anymore.
