### ISSUE TITLE
Borg xenobiology issues

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1097]
You cant unwrap a monkey cube directly after pulling it out of the box, it needs to be placed on a table and then picked up again to be unwrapped. (Related to: The table has to be clicked two or three times before the cube is placed on it).

Injecting a monkeycube while holding it with a gripper causes the cube to disappear without any monkey spawning.

Slime steriod cant be picked up with either of the grippers.

And saving the best for last: Injecting a gold core literally breaks the server.

**Comment by LordFowl** [comment]
All of these are true except for the last one, which remains unconfirmed.

**Comment by Pratepresidenten** [comment]
Update! Injecting a monkeycube while its in the borg gripper causes the monkey mob to spawn inside the borg.

Slime steroid or whichever the other docility potion is called still cant be picked up.
