### ISSUE TITLE
going up the stairs in a wheelchair sends you to space

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#10987]
![Capture](https://user-images.githubusercontent.com/31339047/104511329-89da5f80-55ba-11eb-95ca-c1efe603a33b.PNG)

**Comment by NerdyVampire** [comment]
From the main level up it sent me to the QM's office:
![image](https://user-images.githubusercontent.com/8639807/106104742-20725900-6143-11eb-8cde-bf55844a88a0.png)

**Comment by LadyFowls** [comment]
https://github.com/Aurorastation/Aurora.3/issues/10877 Related, I can try looking into this

**Comment by SleepyGemmy** [comment]
duplicate of #10877.
