### ISSUE TITLE
Ghost clothing opacity is equal to living mobs

### ISSUE THREAD

**Issue by Shenaanigans** [Aurorastation/Aurora.3#11000]
The clothing on ghost sprites now has higher opacity than the rest of the body, making it difficult to distinguish who is actually in game and who is just an observing ghost. Example seen here in my luminous white labcoat.

![image](https://user-images.githubusercontent.com/63329322/104794105-8b02bc80-5773-11eb-9c21-aa14c2f4e972.png)

**Comment by Geevies** [comment]
fiksed
