### ISSUE TITLE
Robot flavor text not saving.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1103]
It doesnt seem to transfer over to new rounds, after the new borg overhaul. (Medical/Rescue modules)

It saves for the round you set it in, but thats pretty much the extent.

**Comment by skull132** [comment]
You are saving from the character editor, right?

**Comment by Pratepresidenten** [comment]
Yup! Just tried something different aswell. Posted the same flavor for multiple modules. The others stuck, while medical/rescue got wiped post round.

**Comment by skull132** [comment]
Oke, yes, I know the issue.
