### ISSUE TITLE
Spell contracts and robeless casting

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#11047]
It seems if a wizard doesn't make someone an apprentice, and instead gives them a scroll for a singular spell instead, the person who receives the contract isn't able to cast it as they need a robe to do so, no robe spawns for them however.

I am thinking this is probably an oversight as everything was made robeless for wizards and apprentices, this was the first time I've also seen a wizard actually give a _single_ spell to. It does still link you to them in servitude. 

Game ID where this happened was cae-dLvP, an admin assisted in allowing me to cast the spell without restriction.

**Comment by Doxxmedearly** [comment]
Wizard is no longer an available gamemode. Closing.
