### ISSUE TITLE
Synaptizine breaks stamina

### ISSUE THREAD

**Issue by Russell454** [Aurorastation/Aurora.3#11065]
Issue was caused by:

Got Hallu stung by a ling, went to medical and was provided a 5u Synaptizine pill which I swallowed. 

Many players on the server followed these steps (due to sting spam), and received the following:
- Stamina bar looks mostly full, but never is full. Always regenerating.
- Hunger and thirst rapidly increasing.

Figure it must have been either the sting or the drug - unsure which. Kind of makes the game unplayable as you have to constantly eat and drink to avoid move-speed loss.

**Comment by Russell454** [comment]
Updated title.

Was given Synaptizine to treat a few issues I had, same issue.

**Comment by Doxxmedearly** [comment]
This was addressed by #11311
