### ISSUE TITLE
Electric Chair is missing a sprite

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#11084]
Creating from applying electrohelmet assembly to a regular steel chair. Result is an object called 'electric chair' which is missing a sprite.
![image](https://user-images.githubusercontent.com/8639807/106104268-85797f00-6142-11eb-850c-e2f4c20aa6ef.png)

**Comment by Doxxmedearly** [comment]
Bug confirmed, but the team has decided to remove the item entirely.
