### ISSUE TITLE
Blobs not attacking walls often, or at all

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#11094]
It seems like the new variant of blobs aren't expending any effort on destroying a wall, at least according to my observations. Breaches are rare, mainly caused by emitters. 

My expectation was that they would still damage walls, but take much longer to do so rather than not at all. I could be wrong in thinking this is how it is supposed to be, though.

**Comment by WickedCybs** [comment]
If a round helps, can be observable with this ID cal-dACB.

**Comment by WickedCybs** [comment]
This is intentional on reinforced walls it seems.

**Comment by Doxxmedearly** [comment]
Intentional behavior.
