### ISSUE TITLE
Wizards can cast spells while paralyzed/paincrit

### ISSUE THREAD

**Issue by DriedCrust** [Aurorastation/Aurora.3#11104]
Due to the recent changes to pain were excessive pain makes you paralyzed instead of unconcious, wizards are able to cast spells while in this state. This is probably because people are still able to talk whilst paralyzed thus, letting wizards cast since speech = able to caste spells.

Yadda yadda, seems pretty not working as intended as an oversight.

**Comment by Doxxmedearly** [comment]
Wizard is no longer an available gamemode. Closing.
