### ISSUE TITLE
Toolbelts not displaying properly

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#11155]
Belts don't show up on a character's sprite anymore, just a bit of white elements at the back.

Example here.
![image](https://user-images.githubusercontent.com/52309324/107166443-484b9300-6973-11eb-9976-d681a599c563.png)

**Comment by Clem-The-Duck** [comment]
Sometimes items on the belts will show on sprite but not the actual belt sprite itself, this is happening to the sec belt as well for me
