### ISSUE TITLE
Golems getting infected via syringes

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#11168]
Been seeing golems getting infected via syringes. No idea how or why but there you go. Its a thing which is weird considering they're not flesh and blood?

![image](https://user-images.githubusercontent.com/60306280/107439930-ce332e00-6b6d-11eb-8a56-b7098cc1efd8.png)

**Comment by Doxxmedearly** [comment]
Addressed by #11164. You'll probably still get the message on injection but no infection will process.
