### ISSUE TITLE
Cargo accesories won't work with holsters.

### ISSUE THREAD

**Issue by Estutes** [Aurorastation/Aurora.3#11178]
When I try to put cargo equipment when wearing a holster on the jumpsuit, it won't allow to put it on as it is already occupied. This doesn't make sense as almost every holster and cargo webbing, drop pouch etcetera should be able to be combined with a simple holster.
I haven't tried other combinations that "make sense" but there's probably other combinations.
For further contact, I'm on discord Estutes#9189

**Comment by Doxxmedearly** [comment]
Not a bug. You can either have a holster, drop pouches, or webbing, but no combination of them. This is intentional behavior.
