### ISSUE TITLE
Improvised Radio Jammers are broken.

### ISSUE THREAD

**Issue by Butterrobber202** [Aurorastation/Aurora.3#11174]
Once upon a time, you could combine two signallers to make a radio jammer, this has somehow been broken. Now it asks you which side of the signaller assembly you'd like to use instead of becoming a jammer.

**Comment by Geevies** [comment]
just tested this, can't replicate, works as intended

**Comment by Butterrobber202** [comment]
> just tested this, can't replicate, works as intended

Can you do a step by step construction for me just in case I fucked it up?

**Comment by Geevies** [comment]
attach two signalers to eachother then click on them with a battery
