### ISSUE TITLE
Infinite welding tools when restocking

### ISSUE THREAD

**Issue by CompleteGarbage** [Aurorastation/Aurora.3#1117]
When restocking a YouTool with an advanced welding tool(and perhaps other types of welding tools, I am unsure,) something odd happens. The advanced welding tool _and_ a normal welding tool appear on the machine's inventory, which, to my knowledge, can result in infinite welding tools.

**Comment by CompleteGarbage** [comment]
It appears industrial welding tools stock as normal welding tools(also a bug, I believe,) but they don't duplicate anything when restocked.
Relevant image:
[https://i.gyazo.com/074c57bfb1d6ce59e75466ed835d380e.png]

**Comment by Geevies** [comment]
Fixed.
