### ISSUE TITLE
Right ear slot not changing character sprite after removing an item from it

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#11185]
If you have an item on the right ear slot, like the electronic earwear or a flower pin for example. Taking it out of the slot will still show the item on your sprite. It will remain like this until you put the headset on your left ear in the other ear slot, then back again.

**Comment by niennab** [comment]
Screenshot as an example. The clover pin isn't on my ear, but shows up on my sprite.
![2021-02-12](https://user-images.githubusercontent.com/56227386/107940498-99b5dc80-6f88-11eb-9184-f7a79e1e7c68.png)

**Comment by WickedCybs** [comment]
Might go hand-in-hand with this issue too, maybe. https://github.com/Aurorastation/Aurora.3/issues/11208
