### ISSUE TITLE
Random spawning dead greimorians are labeled as spiders.

### ISSUE THREAD

**Issue by Estutes** [Aurorastation/Aurora.3#11201]
It doesn't have much explanation. I think this is wrong. You may contacat me through discord.
![image](https://user-images.githubusercontent.com/69876530/108006457-cd7e1a00-6ffb-11eb-9587-2ad88d132aa2.png)

**Comment by WickedCybs** [comment]
Will be rectified in this PR https://github.com/Aurorastation/Aurora.3/pull/11213.
