### ISSUE TITLE
Dying while pointing results in a permanent point marker

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1125]
If you die while pointing at something (Say, as a mouse that gets matter-decompiled while pointing at a door), the red arrow pointing marker doesn't disappear and stays permanently.

**Comment by SierraKomodo** [comment]
Side note, this /may/ be related to #942 in that this is one way to get a 'target reticule' stuck on a sprite.

**Comment by FirinMaLazors** [comment]
Confirmed that this is still the case with the highlight-pointing system.
