### ISSUE TITLE
Body scanner console and sleeper UIs are broken

### ISSUE THREAD

**Issue by Tulenich** [Aurorastation/Aurora.3#11274]
To be more specific, it doesn't fit on screens with low resolutions. I use somewhat like 1360x768 and the upper side is off-screen, so i can't move the ui nor close it. The only way to close it is to go far away enough. 
![image](https://user-images.githubusercontent.com/77988543/108632576-c1251180-7480-11eb-87fa-abbd3b29cda7.png)
The round ID is cal-cC6Y. I talked to the admin but they didn't give me a proper answer (and i don't remember the ckey).
I think that the way to fix it is to make their UI a bit smaller.

**Comment by sheeplets** [comment]
Drag the bottom of the window all the way down to your taskbar and let go. It'll automatically resize the window to fit vertically, and you can resize it from there as you need to.

**Comment by Tulenich** [comment]
Maybe you can do that, but permanent solution would still be better. 
Also, I'm not sure if this actually works, since it's TGUI and not NanoUI.

**Comment by Tulenich** [comment]
And yes, it doesn't work. It just doesn't stretch out enough to reach bottom.
