### ISSUE TITLE
Loading crates and lockers on the cargo trolley creates odd behavior

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#1128]
![cargotug](https://cloud.githubusercontent.com/assets/11579997/20044826/37b0ba34-a483-11e6-9aa2-e3ee0df3e436.png)

When you move the cargo tug with crates or lockers loaded, the crates/lockers won't move from the place they were originally loaded.

**Comment by skull132** [comment]
Is this for all the crates, or for the ones spawned from cargo?

**Comment by Alberyk** [comment]
Any crate/locker, it seems.
