### ISSUE TITLE
Species nightvision works over cameras

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#11283]
If you activate taj or vaurca low light vision you'll be able to see into dark rooms over a camera. That's probably not intentional, I'd think.

**Comment by Geevies** [comment]
Fixed by https://github.com/Aurorastation/Aurora.3/pull/11416

**Comment by WickedCybs** [comment]
This was fixed by a recent PR, closing.

**Comment by WickedCybs** [comment]
Goddamn it Geeves.
