### ISSUE TITLE
You can get auto-traitor'd during crew transfer

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1130]
Yes I would call this an issue.

Auto-traitor can and will appoint traitors while the shuttle is coming to the station, while it is docked with the station, and while it is leaving the station, it's essentially impossible for traitors to do anything meaningful or entertaining during this time and mostly it encourages EoR grief and such.

**Comment by NonQueueingMatt** [comment]
Fixed
