### ISSUE TITLE
A plains tyrant will 'damage' a regular wall but completely destroy a reinforced one

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1133]
I'm not sure whatever dictates simple-mobs breaking down walls, but I hit a regular wall and it did about half the wall's health, but when I hit a reinforced wall it completely broke in one hit, so did about 3-4 other reinforced walls.

**Comment by Alberyk** [comment]
Nanako changed how mobs smashing walls work, this should be fixed.
