### ISSUE TITLE
Automatic CPR abruptly stops whenever mouth-to-mouth can't be performed

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#11346]
Whenever you try to do CPR on someone and either party is wearing a mask CPR will cut off abruptly after one compression and give you a big red message in the text window about needing to remove your or your patient's mouth covering to give mouth-to-mouth. If your patient is actively in cardiac arrest this is understandably super inconvenient and also probably going to kill them.

**Comment by VisVirific** [comment]
This should be fixed because of #14116, which re-organizes the Manual CPR a little bit so only Compressions shouldn't suddenly stop because of a mask
