### ISSUE TITLE
Two borers can take over a monkey.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#11357]
As it says on the tin. Two borers can infest a monkey (or others) at the exact same time. ONe of them then takes over the mind of the monkey, and the other can override that, effectively turning the first one INTO the monkey, wiping their borer status.

Also noticed that after being placed into a new borer, I screamed PLEASE and one of the nearby merc's mercing me said it, not me.

**Comment by Geevies** [comment]
borers forcing others to speak when they're outside a body is intentional, since they don't have a mouth
