### ISSUE TITLE
Speaking certain languages sometimes adds the language sign to your post without actually translating it.

### ISSUE THREAD

**Issue by Chen-Yakumo** [Aurorastation/Aurora.3#11363]
Tried to speak Ya'ssa. Had no issues for the majority of the round, but I eventually had to start adding a space after ",r" to speak in Ya'ssa. Failure to do so would result in 'Chen McCatTaj says, ",rrrShe is trrrrying to speak Ya'ssa.' rather than 'Chen McCatTaj mrowls, "She is trying to speak Ya'ssa.'

Admittedly, I am using full autohiss.

**Comment by MarinaGryphon** [comment]
Found the issue; it was detecting the revenantspeak key. It's *specifically* only Ya'ssa and *only* if it's followed by an S, because that detects the revenant key, `,rs`.
