### ISSUE TITLE
Native Tajaran Foot-Wear that spawn in fannypacks have no icon; can not be removed from fannypack.

### ISSUE THREAD

**Issue by Chen-Yakumo** [Aurorastation/Aurora.3#11364]
Spawned on the Odin with my Native Tajaran Foot-wear, which was placed in my fannypack instead of my feet, which had sandals. The icon state was set to "null" and Yonnimer had to change the icon so I could remove them, then spawn a new set for me.

**Comment by MarinaGryphon** [comment]
The path in the loadout is wrong; `path = /obj/item/clothing/shoes/tajara` instead of `path = /obj/item/clothing/shoes/tajara/footwraps`.
