### ISSUE TITLE
Toolboxes not spilling on simplemobs or windows

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#11375]
What the title says. Content keeps inside resulting in the fastest window and grill breaking tool we currently have. Not sure about all simplemobs but it did not spill on gremorians or however they are called nowadays.

**Comment by SleepyGemmy** [comment]
as far as i know, it's working as intended. i.e. to stop people robusting eachother, but its still usable for breaking in/attacking NPCs.
