### ISSUE TITLE
Cargo "Random Junk" Spawns Unusable, unfinished, and inappropriate items

### ISSUE THREAD

**Issue by EvilBrage** [Aurorastation/Aurora.3#1138]
As title. Some items are unusable due to not having a sprite, others are simply the "base" items for a category that were never meant to actually be in the game, and others still make no sense (thermal vision and other traitor items.) I hate to shout "sloppy coding" but it is.

**Comment by skull132** [comment]
Duplicate of #1131 

If you have specific items to add to that list, please leave a reply there.
