### ISSUE TITLE
Icarus Drone event resolves instantly

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#11401]
The malfunctioning Icarus drone event, where a bunch of hostile-type drones spawn around the station exterior, instantly resolves itself, sometimes even to the point where the end-announcement registers before the begin-announcement does.

![image](https://user-images.githubusercontent.com/22651198/110402537-2fe99980-8041-11eb-9276-7caebbceb08e.png)

**Comment by Doxxmedearly** [comment]
whoops forgot to list this in my PR. addressed by #11452
