### ISSUE TITLE
Changelog button does not work for some people

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1142]
Pressing the 'Changelog' button in game results in, literally, nothing happening (Aside from the button going from 'bold' to 'unbold' if there were new updates when you clicked it).

This seems to only be affecting certain people, such as myself and TheGreatJorge. Ice_dew reported the button worked properly for him.

**Comment by Bedshaped** [comment]
Could it be related to network connection?

Sometimes when I click the button it takes a good 5-10 seconds before the screen appears.

**Comment by skull132** [comment]
In a way, it is.

The game needs to send you resources (HTML, CSS, javascript, etcetera) files every time you connect. Until those files are downloaded, which is connection dependent, you cannot open the changelog.

**Comment by SierraKomodo** [comment]
Note that this was happening long after I connected, and everything else loaded fine when I clicked their respective buttons/links

**Comment by skull132** [comment]
Did clicking the changelog button a second time make it appear?

**Comment by SierraKomodo** [comment]
Nope, it was non-functional the entire round for me (At least for the first half hour in which I was trying)

**Comment by skull132** [comment]
Did you have the game up on a secondary screen, or had it up momentarily on a secondary screen during that round?

**Comment by SierraKomodo** [comment]
Don't believe so, always run the game on my primary monitor.

**Comment by skull132** [comment]
Well. Either that happened, or some other weird thing happened with IE.

Regardless, the procs used by Changelog are very basic and core to BYOND itself. So there's no fixing the fickleness of it.
