### ISSUE TITLE
Moving while attempting to put on a RIG/Hardsuit results in it being sent to the back-slot shadow realm

### ISSUE THREAD

**Issue by JohnWildkins** [Aurorastation/Aurora.3#11443]
Reproduction steps:
- Try to put on a RIG or hardsuit
- Move before it finishes
- Cry yourself to sleep attempting to pry off a suit that is not being "worn", in a back slot that is unoccupied (and can now take your backpack again, over top of the cursed suit), and can not be interacted with in any meaningful fashion short of admin deletion

**Comment by JohnWildkins** [comment]
This is related to #9760, probably.

**Comment by Geevies** [comment]
Fixed by https://github.com/Aurorastation/Aurora.3/pull/11459
