### ISSUE TITLE
Ghosts can name Combat Drones and other animals

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#11472]
While ghosting, I was able to right click and rename a combat drone (to combatt drone) that spawned in round.
![comatt](https://user-images.githubusercontent.com/56227386/111698240-e403d500-8836-11eb-878b-9be19c05d9af.png)

edit: I then tested it on a rat in maintenance and had success.
![comatt2](https://user-images.githubusercontent.com/56227386/111698925-b79c8880-8837-11eb-81e6-8458ed9de2c1.png)

**Comment by Geevies** [comment]
OooOOOoooOOOOoo spooky
