### ISSUE TITLE
As a ghost i can interact with some machines.

### ISSUE THREAD

**Issue by VikingPingvin** [Aurorastation/Aurora.3#1149]
As a regular observer ghost i was able to interact with some machines.

I can open up the APC interface, but can not interact with it due to access.

I can however interact with the shuttle console in mining and send it on it's way and back.

EDIT: Alberyk told me it may be because of admin perms?

**Comment by skull132** [comment]
Not a bug. All NanoUI interfaces can be viewed as a ghost. And having
+ADMIN enables you to interact with them.

Basically to allow adminghosts to fix things without needing to BST
