### ISSUE TITLE
ERT doesn't get certain equipment that's rather important

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#115]
ERT doesn't get access to void suits or any ammo boxxes for their weapons, which is a severe oversight considering the syndicate ops get access to both. Provides a bit of a balance issue, and also severely cripples ERT's ability to equip themselves (Cant wear backpacks with the hardsuit rigs).

**Comment by Alberyk** [comment]
ERT has magazines for their weapons. They just don't have access to voidsuits, but, that is probably not a big issue when they have plenty of hardsuits.

And yes, there is more than enough ammunition in their armory; https://i.imgur.com/oJ8kZez.png

**Comment by skull132** [comment]
ERT equipment isn't crippled, and they're pretty much right as rain.
