### ISSUE TITLE
Broken Recipe Megalist (Cooking)

### ISSUE THREAD

**Issue by thatdanguy23** [Aurorastation/Aurora.3#11535]
A list of recipes from the wiki that don't work as advertised, or have other problems. This is likely to be expanded upon once I find others!

> **Roburger:** Robot heads, with or without flashes, cannot be added to bowls/plates/utensils in order to be mixed. Clicking the bun and robot head on each other does not work, either.
> **Ghostburger:** Ectoplasm cannot be added to bowls/plates/utensils in order to be mixed. Clicking the bun and ectoplasm on each other does not work, either.
> **Clownburger:** Neither of the clown mask variants can be added to bowls/plates/utensils in order to be mixed. Clicking the bun and masks on each other does not work, either.
> **Mimeburger:** The beret cannot be added to bowls/plates/utensils in order to be mixed. Clicking the bun and beret on each other does not work, either.
> **Classic Hotdog:** Mixing corgi meat and a bun in a bowl/plate/utensil makes a burger, not a hotdog.
> **Apple Pie:** Currently not functioning. When an apple and flat dough is put together in an oven tray and cooked, the apple does not bake, and the flat dough becomes a flatbread. If done on the stove, the items become pan-fried.
> **Spell Burger:** Wizard hats cannot be added to bowls/plates/utensils in order to be mixed with a burger. Clicking the burger and hats on each other does not work, either.
> **Candied Apple:** Mixing water and sugar makes ice, regardless of the order they are placed in the mixing bowl. Making caramel sugar and trying that instead also doesn't work.
> **Mint:** No microwaves, and the recipe doesn't work in any of the other machines, nor with generic mixing.
> **Nomad Kabob:** Uses the generic kabob sprite instead of the nomad_skewer sprite that's in the icons. Unsure if intentional. Works fine otherwise.

**Comment by MarinaGryphon** [comment]
> Mixing water and sugar makes ice, 
You did this on a test server, right? That's due to the secret chem system; delete `config/secretchems.json` and try again.

**Comment by MarinaGryphon** [comment]
Also, the roburger, ghostburger, clownburger, spellburger, and mimeburger have been removed; they don't have recipes.

Mint can be made with 5u sugar and 5u frostoil in a saucepan.

> Apple Pie: Currently not functioning. When an apple and flat dough is put together in an oven tray and cooked, the apple does not bake, and the flat dough becomes a flatbread. If done on the stove, the items become pan-fried.

Requires 5u sugar.

The hotdog and nomad kabob issues are verifiable and I'm working on fixes.

**Comment by thatdanguy23** [comment]
> Also, the roburger, ghostburger, clownburger, spellburger, and mimeburger have been removed; they don't have recipes.
> Mint can be made with 5u sugar and 5u frostoil in a saucepan.
> Apple Pie requires 5u sugar.

Edited the wiki to reflect this!


> The hotdog and nomad kabob issues are verifiable and I'm working on fixes.

Perfect, glad I could help bring them to attention!

**Comment by Doxxmedearly** [comment]
Addressed as above
