### ISSUE TITLE
Bones automagically heal (?when splinted perhaps?)

### ISSUE THREAD

**Issue by listerla** [Aurorastation/Aurora.3#11569]
![Screenshot 2021-03-29 160557](https://user-images.githubusercontent.com/57296132/112990608-419bf980-9134-11eb-9d25-4e8a0cf3dafa.png)
![image](https://user-images.githubusercontent.com/57296132/112990652-4c568e80-9134-11eb-8182-02257a5226cf.png)

In a round, I had received the bonebreak messages and been scanned to show broken bones. I was splinted and bandaged on the site of the event, and due to a hectic time only went to medical 20-30 minutes later. By the time I had arrived, a Zeng-Hu scanner and self-examine both indicated no broken bones, and LOOC confusion ensued.

**Comment by Lordnesh** [comment]
ckey: lordnesh
Game ID: cbk-dE6u
patient came in with fractured skull. Administered Butazoline (maybe more, that's all I remember), and started to hear bone snapping as the bones literally knitted themselves back together again. First scan showed fracture in skull, second did not. No surgery was ever done.
