### ISSUE TITLE
Facial Reconstruction can change languages and accents

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#11572]
You can edit the languages and accents of other people simply by cutting open their face and reconstructing it.

**Comment by Geevies** [comment]
Plastic surgery is set to be able to do that, according to old-code. Whether this is good or not is up to the maintainers, though.
![image](https://user-images.githubusercontent.com/22774890/113127352-f4de1e80-9218-11eb-8c9e-44dcee6e1a3b.png)
