### ISSUE TITLE
Pathogenic incubator going through negative values

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1159]
Not too sure what caused it, but at some point, the incubator decided it wanted to use virus food regardless of there being any left.

**Comment by Aurum22** [comment]
Was there a whole number of virus food in the machine? I believe having to deal with decimal components causes issues with some virus machinery sometimes.

**Comment by Pratepresidenten** [comment]
Not that I saw in particular. But It might have happened as I put in a beaker filled with virus food while the machine was still on. Might cased an issue as it tried to refill and spend resources at the same time.

**Comment by skull132** [comment]
Closed due to issue clearance.

Not confirmed.
