### ISSUE TITLE
Wallets with custom names default to their original title after you insert an ID card into them twice

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#11594]
Put your ID in, take it out, and then reinsert it once more.

It's kind of bumming me out that my Gucci Horsebit 2455 wallet purse keeps doing this, how else do you expect me to show off my clout?

**Comment by dirrgang** [comment]
This is related to #11584 - namely any item that has a customized name but at some point in its existence modifies its name and reverts it by using the initial(name) proc.

The appropriate fix for this might be more elaborate than the band-aid which is just adding a original_name var, it's on someone higher up to decide how this is to be fixed.
