### ISSUE TITLE
Instruments (violins, pianos, etc) cause game-breaking amounts of lag

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora.3#1161]
As it says on the tin. To my knowledge, this is why Baystation originally removed the piano from the bar and made instruments inaccessible to players.

With the recent cargo update, it is now possible to acquire them from the random spawns, however they still cause massive lagspikes to anyone within broadcasting range of the instrument while it is playing, up to, in some cases, people having issues holding a stable connection.

**Comment by skull132** [comment]
Not exactly fixable without spending a decent amount of time DLL writing. A basic solution would be to scrap the current system and to mirror what other servers have done to achieve TTS: feed notes in string form to a .dll, have that .dll compose and compress an .ogg file, feed that .ogg file to players hearing the composition.

Impact would be considerably smaller as it's only 1 file per composition, as opposed to a file per note that gets replayed for days.

But this refactor would be relatively hyuuge, so most likely we'll remove the instruments instead.
