### ISSUE TITLE
Blood bags bitten by vampires don't display descriptions properly

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1164]
![untitled3](https://cloud.githubusercontent.com/assets/19973802/20341577/a4ad0dfc-ac4b-11e6-96ca-b5982ddb77ed.png)

Dunno if that's meant to be red or whatever.

**Comment by skull132** [comment]
Unclosed or bad HTML. Reee.

Should most likely be `<span class='notice'>There are teeth marks on it.</span>`, but the class notice is missing. Unsure about the closing tag.

**Comment by Bedshaped** [comment]
WONT FIX, thanks

**Comment by Bedshaped** [comment]
Nah I'll fix, fix incoming.
