### ISSUE TITLE
Message Monitoring console; certain programs broken (for AI atleast)

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#11701]
Currently playing as AI (traitor). I find that these programs inside it fails to load:
2. View Message Logs
7. Send Admin Message
-- both probably the most important ones for a traitor wanting to mess through this system.
In both cases I have to de-authenticate and authenticate again to get to the main menu

**Comment by Karolis2011** [comment]
Can't AI just access admin mode on Chat Client?

**Comment by NerdyVampire** [comment]
> Can't AI just access admin mode on Chat Client?

Ah that is probably why the programs were bworked, the new chat client thing. I suppose it is possible. In that case the programs should probably be removed from the message monitoring console, if they aren't relevant anymore? I'll try your suggestion out in my next round.

**Comment by NerdyVampire** [comment]
> Can't AI just access admin mode on Chat Client?

So admin mode does allow me to see other peoples chats, but it does not allow me to send an Admin message like the Messaging Console, I think that's the only true feature I'd be missing if we replace the monitoring console entirely.

**Comment by Sgtsammac** [comment]
Still broken for human players too.

![](https://cdn.discordapp.com/attachments/741526983015530506/850452401689460756/unknown.png)

From this menu, if I click option 2 or Option 7 I just get a blank screen that I then have to unautheticate and reautheticate but still doesn't work.



![](https://puu.sh/HMhHS/b9a785c190.png)
