### ISSUE TITLE
Flying Demons with Knives Are Immortal?

### ISSUE THREAD

**Issue by CrowOfBourbon** [Aurorastation/Aurora.3#11757]
You can punch a vicerator, but it takes no damage. 

Which, begs to differ if the problem is the fact that we can PUNCH them, or the fact that they're immortal to fists. 

Alternate suggestion: Remove them from cargo crates. Because 4mins into a low pop round as a technie and dying to a robot you can't even do harm to barehanded is uh, not fun.

**Comment by Butterrobber202** [comment]
> Alternate suggestion: Remove them from cargo crates. Because 4mins into a low pop round as a technie and dying to a robot you can't even do harm to barehanded is uh, not fun.

for the record, almost anything in SS13 can be used as a weapon, and almost everything is better than your bare hands.

**Comment by Doxxmedearly** [comment]
Duplicate report of  #11879
