### ISSUE TITLE
Clicking a Locker somehow will make Cyborgs place their Components inside...

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#1176]
I've had this bug happen twice. Once as a SEC Module Cyborg, I accidentally placed my 'Handcuff' dispenser into a Locker. It came back that time, though. Then it happened again when I accidentally as a Medical Cyborg managed to put my Chemical Gripper into a Patients Locker, and couldn't get it back except by resetting. The Roboticist was able to pick up the Gripper and throw it, but I don't know if it had its normal uses. This is a crippling bug when it does happen, because it's like getting a limb cut off, imagine if an Engineering Cyborg lost their Wrench this way.

With Admin allowance, I attempted to reproduce the bug, I was unable to. But it's happened to me in the past, too... If I get anymore information on it, i'll post here. It's not limited to one Module, I think it applies to all Modules, and I think it might have something to do with opening and/or dragging containers.

**Comment by SierraKomodo** [comment]
As a note, the locker I witnessed this happening on was one that can be locked. The bottom-middle patient locker in the medbay patient room.

**Comment by Alberyk** [comment]
As the roboticist that fixed said cyborg, bug confirmed.

**Comment by SirFruitcakes** [comment]
The handcuff dispenser was placed into a locked Locker too. That might be a reoccuring theme.

**Comment by NanakoAC** [comment]
lohikar reports fixed by baymerge
