### ISSUE TITLE
Reoccuring infections in Vaurca

### ISSUE THREAD

**Issue by Lordnesh** [Aurorastation/Aurora.3#11766]
Game ID: cbJ-dlh3
infections for Vaurca do not get removed with Thetamycine. They keep coming back.

**Comment by Doxxmedearly** [comment]
Vaurca do not process medications differently from humans so any additional information about the situation would help greatly.

**Comment by Lordnesh** [comment]
> 
> 
> Vaurca do not process medications differently from humans so any additional information about the situation would help greatly.

In my experience, and what has been reported by others, is that infections reappear after being treated. I am afraid I do not have any more information, other than that.

**Comment by Doxxmedearly** [comment]
Alright, I'll look into it
