### ISSUE TITLE
being exposed to phoron as an IPC causes burn damage 

### ISSUE THREAD

**Issue by Smithead** [Aurorastation/Aurora.3#11807]
#11772 

IPCs take burn damage after being exposed to phoron.

During a round while acting as an antagonist, my character, a Xion Industrial Frame detonated the phoron supply tank. Phoron flooded the asteroid for a brief moment, which contaminated my character's clothes, and caused severe burn damage to all limbs.

If this is a feature, some QoL changes to notify players their gear has been contaminated may be nice.

[relevant screenshot](https://gyazo.com/467f0cb916ac204aaac1326844577bb9)

**Comment by Doxxmedearly** [comment]
Will be resolved by linked PR
