### ISSUE TITLE
More nondescript logs

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#1181]
http://puu.sh/stDoT/d01eadf769.png

This appears when someone is attacked while grabbed, I think?

**Comment by Alberyk** [comment]
When someone stomp on them, in fact.

**Comment by printer16** [comment]
Can not replicate/more information required. (Picture is no longer valid.)

**Comment by CakeIsOssim** [comment]
This was fixed a while ago anyway, I think. I will close it when I find out.
