### ISSUE TITLE
Account Numbers Borked. Not sure if a permanent issue.

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#11823]
![image](https://user-images.githubusercontent.com/55027366/116905764-b4225c80-ac3f-11eb-8bd9-eb5f2ea66f19.png)

**Comment by JohnWildkins** [comment]
SSeconomy generates a random number from 111111 to 999999 and then iterates it randomly, so if it starts near the very tippy top it becomes 7 digits and then byond gets very sad :(
