### ISSUE TITLE
Unable to remove wristbound.

### ISSUE THREAD

**Issue by Lordnesh** [Aurorastation/Aurora.3#11839]
round ID: cbS-dF6T

Description: When moving wristbound PDA from wrist to hands, and then back to wrist, sometimes the green overlay that indicates the item can fit in the slot remains. When this happens, the PDA can no longer be removed by the player.

Testing: Ahelped and had admin remove it for me. Was able to interact with it, but green overlay persisted. Reconnecting removed the green overlay.

Notes: Reconnecting may or may not solve the issue all together, did not test. Did not try closing window entirely. Issue seems to occur when moving the entity quickly from my experience.

**Comment by Shadow-Quill** [comment]
This is a graphical bug that happens sometimes with byond.
