### ISSUE TITLE
Technomancer regen aura and instability rapidly killing

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#11842]
It's probably intended that regen aura starts killing you after a while, though it seems to either massively build up instability or start rolling extremely deadly events like MSOF a bit early.

Used it during a round and I noticed my heart quickly stopped, then apparently I took massive toxin damage in the span of a few seconds according to dchat. Getting about eighty dumped instantly.

Could have been more at play maybe, but unsure. I can't recall what my instability was at before I used it. I don't think this was my own user error due to how drastic it was.

round ID: cbT-aqnK

**Comment by NonQueueingMatt** [comment]
Regen aura doesn't have any special code that inflicts damage. I reduced the lethal instability effects which should make it better.
