### ISSUE TITLE
Corndog Conundrum

### ISSUE THREAD

**Issue by Mrfilms** [Aurorastation/Aurora.3#11905]
There is an issue with the recipe for making corn dogs. The wiki lists the recipe as "Fry 1 Sausage, 1 batter,", however, the code below shows that the recipe also contains "corn".

```
/decl/recipe/corn_dog
appliance = FRYER
items = list(
     /obj/item/reagent_containers/food/snacks/sausage
 )
fruit = list("corn" = 1)
coating = /decl/reagent/nutriment/coating/batter
result = /obj/item/reagent_containers/food/snacks/corn_dog
```
As you can see, there is ambiguity in the code as to which food item needs to be battered. I have tested the following alternatives in game (ID cb3-dhMI):

- corn with batter on it + sausage
- sausage with batter on it + corn
- corn + sausage + batter

All three of these failed to result in the desired outcome of producing a corndog - they merely fry their constituent ingredients as one would expect if one were to be frying them separately (i.e. sausage with batter on it fries into battered sausage, corn fries into 'deep fried corn', etc) . 
I interacted with dev **arrow768** about this issue via ahelp and he recommended that I fill out a bug report.

**Comment by deGurkin** [comment]
Had the same issue
Was very upset.
