### ISSUE TITLE
Augment - Integrated Eye Sensors bug

### ISSUE THREAD

**Issue by Lordnesh** [Aurorastation/Aurora.3#11937]
Round ID: cb9-dauQ
As a G2 unit with this augment, I am unable to see the job icon for medical staff.
![image](https://user-images.githubusercontent.com/70110584/119050977-3329cb80-b988-11eb-92ba-40bc83345e71.png)

**Comment by Casper3667** [comment]
fixed by https://github.com/Aurorastation/Aurora.3/pull/12116
the jobs had no associated sechud icons.
