### ISSUE TITLE
Issue with Dionae languages

### ISSUE THREAD

**Issue by Rotharia** [Aurorastation/Aurora.3#11940]
Dionae cannot understand nral'malic or sinta but can speak it. Issue has persisted across multiple rounds. When I brought it up to others they claimed they had no such problems so I think it's specific to me ckey: Rotharia, making this at the suggestion of Mel.

![image](https://user-images.githubusercontent.com/19884004/119148892-f4912100-ba1a-11eb-9794-c58d2c616117.png)

**Comment by Geevies** [comment]
The diona here is speaking Sinta'Azaziba, but the unathi are speaking Sinta'Unathi. do you have any screenshots of Nral'malic being spoken?

**Comment by Rotharia** [comment]
I do not, it may be a misunderstanding on my part then. I apologize.
