### ISSUE TITLE
Lunchboxes are spawning with NOTHING in them

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#11961]
As above. When you spawn with a lunchbox and selected foods, nothing actually spawns inside the lunchbox. No food, no water. May or may not be related to https://github.com/Aurorastation/Aurora.3/issues/11741

**Comment by WickedCybs** [comment]
You need to reselect the food for it to spawn again.

 It's due to this PR https://github.com/Aurorastation/Aurora.3/pull/11848, that adds a utensil option, and extra food.

**Comment by Doxxmedearly** [comment]
@Melariara Cybs is correct. Not much can be done about it. Just reselect. If it's still not working message me and I'll reopen this.
