### ISSUE TITLE
Bodies dropping out from inside closed stasis/bodybags

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1199]
Not sure what triggers it, but whenever you drag a stasis/bodybag around, the body inside sometimes tends to just fall out without the bag being opened at any point.

**Comment by Pratepresidenten** [comment]
Necro time! I found out what causes this. If an airlock closes when a body/stasis bag, the contents pop out.

**Comment by remona-minett** [comment]
This is ancient, but my best guess is that a body fails to trigger whatever prevents the airlock from crushing living entities, but it still does the crush damage to the body, somehow removing it from the bag? Perhaps either making the airlocks acknowledge corpses in the doorway or making them immune to crush damage (seems less favorable) would solve this?

**Comment by fernerr** [comment]
Fixed by #10608
