### ISSUE TITLE
Cyborg cannot reattach organs

### ISSUE THREAD

**Issue by Yakunan** [Aurorastation/Aurora.3#12022]
![Borg org](https://user-images.githubusercontent.com/77746601/121556215-fba4c100-ca13-11eb-86dd-f8a6d39e54be.png)

**Comment by Yakunan** [comment]
Dont have much else to add.... Take the organ into your gripper and try to place it back into the chest

**Comment by Lordnesh** [comment]
https://github.com/Aurorastation/Aurora.3/issues/10321
