### ISSUE TITLE
Steel sheet spawning with the wrong sprite in the bar.

### ISSUE THREAD

**Issue by HouseOfSynth** [Aurorastation/Aurora.3#1205]
So a steel sheet spawned in the bar with this sprite: https://i.gyazo.com/9f04c1538ea5b05d97359b1551106017.png

It looked like this when examining it: https://i.gyazo.com/8acaff62f4d5a08a67315b19d9f8969c.png

**Comment by ToasterStrudes** [comment]
Think it was just something for the Christmas rotation, Steel sheets were being re-textured to look like the skin of corgi/lizards. Probably just easier to replace the sprite than to make a specific item for fluff.

**Comment by LordFowl** [comment]
Fixed.
