### ISSUE TITLE
IPC jaw breaking with no jaw to break

### ISSUE THREAD

**Issue by courierbravo** [Aurorastation/Aurora.3#12078]
Bug: IPC's break jaw when taking fall, unable to repair
Game ID: ccE-ddyK (character: NT-ARC)
Its happened to me a couple times now. With both a Gen 2 industrial frame and a Xion frame

Leaves me unable to really talk while playing, as anything I say in anything but AEL is horribly slurred and has a good chance of knocking me down in "pain"

in round incident happens mid to late round, shortly after ship debris fall and bust open cargo warehouse

**Comment by Doxxmedearly** [comment]
@JohnWildkins seems to be an issue with the jaw joint?

**Comment by EmperorJayJay** [comment]
Hey I'm bumping this. Just happened to me today.

![image](https://user-images.githubusercontent.com/107105300/172565552-1572db76-30bd-4a90-bc61-c7b87991722d.png)
