### ISSUE TITLE
Exosuits are invulnerable 

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#12110]
At the moment, exosuits cannot really be destroyed. They can be unloaded on with an entire armory and not show any signs of damage. Only time a part did take damage was when alb applied 400 straight brute with admin tools.

Not sure why this is happening now. Can be seen in round ID: ccK-c7Gv.

**Comment by Alberyk** [comment]
Attacking any mech causes this runtime

runtime error: 
[18:40:35]Undefined operation:  / 100
[18:40:35]proc name: apply damage (/mob/living/heavy_vehicle/apply_damage)
[18:40:35]  source file: mech_damage.dm,91
