### ISSUE TITLE
industrial IPC EVA overheating when it should not

### ISSUE THREAD

**Issue by SebkillerDK** [Aurorastation/Aurora.3#12164]
right, so i was EVA for a bit as my industrial G1 heph IPC. when i noticed that my temperture was slowly rising, and kept rising, despite the fact that i was walking, and not wearing any extra gear. i had a suit cooler on and active in my backpack slot.  despite this, i eventually overheated and began burning. 

i have been EVA before with full gear with no issue.

**Comment by RazorXLVII** [comment]
Bumping.
Was in EVA for a few minutes with my Industrial G2 IPC. My temperature was slowly yet progressively rising. I was walking and was not wearing any armor outside of my Idris coat. I had a suit cooler on my backpack slot and I ensured that it was toggled on. Taking it off in space, switching it offline and online and putting it back did not fix the issue. Shortly after I overheated and began burning.
