### ISSUE TITLE
AIs cannot un-electrify doors

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#12201]
As implemented when the feature to electrify doors as a non-antag AI was removed, they were given the option to be able to reset an electrified airlock.
This option no longer works as it prints "Your programming prevents you from electrifying the door." instead of resetting the airlock.

**Comment by AnselmKonrad** [comment]
Stationbound also have this issue. I understand not being able to _electrify_ a door but we cannot reset it back if its electrified. meaning only engi borgs can fix it by doing it manually by hand.
