### ISSUE TITLE
Dev: Devouring doesn't display msg to target

### ISSUE THREAD

**Issue by Bedshaped** [Aurorastation/Aurora.3#1220]
![https://puu.sh/sT0hZ/fd56a8e1f1.png](https://puu.sh/sT0hZ/fd56a8e1f1.png)

**Comment by NanakoAC** [comment]
What was the victim at this time?

**Comment by Alberyk** [comment]
A resomi

**Comment by NanakoAC** [comment]
Unable to reproduce in live testing. need more info

**Comment by NanakoAC** [comment]
probably related to previous visible message bugs
