### ISSUE TITLE
Borgo sprite components freeze, primarily text bubbles.

### ISSUE THREAD

**Issue by AnselmKonrad** [Aurorastation/Aurora.3#12254]
How do I reproduce this? Unfortunately I dont know despite this being a very consistent issue I tend to have sometimes, primarily when engaging in heavy conversation / interaction with GUIs. So perhaps thats an indicator.

My chat bubble will get stuck as if i am never-endingly typing, even when moving. I use the Venus Drone sprite,  This is particularly annoying when trying to speak to someone as they do not know when you are going to speak, or not speak.

One time, I have had my maintenance hatch stuck open as well, but this was particularly much more rare, and only occured one time. I have seen another cyborg have this happen as well, but not multiple. 

Can I suggest a button that refreshes a sprite entirely for stationbounds?

**Comment by AnselmKonrad** [comment]
![image](https://user-images.githubusercontent.com/86074513/130130224-3236f4b4-4793-4d6a-8a60-6176dd164030.png)
I primarily refer to this. I know you cannot see my full screen, but rest assured there is no text box to input anything. This is prevalant. This chat bubble does not go away, any hopes on seeing a sprite reset button for borgo?

**Comment by Ben10083** [comment]
Work-around https://github.com/Aurorastation/Aurora.3/pull/12417

**Comment by mikomyazaki** [comment]
Has been fixed by Geeves at some point.
