### ISSUE TITLE
Flavor Text URL No Longer Works

### ISSUE THREAD

**Issue by UnknownMurder** [Aurorastation/Aurora.3#1226]
1. Open up Flavor Text
2. Open up General
3. Put the URL into General
4. Click [DONE]
5. Test your Flavor Text.
6. 
This is the result
![image](https://cloud.githubusercontent.com/assets/7517616/21291247/58bc80e8-c49d-11e6-88f5-7cb095cbfbdc.png)

**Comment by Arrow768** [comment]
What was the url you put in ?⁣​

**Comment by Alberyk** [comment]
That is because the link was bigger than what could be displayed when examining.

**Comment by skull132** [comment]
Reference what Alberyk said, that's what happened. Use puush or some similar method of shortening the URL down, or place it earlier in the FT.

Not a bug, coupled with won't fix if we ever wanted to make flavour text showcase being "smart". Though, the issue with that would be simple: it'd be open to abuse.
