### ISSUE TITLE
Canister UI Open/Close button pair toggles rather than switches.

### ISSUE THREAD

**Issue by Talkarcabbage** [Aurorastation/Aurora.3#12310]
Clicking the open button, on a canister that is already open, will close it. Likewise, clicking close twice will bring a canister from open, closed, back to open again. Given that the UI lags updates, that could result in flooding a room with gas because of it.

Previously, each button could be pressed infinitely many times and would appropriately only close or open the valve, which is closer to the expected behavior.

**Comment by FluffyGhoster** [comment]
UI was reworked, this should no longer happen
