### ISSUE TITLE
Job age restrictions not working

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#12327]
At the moment you can be an eighteen year old HoP or something for example. Game isn't respecting the minimum age requirementa for whatever reason.

**Comment by Shadow-Quill** [comment]
Can't reproduce on private server.

**Comment by WickedCybs** [comment]
Yeah this isn't an a issue anymore, I might have mistaken this for something separate where say, a Zhan could be captain. Not sure. Oh well.
