### ISSUE TITLE
Diona Check-light-level Command Not Working

### ISSUE THREAD

**Issue by Zer0Winds** [Aurorastation/Aurora.3#12338]
When using the Check Light command for Diona, you get the message...
"Our response node is damaged or missing, without it we can't tell light from darkness. We can only hope this area is bright enough to let us regenerate it!"
...since the organs for Diona were removed, they can no longer use the command, as they actually just do not have the Response Node now.

**Comment by remona-minett** [comment]
I don't really understand why they were removed in the first place, but if the rest of the organs mechanically did nothing, wouldn't the simplest solution be to just re-add the response node and nothing else, if the organs need to stay gone?
