### ISSUE TITLE
Dev: Donut boxes do not display how many donuts they have on sprite

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1235]
![image](https://cloud.githubusercontent.com/assets/19973802/21292597/29bd6590-c570-11e6-95de-67dbb1e5a2a8.png)

Invisible donuts on the test server.

**Comment by NanakoAC** [comment]
cigarettes, eggs, candles, crayons and a couple of other things use the same code, will need to look into them all

**Comment by Alberyk** [comment]
I got this.
