### ISSUE TITLE
Vaurca not resistant to radiation or shock

### ISSUE THREAD

**Issue by sleepywolfie** [Aurorastation/Aurora.3#124]
Vaurca are not resistant to radiation or shock, as they were in old code and lore-wise.

**Comment by skull132** [comment]
https://github.com/Aurorastation/Aurora.3/blob/master/code/setup.dm#L665

We exceeded the maximum amount of race related flags by 1. This is why it's not working. Either one flag needs to be removed, or some other alternative solution found. (Maybe check if species name = "Vaurca"?)
