### ISSUE TITLE
VAMPIRE URGENT Bugs

### ISSUE THREAD

**Issue by Ninshuu** [Aurorastation/Aurora.3#12466]
After drinking blood you are awarded with two types of mobility skills. Toggle Veil walking and Veil step. 

Toggling veil walking not only cost way to much blood but to keep it open also cost just as much.
Veil Step skill is complete inaccessible dispute opening a window once use of the verb is applied however it does not allow for any teleports at all.

Summoning Bats- also a expensive move that cost way to much for what it’s useful for. Only usable as a means to detours advancements however they attack dmg is so weak and only 2 comes out. No even worth being in the game

Berserk Mode

grabbing while in beserk mode will almost always bug the player, you will be locked in place until you drop whatever in your hand even if it’s nothing. Same happens when using grapple verb

grabbing victims sometimes won’t allow for aggressive transition while in beserk mode

**Comment by Casper3667** [comment]
> Veil Step skill is complete inaccessible dispute opening a window once use of the verb is applied however it does not allow for any teleports at all.
Veil step works by right clicking a dark place and picking the option to do it from there.
