### ISSUE TITLE
Say/Emote/PDA verb windows have no cancel function

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#125]
To explain what I mean, for example, this is how the OOC verb works: http://puu.sh/n6pdx/b73c4b5602.png

Would be nice to be able to hit Escape or be able to cancel out the say function again, in case of typos or bad sentence structure.

**Comment by skull132** [comment]
Does leaving them empty not cancel?

Usually, sending an empty string is caught by the code, and the verb
returns (cancels).

Since it's using byond's core systems, there ain't too much we can do. I
think, I forget if there are input procs with a cancel button.

**Comment by OneOneThreeEight** [comment]
Leaving them empty does cancel it out.

As far as I know it's something to do with Bay, with any of the tg bases they have cancel buttons for the say/emote/PDA function.

**Comment by skull132** [comment]
Bay12 uses DM's input() proc for it. There is shit with a cancel button, but I forget. It might also be custom coded, TG's.

**Comment by NanakoAC** [comment]
fixed by #670
