### ISSUE TITLE
/me doesn't send in the dark even if the observer can see them

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#1252]
/me doesn't send in the dark even if the observer watching the emote has nightvision goggles / mesons / optical sensors etc.

**Comment by NanakoAC** [comment]
@darkrising After some thought, i've come to the conclusion that it's not feasible to make this work correctly. 

I could do it, it wouldn't be complicated. but it would require a lot more processing for each emote. 100% more for each reciever, stacking additively. That's not good.

What i CAN do however is an alternate solution that - although it still doesnt work correctly - might be preferable to you. I can remove darkness from the equation and make visible emotes always seen in the dark, regardless of any vision.

**Comment by darkrising** [comment]
@NanakoAC That would probably be for the best. For example a vampire in a vamp round might be standing in the shadows doing some high speed /me'ing before they're shot to death.

**Comment by Geevies** [comment]
Nothing we can do. Use say "!cries.", it's a verbal version of /me that works in the dark.
