### ISSUE TITLE
Dev: Unsafe Pressure indicator removed(?), does not appear

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#1257]
Little/No Pressure:
https://puu.sh/sUBAg/59660187c8.png

Overpressure:
https://puu.sh/sUBNE/ca6fae5897.png

But there's still an O2 indicator.

**Comment by skull132** [comment]
Possibly due to life(). Will look into it.

**Comment by skull132** [comment]
Cannot replicate: https://puu.sh/sYVVt/dbb5cd2434.png

Code seems to be working fine on both back and front end counts. Also works on overpressure. Any further details? Can you try to replicate it on the current test server?

**Comment by CakeIsOssim** [comment]
I was able to replicate it on both a private test server and the developer test server. I didn't have any debug logs or anything open at the time so I don't really have any more details.

**Comment by skull132** [comment]
A fix was pushed. If it's still around, report it again or ping me.
