### ISSUE TITLE
Issues with the Chess board

### ISSUE THREAD

**Issue by Leakbang** [Aurorastation/Aurora.3#12613]
I see a few issues have been opened on the Chess board lag. I suppose that is not the biggest issue with it right now as there are bigger issues plaguing it.
1. Bad colors. Chess has always been white vs black. black vs red feels really out of place. Also the background is blue which makes it even uglier. The colors really don't go with each other. Here are a few screenshots of good looking chess boards:
![image](https://user-images.githubusercontent.com/51197897/137041659-d54b397d-93da-4572-9ad5-aaa91bb0f6e6.png)
![image](https://user-images.githubusercontent.com/51197897/137041717-27b7aa6a-c068-4dfd-b810-a9704ce3c9a5.png)
Images taken from Lichess. It's a FOSS chess platform.
Another big issue with the chess board is the 'last move highlighting'. The way it was done in-game, was really confusing. I thought that the game had bugged out and my pieces are duplicating.
Here's a screenshot of how it's done on Lichess
![image](https://user-images.githubusercontent.com/51197897/137041967-a06edb60-e3d9-45e6-9336-403ccb7cfd08.png)
2. The opponents can move each others' pieces and there is not any visual feedback for the opponents to realize.
3. Restarting the match is impossible, I had to manually delete all of the pieces to be able to play again.

There are a lot of other issues that I could list about the chess board right now, but really, it's pretty bare bones right now.

**Comment by Ben10083** [comment]
This is no longer an issue as this code has been replaced right?
