### ISSUE TITLE
AIs can't open windoors still.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#12694]
Last fix fixed Cyborgs and Androids, but didn't fix AI. AI still cannot interface with Windoors at all, unfortunately.

**Comment by martinlyra** [comment]
This is possibly an access-related issue, because AIs can open windoors that don't have access requirements.

**Comment by Casper3667** [comment]
fixed in https://github.com/Aurorastation/Aurora.3/pull/12685
