### ISSUE TITLE
Can't Make a Burrito

### ISSUE THREAD

**Issue by BileGH** [Aurorastation/Aurora.3#12696]
Mixing tofu/2x meatballs, 1u spice and Tortilla doesn't make a burrito no matter how you put it.
Steps:
Make tortilla
Make tofu
Added both to a plate, nothing
Added both to a bowl, nothing

SampleTex informed me to make a bug report

**Comment by martinlyra** [comment]
Did you drag the plate/bowl's sprite onto your character after putting the ingredients in?
