### ISSUE TITLE
Tendon and Necrotic Organ repair surgery do not repair their organs.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#12702]
Patching a tendon with the fix-o-vein doesn't do anything. The bar appears but it doesn't actually patch.

With the necrotic organ repair, I only tried repairing eyeballs so I'm unsure if its all organs but steps for necrotic removal are ATK, Scalpel.

Not every part of the eyeballs could be saved; some dead tissue had to be removed, making it more susceptible to future damage.

You finish treating damage within UNFORTUNATE PATIENT's head with regenerative membrane.
This organ is still dead! You must remove the dead tissue with a scalpel!

The eyeballs is too damaged. Repair it first.
You aren't sure what you could do to UNFORTUNATE PATIENT with the scalpel.

It just cycled through this constantly.

**Comment by VisVirific** [comment]
Found the reasons for the Tendon not healing and the Necrotic Organ Repair being funky.

**Tendon Healing**
_code/modules/surgery/other.dm_ in the _fix_tendon_ surgery, the processes use **tendon.heal()** while everything else that can actually repair the tendon uses **tendon.rejuvenate().**
**Proposed solution:** Just swap the affected.tendon.heal() with **affected.tendon.rejuvenate()**

**Necrotic Organ Repair**
The fix_dead_tissue surgery is mostly funky as it seems to require people to _spam the ATK to get the damage levels under the organ.max_damage_, but without a way to tell when it's possible to use the scalpel. An idea to solve this would be give readout of sorts of how much damage there is left that you need to spam the ATK with until you can use the scalpel to complete the fix_dead_tissue.
