### ISSUE TITLE
Cyborg binary communications issue? Can send binary comms, but cannot see them show up.

### ISSUE THREAD

**Issue by AnselmKonrad** [Aurorastation/Aurora.3#12751]
As a cyborg, you can speak with the binary communications but you cannot see the actual radio chatter, as if it was never sent. this causes an issue where the AI tries to give cyborgs commands / information but we will never see it. confirmed by ahelp in-round and seems persistent

**Comment by Arrow768** [comment]
Most likely related to #12709

**Comment by AnselmKonrad** [comment]
It seems to be maybe an issue with a borg being synced to an AI? When I am not synced, I have noticed it works. When I AM synced, however. It does not work. I can send, but not receive. This might help when trying to replicate it?

**Comment by Pratepresidenten** [comment]
Its an issue with BSTs aswell. They cant see transmissions relayed or received either.

**Comment by Arrow768** [comment]
This should be resolved by #12790
