### ISSUE TITLE
.45 Pistol sends Unathi wearing full ballistic gear from the Armory into paincrit despite dealing no or little actual damage

### ISSUE THREAD

**Issue by honkel** [Aurorastation/Aurora.3#12760]
Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.
* Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!
* Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.
* Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
* All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera.

Server revision: - 2021-11-13
84cb313108b033044f8512f685e7f0b710ac3cd4
Current Map: NSS Aurora

Ahelped to MattAtlas.

Fairly simple, got shot with a .45 pistol and almost went straight into painrcrit after a single shot despite wearing anti ballistic armor. I think they targeted my leg, but the weird thing is basically no physical damage was done. I was set on fire after briefly but by the time I got to medical (within 2 minutes) the natural healing had taken care of all wounds. I don't think bulletproof armor should stop pain from being shot, but if your armor absorbs the blow as it did with both shots I took I don't think it should still render you unable to stand.

EDIT: The pistol was loaded with lethal .45 ammunition.

**Comment by SleepyGemmy** [comment]
can't replicate.
