### ISSUE TITLE
Read mind bug

### ISSUE THREAD

**Issue by Dekserrrrrr** [Aurorastation/Aurora.3#12828]
When reading the mind of someone, they have a set time of about 10 - 20 seconds to respond before the game automatically defaults the answer to "You gain nothing useful from [name]." This happens to people who have gained psionics, I'm not sure if it's different for Skrell who spawn with psionics.

**Comment by SleepyWolfe** [comment]
the reason for this is the person has to respond quickly : a basis I'd say is to give it lore reason. The brain needs to respond QUICKLY to something - immediate feedback, not a trained response. It makes it so you have to ask a simple, quick question for mind control with a simple, quick answer.

**Comment by llywyn** [comment]
it would be cool if it was made more clear mechanically (particularly to the person having their mind read). for them, the pop-up remains and you type everything in, press send, and then there's no indication the mind-reading didn't work -- a message or something to say it failed, like how the mind-reader gets one saying they gathered nothing useful, would be nice.
