### ISSUE TITLE
Dev: Holoscreen inconsistencies

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#1283]
The new holoscreen sprites @NanakoAC  added only changed the core screen, not the lights or keyboard, making them look weird and contrasty. This is especially noticeable with the standby screen, which has a black holoscreen apparently projected by bright blue projectors.

**Comment by NanakoAC** [comment]
the keyboard colours were intentional, but sure change the projectors

**Comment by LordFowl** [comment]
Modular consoles never had seperate keyboard sprites.

Seperate keyboard sprites in unmodular consoles was largely redundant and overlay-crazy.

**Comment by skull132** [comment]
Merged.
