### ISSUE TITLE
Rig suits (void module?) do not appear to react to wire pulses

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#129]
When attempting to hack a rig suit, pulsing wires does nothing.

**Comment by NanakoAC** [comment]
Cannot reproduce. Tested thoroughly, all rig wires work as intended.

Not all of them give feedback about what happened though, but 3/5 do.
My guess is user error, maybe you tried to pulse without the multitool in hand, or while wearing it, or from more than one tile away.
