### ISSUE TITLE
AI Loadout doesn't work.

### ISSUE THREAD

**Issue by Butterrobber202** [Aurorastation/Aurora.3#12913]
The "Change Hologram" command for AI offers the choice to use your current loadout (job clothing excluded) as your hologram. A pretty good idea to avoid excessive custom AI icons. Sadly, as its currently configured, the AI Job isn't allowed to display any loadout items at all on their character's body. Meaning if you try this, you end up with a naked human.

**Comment by FluffyGhoster** [comment]
Closing in favor of 19360
