### ISSUE TITLE
[NBT] Minor mapping bugs

### ISSUE THREAD

**Issue by Dekserrrrrr** [Aurorastation/Aurora.3#12943]
Executive Officers door is named with a typo:
![Screenshot_583](https://user-images.githubusercontent.com/92396228/150638874-27509688-a325-4ae0-a1ed-163db6bd5977.png)

Trash pile on the Representatives bed:
![Screenshot_584](https://user-images.githubusercontent.com/92396228/150638895-71ce3a11-7b76-4be7-95e5-42c8859ee434.png)

Hanger Bay Newscaster on the floor:
![Screenshot_586](https://user-images.githubusercontent.com/92396228/150639151-c1bbc112-7f29-4f5f-b4fe-8b54b2f65bdf.png)

This should continue as steel, not spaceship alloy, near the Hanger:
![Screenshot_587](https://user-images.githubusercontent.com/92396228/150639248-6ebe12c5-52dc-4dc6-9b97-1396582211ee.png)

Wrong-way facing emergency shutter/Should be a double shutter in EVA near the Hanger:
![Screenshot_588](https://user-images.githubusercontent.com/92396228/150639351-46e4b3f8-f2ba-4f73-958a-c4787399a3ba.png)

Steel wall:
![Screenshot_589](https://user-images.githubusercontent.com/92396228/150639524-904879c8-7e32-40f7-8dce-7bb1369a1387.png)

Notice board is in the glass (Security lobby):
![Screenshot_590](https://user-images.githubusercontent.com/92396228/150639675-8f099f5a-4ad0-4e4a-8025-318ac4bded01.png)

Another misplaced emergency shutter (kitchen):
![Screenshot_591](https://user-images.githubusercontent.com/92396228/150639799-25233e82-6f96-470d-8075-b8e9be4244a0.png)

There are a lot more but these are just some I noticed at a glance.

**Comment by Alberyk** [comment]
Fixed.
