### ISSUE TITLE
[NBT] Map Issues

### ISSUE THREAD

**Issue by Hunttark** [Aurorastation/Aurora.3#12944]
_Ignoring the standard format/round number since this is regarding the NBT map/bug issues._

- 3-4 IV stands spares in maintenance/Infirmary storage. There are presently no additional IVs besides what is provided in the general areas. (Could be added to recovery)
- Infirmary ringer system is absent
- Infirmary interior airlock exit button is absent
- Additional NanoMed Plus machines, the NSS Aurora had 3, the Horizon has 1, more are necessary to meet the average infirmary player base
- Infirmary ORs do not have holosign switches
- Examination room has two paper bins
- Infirmary showers do not have showers
- Infirmary does not have an autopsy room
- The morgue needs a table with a body-bag box
- Infirmary foyer airlocks have med-staff access requirements
- The medbay lockdown shutters are not over most of the exterior Infirmary windows
- Infirmary GTR/ICU decals are in the wrong locations. The ICU decal should be in the north section while the GTR decal should be in the general area
- Infirmary examination room maintenance airlock has a wall under it
- Xenoflora labs do not have any atmospheric systems
- Changing room showers do not have showers under the curtains
- Trash compactor appears to face the wrong way, might just be sprites.
- No Infirmary gumball jar

**I will probably have additional bugs/map issues, so apologies in advance for any additional issue 'threads'**

**Comment by Alberyk** [comment]
Everything except the autopsy table and the surgery holo signs has been fixed.

We decided to keep autopsy in security.
The holosign code is a clusterfuck. I will make it less awful soon-ish.

**Comment by stobarico** [comment]
_Adding a point_

- On the Machinist's workshop, there is a core R&D console (That you do not have access to) in addition to the robotics console, that console is also on the same turf as a protelathe.
- I do not know if this is intentional, but the Machinist's Workshop  gets no robotics fabricators while science apparently gets a whole robotics department.

**Comment by Hunttark** [comment]
_Adding additional issues_

- Pharmacist-laboratory windoors are not accessible by the pharmacist/chemist.
- Infirmary needs a pill cabinet to store pill bottles.
- First responders do not spawn with the rest of the medical on the upper level, thus the CMO can not brief them
- No exit button for the Infirmary near psych.
- There are no sinks within the general Infirmary, usually, one is needed in the GTR and one in the pharmacy lab, the only two are in the surgical theatres.
- Additional wheelchairs if possible, there are presently only two
- Infirmary general storage (where the kits are) needs one of the blue/general toolboxes
- First responders need a void suit charger in their quarters.
- A filing cabinet in the GTR, foyer front desk, or main storage
- There are no light switches for the Infirmary
- Pharmacist closet must be added, presently there are no autoinjectors or inhaler boxes available to the pharmacist (Pharmacist Wardrobe Closet has them)
- Infirmary lockerroom needs GPS systems for personnel to use
- Canes should be added to the Infirmary general storage
- Prescription glasses box should be added to the Infirmary general storage
- Box of needles should be added to the Infirmary general storage.
- Potentially adding a nano med to the upper level of the Infirmary, we also ran out of NanoMed stock when we had two instead of one since they only have 2x of each item roughly.

**Comment by Hunttark** [comment]
_Additional Map issues_

- Infirmary psychiatry wing does not have shutters for Infirmary lockdown.
- Missing Infirmary lockdown shutter, directly beside the ringer button in the Infirmary

**Comment by honkel** [comment]
The consoles in the XO office don't work, neither one of them. They just say "You press the power button, but the command console does not respond," instead.
