### ISSUE TITLE
[NBT] Tesla issues

### ISSUE THREAD

**Issue by NonQueueingMatt** [Aurorastation/Aurora.3#12948]
![dreamseeker_1Im3kgb7Pj](https://user-images.githubusercontent.com/13016572/150642678-4a656c61-42e1-41fb-b4f5-ac9461c18d23.png)

Tesla starts with 3 center pieces at the top, they need to be 1 center 1 right 1 left. The left one goes on the right because of shitcode, same with the right one going on the left

**Comment by Alberyk** [comment]
Fixed.
