### ISSUE TITLE
[NBT] Engineering webbing does not recognize the legitimacy of ship engineers

### ISSUE THREAD

**Issue by MortalRed** [Aurorastation/Aurora.3#12949]
![Screenshot (131)](https://user-images.githubusercontent.com/98221723/150642885-036d47df-5ca2-45cd-9d02-753799f0686f.png)
As the title of the regular engineer is different on the Horizon, I don't think it recognizes it as valid for the webbing.

**Comment by Alberyk** [comment]
Fixed.
