### ISSUE TITLE
[NBT] No Access To Sliding Doors

### ISSUE THREAD

**Issue by Bamboogled** [Aurorastation/Aurora.3#12941]
As Machinist, don't have access to a sliding door that's required to actually get out of the room you spawn in. You can still disassemble a window to get out, though.
![dreamseeker_lmeCgodeVj](https://user-images.githubusercontent.com/55857228/150639091-3cd07c80-b5b4-4259-b768-477adc908ec5.png)

**Comment by Alberyk** [comment]
Fixed.
