### ISSUE TITLE
[NBT] Operations lift is unable to be called when it's on a different floor

### ISSUE THREAD

**Issue by llywyn** [Aurorastation/Aurora.3#12952]
![image](https://user-images.githubusercontent.com/82828093/150646944-d51d6943-5415-424d-8d09-43ce7666cf49.png)

Also no railings or anything to stop people from falling combined with it being hard to tell when it's down a floor makes it a bit of a safety hazard, but not sure if that's a bug or by design.

**Comment by Alberyk** [comment]
Fixed.
