### ISSUE TITLE
[NBT] Warehouse windoor access allows First Responders (and possibly other roles, only tested with FR)

### ISSUE THREAD

**Issue by llywyn** [Aurorastation/Aurora.3#12956]
![image](https://user-images.githubusercontent.com/82828093/150650787-7ef775fb-6fa8-4675-ba78-cfebabda04ee.png)

First responders (at least) are able to use the warehouse windoor, but not the actual warehouse airlock. In the previous map the warehouse was inaccessible to them, so I assume it's the windoor that's bugged and they're not supposed to be able to enter

**Comment by Alberyk** [comment]
Fixed.
