### ISSUE TITLE
DEV: Rainbow Blood

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#1295]
http://i.imgur.com/RWZ7Liw.png?1

All of that blood is either from Vaurca or from Humans. It should be yellow or red. Yet we have blue blood, purple blood, bright red blood, green blood, and even orange blood - not to mention the blood overlays are pure white.

Something is seriously fucky.

**Comment by LordFowl** [comment]
After I restarted the server the bug seemed to have vanished. Leaving this up in case anyone has any input.

**Comment by skull132** [comment]
I think this may be an odd product of blood colours mixing. Which I do believe is now a mechanic.

**Comment by LordFowl** [comment]
What a weird fucking mechanic. Bay needs to learn their colour theory.
