### ISSUE TITLE
[NBT] Kitchen & Garden Lack Vendors + Access

### ISSUE THREAD

**Issue by Kaizrr** [Aurorastation/Aurora.3#12953]
- The kitchen lacks a dinnerware vendor of any sorts which makes operating it exceptionally difficult. 

- Kitchen lacks extra fry oil, meaning the deep fryer cannot be re-filled.

- The garden lacks the proper seed vendor and the one that is currently present is the limited access vendor (The one used in the public garden that has like half of what the hydroponics vendor has).

- Lastly, the kitchen has a stairwell to the bridge bar but no access, were service staff suppose to have access to the bridge's bar?

**Comment by Alberyk** [comment]
Fixed.
Service staff should not have access to any area of the bridge.
