### ISSUE TITLE
[NBT] - Multiple issues with the Mining Pod airlock (Edited 01-23-2022)

### ISSUE THREAD

**Issue by RazorXLVII** [Aurorastation/Aurora.3#12967]
1. As the title says, cycling the airlock to exterior with at least three miners takes while in the mining pod takes _around_  10 minutes, more or less. Attempt to repeat the issue by putting two crates in the airlock and have two of the three miners lie down below the third.
2. For reasons unkown, the airlock self-combusted and spread a rather large fire in the hangar shortly after landing back in the Horizon.

**Comment by Alberyk** [comment]
Fixed
