### ISSUE TITLE
[NBT] Tagmaster directory incomplete

### ISSUE THREAD

**Issue by TheBurninSherman** [Aurorastation/Aurora.3#12968]
![image](https://user-images.githubusercontent.com/55469976/150661058-cea16391-7c9f-428f-8e85-7cc8fb21872c.png)

As can be seen above, the mail tagging system is missing many destinations on the ship and therefore operations cannot ship things to many departments via the mail chutte/disposals sytem.

**Comment by Alberyk** [comment]
Please star writing [ NBT] on your reports titles.

**Comment by Alberyk** [comment]
I added more of them around. Tell me if it is enough.
