### ISSUE TITLE
Roundstart research fabricators take an abnormally long amount of time to print things right now

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#12995]
With the normal manipulator stock parts, it seems like they take upwards of twenty-thirty seconds if not far more than that to print anything. If replaced with pico-manipulators, it goes down by a MASSIVE amount though, being within 5 or so seconds, though that's still slower than the old pico-manipulators I think.

This is probably related to the whole timer stuff going on right now I suppose.

**Comment by NonQueueingMatt** [comment]
Should be fixed.
