### ISSUE TITLE
[NBT] Service Manager can't access Service areas

### ISSUE THREAD

**Issue by feartheblackout** [Aurorastation/Aurora.3#13000]
According to [this page](https://wiki.aurorastation.org/index.php?title=Guide_to_the_NBT#Service_Manager), the Service Manager is supposed to be able to access every Service area. I didn't test every single area with my access, but I couldn't access the Kitchen, Bar, or Hydroponics, leading me to assume that areas like the Chapel or Library would be inaccessible as well.

**Comment by Alberyk** [comment]
Fixed.
