### ISSUE TITLE
[NBT] Mining shuttle airlock shittery

### ISSUE THREAD

**Issue by Dekserrrrrr** [Aurorastation/Aurora.3#13003]
![Screenshot_620](https://user-images.githubusercontent.com/92396228/151671506-b3260574-8db9-44ee-9fcf-5dccb088e8be.png)

When the airlock cycles to the exterior, it forces the far-left interior door open too

![InkedScreenshot_620_LI](https://user-images.githubusercontent.com/92396228/151671548-9820584f-e193-4857-8929-4564fd91d807.jpg)

**Comment by CaptainGecko** [comment]
![Funny door](https://user-images.githubusercontent.com/94259758/151680751-e79938a8-e1fd-4658-9510-c2c685954b89.png)

Adding my bit to show the problem in practice. This door seems to be considered like an external door.

**Comment by Alberyk** [comment]
Fixed.
