### ISSUE TITLE
Mining Pod Cannot Function Well

### ISSUE THREAD

**Issue by Tristan63** [Aurorastation/Aurora.3#13018]
![eca22eaae7c61a9b3a79f303c87ae497](https://user-images.githubusercontent.com/66579448/151688906-e54087be-f571-4149-a5af-8ff212e390e0.png)

This interior airlock is classified as an exterior one. ^
![fb9e40f52e049e0735fd6ce15ca14676](https://user-images.githubusercontent.com/66579448/151688914-a3927aff-b4e2-4b75-b07e-44ac36c435f8.png)

No contacts on long range pad in the mining pod, not even the bridge.

The bloody thing takes more time to cycle than the old giant airlock on the Aurora.

**Comment by Tristan63** [comment]
also you can't access any APC onboard the pod at all

**Comment by Alberyk** [comment]
Fixed.

**Comment by Tristan63** [comment]
epic
