### ISSUE TITLE
[NBT] Engineering substation ladder is unfinished

### ISSUE THREAD

**Issue by Dekserrrrrr** [Aurorastation/Aurora.3#13024]
![Screenshot_624](https://user-images.githubusercontent.com/92396228/151694683-16a3d847-da56-4023-b2ca-8adaef8aec51.png)
![Screenshot_625](https://user-images.githubusercontent.com/92396228/151694685-44e6c7bb-f598-4feb-892b-debaa66d8927.png)

**Comment by Alberyk** [comment]
Fixed.
