### ISSUE TITLE
[NBT] Add nitrile gloves for non-humans in the Science EVA Prep Room 

### ISSUE THREAD

**Issue by CaptainGecko** [Aurorastation/Aurora.3#13033]
![gloves](https://user-images.githubusercontent.com/94259758/151703944-13230f2b-5437-4b6c-b2a7-67f0121e17c1.png)

So far the Science EVA Prep Room only offers Nitrile Gloves for humans. On the Aurora, alien-fitting Nitrile gloves can be found in the lockers, but they seem to be missing here. They should probably be added back, a pair of nitrile gloves for Tajaras and Unathi in each excavation locker.

**Comment by Alberyk** [comment]
Fixed.
