### ISSUE TITLE
[NBT] Near-total lack of disposal units in the Science Department on Deck 1

### ISSUE THREAD

**Issue by CaptainGecko** [Aurorastation/Aurora.3#13031]
So far, I can only see a single disposal unit in Deck 1 science, in the firing range. Here are some proposals for disposal units placement:

![disposal01](https://user-images.githubusercontent.com/94259758/151703541-2e602fcf-4cbd-4adf-a282-2d30b7a9b061.png)
In the Storage room by the Xenoarcheology Atrium, as well as in the Anomalous Energies Collection room (yes I know that it would make things quite tight in the Storage room, but both the Space AC and replacement emitter are very rarely used, and can still be displaced to make room to grab the other.)

![disposal02](https://user-images.githubusercontent.com/94259758/151703545-8cbd9d3d-739f-4f5b-a5f7-833c758dbb15.png)
In the Xenoarcheology Atrium (this spot, I think, it the more advantageous one, with proximity to the paper bin and chemical dispenser, to quickly dispose of bad reports draft and chemical substances _assuming they aren't too dangerous_.)

![disposal03](https://user-images.githubusercontent.com/94259758/151703549-4f936525-b94b-4263-a036-7eecaaf2d95b.png)
In the science EVA Prep Room (This spot here seems empty for no reason, I don't see why we couldn't add a disposal unit here.)

**Comment by Alberyk** [comment]
Fixed
