### ISSUE TITLE
[NBT] The science department's Storage Room needs its use (and roleplay oppotunities) back.

### ISSUE THREAD

**Issue by CaptainGecko** [Aurorastation/Aurora.3#13034]
![Storage01](https://user-images.githubusercontent.com/94259758/151704247-c199ca17-4aac-4b41-8ea0-5ba566d65d4f.png)
(The current storage room)

It seems that the Horizon's Science Department's storage room (just South of the conference room) is not meant to be used to store things, but rather, is already stored full of gear. Four full lockers of uniforms, headsets and gloves are overkill (a single one on the Aurora was already more than enough), and much space could be spared to grant the storage room the actual uses it had on the Aurora.

![storage03](https://user-images.githubusercontent.com/94259758/151704287-bf322c46-900d-411e-8abf-184e161fb1e9.JPG)
Reminder that this was the storage room on the Aurora.
- It had an "armored door" that could be locked by the Director, and the room itself could only be accessed by the RD, Xenobios (and alt titles) and scientists (and alt titles).
- It featured a rack with 50 sheets of steel and glasses on it, the rest of the room was completely empty and to be filled.
- A science weapons locker to store weapon prototypes.
- An Exosuit charger.
- A table behind armored windows (+windoor) for extra secure storage of items of smaller sizes.
- A security camera.

Beyond allowing science players to store their creations in a secure way (and, say, not leaving weapon prototypes on RnD's table, for instance), it would act as an objective for some antags too and had the potential to play a role in some rounds.

![Storage02](https://user-images.githubusercontent.com/94259758/151704491-252528e9-e197-4998-ae5b-826cf63309dd.png)
Here's a prototype I made with some (more or less shoddy) editing. We keep two of the lockers we currently have on the West side of the room, and yet, still have enough space for storing spaces with a weapons locker and an exosuit charging port too.
Here' are a few notes too:
- The "table area" could be made smaller to resemble the one we had in the Aurora for even more space, if needed.
- The science locker, just next to the weapons locker, could be swapped with an empty locker, a crate, or a radiation-proof suit locker.

**Comment by Alberyk** [comment]
Fixed.
