### ISSUE TITLE
[NBT] SCC mining cyborgs are blowing up when leaving the ship

### ISSUE THREAD

**Issue by Ershovdi** [Aurorastation/Aurora.3#13039]
"Initiating wipe of all databases containing information related to Stellar Corporate Conglomerate!"
"You hear the sound of a nearby explosion coming from the east."
And then I blew up.
Happened on the mining shuttle while flying off the ship to the romanovich cloud asteroid. That shouldn't happen I suppose.

**Comment by Tristan63** [comment]
![0c0c0d733521ef110b6abf3423381115](https://user-images.githubusercontent.com/66579448/151716076-89b42aa8-4988-45eb-a437-2d5bac6e6746.png)

**Comment by Alberyk** [comment]
Fixed.
