### ISSUE TITLE
[NBT] Mining Pod - Incorrect Light Fixture Placement

### ISSUE THREAD

**Issue by RazorXLVII** [Aurorastation/Aurora.3#13032]
There is a light fixture incorrectly placed in the mining pod. It should be placed on the wall, but as you can see in the image it's (likely) floating above the seat.

<img width="286" alt="Mining Pod Bug" src="https://user-images.githubusercontent.com/26613295/151704005-f20ad78b-c034-4e04-9276-778c52814c23.png">

**Comment by Alberyk** [comment]
Fixed
