### ISSUE TITLE
[NBT] Operations Lobby APC

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#13043]
- Operations Lobby APC is still called Cargo Lobby APC.
- Said APC doesn't actually appear to be connected to the power network, but others appear to be connected to it (Technical storage, primary tool storage, security checkpoint, central primary APC near the docking area.

![image](https://user-images.githubusercontent.com/60306280/151723184-4b60671e-09d3-4bc6-9318-e515afda202f.png)

**Comment by Alberyk** [comment]
Should be fixed.
