### ISSUE TITLE
[NBT] Mini Disposal Issue by Medical Spawn Point

### ISSUE THREAD

**Issue by VisVirific** [Aurorastation/Aurora.3#13044]
* This disposals unit spews out anything you shove into it.
![disposal mapping problem](https://user-images.githubusercontent.com/32141503/151724100-353a5140-10ec-4f3e-81cb-7705e5152418.PNG)

**Comment by Warbidon** [comment]
can confirm it still occurs.

**Comment by Alberyk** [comment]
Should be fixed.
