### ISSUE TITLE
[NBT] Invisible jumpsuit icons, item, not worn.

### ISSUE THREAD

**Issue by FlamingLily** [Aurorastation/Aurora.3#13046]
This may be known but there was no github issue I could find. Idris security jumpsuit's item icon is invisible, I have not seen others, though do comment them if there are it would be useful to have it all in one place. 

![image](https://user-images.githubusercontent.com/80451102/151737529-e674e952-03db-4e44-a614-311aa38687ec.png)

**Comment by Alberyk** [comment]
Fixed.
