### ISSUE TITLE
[NBT] Shield Generator Access is borked, starts with no access requirements, yet no one can open the door *not even the AI*

### ISSUE THREAD

**Issue by FlamingLily** [Aurorastation/Aurora.3#13047]
As the title says. If I had to guess, it's the 'tamper proof electronics'. Don't have the screenshot, but every item on the electronics' access list was white, as opposed to green, it was set to requiring one, not all, and the door wouldn't open. I also set it directly to ALL of Engineering (as an engineer), and it still didn't open.

**Comment by Alberyk** [comment]
Fixed.
