### ISSUE TITLE
Quotations in some UI often appear as &#34;

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#13073]
Quotations in some user interfaces often end up appearing (after saving) as a string of characters: `&#34;`
This also happens to apostrophes, which will appear as: `&#39;`

The two places I have seen this appear the most is on the Character Setup menu in both the name and description of items - if they have a custom name or custom description - and in Character Records, mostly in the Setup menu still. This menu is the only location I can accurately and repeatedly replicate this bug. It _may_ also appear in-game sometimes, as I have seen it in the floating text above mobs when they speak, though it is unreliable and difficult to replicate.

This string of characters does not seem to carry over onto the item when spawned in; however, it _will_ carry over if you re-open the name or description text edit box and save it again. Photos for showing what I mean below.

**Before re-opening and saving**
![bug report 1](https://user-images.githubusercontent.com/15650378/152364519-73b875c1-922f-4579-aeb6-36a83831f5af.PNG)

**After re-opening and saving**
![bug report 2](https://user-images.githubusercontent.com/15650378/152364789-e0897682-5a56-43eb-897c-20d8d9c325ad.PNG)

**Comment by Dekserrrrrr** [comment]
I think that's an underlying issue with Byond and its century old engine. I might be wrong though.
