### ISSUE TITLE
Dev: Opening the Criminal Sentencing Computer's UI causes client-side errors

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#1307]
Interacting with the Criminal Sentencing Computer in Security Processing prints the following messages to the DreamSeeker client log:
```
winset: Element crim_sentence not found.
winset: Element crim_sentence not found.
```
revision: 70ad90663b1240dbf6f2d19d7b80392a510c6b98

**Comment by skull132** [comment]
@Arrow768 and @LordFowl , since you were the ones working on it.

**Comment by LordFowl** [comment]
Doesn't seem to have any effect on the actual client of the console. My UI is a bit rusty, so @Arrow768 might want to take a look.

**Comment by Arrow768** [comment]
Not related to dev or the sentencing console alone
This happens with everything that uses a var/datum/browser
* Airlock Wires
* Brig Door Control
* Solar Control
* GPS
* Telescience Computer
* ...

**Comment by Lohikar** [comment]
Turns out this is caused by attempting to set the onclose event on a window that the client hasn't recieved yet.

**Comment by Lohikar** [comment]
Fixed in development with SMC.
