### ISSUE TITLE
[NBT] AI Upload Chamber power issues

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#13086]
Certain machinery in AI Upload Chamber seems to be lacking power despite other things in said area being powered/functional.
![dreamseeker_2022-02-05_06-25-04](https://user-images.githubusercontent.com/11140088/152645830-4175bfd9-6638-4841-9e48-b0028dc058d9.png)

The vents/scrubbers won't turn on, and the turret controller doesn't work, but the doors, blast doors, and air alarm all seem to be working.

**Comment by Alberyk** [comment]
Fixed
