### ISSUE TITLE
[NBT] Arrivals APC's are not connected to the main grid.

### ISSUE THREAD

**Issue by Ershovdi** [Aurorastation/Aurora.3#13085]
Arrivals APC's on Horizon are not connected to the main grid (green wires on the screenshot), and that's why they are not getting any charge. Needed to connect them manually (red wires on the screenshot)
![dreamseeker_RH1RSdoRPv](https://user-images.githubusercontent.com/63337306/152645549-1f5323b4-e077-4a51-bd9e-a0bedb527733.png)
.

**Comment by Ershovdi** [comment]
![dreamseeker_iRWdPLhGT6](https://user-images.githubusercontent.com/63337306/152645573-2c55885a-2a23-46ac-85eb-0b1844eb29e6.png)
Little addition here. Red wires - placed manually. Green wires - already mapped. Needed to connect the green wires with main grid.

**Comment by Alberyk** [comment]
Should be fixed.
