### ISSUE TITLE
[NBT] Engineering corridor door isnt open to the public

### ISSUE THREAD

**Issue by llywyn** [Aurorastation/Aurora.3#13095]
The airlocks on the bottom right have standard engineer access. I think this is supposed to be an all-access door because it only leads into the waiting area, and the desk has a buzzer on it to get an engineer's attention, which can't be reached atm.

For this to match how the Aurora map is and how every other department is on the Horizon, the bottom right doors should be open to anyone, and then the important stuff (just the 3 shield projectors, probably?) should be moved behind the actual doors into engineering proper.

This was the case with Science too earlier in the tests but it was fixed and everyone got access to their corridor so I think this just wasn't reported yet or was missed.

![image](https://user-images.githubusercontent.com/82828093/152656779-e69d4ac9-32db-43ff-a602-753b451b934d.png)

**Comment by Alberyk** [comment]
Fixed
