### ISSUE TITLE
[NBT] Intrepid not launching to navigation sites (Probably a timer issue)

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#13099]
Round ID: cgl-cV80

Bridge crew attempted to take the Intrepid to an asteroid and then empty space. Neither worked. Apparently the ship might have thought it was already there or something, unsure.

**Comment by WickedCybs** [comment]
It launched on the round afterward. Suspect it might be because the Intrepid tried to land at an asteroid the mining pod was already at. This bricked it for the rest of cgl-cV80 maybe.

**Comment by WickedCybs** [comment]
At this point it might be a timer issue, I saw Alb restart the MC for a minind pod that had a similar issue and it finally launched.

**Comment by NonQueueingMatt** [comment]
This is caused timers, yes, but not in the way you think. The timer subsystem locking up causes it to infinitely get stuck in the processing queue, and thus no other subsystem can process, like shuttles.

Should be fixed now.
