### ISSUE TITLE
[NBT] Xenobotany Atmos controller has control of the entire ships atmos network.

### ISSUE THREAD

**Issue by DisreputableSquid** [Aurorastation/Aurora.3#13094]
![bUG](https://user-images.githubusercontent.com/17767700/152656902-709f41e4-c1a5-459b-af5b-45d34e3879b9.png)
The Hazardous Specimens Atmospherics controller has access to every air alarm on the ship, and control all of them fully. 
Steps to reproduce: Enter Xenobotany as a Xenobotanist, access the atmos controller for the Hazardous Specimens Area. You will get a full list of the ships air alarms and can control all of them.

**Comment by Alberyk** [comment]
Fixed.
