### ISSUE TITLE
[NBT] Living Quarters door is missing an emergency shutter

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#13097]
![dreamseeker_2022-02-05_12-49-15](https://user-images.githubusercontent.com/11140088/152658526-18a118c8-18b8-4ae1-89ff-d5f84da2d113.png)

![dreamseeker_2022-02-05_12-49-47](https://user-images.githubusercontent.com/11140088/152658534-27c33897-63fc-4657-a377-aef0624f2f3c.png)

**Comment by Alberyk** [comment]
Fixed.
