### ISSUE TITLE
Dev: Medical Ward is missing a wire

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#1309]
![2016-12-25_14-59-03](https://cloud.githubusercontent.com/assets/7097800/21472870/b9a2b9ac-cab2-11e6-9b83-9b20894f9883.png)

**Comment by skull132** [comment]
Note to self:
* Fix arrival shuttle engines
* Fix that one derpy ass intercomm in arrivals, below sec checkpoint
