### ISSUE TITLE
DO's do not have an option to send a fax to all machines on station

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#131]
This is a feature that would be very helpful for us to have; It's essentially how faxxes worked in old code. Currently I have to send the same fax repeatedly to have it go to every fax machine on the station, which fills the fax history and is more work than should be necessary.

**Comment by SierraKomodo** [comment]
A thought I've had to replace this, and make sending faxxes to multiple locations a bit easier would be to allow selecting any number of faxxes in the dialog, either through checkboxxes or a select box list that allows selecting multiple options. If it's not possible to support this, the original 'Send to all' option will work as well.

**Comment by skull132** [comment]
I plan on doing DO related shit this week, so I'll defo look into it. I
don't know if BYOND natively supports input where you can select mulitple
things, but there are ways past that. Either HTML forms or by using a loop
and cancel button (sorta like how custom vote options work).

**Comment by SierraKomodo** [comment]
With the functionality provided by the Web Interface by @Arrow768 this can be closed, I'd think, unless there's plans to make this a feature in aurora code itself.

**Comment by Bedshaped** [comment]
Closing due to being added.
