### ISSUE TITLE
[NBT] Disposals room plastic flaps aren't airtight

### ISSUE THREAD

**Issue by HappyFoxFluff** [Aurorastation/Aurora.3#13108]
The type of plastic flaps used next to the mass driver in disposals aren't airtight, they're the non-airtight regular variety which means that when you open the blast doors for the mass driver it vents the whole room. There is also no way to move crates onto the mass driver (except, ironically, when the room vents and it pulls the crate onto the mass driver due to airflow).

**Comment by Alberyk** [comment]
Fixed
