### ISSUE TITLE
[NBT] Missing powernet sensors

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#13109]
The power monitor is missing powernet sensors on the Horizon.
![2022-02-05_20-47-01](https://user-images.githubusercontent.com/11140088/152668141-d012ff1f-9c29-485c-8bfe-6c1d08903c44.png)

**Comment by mikomyazaki** [comment]
Seems to be working for me. Can you give any more info?

![image_2022-02-11_144656](https://user-images.githubusercontent.com/47489928/153612787-c6c2379b-b32f-474e-8188-2febe697fbbb.png)

**Comment by Alberyk** [comment]
Added more of them. Should be fixed.
