### ISSUE TITLE
AI appears able to set alert levels

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#13102]
The AI appears to be able to set station alert levels when using a console with the command and communications program open. This may require someone else having left the program open, unsure.

I didn't actually try pressing the buttons to avoid IC disruption, but the buttons were blue and appeared clickable:

![2022-02-05_14-08-48](https://user-images.githubusercontent.com/11140088/152660595-f4908d9c-e38b-4d4c-9d4d-4e26ea67e163.png)

**Comment by DreamySkrell** [comment]
if clicked with no access (such as a borg), you get a red "You press the button, but a red light flashes and nothing happens." message

also AI can now (again) change alert level as per https://github.com/Aurorastation/Aurora.3/pull/14443
