### ISSUE TITLE
[NBT] Multiple mapping issues for Xenoflora lab.

### ISSUE THREAD

**Issue by DisreputableSquid** [Aurorastation/Aurora.3#13117]
The xenoflora lab has a number of issues with it currently.

1. Seed extractor is blocked in and inaccessible
2. The equipment is scattered all around the room, making efficient use of them frustrating. at the very least, the two xenoflora pieces of equipment, and the Biogenerator and the Seed extractor should all be located adjacent to each other, and the stack of gene disks adjacent to the two machines that use them.
3. The hazardous xenoflora area should be larger, especially considering that away missions may have the opportunity to bring back samples. Perhaps replace one of the exterior blisters to be one? 
4. There needs to be more piping to control air supply to at least one of the blisters, to grow plants that survive in extreme conditions.
5. Unstable Mutagen needs to be added to the Garden supplies vendor in the lab.

**Comment by Alberyk** [comment]
Most of this should be fixed. Making the hazardous xenoflora area bigger was not possible.
