### ISSUE TITLE
[NBT] Add a storage for anomalies + Anomaly containers

### ISSUE THREAD

**Issue by CaptainGecko** [Aurorastation/Aurora.3#13135]
Yes it's me again, annoying you all with Xenoarcheology again!

The Aurora's Xenoarcheology department features a storage room. It allows the local Xenoarcheologist to put their finds somewhere, preferrably close, so possibly anomalous and dangerous finds won't end in the regular storage, and more importantly, won't have to be dragged all the way there as they spawn horrors and such, for instance. A little while ago, anomaly containers were also implemented, which allowed the storage of anomalies that couldn't be turned off too, and the storage room came with two.

![unknown](https://user-images.githubusercontent.com/94259758/153198056-7b68e617-3ed9-4549-9dc1-18e8fe7bbf0f.png)
The storage room is located there on the Aurora.

![unknown2](https://user-images.githubusercontent.com/94259758/153198104-7a07582d-1929-438e-828b-0daa04f8b329.png)
This is the storage room. Anomaly containers on the right.

The Horizon's Atrium, no matter how beautiful it may be, is lacking in this department. First there's not even a table to put artifacts while waiting to be processed (See the Aurora's Atrium, just by the entrance, a two-tile table behind windoors.) But there's also no storage room at all, and by extent, no anomaly containers! Without the room, there is actually no way to store finds Xenoarcheologists bring back. There are also no containers, naturally.

As to where the room should be located, I'm not too used to the Horizon's map yet, but as far as my non-expert opinion goes...
![151703545-8cbd9d3d-739f-4f5b-a5f7-833c758dbb15](https://user-images.githubusercontent.com/94259758/153198815-ad21193d-fb70-42cb-9d88-deb4056494c9.png)
If there is nowhere to go to make an extra room, there is a room for anomaly suits on the West side of the Atrium. The suit racks could be moved to the Atrium itself, where there is space, just like how it is on the Aurora, and this room might be turned into a tiny storage.

**Comment by NonQueueingMatt** [comment]
Not a bug.
