### ISSUE TITLE
[NBT]Xenofloa lab equipment issue

### ISSUE THREAD

**Issue by DisreputableSquid** [Aurorastation/Aurora.3#13154]
The Xenoflora lab is missing its Bioballistic Injector, the machine that lets you add genes to a plant. Instead it just has two of the isolators. 

Also the gardening equipment Vendor needs some unstable mutagen bottles, or for the reagents to make it automatically in the Chem dispenser in Xenobotany. I know the dispense is more for collecting reagents from plants, but its terribly frustrating to be unable to produce my own unstable mutagen.

The Dangerous Xenoflora area's airlock area's buttons are reversed. the left button opens the right door, the right button opens the left door.

The placement of the two xenobotany machines make the corner table inaccessible. Recommend swapping the table and the machine to connect the two tables on the left wall together.

Also Xenobotany has no disposals.

**Comment by Alberyk** [comment]
Fixed.
