### ISSUE TITLE
Dev: All players are blind

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#1315]
Players spawning spawn blind, changing BLIND mutators and blindness variables do not restore sight.
Introduced by 22c43472ae4ce151c669854f1bfc4fd94817fd3d, and fixed by reverting the changes to `H.blind.layer`.

**Comment by skull132** [comment]
Reverting it isn't much of a fix. blind.layer is unusable in 510+ versions of BYOND. I did a slight error while replacing the variable, though. blind.invisibility works backwards.
