### ISSUE TITLE
[NBT] Multi-level hull shield blocks off shuttle access

### ISSUE THREAD

**Issue by Karakamenk** [Aurorastation/Aurora.3#13156]
I guess because the shuttles are not technically part of the ship, multilevel hull shields will form a a protective bubble around them, preventing the crew from accessing them. This is only if the multilevel option is selected on the hull shield. If the bubble shield gets a multilevel option, this might become a problem too.

**Comment by NonQueueingMatt** [comment]
Will be fixed in time for the NBT.
