### ISSUE TITLE
[NBT] Horizon Lounge Area is the main Dumping ground of the Station

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#13153]
All the Items put into most of the main station Trashbins eventually ends up beeing expelled in the lounge area, This is not desired. I Hope so at least.
unless this is an injoke
* Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
it is actually possible to put things into one Lounge Trashbag and have them come out the other
it is quite funny.

**Comment by deGurkin** [comment]
![grafik](https://user-images.githubusercontent.com/30761807/153726305-31c46691-9974-4f6e-a031-9ed60842c84a.png)

**Comment by Alberyk** [comment]
Fixed.
