### ISSUE TITLE
[NBT] Wall mounted tank control computers don't display holographic screen

### ISSUE THREAD

**Issue by mikomyazaki** [Aurorastation/Aurora.3#13172]
This is because they are of type `/obj/machinery/computer/general_air_control/large_tank_control/wall`, not a subtype of `/obj/item/modular_computer/telescreen` which has handling for the screen icon.

**Comment by FluffyGhoster** [comment]
Looks like they work to me, reopen and indicate how to reproduce and what to expect if not working as expected
