### ISSUE TITLE
[NBT] Long range holopads can only contact the mining shuttle

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#13174]
It seems every long range holopad can only contact the mining shuttle at the moment. So the Intrepid can't be contacted by the bridge and vice versa for now as an example.

**Comment by mikomyazaki** [comment]
How far apart are the ships when you're trying to contact them?

Currently the Long-Range Pads can only contact things that are 0 to 4 overmap spaces apart. They also cannot contact a ship that is docked with it.

**Comment by WickedCybs** [comment]
It seems like I misunderstood how they worked. As far as I can tell, you can call all the other holopads if you're not docked yes. Closing the PR due to that.
