### ISSUE TITLE
[NBT] Bridge level bar needs a booze-o-mat and alcohol dispenser

### ISSUE THREAD

**Issue by Cooleosis** [Aurorastation/Aurora.3#13173]
Really not much of a bar without them. Add those two machines and I'd honestly prefer using it to the main bar by the kitchen.

**Comment by mikomyazaki** [comment]
Seems to have been fixed.

![bridge_level_bar](https://user-images.githubusercontent.com/47489928/154684639-bb9e6800-99b9-40f6-94c7-
17415e9e6100.PNG)

**Comment by Cooleosis** [comment]
Not that bar, this one directly next to cryo

![rtsyhnrthrstb](https://user-images.githubusercontent.com/9246921/154818544-fdff5d04-e2bd-424f-9679-1983df96ca3e.JPG)

**Comment by mikomyazaki** [comment]
I think this one is supposed to be a cafeteria, not a bar.

**Comment by NonQueueingMatt** [comment]
Not a bug.
