### ISSUE TITLE
[NBT] Mining Shuttle can launch without opening the blast doors infront of it

### ISSUE THREAD

**Issue by mikomyazaki** [Aurorastation/Aurora.3#13178]
Doors circled in red seem to be there to "block the mining shuttle dock" -- But it can launch/land anyway.

![image](https://user-images.githubusercontent.com/47489928/153791191-2b2a55a9-4758-4cbc-8f88-4e938bc7022e.png)

**Comment by Alberyk** [comment]
Not a bug. These can't open anyway.
