### ISSUE TITLE
Z-mimic isn't correctly handling layers of mimiced objects

### ISSUE THREAD

**Issue by mikomyazaki** [Aurorastation/Aurora.3#13193]
See this example, the stack of things from top to bottom is:

---
Open Space
Lattice
Turret
---

But they are displayed to the viewer on the top level as:

---
Open Space
Turret
Lattice
---

I guess because the layer of the icon of the lattice is on `UNDER_PIPE_LAYER` which is below the turret.
Top Floor:
![floor3](https://user-images.githubusercontent.com/47489928/154164876-de0df08d-2b03-4ca9-89ff-3a0dccae6955.PNG)
Middle Floor:
![floor2](https://user-images.githubusercontent.com/47489928/154164878-59c0d9a9-80f1-43f7-9ff6-58cff4cdea3e.PNG)
Bottom Floor:
![floor1](https://user-images.githubusercontent.com/47489928/154164883-d9df198b-1396-4830-930a-38cb5db129c2.PNG)

**Comment by JohnWildkins** [comment]
Fixed by #14495
