### ISSUE TITLE
Changeling mute sting doesn't provide a message for the victim

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1321]
This is reported second hand through ckey Cripto104, whom doesn't have a github.

I do distinctly recall this sting giving the victim a message along the lines of their vocal cords restricting in the past; Cripto reported he received no message or warning at all he'd been muted (And as such thought he was lagging or something broke).

**Comment by Alberyk** [comment]
Probably  fixed in my last changeling update/pr.
