### ISSUE TITLE
[NBT] Can't change the propulsion pressure regulator back to 15000 kPa target pressure if you tweak the setting at all during a round

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#13226]
If you try maxing it out ingame again, the highest it'll go to is 5066.25 kPa

![image](https://user-images.githubusercontent.com/52309324/154829725-cf0cd4c7-cfd5-4492-8211-81cea84f2c5d.png)

**Comment by WickedCybs** [comment]
This is the roundstart target pressure setting for reference.

![image](https://user-images.githubusercontent.com/52309324/154829764-48e526c2-7af1-404f-b7b6-62bf882e0f1f.png)

**Comment by mikomyazaki** [comment]
It will now start at 5066 kPA. But I will be looking at allowing that area (and others) to pump at higher pressure again.
