### ISSUE TITLE
[NBT] Chaplains office vents itself when losing power due to the coffin ejector blast doors

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#13239]
Since blast doors open when unpowered, both the blast doors tend to open with a lack of power and sometimes they'll even stay open when power comes back. Not 100% sure if this would be considered a valid issue, but I think the blast doors staying open at least are kind of one.

![image](https://user-images.githubusercontent.com/52309324/154865899-478fe35e-702a-4f10-b81c-e7955934796e.png)

**Comment by SleepyGemmy** [comment]
Duplicate of #13228.

**Comment by WickedCybs** [comment]
fugg
