### ISSUE TITLE
Depowered Airlocks Open After Crowbarring Them Shut

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#13232]
![image7](https://user-images.githubusercontent.com/99297919/154865091-c9d17ee0-6784-4735-b863-8c177840efc5.png)
depowered airlocks open themselves after being crowbarred shut despite them being, you know, depowered.

**Comment by mikomyazaki** [comment]
Seems to be intentional from the comments on the relevant bit of code.
I don't know why a depowered airlock is meant to move, though...

```
//if we lost power open 'er up
if(insecure)
	INVOKE_ASYNC(src, /obj/machinery/door/.proc/open, 1)
	securitylock = TRUE
```

**Comment by SleepyGemmy** [comment]
@mikomyazaki No idea. Makes more sense that they don't reopen after initially having opened, if power has been lost.

**Comment by mikomyazaki** [comment]
> 

Good point. I'll look into that...

**Comment by mikomyazaki** [comment]
> @mikomyazaki No idea. Makes more sense that they don't reopen after initially having opened, if power has been lost. Edit: Also, you may have misread. That comment likely refers to the initial opening, not any subsequent openings of the airlock.

I'm having trouble replicating this. Is it possible power was restored to the doors for a second then gone again?

What was the cause of the powercut when you observed this?

**Comment by SleepyGemmy** [comment]
>I'm having trouble replicating this. Is it possible power was restored to the doors for a second then gone again?
>
>What was the cause of the powercut when you observed this?

@mikomyazaki Electrical storm, i.e. the blue APC and a timer before it resets. Could be related to that?

**Comment by SleepyGemmy** [comment]
stale, closing.
