### ISSUE TITLE
[NBT] Stairway into the Kitchen from Command with a Bar where no one has access?

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#13243]
This seems entirely odd. Like, the Break Room is directly connected to the Kitchen, this seems like Antag Bait more than an actual Feature, maybe letting the Service manager go man the breakroom bar or something would justify this feature.

**Comment by SleepyGemmy** [comment]
@deGurkin The chef likely lacks access because they are only supposed to get up there and serve in the bar or meeting room, if command gives them access. Whether this is by a guest pass or by direct ID changes.

**Comment by deGurkin** [comment]
Gotcha.
