### ISSUE TITLE
NBT Atmos pipes gas flow and pumps not working

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#13246]
The new ship atmos section of the engineering department has a weird issue where the gas containers (the big circular gas containers) gas flow doesn't work and pumps won't turn on EX: if you turn on the pump to connector in whatever containers the pump won't turn on (sprite wise) and it won't inject gas into whatever is wrenched to the connector like air pumps and cannisters, same thing happens if you try to send gas to the mix pipeline it won't work the pumps won't turn on and the gas won't be sent a drone tried removing the pump from the connector and just hooking the connector directly to the pipeline that comes out of the chamber and that also din't work there was no gas flow even thought there clearly was gas inside the pipes

**Comment by mikomyazaki** [comment]
Did you check the vent pump within the tank was turned on and had a high setting?

The air flow from the air tank does work (or has done for me in recent rounds) -- It just might not be as much as usual due to some pipe changes that are being tested.

**Comment by mikomyazaki** [comment]
I've reverted the changes to pipes for now on the NBT repo, so this shouldn't be an issue either way. Please reopen if you see the same problem occur again.
