### ISSUE TITLE
Colorable Shorts lack their .DMI on the Aurora server branch

### ISSUE THREAD

**Issue by Aticius** [Aurorastation/Aurora.3#13248]
#13150 is the PR that adds "colshorts". On the NBT branch, this item spawns and looks proper, but on Aurora, this item spawns, lacking it's sprite icon, which defaults to the HONK shirt placeholder.

Someone did an oopsie, somewhere.

**Comment by mikomyazaki** [comment]
Looks like #13126 deleted them due to an unnoticed conflict.
