### ISSUE TITLE
[NBT] AI Uplink Turret Control not responding to CMO command ID.

### ISSUE THREAD

**Issue by Pedantic11** [Aurorastation/Aurora.3#13242]
Round ID: Round Prior to cgA-dBRH
Issue (?): Not sure if this is an actual bug or not, but the CMO doesn't have access to the Turrets or AI Upload on the Horizon. On the Aurora, Command access usually allows for control of at least the outer turrets, which thankfully don't shoot at the CMO, but here it simply flashes 'access denied.' Aside from that, the CMO also has no way of access the AI core's interior, though that might not be a bug, considering how little reason they should have (MOST OF THE TIME) to access it.

As stated, the turrets didn't fire on the CMO, but the also couldn't be disabled. First time I've seen this issue, but also the first time I've really interacted with the AI uplink on NBT.

**Comment by mikomyazaki** [comment]
I asked about this, apparently the CMO isn't supposed to have access only the CE, RD, Captain, HoS -- So I'll close this.

I'll check about the CMO not being shot by the turrets, though. Thanks.
