### ISSUE TITLE
Holomenu Bug with Centering

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#13250]
Every time you look at the text it changes [center] and [/center] to <center> and </center>

Every time

Very annoying
It shows up on the actual menu, ruining it
![grafik](https://user-images.githubusercontent.com/30761807/154997506-ca2d7d2a-0af3-409d-8a38-dbd1e6d1bf97.png)
![grafik](https://user-images.githubusercontent.com/30761807/154997376-27c803e2-937e-40b5-91e5-8b3202b030c6.png)
![grafik](https://user-images.githubusercontent.com/30761807/154997543-97182525-292f-4dad-8fb2-c2ca442fc318.png)

**Comment by deGurkin** [comment]
it keeps degrading 
![grafik](https://user-images.githubusercontent.com/30761807/154997683-7087afe0-c066-41d9-841f-a1c310f66aed.png)

**Comment by SleepyGemmy** [comment]
@deGurkin It's `[center]text[/center]`, not `<center>text</center>`.

**Comment by deGurkin** [comment]
yeah it keeps degrading, every shift I have to manually edit it back xD
