### ISSUE TITLE
Infinite roller beds (maintenance drone variation)

### ISSUE THREAD

**Issue by FlamingLily** [Aurorastation/Aurora.3#13268]
Step 1) Pick up roller bed with multipurpose gripper
Step 2) Activate gripper to deploy roller bed
Step 3) Roller bed deployed, gripper still holding roller bed
Step 4) Repeat steps 2 and 3 ad infinitum
![image](https://user-images.githubusercontent.com/80451102/155455906-df301889-1157-4ee9-adfd-49d7d52c43f8.png)
I'm assuming deploying the roller bed isn't properly deleting the reference to the roller bed stored in the gripper, so technically each roller bed duplicated is the same, but I'm not certain.

**Comment by mikomyazaki** [comment]
Likely the same bug as #12236 claimed to fix.
