### ISSUE TITLE
pAIs inserted into PDAs remain in your hand and in the PDA at the same time

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#13276]
When you insert a pAI into a PDA, the pAI is still in your hand but also referenced by the PDA, resulting in magical teleportation shenanigans if you drop the pai somewhere then right-click the PDA to eject it.

Ejecting the pAI from the PDA also seems to not properly clear whatever vars the PDA uses, and the PDA becomes hard locked from accepting anymore pAIs, even after ejecting the first one.

**Comment by SleepyGemmy** [comment]
issue #13288 may be related due to similarities.

**Comment by FluffyGhoster** [comment]
Is this still reproducible?

**Comment by FluffyGhoster** [comment]
Given the lack of a reply, I'll mark this issue as solved, if not, feel free to reopen it
