### ISSUE TITLE
High temperature Tank transfer bombs just deleting a single tile

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#13295]
Ive made a bomb that was -174C oxygen and 9477C phoron the bomb does explode however a single tile is deleted

![Explosion_Size](https://user-images.githubusercontent.com/51837452/156029375-6e65796d-91f3-4b83-9c64-517cb1b74e4b.png)
Ive tried it inside the station as some people on discord guessed that perhaps the reinforced tiles were just too strong
![Explosion_in_station](https://user-images.githubusercontent.com/51837452/156029476-f97c6fc5-13c8-4454-8c99-ba36e29c91eb.png)
here the explosion log
![Explosion_Log](https://user-images.githubusercontent.com/51837452/156029501-5261f19f-44e2-43b1-be5d-6d775db9adbe.png)
When the bomb explodes the oxygen canister gets deleted and the phoron one gets emptied
![phoron_cannister](https://user-images.githubusercontent.com/51837452/156029648-9e1a82a9-81a7-4113-ac98-f953ae8116b5.png)
 
____________________________________________
At first i had closed this issue because after talking with some discord perps they said it might be because since I'm using a local server some configs might be different from the actual server and that might be causing it however today (17/03/2022) i tried it on the actual server with the same setup and the same thing happened

![ActualSeverAttempt](https://user-images.githubusercontent.com/51837452/158903771-baff975e-500a-41bd-a056-f550a9c40f76.png)

Round id just in case it might be usefull: cgZ-c60X

**Comment by Karakamenk** [comment]
I'm a freak that reads bomb code, it's working as intended. Bomb code isn't dependent on high temperatures, more just molar  ratios and quantities of gas, above certain temperature thresholds.

**Comment by LeiteQualhado** [comment]
Man this an old one was made back in the Aurora, i'm going to close this for two reasons, first is that it doesn't matter anymore on the Horizon and second is that so far all TTV bombs work just fine so no idea
