### ISSUE TITLE
Biogenerator: Empty Cigarettes

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#13291]
The biogenerator does indeed produce empty cigarettes, once lit it will go through all it's material (0 Units) and die. 
The idea is you put something in there, with the ACME cigarettes literally anything, but Hopefully AT LEAST Tabacco and Ambrosia Vulgaris
But you can not put those in there, not ground up, not dried, not undried.
You can also not add other chemicals into the cigarettes from the biogenerator either.
Not from the box OR from the individual cigarettes.
This has happened with multiple packs over multiple Rounds and I believe this is unintentional.
The ability to add Tabacco leaves would be a minimum.
Adding Extra chemicals would be a Sweet plus, so I can make my Dyn Menthols and S'Rendarr's hand with Watermelon Flavouring.

**Comment by sheeplets** [comment]
Click on a beaker with a blank cigarette in hand to "dunk" them and soak up to 15u of whatever reagent is inside. You can grind tobacco leaves and do this to make regular cigarettes.
