### ISSUE TITLE
[NBT] Bar shutters power outage/desync issue

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#13301]
The Bar shutters do not properly close in the case of a power outage and then Desynch when power is back on
![grafik](https://user-images.githubusercontent.com/30761807/156247437-6ccd5ae5-b94e-4263-805c-69f09405e0e2.png)
This has happened multiple times and ReadthisnamePlz was there to see it

**Comment by SleepyGemmy** [comment]
possibly related to #13233?

**Comment by NonQueueingMatt** [comment]
Marking as fixed for now.
