### ISSUE TITLE
[NBT] Third-party Ship Captain Can't Access Kitchen Locker

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#13327]
![image14](https://user-images.githubusercontent.com/99297919/156902268-56c1c1a6-1eaf-4a25-8ab9-0cd3b1150043.png)
orion express vessel. the captain (and crew?) of the third-party ship can't access their own kitchen cabinet.

**Comment by NonQueueingMatt** [comment]
fixed
