### ISSUE TITLE
[NBT] Third party orion express shuttle leaves plating in space after it flies away.

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#13331]
Pictured.

![image](https://user-images.githubusercontent.com/52309324/156903661-a0977190-a0c5-4431-b41a-776c4f3a0aeb.png)

It targeted the Horizon hangar but a separate issue report https://github.com/Aurorastation/Aurora.3/issues/13330 noted that this ended up putting it in the space outside the bar lounge. Not sure if it'll keep leaving plating on other nav zones.

**Comment by NonQueueingMatt** [comment]
fixed
