### ISSUE TITLE
[NBT] Funerals are a bit gruesome

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#13337]
This is less of a bug and more of a quality of life complaint
![grafik](https://user-images.githubusercontent.com/30761807/156928904-252d79ec-0497-4130-af29-63459073de53.png)
One moment you are having a nice coffee in memory of your friend then he shoots by the lounge, hits a carp, the coffin opens and you see his rapidly crystalising corpse float by

**Comment by deGurkin** [comment]
I do not know how this works with the shields either

**Comment by Alberyk** [comment]
Not a bug.
