### ISSUE TITLE
[NBT] Third-party Vessel Can't Dock With the Horizon

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#13330]
orion express vessel. when trying to dock with the main vessel, there is no option to dock with the Horizon. when trying to dock with the main vessel's shuttle, there is an option for the mining hangar on the horizon, but it puts you outside in space near the bar lounge.

![image15](https://user-images.githubusercontent.com/99297919/156903595-e758d74c-d191-40a0-b955-d49bd4cd3e11.png)
pictured: the options for the main vessel's shuttle.

**Comment by NonQueueingMatt** [comment]
fixed
