### ISSUE TITLE
[NBT] Third party orion express shuttle can't land on the derelict or asteroids

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#13332]
You get a message about not finding any valid landing zones even if you're right on top of the derelict/asteroid. This is what both the main OX ship (I'd think that's intentional because its big) and the far smaller shuttle suffer from.

That said, it also might not be intentional that the smaller pod style shuttle can't seem to enter open space at all too. This could be because the orion ship itself already occupies open space too but I'm not sure.

**Comment by WickedCybs** [comment]
It couldn't land on the Horizon either. Which was strange, since I saw it was able to on a previous round, albeit in the wrong position.

**Comment by NonQueueingMatt** [comment]
fixed
