### ISSUE TITLE
Rat Ghost Spawner shows up to players

### ISSUE THREAD

**Issue by mikomyazaki** [Aurorastation/Aurora.3#13349]
See here for more details #13347 

Apparently shouldn't be visible to players without elevated permissions.

**Comment by mikomyazaki** [comment]
It does show up as disabled though. Soooo... idk if it needs to be invisible.

![image](https://user-images.githubusercontent.com/47489928/157041837-23a3969c-419a-4268-93a7-1ad835c552bb.png)

**Comment by SleepyGemmy** [comment]
still a bug.
