### ISSUE TITLE
[NBT] Being on Top of a Thruster Tile Is Extremely Loud

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#13342]
![image18](https://user-images.githubusercontent.com/99297919/156940396-7e0b3291-7c5a-483e-93b9-6f75ce805516.png)
standing on the "parent" tile of the thruster is extremely loud. this may not be an issue for the average player in a round, but i found out the hard way as a spectator.

**Comment by NonQueueingMatt** [comment]
not really a bug
