### ISSUE TITLE
Air Leaks Through Inflatables

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#13358]
when using inflatables to seal entrances, air will sometimes leak through even if you use it properly like an airlock. one example is if you build on the construction level on the aurora, air will somehow leak through two inflatable doors into space.

**Comment by mikomyazaki** [comment]
Can you provide a screenshot of a place + inflatable layout where this is happening?

**Comment by SleepyGemmy** [comment]
not applicable anymore as it only occured on the aurora (afaik).

**Comment by SleepyGemmy** [comment]
duplicate of #12877.
