### ISSUE TITLE
Dev: Request consoles cannot send messages

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#1338]
Attempting to send a message of any kind on a request console fails with the message `*The Requests Console beeps: 'NOTICE: No server detected!'`.

Faxing papers via. request console doesn't work either.

**Comment by Lohikar** [comment]
Was unable to replicate issue in later tests.
¯\\\_(ツ)_/¯

Someone else should probably take a look.

**Comment by NanakoAC** [comment]
ill look into it

**Comment by NanakoAC** [comment]
nope cant reproduce, may have been some transient issue
