### ISSUE TITLE
Medbots and Cleanerbots can't be built

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#13426]
The arms don't connect to the bucket/medbox :(

Other bots might not be able to be made too - farmbots, floorbots...

**Comment by Ben10083** [comment]
were you using any brand arms (zeng hu for example) or the unbranded ones?

**Comment by SleepyWolfe** [comment]
it was with the unbranded  - I noticed for some reason somehow the mech fabricator didn't have unbranded available to select in the brand options as well recently. I'm not sure if other people are having this issue, since I've been seeing mechbots in places on station.

**Comment by Ben10083** [comment]
> it was with the unbranded  - I noticed for some reason somehow the mech fabricator didn't have unbranded available to select in the brand options as well recently. I'm not sure if other people are having this issue, since I've been seeing mechbots in places on station.

I thought I had this issue as well, but someone pointed out I was using a prosthetic arm instead of robot arm 

Can you test the following:

- unbranded prosthetics
- branded robot arm
- unbranded robot arm

(If you can't find unbranded robot hats fine it's possible that was removed or renamed)

**Comment by Afya212** [comment]
Zero issues with it. This seems like a non-bug.
