### ISSUE TITLE
Cargo shorts unobtainable due to job name changes

### ISSUE THREAD

**Issue by anconfuzedrock** [Aurorastation/Aurora.3#13434]
![image](https://user-images.githubusercontent.com/18406892/162601380-0cabe17b-477a-4822-b17a-23d4005a7e0d.png)
This code doesn't work, they don't show up in loadout bcuz the job changed name. I Can only imagine how many similar issues exist.

**Comment by Alberyk** [comment]
Not a bug. This is outdated code.
