### ISSUE TITLE
Request Console forms still bear Nanotrasen headers instead of SCC ones.

### ISSUE THREAD

**Issue by Alfa1561** [Aurorastation/Aurora.3#13432]
The forms in the request console form printer all still have NT headers stating things like "NanoTrasen Inc. - Civilian Branch of Operation" instead of new headers referencing the SCC.

**Comment by Alfa1561** [comment]
This also applies to the warrants on the holoprojector

**Comment by Ben10083** [comment]
This has been solved according to @Lancer411.

**Comment by Ben10083** [comment]
CCIA claims they have solved this issue and to direct anything they missed to their head. This can be closed now I imagine.
