### ISSUE TITLE
Operations wristbound computer is non-functional, spawns with no parts.

### ISSUE THREAD

**Issue by anconfuzedrock** [Aurorastation/Aurora.3#13435]
![image](https://user-images.githubusercontent.com/18406892/162601437-e9691ad6-0987-4489-a4d4-1b74223d0dd5.png)
This bad boy starts with no parts when you get it. it doesn't even turn on. Presumably because of job stuff changes?

**Comment by Ben10083** [comment]
![image](https://user-images.githubusercontent.com/91219575/163450048-c6d4d37a-f776-4505-8e66-1f70c3fa793e.png)
Operation wristbound works fine on my end, tried it with Operations manager and hanger technician. @anconfuzedrock do you still have this issue?
