### ISSUE TITLE
Can't roll up sleeves of your uniform(s)

### ISSUE THREAD

**Issue by Vulcenus** [Aurorastation/Aurora.3#13479]
You can't roll up your uniform's sleeves in-game, which I believe is a critical issue. Tested and tried in-game for the PMCG uniforms, and I was able to replicate the issue three times successfully. Attached the image down below.
![sleeves3](https://user-images.githubusercontent.com/57201055/163029743-d08b7814-c1d1-46c3-ad17-14c308922218.png)

**Comment by KingOfThePing** [comment]
There are many uniforms that do not have rolled-up sleeve sprites. Not a bug.
