### ISSUE TITLE
Intrepid coming back with zero pressure on airlock and void exposed tiles when docked into the hangar

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#13472]
The two areas outlined in the circles had no pressure despite being in a well-ventilated area. Walking within would cause damage and oxyloss. This only really happens when the Intrepid comes back from a trip to space.

![image](https://user-images.githubusercontent.com/52309324/162903992-6ec06550-0766-47ef-888b-283894edcdf1.png)

At one point, the Intrepid was also stuck in a cycling loop because for the small airlock, one tile within had zero pressure (the one without the vent) and the tile with a vent had full pressure.

![image](https://user-images.githubusercontent.com/52309324/162897753-493a331b-91c9-456d-9599-fa2395df7b02.png)

**Comment by mikomyazaki** [comment]
For some reason the turfs in the airlocks aren't being assigned a zone when:
- The shuttle returns to the Horizon
- The airlock doors are opened on the Horizon

It works correctly in space however.

**Comment by mikomyazaki** [comment]
Looks like it's caused by TranslateTurf skipping some turfs if the shuttle is landing on the same type of turf as is placing down.
