### ISSUE TITLE
Orion shuttle pod can't return to the main ship after leaving

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#13491]
It seems like once it leaves, if it tries to return it gets no valid option to dock with the ship. The options only lead to space.

**Comment by SleepyGemmy** [comment]
![image](https://user-images.githubusercontent.com/99297919/163169701-15c8c86a-725a-41b1-9922-95c4412649a3.png)
confirmed.

**Comment by TheDanseMacabre** [comment]
Testing shows that the waypoint is leaving with the shuttle when the shuttle takes off
