### ISSUE TITLE
Xenoarch coolant.

### ISSUE THREAD

**Issue by gamermagnet** [Aurorastation/Aurora.3#135]
When Filling the Xenoarch  radiocarbon spectrometer with coolant you revive text about it being filled but nothing changes place (The bucket still has coolant even if the text says i have moved it)

**Comment by The-Green-Gamer** [comment]
happens to me too

**Comment by ArcBotSS13** [comment]
https://github.com/Aurorastation/Aurora.3/pull/300 It was missing the OPENCONTAINER flag.

**Comment by skull132** [comment]
Fixed in #300 .
