### ISSUE TITLE
All Robotic Grippers interact twice

### ISSUE THREAD

**Issue by Ben10083** [Aurorastation/Aurora.3#13508]
Every Robotic Gripper interacts twice with anything clicked, this breaks alot of interactions for synthetics.

**Comment by mikomyazaki** [comment]
I know this happens because it's happened to me. But I'm blanking on an item that it actually affects.

Can you give an example for my testings.

**Comment by Ben10083** [comment]
> I know this happens because it's happened to me. But I'm blanking on an item that it actually affects.
> 
> Can you give an example for my testings.

Power cell charger, if you try to click it with cell, it even shows how you place the cell then remove it

Disposal unit, you place item in, then you open screen

APC can't put in cell (unless that was lag but I doubt it)
