### ISSUE TITLE
Orion Express vaurcae spawn without needed items.

### ISSUE THREAD

**Issue by Ershovdi** [Aurorastation/Aurora.3#13526]
Spawned as a Vaurca Orion Express Courier. The game did not spawn a filter port on me and I started to die. That is a big problem for Vaurca players, please fix.   :)

**Comment by Ershovdi** [comment]
They also do not spawn with sandals on them.

**Comment by DaTruRiZZoB** [comment]
Does this also affect other races that require items, such as off-world humans?

**Comment by Ershovdi** [comment]
Didn't check it. Probably no? The Orion Express spawns might have hardcoded items, so the species' items don't spawn. Just a theory, though.

**Comment by Doxxmedearly** [comment]
Ghostrole species need to have specific outfits enabled. So for it looks like no species-specific outfits have been coded for any ghost roles (Probably an oversight). So, this would also affect offworlder humans, and any other species that might need specific items.
