### ISSUE TITLE
Opening photos in faxxes sent to CCIA causes a crash

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1357]

**Comment by Lohikar** [comment]
Always, or is there a specific trigger?

**Comment by SierraKomodo** [comment]
Not certain if there's a specific trigger; It happened to myself and the other CCIA online at the time when opening a fax sent to us. It had a standard paper form with two photographs attached to it.

**Comment by Ornias** [comment]
I was the other CCIA online and can confirm. This does not happen with all photographs, but I have a sneaking suspicion it's due to the photograph size due to how it's happened recently.

**Comment by Lohikar** [comment]
Tested a bit with both `master` and `development` and was unable to replicate.
It definitely sounds like it's a real bug though, maybe an edge case?
