### ISSUE TITLE
Cigarettes cause major organ failure (too fast)

### ISSUE THREAD

**Issue by JoeTheBroseph** [Aurorastation/Aurora.3#13609]
Smoking three or four cigarettes causes a toxin filter (mechanical liver) to fail, not sure if it's any different with an organic liver, but eventually the liver failure causes major organ failure. Tested this a couple times and almost certain it's due to cigarettes.

 There's probably some sort of toxin element in the cigarettes now which is too strong, I don't know. Either way, it's pretty game breaking to die off of three cigarettes.

![image](https://user-images.githubusercontent.com/37187170/164562827-8214e411-f4a9-4f20-bc85-23511724904e.png)

**Comment by mikomyazaki** [comment]
[See here for an explanation of this bug](https://github.com/Aurorastation/Aurora.3/pull/13616#issuecomment-1106714766)
