### ISSUE TITLE
Missing wire on deck 1 that cuts power supply to the port side of the ship

### ISSUE THREAD

**Issue by DragonHunter22** [Aurorastation/Aurora.3#13624]
There is a missing wire on the map that has to be placed every round in order to power the port side of the ship (including thrusters).
Cyan wire is the missing one.

![image](https://user-images.githubusercontent.com/6493802/164838105-2cf8756a-6a6a-4afe-9197-b513dd13268c.png)

**Comment by Ben10083** [comment]
Thanks for such a clear and concise report!
