### ISSUE TITLE
Lobby can duplicate characters

### ISSUE THREAD

**Issue by mikomyazaki** [Aurorastation/Aurora.3#13637]
e.g. HoSes appear in the Command AND Security departments? Should probably just appear in command. This problem happens with the crew manifest too tbh.

![image](https://user-images.githubusercontent.com/47489928/164943053-d935e116-219f-4230-b946-6ae87f16acee.png)

**Comment by Ben10083** [comment]
I mean I can see the argument of it being good that it shows it twice in the manifest, so you can see the entire dept at once instead of needing to check the command dept if they have a head.

**Comment by Arrow768** [comment]
I am pretty sure that's intentional.
