### ISSUE TITLE
A removed explosive from an explosive implant can't be reinserted into the implanter

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#1364]
Either it could be inserted into the implanter again or put onto a dish first. As it stands right now you are left with a useless explosive in your hand.

**Comment by skull132** [comment]
No implant can be reinserted after it's been removed, AFAIK?

**Comment by darkrising** [comment]
Well as it stands it seems pretty easy to pop one out by mistake as I found out.

**Comment by skull132** [comment]
How..?

**Comment by Pyrociraptor** [comment]
If you "activate" the implanter, it pops it out.
