### ISSUE TITLE
AI can see everything on the Starmap overlay regardless of if its turned on or not.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#13673]
Unsure if this is a bug or not but.

![image](https://user-images.githubusercontent.com/60306280/165089901-68744c0c-7088-4089-aafb-bc31824714c0.png)

**Comment by mikomyazaki** [comment]
It is very much a bug. Thank you o7

**Comment by Afya212** [comment]
Taj also seem to have this bug,
![image](https://user-images.githubusercontent.com/54920261/168130778-3530ad39-9704-4779-9434-bb8b5f7d65ad.png)

**Comment by FluffyGhoster** [comment]
Is this still present with the new overmap system?

**Comment by FluffyGhoster** [comment]
Since two months have passed with no answers, I'm gonna go with "no, it's not present anymore", feel free to open a new one regarding the new system if it's still happening however
