### ISSUE TITLE
Legionaire peacekeeper spawns in space on TCFL ship

### ISSUE THREAD

**Issue by Clem-The-Duck** [Aurorastation/Aurora.3#13683]
Tried to spawn as tcfl peacekeeper on the TCFL third party ship, spawned in space, then was gibbed after a minute or two. Tried to spawn again and it worked fine? There was one Prefect flying the ship when is spawned but i dont know if they were doing anything on the consoles. Round ID chD-aooU

**Comment by NonQueueingMatt** [comment]
Fixed.
