### ISSUE TITLE
Ghostspawn Bartender can not change the ghostspawn bar menu

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#13686]
says his ID doesn't have access.
He CAN change the barsign tho so that's good.

**Comment by Ben10083** [comment]
![image](https://user-images.githubusercontent.com/91219575/166127152-05eb0600-58df-4ce8-9b89-7acf1b9d776f.png)
I was able to edit the bar menu as the ghost bartender, are you sure it wasn't something else?
