### ISSUE TITLE
Can't repair lung rescue condition on undamaged lungs surgically

### ISSUE THREAD

**Issue by mikomyazaki** [Aurorastation/Aurora.3#13705]
`/decl/surgery_step/internal/fix_organ/can_use` has a check that prevents you doing this step if the lung is damaged. This will prevent you from fixing the rescued condition if your lungs are already healed up.

A workaround is to apply pneumalin, but the surgery step should allow you to perform it if the lung has `rescued = TRUE`. Probably via some organ specific proc override so we can use it for special damage types on other organs in future.

**Comment by VisVirific** [comment]
When you mention an organ specific proc override, would it be like ``if(I.unique_wound == TRUE)`` or something in the ``fix_organ/can_use`` use? or something else in general?

**Comment by mikomyazaki** [comment]
> 

I imagine it would look something like this:
```
/obj/item/organ/internal/proc/is_damaged()
    return damaged > 0

/obj/item/organ/internal/lungs/is_damagedl()
    return (..() || rescued)

/decl/surgery_step/internal/fix_organ/can_use(mob/living/user, mob/living/carbon/human/target, target_zone, obj/item/tool)
	if(!..())
		return FALSE
	var/obj/item/organ/external/affected = target.get_organ(target_zone)
	var/is_organ_damaged = FALSE
	for(var/obj/item/organ/I in affected.internal_organs)
		if(I.is_damaged())
			is_organ_damaged = TRUE
			break
	return is_organ_damaged
```

Or... maybe something else. The above assumes that any special condition you put in `is_damaged()` can be fixed via that specific surgical step. You'd probably want to think up better proc names.

Then if other organs ever have specific conditions that are fixed by that surgery step, they can have it included in their `is_damaged` too.

**Comment by VisVirific** [comment]
Mm! I see. I can see what I can do if you don't want dibs on this bug, then.

**Comment by mikomyazaki** [comment]
> Mm! I see. I can see what I can do if you don't want dibs on this bug, then.

I desperately do not want to touch surgery code if I can avoid it.
