### ISSUE TITLE
Warden's Newscaster and Armory Ion Rifle

### ISSUE THREAD

**Issue by VeteranGary** [Aurorastation/Aurora.3#13718]
On the Aurora, the warden office was equipped with a 'security newscaster' that allowed the warden to post wanted issues, and censor certain media channels within good reason. This is missing from the current warden's office on the Horizon, and it's bit an inconvenience as only the Head of Security office has one now. Typically, it was easier to delegate this task to the warden as they are most commonly present at the brig given an emergency/manhunt. Though as the space in the current warden office is pretty limited, it might have to be placed elsewhere, such as outside of the processing cubicles or in the security front desk.

Secondly, the ion rifle is missing from the security armory. Only posting this as a bug, as in the changelogs there is no note that this was intentional, or if it was moved to the crew armory. This removes a vital option of non-lethal from security that can disable energy weapons or non-lethally take down IPCs, as for the latter, the only way to non-lethally take down an IPC is with a stunbaton and hand-to-hand. If for whatever reason this method is too dangerous to use or ineffective, it essentially goes straight to lethals, which doesn't exactly seem like fair escalation. Practically any other species, ranged non-lethal can still be used if those tactics fail.

**Comment by Ben10083** [comment]
While I can likely map in the security newscaster, I am unsure if we should add a Ion Rifle, considering how strong they can be.
