### ISSUE TITLE
DEV: Accounts uplink terminal is missing a frame

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#1372]
The accounts uplink terminal in HOP office is a floating screen without a frame.

We should make it into a program in future, but for now that should be fixed

**Comment by Alberyk** [comment]
![nanamitake](https://cloud.githubusercontent.com/assets/11579997/21583889/ceee91d2-d07a-11e6-8bbf-faf25904624e.png)

No, it is not.
