### ISSUE TITLE
Crates Runtime

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#13734]
related code: `var/matrix/M = get_door_transform(I == (closing ? num_steps : 0) ? 0 : animation_math_list[closing ? num_steps - I : I], I == (closing ? num_steps : 0) ? 1 : animation_math_list[closing ?  2 * num_steps - I : num_steps + I])`
found in: crates.dm, L54
runtime:
> proc name: animate door (/obj/structure/closet/crate/animate_door)
> source file: crates.dm,54

**Comment by FluffyGhoster** [comment]
This is fixed
