### ISSUE TITLE
TCFL Ship has radio repeat three times

### ISSUE THREAD

**Issue by Ben10083** [Aurorastation/Aurora.3#13786]
![image](https://user-images.githubusercontent.com/91219575/166847680-cd61e782-f83a-4abd-af8f-1a46a484f8d0.png)
Its normal for it to do it twice due to current wonkyness, but this round (chL-dLjU), there were three.

**Comment by Doxxmedearly** [comment]
I saw this in one round, but not the other. I think it repeats for every active ship out there (We had TCFL, FSF, and OE active)
