### ISSUE TITLE
Bicaridine overdose doesn't appear to fix internal bleeding

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#1379]
I used to use this method quite a lot, 30+ units of bicaridine should cause an overdose that repairs internal bleeding. However, it appears it doesn't work anymore.

**Comment by NanakoAC** [comment]
I'm not sure it ever did work to begin with. 
Fixed in #1385

**Comment by skull132** [comment]
FML when I forget to hotkey the fucking autoclose.

This will be fixed shortly on Master. Closing now because really can't be arsed to comb these without autoclose.
