### ISSUE TITLE
Gun accuracy is fucked to all hell

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#138]
I find myself (and others) missing an awful lot in point-blank environments and even in longer range engagements.

For example, this happened today in a hostage situation:

http://puu.sh/n7ZK3/0c261ff2e9.png

So, basically, what happened was that somehow the point-blank shot totally fucking MISSED the intended target, the hostage, whizzed past the head of security, hit the cadet behind him and disintegrated her fucking arm and caused the poor gal to be forced to get a new robolimb.

While this is utterly hilarious, this is going to lead to rage-inducing instances of inconsistent gunplay and constant missing because baycode spacemen apparently graduated at the Stormtrooper Marksman academy. Gun accuracy is gonna need some tweaking.

**Comment by LordLag** [comment]
http://2static.fjcdn.com/pictures/Xcom+miss_bd06da_5830505.png

**Comment by OneOneThreeEight** [comment]
http://i.imgur.com/GFQg4s7.jpg

**Comment by skull132** [comment]
Accuracy does need a look over. Enhancement it is.

**Comment by K0NFL1QT** [comment]
Were you aiming at a limb? I unloaded six rounds of detectives .45 at a wizard to try and break their hand and make them drop their staff. Every shot was on target but 'narrowly missed'. When I aim at centre mass I don't get any such problem.
