### ISSUE TITLE
Dev: Medical Diagnostics Scanner's sprite is facing the wrong direction

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#1380]
![2017-01-02_17-30-32](https://cloud.githubusercontent.com/assets/7097800/21597495/3e4d42b2-d111-11e6-8010-ec36607901cb.png)

**Comment by NanakoAC** [comment]
the console also isnt animated and the bed doesnt have the pulsing light it should have

**Comment by NanakoAC** [comment]
fixed by #1388
