### ISSUE TITLE
3 AI-related rooms are missing wires connecting their respected APC's

### ISSUE THREAD

**Issue by DragonHunter22** [Aurorastation/Aurora.3#13836]
There are missing wires in 3 rooms related to the AI core. There is no wire connecting the APC's to the grid. Pictures included.
Pictures 2 and 3 are pretty straightforward. Missing wires.
Picture 1 (The AI core) is a bit weirder. Seems like the green wire doesn't go anywhere and the yellow one is unpowered.
![Posnetek zaslona 2022-05-08 174140](https://user-images.githubusercontent.com/6493802/167303912-49aa0b61-2e59-427a-bffe-3336cefe974d.png)
![Posnetek zaslona 2022-05-08 172602](https://user-images.githubusercontent.com/6493802/167303913-cc5a5526-af8d-4c96-a850-98599dfe11bd.png)
![Posnetek zaslona 2022-05-08 172536](https://user-images.githubusercontent.com/6493802/167303916-50668784-a76a-4203-86f6-4c06798d7d44.png)

**Comment by Afya212** [comment]
This is testmerge related* 

Also should be fixed in the next round.
