### ISSUE TITLE
Rolling up sleeves makes Blue Surgeon's Scrubs invisible.

### ISSUE THREAD

**Issue by RisingValiant** [Aurorastation/Aurora.3#13920]
Should be showing the blue scrubs sprite, isn't.
![image_2022-05-13_074054456](https://user-images.githubusercontent.com/105501502/168296320-22106242-ffa8-4369-8136-8cca63c1da78.png)

Spoke to Faris1 about the issue

**Comment by RisingValiant** [comment]
I think it might've been my loadout, the normal scrubs sprite is fine.

**Comment by RisingValiant** [comment]
Not the loadout, it happened again for some reason, no idea why.
![image](https://user-images.githubusercontent.com/105501502/168318253-e2158cea-64a9-48f7-879e-6b47ce20bd3a.png)

**Comment by RisingValiant** [comment]
I figured it out, the scrubs turn invisible when you roll up sleeves.

**Comment by NonQueueingMatt** [comment]
Should be fixed.
