### ISSUE TITLE
PMCG Sunglasses missing sprite/Warden Advanced Aviators gone

### ISSUE THREAD

**Issue by VeteranGary** [Aurorastation/Aurora.3#13928]
https://prnt.sc/hEim3tKqxLQ5

Sprite does not show at all when these glasses are worn, at least on tajara specifically, not tested on other species. Additionally, the warden does not seem to spawn with the advanced aviators with the addition of these glasses, would be preferable if these were optional, such as moved to the warden's locker or selectable in loadout as warden/hos. Believe these are the same as HUDsunglasses but just different sprite.

**Comment by alsoandanswer** [comment]
fixed
