### ISSUE TITLE
Ghost Roles see AOOC

### ISSUE THREAD

**Issue by Ben10083** [Aurorastation/Aurora.3#13934]
![image](https://user-images.githubusercontent.com/91219575/168398872-947a3e47-7840-4997-a778-449db0c71c20.png)
As title says, some ghost roles like with away sites can see AOOC, even when they really shouldnt. They can't speak on AOOC, but can listen into antags planning whatever they do.

**Comment by NonQueueingMatt** [comment]
This is because they spawn with a special_role var.
