### ISSUE TITLE
"Bridge" access showing up twice.

### ISSUE THREAD

**Issue by Afya212** [Aurorastation/Aurora.3#13949]
On the guest pass terminals and the ID modification panel 'Bridge' access and 'Bridge Crew' access both show up as 'Bridge' and are both toggled with each other. I wasn't able to duplicate this locally so I assume it's a config/DB thing.
![image](https://user-images.githubusercontent.com/54920261/168452516-2fe0ab43-afcf-4ebd-bd8b-658651393986.png)

**Comment by NonQueueingMatt** [comment]
Tried this on live, it seems to work fine. I don't see duplicated access, so it must've been fixed.
