### ISSUE TITLE
Moving the CCIA shuttle creates a hole in the hangar below

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#13946]
Just saw the CCIA shuttle move from the dock behind the chaplains office. Moments later the hangar below got an atmospheric alarm. Checking with the AI shell I found 6 holes in the roof in the lower-left corner of the mining shuttle hangar.

**Comment by SleepyGemmy** [comment]
for informative purpose: the issue appears to be shuttle code related.
