### ISSUE TITLE
Consular Office buttons do not work 

### ISSUE THREAD

**Issue by connorjg1** [Aurorastation/Aurora.3#13941]
Desired result: Pressing the Consular Office Door and Door Bolt buttons should open the door and bolt the door appropriately.
Actual result: The Consular Office Door and Door Bolt buttons do neither of those. 

Steps to reproduce:
Spawn as Consular
Press door buttons 
Witness as nothing happens

**Comment by Afya212** [comment]
This also goes for the buttons to leave medical, they don't open the doors anymore.

**Comment by SleepyGemmy** [comment]
can't replicate.

**Comment by SleepyGemmy** [comment]
caused by #13910.
