### ISSUE TITLE
You Spawn in Uniform Instead of Loadout Attire

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#13944]
you spawn in your uniform instead of in your loadout attire now, which means that you have to turn nude for 0.1 seconds every shift so you can put on your customized clothing.

the responsible code seems to be:
![image](https://user-images.githubusercontent.com/99297919/168447388-ef51e100-f0f4-473e-8f7e-7c22ac34ea5d.png)
from #13936.

**Comment by Ben10083** [comment]
![image](https://user-images.githubusercontent.com/91219575/168441147-8089e0b4-4788-4d65-a8b8-51649b2c589c.png)
Seems the priorities changed for it, loadout is chosen over your job gear

**Comment by alsoandanswer** [comment]
Not a bug. this is a subjective thing
