### ISSUE TITLE
Oqi Uniform spawns an Ix Uniform instead

### ISSUE THREAD

**Issue by Jakers457** [Aurorastation/Aurora.3#13958]
Spawning the Oqi work uniform, specifically medically, produces an Ix Uniform instead. 

This can be replicated by choosing it in the loadout or spawning with the admin menu, it might just be the wrong sprite assigned under the codex or pathing. I don't speak coder

**Comment by NonQueueingMatt** [comment]
Sprites are accurate, name is wrong.
