### ISSUE TITLE
Fleet Shorts Exposed Butt-Crack

### ISSUE THREAD

**Issue by mogsinald** [Aurorastation/Aurora.3#13972]
In the character setup there are a selection of boxer shorts that you can wear. All of them have correct positioning that a normal person would wear them except for one, the fleet shorts, which exposes a tiny bit of the sprites ass crack.

Shorts, Army:
![image](https://user-images.githubusercontent.com/105111153/168547825-3c5ddab8-4021-4b55-a171-ebca8c4d580a.png)

Shorts, Fleet:
![image](https://user-images.githubusercontent.com/105111153/168547844-555c36c6-c729-4366-a63e-c013419edbde.png)

As you can see the fleet shorts are positioned slightly lower. Unless this is an intentional feature for characters to flaunt their booty please fix.

**Comment by Ben10083** [comment]
Not a bug.
