### ISSUE TITLE
You can look through walls with a Photocamera

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14019]
Yeah uh, so I found this out on accident
maybe it only works on moving mapspaces like Elevators.

**Comment by deGurkin** [comment]
![grafik](https://user-images.githubusercontent.com/30761807/169395702-74cee0df-4d06-4815-a1d8-13cdc11a83ae.png)

**Comment by SleepyGemmy** [comment]
duplicate of #6749.

**Comment by deGurkin** [comment]
Oh my I am sorry

**Comment by JohnWildkins** [comment]
> Oh my I am sorry

no worries king, better to report a bug twice than not at all
