### ISSUE TITLE
The static alarm monitoring console on the bridge displays nothing.

### ISSUE THREAD

**Issue by GrayRachnid** [Aurorastation/Aurora.3#14032]
![image](https://user-images.githubusercontent.com/6613514/169615375-8119bbae-7500-4053-a3f1-0e617d566841.png)

Checked it with Bridge Crew access. Unsure if it needs engineering access to display anything but I doubt that.

**Comment by Afya212** [comment]
Not a bug exactly. You need engineering or sec access to see it.

**Comment by stobarico** [comment]
> Not a bug exactly. You need engineering or sec access to see it.

It's a bug for sure, had a round that the Captain themselves checked and it was blank for them too. Easy fix would be just changing it to a multipurpose computer, maybe a research preset since it's right next to the messaging server monitor.

Also, yeah, still an active bug
