### ISSUE TITLE
Issue with the syringe dart

### ISSUE THREAD

**Issue by CaptainGecko** [Aurorastation/Aurora.3#14031]
![image](https://user-images.githubusercontent.com/94259758/169609181-3406da77-760d-492f-b3d5-980226dc1187.png)

More of an oversight than an actual glitch, but still.
The old syringe dart was just the normal syringe sprite aligned with the dart's "tail". The new syringe sprites are very cool, but also no longer align with the dart's tail, as you can see on the picture above. We're going to need a new sprite for the tail-end I assume, adjusted to the new syringes.

**Comment by Cairo283** [comment]
Note that the syringe used in this situation was a large one, not a normal 15 unit one.
