### ISSUE TITLE
When stashing something in a plant and pulling it out you get the same type item not same amount

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14044]
So for a gimmick I was stashing phoron crystals in a potted plant, after pulling it back out I had 1 Crystal instead of 10
Which really fucks with the gimmick
![grafik](https://user-images.githubusercontent.com/30761807/169668332-d3d8c60d-b001-4a92-9b69-4a2f155943a7.png)
10 go in 1 come out.

**Comment by SleepyGemmy** [comment]
did you examine the item and verify the stack amount?

**Comment by NonQueueingMatt** [comment]
Tested and I can't reproduce it. When you pick up the phoron stack the text on it doesn't show up, but you still get all 50 of them.
