### ISSUE TITLE
Nobody can use Security cameras on green

### ISSUE THREAD

**Issue by honkel** [Aurorastation/Aurora.3#14042]
Revision unknown
Current Map: SCCV Horizon

CE can't check cameras on the SM, Captain can't look at anything, etcetera etcetera.

This does not apply to the XO laptop, have not tried it with other laptops. Downloaded camera program may bypass the restrictions

EDIT: I cannot English

**Comment by SleepyGemmy** [comment]
probably caused by #13993.

**Comment by GrayRachnid** [comment]
Addition: The static security camera consoles do not update when the alert changes. They remain locked to whatever is on green.

**Comment by NonQueueingMatt** [comment]
This is fixed by #14061. Only applies to the static camera consoles.
