### ISSUE TITLE
People are popping out of cryocells whenever I move.

### ISSUE THREAD

**Issue by RisingValiant** [Aurorastation/Aurora.3#14057]
I've seen this happening before but the dev I talked to the first time I saw this couldn't reproduce it locally, I have no idea why it's happening but here's some things that might narrow it down: 
- It isn't me grabbing them and dragging them out, that was the first thing we thought, and the most recent time it happened I never even touched the person aside from putting them in the cryocell
- It might be specific to my species? I'm playing a dionae surgeon, normal, not coeus.
- I've usually seen it in the leftmost cryocell in medical, temperature is 123 kelvin, chemical was cryoxadone in the most recent case.

Like I said, no idea what's causing this, it's an elusive one though, Game ID is ch4-aFO0

**Comment by GrayRachnid** [comment]
I've had this happen to me. Unrelated to species. The only thing that happened to mine is someone else took them out, and I couldn't put them back in the same cryocell. Had to put them in another.
