### ISSUE TITLE
monocycles and spacebikes seemingly do not function

### ISSUE THREAD

**Issue by Dahbunny** [Aurorastation/Aurora.3#14069]
While i could just be missing something the ridables with the acception of the janicart seem to miss hud elements and interfaces that allow them to be ridden, you can mount them and put up the kickstand but there is no way to start the engine and moving simply gets off of them

**Comment by NonQueueingMatt** [comment]
The engine works. The kickstand needs to be down first, then you can control click the bike to start it, then alt click to pull up the kickstand.
