### ISSUE TITLE
Tea pots have a default weird offset.

### ISSUE THREAD

**Issue by GrayRachnid** [Aurorastation/Aurora.3#14071]
I'm not sure if this applies to all of them, or just the one on the bridge normally.
![image](https://user-images.githubusercontent.com/6613514/169718649-be8454b8-0d26-4957-ac7e-21c54281da2a.png)
I clicked where my mouse it, and it ended a few pixels above it.

**Comment by deGurkin** [comment]
Oh a bunch of the Vaurca drinks have the same issue
and the bar menu
