### ISSUE TITLE
Ghostspawn Cargo freighter Unloader does not work, neither does the smelter

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14084]
![grafik](https://user-images.githubusercontent.com/30761807/169910085-940dffa1-fd28-4a4d-bba7-07492cb1d826.png)
Sat there for like 20 minutes lookin like this, so I took ou the railing and put the ore in manually, still didn't work

Round before ch5-dqxf
Yonnimer was there
One of the coders of the Freighter was there, equally as confused
Round had to be manually restarted so it may be a ticker issue

**Comment by TheDanseMacabre** [comment]
This is an overmap issue, I believe. However, if you disassemble and reassemble the machines, they will work properly.

**Comment by deGurkin** [comment]
been patched with the ship spawning on the map
