### ISSUE TITLE
New Guest Pass Terminals are broken

### ISSUE THREAD

**Issue by GrayRachnid** [Aurorastation/Aurora.3#14098]
![image](https://user-images.githubusercontent.com/6613514/170111665-dcaa49f7-03f0-472b-8a2e-677308c2545c.png)

**Comment by SleepyGemmy** [comment]
![image](https://user-images.githubusercontent.com/99297919/170118771-4ceb3e51-4268-4117-bb4d-3d7754de0ea5.png)
can't replicate.

**Comment by SleepyGemmy** [comment]
could be related to the new computer sprites PR being testmerged.

**Comment by JohnWildkins** [comment]
related to test merge, has been resolved
