### ISSUE TITLE
You cannot deconstruct reinforced walls

### ISSUE THREAD

**Issue by Forester40** [Aurorastation/Aurora.3#14108]
The deconstruction process for reinforced walls gets stuck on the second welding tool step. You can do the step, but afterwards nothing happens to the wall and you can still use a welding tool on it again and again and it never goes forward to the step where you can use a wrench.
To reproduce, just try and deconstruct a wall.

**Comment by deGurkin** [comment]
Have you tried applying the crowbar 20 times?
I have deconstructed many a wall and I have never run into this issue

**Comment by Dreamykass** [comment]
I just tried it on horizon, and yes, it works there.
There was a round yesterday, with an expedition to the thrashed sol base -- and we couldn't deconstruct any reinforced wall. A few people have tried it, including me.
It just stopped on the "Use a Welder to weld through the external support rods", and couldn't go forward (clicking with a crowbar did nothing).
