### ISSUE TITLE
Powernet is totally borked

### ISSUE THREAD

**Issue by FlamingLily** [Aurorastation/Aurora.3#14124]
![image](https://user-images.githubusercontent.com/80451102/170810753-9d67f78c-0863-4f41-9b98-b55dad40be12.png)
![image](https://user-images.githubusercontent.com/80451102/170810765-00d754f7-3201-4f71-9b91-f3585d3fe3e6.png)

External Power Good:
![image](https://user-images.githubusercontent.com/80451102/170810830-bd431038-3943-4597-8c39-78970957dd66.png)

Looks like the powernet only updates when an APC powering cable is cut (even then I'm not sure on the extent). This  is. Really broken.

**Comment by SleepyGemmy** [comment]
can replicate on master a5e6852ac4fa00559f9e83c16bf625112c027034.

**Comment by SleepyGemmy** [comment]
possibly caused by #13988.
