### ISSUE TITLE
The PACMAN generator (portable generator) spawn with the wrong fuel in the crate

### ISSUE THREAD

**Issue by DragonHunter22** [Aurorastation/Aurora.3#14123]
So the old PACMAN generator (Now called the portable generator) in engineering storage used to run on phoron sheets, which still spawns in the yellow crate next to it. Since the generator now runs on graphite, the phoron sheets are useless, and most likely an oversight that they haven't been replaced by graphite.
![image](https://user-images.githubusercontent.com/6493802/170807808-03946ae9-6a69-4f6d-9a79-4ae26a0a37aa.png)

**Comment by SleepyGemmy** [comment]
will fix.
