### ISSUE TITLE
[bug] Xenobotanist doesnt have Hydroponics access

### ISSUE THREAD

**Issue by DisreputableSquid** [Aurorastation/Aurora.3#14143]
The Xenobotanist doesnt appear to have hydroponics access, as it is unable to open Strange Seed Packet crates ordered from cargo.

**Comment by SleepyGemmy** [comment]
they shouldn't have hydroponics access, but they should have access to the crates.

**Comment by SleepyGemmy** [comment]
this is a cargo database issue and can only be fixed by maintainers (?).
