### ISSUE TITLE
Siik'Maas and Siik'Tajr should be more distinguishable

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#1416]
At the moment both languages "mrowl" and there's not really much differences between the look of the two on screen. Siik'Tajr is a tiny bit more red. Perhaps changing the sound from 'mrowls' to something different and/or changing the font colour to be more unique.

**Comment by Alberyk** [comment]
Siik'tajr is not full verbal, as in, it has signs verbs and can't be fully understood over the radio, unlike siik'maas.

**Comment by Geevies** [comment]
Die, tajara, die.
