### ISSUE TITLE
Powernet still not updating when needed

### ISSUE THREAD

**Issue by FlamingLily** [Aurorastation/Aurora.3#14175]
#14130 fixed the powernet not updating when a wire was cut, but it still fails to update elsewhere, including when SMES outputs are updated, and potentially when breakerboxes toggled (unconfirmed)

**Comment by JohnWildkins** [comment]
Was able to find another issue relating to machines not being disconnected properly from the powernet when node wires were cut, but I can't replicate any issues with toggling the output on SMES. Is there a particular reliable method of doing so?

**Comment by FlamingLily** [comment]
Haven't seen this happen for a while, will re-open if I see it again
