### ISSUE TITLE
New Intrepid redesign has no walls

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14171]
![grafik](https://user-images.githubusercontent.com/30761807/171420711-1046b157-6b3c-459e-897d-4ffea32b57c4.png)
Unsure if it is even airtight

**Comment by SleepyWolfe** [comment]
those are windows in the wing, pretty sure.

**Comment by SleepyGemmy** [comment]
> those are windows in the wing, pretty sure.

no, just technical greebles.
