### ISSUE TITLE
Sounds don't play while inside of voidsuit cyclers/sleepers/medical scanners - You can't hear (or see) speech from nearby players or radios either

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#14192]
Sounds used to play just fine, I've noticed this as a recent development in the past few days. Maybe a bit longer. It seems like everything on the outside of these is muted as long as you sit inside. You also can't hear anyone speak, or see their chat bubbles.

Also seems to be intermittent and/or dependent on the individuals? I've personally experienced it while in the cyclers, others reported it while in the scanners in LOOC. A recruited volunteer claimed to not have issue with the cyclers after I had mere moments before.

**Comment by sheeplets** [comment]
Omega clog

**Comment by Ben10083** [comment]
Also affects Rechargers

**Comment by Ben10083** [comment]
Happens when in disposals as well

**Comment by Doxxmedearly** [comment]
I suspect it's related to #13913 as discussed in the code dungeon earlier today, 6/3
