### ISSUE TITLE
When windoors lose power they turn invisible

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#14193]
Title. Noticed in the medical bay after a blackout, all of the windoor sprites disappeared until they were interacted with.

**Comment by sheeplets** [comment]
![image](https://user-images.githubusercontent.com/44004468/171878378-ede7e09e-78a8-44d8-9312-1a07dc50d6aa.png)

**Comment by SleepyGemmy** [comment]
duplicate of #14037.

**Comment by Ben10083** [comment]
Duplicate of #14037
