### ISSUE TITLE
Cargo Bay Screen

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#142]
The Bridge's Status Screen overrides the Cargo Bay's ETA Screen.

**Comment by SierraKomodo** [comment]
This may have already been fixed and this issue report just wasn't closed. The two status screens in the cargo lobby/QM's office display the shuttle timer no matter what I set the bridge status display to. As a note, setting the bridge status display /does/ set the display on the cargo consoles as well, but it gets changed back to the shuttle timer (IF the shuttle timer is active) after a few seconds.

![rsehserdhredh](https://cloud.githubusercontent.com/assets/11140088/19839104/7c1bbc86-9e99-11e6-8722-7939a4a321a3.PNG)

**Comment by Bedshaped** [comment]
Closing. Please repost if the issue wasn't fixed.
