### ISSUE TITLE
Floor decals in cargo don't always show up as they should

### ISSUE THREAD

**Issue by Llywelwyn** [Aurorastation/Aurora.3#14263]
the coloured floor markings denoting sorting piles for cargo seem to just arbitrarily not show up sometimes - has something to do with changing z-levels. not sure exactly how it happens, just sometimes when going up/down the stairs they decide to either show up or not. it happens on both z-levels -- whilst on the actual warehouse floor and when looking down from above.

![image](https://user-images.githubusercontent.com/82828093/172755724-bcf6de3f-1bf6-44b3-864b-d92c0cdba822.png)

![image](https://user-images.githubusercontent.com/82828093/172755741-a268e98a-745f-4727-96e7-7bdcdb4455c9.png)

**Comment by SleepyGemmy** [comment]
bug confirmed. i have seen this happen with other floor decals too.

**Comment by JohnWildkins** [comment]
Appears to be fixed by #14495
