### ISSUE TITLE
Ghostspawn issue - TCFL ship

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14275]
![grafik](https://user-images.githubusercontent.com/30761807/172923452-31258640-0a9e-4091-b61a-29aea1cbc022.png)
There do not appear to be any navpoints for shuttles to spawn in on for the TCFL ship map

**Comment by Doxxmedearly** [comment]
Is this during the testmerge of #14224 ?

**Comment by Doxxmedearly** [comment]
Oh yeah, it would be. This is because ships are no longer subtypes of shuttles and thus don't autogenerate their own away points. Hrg.
