### ISSUE TITLE
Xenobotanist Access issue - Hazardous Specimens lab

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14290]
![grafik](https://user-images.githubusercontent.com/30761807/173130009-27472de3-2c30-4f5e-a8b1-2195a509b3a8.png)
The Xenobotanist does not have access to the Hazardous Specimens Air Controller when inside the room.
This means someone can lock him in there and mess with the air controls
it also means he can not manually override it in case of a serious emergency.
The Xenobotanist should have access to air control in the Hazardous specimens Room

**Comment by SleepyGemmy** [comment]
will fix.
