### ISSUE TITLE
floor tiles off of the horizon currently have no traction.

### ISSUE THREAD

**Issue by Dahbunny** [Aurorastation/Aurora.3#14304]
For example as of last night, mag boots are not working on the shuttle when moving, resulting you being juggled, and in open space mag boots are not sticking to bridges made by miners (floor tiles, normally to prevent "slipping") or dirt tiles, you can still adhere to scafold however (just rods), unsure if it was a problem just for that round, will update as i test more.

**Comment by Doxxmedearly** [comment]
This has been noted to happen on away sites as well (See #13723), though I will see if it may have been caused by #14257 accidentally.
