### ISSUE TITLE
Setup Character color squares are 'blue' when RGB values are 8,8,8

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1430]
This is the second right-most selection on the gray scale bar in the 'Standard' color selection tab (Right-most if you don't count the bigger swatch that is 0,0,0/pure black). The color square next to 'Change Color' displays blue instead of a really dark gray. The actual sprite displays the correct color.

**Comment by skull132** [comment]
Missing padding, probably?

Which colour, skin colour?

**Comment by SierraKomodo** [comment]
Hair color is what I caught the bug on, didn't test other slots or RGB codes. I did notice things seemed to be a bit off when updating my other characters however.
