### ISSUE TITLE
Supermatter overheating easily

### ISSUE THREAD

**Issue by courierbravo** [Aurorastation/Aurora.3#14322]
The supermatter is overheating incredibly easy. 15 shots with the normal 2 cold - 2 hot Hydrogen setup still requires intervention to prevent delam. Unsure if its related to supermatter heat output or radiators not working as intended. 
What should be happening is that the supermatter can handle 40 - 45 shots from the emitter with a 2-2 hydrogen setup without requiring any intervention. Using methods like replacing either cold or hot loop with phoron (the better of the two for heat transfer) doesnt seem to improve much. 
This is resulting in sub-optimal power output, making using the engine difficult and unreasonable.

**Comment by courierbravo** [comment]
I'm currently running tests on the live server. Some players and I were talking and there's a theory that its to do with the output rate not being high enough. So, what's normally an output rate of 100L, ive increased to 300L, then put 12 shots into the engine.

**Comment by FlamingLily** [comment]
Unsure if there's any recent changes that have changed this but not too long ago I ran a 35 shot 2:2 setup as described above and it didn't have any issues, so it's possible that it's really inconsistent (Or there's been a recent change which is causing the issue)

**Comment by NonQueueingMatt** [comment]
Fixed
