### ISSUE TITLE
Economic Status Impoverished does not properly work

### ISSUE THREAD

**Issue by EmperorJayJay** [Aurorastation/Aurora.3#14328]
When setting up my character I will select Impoverished.
![image](https://user-images.githubusercontent.com/107105300/173924461-668d6e7f-d7a3-4ec9-b9c8-dd7bc5a8ab98.png)
Upon saving and reloading this will reset to poor. I am saving it during this.
![image](https://user-images.githubusercontent.com/107105300/173924591-e1873106-0b6b-4690-a078-29bb8f9235a8.png)

**Comment by SleepyGemmy** [comment]
the SQL database needs to be updated to allow the "impoverished" enum, according to Matt on the discord.
