### ISSUE TITLE
Borg Custom Sprite Issue

### ISSUE THREAD

**Issue by MaitreCrabe** [Aurorastation/Aurora.3#14337]
After having played a bit as WYVERN lately, I noticed the custom sprite had a few issues. First of all, the eye light was missing, both in help and harm intent. As well as a straight black bar right underneath the sprite that isn't supposed to be there, as well as a few issues with said eye, such as a few green pixels moving during the walking animations, making it look like the borg is blinking, something that wasn't intended in the original sprite. Below this, you will find the link to a video of the latest round I've played with WYVERN (On the 17th of June). The original sprite remains at your disposal if you wish to compare it to the video.

https://youtu.be/5Nhqz8EcwzE
[WYVERNcustomborg.zip](https://github.com/Aurorastation/Aurora.3/files/8933306/WYVERNcustomborg.zip)

**Comment by SleepyGemmy** [comment]
related issue (?): #14307.
