### ISSUE TITLE
Papers spawned in comms consoles from a command report use the 'empty paper' sprite

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1433]
Prior to the merge, the spawned papers had the 'Stuff's written on me' sprite. The papers do have contents when you examine them.

**Comment by Jennalele** [comment]
Also true for papers that come from the virology disease analyzer.

**Comment by printer16** [comment]
And supply manifests.

**Comment by Lohikar** [comment]
This will be true of any paper that's spawned in with its contents already written in; papers written on manually are fine.
