### ISSUE TITLE
Faction Selection Issues

### ISSUE THREAD

**Issue by Triogenix** [Aurorastation/Aurora.3#14345]
Nanotrasen has a typo in departments
![Screenshot_288](https://user-images.githubusercontent.com/73185699/174492639-9276da67-93eb-480e-9ad6-8fcdc38ff26f.png)

The SCC is missing Service from their departments(bridge crew are service.)
![Screenshot_289](https://user-images.githubusercontent.com/73185699/174492670-9181b9c9-a29e-4631-b961-9dcb58f336b4.png)

**Comment by JohnWildkins** [comment]
Fixed by #14347
