### ISSUE TITLE
New APCs cannot be mounted on spaceship alloy walls

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#14350]
Trying to mount an APC frame on a spaceship alloy wall just results in the standard 'you push on the wall' action to check for false walls. This means you cannot, for example, replace a destroyed APC in the propulsion areas.

**Comment by SleepyGemmy** [comment]
this is because the ship's walls are of a "cardinal" subtype, which returns any attacks applied to it without doing anything.
