### ISSUE TITLE
Nitrile glove box issues

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#14374]
Introduced with #14283.

Glove boxes are too small to fit the added xeno-gloves, and it's no longer possible to snip the tips off to jank them into existence using anything sharp. Wirecutters, plant cutters, knives, scalpels, broken glass, etc.

Downgrade in every regard, IMO, even working as intended.

![image](https://user-images.githubusercontent.com/44004468/175845423-6e3ed6de-c983-462e-a8f8-34f46c882786.png)

![image](https://user-images.githubusercontent.com/44004468/175845295-6774a566-852d-4c73-a788-fe8541c4c4c3.png)
![image](https://user-images.githubusercontent.com/44004468/175845234-c5d846d9-5e7f-4c40-813c-e24ff32155c0.png)

Three boxes of them also got mapped into the OR walls.

**Comment by KingOfThePing** [comment]
fixed https://github.com/Aurorastation/Aurora.3/pull/14378
