### ISSUE TITLE
Alt clicking tiles as a ghost does not bring up the 'floor' tab to see items on that tile

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1438]

**Comment by skull132** [comment]
I don't think it ever did?

**Comment by SierraKomodo** [comment]
No, but it's still a bug IMO. Just one that was never actually reported.

**Comment by MarinaGryphon** [comment]
Unsure if this is still an issue or if it's even a bug to begin with.
