### ISSUE TITLE
CCIA Agent security HUD icons show a question mark instead of the NT icon

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1439]
![waegaweg](https://cloud.githubusercontent.com/assets/11140088/21745197/8c313fde-d4da-11e6-9a1c-2143c468d4a0.PNG)

**Comment by HunterRS** [comment]
This is the same for ERT

**Comment by NanakoAC** [comment]
need to know the exact text of their assigned roles

**Comment by SierraKomodo** [comment]
This is the titles on the ID cards correct?

I've noticed on attempting to fetch this in-game that the CCIA ID cards aren't 'activated' or whatever the term is when we spawn in. I had to take off my gloves and do the biometric scanning thing for it to show a job title when I used the show ID verb.

Here's the exact job title for CCIA:

> Central Command Internal Affairs Agent

**Comment by NanakoAC** [comment]
fixed by #1588
