### ISSUE TITLE
some backpacks are invisible/lack sprites

### ISSUE THREAD

**Issue by honkel** [Aurorastation/Aurora.3#14414]
I've only seen it with satchels so far. No inhand, or tile sprites

**Comment by NewOriginalSchwann** [comment]
Did some testing: All messenger bags appear to be invisible and all medical bags show up as grey backpacks.

**Comment by sheeplets** [comment]
Duffel bags also seem to be affected.

**Comment by SleepyGemmy** [comment]
fixed in #14412 and #14415.
