### ISSUE TITLE
CCIA Agents are starving when they are spawned in

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1441]

**Comment by LordFowl** [comment]
This may be a result of your hunger being randomly determined when spawning. Please try spawning in multiple times to see if it changes.

**Comment by SierraKomodo** [comment]
Alright, confirmed it is randomized. With that, I guess this goes from being a bug to a feature request - Let CCIA, ERT, etc spawn without any hunger.

**Comment by skull132** [comment]
Refactor. :ree:

**Comment by SierraKomodo** [comment]
May also want to look at IPCs and hunger. There's been a few that spawn in and immediately end up disabled from hunger.

**Comment by Alberyk** [comment]
Fixed already.
