### ISSUE TITLE
Paper bags no longer have in-hand sprites

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#14424]
Woe.

**Comment by SleepyGemmy** [comment]
caused by #14342.
paperbags were turned into contained sprites but no in-hand sprites were created or moved over to the new contained sprite file, if any existed.

**Comment by KingOfThePing** [comment]
I tested this and it is not reproducable. Both in-hand sprites are in the respective .dmi and the path is also correct.
