### ISSUE TITLE
Oversight: Axiori Skrell Cannot Use 'Attach Nymph Limb'

### ISSUE THREAD

**Issue by runecap** [Aurorastation/Aurora.3#14450]
Axiori Skrell can spawn with nymph limbs, however if you try to get one midround with the 'Attach Nymph Limb,' you get the response '_the diona nymph refuses to attach to your limb_'

The actual issue behind this is just the verb can only be used by certain species, and Axiori Skrell aren't on that list.

**Comment by DreamySkrell** [comment]
fixing this
