### ISSUE TITLE
Slimes cannot be killed with fire extinguisher fluid

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#14479]
Ran into a bunch of slimes and had a nightmare of a time both escaping while using the fire extinguisher before abandoning it and trying to get to water. The fire extinguisher fluid wouldn't kill them.

**Comment by SleepyGemmy** [comment]
feature, not a bug. slimes are only vulnerable to water, which the fire extinguishers no longer contain.

**Comment by JohnWildkins** [comment]
what gem said
