### ISSUE TITLE
There is no attack delay when attacking simple mobs/things

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#1448]
What it says in the tin, no cooldown on attacks, so, you can click common mobs and kill them real fast.

**Comment by skull132** [comment]
When fixing, apply this at as high a level as you can. Or as low. You know what I mean.

Usual cooldowns for all weapons are handled in `obj/item/proc/attack`, in item_attack.dm line 52. I'm not quite sure why it doesn't end up in that stack, tbh.
