### ISSUE TITLE
Autohiss is a bit much

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#1452]
too many SSs's, need to tone it down a little to be useful

**Comment by skull132** [comment]
There are two settings.

Hiss, and obscene hiss. From testing, hiss was fine. It's meant to be used with only 1 s in speech. If you type any more, you're overdoing it.

**Comment by LordFowl** [comment]
Obscene hiss is just 2-3 more hisses. Any hisses you saw was probably the player manually hissing as well.

**Comment by skull132** [comment]
Test it for yourself, _with proper usage_, and report back.

**Comment by LordFowl** [comment]
As there has been no further complaint, closing.
