### ISSUE TITLE
Positronic brains pop out nameless from gibbed IPC

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#1457]
I was fighting a blob on my industrial frame IPC when I was sucked in and gibbed. The resulting positronic popped out nameless.

**Comment by LordFowl** [comment]
I can't seem to replicate this. The bug was perhaps fixed, or there was something more going on than just the fact you were gibbed.

**Comment by Lohikar** [comment]
It seems to have been fixed at some point and this issue wasn't closed.
IPCs' posibrain's brainmob was not having its name set correctly.
