### ISSUE TITLE
Exoplanet ATMOSPHERE

### ISSUE THREAD

**Issue by ArtofWASD2** [Aurorastation/Aurora.3#14596]
Exoplanets are planets meant to have no atmosphere. They scan as having a 0KPA atmosphere and 0C temperature. However, some exo planets currently spawn with N20 gas. N20 is -50C. This means that not only do exoplanets have an atmosphere, they are far below freezing. Either this is an issue with exoplanets, or an issue with ship scanners showing 0 on scans.

**Comment by FluffyGhoster** [comment]
Exoplanets were reworked supporting different atmospheres, I therefore believe this report not to be longer relevant; feel free to reopen otherwise
