### ISSUE TITLE
Light Fixture Sprite in Right click menu is wrong

### ISSUE THREAD

**Issue by EJDenton** [Aurorastation/Aurora.3#14656]
This does not seem to affect all light fixtures but the one in the warehouse I can replicate with. If you right click the tile you will see the light fixture sprite looks like some sort of gun. Picture of it posted below.

https://i.gyazo.com/be775e0decddb5f94eb27aa58d9eb738.png

**Comment by KingOfThePing** [comment]
Can't replicate this

**Comment by EJDenton** [comment]
Not sure of a good way to replicate but I saw it happen again in the armory.

https://i.gyazo.com/e2231e2e924b2b0534c9ff829a542e57.png

Light fixture again, sprite of an O2 tank.

**Comment by SleepyGemmy** [comment]
presumably a bug with caching and the context menu.
