### ISSUE TITLE
New characters can't select a faction

### ISSUE THREAD

**Issue by montyfatcat** [Aurorastation/Aurora.3#14690]
When creating a new character after selecting "New Character" in the load slot menu, the faction is set to "none" but shows the job selection of a nanotransen character. If you try to change the faction, it tells you that you have an invalid selection and refuses to open the window to select a new one. This quite literally softlocks you out of being able to make a new character that isn't service, medical or research.

Made an ahelp in round cjw-db1W which MattAtlas responded to, who had the same issue.

**Comment by Alberyk** [comment]
If you save the character you can change the faction.
