### ISSUE TITLE
Able to undersatnd all languages 

### ISSUE THREAD

**Issue by Orr404** [Aurorastation/Aurora.3#147]
Don't exactly know the cause though I'm pretty sure it was being transformed by a wizard I could understand all languages if not speak them it might have also been caused by the pAI I had which had a universal translator installed, but I would probably guess the wizard part was the real issue.

**Comment by skull132** [comment]
It's to do with constantly being rejuggled. Were you a borg, at some point, before being a human and realizing tihs?
