### ISSUE TITLE
Solar Tracker Sprite Broken

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#14728]
It's missing the actual console bit and only shows the display.

![image](https://user-images.githubusercontent.com/52309324/186824876-3e1a6b14-b03a-4f3a-8b58-b0506029a6d5.png)

**Comment by Baa14453** [comment]
Completely invisible when switched off 
![image](https://user-images.githubusercontent.com/9057997/194122528-fec140df-c377-4d2f-8b0c-84cca0d6e6c9.png)
