### ISSUE TITLE
Monkeys not being affected by viruses they should be able to get.

### ISSUE THREAD

**Issue by Jennalele** [Aurorastation/Aurora.3#1472]
While doing virology, both today and a few other times since the code update, I've been totally unable to infect monkeys with viruses from blood syringes. Even if the virus lists monkeys as an infected species. This has led to me needing to stick patients with radium.

**Comment by skull132** [comment]
Confirmed.

Injecting any mob with blood doesn't appear to carry over viruses.

**Comment by skull132** [comment]
Fixed, shit didn't autoclose. :ree:
