### ISSUE TITLE
Player mobs appear visible over things they shouldn't (curtains, water)

### ISSUE THREAD

**Issue by Dekserrrrrr** [Aurorastation/Aurora.3#14741]
![image](https://user-images.githubusercontent.com/92396228/187069305-5ec22c02-5083-4a47-a483-cdc07417a4e7.png)

![image](https://user-images.githubusercontent.com/92396228/187069326-ef9e6848-c8b5-4e56-ba5c-a2a035f3c1cf.png)

**Comment by SleepyGemmy** [comment]
can't replicate on master 8a3bb11.
