### ISSUE TITLE
Surgeries not working.

### ISSUE THREAD

**Issue by sleepywolfie** [Aurorastation/Aurora.3#1475]
Trying to repair synthetic eyes and brain damage is not working. Vaurca surgeries aren't working either. I'm not sure what else about surgery stuff is broken.

**Comment by Lohikar** [comment]
![2017-01-08_15-02-44](https://cloud.githubusercontent.com/assets/7097800/21754142/cbdda880-d5bf-11e6-927b-50ec02276a5c.png)
Looking at the changelog, it looks like Bay removed eye & brain surgery in favor of the generic organ surgery.

**Comment by skull132** [comment]
Aye, generic organ surgery (use nanopaste if assisted or synthetic organs) will now work instead. Try thos ei you can, and report back.

**Comment by skull132** [comment]
Vaurca surgeries should be fixed as of #1513

**Comment by LordFowl** [comment]
Not correct, as the PR states.
