### ISSUE TITLE
Ambience needs to be toggled repeatedly when music is played

### ISSUE THREAD

**Issue by GMR25** [Aurorastation/Aurora.3#14793]
1: Have ambience toggled off
2: Have someone play music on the wall jukebox or change the holodeck simulation
3: Have to toggle ambience on and off again to mute the horrid noise

Expected behaviour: The ambience toggle being respected by wall jukeboxes instead of needing to be turned on and off repeatedly.

**Comment by SleepyGemmy** [comment]
fixed in #14716.
