### ISSUE TITLE
Library Bug - Inventory

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14806]
You can print a bible whenever but there is no Quran in the game at all - at least not available inside the Library records to be printed.
Which was Jarring because I could print a bunch of holy books on say Qerblak or Numerology

**Comment by Zelmana** [comment]
Books available in the library lookup are uploaded via the web interface found here:

https://byond.aurorastation.org/server/library

Many of the books are very short, and I believe there is a character limit.
The Bible, printable directly, is a un-readable book and serves as flavor for chaplains, and I believe has some mechanics for fighting against wizards/technomancer abilities as well as vampires.

I do not believe it's feasible to have the entire Bible or as requested here the Quran readable ingame.
