### ISSUE TITLE
Equipment Issues - Engineering

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#14800]
First off there is no easily Accessible Space ACs 
![grafik](https://user-images.githubusercontent.com/30761807/189543135-c9524241-65b8-45bf-84c5-76f3fff14e6b.png)
This is an issue when there has been an event that dramatically cools a room (like an artifact) 
Spent nearly an hour this round trying to get mining out of red atmosphere alert due to temperature.

Secondly the spawn for the Pipe Painter and the Floor Painter are in Engineering Lockers and Atmos Spawn respectively
but the Pipe painter spawns in Engineering and the Floor painter in Atmos
This feels unintended, and if it is intended it is usually just annoying to go downstairs/upstairs to get the respective tool

**Comment by SleepyGemmy** [comment]
will fix today.
