### ISSUE TITLE
NanoUI does not display.

### ISSUE THREAD

**Issue by MarinaGryphon** [Aurorastation/Aurora.3#1486]
OS: Windows 10
CKey: MoondancerPony
IE version: 11.576.14393.0

Only present after baymerge.
Solutions tried:
- Reloading NanoUI
- Reconnecting
- Restarting BYOND
- Clearing cache
- Restarting the computer
- Removing BYOND-related registry entries
- Reinstalling BYOND
- Waiting.

There is a similar issue on the Baystation github. The only solution was to reinstall the OS, which is not an option for me.

**Comment by MarinaGryphon** [comment]
NanoUI works as a maintenance drone only.

**Comment by Arrow768** [comment]
A few more info are needed. 

OS Version
Browser Version (IE) 
Ckey

Am 9. Jänner 2017 09:42:08 MEZ schrieb MarinaGryphon <notifications@github.com>:

**Comment by Arrow768** [comment]
Try the following:
* [Deactivating the Internet Explorer Addons](https://support.microsoft.com/en-us/help/17447/windows-internet-explorer-11-manage-add-ons)
* [Resetting the Internet Explorer Settings](https://support.microsoft.com/en-us/help/923737/how-to-reset-internet-explorer-settings)
* Deactivating the Internet Explorer Feature and then Reactivating it after a reboot (Controlpanel -> Software -> Features)

**Comment by MarinaGryphon** [comment]
I did all of these things, and uninstalled and reinstalled BYOND, upgraded it, cleared my cache a billion times, and even deleted the BYOND registry keys and reinstalled.

Apparently, something worked, it hasn't happened since.
