### ISSUE TITLE
Vaurca surgery bugged

### ISSUE THREAD

**Issue by sleepywolfie** [Aurorastation/Aurora.3#1487]
When surgeons try to do surgeries, they just attack the poor vaurca. Drills, saws, scalpels, nothing can break into their thick crab things anymore.

**Comment by LordFowl** [comment]
RRRREEEEEEËÈEÈEEEEEEEEEEEEEEEEEE

**Comment by LordFowl** [comment]
For my sake of reference; https://github.com/Aurorastation/Aurora.3/pull/493
