### ISSUE TITLE
Xenobiology Is Missing An Air Alarm

### ISSUE THREAD

**Issue by ArtofWASD2** [Aurorastation/Aurora.3#14890]
Xenobiology does not have an air alarm linked to it, and is not visible on the engineering scrubbers network.

**Comment by ArtofWASD2** [comment]
> Well the point is for the Xenobiologist to set it no? For xenoplants that need exotic environments if you could remotely set it it would screw over the plantman.

They are seperate zones in the map. The scrubbers have different map names. Additionally, you cant remotely set the atmosphere or temp without an engineer unlocking the alarm for you.

**Comment by WickedCybs** [comment]
This is fixed now I believe.
