### ISSUE TITLE
cat ears no longer change to hair color

### ISSUE THREAD

**Issue by nursiekitty** [Aurorastation/Aurora.3#1491]
tested on different races with same result

**Comment by LordFowl** [comment]
Are cat ears an item?

**Comment by Alberyk** [comment]
The item in question: /obj/item/clothing/head/kitty

**Comment by LordFowl** [comment]
Doesn't seem like much of a bug to me.

**Comment by Jennalele** [comment]
They used to change color to match the color of the wearer's set hair color.

**Comment by Lohikar** [comment]
A quick inspection of the code shows that they're using an obsolete icon system; baymerge seems to have commented out the color change part.

It'll probably need a partial rewrite as it's probably best to not use the obsolete icon system.
