### ISSUE TITLE
Gold slime core can summon invisible mobs.

### ISSUE THREAD

**Issue by chaoticidealism** [Aurorastation/Aurora.3#14924]
Gold slime cores are supposed to summon hostile mobs. I activated one, and got (among other, normal mobs) an invisible mob (one with no sprite) called "crate". 

Unless this mob is supposed to be invisible, this is probably a bug.

**Comment by deGurkin** [comment]
Crate has attacked me before in maintenance, I think it is a joke about mimics that is left fragmented in the code.

**Comment by chaoticidealism** [comment]
Possibly. It's supposed to be a hostile crate that attacks you, right? But then someone removed the sprite.
