### ISSUE TITLE
Skrell head decorations loadout settings don't save.

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#1493]
When selecting a Skrell head decoration (chains, headbands...) for your loadout, they only save for one round. If you try joining again, you will not spawn with that item, and you'll find it is no longer in your loadout list.

**Comment by Alberyk** [comment]
Seems to happens with any whitelist related item.

**Comment by skull132** [comment]
Pushed a tentative fix. Reply or report again if that didn't do it.

**Comment by YouJustGotOwened** [comment]
The fix didn't work from what I can tell. None of the chains that I have selected spawn in.

**Comment by Alberyk** [comment]
Still happening.

**Comment by skull132** [comment]
What the absoloute haram. I tested it. Got an example character for me to look at?

Also, does it fix itself whenever you press reload character?

**Comment by Alberyk** [comment]
Any xenogear, like unathi gloves.

Also, yes, it is fixed when you reload.

**Comment by skull132** [comment]
...I fixed it. :ree: Time to debug some more.

**Comment by Alberyk** [comment]
I think this is fixed now.
