### ISSUE TITLE
Cloth Bed uses wrong Sprite

### ISSUE THREAD

**Issue by Ben10083** [Aurorastation/Aurora.3#14935]
![image](https://user-images.githubusercontent.com/91219575/196281642-1001c392-b200-4212-89d1-a9524edca849.png)

**Comment by SleepyGemmy** [comment]
can't replicate.

![image](https://user-images.githubusercontent.com/99297919/196529816-b52859e5-5605-49e8-8514-5be8ec9c120c.png)
