### ISSUE TITLE
Cyborg Optical Material Scanner not working.

### ISSUE THREAD

**Issue by XenosTiger** [Aurorastation/Aurora.3#1495]
ra station 2017-01-09 175206](https://cloud.githubusercontent.com/assets/18099476/21787020/de65d394-d694-11e6-828c-e6d2b51a8c26.png)
![aurora station 2017-01-09 175156](https://cloud.githubusercontent.com/assets/18099476/21787021/de661f48-d694-11e6-9450-6fba2169dd45.png)

The first image shows me standing adjacent to a Pitchblende deposit, with my Optical Material Scanner selected. The second image is me standing so my light didn't shine on it, but I pointed at it. It didn't show up. 
This leads me to believe that, for some reason, the Optical Material Scanner for mining borgs is completely borked. I tried toggling it the same way you would a stunbaton. No effect. I tried selecting it from the HUD overlays that borgs have. Not there. I turned off my existing HUD. Still not working.

I have no idea what to do, but until it's fixed, Mining Borgs are next to useless.

**Comment by XenosTiger** [comment]
![aurora station 2017-01-09 175206](https://cloud.githubusercontent.com/assets/18099476/21787097/499a6abc-d695-11e6-8f8c-4515af5af30d.png)

**Comment by skull132** [comment]
:ree: Silicon life, I blame that.

**Comment by SirFruitcakes** [comment]
This seems to also extend to Engineering Meson Scanners.

**Comment by SirFruitcakes** [comment]
I'll post a separate Github of that when I get a moment to confirm it.
