### ISSUE TITLE
Generic style bags do not change colour

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#14969]
For generic style of backpacks, whether it's the Backpack, Satchel, Duffelbag, or Messenger bag, do not change colour. They remain grey.

Only Rucksack, Leather Satchel and Pocketbook change cololur.

This is also after the recent bug fix.

![bagsbug](https://user-images.githubusercontent.com/56227386/197397426-8c4093df-30a1-40ea-aa3b-41b7c230c8cb.png)

**Comment by SleepyGemmy** [comment]
this is intentional.
there are no coloured sprites for the backpack, satchel, dufflebag, or messenger bag, unless you use the faction-specific sprites.
