### ISSUE TITLE
Chat Log Mangled

### ISSUE THREAD

**Issue by Olympus7** [Aurorastation/Aurora.3#1498]
An error occurs while logging that cancels the production of new lines of text (Log file http://puu.sh/th2OE/1a7a038d48.htm)
![ss 2017-01-09 at 08 03 09](https://cloud.githubusercontent.com/assets/25020422/21789930/af1b04ee-d6a6-11e6-84af-a7b9dbd98689.png)

If it helps, part way through the round (6:50 EST, Game ID: bMs-djFo) I turned logging on.

**Comment by skull132** [comment]
BYOND error. Not something we can do anything about at the moment. If you
are using the beta version, I'd suggest going back to stable and seeing if
that fixes it.

**Comment by skull132** [comment]
Also, loaded fine on my Chrome.

So, user side error. Nothing we can do about it one way or another.
