### ISSUE TITLE
Custom item issues (Ankala Ahzi)

### ISSUE THREAD

**Issue by CaptainGecko** [Aurorastation/Aurora.3#14984]
Custom items just shipped! Alas there's a few issues. For reference, app was [here](https://forums.aurorastation.org/topic/17432-the-ahzi-fleet-kit/).

Now then, two main problems:
- The app included both a **flag** and a **banner**. The flag (the one-tile-large one) is here, though it seems that the banner (the two-tiles-large one) is not. At least, my character does not spawn with her custom banner in her inventory, or at her feet if her inventory is full. As far as I can tell checking the files, **it was not implented with the rest of the custom items in the app**. The file sent on the app (linked above) does still include both the flag and the banner itself so you can just take it straight from there to implement it.
- **The armband is all messed up**, but it looks like it's on me. After checking again, it seems that the file I sent is lacking directional sprites, I must've misclicked somewhere and saved the mistake like the idiot that I am. Here's a fixed version of the armband, with proper directional spritesso that it can be updated and fixed, on discord: https://discord.com/channels/157516682288562176/302201161044328450/1034582179897954375

Contact me @CNEGecko#9618 on discord if you need help with anything.

**Comment by CaptainGecko** [comment]
Update, I mixed the two because I'm stupid. What is implemented is the one-tile large BANNER, and **what needs to be implemented is the two-tile large FLAG**.

**Comment by Alberyk** [comment]
The missing flag should be fixed. I will fix the armband soon.

**Comment by CaptainGecko** [comment]
Update! Both the flags and the banners are in here so far! Though both are currently named flags, must've been because I've mis-named these.
