### ISSUE TITLE
Bags Strap Issues

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#14980]
- "normal" straps are 2 pixels thick instead of 1 pixel thick (masking issue?).
- "hidden" straps still show the shoulderpiece (i.e. where the strap goes over the shoulder).

**Comment by EJDenton** [comment]
I'll put this here instead of making a new report, but I change my bag strap to hidden in character creator but it never seems to save it. It always reverts to normal on round start.

**Comment by SleepyGemmy** [comment]
> I'll put this here instead of making a new report, but I change my bag strap to hidden in character creator but it never seems to save it. It always reverts to normal on round start.

did you save the character slot?

**Comment by EJDenton** [comment]
I thought I might not have saved it the first time but I checked multiple times after that and made sure to save it. I played three rounds last night and each time I had to manually hide the strap after round start.
