### ISSUE TITLE
Possible Duplication Bug - Steel Rods

### ISSUE THREAD

**Issue by EJDenton** [Aurorastation/Aurora.3#14993]
During a round, the stack of steel rods that starts in the main engineering supply room began to duplicate new stacks when you tried to pull one from the stack with an empty hand. The original stack of sixty would decrease to 59 but instead of finding one steel rod in your hand you would now have a new stack of sixty. You could drop the new stack and pull another stack of sixty from the original and watch it decrease to 58.

**Comment by EJDenton** [comment]
Also just noticed that the affected stacks don't want to recombine either. I weldered the stacks down to just one rod each and the rods would not combine into one stack.

**Comment by NonQueueingMatt** [comment]
this was fixed
