### ISSUE TITLE
Cyborg Gripper Problems

### ISSUE THREAD

**Issue by XenosTiger** [Aurorastation/Aurora.3#1499]
As a foreword- If it's possible, I'd like to allow anyone to post to this thread, so that there's a nice, quick lookup for any Cyborg issues that may arise from this new code.

Yet another issue with borgs, this time with Service, Medical, and, I'm assuming, Science. I talked with Nanako about this, and we think we've come up with the root of the issue.

The problem is that any actions that involve the Borg holding something in their gripper, and attempting to place that object inside a tile entity, such as Medicine Storage, or any of the devices in the Kitchen, will result in a failure- in the case of a Service Borg in the kitchen, you'll get the message "that's not edible". 

What Nanako and I both think the cause is, is that the code thinks you're trying to place the /gripper/ into the storage/tile-entity/whatever.

I tested the kitchen issue out with my gripper and my plant bag, carrying apples, ice-cream, and Chantrelle mushrooms, all with the same result.
![aurora station 2017-01-10 012821](https://cloud.githubusercontent.com/assets/18099476/21796089/428a0450-d6d4-11e6-9bcd-dc70e196ee81.png)

**Comment by Lohikar** [comment]
Related: #1489.

**Comment by NanakoAC** [comment]
Don't worry, i've got everything in hand <3

No thinking needs to be done, i'm familiar with it and working right now on a permanant solution to simultaneously fix everything and prevent future gripper problems. Might be a day or two, but it should be done this week

**Comment by Pratepresidenten** [comment]
The borg transfering someone from a buckled bed bug is back for the sleepers. You'll put them in, but they'll still register as being on the bed still, causing them to teleport back onto the rollerbed if you pull or nudge it.

**Comment by NanakoAC** [comment]
@Pratepresidenten seperate issue please, this one is only for gripper related things

**Comment by NanakoAC** [comment]
fixed by #1518
