### ISSUE TITLE
IPC Shells skin tone issues

### ISSUE THREAD

**Issue by Jennalele** [Aurorastation/Aurora.3#1503]
Shells are buggy as fuck right now. Sometimes, you have to completely change their species and then re-select shell to be able to get your customization options to appear properly in the menus. Skin tone doesn't seen to register properly, either, as when I tried most recently, with several different colors, I appeared nearly cue-ball white: https://gyazo.com/577a53178a08a22dd738ead15439e094 And lacked a face.

**Comment by Fire-and-Glory** [comment]
On the vein of issues with shell appearances, I've noticed that saving char settings doesn't actually save the shell-type, so next time you load it it'll default to human, which'll be unpleasant when you spawn.

**Comment by Jennalele** [comment]
Funny story, that, as a human shell I recently spawned as this fockin abomination: https://gyazo.com/b7fcc8363e8318d2d9a1ae892144b9dc
