### ISSUE TITLE
Corporate Reporters do not get additional title accesses

### ISSUE THREAD

**Issue by feartheblackout** [Aurorastation/Aurora.3#15047]
Corporate Reporters, but not Freelance Journalists, are supposed to have extra departmental access based on selecting the alt title itself. Since our switch from Aurora to the Horizon, that is no longer the case. My best guess is that something from the new megacorp faction system is overriding it, but I'm not experienced enough to reason out the solution on my own.

**Comment by SleepyGemmy** [comment]
just tested. can confirm.

**Comment by feartheblackout** [comment]
Fixed by #17091
