### ISSUE TITLE
Can't make glass airlocks

### ISSUE THREAD

**Issue by Cooleosis** [Aurorastation/Aurora.3#15056]
Expected: Bopping a partially made airlock with reinforced glass turns it into a glass airlock.

Reality: Red text saying "You can't make an airlock out of the reinforced glass sheets." Also occurs with regular glass. Tried at every stage of airlock construction on multiple different types of airlock.

**Comment by SleepyGemmy** [comment]
just tested. can confirm it doesn't work.
