### ISSUE TITLE
Possible Deaf Bug Encountered

### ISSUE THREAD

**Issue by EJDenton** [Aurorastation/Aurora.3#15066]
I was dealing with a number of auto-traitors that all chose to use frag grenades. After the fourth, or fifth, frag grenade I appeared to be permanently deaf. Medical attempted to resolve this with chemistry and was adamant in looc that surgery would not fix the issue. After speaking with an admin, they suggested it may be a bug and healed me, restoring my hearing.

I'm not sure if this was simply permanent deafness brought on by too many grenades but I assume medical should be able to resolve it.

The game ID was ckP-aGVI if needed.

**Comment by JohnWildkins** [comment]
Did a bit of testing and everything seems to be fine. Looking at it, a close-range explosion (or even a mid-range one) starts to do a lot of ear damage very quickly, and it's _possible_ your ear damage was so high that one dose of medicine didn't bring it below the threshold to start clearing up your deafness.
