### ISSUE TITLE
Bloodbags give only about 2%

### ISSUE THREAD

**Issue by coolbc2000** [Aurorastation/Aurora.3#1507]
Bloodbags at any transfer rate only give about 2%, making Iron pills just waaaaay better for blood loss, which makes no fucking sense at all.

**Comment by Fire-and-Glory** [comment]
I've noticed this, I'm not even sure the bloodbags give any blood, it might just be natural regeneration or something.

But yeah, I've seen bloodbags drain all away in an IV and not make a dent.

**Comment by Geevies** [comment]
Fixed.
