### ISSUE TITLE
Strange Glitches (Possibly lingmode related)

### ISSUE THREAD

**Issue by XxdwbxX** [Aurorastation/Aurora.3#151]
As ling, I was passing the bridge and saw a strange tile with a red shape. After mentioning it ahelp, it was suggested I relog. I did, and that gave birth to new issues.

I failed to get a picture of the first object/glitch as it was gone when I relogged.

Coming back in, I see that my Damage Zone indicator shows a bio suit when targeting the torso (http://imgur.com/f9kWokM) but displays as normal when targeting elsewhere.

A short time later, I noticed it had changed again (did not relog): http://imgur.com/8B2PVAA

And again: http://imgur.com/NUfSIYT

Edit: The first object was in space by the port bridge entrance, so I did not interact with it other than the Examine verb and it was treated as a space tile.

**Comment by skull132** [comment]
Not been reproduced at all, most likely a resource issue on your end.
