### ISSUE TITLE
Mining industrial drill almost useless now, can't dig most turf

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#15110]
Called in with the drill dropper it only works on rocky ash, which used to spawn under some mined rock, except for grove planets, now that barren/lava exo's only have ground as turf it pretty much cant dig anything, only use is mineral asteroids which isnt even likely to spawn

**Comment by deGurkin** [comment]
Can confirm the bug on Grove exoplanets

**Comment by Doxxmedearly** [comment]
Fixed by #16386
