### ISSUE TITLE
Bloodstains on footwear appear black

### ISSUE THREAD

**Issue by CyberSpyXD** [Aurorastation/Aurora.3#15167]
Instead of getting coloured red it is coloured black. The blood colouring seems to work on stuff like uniforms still for whatever reason.

This might be related to mapped in blood eventually turning black over time.

**Comment by SleepyGemmy** [comment]
possible caused by #13350?

**Comment by FluffyGhoster** [comment]
Doesn't seem to be a thing anymore, reopen if it is
