### ISSUE TITLE
Hardcoded year is wrong (2561 vs 2459)

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#1516]
I mean... there you go.
Noticed it on the robotics construction form, reassignment, and cyborgification release. I assume this will carry over to the rest of the templates

Step 1: Print paper from request console
Step 2: Look at paper
Step 3: Notice the date field

**Comment by skull132** [comment]
The function itself needs a bit of a tweak, apparently.
