### ISSUE TITLE
Lung Randomly Popping while EVA

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora.3#1517]
While in a security hardsuit as a human with a full oxygen tank mounted onto the hardsuit (set to 16 distribution pressure), I suddenly had my lung pop after being completely fine in space for 3 minutes. The suit was not damaged. My air contents were fine. My internals were running. Yet my lung randomly popped and I began taking extremely rapid oxygen damage. After two adminheals, the sequence repeated itself until I went back inside.

**Comment by skull132** [comment]
It's possible that the threshold was raised. Try to replicate with a
release pressure of 21.

**Comment by XenosTiger** [comment]
From what I know, a release pressure of 17 kPa is the bare minimum that is safe in SS13. Having it set to 16 kPa will cause the same effects as being in a room with an orange atmos alert- which may or may not result in lungs popping, even though it usually only happens if you set it to a red release level...

**Comment by Spoopy11** [comment]
The minimum used to be 18 on an oxy tank, but, just the other day I had an oxy-tank set to eighteen and I was choking and gasping. Set up to 21/default I had enough airflow to cause me no problem.

**Comment by Alberyk** [comment]
21 kpa should be the safe one, don't go lower.

**Comment by Serveris** [comment]
Xenos messaging me made me realize I made a typo. The distribution pressure was indeed 18, I think I made a mistake with the keystroke. Same issue has persisted into every round I've played today.

**Comment by Jennalele** [comment]
I've seen this happen to me with my distro pressure at 21. 

Not to mention, it is immediate, sudden, without warning. No pain, no oxygen damage beforehand. You're fine, totally cool and doing your thing one second, then bam, you feel a stabbing pain in your chest and suddenly start dying rapidly.

**Comment by skull132** [comment]
Not a bug. Running low distro pressures is dangerous, and the severity of lung damage was increased. This isn't something we can change without making spess less deadly for people in general, unfortunately.
