### ISSUE TITLE
Station Alert consoles don't show alerts 

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#1521]
When clicking a station alert console (the one at the Engineering desk), they don't show a list of the current alerts. It just pops up an empty window.

**Comment by Lohikar** [comment]
Does it show the headers for each alert type?

**Comment by Juani2400** [comment]
Nope! It's empty. It only shows the header title at the top.

**Comment by skull132** [comment]
Duplicate of #1839
