### ISSUE TITLE
Clicking a tile with an unopened drink prints a message

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#1525]
Clicking a tile with an unopened beverage such as Space Beer or a vendor drink prints the following message:
![2017-01-11_22-51-15](https://cloud.githubusercontent.com/assets/7097800/21877401/7a94567a-d850-11e6-88e6-282d935b9d25.png)
Clicking on yourself with the unopened drink prints the message twice.

**Comment by skull132** [comment]
It may try to splash the tile. At which point it makes sense.

**Comment by MarinaGryphon** [comment]
P. sure this is now fixed from Burger's common container framework thing.
