### ISSUE TITLE
Undeleteable Immortal blob remains.

### ISSUE THREAD

**Issue by SenpaiShadow** [Aurorastation/Aurora.3#1528]
Main core got destroyed.
All other blob remains had negative health, wouldn't get destroyed.
Sec empties their laser rifles, nothing happened.
Unable to delete the remains.
Update1: Immune to delete-all as well.
Update2: After trying to del-all it several times it finally worked, slowly, but it worked. Part by part got deleted.

**Comment by SoundScopes** [comment]
Garbage collector isn't deleting the parent blob fast enough so all the children's parent var isn't null.
If the garbage collector had a backlog then delete-all would also be delayed.

A fix, parent blob keeps track of the children and updates it's health when it dies for each child.
