### ISSUE TITLE
Message monitor console password is not random

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#15289]
I think ever since the Tcomm rework was made the password for the message monitoring console ins't random anymore, i've had i think like 5 or 6 rounds and the password is the same

![passoword](https://user-images.githubusercontent.com/51837452/206931070-717c6405-75d9-4c1f-9824-069b3293eaa2.png)

**Comment by JohnWildkins** [comment]
Intentional. SCC IT budget cuts have led to inferior security practices.

(this is a joke. will be fixed sharpish)
