### ISSUE TITLE
Audible emotes are not received by the people around you

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#15292]
When you use one in some cases it comes through just fine on your end, but can't be seen in either the text box or overhead chat by anyone else. Some people have also reported not even being able to see their own emotes, they're just eaten by Byond and disappear on both ends. 

Recent-ish issue, at least as far as I can tell. I've been screaming into the void for days now (at least) and wouldn't have ever realized if someone hadn't commented on it.

**Comment by JohnWildkins** [comment]
When you say audible emotes, are you using audible emotes in the IC tab, or putting `!` before your emote in a say prompt?

**Comment by sheeplets** [comment]
> When you say audible emotes, are you using audible emotes in the IC tab, or putting `!` before your emote in a say prompt?

Say "!example emote."
