### ISSUE TITLE
Plasma in the Air

### ISSUE THREAD

**Issue by tsm34** [Aurorastation/Aurora.3#153]
There's something horribly off about it. All the air alarms will read no plasma in the air when a room is previously filled then scrubbed, but then I stand there sounding like a paranoid freak with my atmospheric scanner which will say .01% plasma. It seems like the code begins to act somewhat erratically when the amount of plasma in the air of a room approaches small numbers. But now, today, after venting my whole RD office of atmosphere and refilling it so that both my atmospheric scanner and the air alarms say there was no plasma in the room, I was still getting toxins to accumulate just be stepping into the room. Even though everything says there is no plasma, and my clothes are not infected. I'll try to test more to see if I can replicate results, but there was another incident about a week ago when all my scanners read N/A for plasma, and only some people where getting toxins in their blood in the room.

**Comment by skull132** [comment]
This was fixed in a pull req imported from Polaris.
