### ISSUE TITLE
Station-Bounce Radios not functioning while on exoplanets

### ISSUE THREAD

**Issue by Jeffmomentred** [Aurorastation/Aurora.3#15361]
When on an exoplanet, talking in anyway through a stationbounce will not register. Microphone on, speaker on, :l or :r.
I am not sure if this is a problem with other away sites besides the two mentioned.

Replicated twice by me
Once on a lava exoplanet
Once on a grove exoplanet
, others have mentioned it.

Seemingly worked well enough for a bit sometimes, then will just stop.
Might have something to do with the Horizon's distance to the mining ship. 

![guhhello](https://user-images.githubusercontent.com/120905824/208288715-c40afeef-f9f6-4f26-8709-82ef95c78998.PNG)

**Comment by SleepyGemmy** [comment]
they're supposed to be shortwave radios, so it should definitely work.
