### ISSUE TITLE
Exosuit Fabricator can not print Gygax armor plates

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#1543]
Tell me if I am just missing things but I should have enough and it is not building.
https://gyazo.com/3e81ecb321520b874d7c53e72f3e02f4

**Comment by Lohikar** [comment]
I was able to construct all parts of the Gygax without issue.
Has this happened more than once?

**Comment by SonicGotNuked** [comment]
Well it happened one round, that is the screenshot and all materials show. I put in exactly three diamonds and used none of them.

**Comment by skull132** [comment]
There's an ancient as fuck issue of blueprint datums sometimes removing themselves from the lists. Never heard of exact steps to replicate, I'm afraid.

**Comment by Pratepresidenten** [comment]
Necro time! Just had this happen several times the past week. It wont print Gygax armor plating, and today the heavy surge protection module. Im pretty sure that this could be an issue with the upgraded fabricators. I had the exact amount for the gold, yet it refused to print, so a possible cost variable not updating with the upgrades?

Components in the fabricator:
1 pico manipulator
2 super matter bins
1 console screen
1 high powered micro laser

Picture linked for materials in the printer, part attempted to print and part costs.
Tried getting as much accurate info as possible.

![bilde](https://user-images.githubusercontent.com/20225964/44048196-f4170d46-9f30-11e8-8ff3-0155ecc1aba6.png)

**Comment by Geevies** [comment]
Die, Gygax, die.
