### ISSUE TITLE
Reagents in blood sometimes duplicate in value

### ISSUE THREAD

**Issue by FlamingLily** [Aurorastation/Aurora.3#15471]
Game ID: clD-aF20
Played Character: Mira Tilton (Had the bug happen to), Ayah Nasri (Identified the bug)

Sometimes, for reasons I don't know, reagents in one's blood will amplify in value (The values pictured are far greater than the values that would be injected)
https://cdn.discordapp.com/attachments/951240371885735946/1058264421543182438/image.png

**Comment by SleepyGemmy** [comment]
duplicate of #11156.

**Comment by FlamingLily** [comment]
> duplicate of #11156.

No sleeper or IV on drain mode was used, I don't think it's the same issue.

**Comment by SleepyGemmy** [comment]
related to #11156.

**Comment by FluffyGhoster** [comment]
Closing this in favor of #15471
If it turns out to not be the same issue, feel free to re-open / re-submit it once that one is marked as fixed

**Comment by SleepyGemmy** [comment]
> Closing this in favor of #15471 If it turns out to not be the same issue, feel free to re-open / re-submit it once that one is marked as fixed

you linked the same issue.

**Comment by FluffyGhoster** [comment]
Yea sorry, I meant to link #15804
