### ISSUE TITLE
You cant lock lockers in the traditional way anymore.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1547]
Can only be locked using the toggle lock verb.

**Comment by Lohikar** [comment]
A quick test shows that you're still able to lock with both `Toggle-Lock` and by attacking the locker with an ID card/PDA.

What is the "traditional" way?

**Comment by NanakoAC** [comment]
this is by design. I made the behaviour of lockers consistent, and ensured cyborgs can interact with them fully.

**Comment by Pratepresidenten** [comment]
The traditional way would be to use any item in hand or non-gripper module and click the locker. Doing this now only opens it.
