### ISSUE TITLE
Pipe dispensers are dispensing the wrong pipes

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#15488]
So not sure what happened but the pipe dispensers are dispensing the wrong pipes from what was selected, portable pipe dispenser thing included, these are the ones i found out so far:

High power gas pump: spawns t-valve fitting
Supply pressure regulator: pipe
Pressure regulator: heat exchange
4 way manifold: pipe cap

i didn't check all the others so i'm sure theres even more that i missed

**Comment by SleepyGemmy** [comment]
will look into this.

**Comment by SleepyGemmy** [comment]
issue related to the `update()` proc in `construction.dm`.
