### ISSUE TITLE
Synthetic tags do not get persistently removed

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1549]
Blame Alberyk for this being on Github.

![image](https://cloud.githubusercontent.com/assets/19973802/21921181/0760fcb8-d9cb-11e6-80f5-d0589a6bc96e.png)

Anyways, if you remove an IPC's tag then the removal doesn't last past the round from what I've seen, and just comes back the next round.

**Comment by LordFowl** [comment]
@skull132 Afaik I just used the code you provided regarding persistency.

**Comment by skull132** [comment]
@Fire-and-Glory Were you alive at round end? Or did you cryo or some such?

Were you also onboard the escape shuttle?

**Comment by Alberyk** [comment]
He was alive, I removed his tag by myself, and I think he managed to leave on the shuttle.

**Comment by Fire-and-Glory** [comment]
I had died in the round, after being resurrected my tag was removed and I transferred on the shuttle.
