### ISSUE TITLE
Window frames don't produce ambient occlusion

### ISSUE THREAD

**Issue by atteria** [Aurorastation/Aurora.3#15512]
Full walls add ambient occlusion to surrounding empty tiles, but window frames do not.
Both have the same crevasse which should logically occlude the same area from ambient light, but they do not.
Just a graphical bug, the game doesn't have consistent lighting in this instance.

To reproduce: Just hit observe and look at the medbay lobby, or the service hallway. Setting icon size to 128x128 can make seeing it easier.
![image](https://user-images.githubusercontent.com/86520558/210691405-4d27853a-549e-444d-b320-1b5df669f081.png)

**Comment by SleepyGemmy** [comment]
not a bug, this is how windows work.
