### ISSUE TITLE
Lawgiver Runtime

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#1552]
http://i.imgur.com/9iHZAdI.png

A lawgiver spawned in the vault.

this thing shouldnt be listening to non humans i guess

**Comment by Lohikar** [comment]
This should have been fixed by 0b5fdba52da334580ee0249fb7c827e6ae6ab6a4.
Did you see this on live or a local server?

**Comment by NanakoAC** [comment]
thats fine then, i was probably running on outdated code

**Comment by Lohikar** [comment]
Saw it happen on code that had the fix applied, looks like fix didn't work.

**Comment by NanakoAC** [comment]
yea not fixed in master http://i.imgur.com/VfdJ3rz.png
