### ISSUE TITLE
Maintenance Drones Hiding Layer Under Grates

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#15524]
title.

**Comment by EJDenton** [comment]
@SleepyGemmy  Is this issue that they should or should not be under grates?

Testing shows them hiding above grates.

![image](https://github.com/user-attachments/assets/37df257f-2995-4d9b-aec8-8436131aec93)

**Comment by SleepyGemmy** [comment]
doesn't seem to be an issue anymore.
