### ISSUE TITLE
More borg grippers!

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1555]
Its not exactly a bug, but a change that was done several weeks before the baymerge was even a thing.
Basically, you can grip a pill bottle out of the pillbottle box, and put it in the chemmaster or wherever. But as soon as you put it down, you cant pick it back up. You can access its contents and put pills back in, but not pick it up.
Being able to access the contents of a pillbottle with a gripper is kinda senseless for a borg, as opposed to moving them from one dispenser/surface to another.

**Comment by NanakoAC** [comment]
not a feature. Inability to pickup pill bottles is a bug.

I'm thinking of switching the content extraction to altclick in order to solve this. Would that work?

**Comment by Pratepresidenten** [comment]
That would work just fine.

**Comment by Surrealistik** [comment]
Confirmed; this is pretty annoying. Hope it gets fixed soon.
