### ISSUE TITLE
Pixel sticking out on Cloth Mask

### ISSUE THREAD

**Issue by Cash7800** [Aurorastation/Aurora.3#15555]
There's one pixel on the cloth mask that has the character sprite clip through 
![annoying extra pixel](https://user-images.githubusercontent.com/122303919/211370885-80b81afa-3f55-4f3c-80df-490c0f519c2b.PNG)
![annoying extra pixel 2](https://user-images.githubusercontent.com/122303919/211371097-c1e5aca3-ab8b-4056-922e-079187b219dd.PNG)

**Comment by SleepyGemmy** [comment]
not a bug.
