### ISSUE TITLE
Toxins cannot be added to the pathogenic incubator

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#1558]
Unsure if this was ever a thing but I've been told that one should be able to add toxins found in the toxin bottles to the pathogenic incubator via a beaker.

**Comment by CakeIsOssim** [comment]
Bumping this bug as it's been open for eight months and still persists to this day.

Also, you mutagens should also work with adding toxicity to the incubator. It accepts neither of them.
