### ISSUE TITLE
Tajara trade ship shuttle dosent work

### ISSUE THREAD

**Issue by NortonDK** [Aurorastation/Aurora.3#15609]
Playing ghost role on the tajara ghost ship, using the shuttle going to Horizon, i could not get back to my mother ship. it was not an option on the shuttle destination menu

**Comment by deGurkin** [comment]
Can confirm
WickedCybs was there to confirm
![grafik](https://user-images.githubusercontent.com/30761807/214726601-cc799300-3350-4e40-a5dc-2d55689ec8fb.png)
![grafik](https://user-images.githubusercontent.com/30761807/214726654-337df673-23d5-491b-9895-cb98e64bfd26.png)
![grafik](https://user-images.githubusercontent.com/30761807/214726681-3ebcd5e9-0dae-4980-b179-fe32f792f3b0.png)
![grafik](https://user-images.githubusercontent.com/30761807/214726698-83d6bb58-dd28-46b7-974e-7fb02787f093.png)
![grafik](https://user-images.githubusercontent.com/30761807/214726728-84ca9595-0b2f-4dff-a8fc-9f78df19ad8e.png)


According to a random ghost flying by it has no docking points at all, not for the shuttle or anyone visiting.
