### ISSUE TITLE
Wristwatches display the wrong date

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#1561]
"You check your watch, spotting a digital collection of numbers reading '09:43'. Today's date is 'January 13. 2561'."

The proper date should be 2459.

**Comment by skull132** [comment]
Duplicate of #1516

**Comment by CakeIsOssim** [comment]
Funny, I searched to make sure it wasn't. oh well

**Comment by skull132** [comment]
It's not an obvious duplicate. But since they call the same function to get the date, they're effectively duplicates. Not something you'd really know unless you knew the code.
