### ISSUE TITLE
Aggro NPC mobs target you even if they can't see you

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#15621]
Aggro NPC mobs (hostile drones, carp, combat drones, greimorians, etc), can and will aggro onto people they cannot and should not be able to see, even including people on different Z levels. This, of course, also makes deadchat extremely spammy.

Image was from round clZ-dLX2

![image](https://user-images.githubusercontent.com/60306280/213897696-3e3caf7e-addc-40cf-9a76-0108accb8f74.png)

**Comment by SleepyGemmy** [comment]
fixed by #15994.
