### ISSUE TITLE
[Possibly Intentional] Mining Cyborgs are unable to operate the Spark's helm.

### ISSUE THREAD

**Issue by BurpleBineapple** [Aurorastation/Aurora.3#15646]
### **Issue Details:**
Mining cyborgs have access to the Spark, but are unable to actually control it in space. This means they're fully capable of landing on away sites and around the Horizon, but they can't move the Spark away from the Horizon to search for mining sites. I talked to Melariara about it and they asked I make an issue report to confirm whether or not this is intentional.

**### How To Replicate:**
- Use the Spark control console to launch. You'll encounter no issues.
- Activate the engines, use the sensors. You'll encounter no issues.
- Trying to use autopilot or trying to manually control the shuttle in space will give you this message below
![image](https://user-images.githubusercontent.com/67706292/214259728-12f36d66-c805-409b-9ed4-4cc71a48dac0.png)

### **Possible Solutions:**
The simplest workaround, thought possibly not the best, is to add a check for mining modules specifically allowing them to interact with helm control machines. I'm a bit lazy and don't feel like writing the whole thing, but can do so if requested.

`	if(istype(M, /mob/living/silicon/robot))`
`		var/mob/living/silicon/robot/R = M`
`		if(R.module)`
`			if(istype(R.module, /obj/item/robot_module/mining))`
`				[allow mining bot piloting here]`
`	if(!issilicon)`
`		[allow human piloting here]`
`	else()`
`		[error message for AI and other robots here]`

**Comment by FluffyGhoster** [comment]
This is intentional, AI and robots aren't allowed to pilot, as per code comment
