### ISSUE TITLE
Xenobiology does not have Commands

### ISSUE THREAD

**Issue by HunterRS** [Aurorastation/Aurora.3#1566]
I just played a round of Xenobiology, and the slimes wouldn't respond to anything, I made sure they were tamed, so I know it's not me. Unless the slimes have different commands

Here is a log from the round

purple baby slime (534) chirps, "Edgar Dawnguard... friend..."
Edgar Dawnguard says, "Hello Slimes"
 [Common] Kalla-Ka'risco Cama asks, "The diona?"
 If they were my friend they would have responded when I say "Hello Slimes" None did.

**Comment by Lohikar** [comment]
As far as I can tell, slimes do not have commands.

**Comment by Lohikar** [comment]
Apparently I can't read.

**Comment by HunterRS** [comment]
They had commands before the merge.

**Comment by Lohikar** [comment]
Yes, and they still do, hence my comment about being unable to read.
Might've been the way you said it, they look to be case-sensitive.
Needs testing.

**Comment by printer16** [comment]
Slime commands are really really finicky. They are poorly written and half of the time don't work, or if they do work (in the case of the follow command) the slimes won't eat anything anymore.

**Comment by HunterRS** [comment]
Hmmm, I'll try again, but if I die cause of no commands

**Comment by Alberyk** [comment]
Fix'd with the wizard upate.
