### ISSUE TITLE
Visible message can stop being displayed during entire rounds

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#1568]
For whatever reason, something happens and visible messages, like attacking or stripping someone stops being displayed for everyone during the entire round.

Round id: bMx-cpV9

**Comment by skull132** [comment]
A null reference got into player_list.

Most likely from a Logout call runtiming.

**Comment by skull132** [comment]
Most likely ends up as won't fix. Only possible way of this happening is if someone's Logout proc for the mob runtimed. I looked over **every** reference to it and they all seem quite sound. Unless we get a specific mode of replication, RIP.

**Comment by skull132** [comment]
Welp, lied.

Happened again, `bMS-agpz`. Related files:
mob.dm:106
atoms.dm:476

**Comment by skull132** [comment]
As a quick fix, can someone please implement an admin verb to reconstruct the mobs list?

Also, issue may be related to xenobios and monkeys. Or more specifically, slime interaction with monkeys.
