### ISSUE TITLE
Photocopier will eat your papers.

### ISSUE THREAD

**Issue by UponASeaOfStars** [Aurorastation/Aurora.3#15695]
step 1: place paper in photocopier
step 2: photocopier eats your paper and will not give it back or make copies
step 3: cry, because those were the leviathan documents

what i expected to happen: corporate espionage
what actually happened: photocopier actually just three shredders in a trenchcoat

**Comment by EJDenton** [comment]
Can confirm, when you put something in the photocopier and open the GUI it shows a message asking for you to add something to the photocopier to copy. If you attempt to put something else in the copier it will say something is already present.
https://i.gyazo.com/ca0169c3e9d0ab5d53730643a189a1e8.png

https://i.gyazo.com/bc2594bbe0348c955dd539033519cd4a.png

https://i.gyazo.com/17f0dc17d8c94b001a8f12a2c9a391f8.png
