### ISSUE TITLE
Tajara cloning fur glitch

### ISSUE THREAD

**Issue by TheFurry** [Aurorastation/Aurora.3#157]
Tajara fur changes to a dark gray color when they are cloned (except tail and ears remain the correct fur color).

**Comment by TheFurry** [comment]
Issues also likely associated with issue #85

**Comment by Serveris** [comment]
Had this occur last night with a black tajaran. Was minding blowingly broken. The back of the ears, and everything from the waist down (legs, tail, feet, hands; everything on the bottom half of the sprite) was black, as it should have been, but the torso, arms, neck, face, and there majority of the head were this light grey color.

**Comment by skull132** [comment]
For reference:
This and issue #158 are actually different.

It appears that during cloning, one of the icon update procs for the mob isn't properly called. An administrator can fix this by rejuvving the patient. This method, however, does not work when the character has prosthetics.
