### ISSUE TITLE
Intrepid CO2 can fills slower than other cans and the kPa also jumps around

### ISSUE THREAD

**Issue by lavillastrangiato** [Aurorastation/Aurora.3#15704]
Trying to refill specifically the Intrepid's CO2 canister means it fills very slowly, a lot slower than other CO2 cans that spawn in atmospherics. 

Also, the kPa on the Intrepid's can will often sharply rise or suddenly fall from the value that it should be. For example, if the can is at 5897kPa, it will suddenly drop to 3245kPa, or rise to 7556kPa.

Steps to reproduce:
1. Unwrench the CO2 can located near the Intrepid's thrusters and bring it to atmospherics' CO2 pump.
2. Wrench the CO2 can to the pump.
3. Observe as the values go all over the place.
4. Also observe that it takes forever to fill by comparing the time it takes for a non-Intrepid CO2 can.

**Comment by NortonDK** [comment]
Maybe admins made it magical and has some insane internal volume? my guess

**Comment by FluffyGhoster** [comment]
The airlock and the intrepid map was changed in the meantime, is this still reproducible?

**Comment by lavillastrangiato** [comment]
Nah, I haven't had the issue since then. I'll close it.
