### ISSUE TITLE
All Heat Exchange pipes sprites are missing

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#15759]
The Heat Exchange pipes sprites are invisible, they are there but just invisible

**Comment by alsoandanswer** [comment]
you have to be more specific about the name

**Comment by LeiteQualhado** [comment]
> you have to be more specific about the name

![Unwrenched](https://user-images.githubusercontent.com/51837452/217324903-16829f9c-06cf-4459-883c-16722ea3f5d3.png)
Yeah i got the wrong name, but these 3 heat exchange pipes when wrenched have missing sprites
![image](https://user-images.githubusercontent.com/51837452/217325117-69bcef1d-c6e6-440b-ada6-f52c2a1d724e.png)
