### ISSUE TITLE
Tajara Robotic limb glitch

### ISSUE THREAD

**Issue by TheFurry** [Aurorastation/Aurora.3#158]
Tajara fur changes to a dark gray color when you add a robotic limb to them. I tested this with a right hand prosthetic. It displays correctly on character creation but the moment you spawn in it changes to an icky gray. Problem is probably related to the cloning issue. #157

**Comment by darkrising** [comment]
This bug is still present, seems to effect leg prosthetics.

**Comment by darkrising** [comment]
Curious thing to note, my silvery / white Tajara has a robotic left arm and her colours are fine. However when I try a prosthetic on my redish Tajara (138,54,15) they will spawn with grey fur.

**Comment by NanakoAC** [comment]
fixed by #698
