### ISSUE TITLE
Rename/Fix the name for the shutters in the engineering desk.

### ISSUE THREAD

**Issue by KesterShadowHair** [Aurorastation/Aurora.3#15809]
Unsure if this was a bug or simply didn't have a name yet. However, the default name for all buttons is remote blast-door control.  That is the instance with the button located on the Engineering desk. 

![naming issue](https://user-images.githubusercontent.com/69920525/218343013-22bf9082-061e-4357-94fd-58a9c7371c73.png)

**Comment by FluffyGhoster** [comment]
This should have been addressed, I see a name in the map editor, if not feel free to reopen this
