### ISSUE TITLE
Autolathe sheet recipe is not consistent with the actual value of sheets

### ISSUE THREAD

**Issue by Corsaka** [Aurorastation/Aurora.3#15889]
Both steel sheets and glass sheets in the autolathe cost 2500 steel, but putting in exactly one sheet of steel to the autolathe will only fill it by 2000 steel. You lose 500 steel per sheet, meaning that if you accidentally insert 37.5 sheets of steel, withdrawing it will end up with only 30.

This should obviously not happen, and the autolathe should be updated to only use 2000 steel/glass instead (also, reducing the max cap to 60000 instead of 75000 would alleviate the .5 issue).

**Comment by NonQueueingMatt** [comment]
Not a bug:
```		var/obj/item/I = new recipe.path
		if(I.matter && !recipe.resources) //This can be overidden in the datums.
			recipe.resources = list()
			for(var/material in I.matter)
				recipe.resources[material] = I.matter[material]*1.25 // More expensive to produce than they are to recycle.```
