### ISSUE TITLE
If the prisoner has no ID you can't put a timer on them.

### ISSUE THREAD

**Issue by SenpaiShadow** [Aurorastation/Aurora.3#1589]
Reported this because the person that found out didn't have a github account.
"If the prisoner has no ID, you can't get a printout for their charges."

**Comment by skull132** [comment]
@LordFowl @Arrow768 
Is there no manual method of setting a timer?

**Comment by SenpaiShadow** [comment]
According to trickingtrapster, no.
My best guess would be that at bay people abused the timers.

**Comment by skull132** [comment]
Well, no, this is most likely our change. To do with the infractions
computer.

IIRC the infractions compooter was tied to being able to automatically
compile and set timers. But we apparently forgot a manual override or
something.

**Comment by LordFowl** [comment]
There is no manual override - if a person has no ID you are meant to either acquire an ID from the HoP or put them in communal/solitary manually. I don't really see the need for a manual override, as people without IDs are usually outsiders.

**Comment by Jennalele** [comment]
Traitors that exchange their ID for an agent card, Heisters/Mercs/Ninjas/Wizards... It's kind of a pain in the ass I'm afraid.

**Comment by Arrow768** [comment]
As mentioned it can easily be remedied by getting a timer and putting them in a communal or solitary while keeping track manually.

Or getting a ID for them.

Or getting a generic prisoner ID from the HoP.

**Comment by LordFowl** [comment]
Outsiders that get arrested but don't get sent to perma should be recoeving an ID anyways. Traitors with an agent card will have to be looked into, but I'm pretty sure you can scan biometric data with an agent card just like a regular ID.

**Comment by LordFowl** [comment]
I have just confirmed that both Syndicate IDs and Guest Passes allow for biometric data to be imprinted on them - meaning that both traitors that have an agent ID _and_ outsiders (and indeed everyone lacking an ID), can be incarcerated without even retrieving a new ID from the HoP.
