### ISSUE TITLE
Mutagen doesn't cause plants to change.

### ISSUE THREAD

**Issue by TheFurry** [Aurorastation/Aurora.3#159]
Mutagen doesn't cause plants to change. When adding unstable mutagen to plants it doesn’t cause any mutation to take place. It’s become impossible to make any mutant plants. Issue is probably related to the tray issue. #61

**Comment by skull132** [comment]
Indeed it is related to that one. Because we don't know if mutagen works or not, I'll close this one. If fixing #61 does not fix this, then please report again.
