### ISSUE TITLE
Plant pots obstruct console on the Bridge

### ISSUE THREAD

**Issue by VeteranGary** [Aurorastation/Aurora.3#15912]
The plant pots in the bridge now have collisions instead of being able to walk over them or reach consoles past them. Auxiliary consoles are blocked by this change. The only two effected consoles are the station alerts, and supply console. This only applies if you are sitting in the seat, however you have to move the plant or go around to access the terminals.

https://i.gyazo.com/8ea635a1c68d3d88908b67b0ce4e45ca.png
https://i.gyazo.com/873f8b9dd56cb8b44f18ab72a7e9ffeb.png

**Comment by Eyeveri** [comment]
I'll fix it rn

**Comment by Eyeveri** [comment]
https://github.com/Aurorastation/Aurora.3/pull/15913
