### ISSUE TITLE
Vaurca start with low dist pressure in reserve tanks

### ISSUE THREAD

**Issue by sleepywolfie** [Aurorastation/Aurora.3#1593]
Vaurca now start with 19 kPa distribution and only 100 kPa pressure, and anything below 21 kPa dist pressure can cause popped lungs. Changing the spawning dist on their tanks to 25 or 30 or something and their internal reserve tanks back to having 300 would have them survive about 30 mins neglecting their tanks, instead of one minute.

i think i know what im talking about but im not sure please help

**Comment by LordFowl** [comment]
Likely. I was using pre-baymerge distro pressures. Will update to go above 21 (Going below 21 is actually low chance)

Actual pressure will not be changing - the default pressure is plenty, especially since K'ois now provides phoron.
