### ISSUE TITLE
The doors on the mini/robotics elevator don't lock.

### ISSUE THREAD

**Issue by Sinbest** [Aurorastation/Aurora.3#15945]
The doors on this elevator don't lock when the elevator moves, so it's possible to fall down the elevator / get crushed by it very easily (amazing lawsuit potential)
![image](https://user-images.githubusercontent.com/84290420/222906893-cfcd9245-3247-4f89-a43f-355850cdaa8a.png)

**Comment by SleepyGemmy** [comment]
not a bug.
