### ISSUE TITLE
three map issues, one minor, two major

### ISSUE THREAD

**Issue by Avignis** [Aurorastation/Aurora.3#15960]
Map issue #1: warden office is not connected to the grid
The wardens office APC does not have wires connected to it, this has been resolved IC myself thrice by getting an engineer to connect the green wire under the office door up to the APC
(The APC should be connected to the grid wiring under the floor)

Map issue #2: engineering foyer ping button is unreachable from the lobby
My assumption is the button is actually inside the office stuck to the window? All I know is the player is unable to press the engineering lobby doorbell while standing in the lobby
(The doorbell should be made sure it is OUTSIDE the office and or perhaps connected to the doorbell system)

Map issue #3: security armory doubling up a locker (minor issue)
The locker containing .45 pistols and machine pistols also happens to have a (completely empty) laser rifle locker on the same tile, this means the player must alt click in order to open said locker if the empty laser rifle locker happens to spawn in front rather than behind
(The laser rifle locker on the same tile should be deleted)

All three issues have been discussed in ahelps with Melariara but the issues were not resolved OOCly. (APC had engineers fix it, using the radio instead of doorbell, alt clicking on the tile that contains the pistols //works//)

**Comment by SleepyGemmy** [comment]
issue 1 and 3 fixed in #15925.
