### ISSUE TITLE
Certain Tools/Items of maint drone not working

### ISSUE THREAD

**Issue by Pyrociraptor** [Aurorastation/Aurora.3#1596]
Certains tool of the glorious Mice-eating drones aren't working properly, if not at all.

- The "jetpack" module is just making you drift in space with a fancy trail (probably because they only work on a "backslots" and drones doesn't have that)

- Pipe painter can't be used on their respective field. You can set the colour/decals, but can't use them.

You can still properly crush and absorb mice.

**Comment by Pyrociraptor** [comment]
Edit: Floor painter may be because I'm a bit of an idiot.

**Comment by skull132** [comment]
Floor painter works, seen it used a few days ago.

**Comment by Geevies** [comment]
Fixed.
