### ISSUE TITLE
Jukeboxes/Audioconsoles Can Be Heard Through Walls

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#15977]
having an audioconsole on the other side of a wall and moving around makes it play momentarily before stopping each time you move.

**Comment by FluffyGhoster** [comment]
Actually, I think what you are having is that the sound player finds two sources that are trying to transmit music, so it keeps flip flapping the sound token position, as the source id is the same.

See if #15985 fixes all these issues.
