### ISSUE TITLE
Severe lag and hung process logs

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1602]
Round ID: bMB-dpyb

The round was lagging incredibly badly while round end was being delayed. The following logs occured after forcing a restart:

Log: [debug] scheduler process hung at tick #4230. Process was unresponsive for 90.267 seconds and was restarted. Last task: 0. Last Object Type: null
Diary: [debug:diary] scheduler process hung at tick #4230. Process was unresponsive for 90.267 seconds and was restarted. Last task: 0. Last Object Type: null
Log: [debug] scheduler process was killed at tick #4230.
Diary: [debug:diary] scheduler process was killed at tick #4230.

Lag seemed to start after multiple manhack grenades detonated

**Comment by SierraKomodo** [comment]
As a note, I haven't seen this happen since that specific round, and I have seen manhacks deployed in rounds since then without excessive lag issues.

**Comment by Lohikar** [comment]
This appears to be caused by insane amounts of spark effects.
~1000 spark objects is enough to completely stall the server.

**Comment by skull132** [comment]
No longer valid, bless SMC.
