### ISSUE TITLE
Watches do not have a sprite on the mob when worn.

### ISSUE THREAD

**Issue by incognitojesus** [Aurorastation/Aurora.3#1603]
What it says on the tin. Equipped watches do not have a sprite that is visible on the mob. I am not sure if this was already reported, because I'm not flipping through ten pages of bug reports.

**Comment by skull132** [comment]
There's a search function you silly.

Did they ever have a sprite? I forget.

**Comment by incognitojesus** [comment]
They do. It's like a black band with some red on the end. I can try and find it in oldcode files.
