### ISSUE TITLE
Changeling's adrenaline sac is useless and puts the ling in crit when hit a few times with a stunbaton (disabler too?)

### ISSUE THREAD

**Issue by Ershovdi** [Aurorastation/Aurora.3#16053]
Last round I've made a decision to evolve adrenaline sacs to avoid being stunned into nothingness. Instead, it completely hindered my character when an officer got two hits with a stun-baton, putting me in immediate crit. Probably because of insane adrenaline.
Though,
PM -> [Secondary Administrator PM] ReadThisNamePlz: stun batons stun and cause pain - the pain got you.

I think the sacs should be tested more on a local server, and totally buffed, because they don't do anything against pain. I thought they would help me with pain, but they did not. Several times in a round, I was in pain crit for ~5 minutes just from stunbaton hits.

**Comment by NonQueueingMatt** [comment]
Reagents were improperly created
