### ISSUE TITLE
Medical Doctors not being able to access Suit Sensors on Laptops

### ISSUE THREAD

**Issue by pkisbest** [Aurorastation/Aurora.3#1606]
So, i saw one of the other posts a few days ago about paramedics not being able to access this. Why are medical doctors not able to access them? Unsure if bug or just designed that way.

**Comment by SebkillerDK** [comment]
i was able to put someone inside a sleeper while grabbing them. its was weird and a Little buggy though.

**Comment by skull132** [comment]
Clarification needed, @pkisbest .

Unable to download the program, or unable to open the program?

**Comment by pkisbest** [comment]
Unable to download it at all. The only medical rank seemingly capable is CMO.

I heard from someone that this was somewhat intentional but I'm not sure about that.

**Comment by SierraKomodo** [comment]
I believe you're referring to #1574 correct?

A response to that stated this was intended functionality by @Arrow768

**Comment by pkisbest** [comment]
Why is it intended to be this way. You would think paramedics would be able to access said system, so they can be stationed at other sections of the station, and still be able to view monitoring. 

Maybe, since they may not have the ingame money to do so, place 1 or 2 laptops, hard coded to have suit sensors on them (similar to how the CMO's computer cant be editted software wise) somewhere in medbay. Possibly in the CMO's office.

Having the CMO only have access to it, is just silly, as the CMO has their own sensors monitoring computer.

**Comment by SierraKomodo** [comment]
From my understanding (Arrow will have to step in and confirm or correct this), the intent is to make laptops require a head of staff to provide software installations. I'm not sure on the reasoning.

It was suggested that we make a post in the suggestions forums to contest this decision; I just haven't gotten around to posting a thread up as I never used laptops before aside from the probably powergamey system of popping open suit sensors anywhere I want to track someone (Which might be one of the reasons behind this decision).

**Comment by pkisbest** [comment]
So the CMO can install this on any laptop?

The CMO can however access other command only things on the laptops. Would making the CMO download the suit sensors, not give access for the person who wants the laptop to download other things?

**Comment by Arrow768** [comment]
I was unaware of issue #1574 you opened @SierraKomodo 
What nanako described in the previous issue oversimplifies the problem.

Every Program has at least two access levels required:
* access_run -> Allows to open the program and use it
* access_download -> Allows to download the program to a device
* Additional access levels that are needed for specific functions in the program

Usually the access_run is set to a basic departmental access.
And access_download is set to the departmental head level.

This allows personell to bring their private devices to the head of staff to download the programs they want on that device. (If the head of staff deems that necessary)

Now with a recent pull request I have implemented work and private devices as well as a client enrollment app.
This means, that if you buy / build a new device it comes only with the client enrollment application.
It allows you to select weather a device is a work device or a private device.

If you select work device you are promted with various software presets you can select from.
Once you then confirm the selection, the preset is installed and the device is locked down.
Meaning you can download any additional software that is not in the preset.
(But you have a quick way of getting the software needed for work)

If you select private device then the software downloader and the file manager are added to the device.
And you can, with the above described restrictions in place, download any software you want.

In the future the idea of work and private devices will be expanded quite a bit, but for now it only effects the download and file-transfer software.
