### ISSUE TITLE
Wet Rag is a Container

### ISSUE THREAD

**Issue by Muncorn** [Aurorastation/Aurora.3#1609]
In previous iterations of code, the wet rag (The rag given to the bartender, found on the counter) could be used to wash stuff and would dry out after a certain amount of uses, at which time you could use it on a sink or whatever and make it wet again. Some stupid developer changed it so the wet rag is a container now, so if you wet it it acts like a glass or flask or whatever. This means it can no longer be used to clean anything, and since you wouldn't use it to store liquid anyway it's utterly useless. If it could be reverted to it's previous form, that'd be a charm.

**Comment by skull132** [comment]
Reverting would be kinda pointless, because then it'd stop working as a wet rag would in terms of container abilities.

It should be possible to code it to do both: clean shit and soak up/distribute liquid.

**Comment by Alberyk** [comment]
Except, that the rag can be used to clean things, you just need to pour liquid on it, by using a container on it, and then using the rag on the thing you want to clean.

![rag](https://cloud.githubusercontent.com/assets/11579997/22106757/73e275c8-de31-11e6-8342-3f76368023bb.png)
