### ISSUE TITLE
Cannot hear people talking/see emotes(?) on different z levels

### ISSUE THREAD

**Issue by Greenjoe12345** [Aurorastation/Aurora.3#16146]
So, if are on the upper level of the atrium, for example, you cannot hear people talking on the lower level, when you should reasonably be able to, the same goes for hearing people above you.

**Comment by remona-minett** [comment]
I discovered that you can see silent emotes from other Z levels, but not audible emotes nor speaking. You _can_ see speech bubbles cross-Z too.

**Comment by Greenjoe12345** [comment]
So it's audible stuff then...

**Comment by NonQueueingMatt** [comment]
Not a bug. This is intentional, since there's way too much shit going on to reasonably add z-say.
