### ISSUE TITLE
(Robotics) Requests Console not notifying linked PDAs or updating sprite when message is received

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#1614]
1.
For the past few rounds since the baymerge, I've been noticing that the robotics lab requests console isn't sending any notifications to linked PDAs -- at least to mine.
I also noticed that the icon doesn't change whenever a low-priority message is sent to the requests console. So it's quite easy to miss out on any messages sent.
I've asked on the OOC if anyone else who's linked their PDAs to consoles have them notifying them, and they responded with "Yes"s. I also noticed other requests consoles like the bridge and RD's having their icons change appropriately.

2.
Just a really weeny-teeny-tiny one while we're here on this topic. I wasn't sure if this was enough to constitute a whole bug report: there's a typo on the requests console. If you click "View Messages" when no-one has sent the console a message, the message displayed will say something like "No messages have been **recieved**."

**Comment by Geevies** [comment]
Think this has been fixed.
