### ISSUE TITLE
[Bug]: Elyran Standard (Formerly: Shell Speech Bubbles not saving)

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#16205]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Event / Other

### Describe the issue

Recently, new chat bubbles were added in and an additional one for shells was added, giving them the option to switch between them. Unfortunately, switching to Normal doesn't save between rounds, meaning it needs to be reset every round.

### How to reproduce

1. Select Speech Bubble to Normal
2. Hit save, play round.
3. Load in next round without the speech bubble you selected.

**Comment by NonQueueingMatt** [comment]
Does not seem to happen locally.

**Comment by niennab** [comment]
I am getting this issue too but only with select characters. I'll change Gulrez' speech bubble type, save the slot, reload the slot and for whatever reason it's back to synth.

**Comment by niennab** [comment]
Maybe it's an issue with Elyran IPCs?

**Comment by Melariara** [comment]
I think its actually a bug with Elyran Standard. Had someone else do a ticket where their socks and skin tone gradient weren't saving while they had Elyran Standard as a language. I told them to remove Elyran Standard, then do everything. They did, and it worked.
