### ISSUE TITLE
[Bug]: Smes and APCs terminals don't have a sprite | One atmospheric pipe can't be normaly clicked and needs to be Alt+click

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#16212]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

All APC terminals and Smes one seem to have a invisible sprite, like if it was not wired and just a knot under it, i found this issue with both the SM smes and the Tesla smes, simply a knot in front of them but in reality the terminal was just invisible
![invisible terminal](https://user-images.githubusercontent.com/51837452/232230519-a0111baa-46e0-4804-bb72-f4bcb3aa9b18.png)
![invisible terminal 2](https://user-images.githubusercontent.com/51837452/232230534-92473a2f-156c-4b2f-b1f4-f8bfb71e3650.png)

Another bug is a single tile in atmospherics where you can't click the valve there and need to alt click and select from the list, even new valves you replace it with will still have the same effect

![not possible to click the valve need to alt click](https://user-images.githubusercontent.com/51837452/232230574-b82fbe32-7ad0-42d8-b68d-18924a2274bc.png)

Although an uneducated guess since i don't mess with dreamaker code i would bet these are related to the layering PR that was recently merged

### How to reproduce

It's a round start bug, no additional actions required

### Round ID

N/A

### Staff ckey

N/A

**Comment by FluffyGhoster** [comment]
This could have been resolved alongside the 3/4th update, do you still notice this anywhere?

**Comment by LeiteQualhado** [comment]
> This could have been resolved alongside the 3/4th update, do you still notice this anywhere?

I even forgot about this issue, so i'd say it's solved
