### ISSUE TITLE
[Bug]: South most holodeck has two filling cabinets, one of which spawn medical records from the crew

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#16235]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

For some reason, one of the filling cabinets, the black spawns medical records from the crew much like the CMO one

![Captura de tela 2023-04-19 181614](https://user-images.githubusercontent.com/51837452/233225458-e672fe29-f5c0-4ba5-9317-3f4cb1a50617.png)

### How to reproduce

Have players in round and just go check their records on it

### Round ID

N/A

### Staff ckey

N/A

**Comment by Doxxmedearly** [comment]
Fixed by #16283, can close

**Comment by LeiteQualhado** [comment]
> Fixed by #16283, can close
