### ISSUE TITLE
Maintenance drones and windoors

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1624]
Windoors wont respond to drones walking into them anymore. They have to be manually opened and closed for passage.

**Comment by LordFowl** [comment]
Not a bug, per se. Side effect of @NanakoAC changes to maint drone's size. Same reason they can no longer walk into doors and open them.

**Comment by Pratepresidenten** [comment]
I recall this being an issue back when the new drone slots were introduced, it was fixed up back then. No chance on a patchup for this one aswell?
