### ISSUE TITLE
[Bug]: Examining shells reveals they are shells.

### ISSUE THREAD

**Issue by 4000daniel1** [Aurorastation/Aurora.3#16287]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon, Intrepid, Spark, Away Site, Third party ship, Overmap, Event / Other

### Describe the issue

As the new height system introduced by #16067 tells  'x is tall/short for a species name)', this can be used to reveal shell IPC's pretty effortlessly.  Some exception should probably be made for them so that they are referred to as humans in the examine text instead of shells.

### How to reproduce

Examine a shell IPC.

**Comment by Llywelwyn** [comment]
fixed by #16369
