### ISSUE TITLE
Security/team antag role blacklist

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#163]
Doesn't exist on this version of the code. Think it was a 10-14 day blacklist preventing fresh newfriends from joining as security.

In addition, I believe team antag roles such as heist, nuclear, head rev and roundstart cultist should be somewhere within 21-30 days last I recall with the forum discussions the community had. I'd go with adjusting it to 3 weeks, seems more fair than 4.

**Comment by OneOneThreeEight** [comment]
Bump! This is important.

**Comment by skull132** [comment]
Introduced in #437 .
