### ISSUE TITLE
Paper-Bins get stuck in backpacks

### ISSUE THREAD

**Issue by apophis775** [Aurorastation/Aurora.3#1630]
Steps to reproduce:

Drag paper-bin to yourself to pick it up
Place in backpack
Be unable to remove it
It used to work, it might be part of the new backpack system. Instead of letting me drag the bin back out into my hand, it asks me to remove paper.

**Comment by skull132** [comment]
Paperbins shouldn't actually be backpackable. They used to be too large for it. Most likely an edgecase from the new storage system.

**Comment by apophis775** [comment]
I'm pretty sure I've been able to put Paperbins in backpacks in the past.  But, I can see the reasoning to not want it, especially if someone is a cultist.

**Comment by skull132** [comment]
..I didn't even think of the cultist reason.

They just seem super bulky and annoying and shit to be backpackable.

**Comment by apophis775** [comment]
Oh weird.  I figured it was cultists.  I mean, a box of 50 sheets of paper is no bulkier than a fire extinguisher IRL, so i figured it was because cultists could use them nearly infinite supply of traveling paper.
