### ISSUE TITLE
Traitor borgs cant hack themselves.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1636]
Seems to be a problem as both linked and unlinked borgs. There just isnt a "Hack" option on the robotics console anymore for traitor borgs.

**Comment by SirFruitcakes** [comment]
Bumping this as it makes playing a Station-bound Traitor literal hell.

**Comment by Alberyk** [comment]
This is fixed, antag borgs get hacked by default now.
