### ISSUE TITLE
[Bug]: Issues with the Unathi Guild Miner Station

### ISSUE THREAD

**Issue by Dekserrrrrr** [Aurorastation/Aurora.3#16370]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Third party ship

### Describe the issue

**Some Issues with the new Unathi guild station:**

-The shuttle cannot redock with the guild station after departing

-Shuttle flag is on the floor and not on a wall
![image](https://github.com/Aurorastation/Aurora.3/assets/92396228/c15b889f-8067-40a3-adfc-632fc45c03cf)

**More minor issue:**

-There are no GPS's for the Miners to take with them

this is not an issue but I **suggest** making the spawnpoints for the Unathi Miners on the shuttle itself, that way if midround someone decides to play the role, they aren't stranded on the station while the shuttle is away.

### How to reproduce

These should be availably noticeable when playing the role itself.

### Round ID

cnT-cJR5

**Comment by deGurkin** [comment]
But wait, there is more!
The Cycler does not cycle properly into the shuttle, burning our way inside proves that the Airlock controls do nothing - a good fix would be a controller on the inside like with the Cataphract shuttle

Also the Air tank to pressurise the lock starts empty
![grafik](https://github.com/Aurorastation/Aurora.3/assets/30761807/c414aa66-da9f-47d2-b1d2-2339f71c9d9e)
![grafik](https://github.com/Aurorastation/Aurora.3/assets/30761807/740e6cfd-2c53-45d2-aa2f-59a9477be239)

There is no Multitool to hack the doors either
No inflatables at all
The Lever for the Conveyor inside the Shuttle does not activate the conveyors inside  the shuttle
apparently one of the conveyors is doubled up
![grafik](https://github.com/Aurorastation/Aurora.3/assets/30761807/3ac0642e-dadf-4972-b440-092b6eecbadd)

There is no smelter control only an Ore Point redemption console which is pointless without the vendor
![grafik](https://github.com/Aurorastation/Aurora.3/assets/30761807/cf422273-8e5f-4241-a1b3-35fc1c0a5538)

The Station Sensor Console has issues connecting
![grafik](https://github.com/Aurorastation/Aurora.3/assets/30761807/54e0e8ee-4354-44a4-8514-9e63479829d2)

There is Alcohol in the breakroom but no Xuizi, so they have access to poison but no booze (there is Sarhezi Wine)
There is no universal Enzyme to make Cheese
There is no access to Water to boil eggs (or to have Water)

There is problably more I am forgetting.
