### ISSUE TITLE
Optical Material Scanner not showing ores properly.

### ISSUE THREAD

**Issue by XenosTiger** [Aurorastation/Aurora.3#1638]
So, here I am with yet another baymerge issue!

Basically, Y'know how optical material scanners work? They're supposed to show you things like furniture, doors, and, most importantly, ores, across the entire screen, regardless of whether or not you have an unassisted visual. However, it doesn't do that. Possibly because, from what I heard, Bay doesn't have ores in the walls? Dunno.

HOWEVER, the scanner is NOT operating as intended. It's not showing all ore nodes on-screen, like it did before Baymerge. So, miners are stuck digging endless networks of tunnels through the asteroid in the vain hopes of maybe discovering a node of ore.

-Edit: "Discovered" ores are still governed by naked line-of-sight. If you couldn't see them without the material scanner, you can't see them _with_ the material scanner, rendering half of the prior paragraph obsolete/invalid.

![aurora station 2017-01-24 174726](https://cloud.githubusercontent.com/assets/18099476/22270607/6551e7ba-e25e-11e6-8ba9-eeba59fbe727.png)
![aurora station 2017-01-24 174655](https://cloud.githubusercontent.com/assets/18099476/22270608/655b7e38-e25e-11e6-8350-97c788becb54.png)

**Comment by XenosTiger** [comment]
Notice the strip of two pieces of ore that were undiscovered in the second image, but showed up later in the first one. (Sorry for the images being out-of-order.)

**Comment by Lohikar** [comment]
That looks like an Optical Meson Scanner overlay, you sure you're using the right type of scanner?

**Comment by printer16** [comment]
The industrial suit has mesons, not materials for some odd reason. Probably an oversight, not hard to fix either.

**Comment by Fire-and-Glory** [comment]
If I remember right from my stretch as miner last night, while my optical material scanner didn't see ores in the walls, and neither did my meson scanner, but if I paired the two together then I could see the ore veins.

I'll be needing to fiddle around, however.

**Comment by Fire-and-Glory** [comment]
![untitled6](https://cloud.githubusercontent.com/assets/19973802/22276122/65ee2f4a-e316-11e6-8f4b-f7c34f896b23.png)

Sorry for big image but I feel this is sufficient information.

**Comment by Alberyk** [comment]
That is because materials scanners don't really remove the darkness from the places anymore, like mesons do.

**Comment by Pratepresidenten** [comment]
To bump this issue, newmap material scanners works well when you buy them, but after you press them into a rig module, (material/meson scanners) they stop detecting materials.

**Comment by Fire-and-Glory** [comment]
The material/meson scanners is a toggle-able visor that can be changed in the hardsuit tab, although the game will tell you that both modes are mesons, it's really just switching between mesons and material scans.

**Comment by chaoko99** [comment]
Still a problem.

**Comment by JohnWildkins** [comment]
Fixed due to removal from general usage in #9726 and replacement in purpose in #10182
