### ISSUE TITLE
[Bug]: Missing disposal pipe near the public garden

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#16393]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Missing disposal pipe near the public garden which is causing trash to be spilled out and the tile damaged
![no disposal](https://github.com/Aurorastation/Aurora.3/assets/51837452/40d8e09a-396c-497e-ad3b-85061b90a7fc)

### How to reproduce

Star a new round and head to the location on the picture

### Round ID

N/A

### Staff ckey

N/A

**Comment by deGurkin** [comment]
can confirm
![grafik](https://github.com/Aurorastation/Aurora.3/assets/30761807/3b93b683-513d-462c-aa5d-289e1f6c494f)

**Comment by Llywelwyn** [comment]
was fixed by #16400

**Comment by LeiteQualhado** [comment]
> can be closed, was fixed by #16400
