### ISSUE TITLE
[Bug]: Anomaly Container Interactions While Incapacitated

### ISSUE THREAD

**Issue by TheSleepyCatmom** [Aurorastation/Aurora.3#16394]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Interacting with an anomaly container while incapacitated, or otherwise crit (no use of hands) allows the interactions to take place when they realistically shouldn't.

### How to reproduce

1. Be Incapacitated (IPC out of power, Paincrit, so on)
2. Interact with an Anomaly Container (Put an Anomaly inside, take it out)
3. Interaction occurs.

### Round ID

cnY-bl32

### Staff ckey

Melariara

**Comment by FluffyGhoster** [comment]
Fixed in #17290
