### ISSUE TITLE
Shuttles on the asteroid leave a mess of sand when they leave

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1641]
![image](https://cloud.githubusercontent.com/assets/19973802/22284754/8b7bb32c-e34d-11e6-99f2-13ba615978d4.png)

This is hugely ugly and doesn't really make sense, I went and confirmed it doesn't happen on-station, I've also seen the raider shuttle leave sand in space near the asteroid framing its form.

**Comment by Alberyk** [comment]
I am nearly sure it is because bay changed their asteroid to be a planet; aka no space.
