### ISSUE TITLE
[Bug]: EMPs don't affect prosthetics

### ISSUE THREAD

**Issue by TMR-SS13** [Aurorastation/Aurora.3#16430]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

I, as an Head Revolutionary, used EMPs to attempt to kill the Captain, who was a heavily augmented individual with prosthetic limbs and a prosthetic heart. The EMPs had zero impact on them, but did have full effect on a nearby IPC. This seems to be an oversight or bug, since prosthetic limbs and organs should be impacted by EMPs.

### How to reproduce

1. Be a person with a prosthetic limb.
2. Drop EMP by your feet.
3. Feel nothing.

**Comment by Doxxmedearly** [comment]
Tested and it does seem to HIT both internal and external prosthetics, but the damage is so minor it may as well have been nothing. Definitely still a bug. Could be an issue with `species.handle_emp_act()`

**Comment by FluffyGhoster** [comment]
EMPs got recently reworked, reopen if this is still relevant
