### ISSUE TITLE
CCIA does not have access ti the NTCC Odin turret controller

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1644]
Even using the 'all-access' ID card that's on the table next to the controller doesn't work anymore. We get 'Access Denied'

**Comment by Lohikar** [comment]
The 'all-access' ID on the table does not have access (it's just captain level), but your CCIA ID should work.

Testing on a local serv shows that CCIA IDs are able to unlock the turret controller.

**Comment by SierraKomodo** [comment]
Must have been lag preventing the CCIA ID from unlocking the panel; During the round I reported this from, I got no event logs at all when using an ID on the controller.

Seems to be working now.
