### ISSUE TITLE
NTCC Odin turrets will shoot everyone when activated, including CCIA

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1645]

**Comment by Lohikar** [comment]
Tested with BSTs, CCIA, and an ID-less mob, turrets did not fire on BST or CCIA but fired on ID-less mob.

The turrets' AI isn't that smart, were people between the turret and what the turret was trying to shoot?

**Comment by SierraKomodo** [comment]
Seems to have only happened during that one round; I haven't been able to get it to happen again on my end.
