### ISSUE TITLE
Shells can't change eye or skin colour

### ISSUE THREAD

**Issue by sleepywolfie** [Aurorastation/Aurora.3#1646]
Shell frames cannot change eye colour, or skin colour

**Comment by SierraKomodo** [comment]
Can confirm this is happening on my shells as well.

**Comment by SierraKomodo** [comment]
It also seems the character appearance dialog menu (The nano UI one that admins can give you, or that is used for wizards/mercs/CCIA/etc) also doesn't update the appearance of shells.
