### ISSUE TITLE
[Bug]: Unable to climb ladders as cult artificer

### ISSUE THREAD

**Issue by Rookieeyes** [Aurorastation/Aurora.3#16488]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

As an artificer I was unable to climb ladders using the manual chat commands, IC verbs, or clicking as I would normally. 
![you lack means of travel in that direction](https://github.com/Aurorastation/Aurora.3/assets/121529171/6b5279af-33a3-422c-b2c9-8e0ac8432df6)

### How to reproduce

1. As a cult artificer construct occupy the same space as a ladder as you would to climb.
2. click on the ladder - nothing should happen.
3. Try to manually enter "move-down " or "move-upwards " You should get the message "You lack means of travel in that direction."
4. Try to use the verbs under the IC tab - same results as 3.

### Round ID

com-dpt2

**Comment by FluffyGhoster** [comment]
This sounds intentional, if there's gravity. Also you lack the hands to use a ladder, like borgs, which I presume have the same limitation (?)

**Comment by Rookieeyes** [comment]
Very well. I'll close the issue in that case. Thank you for your time.
