### ISSUE TITLE
Abandoned crates no longer spawn while mining

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1652]
Due to the inherent random nature of this, feedback from other recent miners and/or coders who have looked at this particular bit of coding recently would be appreciated.

From what I have observed, ever since we have had the latest BigBaymerge update, not one abandoned crate has spawned, whether they spawned before that update is unknown to me.

Regardless, I usually do a fair amount of wall mining as miner, making 3-tile wide tunnels as I go, typically spawning one or more abandoned crates every two rounds a few months back.

This month, I have played 4-5 rounds of miner while doing this wall mining(so far), and have not seen one crate.

**Comment by LordFowl** [comment]
At some point Bay removed them. I can't actually find a commit that does this, so I don't know why, but they're gone.
