### ISSUE TITLE
[Bug]: A bunch of TGUI issues

### ISSUE THREAD

**Issue by lavillastrangiato** [Aurorastation/Aurora.3#16530]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

1. Readability of the NTos/computer programs has decreased. No more bright green buttons to click!
2. **Suit sensors no longer have the name of locations on them, just coordinates.** This is a serious problem when you are medical-- it makes serious cases that much harder to hunt down if you don't have a name.
3. Text on pop-up windows is very small, decreasing readability.
4. Colours on pop-up windows, such as the suit sensors UI and the body scanners, mean it is harder on the eyes. A slightly lighter background on the window makes things way easier on the eyes.
5. **GAS SUPPLY CONSOLES ARE NO LONGER LABELLED WHAT GAS THEY ARE D:**
6. You can't click on accents to bring up their blurbs anymore in chat.

![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/5c03202b-7d3d-420c-bc82-f304d0013352)
![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/3774e7fa-36aa-42ec-a64d-1b9e6e9bf4dc)
![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/c83d962a-1afb-46e0-9c61-5d44d9341212)

### How to reproduce

1. Open the computer programs.
2. Open suit sensors. No coordinates.

1. Open gas supply consoles.
2. No labels.

1. Click accent tag.
2. No blurb.

### Round ID

cov-acSX

**Comment by NonQueueingMatt** [comment]
The bugs here are fixed. For the rest, we'll wait a few days - it might just be a "getting used to it" issue.
