### ISSUE TITLE
[Bug]: Cannot Load Title Screen (and thus cannot join)

### ISSUE THREAD

**Issue by zagoon** [Aurorastation/Aurora.3#16531]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Event / Other

### Describe the issue

Since the TGchat merge I've been unable to load the title screen. It worked for a few minutes at the beginning of the first round it was merged, but disappeared while I was fiddling with the chat settings and hasn't loaded since.

I've tried: 
- clearing the cache and waiting for the resources to redownload
- reloading byond and the game several dozen times
- sitting around in the lobby for half an hour
- restarting my computer
- uninstalling and reinstalling
- both stable and beta builds
- playing with the chat settings some more in case that was somehow the culprit

This appears in the status pane every time I attempt to load: 

![infowindow](https://github.com/Aurorastation/Aurora.3/assets/9440824/e8fb9e2d-5fa6-4b20-88f7-cc60af28b2d0)

Aside: is it possible to create verbs for readying and observing (the Observe verb in the OOC tab seems to be for something else) to reduce reliance on the title screen functioning correctly?

### How to reproduce

1. attempt to join the game
2. be one of the unfortunates who can't seem to load the title screen

### Round ID

cov-acSX, cov-aCeK

**Comment by NonQueueingMatt** [comment]
This is an asset issue, not particularly something we can solve. I'll look into what we can do, though.
