### ISSUE TITLE
[Bug]: Rest, Sleep missing. Tactical Laying down disabled after TGUI addition

### ISSUE THREAD

**Issue by Syncrosync** [Aurorastation/Aurora.3#16540]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Rest, Sleep verbs missing. Tactical Laying down disabled after TGUI addition

### How to reproduce

N/A

**Comment by NonQueueingMatt** [comment]
First bug is fixed. Second is not a bug - it's just not testmerged.
