### ISSUE TITLE
[Bug]: TGUI? Some vampire abilities don't come back after use

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#16555]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Some abilities like screech and glare are one use, they don't reappear, assuming from TGUI update

### How to reproduce

1. Be vampire
2. Use Glare or C. screech
3. See they never come back

### Round ID

cow-apMC

**Comment by NonQueueingMatt** [comment]
Caused by add_verb_in not having the proper amt of args
