### ISSUE TITLE
[Bug]: Merchant's List is not found by the TG UI.

### ISSUE THREAD

**Issue by Zintizoodaa** [Aurorastation/Aurora.3#16551]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [ ] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Third party ship

### Describe the issue

The Merchant's List function on the merchant station does not function, and instead says "Interface was not found".

### How to reproduce

1. Opened the console on the merchant station.
2. Clicked "Merchant's List"
3. Merchant's List displays "Interface not found".

### Round ID

cov-dEDL

### Staff ckey

None contacted.

**Comment by NonQueueingMatt** [comment]
Deadass completely forgot to port this UI
