### ISSUE TITLE
You can bring back the dead with a robotic head transplant

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#1656]
If you place a robotic head on a headless body and then put a brain inside, it will bring back the body to life with the brain in control of said body in question. I guess it is related to how you revive ipcs now ,but, this surely should not work if the body is organic.

**Comment by MarinaGryphon** [comment]
Another issue is that I'm pretty sure `life()` is never procced after doing this. That means if they fall asleep, they'll never wake up on their own. They also won't process chems, heal, etc. I'm not sure if they even need to breathe- which is a huge issue.

Fixing the robotic head on an organic body thing would be a simple fix, but I think there's a deeper issue at play.

**Comment by Alberyk** [comment]
Fixed.
