### ISSUE TITLE
[Bug]: TGUI: Follow verb borked

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#16568]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Follow verb as ghost seems to randomly break, unless it's tied to antagHUD? In this case it was on.

![image](https://github.com/Aurorastation/Aurora.3/assets/5076069/306e34ae-0445-4333-b056-fbc3efdff3c8)

### How to reproduce

1. Observe a round
2. Turn on AntagHUD
3. Click Follow to see who the antags are
4. Bluescreen error?

### Round ID

cow-dyAP

**Comment by NonQueueingMatt** [comment]
should be fixed now
