### ISSUE TITLE
[Bug]: AI Command and Communications failure due to new interface

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#16564]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

AI's can no longer properly change alert levels through the command and communications console, due to the new interface.

When interacting through the shell you get "Console pings: "Command and Communications Program downloaded successfully!""

When interacting through the core you get "You're too far away from the command console to do that."

### How to reproduce

1. Play AI
2. Interact with the command and communications program on any head console

### Round ID

cow-cPAH

**Comment by NonQueueingMatt** [comment]
Fixed in https://github.com/Aurorastation/Aurora.3/pull/16560, don't download stuff but instead use the C&C console in the bridge
