### ISSUE TITLE
[Bug]: Turrets have their behavior locked to AI

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#16565]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

AI's can no longer change the state of any turrets on the vessel, as the controls are 'behavior locked' with no apparent way to unlock them.

### How to reproduce

1. Play AI
2. Interact with any turret control panel

### Round ID

cow-cPAH

**Comment by NonQueueingMatt** [comment]
Fixed by https://github.com/Aurorastation/Aurora.3/pull/16560
