### ISSUE TITLE
[Bug]: Synthetic equipment can no longer shift+click to open airlocks

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#16567]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

AI, cyborgs and drones can no longer shift+click airlocks to open them remotely, which is a rather big and annoying handicap when your main job is described as a 'door opener' lol.

The only current way to open an airlock remotely is to click it and open the interface, then toggle doors state, which is very cumbersome.

### How to reproduce

1. Play AI, Borg or Drone
2. Shift+click any airlock

### Round ID

cow-cPAH

**Comment by Playbahnosh** [comment]
Already fixed. https://github.com/Aurorastation/Aurora.3/issues/16547

**Comment by NerdyVampire** [comment]
> 

Ah, wasn't working in my last round. Must not have been updated yet then. Thanks!

**Comment by NonQueueingMatt** [comment]
Fixed by https://github.com/Aurorastation/Aurora.3/pull/16560
