### ISSUE TITLE
IPC/Shell bug: Human shell with organic left leg.

### ISSUE THREAD

**Issue by CompleteGarbage** [Aurorastation/Aurora.3#1657]
I noticed near the end of one round that my left leg was organic. I was playing an IPC shell named Taurus. Will update with more information if any arises.

First encountered: GameID bMM-aoig

I have not attempted to reproduce yet, I will add a post later when I do.

Relevant image: https://gyazo.com/61e3816e3d395682da45e00aa352cd41

**Comment by Fire-and-Glory** [comment]
I can verify that this exists, it has occurred to me in the past.

@Alberyk has had experience with this too.

**Comment by skull132** [comment]
@LordFowl

**Comment by LordFowl** [comment]
@skull132 As FaG states, this doesn't appear to be an issue because of shells. Probably an issue with the robotize() proc.
