### ISSUE TITLE
[Bug]: Use-Scope verb doesn't work (at least on prototype weapons

### ISSUE THREAD

**Issue by Kelnor277** [Aurorastation/Aurora.3#16574]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon, Intrepid, Spark, Away Site, Third party ship, Overmap

### Describe the issue

The Use-Scope verb does not work on prototype weapons (and possible not on any weapon)
The use scope right click option is no longer there. (neither is "name prototype" or "describe prototype" incidentally)
Manually attempting to "Use-Scope" in the bar does nothing either.
Also, and I don't know if it's a bug or not, but the Toggle-Safety verb used to bring up a dialog box asking which gun (if you had more than one in your inventory.) now it simply seems to toggle the safety on a random gun in your inventory (it was doing it to the pistol in my pocket instead of the rifle I was holding when I tested it.)

### How to reproduce

Build a laser prototype with a scope (or possibly use a premade gun with a scope).
Hold the weapon properly using both hands
Type "Use-Scope" into the command bar.
Watch nothing happen.

**Comment by NonQueueingMatt** [comment]
Fixed by https://github.com/Aurorastation/Aurora.3/pull/16577
