### ISSUE TITLE
[Bug]: Tech Processor not working

### ISSUE THREAD

**Issue by Kelnor277** [Aurorastation/Aurora.3#16573]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Tech processors don't seem to increase research.
There was an offship server.
Tried it with my research console attached to the core RnD server and the other RnD server.
I do not know if an offship RnD server affects this or not.
It was working before TGUI. Unsure if that is what broke it however.

### How to reproduce

Build tech processors.
Attach to core RnD server.
Obeserve research progress.
Synch research.
See no progress.

### Round ID

cox-akC7

**Comment by Kelnor277** [comment]
Update: I just tested with no offship and it worked, either it was fixed by something else, it only happens if there's an offship server or it could have just been severe lag taking forever to update on the first round.
I'll update with more information when I can.

**Comment by Playbahnosh** [comment]
This issue has been explained here: https://github.com/Aurorastation/Aurora.3/issues/15727

**Comment by Kelnor277** [comment]
Nevermind it's working, either I was mistaken the first time or it got fixed. Closing
