### ISSUE TITLE
[Bug]: [TGUI]: Operations bounties can't be claimed

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#16570]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/5076069/2ce5f70c-be8d-4842-a837-8b5e2ded9575)

Bounties unable to be claimed once completed

### How to reproduce

1. Complete a bounty
2. Try and claim credits
3. Cry

**Comment by NonQueueingMatt** [comment]
forgot to add the fucking button

**Comment by NonQueueingMatt** [comment]
fixed by https://github.com/Aurorastation/Aurora.3/pull/16576
