### ISSUE TITLE
[Bug]: Chat colours unintentionally changed

### ISSUE THREAD

**Issue by Spookat** [Aurorastation/Aurora.3#16588]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

The radio channel colours were unintentionally changed while importing TGUI. Common radio is very dark, as are Tajara languages. Likely others too.

Might fix this myself tomorrow, just putting it here as requested by Matt.

**Comment by io-util** [comment]
Tajaran Language colours do not seem to have changed, and look completely normal in my eyes. 
![image](https://github.com/Aurorastation/Aurora.3/assets/39163886/a26fc76b-bd9a-47df-b150-adc6c588f5fc)

Though common color definitely got darker than it was before, which may have made it a little harder on the eyes for some people. It changed from 

![image](https://github.com/Aurorastation/Aurora.3/assets/39163886/d1da7895-448f-4c43-bae2-8e35851f7c0a)

to

![image](https://github.com/Aurorastation/Aurora.3/assets/39163886/cc9afe0d-0c75-4ae2-a042-8966fb774c66)

**Comment by Spookat** [comment]
> Tajaran Language colors always looked this dark iirc (though I am not a Tajaran player, and I am just judging from what I saw observing).
> 
> ![image](https://user-images.githubusercontent.com/39163886/249651843-a26fc76b-bd9a-47df-b150-adc6c588f5fc.png)
> 

![image](https://github.com/Aurorastation/Aurora.3/assets/99222453/2dedab50-1620-4f67-adfc-c0b31e3db0df)

This is pre-TGUI.

**Comment by NonQueueingMatt** [comment]
Some colours were different for some reason
