### ISSUE TITLE
[Bug]: TGUI menu windows disappearing occasionally

### ISSUE THREAD

**Issue by Spookat** [Aurorastation/Aurora.3#16589]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

TGUI menus seem to close themselves every once in a while. Happens anywhere between a few seconds to five-ten minutes. I noticed this in the lobby and while playing FR as I tend to have a window permanently open for suit sensors.

All menus seem to be affected, but the ones I have personally witnessed:
Crew Manifest, Suit Sensors, Player Panel, Check Antagonists

Doesn't appear to be related to new data entries (players joining/cryoing), didn't notice a particular trigger for it to happen.

### How to reproduce

1. Open Crew Manifest in lobby or in-game
2. Wait

**Comment by lavillastrangiato** [comment]
This also applies for the character customization pop-up for offship roles.

**Comment by Playbahnosh** [comment]
Also had this happen as borg with Alarm Monitor, RCON and Crew Manifest. Windows just randomly disappear and have to be opened again.

**Comment by zagoon** [comment]
This happens with the PDA chat client, too. Sometimes it just closes the window immediately after opening; sometimes it can take a few minutes.

**Comment by Spookat** [comment]
This happens to all players with menus open at the same time, or at least the same program open, from what I've noticed.

**Comment by NonQueueingMatt** [comment]
fixed
