### ISSUE TITLE
[Bug]: TechnoMancer Core bugs out after reconnecting

### ISSUE THREAD

**Issue by ARandoDude1337** [Aurorastation/Aurora.3#16598]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

After having to reconnect as a technomancer. My "Spell" Core Ceases to function. Even after taking it off and putting it back on. along with taking it off waiting a few seconds and putting it back on. Nothing seems to pop back up.

### How to reproduce

1. Roll Technomancer
2. Reconnect
3. Core stops working
4. Hopefully a benevolent fix.

### Round ID

coz-a9tv

**Comment by NonQueueingMatt** [comment]
Fixed by #16805
