### ISSUE TITLE
[Bug]: Defib attempts get return 0'd if the patient is on surgery-compatible surfaces (OR tables, standard tables, stretchers)

### ISSUE THREAD

**Issue by scheveningensun** [Aurorastation/Aurora.3#16592]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

The new defib produces the "you're not sure what to do with this" error message commonly seen when doing an incorrect surgery step, if the person receiving the shock is on a surgery compatible surface. This is likely because of the game thinking the defib is a surgery tool, which prevents its actual intended behavior as a device from working correctly on the related surgery surfaces.

**Comment by NonQueueingMatt** [comment]
defib wasn't added to the safety check override, oops
