### ISSUE TITLE
Transform sting causes you to slowly die from massive organ rejection

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1660]

**Comment by Alberyk** [comment]
I guess this happens when you change species or something?

**Comment by LordFowl** [comment]
Shouldn't do. Transform sting is likely using an outdated change species proc.

**Comment by SierraKomodo** [comment]
@Alberyk The people affected included those who didn't change species (They were human), and an IPC that had been changed with a human's DNA
