### ISSUE TITLE
[Bug]: clicking "reply" button next to PDA messages in the chat view does not work

### ISSUE THREAD

**Issue by CaptainGecko** [Aurorastation/Aurora.3#16601]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

![Untitled](https://github.com/Aurorastation/Aurora.3/assets/94259758/d9cb8d55-22c8-4c74-8789-478816d89bec)

Clicking the "(reply)" button next to messages doesn't actually bring the PDA chat window.

### How to reproduce

1. Receive PDA message
2. Click "(reply)"

### Round ID

coz-cUyp

**Comment by NonQueueingMatt** [comment]
fixed in next PR
