### ISSUE TITLE
[Bug]: Body scanner gives wrong body temperature

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#16600]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

The individual has ~37 C body temperature. 
Inside the body scanner, it states that their body temperature is around ~310 C (This seems to be pulling the kelvin temperature and saying its celsius. 
When a scan is printed, their body temperature is -240 C (This seems to be pulling the celsius temperature and saying it's kelvin).

Medical Scan:
![image](https://github.com/Aurorastation/Aurora.3/assets/8042031/88b5dfea-0b42-4268-9de9-e2d092405646)
Inside Body Scanner:
![image](https://github.com/Aurorastation/Aurora.3/assets/8042031/2d532187-9946-4a1d-9da1-42361f3a6193)
Body Scanner Printed:
![image](https://github.com/Aurorastation/Aurora.3/assets/8042031/f5ab7e7a-f11a-47e2-93a7-5cb13c21ee9d)

### How to reproduce

1. Medical scan human, note temperature
2. Put human in body scanner, note temperature
3. Print body scan, note temperature

**Comment by NonQueueingMatt** [comment]
fixed in next PR
