### ISSUE TITLE
[Bug]: Clicking away or out of PDA chat while having text in box causes the text to send.

### ISSUE THREAD

**Issue by lilahnovi** [Aurorastation/Aurora.3#16618]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

When writing chat messages on the PDA, if you click off the game screen, click to move the chat PDA window, or click anywhere that isn't directly either the chat screen, it will send the message.

### How to reproduce

1. Open the PDA.
2. Go to Chat Messaging.
3. Click your best friend.
4. Open their window.
5. Type something in the chat bar, but don't click send.
6. Click away from the PDA window - into the game, onto your other monitor, onto the title bar for the PDA menu, anything.
7. Watch as your message is sent unfinished to your friend. 
8. Experience woe if you click away and click back, and watch the same message send over and over again.

**Comment by NonQueueingMatt** [comment]
"fixed" (it wasn't a bug but i got rid of it)
