### ISSUE TITLE
[Bug]: Probably related to TGUI: Black menu for many players

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#16611]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Event / Other

### Describe the issue

Myself and 6 other players are having a issue that at random we just won't be able to join the game due to the menu going black, usually it would happen at round end which would need to relaunch the game, but now simply won't work if you join the server.

restarting the PC doesn't work, waiting 30 minutes doesn't, clearing cache doesn't, and i'm willing to bet other players also are having this issue

### How to reproduce

Roll the dice and get hit by the curse

### Round ID

N/A

### Staff ckey

N/A

**Comment by NonQueueingMatt** [comment]
This is related to the new asset sending in some way. I testmerged a PR that might make it better and did a config change that we forgot to do - let's see if it helps.

**Comment by dessysalta** [comment]
> This is related to the new asset sending in some way. I testmerged a PR that might make it better and did a config change that we forgot to do - let's see if it helps.

Not sure if my opinion is needed, but it's still bugged out for me. Just tried to join and I have a black menu screen, dunno if the PR is still testmerged or not.
