### ISSUE TITLE
[Bug]: Exosuit fabricator prosthetic manufacturer options don't work

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#16616]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

No matter which manufacturer I selected, it produced a Hephaestus Integrated Limb variant of the prosthetic.

### How to reproduce

1. Select Bishop Cybernetics or any manufacturer besides Hephaestus Integrated Limb
2. Print a Prosthetic (External) limb such as Prosthetic Left Arm
3. Notice it printed a Hephaestus Integrated Limb left arm

### Round ID

coC-cqZa

**Comment by NonQueueingMatt** [comment]
fixed in next PR
