### ISSUE TITLE
[Bug]: TGUI: Missing bottle selection on Chem Master

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#16612]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

The selection of the bottle type for the chemaster is now missing after the introduction of the TGUI making unable to choose different shapes

### How to reproduce

Try to make a chemical bottle on chem master

### Round ID

N/A

### Staff ckey

N/A

**Comment by NonQueueingMatt** [comment]
`dat += "<tr><td><a href=\"?src=\ref[src]&bottle_sprite=[sprite]\">[chem_asset.icon_tag(sprite)]</a></td></tr>"`

The spritesheets are probably used wrong here
