### ISSUE TITLE
[Bug]: PDA Crew Manifest Does Not Have Top Buttons

### ISSUE THREAD

**Issue by NobleRow** [Aurorastation/Aurora.3#16620]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

When you open the crew manifest on your PDA, the entire top bar is gone. This includes the X button, the power button, the minimize button, the PDA light button, and so on. You are also effectively stuck on the crew manifest unless you screwdriver the PDA to turn off the power.

![Screenshot 2023-07-03 165310](https://github.com/Aurorastation/Aurora.3/assets/137841920/15e66dfe-a700-43e3-aa6c-897a348b59f3)

### How to reproduce

1. Open PDA
2. Click the "Crew Manifest" button
3. Try to get out.

**Comment by NonQueueingMatt** [comment]
fixed
