### ISSUE TITLE
[Bug]: Changeling abilities not functioning correctly

### ISSUE THREAD

**Issue by Ublict** [Aurorastation/Aurora.3#16629]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Multiple changeling abilities do not work properly. Transformation sting does not work at all. I attempted to sting people and monkeys during a round to make them turn into clones of myself, and it did not work. I received correct text that my sting was ready but harm intent does not do the sting and just normally punches. 

Lesser form ability is only half functional. I can use it and change back to the regular form, but the menu becomes glitched and in order to see the correct menu again and not the non-functional lesser form menus I need to relog every time after using the ability and returning to the normal form. 

### How to reproduce

1. Be changeling
2. Buy transformation sting and lesser form ability
3. Attempt to use transformation sting as the text tells you to. It does not work
4. Attempt to use lesser form. it will work
5. Revert to normal form. Menus will remain the same as they were as the lesser form and be unusable and non-responsive.
6. relog
7. Menus are normal and bugs can be repeated.

### Round ID

coD-aKRg

### Staff ckey

Evildwells666

**Comment by NonQueueingMatt** [comment]
> Transformation sting does not work at all. I attempted to sting people and monkeys during a round to make them turn into clones of myself, and it did not work.

It does work, I just tested it in game - it just doesn't work against live peoplee. They need to be dead first.

Second will be fixed in the next PR
