### ISSUE TITLE
[Bug]: Defib 'disappears' + icon stuck in hand if you attempt to use it unwielded

### ISSUE THREAD

**Issue by Bamboogled** [Aurorastation/Aurora.3#16623]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

If you attempt to use the auto-resuscitator on someone without wielding the paddles, it will you give the normal 'You need to wield the paddles with both hands before you can use them on someone!' error, but at the same time the defib seems to disappear (can't be dropped) and the icon is stuck in your hand. You can still pick up objects with the hand, but icons will overlay on top of the defib icon.

You can still examine the defib and even deploy the paddles and use it as normal, but you can't seem to drop it and the icon seems stuck.

I couldn't reproduce this issue with the compact defibrillator variant.

https://i.imgur.com/okSgbvb.gif

### How to reproduce

1. Pick up auto-resuscitator.
2. Deploy paddles.
3. Use the paddles on someone WITHOUT wielding them.
4. Red text tells you you need to wield them, you now cannot drop the auto-resuscitator and the icon is stuck in your hand.

### Round ID

coC-dBZ2

**Comment by NonQueueingMatt** [comment]
cannot replicate locally

**Comment by Bamboogled** [comment]
Update to this since it happened to me in another round (coM-dvVa). This was with the compact defib variant, my belt got stuck in my hand (could access storage but not equip to any slot or drop it, icon stuck in hand) after I wielded the defib paddles with my belt in my other hand.

**Comment by wshuwshuwshi** [comment]
happened to me.

Hold Autorescusitator in hand
Use in hand
Wield Paddles

Now the autorescusitator is stuck in your hand. If you click the icon, you can grab the paddles. But you can also hold things "on top" of the autorescusitator sprite

Round ID
coU-drc0

Staff Ckey
No Response

**Comment by wshuwshuwshi** [comment]
[https://cdn.discordapp.com/attachments/970384062252474379/1132053198765568140/image.png](url)
[https://cdn.discordapp.com/attachments/970384062252474379/1132053252230361239/image.png](url)
[https://cdn.discordapp.com/attachments/970384062252474379/1132053321654468718/image.png](url)
[https://cdn.discordapp.com/attachments/970384062252474379/1132055411005071480/image.png](url)
