### ISSUE TITLE
[Bug]: Inbuilt cyborg computer has no option to close programs

### ISSUE THREAD

**Issue by Infixx** [Aurorastation/Aurora.3#16622]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

I can use the inbuilt borg computer fine up to the point I use a program and it will not let me close said program I have tried a ton of times reconnecting changing to beta version dialing back a version etc nothing.

![123](https://github.com/Aurorastation/Aurora.3/assets/17614288/ba8e392a-b4c1-43d1-9423-42caf53ba8f9)

Also when I open the inbuilt computer for the first time in a round or when I reconnect nit gives me this message in chat 

![1234](https://github.com/Aurorastation/Aurora.3/assets/17614288/5906c5a2-17f6-4afd-9753-8137f766f5cd)

### How to reproduce

1. Join server
2. join as a cyborg/robot
3. open the inbuilt computer
4. open a program
5. Get annoyed there is no option to close the program

### Round ID

coC-dey6

**Comment by NonQueueingMatt** [comment]
This isn't a bug to do with the cyborg computer but rather the crew manifest program. Fixed already.
