### ISSUE TITLE
[Bug]: Vaurca Hivenet got drained of color

### ISSUE THREAD

**Issue by Butterrobber202** [Aurorastation/Aurora.3#16638]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

tg chat stole Vaurca Hivenet color coding on emotes and chat. K'lax were green, Zo'ra were red, C'thur were blue. Lii'dra were grey.

### How to reproduce

talk in hivenet

**Comment by NonQueueingMatt** [comment]
fixed in next PR
