### ISSUE TITLE
[Bug]: Hardsuit Modules tab closes if you drop an object.

### ISSUE THREAD

**Issue by Rookieeyes** [Aurorastation/Aurora.3#16637]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Searched for Suit, Module, and Hardsuit before posting this. The closest to this issue is the TGUI windows closing randomly, but I think this is still separate. I noticed this issue both with a ninja stealth suit, and a medical hardsuit.

If I drop an item with Q the Hardsuit modules tab disappears if I am wearing a hardsuit. The issue repeated if I drop the item using the 'drop' button. The issue repeats if I use the 'drop-item' verb in the chatbar. The issue repeats both if the hardsuit is toggled, or not. 

Update: Looks like it happens if an object leaves your hand at all. Happened when I transferred something to a bag I was holding in my hand, to a bag on the floor, and putting an ID into a wallet slot. It also happened when I gave the item to someone else.

### How to reproduce

1. Equip a hardsuit
2. Drop an item in your hand using any of the three methods in the description
3. The hardsuit modules tab should disappear.
4. The tab should reappear if you toggle/untoggle the hardsuit.

### Round ID

coD-djXH

**Comment by NonQueueingMatt** [comment]
This is a tricky one.

Somewhere in `verbs_cat_check`, called automatically by remove_verbs, the hardsuit modules tab is removed (presumably because there aren't any verbs in it?) There might be a hacky workaround, but i'll see if I can fix it in a good way.
