### ISSUE TITLE
[Bug]: Upon entering the Crew Manifest, the PDA bricks.

### ISSUE THREAD

**Issue by Stev-the-third** [Aurorastation/Aurora.3#16631]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

The Crew Manifest completely lacks a way to exit out or go back. Removing and replacing the battery from the PDA causes it to permanently brick to the NtOS blue screen. I tried to remove and replace the hard-drive and that did nothing, and refreshing it about 10 to 15 times caused it to stay on the NtOS blue screen.

### How to reproduce

1: Open PDA
2: Enter Crew Manifest

**Comment by NonQueueingMatt** [comment]
fiixed
