### ISSUE TITLE
[Bug]: Tesla causes massive clog overtime

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#16674]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

The source of the recent wave of clog as the round goes on seems to be the tesla, everytime the tesla fires the eletrical arc they never dissipate and instead keep building up and up, it gets to a point the server begins to clog.

During a live round i tested along with other fellow ghosts that if you get closer to the tesla the more it lags, to a point it just switches to 2 fps if you are directly seeing it.

### How to reproduce

Set the tesla, wait
![image](https://github.com/Aurorastation/Aurora.3/assets/51837452/f9f902f4-877b-4983-843f-231306cd580d)

### Round ID

N/A

### Staff ckey

N/A

**Comment by NonQueueingMatt** [comment]
This was not the cause.
