### ISSUE TITLE
[Bug]: Cleanbot remote changes

### ISSUE THREAD

**Issue by Afya212** [Aurorastation/Aurora.3#16682]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

The cleanbot (and possibly other bots) don't seem to have a distance check once you have the controller open you can mess with the settings regardless of distance as long as you have it up.

**Comment by FluffyGhoster** [comment]
This should be solved with the switch to TGUI for cleanbots
Reopen if not
