### ISSUE TITLE
[Bug]: Recycling in the autolathe doesn't delete item, resulting in infinite resource potential

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#16695]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Recycling things like a micro-laser into an autolathe adds the resources to the autolathe but does not delete the item, allowing you to recycle the item again infinitely and thus, infinite steel/glass.

### How to reproduce

1. Use micro-laser on autolathe

### Round ID

coK-ahDF

**Comment by LeiteQualhado** [comment]
Can confirm, in theory you can forever fuel the autolathe with a single microlaser, all you need is patience and endurance.

Although it still takes steel and glass sheet normally deleting them, so the issue seems to be limited to these small devices items for recycling
