### ISSUE TITLE
[Bug]: NutriMax Vendable Sprites Don't Match Vended Items

### ISSUE THREAD

**Issue by Duthco** [Aurorastation/Aurora.3#16698]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Working in the Public Garden, I noticed the sprites for the vendable items listed on the Public Garden's NutriMax, (e.g. Jug Of E-Z Nutrient, Jug Of Left-4-Zed, Jug Of Robust Harvest, Pest-spray, Syringe, and Plant Bag) didn't match the sprites for those items, although the vended item sprites were correct. 

I asked the Botanist in Hydroponics their if this matched what they saw, and they said they were wondering the same thing.

Being there no Xenobotanist on that shift, I could not verify if the NutriMax in Xenobotany was also affected, though I suspect it is likely.

Below are screenshots of the item vendor listings:

![Capture2](https://github.com/Aurorastation/Aurora.3/assets/37712364/a6e89bcc-8662-4f88-bc28-3b900efe203b)
![Capture3](https://github.com/Aurorastation/Aurora.3/assets/37712364/00ac54ae-022a-44d1-89a8-055ff6227820)
![Capture4](https://github.com/Aurorastation/Aurora.3/assets/37712364/8cc0a069-fc71-4d97-b360-d7d60715990c)
![Capture1](https://github.com/Aurorastation/Aurora.3/assets/37712364/cf1c5989-fd9d-42d5-8927-2ec6362a6121)
![Capture5](https://github.com/Aurorastation/Aurora.3/assets/37712364/f295984f-5b68-44d1-aada-24823e908ddf)
![Capture6](https://github.com/Aurorastation/Aurora.3/assets/37712364/7a8b83ba-1bbf-4775-80df-fdc05bef99be)

Then, below is a screenshot of the actual item sprites in the same order (from left to right) as listed above:
![Capture](https://github.com/Aurorastation/Aurora.3/assets/37712364/7bc5978f-6270-4d9d-a213-dc2d96ffceb8)

### How to reproduce

1. Visit any NutriMax vendor.
2. Observe the vendable item sprites.
3. Vend any item and consider the sprite of the vended item against the vendor's listing.

### Round ID

coK-aFYW

**Comment by Duthco** [comment]
Playing in a round a couple days later, it appears the sprites match again.
Round ID: coL-dI3x

I'm not sure if it was fixed, or if the one round my screenshots are from was just an odd one, so I'll wait for someone who knows more to close this if it resolved _naturally_

**Comment by NonQueueingMatt** [comment]
> Playing in a round a couple days later, it appears the sprites match again. Round ID: coL-dI3x
> 
> I'm not sure if it was fixed, or if the one round my screenshots are from was just an odd one, so I'll wait for someone who knows more to close this if it resolved _naturally_

This is generally a clientside cache issue.
