### ISSUE TITLE
Security Camera Console

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#167]
Whenever you open up Security Camera on a Console... It bugs on you then crashes the window... It worked for some people including me. It didn't crash on some people.

**Comment by skull132** [comment]
Define bugs on you?

Also, what BYOND version do you have?

**Comment by UnknownMurders** [comment]
The latest.

**Comment by UnknownMurders** [comment]
Right. I asked Owened to attempt to open up Security Camera. 
https://gyazo.com/175de4265ab73efe1b90b5c3ba6248e9

**Comment by NanakoAC** [comment]
this is a client issue that varies between people. 

i think there's not much we can do until we overhaul the underlying UI system

**Comment by SierraKomodo** [comment]
Is this still something that happens?

**Comment by Bedshaped** [comment]
Closing. Please repost if issue remains persistent.
