### ISSUE TITLE
Antag role selections don't always load properly when loading up a slot/restarting the server

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1670]
The special role selections in the character setup menu don't seem to carry over to the next round when the server restarts, even after selecting 'Save slot'. The selections do seem to stick when switching between slots before a server restart, however.

Other players have mentioned having this issue as well.

**Comment by skull132** [comment]
You're aware that the selection is character specific now, aye?

Meaning, even when saving, it'll only save for that character.

**Comment by SierraKomodo** [comment]
I am aware of that. The slot I have named 'B.C. of F.C.O.' was set to 'Yes' for ninja, wizard, traitor, and borgs and saved. When I logged back on that evening and checked, everything was set to 'No'.

**Comment by SierraKomodo** [comment]
As a note, there's been multiple people reporting this as an issue (Although so far nobody has wanted to actually post on this issue report).

**Comment by AgentWhatever** [comment]
I am also experiencing this bug. Every single time I have to set my antag options, save my character, only to do it again next round.

**Comment by Pratepresidenten** [comment]
Its not only linked to the "thrall" role either. Seems to me that it doesnt matter what antag roles you pick, it will reset from time to time.
Another issue is that you get antag roles that you dont even have enabled.

On another possible related note: Company relation and spawnpoint resets every round aswell.

**Comment by SierraKomodo** [comment]
I've only had traitor selected before and it's reset.

**Comment by AgentWhatever** [comment]
Allright, I figured something out. Its not that the options are not saved, its that they arent loaded in correctly. Theres a button with "reload slot" and voila, anrag options are set as usual again
