### ISSUE TITLE
[Bug]: after the update to the CondiMaster and ChemMaster, condimaster thinks that anything in the placed beaker is empty (it is not). ChemMaster works fine.

### ISSUE THREAD

**Issue by idiotGG** [Aurorastation/Aurora.3#16718]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

There was a revamp of the condimaster and the chemmaster recently. After the update ChemMaster works fine but the condimaster in the kitchen reports the beaker as empty always even though it is not.

### How to reproduce

I've placed the beaker in the condimaster filled with various things a few times and it always says that it is empty.

### Round ID

514325

### Staff ckey

coM-clF4

**Comment by lilahnovi** [comment]
Just doubling up on this with an image. This was an attempt with multiple types of reagents including medications. It just doesn't register anything being in the beaker. However, the ChemMaster works fine, as I had the chemist separate the nutriment from animal protein for me.
![image](https://github.com/Aurorastation/Aurora.3/assets/124811534/b287a6bb-bca7-45e8-be0b-992cdcd2b4df)
