### ISSUE TITLE
[Bug]: General Rev Issues (Mega-Bug Report)

### ISSUE THREAD

**Issue by TMR-SS13** [Aurorastation/Aurora.3#16727]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Revolution appears to be completely broken, apparently, from the round I just played. Issues will be listed below. Anything marked as "Head Revolutionary" can also be assumed to apply to "Head Loyalist".

1. Head Rev gear did not spawn (likely due to overfull bag at start).
2. Head Revolutionary action buttons didn't appear (Invite to Revolutionaries, Set Ambition).
3. Head Revolutionary action buttons did not work when forced by admins, and deleted all other IC action buttons and their uses, such as "say" and "me" and "rest". This was only remedied by cryoing and respawning.
4. Head Revolutionary action buttons did not work post-cryo and respawn fix, despite appearing alongside all other verbs. The menu for "choose who to convert" came up, and was clicked on, but nothing happened on either end re: "You are trying to convert X" or "you are being converted by the revolutionaries, click yes or no". Admins had to manually convert people.
5. Revolutionary icons did not appear to other revolutionaries, including head revs and regular revs. They were simply completely invisible.

Feel free to add more Revolution bugs on here if you notice them.

### How to reproduce

1. Load up server.
2. Fill Loadout to the point that your bag is full at round-start.
3. Play Revolution as Head Rev/Head Loyalist.
4. Try to convert/utilize abilities.

### Staff ckey

Alberyk

**Comment by zagoon** [comment]
Additional info on the icons failing to appear: recruited revs and loyalists do not show up on ghosts' antaghud _period_, including on the follow list.

**Comment by FluffyGhoster** [comment]
Is the issue still present after #16959 was merged?
