### ISSUE TITLE
[Bug]: Datalink constantly severs on Spark

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#16721]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon, Spark

### Describe the issue

The datalink from the Spark to the Horizon constantly severs and reconnects. Saying this message every few seconds.
![image](https://github.com/Aurorastation/Aurora.3/assets/8042031/ff8c6bf8-d366-4e9c-8233-154efc910378)

I have not used the Intrepid or Canary to see if this happens to them too

### How to reproduce

1. Go to Spark

### Round ID

coM-c9fz

**Comment by LeiteQualhado** [comment]
this actually only happens when the Horizon bridge lost power and the sensors turned off, since the sensors are offline the console keeps trying to link with it but can't
