### ISSUE TITLE
[Bug]: Cannot eject documents from fax machines

### ISSUE THREAD

**Issue by Greenjoe12345** [Aurorastation/Aurora.3#16753]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

the TGUI interface for fax machines lacks a button to eject the document put into it, making it impossible to remove the paper after putting it in.

### How to reproduce

Put a paper in the fax machine
open the gui
see a lack of eject button

### Round ID

coP-cEND

**Comment by Doxxmedearly** [comment]
The eject button pops up after you confirm your identity - tested locally. 
Probably should be there by default, though, since it IS impossible if you don't have an ID
