### ISSUE TITLE
A Disgraceful Alberky Typo

### ISSUE THREAD

**Issue by UnknownMurder** [Aurorastation/Aurora.3#1677]
![image](https://cloud.githubusercontent.com/assets/7517616/22442317/88297a5e-e700-11e6-9a00-01ecc93212aa.png)

You can reproduce the typo by heading over to the changelog.

**Comment by Lohikar** [comment]
I'm just going to leave that there just to bug you.

**Comment by Alberyk** [comment]
That is why you don't write changelogs at 4 am

**Comment by skull132** [comment]
Changelog file shouldn't be edited. RIP.
