### ISSUE TITLE
Duty Officers & ERT Officers

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#168]
The Duty Officers and ERT Officers (Or Escort) have Syndicate HUD. 

![image](https://cloud.githubusercontent.com/assets/12143105/13240120/6bb1fa9a-d9a5-11e5-82e0-58756b2f3324.png)

**Comment by Serveris** [comment]
This is likely due to them being registered as antagonists, code wise, to make it easier for modmins to keep a closer eye on them.

**Comment by UnknownMurders** [comment]
I have been told it may be a bug by a staff, so I had went ahead and filed this issue.

**Comment by skull132** [comment]
Not a bug, read what Serveris posted.

Also fixed in one of the pulls by Nanako a few weeks ago.
