### ISSUE TITLE
[Bug]: Vaurca eye slot bug

### ISSUE THREAD

**Issue by Snowy1237** [Aurorastation/Aurora.3#16808]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Items placed in eye slots do not show up on the sprites of Vaurca, nor do they show up on examine or apply any of their effects (flash protection), they only appear in the eye slot itself.

### How to reproduce

1. spawn as vaurca with flash-resistant blinders.
2. blinders invisible on examine and on the sprite.
3. flash yourself, see that flash resistance is not applied.

### Round ID

coO-bEsB, coT-c8ES.

**Comment by crunchypretzels** [comment]
I can't seem to reproduce steps 1 or 2 of this. What species of Vaurca were you playing?

**Comment by meep109** [comment]
@crunchypretzels The same bug happened to me specifically on Vaurca Warriors. I don't think it happens anywhere else

**Comment by Snowy1237** [comment]
> I can't seem to reproduce steps 1 or 2 of this. What species of Vaurca were you playing?

I have been playing a warrior.
