### ISSUE TITLE
[Bug]: YouTool and Engi-Vend in Engineering EVA showing wrong icons?

### ISSUE THREAD

**Issue by hazelrat** [Aurorastation/Aurora.3#16816]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Apologies if this bug has already been reported. Items in the aforementioned vendors in engineering EVA storage very occasionally show the wrong icons. I'm not certain if the icons are consistent, though I have seen the bug once before a few weeks ago, unsure if it was fixed and then something recent broke it again. It's also possible the bug has existed the entire time and it just shows up rarely, not sure.

The items do vend exactly as they should, you can't get items you otherwise couldn't, it's just the icons in the vendor UI that are inaccurate. Do not know if this applies to other similar vendors, or if it's specifically these two.
![image](https://github.com/Aurorastation/Aurora.3/assets/83198434/683e45c4-2714-4f3f-93a8-689cabff7a1c)
![image](https://github.com/Aurorastation/Aurora.3/assets/83198434/46c409cb-e8a9-46f4-a7ca-2c1bd3d2e5ad)

### How to reproduce

1. Open the YouTool and Engi-Vend vendors in Engineering EVA Storage.

### Round ID

coV-alnt

**Comment by NonQueueingMatt** [comment]
Spritesheet cache issue.
