### ISSUE TITLE
[Bug]: Full beaker in sleeper cannot be ejected.

### ISSUE THREAD

**Issue by Kelnor277** [Aurorastation/Aurora.3#16820]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

When a sleeper beaker is full, the prompt changes from "Eject Beaker" to "No Beaker" and the beaker is no longer ejectable.

### How to reproduce

Dialysis until beaker is full.
Observe that you cannot eject beaker now.

**Comment by FluffyGhoster** [comment]
I tried to reproduce this, and was unable to, I filled the beaker almost full with inaprovaline, added a carbon/human to the sleeper, activated dyalisis, waited the free space to say 0 and then some more, pressed eject, and it was ejected successfully
