### ISSUE TITLE
[Bug]: TGUI: Order details get stuck on screen when changing tabs on the cargo control program

### ISSUE THREAD

**Issue by Greenjoe12345** [Aurorastation/Aurora.3#16844]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

When you press details on the cargo control program, the details come up as expected, the issue is they then continue to stay there, on all other tabs.
![image](https://github.com/Aurorastation/Aurora.3/assets/33647525/4f83b3e0-f670-4f24-abfe-dda6b2a62422)
For example, here it is, now at the bottom of the bounties tab

### How to reproduce

Place an order at cargo
go to the cargo control program
press details on that order
change tabs on the program

### Round ID

Seen it in multiple rounds.

**Comment by NonQueueingMatt** [comment]
This is intentional behaviour.
