### ISSUE TITLE
[Bug]: (IPC) You cannot drink with a tongue gustatorial

### ISSUE THREAD

**Issue by dessysalta** [Aurorastation/Aurora.3#16843]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Tried to drink from a glass as an IPC. Said I have no mouth, despite being a shell IPC with a tongue gustatorial centre.

### How to reproduce

1. Make or find drink as a shell IPC with a gustatorial centre (tongue).
2. Attempt to drink.
3. "Where do you intend to put the glass of whiskey? You don't have a mouth!"
4. Cry, decide to emote it out instead.

### Round ID

coV-c1yI

### Staff ckey

campinkiller

**Comment by crunchypretzels** [comment]
To use the tongue, use the ability in the top-left corner of the screen to set your taste sensitivity or to drink.

**Comment by dessysalta** [comment]
To the surprise of no one, I am an idiot. (joking lmao)
Closing this.
