### ISSUE TITLE
[Bug]: Diona limbs can't be re-attached.

### ISSUE THREAD

**Issue by Stev-the-third** [Aurorastation/Aurora.3#16852]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] The round I am reporting the bug from, or I am going to talk about, has already ended.

### Location

Horizon

### Describe the issue

Diona limbs, as removed by Unathi or Skrell (I haven't confirmed on Diona themselves yet), can be removed with the verb but then not re-attached in any way I can see. I might just be blind and not know how to re-attach them though.

### How to reproduce

1: Spawn as a Unathi or Skrell with a diona limb
2: Remove it using the verb in Abilities
3: Realise you can't re-attach it.
4: Cry.

**Comment by Doxxmedearly** [comment]
Right click the nymph and attach.
