### ISSUE TITLE
[Bug]: Uniform overlays on top of rescue hardsuit sprite

### ISSUE THREAD

**Issue by Bamboogled** [Aurorastation/Aurora.3#16872]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Whatever is in your uniform slot will overlay over the rescue hardsuit. I haven't tested this with other hardsuits and I've only seen the pants overlay.

https://i.imgur.com/qmnK7LG.png

### How to reproduce

1. Wear something in the uniform slot.
2. Put on rescue hardsuit.

### Round ID

coX-dC2E

### Staff ckey

N/A

**Comment by dessysalta** [comment]
Confirmed just a couple days ago, this also happens with things like the Breacher suit and some/most other hardsuits you can't normally make on-ship. Weird thing about it is it can sometimes be fixed (i.e. in our Starship Troopers event recently, wearing sec gear disabled the bug) but apparently not every ship-bound piece of clothing fixes it? And it's specifically attached to the chest of the hardsuit, meaning if you retract the chest, it won't overlay the leg portion of the outfit.

**Comment by FluffyGhoster** [comment]
This should be fixed now
