### ISSUE TITLE
[Bug]: Remote controled Mech and Hardsuit issues

### ISSUE THREAD

**Issue by ARandoDude1337** [Aurorastation/Aurora.3#16881]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

So another round playing as Danny Brovano. And i make my mech (as i do) and eventually put on an EVA Suit and hop onto my remote controlled mech center. I pair my mech with the centre. and start piloting it. 

First issue is the mech's movement. No matter what i try IC Tab or keybinds even with hover thrusters im unable to move up or down between levels at my leisure.

Second Issue. When remotely piloting a mech and you have a hardsuits (on or off i tested) it removes the hardsuit tab and i cant access augments and it wont come back unless your reconnect the game. (Not a deal breaker but certainly annoying.)

### How to reproduce

1.Build a mech (preferably with Hover thrusters)
2.Get a remote control centre kit and a Exo Remote Control link.
3.Pair it to the Exo.
4.Try to move up and down. and even though you have thrusters it says "You lack the means to do so"

Hardsuit issue.
1. build a remotely controlled mech
2. equip a hardsuit (havent tried if it being passibely on solves the issue without toggling it but mines was toggled on)
3. Pilot the remote mech. (you should see hardsuit tab go away. makes sense)
4. Exit the mech remote piloting (Hardsuit tab doesn't show back up)

### Round ID

coY-dxVD

**Comment by Fyshen** [comment]
If this ever gets fixed, I'd like to add - using the remote controlling station also removes the ability to use the top left hot buttons afaik - in my case, losing access to my retractable combitool.
