### ISSUE TITLE
[Bug]: AI cannot configure APCs

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#16880]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

I am unable to change the equipment/lighting/environment modes in any APC.

![image](https://github.com/Aurorastation/Aurora.3/assets/8639807/2b06fa59-c28b-4a5e-bed9-ca65ccd48d18)

### How to reproduce

Play AI.
Use an APC

### Round ID

coY-dav1

**Comment by Fyshen** [comment]
I was about to report this same bug - I've had it consistantly for a few days now.
