### ISSUE TITLE
[Bug]: PAI Bug for Software System (Medical hud)

### ISSUE THREAD

**Issue by ARandoDude1337** [Aurorastation/Aurora.3#16908]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When joining as a PAI. i downloaded a few systems as you do and opened the Medi Hud because i was with a paramedic. I selected it and nothing happened so i tried to exit out. But i couldnt exit out of that tab. Thusly i can no longer access anything computer wise. Which is pretty bad.

### How to reproduce

Become PAI
Download Medical Hud
Open Medical Hud
Get stuck in the medi hud.

I reconnected, Quit out and rejoined, And cleared cache and rejoined 

### Round ID

co3-acyf

**Comment by Trusty-Mccoolguy** [comment]
This has in fact been reported. It isn't restricted to the medical hub.
There are two 'categories' of programs. Any programs that show up in the secondary portion (such as your universal translator and medical/security hud and flashlight), will also have a duplicate in the first category. If you try to open them there, you open a bugged, false version, and it will brick your pAI system.
