### ISSUE TITLE
[Bug]: Security records show no charges

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#16935]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Even if you charge someone the charges won't appear on  security records, nor do canonical charges

### How to reproduce

charge someone with something and see if it appears on records

### Round ID

N/A

### Staff ckey

N/A

**Comment by FluffyGhoster** [comment]
The new TGUI port of the program should have fixed this, if not, feel free to reopen
