### ISSUE TITLE
Engineering Borgs Can't Make Reinforced Floors With Metal Rod Synthesizer

### ISSUE THREAD

**Issue by Surrealistik** [Aurorastation/Aurora.3#1694]
Per title.

**Comment by Pratepresidenten** [comment]
You need to pry the tile away before applying the rod synthesizer to the plating, and on a related note, I dont think the "Reinforcing floor" text is displayed whenever you try to reinforce it.

**Comment by Surrealistik** [comment]
Yes, I am applying the rods to the subfloor.

If you're saying that notification/confirmation of reinforcing the floor doesn't happen for some reason (which would also be a bug) that could also be the problem.

**Comment by Geevies** [comment]
Fixed.
