### ISSUE TITLE
[Bug]: Psionics break people

### ISSUE THREAD

**Issue by StarDust7767** [Aurorastation/Aurora.3#16962]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

So during round co5-c6LW I asked Xim to do some psionics on my character. He said sure and then did some kind of chest crushing motion, and the logs of the attack said this.
Xim'Eq Lixuq extends their arm and makes a grab motion towards Lalu Deimos!
You feel an invisible force tighten around you!

After this, for some reason I was unable to look around with arrow keys, click to look around, nothing worked, I checked if I had accidentally locked myself in place, I hadn't. I relogged to see if something is broke. Nothing. The only way for my character to look around was by physically moving in that direction. 

Xim used then another power, some kind of Ion blast that suddenly caused this issue to another player afterwards who reported the same problem I'm having, but only after a psionic power was used on them.

The only way as of right now is to ghost and respawn as a new character, that seems to reverse the effects of the bug.

### How to reproduce

Have a skrell use a non-standard power on someone, or maybe even a standard one. I'm not exactly sure. Use some kind of offensive psionic power on someone and try to look around.

### Round ID

co5-c6LW

**Comment by NonQueueingMatt** [comment]
You were hit by Stasis which... does what it says on the tin. It immobilises you.
