### ISSUE TITLE
[Bug]: Psionics: Using stasis on yourself freezes you and doesn't allow you to unfreeze yourself.

### ISSUE THREAD

**Issue by sadkermit** [Aurorastation/Aurora.3#16964]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

If you use stasis on yourself, you are unable to move. Clicking yourself says 'They are already in stasis' (or something to that effect) with no options to release from stasis. 

I might just not be aware of the correct way to unstasis someone/yourself, but I tried what I could before getting another skrell to unstasis me.

### How to reproduce

Use stasis on yourself.

### Round ID

co5-c6LW

### Staff ckey

arrow768

**Comment by NonQueueingMatt** [comment]
The correct way to unstasis someone is to drop the spell, but I'm not sure if you can do that while stasis'd.
