### ISSUE TITLE
[Bug]: Psionics visual bug

### ISSUE THREAD

**Issue by lilahnovi** [Aurorastation/Aurora.3#16963]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

I just witnessed this visually. Nobody around is using psionics, but I'm selecting over it and it shows up as 'stasis' on the bottom bar.
![image](https://github.com/Aurorastation/Aurora.3/assets/124811534/2645f693-9a3f-4b06-b57f-0617b1bde240)
 
![image](https://github.com/Aurorastation/Aurora.3/assets/124811534/f0eb725d-4c4f-4c89-a4f9-058799132d5c)

**Comment by sadkermit** [comment]
not just a visual bug. It can be picked up and used by anyone lmao

**Comment by NonQueueingMatt** [comment]
Some odd behaviour might cause a spell to not self-delete when dropped.
