### ISSUE TITLE
[Bug]: Psionics: buying abilities does not deduct points

### ISSUE THREAD

**Issue by sadkermit** [Aurorastation/Aurora.3#16965]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Buying points from the pointmenu does not deduct from your 8 points. Right now, you can buy every ability.

### How to reproduce

Buy psionics from the pointshop.

### Round ID

co5-c6LW

**Comment by NonQueueingMatt** [comment]
How did I miss this
