### ISSUE TITLE
[Bug]: Unable to target some effects/overlays

### ISSUE THREAD

**Issue by sadkermit** [Aurorastation/Aurora.3#16971]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The Bridge was unable to use the targetting console to target hazards. You are able to open the overmap using the targetting console, however clicking any entities on the overmap yields no feedback. 

**Update:** this extends to greimorian larvae, ash piles, cobwebs, and similar effects/overlays/decals, which the entities on the overmap also count as.

### How to reproduce

Try to target an overmap entity using the targetting system console.
Try to squish a greimorian larvae.
Try to sift your hands through a pile of ash.
Try to break cobwebs.

### Round ID

co5-dsXH

**Comment by Melariara** [comment]
Gonna delete mine and throw the info from it in here. 

![image](https://github.com/Aurorastation/Aurora.3/assets/60306280/5dca52b5-81d0-4980-a8bd-e0afe786d949)

![image](https://github.com/Aurorastation/Aurora.3/assets/60306280/6ac2ab0b-589c-41a2-acb7-bf4609088235)
