### ISSUE TITLE
[Bug]: Psionic Crush has seemingly unlimited range

### ISSUE THREAD

**Issue by CometBlaze** [Aurorastation/Aurora.3#16993]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Psionic was inside the FR's room when he used crush on me, while I was standing in medical reception. I ran all the way to the front of the dining hall and continued being crushed. Another incident involved him using crush while inside operations and I continuing to be crushed all the way at the medbay's reception.

### How to reproduce

1. Get crushed
2. Try to run away

### Round ID

co7-bDD8

**Comment by Doxxmedearly** [comment]
Probably due to the spell only needing a clear line to the target with `get_line()` and not also checking range.
