### ISSUE TITLE
[Bug]: Tajara Industrial Hardsuit Sprite Issue

### ISSUE THREAD

**Issue by LynxSolstice** [Aurorastation/Aurora.3#17000]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/112824777/5ab5f329-4b62-418f-a83f-ecad6320901a)

The suit has text that shows up on the sprite.

### How to reproduce

Be a Tajara
redeem ore
get points
buy hardsuit
wear it
sprite issue

**Comment by FluffyGhoster** [comment]
This should be fixed now, in https://github.com/Aurorastation/Aurora.3/pull/17125 , can you check and confirm?
