### ISSUE TITLE
[Bug]: Incorrect air supply piping in deck one science

### ISSUE THREAD

**Issue by hazelrat** [Aurorastation/Aurora.3#17009]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

There seems to be a bent pipe in deck one science where there should be a manifold, so it doesn't actually connect to the adjacent vent. Noticed it while venting the chamber last round, replaced it with a manifold to get it functional.
![image](https://github.com/Aurorastation/Aurora.3/assets/83198434/de3d49a0-968e-4f42-8554-308fb188d9cc)
![image](https://github.com/Aurorastation/Aurora.3/assets/83198434/dab8b4c0-a451-4eef-96d2-55e5116c15f5)

### How to reproduce

1. Head to deck one xenoarchaeology and lever off the tiles adjacent to the vent by the entrance to the firing range.

**Comment by Nalarac** [comment]
I believe this will be fixed in #16934.

**Comment by lavillastrangiato** [comment]
pls close this as it's a fixed issue
