### ISSUE TITLE
[Bug]: Incorrect disposals section near Holodeck beta.

### ISSUE THREAD

**Issue by Stev-the-third** [Aurorastation/Aurora.3#17007]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/61610777/d53b9cce-f779-4851-9fbd-dde35c3b4c33)

The disposals pipe leading out of the door to Holodeck Beta is a corner, instead of a manifold.

**Comment by FluffyGhoster** [comment]
Is this still an issue? For what I have seen with a quick glance at the map, it seems to be the correct type of disposal currently (?)
