### ISSUE TITLE
[Bug]: Server crash after opening airlock with jackal inside

### ISSUE THREAD

**Issue by Estutes** [Aurorastation/Aurora.3#17016]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/69876530/a21c89ac-ece8-4a39-8703-90c27ff1e813)
Okay so I walked into the airlcok after shooting the jackal, the jackal was in some sort of attack window loop, something that I've seen sometimes mobs do, of attacking the window for some reason, maybe there was a carp outside my view area. It was after I opened the airlock and walked into the airlock cell, the game froze. The jackal did not have time to react visibly before crashing

Worth noting that during the round and according to talks in general chat of discord, people were saying that insane ammounts of mining took place, due to the usage of some OP power cell and long hours of work.

### How to reproduce

Probably opening the airlock and the jackal pathfinding towards my character

### Round ID

co9-bgmM

**Comment by SleepyGemmy** [comment]
probably caused by #17016.
