### ISSUE TITLE
[Bug]: No id's or access for tajaran smugglres

### ISSUE THREAD

**Issue by Shajoisafrog** [Aurorastation/Aurora.3#17028]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

Tajaran smugglers spawn with no id's so they can't operate airlocks, air alarms, etc on the ship.

### How to reproduce

1. pick tajaran smuggler from ghost spawns
2. select crew
3. profit?

**Comment by LynxSolstice** [comment]
#16899 is caused by this issue.
