### ISSUE TITLE
[Bug]: Operations lift can't move after going to first deck

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#17026]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

After moving the Operations lift to the first deck, it was no longer able to move to the second or third decks. There were floor tiles in the lift area on the second deck, but removing them didn't allow the lift to move up.

### How to reproduce

1. Move Operations lift to deck 1
2. Try to move the lift back up

### Staff ckey

MattAtlas

**Comment by FluffyGhoster** [comment]
An attempted fix of the elevator was deployed with PR #17053 , is this issue still occurring now?

**Comment by Nalarac** [comment]
This issue has been fixed.
