### ISSUE TITLE
Using Needle on Harm Intent as Medical Borg Removes Needle Tool Forever

### ISSUE THREAD

**Issue by Surrealistik** [Aurorastation/Aurora.3#1703]
Per title.

When you use the needle on harm intent and it breaks as a result, the needle tool is gone until being module reset; not even refreshing the inventory, recharging, repairing the cyborg, or rejoining the game will bring it back.

On Paradise this has been fixed such that using a borg recharge station will restore the needle.

**Comment by SebkillerDK** [comment]
I have had this happen a couple of times to me aswell while i was playing as a borg.
