### ISSUE TITLE
[Bug]:  pAI issues compilation [Softlock + other errors: !!Read before submitting your own pAI bug!! broken interfaces]

### ISSUE THREAD

**Issue by Trusty-Mccoolguy** [Aurorastation/Aurora.3#17064]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.
- [X] I have done all that I can on my end to try to resolve these issues including working with my cache, etc.
- [X] I can confirm this is a long term and consistent issue.
- [X] I can confirm that multiple people have experienced such issues.

### Location

Horizon

### Describe the issue

I will be including my main three bugs here which have not been reported as well as another bug that I noticed and was going to report myself, but other folks have been multi-reporting - hopefully this keyword search will keep folks from being able to miss the previous posts including this one. pAI softlock broken computer interface. There.
‏‏‎ ‎
‏‏‎ ‎
‏‏‎ ‎
Issue 1. 
**When becoming a pAI, it does not automatically update out of ghost mode** and seems to believe that I am still a ghost.

Steps to reproduce:
1. Submit pAI personality
2. Get accepted as pAI personality

Tada! You are now a ghost that registers as a pAI.

3. Reconnect, to update your tabs so that you have pAI functionality. 
4. Get added to a local computer such as a PDA or wristbound.
5. attempt to open local computer.

Temporary workaround and problems with it:
I can try to reconnect, and that usually updates the tabs to include pAI tabs, but this unfortunately keeps me from being able to use any local computer system. When trying to do so, it is broken and refuses to open without any error messages.
‏‏‎ ‎‎
‎‏‏‎ ‎![ghost pai](https://github.com/Aurorastation/Aurora.3/assets/20867711/0e645a03-980d-4b65-973c-d24dd9dda598)
‎‏‏‎ ‎
Issue 2. 
**When using a pAI computer interface, if I am disconnected, I fail to be able to open my computer interface again**. It is broken and refuses to open without any error messages sent. (This does not refer to local computer such as a PDA - I cannot in any way access those anyway, see Issue 1).

Steps to reproduce:
1. Submit pAI personality
2. Get accepted as pAI personality
6. Open computer interface, use it
7. Crash / disconnect. Sometimes the bug happens if the computer interface is open, sometimes when it is closed too, but more often when it's still open on disconnect/crash.
8. Reconnect and attempt to open interface.

There is no workaround for this. Attempting to refresh tgui, reconnect again, etc, nothing works.

‎‏‏‎ ‎
‎‏‏‎ ‎
Issue 3:

Previously, I was able to access various radio types as a pAI. I can no longer do this. Attempting to speak on the Security channel to assist my user does not work and simply turns the message into a simple say. It is frustrating as there is information I need to report occasionally that I cannot do privately to security as a result of this. However, I am still capable of hearing Security chatter, as my user is a security officer. This is rough.
‎‏‏‎ ‎
‎‏‏‎ ‎
‎‏‏‎ ‎
Issue 4: 
**When using a pAI computer interface, duplicate entries of certain downloaded software will appear** in the top half of the software list, while also appearing in the bottom category for software at the same time. **Clicking on any of these 'trap' duplicates in the top half of the software list will softlock the computer interface completely**. The entries for these softwares that show up in the bottom still work. Software that doesn't have a duplicate but appears in the top (such as doorjack) is still functional.

Steps to reproduce:
1. Submit pAI personality
2. Get accepted as pAI personality
4. Open computer interface
6. Download, for instance, security/medical HUD
7. Notice the two entries for them, one above and one below the separation of software types
8. Click on the duplicated program above the separation of software programs
9. You are now softlocked

There is no workaround for this. Attempting to refresh tgui, reconnect, etc, nothing works. This is the issue that has been reported multiple times, my main goal is to simply report the additional bugs I've experienced, and help organize the multiple pAI bugs I've experienced and potentially help make it harder for folks to unintentionally miss the fact that they've already been reported.
‏‏‎ ‎
‏‏‎ ‎![pai softlock options](https://github.com/Aurorastation/Aurora.3/assets/20867711/2dd46a87-f909-43fe-ac86-2b6032ec4db0)
‏‏‎ 
The red-outlined options here are traps that will softlock my pAI computer interface.‎

### Round ID

Every round I've been in in the last two weeks.

**Comment by AlaunusLux** [comment]
Issue 1: Fixed. pAI now have the ghost tab removed, and proper verbs added without having to relog. pAI can now access PDA and Computers they are inserted into. 

Issue 2: Fixed, and fixed for the local computer UI too.

Issue 3: Unsure if this changed since the post, but an encryption key needs to be inserted into the pAI - it can be taken from spare headsets usually found in lockers.

Issue 4: Those items that take you to the soft locking page are now hidden from the Programs list. The error page has also been updated to have the normal buttons to close the in-UI window, should anyone somehow make their way there.
