### ISSUE TITLE
[Bug]: Body scanner gives wrong body temperature

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#17068]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Repeat of #16600. This bug still exists.

**Comment by Doxxmedearly** [comment]
It PR referenced is still open and awaiting merge. Please do not make duplicate issues.

**Comment by FluffyGhoster** [comment]
Closing as duplicate
