### ISSUE TITLE
[Bug]: Transfer votes not showing up in chat when initiated

### ISSUE THREAD

**Issue by scheveningensun** [Aurorastation/Aurora.3#17071]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

As title says, the vote initiates when started, (you can type Vote to bring up the vote and thus cast your vote) but does not notify the entire lobby that the round is being voted by so-called democracy to either end or continue the round. The only people notified are those who have the vote sound effect turned on - though local insectoid forklift player Herpetophilia claims they saw it both times in chat on their side, however, and clearly the rest of the lobby (myself included) did not see the purple text to vote to crew transfer, as the following crew transfer vote to resolve the issue was something close to 17-2 or so.

Someone claimed for this round that it didn't initialize 100% correctly either but I'm not sure of the truth of that.

### Round ID

cpi-aGpe

### Staff ckey

Roostercat

**Comment by FluffyGhoster** [comment]
Has this issue happened again? Byond is notorious to sometimes eat chat messages, the round might not have initialized correctly, and I see the vote being correctly announced in my experience
