### ISSUE TITLE
[Bug]: Technomancer Apprentice Core starts with maximum instability

### ISSUE THREAD

**Issue by Icedcabbage** [Aurorastation/Aurora.3#17085]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Upon activating the Apprentice Bluespace crystal, the bracelet that spawns has maximum instability that does not go away, usually leading to death.

### How to reproduce

1.  Active the Apprentice Core Crystal in hand (for me it spawned a bracelet)
2. Look at Status tab, it will have the core at maximum instability

### Round ID

cpj-aQh7

**Comment by FluffyGhoster** [comment]
Are you sure you did not got equipped with the unstable technomancer core (`/obj/item/technomancer_core/unstable`)?

**Comment by Icedcabbage** [comment]
I'm not certain, though I do remember it went into the wrist slot.
