### ISSUE TITLE
[Bug]: Butterfly hairpin has no mob icon in ear slot

### ISSUE THREAD

**Issue by listerla** [Aurorastation/Aurora.3#17095]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When you wear the butterfly hairpin (and possibly others - not yet tested) in the ear slot (which they can be placed in) the icon does not show up on your mob. The hair bow, contrarily, works just fine.

![image](https://github.com/Aurorastation/Aurora.3/assets/57296132/2cbb1ce2-5080-4a37-9d6a-abf357932343)
![image](https://github.com/Aurorastation/Aurora.3/assets/57296132/b4b08037-f669-41b9-a118-0af4066366e5)

### Round ID

cpk-akhH

**Comment by Doxxmedearly** [comment]
Can confirm this happens with the Dainshu feather, so it is probably an issue with all hairpins
