### ISSUE TITLE
[Bug]: Headrevs still cant invite people

### ISSUE THREAD

**Issue by UltraBigRat** [Aurorastation/Aurora.3#17115]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

While this bug has been reported the issue had been closed when a fix pr was merged 3 weeks ago #16959 , however yesterday it was still broken and I was told to open a report. 

Headrevs have no verb to convert others with right clicking showing nothing new and seemingly no other new verbs. The round resulted with admins having to manually  convert people.

### How to reproduce

1. Be headrev
2. Realize you cant convert anyone
3. Admins have to manually  set the status of everyone you convince.

### Round ID

cpm-c2m6

### Staff ckey

There were several admins on at the time who saw this, however I don't remember who they were.

**Comment by NonQueueingMatt** [comment]
Can't replicate.
![immagine](https://github.com/Aurorastation/Aurora.3/assets/13016572/d6601858-f1ce-4ceb-8025-92abf56ffaca)

**Comment by FluffyGhoster** [comment]
Closing as stale, reopen if it's still reproducible
