### ISSUE TITLE
Players are able to join in to replace a carded AI who is inactive or stored themselves.

### ISSUE THREAD

**Issue by Chada-1** [Aurorastation/Aurora.3#1713]
As said in the title, I think it might be possible to store yourself or log out as a carded AI, and then have another person (Or yourself, if you want to test it) join in as the carded AI. It doesn't remove the name of the old AI, despite the fact that if you do or say anything it uses your name for the action. 

This is a hilarious quote from an AI joining in as the Intellicard sitting on the Captains shelf.

http://puu.sh/tNzYI/67551e766a.png

Not sure if a coder is able to do this kinda thing, but if you are, the game ID was bMS-aCmI

**Comment by SierraKomodo** [comment]
In this case it was because the AI wipe-core'd itself (It was me.)

**Comment by JohnWildkins** [comment]
Fixed by #6411 and #10470
