### ISSUE TITLE
[Bug]: Crowbaring off then placing down full floor tiles places small ones instead.

### ISSUE THREAD

**Issue by Stev-the-third** [Aurorastation/Aurora.3#17149]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

If you crowbar up a full steel floor tile (Untested for other times), placing it back down cuases it to be the smaller 4 tiles.

**Comment by SleepyGemmy** [comment]
duplicate of #14658. please search before creating an issue.
