### ISSUE TITLE
[Bug]: The event controller is fucking wack and rolling imbalanced events

### ISSUE THREAD

**Issue by scheveningensun** [Aurorastation/Aurora.3#17166]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Major events can spawn in 18 minutes into the round. That means Hivebots can spawn into awful locations at nearly roundstart. This is bad for a server that focuses on roleplay over mechanically griefing people roundstart.

**Comment by FluffyGhoster** [comment]
It's been months that I've not seen it happen, so this seems fixed
Reopen if not
