### ISSUE TITLE
Missing Underwear Option Choice upon Creation of a New Character

### ISSUE THREAD

**Issue by UnknownMurder** [Aurorastation/Aurora.3#1718]
![image](https://cloud.githubusercontent.com/assets/7517616/22627237/b086c6c2-eb84-11e6-9f47-ddaff8acb581.png)

Title says all.

**Comment by UnknownMurder** [comment]
Note: If you keep making your character through, you'll see that the option somehow randomly appear.

**Comment by SierraKomodo** [comment]
It has to do with whatever underwear item is selected and your character's gender. Alot of underwear options are locked to a specific gender; Changing your gender should make the option appear again.

**Comment by skull132** [comment]
Fixed in #2992
