### ISSUE TITLE
Restocking vending machines can replicate items inside box/storage

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#1719]
Restocking items with boxes, like donuts or any box that spawns filled, even if empty, will fill said box with the original contents when dispensed again.

Example:
Stuff empty donut box inside sec vending machine.
Dispense donut box.
Donut box is full, even if the one you restocked was empty

**Comment by HunterRS** [comment]
I think it dispenses the full on first, try dispensing all of them, it does the same with chemmaster if you put a lower bottle, the bigger ones will come out first.

**Comment by Geevies** [comment]
Fixed.
