### ISSUE TITLE
[Bug]: Invisible wall on xenoarcheology

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#17196]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

There is a invisible wall located here.
![invisible wall](https://github.com/Aurorastation/Aurora.3/assets/51837452/26bdc7a8-cb4a-43eb-a827-541ce78b2ab2)
It splits the path requiring to go north or south of the hallway to go trough it

### How to reproduce

Simply try to go past the area show in the picture

### Round ID

N/A

### Staff ckey

N/A

**Comment by nauticall** [comment]
Outdated server. Will be fixed by #17195 in the next round. ^^
