### ISSUE TITLE
IPC health monitor on HUD does not work

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#172]
The health monitor on the HUD for the player does not reflect character's health if an IPC. In fact, it doesn't work at all, and no matter how damaged you are, it'll never change.

**Comment by CakeIsOssim** [comment]
I have just been informed that it's actually a pain indicator, not true health. So, this likely isn't a bug.

**Comment by skull132** [comment]
Yup, pretty much. Same thing applies to Diona, who also have `NO_PAIN` in their list of flags.
