### ISSUE TITLE
[Bug]: AI gets killed by Leviathan firing

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#17211]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

During round the Leviathan was charged up and fired. As I was anxiously panning over (as AI) to watch it fire, I suddenly die, and return to see my core have been violently thrown out of its place. Sadly the admin/captain couldn't return me to life at the time.

![image](https://github.com/Aurorastation/Aurora.3/assets/8639807/71c27872-21e7-4ebc-8153-c238c2d5310a)

This is how it looked afterwards. I haven't experienced the event enough to say whether this is a consistent reaction or random.

### How to reproduce

1. Play AI
2. Have the captain fire the Levi

### Round ID

cpz-dx4H

### Staff ckey

ReadThisNamePlz

**Comment by SleepyGemmy** [comment]
was the gravgen disabled?

**Comment by NerdyVampire** [comment]
> was the gravgen disabled?

Unfortunately I don't recall. I remember the gravity failed some time in the round, but whether it coincided I can't say. But the core ought to be wrenched down and immovable?

**Comment by SleepyGemmy** [comment]
> [...] But the core ought to be wrenched down and immovable?

yeah, it is anchored and *should* be immovable.
gravgen being enabled prevents mobs from being thrown (as added in #15254) but i don't think the issue where anchored mobs are thrown if its disabled was ever fixed.
honestly would probably just be as easy of a fix as to add a anchored check to the code in the PR i linked, for anyone who reads this comment.

**Comment by SleepyGemmy** [comment]
could replicate this with the gravgen being disabled.
