### ISSUE TITLE
[Bug]: Funky wall texture on deck 3 holodeck 2

### ISSUE THREAD

**Issue by ARandoDude1337** [Aurorastation/Aurora.3#17214]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Was walking around the horizon and noticed that this wall in particular was funky.

### How to reproduce

1. Get on the horizon
2. profit?

### Round ID

cpA-cskW

**Comment by ARandoDude1337** [comment]
![Funky wall](https://github.com/Aurorastation/Aurora.3/assets/132208064/0c2f9380-c676-4991-989f-85ffc672cb63)

**Comment by SleepyGemmy** [comment]
seems like its trying to smooth to the emergency shutter. i assume it doesn't have a sprite for that.
