### ISSUE TITLE
Ruptured lung with working internals

### ISSUE THREAD

**Issue by Faryaa** [Aurorastation/Aurora.3#1721]
Went to EVA with intact hardsuit and emergency airtank like a real EVA boss. Got ruptured lungs for no appearent reason.

Airtank was filled to full before that. Pressure is optimal. Tank were not empty from sudden.
Tank was stored in the pocket.

**Comment by skull132** [comment]
Was your tank release pressure set to below 21 kPa?

**Comment by Faryaa** [comment]
It was 17 kPa which is standart set up for anyone who spacewalk alot. Its minimum needed to provide air. I later changed it up to 30 kPa after rejuv from admin but I got new lung rupture with that.

**Comment by Alberyk** [comment]
Don't go under 21 kpa, bay merged changed it.

**Comment by Faryaa** [comment]
So thats just bay thing with minimum pressure is 21 kpa? Well, no issue with that then.
