### ISSUE TITLE
Chat Log Doesn't Clear Automatically

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#17254]
the chat log should probably clear after each round or when leaving and rejoining, as it used to work before.
would probably be preferable as an option to toggle.

**Comment by DreamySkrell** [comment]
I think it's fine as it is. If for whatever reason you lose connection, you get to keep the chat and know where you left off.
Also nice for saving logs, where you don't lose them if you forget to save before round ends.

It should definitely be a toggle.

**Comment by NonQueueingMatt** [comment]
It shouldn't.
