### ISSUE TITLE
[Bug]: Autoinjectors can't be secured

### ISSUE THREAD

**Issue by lavillastrangiato** [Aurorastation/Aurora.3#17288]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

To secure an autoinjector that has been filled with a reagent, you need to click on it while in hand. To open it to refill it after it's spent, you need to open it with a screwdriver.

I cannot secure an autoinjector once filled with reagents. Other players have informed me they also cannot secure it.

### How to reproduce

1. Pick up empty autoinjector
2. Fill with reagent
3. Click on autoinjector in-hand
4. Be unable to secure it

Alternatively;
1. Expend autoinjector
2. Open with screwdriver
3. Refill with reagent
4. Click on autoinjector in-hand
5. Be unable to secure it

**Comment by FluffyGhoster** [comment]
User error, the securing was changed to ALT+Click, not simple hand activation anymore
