### ISSUE TITLE
[Bug]: Shoes (specifically boots?) fly off when people lay down.

### ISSUE THREAD

**Issue by lilahnovi** [Aurorastation/Aurora.3#17293]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Looks like shoes are also all messed up, and when somebody lays down, the sprite for shoes goes flying. Boots in particular, not sure about other shoes. Sofia did not lose her chucks during the previous round.

![image](https://github.com/Aurorastation/Aurora.3/assets/124811534/8dc4bc7f-b8a4-49ad-814e-69f0f5a9d682)

**Comment by alsoandanswer** [comment]
Fixed
