### ISSUE TITLE
[Bug]: Tactical lay down is broken

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#17310]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

You are able to do a tactical laydown by middle mouse clicking the walk icon, but once you lay you will be unable to get up unless a admin rejuvenates you

### How to reproduce

Middle click the walk button to use the tactical laydown and then attempt to get up by middle clicking it again or trying something else

### Round ID

 cpJ-cjQo

### Staff ckey

N/A

**Comment by FluffyGhoster** [comment]
Unable to reproduce:

1. Spawned on local instance with the latest code as human
2. Middle clicked the movement intent icon, laid down
3. Middle clicked again, got up

https://i.imgur.com/yu6NmUZ.gif

**Comment by LeiteQualhado** [comment]
> Unable to reproduce:
> 
> 1. Spawned on local instance with the latest code as human
> 2. Middle clicked the movement intent icon, laid down
> 3. Middle clicked again, got up
> 
> https://i.imgur.com/yu6NmUZ.gif

Perhaps it was patched by something, Yonimer had to rejuvenate me for me to be able to get up, regardless i will close the issue and if it does happen again re-open it after investigating more
