### ISSUE TITLE
[Bug]: Broken Xeno Footwear from #16265 test merge

### ISSUE THREAD

**Issue by VeteranGary** [Aurorastation/Aurora.3#17324]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Under the tajara xenowear, both versions of the jackboots do not work as well as the adhomian boots. Using them gives a bugged item that cannot be worn by tajara. Other boots such as the workboots work fine, for whatever reason.

https://i.gyazo.com/b1ec451db5b45bcd0e1c5d8a4936574d.png

### How to reproduce

1. Select footwear under Xenowear - Tajara.
2. Does not appear on preview.
3. Gives default footwear and places broken footwear in bag on spawn.

**Comment by Greenjoe12345** [comment]
This also applies to the tajara dress flats, and possibly some types of human jackboots, too, the ones the TCFL use seemed to be missing icons too.
