### ISSUE TITLE
[Bug]: Me/Visible emotes are broken

### ISSUE THREAD

**Issue by Spookat** [Aurorastation/Aurora.3#17335]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/99222453/ff89cc5b-a550-4ec2-845f-562dfb758d18)

Me no longer works.

### How to reproduce

1. Use your usual macro or command to emote.

### Round ID

cpM-c2m6

**Comment by FluffyGhoster** [comment]
Fixed in latest commit of the testmerged PR
