### ISSUE TITLE
[Bug]: emoting with /me is broken

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#17341]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Using /me to emote in any way is broken since yesterday. The only way to emote is using say "!emotehere."

### How to reproduce

1. join
2. press whatever you have bound to open /me text box or use the command bar and type me
3. type your emote
4. get error message of "unkown emote 'me'".

### Round ID

cpN-c5f7

**Comment by FluffyGhoster** [comment]
Resolved already, the server was just not live with the fixed code yet
