### ISSUE TITLE
[Bug]: No suit cycler on the free booter ship

### ISSUE THREAD

**Issue by LynxSolstice** [Aurorastation/Aurora.3#17357]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/112824777/b171a030-99c8-4b57-82f5-e721ce9a544d)

**Comment by lavillastrangiato** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/9bcd2f20-d72d-43a8-b05b-c4951dbae5c0)
This issue can be closed now.

**Comment by FluffyGhoster** [comment]
As per above
