### ISSUE TITLE
[Bug]: Bodymarking Tattoo (Koi, R. Arm) is broken

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#17367]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

Selecting the tattoo body marking in the title does not show it in the character preview. Others seem to work.

### How to reproduce

1. go in character creation
2. select said tattoo
3. dont see it

### Round ID

cpQ-dBiE

**Comment by alsoandanswer** [comment]
lol apparently the left and right arms are swapped around
