### ISSUE TITLE
AI LOOC is based on the core instead of the eye.

### ISSUE THREAD

**Issue by ShameOnTurtles** [Aurorastation/Aurora.3#1739]
Contrary to what's stated in the changelog:
> AI now hears LOOC both around its eye and its core, and speaks in LOOC around its eye. Keep in mind that you won't hear and won't be heard if there is a wall between your eye and the target. 

Some testing done:
- The AI cannot hear LOOC around it's eye regardless of holopad mode.
- The AI cannot broadcast LOOC to people around the eye, regardless of holopad mode.

From what I can tell LOOC seems to still be based around the core.

**Comment by AgentWhatever** [comment]
Can confirm as a frequent ai player

**Comment by nicemoreoften** [comment]
should be fixed by #7886
