### ISSUE TITLE
Atmo alarms can not be set remotely

### ISSUE THREAD

**Issue by TheFurry** [Aurorastation/Aurora.3#174]
when you fiddle with the green computer that monitors all the alarms you can't change a single thing. even though it says the setting for remote control is on auto.

**Comment by skull132** [comment]
"Auto" only grants remote control whenever the alarm is activated. Were the alarms you were trying to change red while changing them?

**Comment by TheFurry** [comment]
no, so is that just a difference we're going with? old code we could just flip the alarms and change settings remotely no matter what

**Comment by skull132** [comment]
I was never actually informed of such a bug existing in old code (though, I can see why I wouldn't be). The idea behind the "OFF|AUTO|ON" settings is this:
* OFF - you cannot interface with the alarm at all. Denied.
* AUTO - the computer and alarm are meant to recognize when remote access is necessary, and grant it under such conditions (typically, when the alarm is active)
* ON - you can do everything forever.

Removing how AUTO acts like now would make the option pointless. Would also give a little too large of a boon for atmos techs at round start as well, tbh. If you want the benefits of full control, gotta hoof it and work for it.

**Comment by SierraKomodo** [comment]
If I recall, in old code, the air alarms were set to default to 'on' instead of 'auto' ; That might be where the confusion here is from

**Comment by skull132** [comment]
No. What's more likely is that, at some point, oldcode had this feature broken.

**Comment by SoundScopes** [comment]
It happened when you changed to the updated atmos/machine code.

**Comment by Bedshaped** [comment]
Closing.
