### ISSUE TITLE
[Bug]: Dropped Mining Mecha's don't respond to voice commands.

### ISSUE THREAD

**Issue by Stev-the-third** [Aurorastation/Aurora.3#17400]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Exosuits dropped via the Mining Mecha Dropper do not respond to commands to link, or any other voice commands. 

### How to reproduce

1: Get a Mecha dropper
2: Enable Maintenance protocols
3: Say "Mining Mecha, listen to me"
4: Hear the silence.

**Comment by Geevies** [comment]
im pretty sure that's because the mech is in a vacuum

**Comment by FluffyGhoster** [comment]
Test it in a pressurized environment and reopen if it doesn't work there either, I think in a vacuum it's expected not to
