### ISSUE TITLE
[Bug]: Laying Down / Rest Orientation Issues

### ISSUE THREAD

**Issue by NobleRow** [Aurorastation/Aurora.3#17408]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The rest function, and laying down in general, has a few issues in regards to orientation. The chief among them that is the most annoying for me is that for some reason resting while laying on your back puts you in the wrong orientation, laying your head on the left side when every bed in the game is oriented to accommodate someone laying their head on their right side (Screenshot 1).
![Screenshot 2023-09-22 185209](https://github.com/Aurorastation/Aurora.3/assets/137841920/e75f0dbf-6cd9-426d-a338-7faaea3a6103)
There is no orientation with ctrl+arrow keys that puts your head on the original right side while laying on your back (See screenshots 1-4).
![Screenshot 2023-09-22 184753](https://github.com/Aurorastation/Aurora.3/assets/137841920/a44288a5-5847-4811-83db-8017219139cb)
![Screenshot 2023-09-22 184743](https://github.com/Aurorastation/Aurora.3/assets/137841920/9dc3f4db-6eef-41f5-9cb8-70fbc94e5e04)
![Screenshot 2023-09-22 184728](https://github.com/Aurorastation/Aurora.3/assets/137841920/15f29597-e308-4ebb-b768-9de957a44a7e)
![Screenshot 2023-09-22 184718](https://github.com/Aurorastation/Aurora.3/assets/137841920/f8ef52d4-a883-4cc9-a46a-e46b3a62b608)

Additionally, being buckled to a bed now exclusively has you laying on your side instead of laying on your back (Screenshot 5). You cannot change your orientation while buckled.
![Screenshot 2023-09-22 184826](https://github.com/Aurorastation/Aurora.3/assets/137841920/85851c63-2cdc-4bde-8a76-0ffe4ed965d4)

### How to reproduce

1. Rest
2. Spam Ctrl+arrow keys to find out you cannot lay down like you could originally.

**Comment by SleepyGemmy** [comment]
caused by #15952.

**Comment by FluffyGhoster** [comment]
This looks expected to me, you are oriented to the right or left when turning right or left, then you're oriented facing the camera when turning south, and away from it when turning north

**Comment by NobleRow** [comment]
> This looks expected to me, you are oriented to the right or left when turning right or left, then you're oriented facing the camera when turning south, and away from it when turning north

The issue is, before this merge, laying on your back places your head on the right. This coincides with every bed sprited for the game which is designed with a pillow on the right side for that purpose.

Screenshot 1 is on the psych's bed-chair and demonstrates this purpose. You're supposed to be able to lay down on your back with your head resting on the pillow. Currently your feet rest on the pillow, and if there were sheets, your entire body except your feet would be covered. This is how every bed in the game is designed.

**Comment by FluffyGhoster** [comment]
Sure, the problem is that previously, we were not considering any direction at all, you were to always fall/lay towards the right indifferently if you was facing it or not, then the buckling would set your direction to south (aka facing the camera), and that's why you were seeing people looking "up"

What can possibly be done is making facing south bound you to be right rotated instead of left rotated, I will look into if it can be done without some special snowflake code

**Comment by NobleRow** [comment]
Perhaps you could separate the tactical lying down merge from the base game so you're not editing core game elements when utilizing the tactical lying down system? The rest function is a more common function anyhow that is utilized by all of the player base, while the tactical lying down system is a very niche circumstance.
