### ISSUE TITLE
[Bug]: Custom item descriptions are missing in game.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#17425]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

As it says. Custom items from the loadout don't appear to have their descriptions properly ported over into the game.

![image](https://github.com/Aurorastation/Aurora.3/assets/60306280/3656ac71-79f3-446a-be4b-0c0ee77662ca)

![image](https://github.com/Aurorastation/Aurora.3/assets/60306280/7ece395f-14b5-425e-b9e6-8c673d82a10c)

**Comment by alsoandanswer** [comment]
have you tried toggling it off and on again and resaving?

**Comment by Generalcamo** [comment]
This is intentional, see #17417 

This will be fixed with #17419

**Comment by Arrow768** [comment]
Should be fixed
