### ISSUE TITLE
[Bug]: ESS rig turns jumpsuits invisable.

### ISSUE THREAD

**Issue by HanSolo1519** [Aurorastation/Aurora.3#17427]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Attempting to wear the Exo-Stellar Skeleton Rig with a jumpsuit/uniform results in the ESS suit chestpiece covering it when active.
![image](https://github.com/Aurorastation/Aurora.3/assets/72716882/9977c7ab-696e-4bfd-860e-a3893db699fd)

### How to reproduce

1. Put on jumpsuit and ESS rig
2. Deploy ESS rig
3. Activate ESS rig
4. Congratulations; you are now in your underpants.

### Staff ckey

cpX-cwCk

**Comment by alsoandanswer** [comment]
Next time, please don't use acronyms for bug reports.

**Comment by HanSolo1519** [comment]
> Next time, please don't use acronyms for bug reports.

Apologies, this is the Exo-Stellar Skeleton Rig, found in the human exowear selection in the loadout.
