### ISSUE TITLE
Engineering Borg Inflatables Dispenser

### ISSUE THREAD

**Issue by Omega5102** [Aurorastation/Aurora.3#1742]
Admin: SirCatnip
Game ID: bMX - bmFn

I was playing engineering borg, and I had been using inflatable doors quite a bit. After a while, the inflatables stopped placing when I clicked (I had ran out previously, however I had refilled it with ones I had picked up)

Replicated the bug by respawning, placing all my inflatable doors and picking them up again. This stopped me from placing them again.

**Comment by SirFruitcakes** [comment]
I second this bug.

**Comment by Surrealistik** [comment]
The doors/walls should probably regenerate when you charge.

**Comment by Omega5102** [comment]
I'll try that.

**Comment by NanakoAC** [comment]
fixed by #1897
