### ISSUE TITLE
[Bug]: Mining points sometimes assigned to wrong ID

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#17449]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Sometimes when Miner B collects their points from the ore redemption console while Miner A is in the room, the points get given to Miner A instead of Miner B.

### How to reproduce

This is how I think the bug might be caused:
1.) Have Miner A touch the ore redemption console first and set up the smelting/alloying/compressing
2.) Put some ore into the industrial smelter
3.) Have Miner B go to the console and hit the "Claim points." button

### Round ID

cpY-c5ar

**Comment by Geevies** [comment]
from what i can see, this was caused by https://github.com/Aurorastation/Aurora.3/pull/17294
