### ISSUE TITLE
[Bug]: In-game "rules" page is very broken

### ISSUE THREAD

**Issue by tomekkiel** [Aurorastation/Aurora.3#17454]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

As the title says. The current rule pop-up in-game window is quite broken. Most of the hyperlinks either don't work, or instead of opening the wiki/forums in your browser, open them in the actual window, where they are unusable. The rules are also incredibly hard to read with the black text on a dark blue-grey background.

### How to reproduce

1. Click on "rules"
2. Strain your eyes trying to read the rules
3. Click on any of the hyperlinks

### Round ID

N/A

### Staff ckey

N/A

**Comment by FluffyGhoster** [comment]
The page doesn't exist anymore, it's a link now, so this is essentially fixed
