### ISSUE TITLE
[Bug]: Xeniobiology's first door from R&D hallway is bolted, and you have to press the button twice to unbolt it.

### ISSUE THREAD

**Issue by synystersparx** [Aurorastation/Aurora.3#17459]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When a round starts, I have to hit the bolt buttons twice to unlock the door so I can open it. If it should be bolted from the start, is there a way to sync up the button state with the door state?

### How to reproduce

1. Start round
2. Try to open Xenibiology Department door
3. Hit the bolts button
4. Try to open door again, fail
5. Hit the bolt button again
6. Open door successfully

**Comment by Jasorn** [comment]
same thing with ship ammo storage room

**Comment by furrycactus** [comment]
This has been the norm for every door that start bolted and have a nearby button for many years.

**Comment by FluffyGhoster** [comment]
Working as intended, as per above, this is the norm with buttons
