### ISSUE TITLE
AIs not getting notification when receiving random traitor law 0.

### ISSUE THREAD

**Issue by TrickingTrapster** [Aurorastation/Aurora.3#1749]
When an AI receives random pick from autotraitor, they should receive a large notification that they have become traitor and received law 0. What happens now is that they receive no notification at all and probably be unable to do any antagging because they have no idea they are an antag in the first place. I have seen this happened before and it happened again recently. In addition, they do not receive a notification when laws are modified by others either.

**Comment by AgentWhatever** [comment]
I had this happen once. Can confirm it's sporadic

**Comment by Geevies** [comment]
Fixed.
