### ISSUE TITLE
[Bug]: Machine pistol description mentions 'NI' instead of 'ZI' abbreviation.

### ISSUE THREAD

**Issue by VeteranGary** [Aurorastation/Aurora.3#17501]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

https://i.gyazo.com/828b09577873299bb2a60525ab3fcc97.png

Incredibly likely this was just one of a handful of oversights from renaming Necropolis to Zavodskoi, an inconsequential issue really. Other Zavodskoi produced weapons such as the bullpup, are abbreviated with ZI, 'ZI Bulldog' for example.

### How to reproduce

1. Examine a Machinepistol
2. Show In Chat the extended description
3. Mentions NI Sabre 550 instead of ZI Sabre 550

**Comment by FluffyGhoster** [comment]
That machinepistol was probably created by necropolis industries and the name remained, perhaps?
Necropolis industries was later absorbed into Zavodskoi, but it isn't a given that they would rename every weapon they got
¯\_(ツ)_/¯
