### ISSUE TITLE
Carp don't attack maintenance drones when the drone's health falls below 0%

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1750]

**Comment by SirFruitcakes** [comment]
I second this, i've already reported it to multiple coders but I guess I forgot to post a github somewhere along the lines.

**Comment by SierraKomodo** [comment]
I imagine it has to do with the coding that makes carp not attack anyone who's down.

**Comment by Alberyk** [comment]
This should be fixed as simple mobs just check if the target is sleeping or not to attack.
