### ISSUE TITLE
[Bug]: Pulling the Janicart removes stamina cost for sprinting

### ISSUE THREAD

**Issue by Somguy2** [Aurorastation/Aurora.3#17509]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When you pull the janicart, you're put into a state where you push the janicart instead. This is normal, and instead of following you, it's infront of you.
When you initiate this state, you seem to have unlimited stamina for sprinting, and can run across the ship superfast with zero cost (This may be intentional, but I have not heard otherwise.

### How to reproduce

Get a janitor cart
Pull it (to start pushing it)
Sprint as much as you like.

### Round ID

cp7-dj35

**Comment by FluffyGhoster** [comment]
Duplicate #16647
