### ISSUE TITLE
[Bug]: You can literally just pick things up through (some?) windows.

### ISSUE THREAD

**Issue by listerla** [Aurorastation/Aurora.3#17510]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

https://github.com/Aurorastation/Aurora.3/assets/57296132/a2b827a9-2cb1-41d0-a11b-23d120e9f7e1

### How to reproduce

1. Enter Xenoarchaeology (potentially other locations)
2. Click on an item on one side of a window while on the other side

### Round ID

cp7-dHhy

**Comment by HanSolo1519** [comment]
This is an issue with tables I believe, you can interact with tables through windows. You can even table-drag yourself onto them, through windows.

If you tried this without a table, I believe this would not be an issue.

**Comment by FluffyGhoster** [comment]
Duplicate #17321
