### ISSUE TITLE
Maintenance drone health can fall below 0%

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1751]
Uncertain if this is intended or not. If not intended, #1750 is a side effect of this bug.

**Comment by LordFowl** [comment]
Possibly related to https://github.com/Aurorastation/Aurora.3/issues/1562 ?

**Comment by SierraKomodo** [comment]
Not certain, I do know drones are not invulnerable because when their health gets low enough (I think the threshhold is around -100%), they die. Space bears tend to wreck drones because they keep attacking even when you're down.

**Comment by LordFowl** [comment]
Then it is not related.

**Comment by SirFruitcakes** [comment]
This is intention I think, for the same reason 'borgs have 200 health, it's just that Drones don't disable at -100 whereas 'borgs do IIRC. Other Species start at 200 HP and drop to 0, Synths start at 100 and drop to -100, or this is how it works going by the Cyborg analyser. Just a hunch, and might not be true.

**Comment by Geevies** [comment]
Fixed.
