### ISSUE TITLE
[Bug]: Serotrotium is not on the wiki or in chem guide.

### ISSUE THREAD

**Issue by lilahnovi** [Aurorastation/Aurora.3#17547]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Just a random chemical that poofs out of the scrubbers sometimes - my character got dosed with it. Not anywhere on the wiki. Found it on /TG./

![image](https://github.com/Aurorastation/Aurora.3/assets/124811534/f5d820df-efa7-4487-8b4e-80db78874ffb)

**Comment by FluffyGhoster** [comment]
If it's missing from the wiki, it should be reported to the wiki maintainers, but it is not a code bug
