### ISSUE TITLE
[Bug]: ChemMaster bugs (TGUI?)

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#17564]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

1. When creating pills and hitting cancel, the reagents are just outright deleted.
2. After creating multiple pills, the popup menu from creating multiple pills goes NT BSOD.

### Round ID

cqc-dwJ7

**Comment by FluffyGhoster** [comment]
Unable to reproduce, even cancelling the creation of one or multiple pills it creates a pill, without deleting the reagents

**Comment by FluffyGhoster** [comment]
Closing as stale, if there is a clear path to reproduce the issue, feel free to reopen as usual
