### ISSUE TITLE
[Bug]: CCIA cannot send faxes in-game

### ISSUE THREAD

**Issue by Spookat** [Aurorastation/Aurora.3#17573]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The new TGUI UI for create command report is bugged and does nothing after selecting a template and clicking submit.

This also applies to freeform report.

**Comment by FluffyGhoster** [comment]
Should be fixed in #17681 , can you check and confirm?
