### ISSUE TITLE
[Bug]: CoC Surveyor shuttle slightly broken

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#17604]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

1.) The APC does not actually draw power and stays at 90% eternally
2.) The airlock doesn't actually cycle (in or out) but the vents do try to do something
3.) The airlock doesn't lose pressure when exposed to space, but the rest of the shuttle will lose air if a window is broken
4.) The shuttle lacks any vent/scrubber system
5.) The shuttle was unable to land on the mineral asteroid specifically (grove exoplanet on this round of testing was fine)

**Comment by lavillastrangiato** [comment]
The ship now has a functioning atmospherics system (scrubber and vent) that refill if it's broken; I swapped the vent frequencies to what they're all supposed to be, but I still can't grok why the airlock continues to keep its air/doesn't cycle properly.

More to come!

**Comment by Nalarac** [comment]
Fixed by #18655
