### ISSUE TITLE
[Bug]: TGUI crew manifest broke during a round

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#17614]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

trying to open crew manifest in lobby or as ghost gives bluescreen
![image](https://github.com/Aurorastation/Aurora.3/assets/5076069/2c8dc96e-7042-4876-ab20-e21e7f3507ef)

### Round ID

cqi-bTf6

**Comment by FluffyGhoster** [comment]
Closing in favor of #17615 which is about the same issue and has the data in text format
