### ISSUE TITLE
Modular batteries start off with 0 charge and there is no way to recharge them

### ISSUE THREAD

**Issue by Arzion5** [Aurorastation/Aurora.3#1763]
The modular batteries used for modular consoles, laptops, and tablets start off at 0 charge when made from R&D. They cannot be recharged in any way, shape, or form because they are incompatible with power cell recharger devices such as high-duty rechargers. The only way to create additional modular consoles, tablets, and laptops is to salvage items from the laptop vendor or from already-existing modular consoles. I am not sure if the tesla link can be fabricated, but as far as I know, it only works for consoles.

**Comment by Arrow768** [comment]
I´ll look into it as part of the IT project.

**Comment by Lohikar** [comment]
Can you not put the battery in a modular laptop then charge the laptop?

**Comment by Surrealistik** [comment]
Already posted about this; you _cannot_ manufacture stuff like the tesla links or anything else that charges the modular technology: https://github.com/Aurorastation/Aurora.3/issues/1747

**Comment by HunterRS** [comment]
I've talked to nanako,  tesla links probably wont be able to be built, but the rest of the batteries can be charged with a recharger

**Comment by Surrealistik** [comment]
Wait, what? So you have to keep recharging the stationary modular computers by taking out their internal battery?

**Comment by HunterRS** [comment]
Tesla Links are ones that draw from the power grid, and yes you if make a console you have to take the battery out and charge it unless you have a tesla link.
