### ISSUE TITLE
[Bug]: Singleton/reagent/drugs does not return what drug it is on being scanned with a reagent scanner, but can be spawned in Cargo's Warehouse

### ISSUE THREAD

**Issue by Somguy2** [Aurorastation/Aurora.3#17647]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

it can spawn in a container in the ops warehouse, and doesn't have an actual name. I have not seen this before, so it may be an issue with the recently added heroin and cocain? but I am not sure because it just returned the name Singleton/reagent/drugs.

### How to reproduce

Find a container with the mystery drug.
It will read: 
![image](https://github.com/Aurorastation/Aurora.3/assets/146895942/b98f6e81-e77b-47e2-9bd2-6f5c0c83c66a)
on examining.

Scanning it with a reagent scanner, or putting it in a machine that will read it, will tell you that it is the chemical "/singleton/reagent/drugs".

I wish I could help more with finding it, but it seems like it's just genuine RNG that gave it to me.

### Round ID

cqo-aLI5

**Comment by Somguy2** [comment]
If it helps with identifying the chemical, drinking it will tell you 'You can taste a bad investment'

**Comment by FluffyGhoster** [comment]
This should be fixed, reopen if not
