### ISSUE TITLE
[Bug]: Making Oxycomorphine by mixing Ethanol and Morphine, with a phoron catalyst does not work.

### ISSUE THREAD

**Issue by Somguy2** [Aurorastation/Aurora.3#17669]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Making the Oxycomorphine by mixing Ethanol, and Morphine, while using a phoron catalyst, does not work, despite the wiki indicating it should.

### How to reproduce

Put 5u of phoron in a beaker.
add 30 u of Ethanol
add 30 u of Morphine
Expect to get a nice drug, but get given nothing.

**Comment by Nalarac** [comment]
Recipe in the code is morphine and mortaphenyl with phoron catalyst. Wiki will need to be updated or recipe changed in the code.

![image](https://github.com/Aurorastation/Aurora.3/assets/8042031/3d641d4b-5dca-4a6b-a755-5d9b3225884e)

**Comment by lavillastrangiato** [comment]
Wiki has been edited.

**Comment by FluffyGhoster** [comment]
As per above
