### ISSUE TITLE
[DEV MAP] Heist/raider shuttle travelling section seems to be missing some animated space tiles

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1768]
![dsrgsd](https://cloud.githubusercontent.com/assets/11140088/22867673/0b1183a4-f141-11e6-95d6-6b1f5626a2c3.PNG)

**Comment by LordFowl** [comment]
Thank you for your diligence, but at this stage due to the rough nature of the map bug reports for every little thing will only clog up the git - you may be free to report major errors or discrepancies, and leave minor issues to be corrected internally until a later date.
