### ISSUE TITLE
[Bug]: Oxycomorphine recipe not working

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#17694]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Went to make the Oxycomorphine recipe, and I'm unable to.

![image](https://github.com/Aurorastation/Aurora.3/assets/60306280/c8d9ba30-2988-4614-9bc8-33f7fd17ac81)

![image](https://github.com/Aurorastation/Aurora.3/assets/60306280/0fc54087-6016-4dc2-b22f-a9d79f25a10b)

### How to reproduce

Just try to make it. Doesn't work. At least this round.

### Round ID

cqv-aQVV

**Comment by Melariara** [comment]
Also, as a result, the recipe for Joy is also bugged.

**Comment by SleepyGemmy** [comment]
oxycomorphine is made with morphine now, not ethanol. joy is made with heroin. i'll let the wiki team know of the inconsistencies.
