### ISSUE TITLE
[Bug]: Operating computers will not accept a scan if one has been inserted previously that shift

### ISSUE THREAD

**Issue by Kelnor277** [Aurorastation/Aurora.3#17706]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Operating computers will not accept a scan if one has been inserted previously that shift.
I think it's  because the old scan isn't being ejected, so it thinks there's still one in the computer.

Also, Op comps no longer show BA/BP/BO etcetera unless a scan is inserted. I don't like that and I'm not sure if that change was intentional?

### How to reproduce

1: Print a scan
2: Put patient on Operating Table.
3: Insert Scan
4: Remove patient and print a new scan (or get a new patient)
5: Place back on table
6: Attempt to insert scan.

### Round ID

cqw-dj2g

**Comment by Acetrea** [comment]
I recently learned that you can right-click the console and it will give the option "Eject Primer". It removes the scan and allows a new one to be inserted.

**Comment by FluffyGhoster** [comment]
You have to remove the previous paper for the computer to accept a new one, right click on it and select the option "Eject primer"
