### ISSUE TITLE
[Bug]: Greimorian eggs cannot be removed via surgery

### ISSUE THREAD

**Issue by shimmeristaken** [Aurorastation/Aurora.3#17729]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When performing surgery to remove greimorian eggs, the hemostat will search but not pull anything out, thus making eggs impossible to remove safe for placing a patient under a large amount of toxin damage.

### How to reproduce

Spawn a greimorian nurse and get it to bite someone a lot
Drag them to scan for eggs
Open a surgical site, and attempt to remove them with a hemostat

**Comment by Acetrea** [comment]
I'm pretty sure that #17598 is what caused this bug.

**Comment by Melariara** [comment]
This is very much still an issue in game and is causing a lot of issues for everyone.
