### ISSUE TITLE
[Bug]: Nooses don't work

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#17732]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Doesn't let you tie the noose around your neck, despite the "this takes 20 seconds" message appearing.

You don't die, you dont suffocate, you dont get buckled, nothing happens at all after the progress bar is filled up. Table/stool/chair does not matter, doesn't work.

### How to reproduce

25 coil lengths in hand,
right click coil
make noose
stand on chair
attempt to clickdrag your sprite onto the noose

### Round ID

cqC-dzqq

### Staff ckey

ReadThisNamePlz

**Comment by SleepyGemmy** [comment]
can confirm. playtested and got the error message "You fail to tie the noose around X."
