### ISSUE TITLE
Medical and rescue drones icon

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#1773]
Rescue modules have the option to become the rescue (green) drone icon and chemical (orange) icon.
Medical modules also have the option to become the rescue (green) drone icon and chemical (orange) icon.

With how the modules are currently equipped and the extra surgery (red) drone icon, it should be that rescue can only pick the green icon and medical the red or orange one.

**Comment by Omega5102** [comment]
Medical module has the chemistry available.
