### ISSUE TITLE
[Bug]: Colorable shorts and short shorts sprites are invisible

### ISSUE THREAD

**Issue by feartheblackout** [Aurorastation/Aurora.3#17740]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The colorable shorts and short shorts, implemented by #17691, have invisible mob sprites.

### How to reproduce

1. Open character setup and go to the Loadout tab
2. Take the "pants and shorts selection (colourable)" item under Uniforms and Casual Dress, with either the type "Shorts" or "Short shorts"
3. Look at your character preview

### Round ID

cqE-daqz

**Comment by lavillastrangiato** [comment]
Can verify this is also happening to me.
