### ISSUE TITLE
[Bug]: Letter signs do not match isolation cells - anomaly studies 

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#17754]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/8639807/3ba5eb03-4926-47c5-b3e8-7e48ae83d4b2)

Simply put, the letters on the floor go A-B-C, while the doors go isolation C-B-A. Very minor issue.

### How to reproduce

No reproduction necessary.

**Comment by FluffyGhoster** [comment]
Should be fixed according to the map editor
