### ISSUE TITLE
You Can Do Surgery on a Patient through a Sealed Hardsuit

### ISSUE THREAD

**Issue by Surrealistik** [Aurorastation/Aurora.3#1778]
If a character has an unfinished surgery, you can complete it, or otherwise do other surgical interactions through a sealed hardsuit (even though it should prevent all such surgical interactions).

**Comment by Lohikar** [comment]
Testing shows that you can do surgery on people wearing RIGs no matter what.

Thanks baycode.

**Comment by Geevies** [comment]
Fixed.
