### ISSUE TITLE
[Bug]: Rubber Carpet turns into regular fabric Carpet

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#17792]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon, Intrepid, Spark, Away Site, Third party ship

### Describe the issue

If you remove Rubber Carpet flooring and attempt to place it back down, the result is the default red and gold fabric carpet.

### How to reproduce

1. Crowbar up Rubber Carpet or acquire it some other way.
2. Attempt to place it on plating.

**Comment by Acetrea** [comment]
This is happening for all subtypes of Carpet.
