### ISSUE TITLE
[Bug]: North-facing lightbulbs incorrectly offset

### ISSUE THREAD

**Issue by zagoon** [Aurorastation/Aurora.3#17790]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

Since the 3/4thening, all north/upward-facing lightbulbs have been fully disconnected from the walls.

I believe this was brought up in the feedback thread, but since no one's looked at that for a while I figured it'd gain more visibility as a proper issue report.
![offset](https://github.com/Aurorastation/Aurora.3/assets/9440824/acf53ae5-930f-48bb-b74a-9d0e0b37ef22)

**Comment by FluffyGhoster** [comment]
It appears solved at the moment
