### ISSUE TITLE
[Bug]: Arterial bleeding does nothing once bandaged externally

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#17807]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Arterial bleeds give a multiplier to bleeding, cause blood squirting, but once the bleed is bandaged, they do nothing. Despite this being the case even since i've started playing in september 2022, i've always been told anytime I bring it up that "no you bleed internally still, it's just that you outheal the blood loss except for chest and head" and even then I've had chest and head arterials not cause blood loss on me, so I tested it on a private server:

![image](https://github.com/Aurorastation/Aurora.3/assets/5076069/7716b886-98fd-4701-8e99-bd5e473fb722)

I gave arterial bleeding to a human on EVERY limb, and never saw their blood drop at all, only until I gave a cut did they start squirting blood rapidly

I was told this isn't how it should work and be bug reported, however keep in mind if this is fixed the time to death will probably tank massively since fixing arterials require surgery and bleeding is the quickest way to die

### How to reproduce

1. Give arterial bleeding all over someone without any external injuries
2. Watch in scanner as they don't lose any blood ever

**Comment by Sniblet** [comment]
Maybe we just have really really good tourniquets in the future? This could possibly be "fixed" by just reflavoring the bleed. It saves on worries about the fatality rate.
