### ISSUE TITLE
[Bug]: Chlorine contamination falsely labeled as phoron

### ISSUE THREAD

**Issue by chaoticidealism** [Aurorastation/Aurora.3#17840]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Spark, Away Site, Overmap

### Describe the issue

When you contaminate an object with chlorine, the object is labeled as having been contaminated with phoron. I'm unsure whether it has phoron-specific effects as well, whether it's just the label that's wrong or the entire effect. Chlorine and phoron could conceivably have the same effect on contact--severe burns to the skin. Chlorine shouldn't cause organ damage, though phoron might need to. If they are to have the same effect, this would be an easy fix because it could all just be generic contamination and examining it could show "Contaminated with toxic chemicals".

### How to reproduce

1. Hold item in your hand
2. Walk into chlorine atmosphere
3. Examine held, contaminated item

### Round ID

cqY-c6tv

### Staff ckey

n/a

**Comment by FluffyGhoster** [comment]
>Chlorine shouldn't cause organ damage

This is incorrect

Anyways, in `code\game\objects\objs.dm` the function `/obj/examine(mob/user)` adds the string where it says it's phoron, but the only check is for contamination.

**Comment by chaoticidealism** [comment]
> > Chlorine shouldn't cause organ damage
> 
> This is incorrect
> 
> Anyways, in `code\game\objects\objs.dm` the function `/obj/examine(mob/user)` adds the string where it says it's phoron, but the only check is for contamination.

What I meant was that skin contact with chlorine-contaminated objects should cause chemical burns to the skin, but not organ damage. Inhaled chlorine should cause lung damage, obviously.

Anyways, it sounds like this is a simple fix; just change the "phoron contamination" to "chemical contamination".
