### ISSUE TITLE
Full access by wearing maintenance drones

### ISSUE THREAD

**Issue by Aboshebab96** [Aurorastation/Aurora.3#1785]
Had an Assistant walk into the bridge casually by wearing the maintenance drone, it apparently acts like a free all access card.

**Comment by Pratepresidenten** [comment]
This issue applies to pAIs aswell it seems.

**Comment by SirFruitcakes** [comment]
Might be related to the way Spiderbots can open doors by drawing a person into a door.

Let me explain... 

they drag, skip through the doggy door, and then the person keeps following them until they bump into the door, and the door opens. I could see it being the same way with this, but a little different.

**Comment by Spoopy11** [comment]
https://puu.sh/uAfT7/9b6c904397.png

**Comment by SierraKomodo** [comment]
Someone in OOC brought up that the 24 December 2016 changelog includes this in the notes from Zuhayr (And are as such saying this isn't a bug):

>Drones (and any mob that can be picked up) can be bashed against airlocks and such to use their internal access, so long as the person using them does not have an ID card equipped.
