### ISSUE TITLE
[Bug]: Ghost Roles cannot pick Plural pronouns 

### ISSUE THREAD

**Issue by Clem-The-Duck** [Aurorastation/Aurora.3#17895]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

Ghost roles when spawned and given the character creation screen are not able to pick the plural pronouns. clicking the button simply does not work

**Comment by FluffyGhoster** [comment]
This should be fixed with #18553
