### ISSUE TITLE
Borg medical sprite prompt

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1790]
Picking the "advanced droid" option in the sprite selection instantly prompts you to select a sprite again once you confirm it.

**Comment by SirFruitcakes** [comment]
It happens for a lot of Modules, if you select advanced droid again, does it fix?

**Comment by Pratepresidenten** [comment]
Yes, but the immediate prompt isnt supposed to be there. There are no such issues with either of the other modules that Ive tried.

**Comment by SirFruitcakes** [comment]
I've had the issue a LOT with the 'Classic' sprite line, so it's not just advanced Droid.

**Comment by Surrealistik** [comment]
Can confirm. Annoying.

**Comment by NanakoAC** [comment]
fixed by #1888
