### ISSUE TITLE
[Bug]: Nralakk Federation Work Uniforms Don't Have Sensors

### ISSUE THREAD

**Issue by SpessMneme** [Aurorastation/Aurora.3#17908]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The Federation work uniforms don't have any sensors, they likely should since they're a work uniform and not personal clothing.

### How to reproduce

Get a Federation work uniform, try and toggle sensors, no sensors.

### Round ID

cra-c0Ff

**Comment by FluffyGhoster** [comment]
Sensors were readded to all uniforms
