### ISSUE TITLE
[Bug]: Deck three civilian subgrid appears to be cut at an early point 

### ISSUE THREAD

**Issue by hazelrat** [Aurorastation/Aurora.3#17930]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The deck three civilian subgrid, the one just south of the engineering breakroom, seems to have been cut at any early point by recent mapping changes, meaning a lot of deck three will always lose power after a little while until an engineer fixes it.

From what I can tell, right now it only supplies power to the engineering breakroom APC, and the rest of the subgrid isn't connected to the substation.

![image](https://github.com/Aurorastation/Aurora.3/assets/83198434/d0bdb662-2150-4c14-8937-78ee97805659)

The green lines in this image are the deck 3 civilian subgrid, the red lines are master grid lines. The substation used to connect to the rest of the subgrid over the stretch of maintenance just south of the shield generator room, so they must've gotten removed to make space for the master grid line running to telecommunications without having been replaced. 

### How to reproduce

1. Start a new round.
2. Check an APC running on the deck three civilian subgrid, this seems to be basically any civilian area on deck three. None of them should have external power.
3. Connect the substation back up to the subgrid, and see that power comes back.

**Comment by FluffyGhoster** [comment]
This should be fixed in subsequent commits to the map PR that introduced it, and is not present on live anymore
