### ISSUE TITLE
[Bug]: Dhrarmela banner does not have any sprites

### ISSUE THREAD

**Issue by Silvore** [Aurorastation/Aurora.3#17956]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The banner of Dhrarmela seems to be lacking any sprites?

### How to reproduce

1. Set up Dhrarmela banner
2. Watch as it doesn't exist

### Round ID

crg-anZ5

**Comment by Wildwestmars** [comment]
Bugfix has been made for these problems, issue is now resolved! 🐱 👍
