### ISSUE TITLE
[Bug]: Shumaila hammer doesn't have any sprites?

### ISSUE THREAD

**Issue by Silvore** [Aurorastation/Aurora.3#17955]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

So, after I made the Shumaila hammer hammer, I noticed there was nothing on the ground, and I had nothing in hand, after right clicking where I was standing, I saw the hammer had no sprites.

### How to reproduce

1. Take null rod and create Shumaila hammer with it
2. Watch as no sprites appear

### Round ID

crg-anZ5

**Comment by Wildwestmars** [comment]
Bugfix has been made for these problems, issue is now resolved! 🐱 👍
