### ISSUE TITLE
Ashtray issues

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#1796]
round in bug discovery: bM6-dMHV

There's a current issue with using ashtrays. Putting cigarette butts wholly smoked into ashtrays fills them and also deletes them from existence, but begins to fill how full the ashtray is. Cigarettes not completely smoked that are doused early into the ashtray actually count as contents in the ashtray. It should be filling the ashtray with plain butts from cigarettes regardless if they were doused early or doused as butts.

Throwing the ashtray against the ground for instance **should** empty all of the ashtray's contents by spilling them onto the ground but it will only empty the ones that were doused early and only partially emptying the ashtray.

**Comment by Geevies** [comment]
Fixed?
