### ISSUE TITLE
VVing a syringe gun causes a read error

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#1798]
bM7-dHMV

Only reproduce-able through one round but it causes anyone who VVs it to immediately crash and be forced to reconnect. Could cause issues with investigating, need to reproduce again.

**Comment by Lohikar** [comment]
This is an old issue; sometimes random objects will become un-VVable, and will crash anyone who tries to VV them.

This is not unique to syringes.

**Comment by Geevies** [comment]
Fixed, I think.
