### ISSUE TITLE
[Bug]: Invisible vines.

### ISSUE THREAD

**Issue by Snowy1237** [Aurorastation/Aurora.3#17995]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The vines from the space vines biohazard are invisible and as such can not be clicked on to destroy them.

### How to reproduce

Spawn vines biohazard and observe that they are invisible.

### Round ID

crl-cW7p and the round before that.

### Staff ckey

Matt has manually given the vines a sprite.

**Comment by Snowy1237** [comment]
The issue seems to be caused by PR #17967

**Comment by FluffyGhoster** [comment]
Fixed in #18019
