### ISSUE TITLE
[Bug]: SCC Scout Ship power runs out almost immediately

### ISSUE THREAD

**Issue by beepbopbeepbop** [Aurorastation/Aurora.3#17993]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

After beginning to fly at low speeds to the horizon, which was 2 tiles away, we immediately loose engine power the moment we reach the horizon's position. This is due to the fact the ship has no SMES of it's own, and is relying on a single APC with a heavy duty power cell.

### How to reproduce

1. Take off on the shuttle
2. Make sure all fuel stuff is on
3. Begin flying towards anywhere
4. Watch the APC to see as the power drains

### Round ID

crl-aV8C

### Staff ckey

Eddymakaveli

**Comment by DreamySkrell** [comment]
fixed
