### ISSUE TITLE
I cannot setup a prosthetic arm on an M'sai tajara

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#1799]
As the title says, I cannot give my m'sai tajara a prosthetic limb. However, I can give my tajara an amputation. This is in the character creation menu, and resetting my limbs doesn't help.

**Comment by Lohikar** [comment]
Tested using latest development branch; was unable to give M'sai or Zhan-Khazan Tajara prosthetic limbs.
Mechanical organs were functional, as are amputations.
No runtimes noted.
