### ISSUE TITLE
[Bug]: Diona Nymph limbs do not appropriately spawn in & Detach/Reattach no longer function.

### ISSUE THREAD

**Issue by Aticius** [Aurorastation/Aurora.3#18035]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Diona Nymph limbs do not appropriately spawn in with all their components, which appears to atleast include the r_hand, but may include more.

Additionally, any attempt to detach the limb using Detach_Nymph simply doesnt bring up the prompt to do so, while having a Nymph nearby and attempting to use Attach_Nymph will claim that you have no open spots for one (despite being down a hand).

To the best of my knowledge, this is caused by https://github.com/Aurorastation/Aurora.3/pull/18015 caused this, but a quick skim of it doesn't immediately explain why.

### How to reproduce

1. Have the dubious idea to have a Nymph Arm as an Unathi (though this probably works with Skrell as well!)
2. Spawn in!
3. Behold your handless (but armed) glory.

### Round ID

crn-dnbn

### Staff ckey

Campinkiller

**Comment by FluffyGhoster** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/0e921acc-3c2f-423e-9a25-bf145fe82b18)
unable to reproduce

**Comment by Aticius** [comment]
Selecting *just* the Nymph Hand appears to work, but selecting the entire Nymph Arm does not include the hand. The steps to reproduce have been updated.
