### ISSUE TITLE
[Bug]: Strawberry Crumble Bars have the wrong recipe

### ISSUE THREAD

**Issue by Karhast** [Aurorastation/Aurora.3#18041]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The Strawberry Crumble Bars have the wrong recipe set for them on the wiki, as confirmed by YouJustGotOwened

### How to reproduce

1. Go to the Guide to Food on the wiki: https://wiki.aurorastation.org/index.php?title=Guide_to_Food
2. Look up Strawberry Crumble bars
3. Toss all ingredients in an oven tray, then into a heated oven

### Round ID

cro-avez

### Staff ckey

YouJustGotOwened

**Comment by Acetrea** [comment]
In the code, two strawberries are needed, not one. The wiki might need to be changed or we can change it to one strawberry in the code, whichever @tomixcomics thinks is right, likely.

**Comment by tomixcomics** [comment]
Yeah, this feels like a wiki thing that should be updated. It's intentioanlly two strawberries. Should be simpel enough to update though.

**Comment by SleepyGemmy** [comment]
fixed.
