### ISSUE TITLE
[Bug]: Off-Ship Shuttle Air Locks Don't Cycle

### ISSUE THREAD

**Issue by Acetrea** [Aurorastation/Aurora.3#18047]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

The airlocks on the third party/off ship shuttles do not cycle. The only buttons that work are force interior and force exterior. Neither buttons on the outside of the airlocks open them, nor does the button to cycle on the inside of the airlock.

### How to reproduce

1. Go to an off-ship shuttle.
2. Click a button to cycle.
3. Watch as it does not work (might even blink a moment, but then returns to it's normal green button state.)

**Comment by lavillastrangiato** [comment]
Which ship is it?

**Comment by Acetrea** [comment]
> Which ship is it?

pretty sure it was the IAC but that got revamped since i made this so idk. i'd also heard it was _all_ offship shuttles when i'd made this. haven't played offship in a while so not sure if it's still like this.
