### ISSUE TITLE
[Bug]: Napalm grenades never go off.

### ISSUE THREAD

**Issue by LynxSolstice** [Aurorastation/Aurora.3#18046]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When primed, the napalm grenades never go off, they just remain in the primed but not exploded state (blinking light, lever released)

### How to reproduce

1. Get Napalm grenade
2. prime napalm grenade
3. nothing happens

**Comment by Colfer1** [comment]
This seems to apply to cleaner grenades too. It may apply to any kind of chemical grenade with a premade assembly but I havent tested that.

**Comment by FluffyGhoster** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/b29ec9bb-bc33-40a7-806e-aa623b509388)
Unable to reproduce

**Comment by LynxSolstice** [comment]
> ![image](https://private-user-images.githubusercontent.com/65877598/292641383-b29ec9bb-bc33-40a7-806e-aa623b509388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzODc4MDgsIm5iZiI6MTcwMzM4NzUwOCwicGF0aCI6Ii82NTg3NzU5OC8yOTI2NDEzODMtYjI5ZWM5YmItYmMzMy00MGE3LTgwNmUtYWE2MjNiNTA5Mzg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDAzMTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNDkyMzllYjQzY2Q4MDFhYWVjYmExZmY4YjBiMDhlNWFjMGQzMWE4YjAyNjdkZjkwZmViYzMzMzg3MjIxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8uDoAvFs1clCLnN_-r8qu6NAcmdSzwgLtzrlSC3ryDY) Unable to reproduce

Was this in a private server or on a branch? It didn't work when I tried using it on highpop server when I submitted the bug report. I primed two grenades and they both failed to go off separately from each other.

**Comment by FluffyGhoster** [comment]
Private server on main branch

**Comment by LynxSolstice** [comment]
> Private server on main branch

May be only an issue on the live server, or related to tickrate. Have you tested the grenades on the live server?

**Comment by FluffyGhoster** [comment]
No, we don't have the ability to spawn grenades on the live server to test things, tests are done locally on the main branch

**Comment by LynxSolstice** [comment]
> No, we don't have the ability to spawn grenades on the live server to test things, tests are done locally on the main branch

Well I encountered the bug on the live server, so if it /is/ an issue on the live server but not on the private server, it's a bit of an issue

**Comment by FluffyGhoster** [comment]
There's a thunderdome, but devs do not have the ability to spawn things currently, and it wouldn't help much anyways as we cannot halt the server and attach the debugger to investigate whatever fails to work as expected on the live server either

**Comment by LynxSolstice** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/112824777/2cad00e8-c893-4545-8f4f-f83271b7e11a)
It's still broken on live.

**Comment by LynxSolstice** [comment]
What's happening it appears, is that the napalm isn't igniting on release

**Comment by FluffyGhoster** [comment]
Ok so, the test done in the spawn area didn't ignite because it's an unsimulated turf area, that doesn't have air processing (because it's unsimulated), me and @Melariara tried the same grenades on the thunderdome (which is simulated turfs) and both ignited correctly

**Comment by LynxSolstice** [comment]
So is the north side of the engineering hallway just unsimulated?

**Comment by FluffyGhoster** [comment]
I don't know where you are referring to, the interior of the ship is simulated to my knowledge, the exterior is space and doesn't have air to burn with, I think napalm also doesn't work if the air is too cold to ignite it with a hotspot exposure or if it's missing oxygen

**Comment by Butterrobber202** [comment]
I've noticed this sometimes in gameplay as well. A grenade thrown on the ship will, sometimes, just never go off. I believe its localized to chem grenades or pre-made "assembly" grenades, as I've never seen a frag grenade hesitate. Its been an issue for a few years. 

I'm a code idiot, so I'm just speculating, but for pre-mades, besides the actual countdown counting down itself, is the activation of the grenade affected by the tickrate?

**Comment by AlaunusLux** [comment]
It seems like this happens if you hold the grenade until it's meant to go off. Nothing happens- opening a pull request shortly that will make it detonate while being held. 

Could not replicate with cleaner grenade.
