### ISSUE TITLE
[Bug]: 9mm pistol sprite disapears after taking out magazine

### ISSUE THREAD

**Issue by Clem-The-Duck** [Aurorastation/Aurora.3#18089]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

pulled the magazine out of a nine mil pistol that was empty, and the sprite disapeared. apparently happens when you attach/remove surpressors. https://i.gyazo.com/c0cd765981dbc3835bb6adaa4815d376.png

**Comment by NonQueueingMatt** [comment]
this should be fixed now
