### ISSUE TITLE
[Bug]: Dominian LMG/Carbine sprite, magazine issues.

### ISSUE THREAD

**Issue by GladiatorGames123** [Aurorastation/Aurora.3#18116]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

During Matt's Zombie Mini-event we were able to find Dominian equipment such as the Dominian Light Machine Gun and Dominian Carbine. The sprites for the weapons in-hand are currently the wrong way! For example, when your character is facing west with the weapon in-hand, the sprite is actually the east facing one and vice versa. This goes for both weapons and may also apply to other added Dominian firearms.

On top of this, the magazine for the Dominian LMG magazine and gun does not display what caliber it fires (7.62) nor does it have the empty-magazine sprites implemented which were handed over with the weapons sprites. The Dominian carbine's magazine does not have it's empty-mag sprite that was provided.

Edit: Dominian Bolt Action also has sprite issues alongside not having an aim down scope button?

Dominian Service Pistol when empty, turns invisible.

### How to reproduce

Gun issues:
1. Spawn a Dominian Light Machine Gun/Dominian Carbine
2. Look East/West, observe that sprites are not facing the correct direction for either weapon. Unknown if there are other spriting issues, may require further testing whether double-handed sprites are correct or not.

Magazine issues:
1. Spawn a Dominian Light Machine Gun/Dominian Carbine
2. (For Dominian LMG) Remove the magazine, observe that there is no indicator in it's desc for what caliber it is, load magazine, fire till empty, remove magazine, sprite still shows magazine as loaded. (For Dominian Carbine) Fire until empty, remove magazine, sprite still shows magazine as loaded.

### Round ID

crx-dGgl

### Staff ckey

MattAtlas

**Comment by Clem-The-Duck** [comment]
Would like to add to this by saying that it seems to be broken for the right hand? Someone holding it in the left hand seems to have the correct orientation (this was for the dominian LMG)

Also the pistol seems to be missing a sprite when the magazine is released
https://i.gyazo.com/aed355ace4fd21d55569004df0462ac5.png

**Comment by GladiatorGames123** [comment]
Handgun does have a unloaded sprite that was provided, alongside! I wasn't able to do extensive testing as to what was/wasn't broken so that may need to be done by someone else as I don't have the tools for it at the moment.

**Comment by NonQueueingMatt** [comment]
When you give sprites to me to add them, it's generally assumed that you double-checked them and did them correctly. Every single right-handed sprite you gave me is broken.

I'll fix it this time, but know that it's disrespectful of my time to do something like this.

**Comment by NonQueueingMatt** [comment]
> Edit: Dominian Bolt Action also has sprite issues alongside not having an aim down scope button?

There is an Use Scope button.
