### ISSUE TITLE
[Bug]: Integrally suppressed guns have a suppressor added to their sprite

### ISSUE THREAD

**Issue by TheDanseMacabre** [Aurorastation/Aurora.3#18153]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon, Intrepid, Spark, Away Site, Third party ship, Overmap, Event / Other

### Describe the issue

I noticed this while testing a PR of mine recently. This happens to integrally suppressed guns, which currently is only the Tajara silenced pistol. Here's what it looks like, using the gun from my PR as an example.
![image](https://github.com/Aurorastation/Aurora.3/assets/57339900/c11c9c1d-3fc8-480c-a22c-6e79ce0d09b5)
 

### How to reproduce

1. Spawn an integrally suppressed gun
2. Look at the phantom suppressor

**Comment by NonQueueingMatt** [comment]
set the suppressor x/y offsets to null to fix it
