### ISSUE TITLE
Cooking griefs 

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#1815]
1: everything takes way too long to cook. (Nevermind how long it takes to heat the machines)
2: you can set the output of a machine from any distance
3: rolling pins make a knifing noise
4: icons are a bit sketchy (cereal box quickly overpixelates to a huge size, and all of its overlays are off in the corner haphazardly stuck onto one another and in some cases even escaping the box's bounds)
5: consumes fuckton of power, even more than atmospherics.
6: everything takes way too long to cook (From what I can tell, all cooking speeds have been arbitratily increased by 4 times)

@NanakoAC

**Comment by NanakoAC** [comment]
1 and 6
As mentioned in the PR, cooking times are drastically increased as part of a shift to time-management based gameplay, and bulk cooking. Cooking time is also non-optimal until the machine is heated

You can make multiple copies of a recipe at once, and many recipes are spread across several machines. the oven and fryer can make multiple recipes that aren't even the same if you just toss in all the ingredients.

It's asynchronous, time-based gameplay. Manage yourself properly and it works out. Start one thing cooking and then prepare ingredients for the next thing in the meantime. Optimise your workflows

In addition, a scaling mechanic was added to prevent extreme cooking times for massive things.

In general this is working as intended, i'm open to tweaking things a bit, but there won't be massive changes from this design goal. If you want to test and report on any specific recipes that take abnormally long, please do

Machine heating times are approx 15 minutes, this is realistic too and i don't believe its a major issue. Many jobs are about preparation - medical has its cryotubes to cool down every round too

2. Noted, is bug, will fix
3. I don't think i touched that, but there is a possibility i caused it. Could you make a seperate issue with a more specific repro
4. The resizing is based on the quantity of ingredients. The maximum possible size (a scale of 2) requires 8x the normal ingredients. Normal is an author defined value, which maybe should be tweaked for cereal boxes if it's getting big "quickly". The scale of the icon is set to the cube root of total reagents / normal value.
5. High power usage is intended, and the values are based on real world analogues, as many things in the game are.  For example the fryer's power usage is equal to two Vulcan 1ER85D-2 electric fryers.
Ive mentioned many times my plan to increase the power usage of the whole station, this is a part of that. High power usage for cooking is neither unrealistic nor unbelievable - generating heat is one of the least efficient and most expensive things you can do with electricity, whereas the work of atmos is largely pumping. 

I don't think the comparison between the two is particularly meaningful, but i'd say we should look at increasing the power usage of atmospherics 

If the kitchen draining the station at roundstart is a problem, perhaps we could make the civilian east substation enabled by default, so it can't deprive more important areas of power

**Comment by Lohikar** [comment]
There are also a few instances of debug messages being written to world.

**Comment by skull132** [comment]
This is either in dev, or already in master. Nanako needs to learn how to autoclose shit for the love of fuck.
