### ISSUE TITLE
[Bug]: Lava Exoplanets reveal unsimmed asteroid tiles when their Rock tiles are destroyed.

### ISSUE THREAD

**Issue by Aticius** [Aurorastation/Aurora.3#18172]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Away Site

### Describe the issue

Lava Exoplanets have a turf unique to them, Basalt. However, the planet spawns with Simulated versions, whereas the mined tiles become Unsimulated, causing ZAS checks on the simulated tiles when there shouldn't be any. And also for them to be surprisingly non-hostile, due to a lack of their generally hot and unbreathable atmospheres.

This should NOT be fixed until https://github.com/Aurorastation/Aurora.3/issues/18080 is resolved, as it will cause planetary fires if the exoplanet generates with a flammable atmosphere. Potentially forever.

### How to reproduce

1. Generate Lava Exoplanet
2. Break a rock tile
3. Observe your turf/unsimulated/asteroid/basalt
4. no atmosphere

### Staff ckey

Roostercat12

**Comment by FluffyGhoster** [comment]
Fixed with above PR
