### ISSUE TITLE
[Bug]: Access Restricted Hardsuits cannot be hacked

### ISSUE THREAD

**Issue by NobleRow** [Aurorastation/Aurora.3#18188]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When a hardsuit has an access requirement, i.e. the First Responder suit or the Cybersuit, the panel on it cannot be opened to hack it unless the hacker has the required access, which defeats the purpose of hacking it in the first place.

### How to reproduce

Take an access-restricted hardsuit,
Make sure you don't have access to it,
Attempt to open its wiring panel.

### Staff ckey

MattAtlas

**Comment by FluffyGhoster** [comment]
Fixed in https://github.com/Aurorastation/Aurora.3/pull/18804
