### ISSUE TITLE
[Bug]: Joining the server gives a black screen

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#18191]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

Every time I join the main screen is black, so no join/observe etc. fixes after reconnecting

### How to reproduce

1. Join the server
2. See black
3. Relog
4. Fixed?

**Comment by Jasorn** [comment]
?? please? i've confirmed this happens from tons of people including moderators, can someone find out whats causing this, byond makes you wait 30secs every time you join, so having to wait a 1 minute EVERY time is very annoying

**Comment by Acetrea** [comment]
Yeah, this happens to me too. Definitely super annoying.

**Comment by FluffyGhoster** [comment]
Try to clear the byond cache:

![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/f546fff3-178a-4296-9b85-3e2baa4044d8)

**Comment by Jasorn** [comment]
just tried and didn't work, i also tried this at the time of making the bug report too

**Comment by FluffyGhoster** [comment]
This should be resolved now, with #18434
