### ISSUE TITLE
Using The Track Feature as AI Results in Indefinite Hang/High CPU Usage

### ISSUE THREAD

**Issue by Surrealistik** [Aurorastation/Aurora.3#1820]
After roughly 2 hours, 30 minutes into a cult round, trying to use the Track feature would reliably result in massive CPU usage and an indefinite hang of Dreamseeker. 

Not sure what causes this, as this is obviously atypical behaviour relative to normal Track feature functionality, and there was no clear trigger.

**Comment by Lohikar** [comment]
Likely related to #660.
Old-ass bug.

**Comment by Geevies** [comment]
Fixed.
