### ISSUE TITLE
[Bug]: Missing turf icons scattered around

### ISSUE THREAD

**Issue by kyres1** [Aurorastation/Aurora.3#18266]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon, Intrepid, Spark, Away Site, Third party ship, Overmap, Event / Other

### Describe the issue

There's instances of missing turf icons scattered throughout the current map(s) from third parties to CC/antag bases and etc. 

This also creates a crippling issue on Konyang/Point Verdant where there is an utterly huge amount of icons missing for no seeming reason; probably due to some later decal application I'm missing.

It'll look like this;
![image](https://github.com/Aurorastation/Aurora.3/assets/36868890/c13d773a-269f-4233-afa1-35f583b3e888)

### How to reproduce

Your best bet is booting the "Haneunim" system, Jump-To-Area on "Point Verdant - (insert anywhere here)" and looking around. There's a lot of missing textures wherever there isn't grass.

### Round ID

N/A

### Staff ckey

N/A

**Comment by FluffyGhoster** [comment]
This should be fixed in a recent PR I made for the exoplanet turf icons, reopen if it happens again
