### ISSUE TITLE
[Bug]: Hephaestus Exosuit Dock Not Recharging

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#18274]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The Hephaestus Exosuit Dock that's supposed to rapidly recharge exosuits seems to simply not be recharging exosuits at all.

### How to reproduce

1. Construct a Hephaestus Exosuit Dock.
2. Step onto the dock with an Exosuit.

**Comment by Ben10083** [comment]
Did some testing, the recharging dock works still, was the exosuit off when you left it? They don't charge if the power is off

**Comment by furrycactus** [comment]
I had stepped onto the dock while the exosuit was active. If it's not able to be replicated, it potentially could've been an issue with lag then.
