### ISSUE TITLE
[Bug]: Medical Records App Does Not Show Notes

### ISSUE THREAD

**Issue by Acetrea** [Aurorastation/Aurora.3#18342]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

On the Medical Records App, notes are not shown. You have to print out the paper to see the notes. (Or examine someone and view Medical Records)

### How to reproduce

1. Open Medical Records App (on either a computer or a PDA)
2. Click on a person who has Medical Records.
3. See that these notes are not shown.
4. Print out the Medical Records
5. They appear on the paper.

**Comment by NonQueueingMatt** [comment]
Records work fine, make sure to click the button with the appropriate record in the top bar under their name. Like this one:
![image](https://github.com/Aurorastation/Aurora.3/assets/13016572/3477edd5-3715-4dcb-b7f0-d15b67aa55c8)
