### ISSUE TITLE
[Bug]:  Vampire thralls get the set-ambition verb but it doesnt work.

### ISSUE THREAD

**Issue by Warbidon** [Aurorastation/Aurora.3#18354]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Getting Vamp Thralled gives you the set-ambition verb, but it does nothing when entered.
Either remove the verb or make it work?

### How to reproduce

1. become vampire thral
2. try to set ambition
3. doesnt work

### Round ID

dont remember

### Staff ckey

N/A

**Comment by Sniblet** [comment]
It doesn't work for any antag
