### ISSUE TITLE
[Bug]: Accessories section of the loadout is empty

### ISSUE THREAD

**Issue by LeiteQualhado** [Aurorastation/Aurora.3#18375]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

Pretty much what the tittle says, i asked in ooc if other's had it and they said yes

![image](https://github.com/Aurorastation/Aurora.3/assets/51837452/c3c98e73-1ef6-4f75-943a-5a88dd5a09aa)

### How to reproduce

Simply open the loadout and head to the section

### Round ID

csa-dlMk

### Staff ckey

N/A

**Comment by FluffyGhoster** [comment]
Fixed with the updated testmerge
