### ISSUE TITLE
[Bug]: Directly click on anything, with an item in hand, causes an attack message to appear.

### ISSUE THREAD

**Issue by Aticius** [Aurorastation/Aurora.3#18376]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Caused by https://github.com/Aurorastation/Aurora.3/pull/18365.

Additionally causes weird behavior with bags and labellers, causing you to label the bag, rather than put it in the bag.

### How to reproduce

1. Hold an item.
2. Use this item on another item (i.e. Put an item in your bag, attach an accessory to a piece of clothing you're wearing, pour reagents into a beaker or other container from a seperate container, assemble or disassemble a KA)
3. Observe attack log.

For labeller weirdness specifically,
1. Set a labeller's text to something valid (maybe also works invalid?)
2. Attempt to place it inside your bag by directly clicking on the bag. (Maybe also works if placed directly into the inventory section?)
3. Label the bag.

### Round ID

csa-dIFf

### Staff ckey

sadkermit

**Comment by FluffyGhoster** [comment]
>Additionally causes weird behavior with bags and labellers, causing you to label the bag, rather than put it in the bag.
Please fill the how to reproduce for this

**Comment by Aticius** [comment]
> Please fill the how to reproduce for this

Whoop. Sorry.

**Comment by FluffyGhoster** [comment]
Ok, that is how it worked before too, I just tested on master, so, not a bug

The message one is solved
