### ISSUE TITLE
[Bug]: The Trinary Perfection Veil is no longer in the loadout menu.

### ISSUE THREAD

**Issue by NobleRow** [Aurorastation/Aurora.3#18400]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The Trinary Perfection Veil is no longer in the loadout menu. It should be in the Religion section.

### How to reproduce

Go to the loadout menu religion section. It is not there.

**Comment by FluffyGhoster** [comment]
Type path or exact name of this?

**Comment by NobleRow** [comment]
> Type path or exact name of this?

Whoops. I can't pull a type path right now but the actual name is Trinary Perfection Mask

**Comment by FluffyGhoster** [comment]
Already fixed in the latest commit of #18365 then
