### ISSUE TITLE
[Bug]: Mining satchel attempts to grab EVERY item now

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#18413]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

It spams the chat with "cannot hold the X" and "fail to pick anything up" etc.
![image](https://github.com/Aurorastation/Aurora.3/assets/5076069/b822025b-5eac-43c1-a4bd-8c09a6e9b2b4)
![image](https://github.com/Aurorastation/Aurora.3/assets/5076069/daf494ee-da62-47eb-b1a9-4453580ebab3)

This was after walking over the warehouse items on the floor

### How to reproduce

1. Have mining satchel
2. Walk over any item
3. See it fills chat with it trying to snatch it up

**Comment by FluffyGhoster** [comment]
It always tried to grab everything, it's just that it didn't print the message when doing so before

**Comment by Jasorn** [comment]
> It always tried to grab everything, it's just that it didn't print the message when doing so before

ok, can we make it NOT spam chat anymore?

**Comment by FluffyGhoster** [comment]
I have fixed this in one of the PRs I made that I can't find anymore, so unless it picks up something or you click the turf, this shouldn't happen anymore

**Comment by Jasorn** [comment]
just played miner today, it still does it, including trying to "pick up" things like intercoms

**Comment by FluffyGhoster** [comment]
Steps to reproduce?

**Comment by Jasorn** [comment]
have a mining satchel in your hand/belt/pocket and walk around the ship, any item will spam your chat about failing to pick it up, including objects like intercoms on walls

it only should give you a message when the bag is full in regards to picking up ore and nothing else

**Comment by FluffyGhoster** [comment]
It occurred to me that I never made the PR after writing it, that's why it's still doing it
