### ISSUE TITLE
[Bug]: Spawning in Residential Lifts at round start.

### ISSUE THREAD

**Issue by Fyshen** [Aurorastation/Aurora.3#18426]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

While playing as a investigator, I have consistently spawned at the residential lifts at round start, when I should start in the Security meeting room. I notice the room has had a minor design, perhaps the spawn point was removed during this and it defaults to the chosen spawn point (my chosen point is the Lift)

### How to reproduce

1. Select Investigator during pre-game lobby.
2. Spawn in the Residential Lift.
3. Be confused.

**Comment by Fyshen** [comment]
After some other rounds, it seems this _does_ happen to others exactly the same.

**Comment by RandomBeaver5** [comment]
This happened to me once. But i spawned in as my warden.
