### ISSUE TITLE
Apple Slices!

### ISSUE THREAD

**Issue by ariever** [Aurorastation/Aurora.3#1842]
So, apples. One, you eat them in one bite, which is a little not realistic (not that im complaining).
But the other thing is, that when you cut one and try to eat the apple slices, you can't. It dissapears out of your hand with the "None of the apple slice left!" text. I think its because apples already don't provide much food wise, and cutting it into fifths would make it into such a small decimal that it doesn't register as anything being there to eat.

I want the apple slices to be able to be eaten normally, please, maybe change the amount of apple inside them?

**Comment by NanakoAC** [comment]
fixed by #1897
