### ISSUE TITLE
[Bug]: KAF Rifles are pointing the wrong way

### ISSUE THREAD

**Issue by CometBlaze** [Aurorastation/Aurora.3#18458]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

Where is he aiming at? Not even he knows...
![image](https://github.com/Aurorastation/Aurora.3/assets/59415394/71590371-2e80-4a3d-9a5a-b2085d14fd15)

### How to reproduce

Equip KAF Rifle
Wield KAF Rifle
Verify your character skipped boot camp

### Round ID

csk-dhzq

**Comment by FluffyGhoster** [comment]
I think this was fixed already, can you verify?

**Comment by FluffyGhoster** [comment]
Perfect, thank you for the check!
