### ISSUE TITLE
[Bug]: Meat Ravioli Recipie doesn't fire

### ISSUE THREAD

**Issue by Eihort80** [Aurorastation/Aurora.3#18451]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Tried 4 times to make the Meat Ravioli recipe and it never worked correctly. Been doing Chef for a bit now, so pretty sure I had it right. Just produced pan fried dough slices and tomato.

### How to reproduce

Follow the recipe on the wiki.
<img width="265" alt="image" src="https://github.com/Aurorastation/Aurora.3/assets/160375289/4d50dde7-5a4e-454a-aebb-f24b470f05ca">
Use the grinder and then the condiment maker to seperate the animal protien from cutlets and add to pan.

**Comment by SleepyGemmy** [comment]
it's made in a saucepan or pot, not a skillet. i'll let the wiki team know.
