### ISSUE TITLE
[Bug]: Ghost role spawner menu NtOS crashes when all slots full?

### ISSUE THREAD

**Issue by Clem-The-Duck** [Aurorastation/Aurora.3#18471]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon, Third party ship, Overmap

### Describe the issue

https://gyazo.com/41c886469bb19ff810e07e512ff8f00c

Apparently after all ghost spawner slots were taken the ghost spawner menu stopped working, just giving the NtOS error of "unable to get property 'filter' of undefined or null reference

### Round ID

csl-dmsK

**Comment by Sniblet** [comment]
Happened again the following round, csm-akXj
A little while after the last external ghostrole was taken, it stopped working for at least two and possibly all ghosts. Maintenance drones were still available, posibrains were made available shortly after the bluescreen but it didn't recover.
![bsod](https://github.com/Aurorastation/Aurora.3/assets/36427443/fc437be6-1a56-4424-bc02-63e64e9dbc4b)
