### ISSUE TITLE
[Bug]: Grass rustling sound is overly loud

### ISSUE THREAD

**Issue by Greenjoe12345** [Aurorastation/Aurora.3#18476]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Away Site

### Describe the issue

The sound of walking through tall grass on Konyang seems quite a bit too loud.

### How to reproduce

Walk through tall grass.

**Comment by FluffyGhoster** [comment]
Note that this is not a bug and should have been made as a feedback thread instead, anyhow, I put up a PR that addresses this
