### ISSUE TITLE
Atmos. Apprentice Falls Under Misc. Category on Manifest

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#18470]
should be under engineering.

![image](https://github.com/Aurorastation/Aurora.3/assets/99297919/b700619e-6790-46ab-86a2-6caa0cdfa971)

**Comment by Snowy1237** [comment]
I have seen this in-game too, I am also pretty sure this has something to do with ID modification and job changes, not the bot.

**Comment by SleepyGemmy** [comment]
thanks for letting me know!
