### ISSUE TITLE
The new(ish) brig machines don't let you account for time spent in processing

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1847]
So this strikes me as dumb enough to be an issue.

The way our brig processing machines currently work is you bring a guy in, insert his ID in the thing, and then apply charges, witness ID's, and incident summary, or just the guy's ID and charges if you want.

Now, you can also set the time to be spent in the cell, how much or less you can set it depends on the charges you've given.

Now this can be a problem, because, due to how the whole system works, with the swiping ID, picking out the charges, typing in an incident summary if you're goodsec, etcetera, you're bound to rack up a few minutes in processing, and unfortunately the machine doesn't let you account for this, this tends to stand out very much if you're managing yellow/low level infractions.

If security wants to keep someone around in the brig for a shorter-than-appropriate time, then they can do that _anyway_, I don't think ignoring processing time should be encouraged by painful mechanics.

**Comment by Geevies** [comment]
Server culture at this stage.
