### ISSUE TITLE
[Bug]: blowing a hole in the konyang outpost vents the planet

### ISSUE THREAD

**Issue by Greenjoe12345** [Aurorastation/Aurora.3#18482]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Away Site

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/33647525/08ef411e-29a1-4d8c-a307-feabd83420ec)
the outpost was blown up, it blew a hole into space which quickly vented the entire z level.

### How to reproduce

blow up the outpost.

**Comment by FluffyGhoster** [comment]
This should be solved with #18399 
Can you check?

**Comment by FluffyGhoster** [comment]
Reopen if still relevant, but should be fixed
