### ISSUE TITLE
When Overdose Threshold is Passed, Damage From OD Persists Even Beneath OD Threshold

### ISSUE THREAD

**Issue by Surrealistik** [Aurorastation/Aurora.3#1850]
If you break the OD threshold for any chemical in your bloodstream, you will keep taking overdose damage as that chemical metabolizes, even when it falls beneath its OD threshold until that chemical is entirely purged.

**Comment by skull132** [comment]
Technically intended effect because Bay's chemical system was updated to be really weird. It only deals with the amount of chemicals you have "metabolized", that is, ticked away. PR #3116 fixed this, so chemicals work as expected now.
