### ISSUE TITLE
[Bug]: South Industrial Smelter in Mining will DELETE ore, and not process it or connect to a console

### ISSUE THREAD

**Issue by Somguy2** [Aurorastation/Aurora.3#18510]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The lower conveyer belt for processing ore does not work.
I loaded a large amount of materials into it, and the console for ore redemption did not update to include any of the newly added materials, toggling the processor for 'enabled' also did nothing.
I then deconstructed the smelter to try and get the materials back, I did not get them back at all. 

Trying with the northern processor, I found it's corresponding ore redemption console did work, and could toggle it's processor. so at least both are not broken.

### How to reproduce

Load ore into the southern ore processor using the conveyer belt
Attempt to program it/turn it on.
Realize ore is entering it, but the console is not updating
Deconstruct the ore processor which should have ore in it
recieve no ore.

### Round ID

csp-aPIk

### Staff ckey

TheBurninSherman

**Comment by Nalarac** [comment]
Current workaround I found: If you screwdriver + crowbar the Ore Redemption Console (to pop out the components and board) and then reassemble it, it'll properly link to the smelter. Any ore put into the smelter beforehand isn't actually deleted and will now show on the redemption console.

**Comment by FluffyGhoster** [comment]
This should be resolved with the above PR, reopen if it happens again
