### ISSUE TITLE
AI can't speak Sol Common, tradeband or gutter.

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#1852]
Makes no sense as they don't use any limbs or other appendages to be able to speak

**Comment by LordFowl** [comment]
AI cannot speak any language but TCB, binary, and more recently EAL. It is not a matter of lacking limbs, as both the pAI and the universal translator do not needs limbs to speak and understand. It is since a design choice.

**Comment by skull132** [comment]
Not a bug.
