### ISSUE TITLE
[Bug]: Attempting to cancel ghost role setup results in advancing it, instead

### ISSUE THREAD

**Issue by Aticius** [Aurorastation/Aurora.3#18541]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Away Site, Third party ship

### Describe the issue

While joining a ghost role, you are prompted for several inputs. Attempting to cancel one simply results in you going to the next step, eventually spawning (when you'd rather not!)

### How to reproduce

1. Start joining a ghost role
2. Cancel on the last prompt
3. Spawn, despite your best efforts.

### Round ID

css-bXyD

### Staff ckey

Melariara

**Comment by SleepyGemmy** [comment]
not a bug.
once you click the spawn button you have claimed that role. don't click it unless you're certain.

**Comment by Aticius** [comment]
> not a bug. once you click the spawn button you have claimed that role. don't click it unless you're certain.

This is an issue if you misclick a button and fail to input any information that's important, (I.E. Name)

**Comment by SleepyGemmy** [comment]
> This is an issue if you misclick a button and fail to input any information that's important, (I.E. Name)

you can enter cryo and rejoin the role.
