### ISSUE TITLE
[Bug]: Point Verdant .45 fast loaders have 30 instead of 6 bullets in them, sprite doesnt change when empty, sprite shows rubber bullets opposed to lethal bullets.

### ISSUE THREAD

**Issue by shimmeristaken** [Aurorastation/Aurora.3#18562]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Away Site

### Describe the issue

Exactly as it says in the title. The fast loaders are a bullet bag of holding, capable of storing far more ammunition than reasonable. Furthermore, they dont change sprites when empty, and also show rubber bullet tips despite the ammo seemingly being lethal.

![image](https://github.com/Aurorastation/Aurora.3/assets/144547020/483f80f9-27ff-4772-a9cc-92fbbddfdcb4)

### How to reproduce

1. Spawn as cop
2. Go to the ready room
3. Pick up a fastloader
4. Congrats, you have enough ammunition to conquer a small nation.

**Comment by Ben10083** [comment]
PR up that can fix this, but the bullet tip things appear intended, at least for now.
