### ISSUE TITLE
[Bug]: First (and presumably second) Transfer votes no longer require 2/3rds majority to call for round-end.

### ISSUE THREAD

**Issue by Aticius** [Aurorastation/Aurora.3#18569]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

Caused by: https://github.com/Aurorastation/Aurora.3/pull/18563

The first and second transfer votes called in any given round require a 2/3rds majority to end the round, under the old voting system. This is no longer the case.

### How to reproduce

1. Call a Transfer Vote
2. Have "Initiate Crew Transfer" win by a single vote
3. Become the enemy of RP.

### Round ID

round before csu-dafl

**Comment by FluffyGhoster** [comment]
This should be fixed, reopen if not
