### ISSUE TITLE
[Bug]: Crew Transfer button appears to be broken

### ISSUE THREAD

**Issue by Triogenix** [Aurorastation/Aurora.3#18566]
![Screenshot_563](https://github.com/Aurorastation/Aurora.3/assets/73185699/95f08abd-492e-47ea-a7dc-114db30cfbc4)
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

Clicking the crew transfer button does not start a vote for the crew transfer past the two hour mark.

### How to reproduce

Go into the game without developer or admin privileges, and attempt to start a crew transfer.

### Round ID

csu-aKlw

**Comment by zagoon** [comment]
Additional info: 'without developer or admin privileges' seems to be important since Campin was able to call a transfer in the round prior.
