### ISSUE TITLE
[Bug]: KASF Corvette spawn weight set to 0.5 Haneium, not 1.5

### ISSUE THREAD

**Issue by mynameasjeff** [Aurorastation/Aurora.3#18580]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

What it says on the tin, PR #18501 seems to have inadvertendly made the spawn rarer, not more common.

### How to reproduce

1. Join game lobby at roundstart
2. Click to display all available ghostroles
3. Find the Corvette.

**Comment by lavillastrangiato** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/8a89807b-b760-4a28-be14-481c37bd3769)
![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/326f5bcd-1cf1-4bbb-9ca0-87d788fd4218)
It looks like the Coalition sectors take priority over the Haneunim sector, as Haneunim is a Coalition sector.
