### ISSUE TITLE
Slimes no longer recognize being fed by monkeys and attack regardless

### ISSUE THREAD

**Issue by hungryman52** [Aurorastation/Aurora.3#1858]
"Soak a monkey cube in water and feed it to the slime by putting the monkey in the disposal. Engage the disposal and maintain line of sight to the slime while it eats the monkey. This will ensure the slime and further ones that come from it will not try to eat you, as you will be in their "friend" list (this list is also copied down to slimes that are born from it)."

this is a bullet point from xenobiology wiki from baystation. I understand that this is aurorastation and things may be different, but can we please make these slimes less agressive. I used to tend slimes in the old Aurora Station and never once got bitten as long as I kept them fed, not only that, but slimes used to take 2 monkeys to make them split, now they only take one monkey no matter how long you starve them. Now I get attacked by baby slimes right after I have fed them and they have split. As stupid as this may sound I even tried hugging the slimes before they split to make it so that they would be friendly with me after they had split. Of course it didn't work. this was posted 2/28/2017, I don't know if this has been updated since then.

Thank you for your time reading this and I hope, it wasn't too long or tedious to read. Maybe I just had a couple of unlucky sessions, but still I feel that the slimes are way too aggressive right now. I do however like their new animated faces and the way they now also talk to each-other.
Anyway like I said I am not sure if this is a bug or a feature, but on day 28 I definitely had this problem multiple times and as I said previously I have tended slimes before and was well able to harvest and control them without any issue.

**Comment by hungryman52** [comment]
"Soak a monkey cube in water and feed it to the slime by putting the monkey in the disposal. Engage the disposal and maintain line of sight to the slime while it eats the monkey. This will ensure the slime and further ones that come from it will not try to eat you, as you will be in their "friend" list (this list is also copied down to slimes that are born from it)." this is a bullet point from xenobiology wiki from baystation. I understand that this is aurorastation and things may be different, but can we please make these slimes less agressive. I used to tend slimes in the old Aurora Station and never once got bitten as long as I kept them fed, not only that, but slimes used to take 2 monkeys to make them split, now they only take one monkey no matter how long you starve them. Now I get attacked by baby slimes right after I have fed them and they have split. As stupid as this may sound I even tried hugging the slimes before they split to make it so that they would be friendly with me after they had split. Of course it didn't work. this was posted 2/28/2017, I don't know if this has been updated since then. 
Thank you for your time reading this and I hope, it wasn't too long or tedious to read. Maybe I just had a couple of unlucky sessions, but still I feel that the slimes are way too aggressive right now. I do however like their new animated faces and the way they now also talk to each-other.
Anyway like I said I am not sure if this is a bug or a feature, but on day 28 I definitely had this problem multiple times and as I said previously I have tended slimes before and was well able to harvest and control them without any issue.

**Comment by OneOneThreeEight** [comment]
I am not sure if adding a comment to this bumps it to the top but I'm going to try anyway.

This issue makes wrangling and cultivating slimes so utterly broken that it is not worth even playing xenobio because of it. Slimes are aggressive to anyone that is not a slime person or fellow slime. It is ridiculous.

**Comment by SirFruitcakes** [comment]
This isn't new. Even on Old Baymerge it was like this. You're probably doing something wrong, like wearing your bio-suit while feeding the Slimes. That obscures who you are and makes the Slimes not recognise you. If you join late you also have to feed them twice, once to sate their hunger and another to befriend them. You have to do it to the same Slime, so have two Monkeys ready. Once to make it grow to an Adult, another for it to eat while as an Adult. Then it'll split after it's done and they should be friendly, note; It's still safer to get them to answer you, if that's not still broken.

**Comment by xTrainx** [comment]
I have been this trouble with slimes lately, i have gone 3 whole shift without being able to befriend a single slime, even after feeding them twice, with no bio suit on, i have tried standing inside the cage, betwen the airlock and all the way outside the cage, all without breaking visual line of sight, but nothing seemed to work. most of the shift ended with me dead, or me going to cryo.

**Comment by hungryman52** [comment]
@SirFruitcakes As I said in the original posting i know how to tend slimes, they are not behaving the way they are meant to.

**Comment by xTrainx** [comment]
after some messing around, i have found out that slimes do befriend if you dont just throw the monkey in, but rather put him into the disposal unil while you grab on him with grab intent, maybe it's because they have to aggro the monkey first. Also better chances to befriend if you throw a second monkey the same way, with grab intent. In short, i have been able to tame slimes after changing tactics a bit

**Comment by Dunkhan** [comment]
Confirming this bug. Also confirming the workaround with the grab intent
I am still experimenting with details but I will update here when I know more

**Comment by Geevies** [comment]
Fixed.
