### ISSUE TITLE
AI's can't read papers partially from a distance anymore

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#1859]
You just can't read them anymore.
Don't know if it is an oversight or by new design.
Also noticed this with borgs.

**Comment by SierraKomodo** [comment]
May have been intended, as that was easily abusable by constantly refreshing the half-displayed paper to piece together the letters and read the paper.

**Comment by Geevies** [comment]
Hold up a paper to a camera, the AI will be able to read that.
