### ISSUE TITLE
Cannot lift samples of dried blood

### ISSUE THREAD

**Issue by Serveris** [Aurorastation/Aurora.3#186]
Forensics cannot swab dried blood for DNA samples using a swab kit. This was corrected in oldcode.

**Comment by skull132** [comment]
Tested this on the server, and was unable to replicate it. Picked up DNA from a spot of dried blood just fine.

What might have happened is that the blood's `blood_DNA` var was null for whatever reason. this can happen, for example, whenever admin spawned or special spawned mobs are involved. Said mobs lack a DNA pattern.

**Comment by skull132** [comment]
Bad report, the second one is more accurate. Closing this.
