### ISSUE TITLE
Blobs

### ISSUE THREAD

**Issue by CompleteGarbage** [Aurorastation/Aurora.3#1861]
**The issue:**

- While infrequent, blobs have a massive destructive potential.
- They often cause breaches spanning the majority of one or more departments.
- Even with interdepartmental coordination, response, and suppression, they often do massive damage before they can be put down.
- Most viable counters have massive potential for collateral damage themselves, and take too long to set up.
- Even using most or all available counters, blobs tend to do a considerable amount of damage before counters prove effective.
- Blobs will often cause damage to critical machinery that is impossible, expensive, or difficult to replace.
- Blobs will often cause advanced damage (fractures, etc.) or death to players.
- Blobs have too-high of a potential to irreparably damage a round's natural course, and to end rounds for multiple players.
     _No other event (with possible exception to meteor storm-- but shields can very easily counter those) has nearly this much quantifiable potential for nearly-unavoidable damage._

**Proposed possible solutions:**

- Decrease the damage blobs do to structures and/or mobs.
- Decrease the rate at which blobs spread.
- Decrease the rate at which the blob can manufacture small-cores.
- Decrease the blob's resistance to damage.
- Implement preventative measures that can lessen the severity of blobs that do occur.
- Increase the effectiveness of current counters.
- Implement additional viable counters to the blob that are an improvement on current counters.

These are the issues with the blob event as I see them, and also several possible solutions I saw. I ask that the development team consider the current balance of blobs, and reach a consensus that benefits the server.
_(Please label this issue as not-a-bug and refactor.)_

**Comment by LordFowl** [comment]
Note that the github is not meant for suggestions of significance. A thread like this better belongs in the suggestions subforums.

**Comment by CompleteGarbage** [comment]
Understood, I'll relocate. Please close.
