### ISSUE TITLE
[Bug]: Signallers & Proximity Sensors (and probably others) do not behave as expected

### ISSUE THREAD

**Issue by Aticius** [Aurorastation/Aurora.3#18612]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

This is a bit broad, but I get the feeling that this is a larger issue than one thing.
Attempting to disassemble an Assembly (the combination of two device objects) with a Signaller and a Proximity sensor results in both objects being deleted, rather than put down at your feet. Additionally, trying to use the Signaller-Proximity assembly brings up no menu, when it should bring up the menu for the Proximity sensor.

This bug probably has some overlap with the occasional chemical grenade weirdness, given their similarities, but that's just a guess.

### How to reproduce

1. Acquire: x1 Signaller, x1 Proximity Sensor
2. use a Screwdriver to prepare a Signaller and Proximity sensor, then put them together.
3. Use the assembly in hand while not secure to take it apart
4. No items are dropped, when they should be.

### Round ID

Round before csC-apBp

**Comment by FluffyGhoster** [comment]
Closing in favor of #18785 - The linked PR to that should solve this too
