### ISSUE TITLE
[Bug]: Sometimes ghost spawner UIs just break

### ISSUE THREAD

**Issue by lavillastrangiato** [Aurorastation/Aurora.3#18615]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon, Event / Other

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/63124803/1055c7a5-b5fd-4216-8356-66bcb427acc2)

### How to reproduce

1. Click the "ghost spawner" option in the Ghost tab.
2. Get this screen.
3. Or, click "Join" then select "ghost spawners" in the setup screen.

### Round ID

csD-afXz

**Comment by FluffyGhoster** [comment]
This should have been fixed by Dreamy recently, reopen if it happens again
