### ISSUE TITLE
[Bug]: Cleaning Bots either do not work on the bridge or cannot detect flour

### ISSUE THREAD

**Issue by courierbravo** [Aurorastation/Aurora.3#18637]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The cleaning bots manufactured in the machine shop are not able to either A. Work on the bridge. or B. detect and clean flour.
I could not tell which in the moment.

### How to reproduce

1. Have scrubbers spill flour in bridge lobby (next to captains office)
2. Bring by cleaning bot
3. pain

### Round ID

csG-akcX

**Comment by zagoon** [comment]
Yeah, cleanbots don't seem to detect flour in my experience as someone who sets them out to clean fairly often.

**Comment by FluffyGhoster** [comment]
This should be fixed now, can you check?

**Comment by FluffyGhoster** [comment]
Closing as stale, open a new one if there's still an issue with this
