### ISSUE TITLE
[Bug]: Getting headbutt (by a Unathi?) as Vaurca sometimes liquifies your socket/organs

### ISSUE THREAD

**Issue by dessysalta** [Aurorastation/Aurora.3#18646]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

If you get headbutt as a Vaurca warrior by a Unathi, some sort of weird BS happens that's probably related to the bone system and internal organs. What happened to me specifically is I was stunned on the ground for a second, then got up and was completely fine save for minor pain. I walked to a vending machine to get a K'ois bar, took one bite of it, suddenly had my neural socket destroyed (_Your mind suddenly grows dark as the unity of the Hive is torn from you._), went blind, couldn't walk, was stuttering and couldn't breathe, and went from 100% BA to 0% in literally thirty seconds.

This was the result of a single headbutt. Nothing in the stomach (aside from some k'ois), and the only treatment immediately after was inap and perco.
![image](https://github.com/Aurorastation/Aurora.3/assets/117083785/23b19d71-6094-4425-b072-044c29c7a1c0)

### How to reproduce

1. Play as a Vaurca warrior.
2. Piss off a Unathi such that they headbutt you.
3. Walk around, maybe get some inap and perconol from a doctor, suddenly fall over and die.

### Round ID

csH-aXWi

**Comment by Sniblet** [comment]
This story lines up exactly with how my testing went. Vaurca's toxmod being what it is, you go blind and hive-deaf instantly upon taking a bite of a k'ois bar, and will die within 30 seconds.
Fun cool fact: a bulwark goes braindead in UNDER A SECOND. No pain message, no heart stopping, no time to take a second bite.

**Comment by Sniblet** [comment]
#18647
