### ISSUE TITLE
Readme and copying files still say Baystation instead of Aurora.

### ISSUE THREAD

**Issue by NullSnapshot** [Aurorastation/Aurora.3#1865]
https://github.com/Aurorastation/Aurora.3/blob/master/COPYING

https://github.com/Aurorastation/Aurora.3/blob/master/README.md

your readme still also links to our website, irc, and github. Just giving you guys a heads up.

EDIT: I also can't spell.

**Comment by skull132** [comment]
Fixed in #1832 and development branch.

**Comment by skull132** [comment]
And addressed in master as well!
