### ISSUE TITLE
[Bug]: Cleanbot Patrol Function no longer works

### ISSUE THREAD

**Issue by NobleRow** [Aurorastation/Aurora.3#18667]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The cleanbot, no matter if it is on idle or on patrol, will not move, and only clean the tile it is manually placed on, defeating its purpose. This is just standard walking grime too, nothing fancy.
![Screenshot 2024-03-15 004630](https://github.com/Aurorastation/Aurora.3/assets/137841920/e5155adc-be98-4c16-a7f4-f3cc1ad68453)
![Screenshot 2024-03-15 004648](https://github.com/Aurorastation/Aurora.3/assets/137841920/00ecc432-8975-430f-b48f-48ab95f02faf)
![Screenshot 2024-03-15 004659](https://github.com/Aurorastation/Aurora.3/assets/137841920/55da0678-16cd-4c4e-90e1-b971608df3dd)

### How to reproduce

1. Take the cleanbot to grime.
2. Turn it on.
3. See it not move past where it stands.

**Comment by FluffyGhoster** [comment]
Actually I think I found a way to reproduce it, it happens when it sees a cleanable that it can't reach, and that's because I forgot to swap a var in the ignore logic

**Comment by NobleRow** [comment]
Oh sick, I've been keeping an eye out for that same type of grime from the scrubbers but it hasn't come up yet.

**Comment by FluffyGhoster** [comment]
Now it should be properly working, can you check?
