### ISSUE TITLE
[Bug]: It is impossible to hack any hardsuit with a multitool/screwdriver.

### ISSUE THREAD

**Issue by N-Komaeda** [Aurorastation/Aurora.3#18663]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

It is not possible to access the wires to hack a hardsuit module. It does not matter if you have a mapped one (CE suit), admin-spawned one (Breacher suit) or built suit (Hazard suit) - the only screen that pops up is the one that says there are 'tamper-resistant' wires installed.

I suspect #18188  faced the similar issue, but this has been tested on hardsuits where the hacker has definitive access.

![image](https://github.com/Aurorastation/Aurora.3/assets/78905387/41b487dc-352b-4f07-856a-2e208b73a6a6)

### How to reproduce

Grab any hardsuit module.
Open the hardsuit by ID/Crowbar.
Press a multitool/screwdriver to the module.
Fail to get the wires shown.

**Comment by FluffyGhoster** [comment]
This sounds expected? If they are tamper resistant, you can't hack them, it sounds like the point to me (?)

**Comment by N-Komaeda** [comment]
I've been informed that the 'tamper-resistant' does not refer to the ability to hack them, but to the randomisation of the wiring. Just like with higher-security airlocks. Hacking a hardsuit module is straight up impossible, even with a cryptographic sequencer, as it just shorts out the access lock. You do not get to modify the wires inside.
Furthermore, multiple people have told me they _have_ done it before. I wasn't there during that, though, and I don't know what may have changed this.
