### ISSUE TITLE
[Bug]: Crew Transfer Votes do not obey 2/3rds majority when majority is in effect (again)

### ISSUE THREAD

**Issue by Aticius** [Aurorastation/Aurora.3#18669]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

I may have missed some button to reopen the original issue, here: https://github.com/Aurorastation/Aurora.3/issues/18569

Reopened because it appears to still be the case.

### How to reproduce

1. Start a Vote
2. Have the vote be 3 for, 2 against (60%, 40%)
3. Crew transfer initiates.

### Round ID

csK-b38v

**Comment by FluffyGhoster** [comment]
It's 2/3rd **majority**, not 2/3rd **total**, approximated as 0.67 weight factor

3*0.67 = 2.01

2.01 is higher than 2, the vote passed

**Comment by listerla** [comment]
As discussed on Discord, a 2/3rds majority would mean that a 3-2 vote would fail; under the current math, in fact, 18-12 would transfer, which is also less than a 2/3rds majority. Either the behavior or the language are wrong.
