### ISSUE TITLE
[Bug]:  Extreme speed boost from coffee for a short time after drinking

### ISSUE THREAD

**Issue by Pedantic11** [Aurorastation/Aurora.3#18681]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Simple one here: When drinking coffee, any kind, the sprite's speed seems to jump incredibly high for a short period of time. Really exhausting to do this, but its competing with hyperzine for sheer velocity. Somewhat balanced by the fact it lasts about four seconds, but still weird.

### How to reproduce

Drink either flat white or standard coffee. Haven't tested with  other drinks, but could reliably hit extreme speeds even when starving with this method.

### Round ID

csM-deYr

**Comment by Jasorn** [comment]
this effect only happens if your character is experiencing a slowdown, if you're just default speed seems like nothing happens

this is from my testing though a while back ex: wearing a hardsuit/voidsuit/duffelbag

**Comment by Pedantic11** [comment]
Something I've found is that it doesn't update immediately: If I'm not moving for a half second, it seems to start. Also, different types of coffees SEEM to stack, but I don't have a way to measure.

**Comment by SleepyGemmy** [comment]
coffee speed boost is intended. is this more than what you think is normal?

**Comment by SleepyGemmy** [comment]
coffee speed boost is intended. closing as feature.
