### ISSUE TITLE
Research Outpost Atmospherics Computer Is Missing

### ISSUE THREAD

**Issue by Aurum22** [Aurorastation/Aurora.3#1869]
The research outpost room designed for testing anomalies has three small rooms which can have various gasses pumped in an out. There used to be a laptop on the table which let you control the vents and scrubbers of the room, but I believe it is missing now as a result of the computer update.
![ejwvwlsohcamamc7cacqshl4g4iejdosqpfjs3ffbgy-6umxwtuu0syksb0jc9_0eo6pfl2z61vso4bofemssxm_c8kay5fgvy-liwetoodggp_in8pztsajgydo4pd0o6q-pwv_ivg](https://cloud.githubusercontent.com/assets/20033434/23539090/bdc7ca3a-ffa6-11e6-9e94-6747c7b464df.png)

Also, there is no wrench anywhere on the research outpost. It would be a convenient addition.

**Comment by skull132** [comment]
No longer exodus, invalid.
