### ISSUE TITLE
[Bug]: Expedition frequency doesn't have proper chat tag or color

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#18695]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Spark

### Describe the issue

The expedition frequency used to be a dark purple color and state [Expedition] instead of [144.5] as seen below

![image](https://github.com/Aurorastation/Aurora.3/assets/8042031/a55ada19-9526-4c99-b859-60311fee6e1e)

### How to reproduce

1.) Get a shortwave radio
2.) Set radio to 144.5
3.) Speak into radio

### Round ID

csO-c12C

**Comment by FluffyGhoster** [comment]
144.5 is not the expedition radio currently, it's the frequency of the navbeacons (that was reused without us noticing when the expedition frequencies were added), is is currently set to 148.7

**Comment by Nalarac** [comment]
I only looked at master without realizing that your bot test merge had touched the frequencies. This is a non-issue then.
