### ISSUE TITLE
Users in Lobby Can Hear People Spawn

### ISSUE THREAD

**Issue by SleepyGemmy** [Aurorastation/Aurora.3#18758]
title.

**Comment by FluffyGhoster** [comment]
I have reduced the sound range of the equipments to avoid it reaching the fake mob lobby area, what sound is it that you hear when people spawn?

**Comment by SleepyGemmy** [comment]
i can hear the equip sounds of items when people join the round.

**Comment by FluffyGhoster** [comment]
#18760 should cover this one, apparently for some god foresaken reason we play a sound when the clothing icon gets updated

**Comment by FluffyGhoster** [comment]
Between the various changes, I can't hear any occurrence anymore, hence closing as resolved, feel free to reopen if this still happens to you (in which case we have to move some things map wise to put distance)
