### ISSUE TITLE
[Bug]: Clicking on a Longbow warhead with an mounted clamp of a mech triggers an immediate explosion

### ISSUE THREAD

**Issue by FabianK3** [Aurorastation/Aurora.3#18750]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Trying to pickup Longbow warheads from the ships magazine with a mech (with selected mounted clamp) results in an immediate explosion instead of picking up and storing the warhead in the mech.

The current [Wiki for gunnery](https://wiki.aurorastation.org/index.php?title=Guide_to_Gunnery#The_Longbow) (2024-03-24) states for the longbow:

> Putting Longbow ammunition together and loading it might not appear straightforward, so in order to do so, here are some steps to follow.
> 1. Select the relevant Warhead from ammunition storage. These can be picked up without an Exosuit. An Exosuit for loading Warheads is only required if you are pre-assembling multiple Casings. If in an Exosuit, pick up the relevant Warheads with the clamp.

Importantly:
> If in an Exosuit, pick up the relevant Warheads with the clamp.

I think this is either a bug or perhaps the wiki is no longer up-to-date.

### How to reproduce

1. Enter mech from the Grauwolf
2. Select hardpoint - mounted clamp
3. Click on Longbow warhead (e.g. HE warhead) to pick them up

=> Instead of picking up the warhead like Grauwolf-bundles, the warhead immediate explodes.

I have recreated the situation multiple times on my local server using the current (2024-03-24) master branch following the steps descripted on the wiki.

### Round ID

csT-cU7q

**Comment by Acetrea** [comment]
Hanger Techs have been dying to this every few rounds and it desperately needs to be fixed.
