### ISSUE TITLE
Processing criminals in the brig via inserting the report into a cell terminal generates 50 debug logs

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#1876]
Specifically it generates something like this:

DEBUG: Searching for criminal with name: Nick Tungstun

Approximately 50-60 times, I stopped counting precisely after 40.

No idea why this happens but as someone that keeps debug logs to supplement staff logs for information, this particular issue is slightly annoying and spammy.

**Comment by skull132** [comment]
Debug logs are not meant to be clean nor used actively.

We funnel information there that *may* come in handy. Like this stuff! For when it ever gets stuck in a loop or something.

Not a bug.
