### ISSUE TITLE
[Bug]: The Civilian Yacht Crew shuttle needs IDs

### ISSUE THREAD

**Issue by TheTrueFoxtrot** [Aurorastation/Aurora.3#18772]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

The Civilian Yacht Crew shuttle needs IDs to operate the airlocks apparently, which sucks because we don't spawn with IDs, only passports

### Round ID

csV-c0Pq

**Comment by Catrly** [comment]
I've not been able to replicate this during testing. On the map, the airlocks are also set to no access requirement on the access buttons so you should not need an ID. Are you sure you mean the civ yacht?

**Comment by Eyeveri** [comment]
This is the solarian yacht one, right? I instructed to have this made because having an ID fixed it. I will look into this.
