### ISSUE TITLE
Possible Surgery Bug: Unremovable Foreign Body

### ISSUE THREAD

**Issue by Surrealistik** [Aurorastation/Aurora.3#1878]
Seems to be related to yankable objects.

Attempted to remove a foreign body from Izkhezash Ssha'Khus's body but kept receiving the prompt that I couldn't see any useful way to use the hemostat after the proper set up steps (scalpel, hemo, retractor, saw, retractor). As a consequence, the object was impossible to remove.

Possibly related to yankable/embedded object, as this was true of his character at the time.

**Comment by Weer6** [comment]
All shrapnel/etc migrates to the torso after hitting and lodging.
