### ISSUE TITLE
Cannot pull/drag people that are looking through cameras

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#188]
When someone is looking through a camera console, they cannot be pulled or dragged using ctrl+click or grab intent. They can be moved if you use grab intent to throw them, which pulls them out of the camera console screen (Note: Throwing them like this only moves them a single tile, instead of actually throwing them like normal).

**Comment by SierraKomodo** [comment]
to add on to this, if you are buckled to a chair while using a camera console and someone tries to drag the chair, the chair will move and you won't. It seems to 'unbuckle' you but without displaying an emote for it. I can still close the dialogue and move around after this happens.

**Comment by Mwahahahaha** [comment]
This does not occur with the modular computer cameras.

However, this still occurs with "classic" camera consoles such as the camera monitoring TV in the detective's office.

**Comment by Geevies** [comment]
This no longer exists.
