### ISSUE TITLE
[Bug]: Audioconsoles switch to playing ambience when offscreen

### ISSUE THREAD

**Issue by Sniblet** [Aurorastation/Aurora.3#18816]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The audioconsole, when out of earshot, changes its track to creepy ambience on loop.

### How to reproduce

1. Play a song
2. Leave
3. Come back. Get close because sometimes the ambience is quiet and you might mistake it for no sound

### Round ID

csZ-asiy

**Comment by FluffyGhoster** [comment]
I was unable to reproduce this locally, coming back I still heard the normal music
