### ISSUE TITLE
[Bug]: KASF Ship lacks Aluminium (and other materials?)

### ISSUE THREAD

**Issue by Greenjoe12345** [Aurorastation/Aurora.3#18820]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

The KASF ship (and likely others) lack the different types of materials Autolathes can take now, this is a problem since recipes were changed to need it, making the KASF unable to make things in their autolathe

**Comment by lavillastrangiato** [comment]
Would be fixed by https://github.com/Aurorastation/Aurora.3/pull/18935
