### ISSUE TITLE
[Bug]: Bug layer set to above table when placed on table

### ISSUE THREAD

**Issue by Ben10083** [Aurorastation/Aurora.3#18836]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

since #18741 merged, spy bug layers are set to below table but are not that in actually, leading to spybugs being above table.
![image](https://github.com/Aurorastation/Aurora.3/assets/91219575/aac69214-fc3e-40b4-a3bc-3a2f131c9e59)
![image](https://github.com/Aurorastation/Aurora.3/assets/91219575/0a74e8bb-e46a-4d3a-8dd9-4637a4f53768)
Note they are not consistent
(should be 2.2)

Likely affects all items placed on tables

Possibly from this

```    
if(!W.center_of_mass)
        W.randpixel_xy()
        W.layer = initial(W.layer) + ((32 - W.pixel_y) / 1000)
        return
```

### How to reproduce

1) spawn with spy bugs
2) place on table
3) above table, indicating wrong layer
4) placing under plants and on ground works fine

**Comment by Generalcamo** [comment]
Not caused by my PR.

**Comment by Ben10083** [comment]
Issue found in auto_align() for tables adjusting layers of objects, causing items to have higher layers than they should (intended for items meant to be above tables, not if below)
