### ISSUE TITLE
[Bug]: Setup characters not shown

### ISSUE THREAD

**Issue by Ben10083** [Aurorastation/Aurora.3#18843]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Event / Other

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/91219575/c9b4dbe7-ef42-426b-88a6-9adead3acc4b)
Characters invisible in setup. Likely caused by https://github.com/Aurorastation/Aurora.3/pull/18749 which was TM'd

### How to reproduce

1. Open setup
2. no character

### Round ID

cs3-dvOJ

**Comment by Generalcamo** [comment]
Fixed
