### ISSUE TITLE
[Bug]: Space is white

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#18844]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/8042031/33c4122d-4e5b-4d25-a580-160823d2bc5b)

### Round ID

cs4-agRT

**Comment by Generalcamo** [comment]
Can't replicate locally.

**Comment by Jasorn** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/5076069/9f542821-02a2-40f3-9b81-6a47a19035d1)
can confirm it happens on the live server anyway

**Comment by Generalcamo** [comment]
Fixed now
