### ISSUE TITLE
Disconnecting while using a camera console gets you stuck in the camera console view

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#189]
If you disconnect while looking through a camera console, when you reconnect you'll be stuck in the camera console view but won't have the dialog window open to close out of the view. As newcode has a 'feature' that using the arrow keys changes cameras instead of moving you around, the only way to break out of this is the Cancel Camera View verb.

**Comment by skull132** [comment]
That's kinda why the verb is there.
