### ISSUE TITLE
Air randomly flows through closed inflatable doors

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#1893]
Seems to happen randomly to a door that's been toggled open then toggled closed.

**Comment by SierraKomodo** [comment]
Still a relevant issue - Air still flows through closed inflatable doors with no real obvious reason

**Comment by Lohikar** [comment]
This may be fixed in dev due to changes to ZAS & inflatables.

**Comment by Geevies** [comment]
ZAS lag, probably. I believe it's been fixed mostly.
