### ISSUE TITLE
[Bug]: Ethanol Is No Longer Spawning Inside Chemical Dispensers

### ISSUE THREAD

**Issue by Acetrea** [Aurorastation/Aurora.3#18942]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Ethanol is missing from Chemical Dispensers. It's needed for Mortaphenyl, Cytophenolate, Polysomnine, Soporific, and other medicines.
![image](https://github.com/Aurorastation/Aurora.3/assets/138949778/f4de5475-894f-41ed-ad3e-475ffa03ff1e)

### How to reproduce

1. Open the Pharmacy Chemical Dispenser.
2. See that there is no ethanol

### Round ID

ctd-dxeL

**Comment by Acetrea** [comment]
Seems to be caused by the #18939 testmerge

**Comment by FluffyGhoster** [comment]
Solved in latest commit to said PR
