### ISSUE TITLE
Thrusters are still UNBEARABLY loud

### ISSUE THREAD

**Issue by hollyhocc** [Aurorastation/Aurora.3#18946]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The thrusters are, since the sound update, UNBEARABLY loud on deck 3.

### How to reproduce

1. Be on deck three while the ship is moving

**Comment by FluffyGhoster** [comment]
On deck one where, precisely?

**Comment by Nalarac** [comment]
I would argue that it shouldn't be loud enough to hurt your ears even if you're standing right next to them.

**Comment by hollyhocc** [comment]
from at least the residential deck elevators
if thrusters are supposed to cause hearing damage it should be for the characters not for me.....
actually that would be a cool mechanic
