### ISSUE TITLE
[Bug]: Leviathan Impossible to "Stand Down"

### ISSUE THREAD

**Issue by Fyshen** [Aurorastation/Aurora.3#18968]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

It is impossible to undo any of the steps required to fire the Leviathan except the lever pull and final button press. Mainly, it should be possible to remove the key from the activation terminal. I questioned this in round with some admins and it seems impossible to do so, thus leaving the Levi fire button begging to be pressed. It would also be nice to also "engage safeties". When you swipe two cards to unlock the Levi, you get a ship wide annoucement saying the safety had been disengaged. A reverse of this would be nice.

### How to reproduce

Fulfil all the steps to fire the Leviathan:
Swipe two keycards
Put key in activation terminal
Turn terminal
Find you cannot undo any of this.

**Comment by Greenjoe12345** [comment]
I heard the key being un-removable is intentional.
Unsure if this is true.

**Comment by Fyshen** [comment]
Possible, but I think this makes little sense. After all, are you telling me once the Leviathan is activated it's impossible to stand down forever? Perhaps this does require staff input but to keep it as is would imo require some extra lore to make sense ("The ZTA has activation machines with are active for 3 hours due to *phoron reasons*")

**Comment by FluffyGhoster** [comment]
As far as I can tell there's no stand down procedure - You can file this as a suggestion, but the lack of a feature isn't a bug
