### ISSUE TITLE
AI Core Turret Misfiring

### ISSUE THREAD

**Issue by Eimras** [Aurorastation/Aurora.3#1899]
**Game ID:** bNn-bGgP
**Admin bug was dicussed with:** SirCatnip

During a round of Malfunction, an EMP blast hit the AI core. After the EMP wore off, a single turret in the AI core started targeting the AI while it's settings were set to not fire at synthetics. It continued to fire even after altering settings and eventually killed the AI.

**Comment by Lohikar** [comment]
Turrets exposed to EMPs have a chance to be emagged, which causes them to target _everything_ within their view radius.

Not strictly a bug, but maybe something worth changing.
