### ISSUE TITLE
[Bug]: Exosuits have no Sprite

### ISSUE THREAD

**Issue by Ben10083** [Aurorastation/Aurora.3#18990]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Exosuits do not have sprites roundstart, and likely not in general.
![image](https://github.com/Aurorastation/Aurora.3/assets/91219575/7416edfc-c2a3-4187-95a5-20335e3f23b0)
![image](https://github.com/Aurorastation/Aurora.3/assets/91219575/f73ce59e-a6a9-4254-a44e-b6cfecc75307)

### How to reproduce

1) Start round
2) Go to Weapon Loading room (either)
3) No Sprite for Powerloader

### Staff ckey

Noble Row

**Comment by Ben10083** [comment]
Possibly caused by current Testmerged PRs such as #18895

**Comment by FluffyGhoster** [comment]
Not present anymore
