### ISSUE TITLE
[Bug]: Refitted research voidsuit (vaurca) doesn't have a functioning sprite

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#19023]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The sprites are all invisible. I am currently wearing it:
![image](https://github.com/Aurorastation/Aurora.3/assets/8639807/f7d44c75-3da7-44df-99aa-5f2cef8fef04)

### How to reproduce

Go to a research suit cycler, unlock, select vaurca, apply, and that's it

### Round ID

cto-c1AE

**Comment by CaptainGecko** [comment]
I will add my two bits in here, this also applies to Unathi voidsuits. I tried refitting the suit back into Human shape, and the sprite is still absent. I suspect this is an issue with the act of refitting itself.

checked on round cty-cWLB

![image](https://github.com/Aurorastation/Aurora.3/assets/94259758/afff43b8-6dbe-4f5a-b1d8-f272d0260630)
