### ISSUE TITLE
Any amount of languages can be selected.

### ISSUE THREAD

**Issue by TehFlaminTaco** [Aurorastation/Aurora.3#1902]
Test is only preformed when "Add" is clicked, Clicking Add multiple times after the dialog pops up allows successive dialogs to be cued. This means any amount of languages can be added to a character.

![All the languages. All of them.](https://i.gyazo.com/dd8801ee5f369a8a5a92cc3e2ffc1a22.png)

**Comment by Fire-and-Glory** [comment]
time to abuse this
