### ISSUE TITLE
AI cannot access their own messaging program:

### ISSUE THREAD

**Issue by ArloHasaSpareID** [Aurorastation/Aurora.3#19081]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The AI has access to its own internal laptop computer, which can run and download select utility programs. 

The chat program comes standard, and while others can initiate chats with the AI (appearing as a small text blurb in the text UI to the right of one's screen) the AI is unable to open the program and browse/look/initiate chats on its own. Opening the program just closes it immediately.

### How to reproduce

1. Be AI.
2. Try and open the IM messenger app in your internal laptop function.
3. Be amazed as it shows up for 0.2 seconds, then vanish, unusable.

**Comment by FluffyGhoster** [comment]
Unable to reproduce, I used the chat program for various tests for another bug as AI without any problem
