### ISSUE TITLE
AI loses its 'AI Commands' tab when entering its AI shell and then returning to the core:

### ISSUE THREAD

**Issue by ArloHasaSpareID** [Aurorastation/Aurora.3#19080]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

An AI has access to several unique tabs in their UI, chiefly an 'AI Commands' tab. This tab holds several key functions. When entering one's AI Shell, this AI Commands tab is replaced by a cyborg tab (like a normal cyborg). But when returning to the core, the cyborg tab remains and overwrites the AI Commands tab. 

The only way to fix this is to quit the game and rejoin. 

### How to reproduce

1. Be AI.
2. Enter your AI Shell.
3. Return to your AI Core.
4. the AI Commands tab is now gone.

**Comment by FluffyGhoster** [comment]
Duplicate #17686
