### ISSUE TITLE
[Bug]: HAP off-ship doesn't have any Air sensors and the Blast doors don't function

### ISSUE THREAD

**Issue by tzui5020** [Aurorastation/Aurora.3#19086]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

There is simply no Air sensors to tell emergency Shutters to close or even tell me when the air's gone and the blastdoors don't close or the buttons are missing.

### How to reproduce

- Spawn HAP ship
- press ship lockdown
- nothing changes
- Breach somewhere
- Nothing changes other then the air leaving

### Round ID

ctx-dmuI

**Comment by lavillastrangiato** [comment]
Can you elaborate on this? I tested the ship lockdown on my local branch and it worked, and the shutters also worked.

**Comment by tzui5020** [comment]
Oh it got fixed in this PR https://github.com/Aurorastation/Aurora.3/pull/19390 .
