### ISSUE TITLE
Changeling regenerative stasis doesnt fully work.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#1910]
The fake death portion works only partially. Handheld scanners marks you as 300 suffocation, no pulse and overall dead. Now the problem is that the health scanner hud shows them as alive and well, and so does the advanced scanner. No damage, no death.

**Comment by SebkillerDK** [comment]
i've seen this happen before. a ling faked his death in medbay. healt analyzer showed dead and 300 suffocation. but advanced scanner listed the ling as alive but unconcius.

**Comment by Geevies** [comment]
Fixed.
