### ISSUE TITLE
IPC Surgery appears to be borked.

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#1911]
Unable to revive dead IPC's due to not being able to remove their Posbrain. Surgery doesn't seem to work

**Comment by Fiskap** [comment]
It appears that the multitool step required to remove internal components simply does not work, the game doesn't recognize it as a surgery tool. Gives me the "You can't see any useful way to use the multitool on X" message.

Also, scanning IPCs on an operating table with a cyborg analyzer used to work. Now, it gives me the same message as for the multitool step. To analyze an IPC during surgery you have to remove them from the operating table. It didn't use to be like that.
