### ISSUE TITLE
Darkness Overlaps Sprinting Gauge

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#1912]
![b13cfd6666963e9976ec225cb6aea813](https://cloud.githubusercontent.com/assets/12206154/23783253/c869408a-051f-11e7-9127-cabce683842f.gif)

**Comment by OneOneThreeEight** [comment]
This is an issue with the classic HUD you are using.

**Comment by NanakoAC** [comment]
do many people use this hud? Is it really worth the effort to support it?

I find it looks awful personally. eye-searingly bad color clashing

**Comment by OneOneThreeEight** [comment]
No.

**Comment by LordFowl** [comment]
If the HUD is not supported, then remove it @NanakoAC
