### ISSUE TITLE
[Bug]: Protolathe produces items in an instant

### ISSUE THREAD

**Issue by Miracae** [Aurorastation/Aurora.3#19129]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Just like title says, it produced instantly parts and Rapid Part Exchange Device in an instant without any upgrades done to it.

### How to reproduce

Just normally set in an item in the queue and it practically pops out instantly

### Round ID

ctD-dbn1

**Comment by FluffyGhoster** [comment]
The design is set to build in 10 deciseconds, which is 1 second, so this seems expected?
It was slower before, because of how the processing had to wait to run

**Comment by Miracae** [comment]
Ah, if it's as intended, then doesn't matter
