### ISSUE TITLE
[Bug]: Footprints getting doubled and white.

### ISSUE THREAD

**Issue by desvenlafaxine** [Aurorastation/Aurora.3#19148]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Footprints appear double and white. There's really not much else to it. I believe this also happens with blood, but I haven't recreated it.
<img width="63" alt="imagen" src="https://github.com/Aurorastation/Aurora.3/assets/45808369/51c4629a-220c-4212-a33b-77e7f640e764">

### Round ID

ctG-czjZ

**Comment by zagoon** [comment]
Occurs with all footprint types. Seems like it's doing something wrong with the base image that's meant to be colored and rotated.

![footprint](https://github.com/Aurorastation/Aurora.3/assets/9440824/8febdf3b-7006-46e0-a87c-1fb8d7018c47)
