### ISSUE TITLE
Holopads unable to translate Sinta'azaziba

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#1915]
https://i.gyazo.com/741f7b365c7606297197a6aec5d4bb7c.png

As you can see here, the secondary unathi language Sinta'azaziba is not properly translating when received via Holopad.  This might be an issue with it being a vocal and emoted language.

**Comment by Kaedwuff** [comment]
This issue was reported half a year ago.

It's still here, as far as I know. 

Not sure if someone just missed it or something? But I'll bump it.

**Comment by Geevies** [comment]
Think it's been fixed.
