### ISSUE TITLE
Ghosts can play Sudoku while living players are playing it.

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#1916]
Fun fact, you can enter numbers on Sudoku as a ghost if someone is playing it :^)

**Comment by Lohikar** [comment]
Was the ghost an adminghost?

**Comment by ToasterStrudes** [comment]
Ghost ghost, not admin ghosted.

**Comment by LordFowl** [comment]
Admin ghosts have total control over _all_ modular consoles as a ghost.
