### ISSUE TITLE
[Bug]: Machinist Protolathe (Or all of them) insanely fast that it breaks the Robotics Console

### ISSUE THREAD

**Issue by NobleRow** [Aurorastation/Aurora.3#19168]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The machinist's protolathe (or all of them) is now near instant, if not instant, and if you try to queue anything it crashes the console. The protolathe is unupgraded and still produces products half a second after the press of a button, when normally it took some time.

### How to reproduce

Open Machinist computer
Open Protolathe panel
Produced a Nano-Manipulator (It pops out instantly)
Produce a second one
Produce a Rapid Parts Exchange device
Produce six nanomanipulators in rapid succession,
The computer crashes after about three clicks
Restart computer and try again.

**Comment by FluffyGhoster** [comment]
How does the console "break"?

**Comment by NobleRow** [comment]
> How does the console "break"?

Does the internet explorer disconnect because every time an item is produced it refreshes the page, so while you queue things it refreshes and overloads TGUI I think.
