### ISSUE TITLE
[Bug]: Access restricted hardsuits don't open to be hacked.

### ISSUE THREAD

**Issue by NobleRow** [Aurorastation/Aurora.3#19173]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

https://github.com/Aurorastation/Aurora.3/pull/18804
Above has made it to where hardsuits can have their wires tampered with to hack into them, but you can't hack into them without access, which defeats the purpose.

You cannot open the panel to hack into them without access.

### How to reproduce

Get a locked hardsuit,
Try Screwdriver
Try Multitool
Try Wrench (for fun)
Try Crowbar: Get told the suit is locked.

**Comment by FluffyGhoster** [comment]
> Get a locked hardsuit

A path to spawn one of those?

**Comment by NobleRow** [comment]
> A path to spawn one of those?

/obj/item/rig/hazmat/equipped

The Research Director's Rig is the one you saw me fiddling with in the machine shop.
