### ISSUE TITLE
[Bug]: Hardsuits no longer have attached noises while being assembled.

### ISSUE THREAD

**Issue by NobleRow** [Aurorastation/Aurora.3#19171]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Hardsuits used to have associated noises for applying the items to them, such as securing the wiring with the wirecutters and securing the associated hardware circuit board, these sounds are now missing.

### How to reproduce

Go to assemble an EVA hardsuit,
Apply wiring,
Snip wiring, get no sound.
Apply board,
Secure board, get no sound.

**Comment by FluffyGhoster** [comment]
Paths for the required components besides the obvious screwdrivers/wires/tools?

**Comment by NobleRow** [comment]
The EVA Rig Assembly

obj/item/rig_assembly/eva

The EVA Rig Board

/obj/item/circuitboard/rig_assembly/civilian/eva

If you do any of the more advanced hardsuits such as the hazard suit or the combat hardsuit, you'll need their associated circuit boards, targeting boards, and an advanced sensor module.
