### ISSUE TITLE
[Bug]: Exosuit components (Equipment) can no longer be removed without fully disassembling the exosuit

### ISSUE THREAD

**Issue by NobleRow** [Aurorastation/Aurora.3#19172]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Previously, the exosuit could have its equipment removed by using the screwdriver, maintenance mode, and some time without completely disassembling the exosuit, this is no longer the case.

### How to reproduce

Put your Exosuit in maintenance mode,
Click on it with any tool,
Smack it (Unless it's a wrench, which disassembles the entire suit)

**Comment by FluffyGhoster** [comment]
I don't see any code that indicates this was ever an option with the screwdriver, I see however that it is with the multitool:

![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/dbc10676-dbc6-48c2-80e6-9bc8645b298e)

Are you sure this was ever a thing?

**Comment by NobleRow** [comment]
I could have sworn it was the screwdriver but if it's able to be done with a multitool then that works for me. I'm sorry to have wasted your time for this one.
