### ISSUE TITLE
Roller beds duplicate people and teleport them.

### ISSUE THREAD

**Issue by Enzayne** [Aurorastation/Aurora.3#192]
Placing a crew member into any sort of tube/scanner while they are still buckled to a roller bed will leave them attached to the roller while also being inside the interactable object. Moving the roller with the person still "inside" will create a duplicate on the bed. Ejecting the person will teleport them to the roller bed when it is moved.

**Comment by NanakoAC** [comment]
This was fixed a few updates ago
