### ISSUE TITLE
[Bug]: DPRA Vessel spawning with a PRA Vessel Prefix

### ISSUE THREAD

**Issue by GillianDaemon** [Aurorastation/Aurora.3#19201]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship

### Describe the issue

The Hailstorm ship for the ALA peoples volunteer space militia spawned with the name PRAV Champion of Hadii. I ahelped it and its apparently a bug issue. Not sure if it can be changed through the ship console or how many other ships are affected.
![ALA](https://github.com/Aurorastation/Aurora.3/assets/56256728/e8ada7e9-b442-4d44-b38e-7732a1af83d9)

### Round ID

ctN-deBa

### Staff ckey

NobleRow

**Comment by Greenjoe12345** [comment]
The name "Champion of Hadii" doesn't seem to appear anywhere in the code, nor does PRAV 
And the tajara aboard were acting rather suspicious ic, pretending to be Hadiists 
So it might have been changed to that ingame?

**Comment by hollyhocc** [comment]
i played as one of the ghost ship crew. the name was in fact changed to that
