### ISSUE TITLE
[Bug]: Srom is broken

### ISSUE THREAD

**Issue by pochetoo** [Aurorastation/Aurora.3#19207]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The Srom (skrell dream) is sort of broken. The chat doesn't work and all people within are invisible. Performing a srom pull, both were invisible and no chat messages showed up.

### How to reproduce

1. Become a skrell.
2. Sleep using the Sleep verb or other method.
3. Be trapped in a hell of your own making until you wake up.
4. Use the Awaken verb to do that.

**Comment by FluffyGhoster** [comment]
The "how to reproduce" section isn't the "write a meme" section - putting a meme point or two is fine, write only a meme means we do not know how to reproduce the issue, eg. I do not know how to enter or leave the Srom

What are the steps to reproduce it?

**Comment by listerla** [comment]
> The "how to reproduce" section isn't the "write a meme" section - putting a meme point or two is fine, write only a meme means we do not know how to reproduce the issue, eg. I do not know how to enter or leave the Srom
> 
> What are the steps to reproduce it?

Select Skrell.
Use the sleep verb.

You will enter Srom and be unable to see yourself, anyone else, or chat messages from yourself or others.

**Comment by pochetoo** [comment]
> The "how to reproduce" section isn't the "write a meme" section - putting a meme point or two is fine, write only a meme means we do not know how to reproduce the issue, eg. I do not know how to enter or leave the Srom
> 
> What are the steps to reproduce it?

Sorry, I was on very little sleep. Editing now.
