### ISSUE TITLE
[Bug]: Plasteel pike (and probably other crafted weapons) have no attack cooldown.

### ISSUE THREAD

**Issue by LynxSolstice** [Aurorastation/Aurora.3#19238]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Intrepid, Away Site, Event / Other

### Describe the issue

There was a gimmick during a round of a big game hunter, I was a geist. Upon being spotted I was attacked by a plasteel pike wielding engineer, who could attack as fast as he could click, far outpacing even myself in DPS.

**Comment by FluffyGhoster** [comment]
How to craft this pike to reproduce the issue?

**Comment by Geevies** [comment]
> How to craft this pike to reproduce the issue?

Plasteel / Steel sheets -> Craft the spear tip
Wood sheets -> Craft the pike staff / stick (can't remember what it's called)

combine em to make a pike

**Comment by FluffyGhoster** [comment]
Unable to reproduce, it doesn't attack as fast as I can click with neither plasteel nor steel spear tips
