### ISSUE TITLE
[Bug]: Changeling Paralysis Sting self-targets

### ISSUE THREAD

**Issue by NobodySomeone** [Aurorastation/Aurora.3#19239]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Changeling para-sting seems to self-target even when clicking on other sprites. Thought it was a fluke the first two times but clicked on a stationary person next to me the third and still ended up stinging myself.
I can't really think of a good reason for it to be able to self-target in the first place past it being really funny, unlike the silent stings it's blatantly obvious you're the one doing it.

### How to reproduce

Be a changeling
Click Para-sting
Click on person next to you
Vomit blood on yourself and end up on the floor

**Comment by FluffyGhoster** [comment]
Closing in favor of #19348 that seems to be the more general version of this issue
