### ISSUE TITLE
[Bug]: #19209 Causes The Pharmacy To Have No Power At Round Start

### ISSUE THREAD

**Issue by Acetrea** [Aurorastation/Aurora.3#19245]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

testmerge #19209 causes the pharmacy APC to not have power at round start, and then until the SM is set up it drains and the power will go in and out

### How to reproduce

watch the pharmacy APC or just the pharmacy in general at roundstart

### Round ID

ctT-ahRn

**Comment by FluffyGhoster** [comment]
Should be fixed in latest commit, when the testmerge will be refreshed it should be fixed on server too
