### ISSUE TITLE
[Bug]: Machines (Protolate, Circuit Printer, Autolate, Machinist Fabricators) slowed down

### ISSUE THREAD

**Issue by Miracae** [Aurorastation/Aurora.3#19243]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The machines have slowed down drastically yet again pre the change. It happened after the recent Byond Crash. Everything is very, very slow.

**Comment by FluffyGhoster** [comment]
Protolates take however many seconds the design is set to (default 10 seconds) and that's expected, they were intentionally slowed down

The others got slowed down as a side effect, but they're being rewritten / updated to be on par, might take some time
