### ISSUE TITLE
Can't put green flags into your bag after activating them

### ISSUE THREAD

**Issue by Weer6** [Aurorastation/Aurora.3#1927]
How to reproduce
1. Acquire green flags from XenoArcheology, Yellow flags are unconfirmed but assume that yellow and possibly red flags are also affected by this bug and find some of those too.
2. Plant one flag from the stack onto the ground.
3. Try and stuff that in your bag with your meaty hands.
4. Sob as you are useless in life and fail to put them in your bag even though they were in said back just five minutes ago, you complete idiot.

**Comment by SirFruitcakes** [comment]
Yup, this is a problem I ran into, but somehow missed this issue. Hopefully it's fixed sometime in the future, possibly after newmap.
