### ISSUE TITLE
YouTool steals drone's tools

### ISSUE THREAD

**Issue by Eimras** [Aurorastation/Aurora.3#1930]
Only noticed with maintenance drone but I'm guessing it'll do the same to a cyborg that uses tools. If you click a YouTool with a tool the machine stocks selected, the machine will take the tool from you permanently.
![image](https://cloud.githubusercontent.com/assets/9496888/24032394/235adc30-0abe-11e7-8070-67a9cc56f217.png) 
Example with the welder being gone.

**Comment by SirFruitcakes** [comment]
I am literally horrified of YouTools now.
