### ISSUE TITLE
You can hold things in two hands even if you only have one hand in reality.

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#1931]
![image](https://cloud.githubusercontent.com/assets/19973802/24037531/0c700f0e-0b63-11e7-90c7-00625b0aa9db.png)

Done on the test server as it is now.

Bit of an issue.

Apparently you can only hold the off-hand if you have a limb-stump, if the stump has been cut off, you can still double-wield a fireaxe and use its power, but you'll drop the off-hand, I'm not sure if this works the same with shotguns.

**Comment by Sindorman** [comment]
It let's you put it in two hands, but it later drops it.
