### ISSUE TITLE
[Bug]: Xenobiologists cannot turn on shield generators for "Hazardous Containment"

### ISSUE THREAD

**Issue by ArtofWASD2** [Aurorastation/Aurora.3#19310]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

As the tittle says, The shield generators intended to contain hazardous slimes or other lifeforms cannot be turned on by xenobio. They require an engineer to unlock the panel controls.

### How to reproduce

N/A

### Round ID

N/A

**Comment by FluffyGhoster** [comment]
Where is this thing and how are you supposed to turn it on?

**Comment by ArtofWASD2** [comment]
> Where is this thing and how are you supposed to turn it on?

Sorry about that... Thought it was more common.

Xenobiology has a hazardous containment room next to the dissection/surgery room. BEFORE you enter the primary xenobiology area. It has windows facing the normal sci hallways.

There are 2 portable shield generators in the room. You are supposed to swipe your ID on them to enable their controls, then you wrench them to the ground. Finally, when you click both generators, a shield is created between them. 

HOWEVER The problem is that xenobiologists cannot unlock the controls with their ID. You have to call an engineer to do it for you.

**Comment by Ben10083** [comment]
Fixed by https://github.com/Aurorastation/Aurora.3/pull/19347 (although maybe I should of made it req_one_access and add both instead)
