### ISSUE TITLE
A single Airlock Electronic can complete multiple Airlocks.

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#1932]
As the title says. When going to create multiple Airlocks, you can use a single Airlock board to complete multiple. What should happen is you use one board and need another to finish the other Airlock. What is happening is the first one to finish eats the board but the other also gets a board inserted, effectively duplicating the Airlock board.

To reproduce, all you have to do is stand beside two or more Airlocks at the same stage, the 'Insert board' stage, and click both. You'll insert multiple of the same Electronic into the Airlocks, and can probably even remove the original for infinite boards.

Note: I discovered this issue with Windoors, not regular Airlocks. If that is somehow relevant.

**Comment by MarinaGryphon** [comment]
I may have possibly fixed this, I'm going to test the fix and then submit a PR.
