### ISSUE TITLE
[Bug]: Slimes not eating

### ISSUE THREAD

**Issue by YamiiNoir** [Aurorastation/Aurora.3#19427]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The slimes in xenobiology are not eating the monkey's. When one is put into a pen with a smile, the slime smile's [agro is on], but it does not move or attack.
The slime's do not seem to die of starvation either.
![Where food](https://github.com/Aurorastation/Aurora.3/assets/172438919/c9ac6d53-08fe-4484-a73e-5b91c0280b64)
I also pmed staff, but as of making this report I have not gotten a reply.

### How to reproduce

1. Go to Xenobiology.
2. Put monkey in slime pen, any way works.
3. Observe

### Round ID

cua-cXg7

**Comment by FluffyGhoster** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/63274a7d-107d-4c56-8266-24c00c80c3db)
Unable to reproduce

**Comment by Melariara** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/60306280/f03411e8-403e-4030-a11d-2318f3a8f26e)

Not working. Round ID: cub-aPUu

**Comment by FluffyGhoster** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/11444189-29fe-4ab4-8eb5-322c29baa371)
Either I fixed it alongside other work or we're missing something, I suppose we'll see if it still does that after the testmerge is refreshed

**Comment by Melariara** [comment]
Still not working.

**Comment by lavillastrangiato** [comment]
Still not working.

**Comment by FluffyGhoster** [comment]
The thing we were missing was: It was a different testmerged PR to cause this, I think I found it and solved it, we'll know for sure once the testmerge is refreshed

**Comment by FluffyGhoster** [comment]
Is the problem still present?

**Comment by FluffyGhoster** [comment]
Given the lack of any reply, I'll consider this issue resolved, reopen if not
