### ISSUE TITLE
[Bug]: Warehouse side room spawned with no floor

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#19456]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/Aurorastation/Aurora.3/assets/5076069/cccf7e1b-a2d7-4e58-989c-980921f131f9)
No idea what caused this, started observing early in the round and noticed ops was vented and saw this

### Round ID

cud-cCfG

**Comment by Fyshen** [comment]
This has happened in the next two rounds - I suspect a mapping error. This needs fixing somewhat urgently, this is a potentially round ending "bug"

**Comment by FluffyGhoster** [comment]
@DreamySkrell

**Comment by DreamySkrell** [comment]
should be fixed by that PR if it ever happens again
