### ISSUE TITLE
AIs can see into an area without cameras

### ISSUE THREAD

**Issue by echotango23** [Aurorastation/Aurora.3#195]
Just between the HoP's office and the meeting room on the bridge is a small three tile hallway that AI's can see at all times despite there not being any cameras that can see the area, even when the airlocks surrounding it are closed.

**Comment by CakeIsOssim** [comment]
The cameras in the AI core have an x-ray modification by default. Not sure if this is intended to be a feature.

**Comment by LordLag** [comment]
The Ai itself can see through walls. The microscopic section mentioned is within the AIs FOV.
