### ISSUE TITLE
[Bug]: Leg actuators module on hardsuits still do not work

### ISSUE THREAD

**Issue by HELLLP3R** [Aurorastation/Aurora.3#19505]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Same as before. Attempting to use the leg actuators module in a hardsuit keeps you in place, but the prompt still comes up (I used it on the rescue hardsuit)

### How to reproduce

1. select module
2. use module
3. remain in place

### Round ID

cuj-cDKm

**Comment by FluffyGhoster** [comment]
Unable to reproduce, the server was probably not updated with the fix yet

**Comment by FluffyGhoster** [comment]
Assuming this as fixed, reopen if not
