### ISSUE TITLE
[Bug]: Some interfaces prevent stationbound movement when opened.

### ISSUE THREAD

**Issue by benbot16** [Aurorastation/Aurora.3#19507]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When opening certain interfaces (such as the TGUI chemmaster or pump/pressure regulator interface), you will become immobile until the interface is closed. I've also seen it occur with some non-TGUI interfaces, such as trash bins and heaters. Other actions are still possible while the window is open (such as rotating).

### How to reproduce

1- Be borg
2- Click on a disposals chute/pump
3- Try to move
4- Close window
5- Try to move again

### Round ID

cuj-c6Nf, multiple others as well

### Staff ckey

N/A

**Comment by Jasorn** [comment]
This happens with humans too, or at least I noticed it happening with the RnD console open

**Comment by FluffyGhoster** [comment]
Closing in favor of #19569
