### ISSUE TITLE
Cooking Batch Spawning Issues

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#1954]
https://i.gyazo.com/8efe47cab215118a70c925c76ca87d29.mp4

This seems to be related to making batches, but I'm not sure.  I found these under a big stack of steaks when I came into the kitchen late round.  They have no sprite or descriptions and I'm almost certain they're not supposed to be occurring.

Upon playing with the 'objs' a bit, I found that they cannot be picked up, but they can be dragged.  I'm not sure what that's about, or if that helps any.

**Comment by NanakoAC** [comment]
my fault, sorry. Fixed in a patch last night
