### ISSUE TITLE
[Bug]: Throwing an item at a tile will eject another item on that tile

### ISSUE THREAD

**Issue by zagoon** [Aurorastation/Aurora.3#19558]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Per the title: if there are two or more items on a tile, and you throw something at the tile from two or more tiles away (so you're not 'setting something down', though sometimes this activates even when you're adjacent to the tile and on green intent), it'll eject one random item off that tile in the opposite direction.

It's very annoying! And sometimes inconsistent! It really shouldn't be happening on green intent at the very least.

### How to reproduce

1. drop two items on a tile that doesn't have a wall or other solid object behind it
2. move far enough away that you aren't adjacent
3. throw a third object at that tile

**Comment by FluffyGhoster** [comment]
Working as intended, you are aiming at the object by having the cursor over it, aim at the tile to not have the movement, otherwise you're hitting and if it's not anchored it moves

**Comment by zagoon** [comment]
It's very unclear that that's what's happening, and also quite annoying if you have to pixel hunt on a tile to avoid this interaction.
