### ISSUE TITLE
Universal Recorder not recording

### ISSUE THREAD

**Issue by Xzinic** [Aurorastation/Aurora.3#1956]
Attempted to print out and read a transcript of a conversation. The resulting paper exhibited only the starting and stopping point of the recording, 

Steps: 1. Acquire a universal recorder. 2. Start recording. 3. Speak. 4. Stop recording. 5. Print transcript. 6. Read transcript and find that only the start and end time are present.

 Round ID: bNB-aIms.

**Comment by CompleteGarbage** [comment]
If the recorder is in a container, it will not record iirc. The same might also be true of pockets, but I'm not sure.

**Comment by Xzinic** [comment]
Even when held and spoken into, it does not retain information aside from start time and end time.

**Comment by OneOneThreeEight** [comment]
Confirmed consistent throughout multiple rounds.

**Comment by NanakoAC** [comment]
The correct way to fix this is to implement a global list of objects (and NPC mobs)  that want to listen to chat. 
Then check the things in that list when doing say messages and audible_message and audible emotes

This should also be used for talking xenoarch things, lawgivers, commandable animals, etc

**Comment by MarinaGryphon** [comment]
Perhaps this is related to slimes not becoming friendly?
