### ISSUE TITLE
[Bug]: Accessing a machine blueprint's additional information freezes your character in place until they construct something

### ISSUE THREAD

**Issue by Corsaka** [Aurorastation/Aurora.3#19569]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Shift-clicking a machine blueprint in order to inspect it brings up the "This object has additional examine information available" button. Clicking that will freeze your character in place until constructing something new. I haven't fully explored this bug to find out exactly what else will cause it, but I haven't had this issue with other additional examine dialogues.

### How to reproduce

1. Obtain steel sheets beforehand or you'll be stuck in place.
2. Build a machine blueprint.
3. Inspect the machine blueprint and click "[Show In Chat]" on the prompt for additional examine information.
4. Observe that your character can no longer move, even with arrow keys. You can move by jumping or by climbing onto objects.
5. Construct something with the steel sheets - I've only tested with frames of objects, but another machine blueprint and a light fixture frame will both work.
6. Observe that your character can now move again.

### Round ID

cut-czsQ

### Staff ckey

Evandorf

**Comment by Corsaka** [comment]
This may also apply to anything that uses the [Show In Chat] button in a state of deconstruction. The same bug has just happened to me while trying to break apart a GwokBuzz Vendor.

**Comment by Jasorn** [comment]
been getting tons of reports of this happening lately via ahelps, this solution you've posted seems to work though
