### ISSUE TITLE
[Bug]: Miners don't start with the Shuttle Manifest Program on PDA

### ISSUE THREAD

**Issue by Nalarac** [Aurorastation/Aurora.3#19574]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Miners don't start with the shuttle manifest program and have to download it before they can fill it out for the Spark. Other roles that use the shuttles such as Bridge Crew and Xenoarcheologist start with this app downloaded, so I don't see why miners shouldn't.

### How to reproduce

1.) Spawn as Shaft Miner
2.) Open PDA
3.) See no app installed
4.) Have Bridge Crew get mad because you don't want to wait 5 minutes for it to download before leaving

**Comment by FluffyGhoster** [comment]
![image](https://github.com/Aurorastation/Aurora.3/assets/65877598/3ff62d9b-b769-4e8f-ae53-812821492aa8)
Unable to reproduce

**Comment by FluffyGhoster** [comment]
Actually I'm stupid, you said shuttle manifest and I read crew manifest
