### ISSUE TITLE
[Bug]: Dead siros are invisible

### ISSUE THREAD

**Issue by listerla** [Aurorastation/Aurora.3#19606]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Away Site

### Describe the issue

When a siro is killed, the body turns entirely invisible.

### How to reproduce

1. Spawn a siro.
2. Kill it.
3. Observe the (lack of) body.
4. Right click the tile it was on, seeing the body technically exists.

**Comment by lavillastrangiato** [comment]
Fixed by #19635
