### ISSUE TITLE
Mice can abduct wheelchairs.

### ISSUE THREAD

**Issue by Chada-1** [Aurorastation/Aurora.3#1961]
As the title says, Mice can buckle themselves to a Wheelchair and wheel it around. They can also use all of their verbs, hide makes them under the wheelchair, while wheeling around, and makes them just about unseeable as they do so. Lay down makes no difference at all, while 'resting' they can still wheel around with no change. The worst part about this beyond immersion breaking and stealing Medical equipment, is the fact that they can Ventcrawl in a Wheelchair which teleports the Wheelchair to wherever they go. Just buckle to a Wheelchair and wheel yourself around. Super easy to reproduce.

**Comment by Geevies** [comment]
Think is this fixed. I personally blame Nanako.
