### ISSUE TITLE
[Bug]: Xion Frames overheating 

### ISSUE THREAD

**Issue by UltraBigRat** [Aurorastation/Aurora.3#19628]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Away Site

### Describe the issue

Xion frames are overheating during EVA, which from what i know shouldnt be happening. First noticed this yesterday, putting on a cooling unit afterward also did not seem enough to offset the overheating, only stopping after getting into atmosphere or going under a cold shower.

### How to reproduce

1. Be a Xion frame IPC
2. Go to space or a planet with no atmosphere
3. In a few minutes internal temperatures reach 1000+ celsius and begin to melt you

### Round ID

cuG-bidD

### Staff ckey

Melariara

**Comment by EJDenton** [comment]
I wasn't able to replicate this. I took an industrial xion unit into space and survived with no issues. The body temperature didn't rise or was affected at all. I tried with a suit as well just in-casae, but it was the same.

Were there any other details about the issue you can recall?

**Comment by FluffyGhoster** [comment]
Tried to reproduce this in space without success, either it got resolved in the meantime or something else happened, reopen if it happens again with more info on what you was doing, damages and the likes
