### ISSUE TITLE
[Bug]: AI Holograms loadout bugged

### ISSUE THREAD

**Issue by squidqueen** [Aurorastation/Aurora.3#19646]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The AI draws from your loadout image to make a customized hologram, the issue therein is that the hologram is stark naked, and in loadout will not apply any clothing options whatsoever. 

It may be linked a similar display issue bug for technomancer illusions, I'm told.

### How to reproduce

Go to loadout with AI on high, begin to apply clothing, nothing applies, remain absolutely naked. Hologram ingame is naked if using the custom loadout projection.

**Comment by lavillastrangiato** [comment]
Duplicate of https://github.com/Aurorastation/Aurora.3/issues/19360 and https://github.com/Aurorastation/Aurora.3/issues/12913

**Comment by FluffyGhoster** [comment]
Closing in favor of 19360
