### ISSUE TITLE
[Bug]: Ghost roles not spawning

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#19705]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Overmap

### Describe the issue

Two rounds in a row since the test-merge pr https://github.com/Aurorastation/Aurora.3/pull/19698 has been in there have been no ghost roles other than maintenance drone.
![image](https://github.com/user-attachments/assets/f53c88ae-bdde-476e-b509-f42d549a8d4a)

### How to reproduce

1. Join
2. Open ghost spawner
3. It's over ghost bros....

### Round ID

cuT-aNnO   &   cuT-ajeO

**Comment by FluffyGhoster** [comment]
![image](https://github.com/user-attachments/assets/266182aa-feb9-47a3-a14e-fc0ddc8a30f6)
Unable to reproduce on the mentioned PR

**Comment by Jasorn** [comment]
I guess there's a small chance it didn't roll any, especially planets because it can sometimes roll non for ghost roles, but seems unlikely two rounds in a row it didn't roll a single ship either times.

**Comment by FluffyGhoster** [comment]
![image](https://github.com/user-attachments/assets/eb8e045c-088d-4e76-b912-75b719e3b5d2)
Working as intended, just a statistical anomaly

**Comment by Jasorn** [comment]
![image](https://github.com/user-attachments/assets/6ef11050-af92-4db5-a420-dbfa57dd8a08)
![image](https://github.com/user-attachments/assets/68ae7c01-2913-4c40-85d7-4e1a4febb2d1)
![image](https://github.com/user-attachments/assets/140560b0-5fcc-4b9b-8def-85427a17a2a5)
![image](https://github.com/user-attachments/assets/a26d9e59-2fc1-446a-8462-6e76c71b1265)
![image](https://github.com/user-attachments/assets/4e3ffd4c-ec48-41a4-aa6b-500cb778c18e)
Here's five back to back rounds of bare bones if no ghost roles, something is fore sure going on here, because I haven't seen a single Moghes spawn either
