### ISSUE TITLE
[Bug]: Offships do not appear to be spawning

### ISSUE THREAD

**Issue by hazelrat** [Aurorastation/Aurora.3#19713]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Away Site

### Describe the issue

Right now, offships don't seem to be spawning in on live. 

Ghostspawns as a whole are functional, but a few days worth of rounds in succession, I've only seen non-offship ghostroles spawn. Tret, the Reclamation, and any of the roles on any of the sector-local planets are spawning, but no offships whatsoever.

### How to reproduce

1. Go on live.
2. Open the ghostrole tab across multiple rounds.
3. See that no offships have spawned across the same number of rounds.
4. Increasingly lose faith in the staggering statistical improbability that this is happening by chance.

**Comment by Jasorn** [comment]
I was saving screenshots yesterday just to see, heres five in a row

![image](https://github.com/user-attachments/assets/ae46194c-d208-474d-a1a1-c8375af17524)
![image](https://github.com/user-attachments/assets/cd1e8139-15bc-469e-a377-371cac95ca16)
![image](https://github.com/user-attachments/assets/42ed50a4-7312-42d7-8b13-1ecbfaf5fc6d)
![image](https://github.com/user-attachments/assets/2c0c608d-75fa-452d-9b69-3d9dbee7f8ae)
![image](https://github.com/user-attachments/assets/1e47f6b7-8bb1-47fa-837c-f7c4a089f345)

**Comment by Nalarac** [comment]
Outside of Uueoa-Esa specific POIs, I've also noticed the only generic POIs spawning are Abandoned Industrial Station, Asteroid Lair, and Orbital Station.

**Comment by Nalarac** [comment]
Fixed by #19812
