### ISSUE TITLE
[Bug]: Going down stairs still spills contents of crates and gurneys, going up does not.

### ISSUE THREAD

**Issue by bigbucceesfan96** [Aurorastation/Aurora.3#19714]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Previous PR reverting the dangerous stairs mechanic only seems to be half working, contents still spill from crates, gurneys, and wheel chairs when going down stairs but not up them. 

### How to reproduce

1. Load a crate with supplies or a gurney with a body
2. Drag entire assembly up stairs with no issue
3. Turn 360 degrees and walk back down the stairs
4. Blow open your bag of body parts like a really bad pinata 

### Round ID

N/A

### Staff ckey

N/A

**Comment by FluffyGhoster** [comment]
We reverted the stairs PR and I'm unable to reproduce the issue, therefore this is believed to be solved
