### ISSUE TITLE
Mislabelled loadout item tag(s?)

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#1972]
If you select a blue poncho in the loadout screen, you are instead spawned with a blue jacket.  There might be other similar things.  Should do some testing maybe.

**Comment by Alberyk** [comment]
![poncho](https://cloud.githubusercontent.com/assets/11579997/24254934/e3897648-0fc2-11e7-830a-775f85e524db.png)

Tested on server and seems to work fine.

**Comment by Kaedwuff** [comment]
Upon trying it on the main server, I was unable to replicate it too. Then, I remembered the bug had specifically happened on Lohikar's test sever when he had newmap up, and discovered isn't replicated there, either.  Sooo. 

I guess I was just really tired and accidentally picked blue jacket.  Go meeeeee. ¯\_(ツ)_/¯
