### ISSUE TITLE
Configable job blacklist not working

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#1973]
https://forums.aurorastation.org/viewtopic.php?p=62412#p62408

Suggestion from awhile back was binned due to its actual implementation in a past code change that locked Day 0 accounts off from initially playing the non-internship security roles. Your account needed to be a week old to play as security. This is no longer the case, possibly due to the recent bay merge, other than that I've not been keeping track since I've been here since forever and would not be able to notice it and prove it's not there.

In that, somehow this is no longer working because I've had a few cases as a trial mod the past couple weeks with less-than-stellar security play stemming from some newfriend individuals with little to no experience with the culture and atmosphere of Aurora security making either mildly dumb judgement calls or quite heavy mistakes.

There have been a fair deal of issues with dealing with newcomers joining as security for their first round. The security department is already not newb-friendly due to the mechanical OOC expectations and the attitude expectations for both IC and OOC. Such examples are not worth going on a large tangent about as they are many and typically just repeats of similar stories heard before. The system does two things, 1.) noob-proofs the department and only permits new folks into the cadet position so they can learn our version of security if interested, and 2.) has the adverse effect of weeding out effortless shitlords who just want to goof off with the stun baton, guns and a badge.

This is definitely something with medium-to-high priority to fix, unless this change was caused deliberately. It is affecting how new people act as security and how regulars react to security, and it's bad practice to give authority and responsibility to just whomever. They need to play a bit to get used to things before deciding to jump into the reigns of flexing security authority over others.

**Comment by skull132** [comment]
Actual issue is that the system I wrote up doesn't work for antags. Which is why it was disabled, IIRC. It should be looked into and patched.
