### ISSUE TITLE
Camera photos have immense lens flare

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#1974]
Steps to reproduce:
1.) Acquire camera.
2.) Take photo and lag the entire server in doing so, this being a separate bug entirely.
3.) Examine photo.

Likely due to the light code changes that this occurs. Caution is advised when attempting to reproduce. But one cannot actually see what was captured in a photo.

**Comment by EthanMalakay** [comment]
https://gyazo.com/cb12aebec277782b44362a35ba2fc3cd
Bug
*claps fingers* fix it :U
