### ISSUE TITLE
Scientists don't have access to Genetics once power is applied

### ISSUE THREAD

**Issue by cha0s5150** [Aurorastation/Aurora.3#1978]
I rebuilt the Genetics Lab. The DNA modifier, the console that goes with it and the APC for the room. Once I got an engineer to the room to turn on the APC and power was applied to the room the machines turned on, but I was then trapped inside the room as a scientist. I had previously gone to the HoP and asked for genetics access and medbay access. I was told there is no genetics access and I didn't need medbay access because medical could handle cloning. There either needs to be access available from the HoP or scientists should already have access be default to the genetics lab as well as their normal access.

**Comment by Eimras** [comment]
Isn't the genetics lab limited to RD, CMO, and Geneticists? Not scientists.

**Comment by OneOneThreeEight** [comment]
Genetics was disabled a long time ago. Genetics is anticipated to be revamped by the time the new map comes in April.

**Comment by MarinaGryphon** [comment]
Protohumans, and by extension genetics, works now. Howerver, I'm pretty sure this is NOT a bug.

The HoP lied to you, that's the fact of the matter. The Genetics Lab is an option for access. The RD has it, the CMO has it, and Geneticists would have it if they could join.

**Comment by Alberyk** [comment]
Not a bug.
