### ISSUE TITLE
Fax machine breaks

### ISSUE THREAD

**Issue by Eimras** [Aurorastation/Aurora.3#1979]
Sending a fax from the Warden's office to the HoS office causes the fax machine to forever be stuck on 
Transmitter arrays realigning. Please stand by. 0 seconds remaining.
I've had this happen on multiple occasions since the update.

![](https://i.gyazo.com/766990f1975cd9996c832cde488c44e1.png)

**Comment by skull132** [comment]
Fixed in #1987
