### ISSUE TITLE
[Bug]: borg syringe can give people infections if used more than once

### ISSUE THREAD

**Issue by miniusAreas** [Aurorastation/Aurora.3#19817]
### Checks

- [x] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

using the syringe that the borg gets (Not the hypospray with preloaded chems) more than once gives people sepsis if used again, like a normal syringe.

This syringe is not disposable, as it it attached as one of your modules. You cannot sterilize it (as far as I'm aware) either, meaning it's essentially currently a one time use syringe.

### How to reproduce

1 - load syringe with chems and inject person 1

2 - load syringe with chems and inject persons 2 3 and 4

3 - wait for infections and or sepsis to happen and kill said persons after awhile.

4 - :surprisepikachu:

**Comment by furrycactus** [comment]
15u of Thetamycin is your friend. Does suck though.
