### ISSUE TITLE
Baking bread with the new Cooking system

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#1981]
From testing, it seems you cannot make normal Bread anymore, due to you only being able to crack eggs into the baking pan, and not add the normal egg which is called for in the recipe. (It produces 'Small dough bread')

**Comment by TrickingTrapster** [comment]
To add to this, this means you cannot acquire bread slices which makes several recipes just unobtainable.

**Comment by NanakoAC** [comment]
my bad, will fix

**Comment by Geevies** [comment]
Fixed.
