### ISSUE TITLE
[Bug]: Consular Office A has misplaced (extra) ringer

### ISSUE THREAD

**Issue by NerdyVampire** [Aurorastation/Aurora.3#19821]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

For the AI eye at least, it appears there is an extra ringer floating above the holopad (see picture). It is interactable and reacts separately from the other ringer, so it seems to be a misplaced duplicate.

![image](https://github.com/user-attachments/assets/9d8bc18f-49f0-40f3-81bb-fb23cffa86bf)

### Round ID

cvk-ddR3

**Comment by courierbravo** [comment]
Already fixed by https://github.com/Aurorastation/Aurora.3/pull/19813, which should be merged within the next round or two
