### ISSUE TITLE
This isn't your average everyday darkness... This is advanced darkness.

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#1985]
The lighting for this area wouldn't update, no matter what. I had a Floodlight Module and the flashlight on, it just wouldn't update. I don't know how to reproduce it, but what should be happening is the light should illuminate it.

Game ID: bNE-aEdk

https://puu.sh/uWFnJ/53f55c76ec.jpg
https://puu.sh/uWG1m/a3d4b4e4ae.jpg

**Comment by Spoopy11** [comment]
Pretty sure this was happening pre-merge, but it's more meme-tastic now with the better lighting system.

**Comment by skull132** [comment]
It happened with old lighting as well, it's a byproduct of smoke. Lohikar is investigating.
