### ISSUE TITLE
[Bug]: lazarus injector no longer works

### ISSUE THREAD

**Issue by Ben10083** [Aurorastation/Aurora.3#19861]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Lazardus injector, when using on dead crusher, does not inject, and hits them with the injector
![image](https://github.com/user-attachments/assets/23412604-bf4e-4b40-ac4a-45018af6ed58)

### How to reproduce

1. kill an animal (ingame)
2. spawn injector
3. attempt to inject

**Comment by hazelrat** [comment]
For some reason, this is selective. Lazarus injectors work fine on corgis, but not on cats.
