### ISSUE TITLE
[Bug]: Paperwork being deleted when removed from a large stack

### ISSUE THREAD

**Issue by squidqueen** [Aurorastation/Aurora.3#19888]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Upon using forms printed by the requests console (case reports and morgue papers) that were both put in folders and journals, when removed from a paper stack with other papers, the paper was hard deleted. 

No moderation tool could locate the paper, so it must have been qdelled. 

### How to reproduce

See above.

### Round ID

cvE-dCQe

**Comment by FluffyGhoster** [comment]
> Upon using forms printed by the requests console (case reports and morgue papers) that were both put in folders and journals, when removed from a paper stack with other papers, the paper was hard deleted.

I can't understand how to reproduce, please provide a step by step instruction on how to reproduce the issue

**Comment by squidqueen** [comment]
printed paper from terminal
Put in journal
take out of journal
i stamped paper 
case closed, both signed
put it into bundle
wanted stamped paper on the front, take all paper out of bundle (hands full so papers falling on floor)
then redo bundle

I think the issue is papers falling to the floor perhaps during server lag
