### ISSUE TITLE
[Bug]: Maint APC has wrong orientation

### ISSUE THREAD

**Issue by FabianK3** [Aurorastation/Aurora.3#19907]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/user-attachments/assets/ad57bc29-b5bd-4e7e-b234-eb9125ab58e2)

APC located on deck three, between engineering breakroom, main lift and public lockerroom.
I assume it should face east instead of west.

**Comment by hazelrat** [comment]
Resolved with https://github.com/Aurorastation/Aurora.3/pull/19887
