### ISSUE TITLE
[Bug]: INDRA Reacting Unpredictably (and Dangerously)

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#19906]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

The INDRA (when running Boron at least) functions normally until Boron begins to fuse with Hydrogen. Once it starts, it begins to accumulate instability dangerously fast with no regard for the gyrotron being active and on full strength. However once it reaches 51%, it appears to automatically stop processing reactants and heat dump rapidly, instantly returning to 0% instability moments later.

### How to reproduce

1. Set up the Supermatter.
2. Hard-wire the gyrotron's grid into the main grid so it's getting power from the SM.
3. Put a Boron and Hydrogen canister on the ports, both pumps on 5 kPa.
4. Set the gyrotron console to 50 strength, 2 delay and turn it on.
5. Set the INDRA field strength to 60 tesla.
6. Initiate fusion.
7. Have several small heart attacks when the instability starts to skyrocket when it starts fusing Boron.

**Comment by FluffyGhoster** [comment]
Should be fixed when the testmerge is refreshed
