### ISSUE TITLE
[Bug]: Tajara cannot wear the adhomian gauntlets

### ISSUE THREAD

**Issue by Greenjoe12345** [Aurorastation/Aurora.3#19916]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Trying to wear the adhomian gauntlets, it seems they cannot be worn. They will not go into the glove slot, and trying to use wirecutters says they are already clipped.

### How to reproduce

Get adhomian gauntlets, try to wear them as a tajara.

**Comment by Greenjoe12345** [comment]
Yes, I suppose it should be made clearer.

**Comment by FluffyGhoster** [comment]
As per hazel's comment/analysis
