### ISSUE TITLE
[Newmap] Misc Issues

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#1993]
* The Quartermaster's window tint does not work properly.
* The telecomms upper-level lounge does not appear to be connected to the grid.
* Engineering has a pipe painter instead of a floor painter.
* The CCIA (crescent) shuttle's station-side airlock controller does not work properly - inner door will not open.
* The ERT shuttle's station-side airlock is non-functional.
* Missing firedoor at (109, 120, 5).
* Missing firedoor at (176, 118, 5).
* Missing firedoor at (179, 116, 5).
* Missing firedoor at (175, 116, 5).
* The Materials lab in Research's APC is not connected to the grid.
![2017-05-06_20-47-06](https://cloud.githubusercontent.com/assets/7097800/25777256/47762a5a-329d-11e7-81b8-16a2ab5bd772.png)
* The cargo bay on the surface level does not have an APC.
* Window at (178, 125, 4) has no hazard shutter.
* Random windows at (167, 131, 6)

**Comment by Juani2400** [comment]
I will work on these during this week.

**Comment by Lohikar** [comment]
Added a few more issues I found.

**Comment by darkrising** [comment]
I'll add a few more if you don't mind:

Tech storage wire missing in engineering: https://tzli.me/i/Z0NadFI6B5
Power sensors for engine out and engine power are throwing errors: https://tzli.me/i/gNxM1kDexe

**Comment by Juani2400** [comment]
#2055 fixes 90% of Lohikar's and all those of Molten (Rising).

**Comment by Arrow768** [comment]
The corner-belt in robotics is not moving items. (Not enabled when the switch is toggled on)
![grafik](https://cloud.githubusercontent.com/assets/1331699/24838346/9f256e08-1d46-11e7-96e9-7564e7d304d3.png)
