### ISSUE TITLE
[Bug]: Sensor Datalink Spam

### ISSUE THREAD

**Issue by benbot16** [Aurorastation/Aurora.3#19937]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Spark

### Describe the issue

On the SCCV Spark, the sensors console continually spammed the datalink contact alert for the entire round.

![image](https://github.com/user-attachments/assets/209f1972-7422-4f35-9c61-ce351d7fe5d3)

### How to reproduce

1. fly SCCV Spark
2. Get the above bug

### Round ID

cvR-cPHF

### Staff ckey

N/A

**Comment by FluffyGhoster** [comment]
The "I have searched the bug with a few keywords, and I confirm this bug was not yet reported." check is there for a reason

Using either the keyword "datalink" or "spam" would have returned #19830 

Closing as duplicate
