### ISSUE TITLE
[Bug]: Overmap projectiles ricochet off overmap sites.

### ISSUE THREAD

**Issue by sadkermit** [Aurorastation/Aurora.3#19960]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Third party ship, Overmap

### Describe the issue

The Sol Navy Recon ship, when firing on a sensor relay with the Grauwolf, will see its fired projectiles ricochet off of what it has targetted, then explode elsewhere on the sensor map z-level. Kinda funny.

Not sure if this extends to other ghostships, not sure if it is exclusive to firing upon the sensor relay, not sure if it was a particular ammo type of the Grauwolf that ricochets, not sure if it's only the Grauwolf or if all ship guns will see their shots ricochet.

### How to reproduce

1. Spawn the Sol Navy Recon ship and load it's Grauwolf.
2. Line up a shot with a sensor relay
3. Shoot the Grauwolf at the sensor relay, watch the projectiles ricochet off
4. Await the admin log of the projectile exploding on the sensor map z-level instead.

### Round ID

cvV-cT9y

**Comment by FluffyGhoster** [comment]
Ricocheting isn't enabled on any projectile, how did you determine this was a ricochet?

**Comment by hazelrat** [comment]
> Ricocheting isn't enabled on any projectile, how did you determine this was a ricochet?

@FluffyGhoster 
I've replicated this in private. It seems like the overmap projectile disappears when it impacts the target, then the actual projectile spawns _on_ the overmap and veers off diagonally, until it impacts the edge of the overmap.

https://github.com/user-attachments/assets/60a8c37c-b0ba-42cd-8723-c7b58e4abfa8
