### ISSUE TITLE
Injured hand still usable.

### ISSUE THREAD

**Issue by Dreviore** [Aurorastation/Aurora.3#200]
As a xenobiology I had a slime glomp at me. Took out my left hand. Weirdly enough under certain circumstances I could still use my hand (say I split a stack of phoron, or I took an item out of my pocket, or even swap an item from one hand to the other.

Only thing I couldn't do was pickup objects with my left hand.

**Comment by skull132** [comment]
How injured was the hand, and do you remember if you were dropping the objects?

Do you also remember if you were outright stopped from picking up objects from the ground? 

Under most circumstances, an injured hand used to simply make you drop stuff and scream. To render a hand completely unusable, you'd have to cut it off.

**Comment by Dreviore** [comment]
Whenever I attempted to pick this up I'd be notified that my hand was too
injured to use (as when you get glomped by slimes) I couldn't pick things
up, or move things from my backpack to that particular hand. BUT I was able
to move stackable items into the hand by splitting it.
