### ISSUE TITLE
Mice vs. Kitchen

### ISSUE THREAD

**Issue by XenosTiger** [Aurorastation/Aurora.3#2003]
Mice are capable of opening and shutting, and, more importantly, toggling power to, the various kitchen appliances. I'm not sure if this is actually worth patching out though, since mice in kitchen are usually KoS anyways, but I assume the same is for any and all smallcreatures?

**Comment by skull132** [comment]
Missing usability checks.

**Comment by Arrow768** [comment]
@NanakoAC Also take a look at the distance checks. The AI can eject items from the machines

**Comment by Spoopy11** [comment]
Ghosts can interact with the machines also.

**Comment by skull132** [comment]
Pretty fucking sure we fixed this. Closing.
