### ISSUE TITLE
[Bug]: Exosuit battery problem

### ISSUE THREAD

**Issue by Obsdark** [Aurorastation/Aurora.3#20039]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

I remove the battery from the exo to recharge it, after i recharge it i tried to add it back but doesn't work, it's asking for a power core now.

Maybie related than i remove a power core from the other exo and add it to the new one, after which i remove it too.

### How to reproduce

1) Make an exo

2) Remove it the battery

3) (not sure about this but) Put a power core on the exo

4) (not sure about this but) Remove the power core from the exo

4) Try to add the battery back

### Round ID

cv0-cv2O

### Staff ckey

Evandorf

**Comment by FluffyGhoster** [comment]
Mechs only work with power cores for what I can see in the code, not with normal power cells
