### ISSUE TITLE
[Newmap] Random damage

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2004]
Approximately 5 minutes after a character spawns, they will take a large amount of oxyloss and brainloss, as well as getting low blood. Usually fatal, always crit. Non-crew characters such as BSTs or ERT are seemingly not affected.

**Comment by Lohikar** [comment]
Additional information: This does not seem to happen to players who readied up at roundstart and spawned normally.

**Comment by Alberyk** [comment]
Death is caused by septic infection in all internal organs, they all have around germ_level = 1004.
