### ISSUE TITLE
Medical and intents not working.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2006]
So this has been a more frequent issue than Im comfortable with, but as of late, using health analyzers and syringes tends to break on help intent, aswell as the borg hypospray.

![5f35bed52b](https://cloud.githubusercontent.com/assets/20225964/24417735/d4d0b05a-13e9-11e7-9311-ae8599862b9d.png)

The issue can be circumvented by swapping intents, but it is extremely annoying in a high pressure situation.

**Comment by SebkillerDK** [comment]
I second this. i have had it happen multiple times aswell, and when the sitation gets tense, it becomes REALLY annoying to have to deal with.

**Comment by NanakoAC** [comment]
this shouldn't be a transient issue but highly reproducible, i'm guessing this would occur whenever the patient is lying on a rollerbed or surgery table

**Comment by Alberyk** [comment]
Fix'd in #2013.
