### ISSUE TITLE
[Bug]: Observers can detach other observers following a mob

### ISSUE THREAD

**Issue by zagoon** [Aurorastation/Aurora.3#20091]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

If ghosts are following a player, and one of those ghosts uses double-click to move away or jump to another mob, all observers on the first mob will instantly cease observing that player (they will de-orbit and no longer follow them).

### How to reproduce

1. Have more than one player following someone
2. Double-click to jump elsewhere on the screen

**Comment by AlaunusLux** [comment]
Caused by changes in #20083 (for visibility)

**Comment by FluffyGhoster** [comment]
Should be fixed whenever we refresh the testmerge

**Comment by FluffyGhoster** [comment]
Should be fixed from now on, reopen if not
