### ISSUE TITLE
[Bug]: Fireman Carrying broken

### ISSUE THREAD

**Issue by Clem-The-Duck** [Aurorastation/Aurora.3#20099]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

When fireman carrying, the person being carried stays stationary and is not actually moved. All other aspects of the carry seem to be the same, but once the person is on your shoulders they do not move with you and just remain in the carry position on the tile they were picked up from.

### How to reproduce

1. fireman carry as normal
2. attempt to move once they are on your shoulders

**Comment by FluffyGhoster** [comment]
Will be fixed whenever we refrest the testmerge

**Comment by FluffyGhoster** [comment]
Should be fixed from now on, reopen if not
