### ISSUE TITLE
Full-grown diona do not have slots for gloves or eye gear

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#201]
Full-grown/adult diona characters cannot wear any form of glovews or any form of eye-slot equipment due to a complete lack of said slots in the hud. This means diona cannot wear sterile gloves, electrical gloves, sec huds, medical huds, etc, which completely breaks/hinders their ability to perform in several different roles.

**Comment by Alberyk** [comment]
It is a feature from bay, not an issue. They also have a natural resistance to shocks.
