### ISSUE TITLE
[Bug]: Tremble Spawns In the Warehouse When It Should Be Admin-Spawn Only

### ISSUE THREAD

**Issue by Acetrea** [Aurorastation/Aurora.3#20136]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

![image](https://github.com/user-attachments/assets/f5f49d1f-9409-4175-b18e-34bad239abf6)

### Round ID

cwu-apcM

**Comment by FluffyGhoster** [comment]
How did you determine this should be admin spawn only?

**Comment by Acetrea** [comment]
> How did you determine this should be admin spawn only?

I had never heard of this drug before, but it was on the Chemistry wiki (as a pharmacist main I'm constantly looking at the chemistry wiki), so I looked at the history at read this:
![image](https://github.com/user-attachments/assets/596832c2-ed66-4ecd-a4cb-5e4eca92a411)

If you want it in the warehouse, then that's fine /shrug
Maybe I outta ask kermit

**Comment by Acetrea** [comment]
> > How did you determine this should be admin spawn only?
> 
> I had never heard of this drug before, but it was on the Chemistry wiki (as a pharmacist main I'm constantly looking at the chemistry wiki), so I looked at the history at read this: ![image](https://private-user-images.githubusercontent.com/138949778/382486001-596832c2-ed66-4ecd-a4cb-5e4eca92a411.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjM3MzMsIm5iZiI6MTczMDU2MzQzMywicGF0aCI6Ii8xMzg5NDk3NzgvMzgyNDg2MDAxLTU5NjgzMmMyLWVkNjYtNGVjZC1hNGNiLTVlNGVjYTkyYTQxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNjAzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODJjYjk0YWMxMzg4ZjZmZWNiM2QzYjhjOWNlN2U0NzIwYTkyYjUwMTM0ZGMyN2IwYmJhNjY0ZDNkM2JmNTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1oYiKPWYeuHKWDBnRUdWFglbKTRH2Jf69JKAfHwWcuU)
> 
> If you want it in the warehouse, then that's fine /shrug Maybe I outta ask kermit

Eh, Kermit says it's fine to be in the warehouse. It's just a weird drug someone forgot to give a recipe to, (and it sucks apparently) so I'll just close this.
