### ISSUE TITLE
The raise dead spell is a bit buggy about the prompts it gives ghosts

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#2015]
Basically, if someone is killed and  then has the raise dead spell used on them, every ghost gets a prompt asking them to be a skeleton.

However, long after someone would've accepted that prompt to be a skeleton, the other ghosts would still have it, and should they choose to accept, it causes a lot of buggy shit with ckey's being displaced from the body and in the case of the one possessing the body late, the client crashing and ending up on the lobby screen.

**Comment by Alberyk** [comment]
Probably fixed after I added the ghost trap to it.
