### ISSUE TITLE
Suit sensors are borked

### ISSUE THREAD

**Issue by Weer6** [Aurorastation/Aurora.3#2018]
Two things, first the sensor "map" shows blank space and no markers for anyone, likely because the Z-levels are somehow implemented into it. second, on the actual map, it reports a third number which is "undefined".

how to reproduce

1. Get suit sensors laptop
2. open.
3. Notice how there is a third "number for every coordinate, all undefined.
4 switch to map
5. be utterly disappointed by the lack of map.

**Comment by LordFowl** [comment]
Does this apply to the current code, or new map code?

**Comment by Lohikar** [comment]
Appears to be current, getting template errors when I open suit monitoring on a modular computer.

**Comment by SierraKomodo** [comment]
Seems to work fine for the AI's suit sensors subsystem on current code.

**Comment by Arrow768** [comment]
Unable to reproduce. It works fine on current.
![2017-04-01_172036](https://cloud.githubusercontent.com/assets/1331699/24579934/94296f4c-16ff-11e7-933b-c229dafa9c3f.jpg)

**Comment by skull132** [comment]
Cannot replicate, no new info, no new reports. Invalid, closing.
