### ISSUE TITLE
Bees break grabs

### ISSUE THREAD

**Issue by Killerhurtz** [Aurorastation/Aurora.3#202]
Having a grab interact with bees can have a plethora of nasty effects, such as breaking that character's grab capabilities or even turning the grab into a real, legitimate item that can be dropped into the world.
![dreamseeker_2016-03-01_18-32-23](https://cloud.githubusercontent.com/assets/17021360/13445770/4f5acc54-dfdc-11e5-8abb-43c1af47f7d2.png)
![dreamseeker_2016-03-01_18-32-40](https://cloud.githubusercontent.com/assets/17021360/13445771/50b17486-dfdc-11e5-8059-46fd8f0bb50f.png)

**Comment by Kaedwuff** [comment]
I have also noticed the ability to drop grabs into lockers at times, when you are trying to stuff people inside.

**Comment by NanakoAC** [comment]
Fixed by  #859
Bees are no longer grabbable
