### ISSUE TITLE
Warrants authorized by the AI use the default spawn name instead of the AI's chosen name

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#2025]
Game ID bNL-dp3X

In this case, I spawned with the name 'GREP', and set my name to 'E.C.O.M.' using the name popup box that appears. When placing a test warrant for an unrelated reason, I noted the bug:

![github](https://cloud.githubusercontent.com/assets/11140088/24570628/4aa7a23c-1621-11e7-96dd-f7af0d3e7df2.PNG)

**Comment by SirFruitcakes** [comment]
This probably has something to do with that pesky Cyborg ID added in Baymerge, but that's just an idea.

**Comment by Arrow768** [comment]
From what I know only the Warden, HoS + Captain have the authority to authorize warrants.

**Comment by Arrow768** [comment]
It has been confirmed that Synthetics do not have the authority to create warrants.
Therefore this has been removed from them
