### ISSUE TITLE
[Bug]: Click-drag actions fail to work

### ISSUE THREAD

**Issue by pochetoo** [Aurorastation/Aurora.3#20274]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Actions that require you to click-drag sometimes fail to work. This is especially notable in cases where clothing needs to be click-dragged to be removed, such as backpacks, which are currently unremovable barring someone else taking it off for you, and uniforms, which suffer a similar effect. Jacket items with storage slots _can_ be removed, but only if you drag it onto a table first.

### How to reproduce

1. Join the game.
2. Attempt to click-drag your backpack off.
3. Try to take drag your uniform and jacket off.
4. Suffer back pain and ask the assistant to help you.

### Round ID

cxe-cM5u

**Comment by kano-dot** [comment]
Likely introduced with the testmerge of #20256
