### ISSUE TITLE
[Bug]: Pants issues

### ISSUE THREAD

**Issue by Jasorn** [Aurorastation/Aurora.3#20312]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Strange clipping with accessories and shoes, the pants always seem to render over top of them, regardless of over/under option for shoe layer:
![image](https://github.com/user-attachments/assets/fe381e21-0ac0-4aa8-8ceb-9c6488114bd0)
![image](https://github.com/user-attachments/assets/9fc1ff03-53c9-4ba4-904c-1abf704e0201)

Renders over top of hardsuits:
![image](https://github.com/user-attachments/assets/2005f0b8-00cb-4e08-b19b-4c7a9efbc858)
![image](https://github.com/user-attachments/assets/c30278df-2322-45ce-bf6b-a3fae91091a2)

**Comment by alsoandanswer** [comment]
Use the change pants layer verb.
