### ISSUE TITLE
[Bug]: Pants not showing.

### ISSUE THREAD

**Issue by Kelnor277** [Aurorastation/Aurora.3#20310]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Pants won't render on my character.
<img width="593" alt="skirts_trouser_loadout_bug" src="https://github.com/user-attachments/assets/af5da234-2e94-4448-b793-2566a7075d41" />
<img width="1651" alt="pants_bug_report_overall" src="https://github.com/user-attachments/assets/32a8bcbb-1202-4562-91ab-f1ccb5cdfb88" />

I tried changing the skirt's layer, none of the layers made the skirt render.

### Round ID

cxo-c08e

**Comment by Kelnor277** [comment]
Also, I was in the round before with the same loadout, with no pants slot merged, and it was fine.

**Comment by alsoandanswer** [comment]
fixed
