### ISSUE TITLE
[Bug]: Unable to equip accessory sweaters

### ISSUE THREAD

**Issue by kano-dot** [Aurorastation/Aurora.3#20318]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon

### Describe the issue

Previously than the testmerge of #20240, accesory sweaters were able to be attached to uniforms. Now that uniforms and pants are their own things, there isn't any option to wear sweaters without wearing a uniform, as they cannot be worn standalone nor can be attached to the pants. 

You can still attach them to overwear stuff like jackets but you can't arrange layer order they appear. I have not tested this with rest of the accessories like shirts, scarf and such.

### How to reproduce

1. Wear a pant and remove your uniform (which game forces you to spawn with one while wearing a pant due to another oversight)
2. Detach the accessory sweater and try to equip it
3. No more fashion today

### Round ID

cxp-czCS

### Staff ckey

N/A

**Comment by alsoandanswer** [comment]
>Wear a pant and remove your uniform (which game forces you to spawn with one while wearing a pant due to another oversight)

Not an oversight. Pants are no longer uniform items.

>there isn't any option to wear sweaters without wearing a uniform, as they cannot be worn standalone nor can be attached to the pants.

Just get a smaller shirt and attach the sweater to that. It was a tough decision to make but I believe more people use the sweater as an accessory used over their clothes rather as a standalone clothing people.

Also, it's possible, but I don't think wearing a very heavy fleece or coarse fabric without any underclothing would be very comfortable.
