### ISSUE TITLE
[Bug]: High vis pants are invisible related to pants test-merge

### ISSUE THREAD

**Issue by FabianK3** [Aurorastation/Aurora.3#20320]
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

Horizon, Intrepid, Spark, Away Site, Third party ship

### Describe the issue

High visibility pants are currently invisible due to the test-merge of #20240.
Independently of the ingame layering of the pants (pants->right click->layer) they are not visible, even if all other clothing is removed.

### How to reproduce

1.) Pick high vis pants (regular or alt) in loadout
2.) Spawn
3.) High vis pants are equipped but invisible, with all three layering options, all other clothing is visible, but the high vis pants are never visible.

**Comment by FabianK3** [comment]
They are not only in-game invisible, but also in the loadout preview:

![image](https://github.com/user-attachments/assets/2b59c69d-bd4b-4ae7-9baf-dc9f6e502ca7)

**Comment by alsoandanswer** [comment]
Fixed.
