### ISSUE TITLE
Vampire Enthrall ability bugged

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#204]
#### Brief description of the issue
The vampire enthrall abilities suffers from a failure to complete after using it the first time.

#### What you expected to happen
When you initiate enthrall on a helpless/restrained target, a message shows up indicating that you bite into their neck and begin to use your 'dark powers'. Several seconds after you initiate enthrall itself, and a message shows up for both you and the victim indicating they are now enthralled.

#### What actually happened
The ability works perfectly the first time, but once you are able to reuse the ability again (i.e. after it reappears on your list of usable abilities), the message about biting their neck and invading their mind appears, but the enthrallment completion message never occurs.  This has on two occasions caused players to continue fighting or run away at the first opportunity, calling for help, due to not realizing what was supposed to have happened.  The blood count is also subtracted from your score as if you had paid for the enthrall ability.  I have waited as long a around thirty seconds before the target managed to escape by resist spamming to see if the enthralled message simply came at a random interval, but it does not seem to happen..

#### Steps to reproduce
Simply attempt to use the enthrall ability more than once.

**Comment by skull132** [comment]
This bug is literally awful.

**Comment by Kaedwuff** [comment]
What's the matter with it

**Comment by skull132** [comment]
Fixed in the rewrite.
