### ISSUE TITLE
Update new map to current Exodus standards

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#2050]
From Nanako:
 - Lowered turf temperatures in the freezer, morgue, AI core/upload, and surgery storage rooms
 - A random cooking oil tank in maintenance near the kitchen, somewhere acessible by chef
 - Several Large Stock Markers dotted around the cargo bay. approx 10-15 of em
 - Making the cargo warehouse(s) a seperate area from the main cargo bay

**Comment by Juani2400** [comment]
#2055 fixes these.

**Comment by Juani2400** [comment]
This is done. Can be closed. @LordFowl

**Comment by LordFowl** [comment]
As no other developer sent anything my way, I suppose so.
