### ISSUE TITLE
Stun Gloves made from Insulated Gloves have a Siemens coefficient of 3

### ISSUE THREAD

**Issue by Ezuo** [Aurorastation/Aurora.3#2056]
Normally insulated gloves have a Siemens value of 0, reducing shock damage completely.
Stun gloves have a Siemens value of 3, increasing shock damage. Since you, y'know, attached a bunch of wires and a power cell to them.
It seems odd that insulated gloves do not keep their value of 0, especially since they're meant to be insulated. 

Verified by Lohikar

**Comment by Lohikar** [comment]
To clarify: I'm not sure if this is a bug, but stun gloves made from insulated gloves definitely have an odd siemens coefficient.

**Comment by Alberyk** [comment]
Sounds like a feature.

**Comment by Arrow768** [comment]
Related to #2063
