### ISSUE TITLE
REPORT GRAMMAR ISSUES HERE

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2057]
Please comment on any grammar issues found in-game on this issue so I can fix them all at once instead of making tonnes of tiny one-line PRs.

**Comment by printer16** [comment]
3. Interact with no humanoid or synthetic being. that is not a fellow maintenance drone.
the period shouldn't be there

**Comment by MarinaGryphon** [comment]
`/datum/robolimb/hesphaistos` in `robo_limbs.dm`

**Comment by Wraithcraft** [comment]
/obj/item/clothing/suit/wizrobe/gentlecoat in code/modules/clothing/suits/wiz_robe.dm

It's tweed, not twead. :)
