### ISSUE TITLE
Airlock electronics cannot be operated.

### ISSUE THREAD

**Issue by TrickingTrapster** [Aurorastation/Aurora.3#2072]
Quite simply, when you unlock it with your ID, the interface just doesn't allow you to change access on the airlock electronics. I suspect it has something to do with the double-spend fix.

**Comment by skull132** [comment]
@MarinaGryphon This is most likely the result of #2053 ? But looking at the code, I didn't see anything which would outright cause this.

Requires testing, confirmation, and investigation. The report may be invalid as well, so yeh, test plz.

**Comment by TrickingTrapster** [comment]
One thing confirmed, even when the cpatain tried it the same thing happened.

**Comment by MarinaGryphon** [comment]
Does it not open at all, or can you just not change it?

**Comment by MarinaGryphon** [comment]
Your ID needs to be in your hand.

**Comment by SirFruitcakes** [comment]
I tested this out as a Drone, the Synthetic ID isn't allowing you to set access, either.

**Comment by MarinaGryphon** [comment]
@SirFruitcakes There's a special case for synths already, so it should work. It's not allowing you to set access? Weird.
So you can't choose any settings? What happens when you click unlock or whatever?

**Comment by MarinaGryphon** [comment]
In fact, it doesn't even check for the Synthetic ID. It should unlock *automatically* if a `/mob/living/silicon` tries to use it.

**Comment by Lohikar** [comment]
To clarify: it is possible to unlock the board, but actually selecting access on said board does not work.

**Comment by SirFruitcakes** [comment]
When I was trying to access the gripper'd Airlock Electronic, it would highlight whatever I clicked, but never do the action. I couldn't choose any settings; It was stuck on all access. IDK if I was doing something wrong. If it's working for Cyborgs, then it might be an issue with Drones.
