### ISSUE TITLE
Advanced Medkits don't clear wounds properly

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#2078]
When you treat a wound with gauze, the wound clears a few minutes after it's fully healed. 

Using a trauma kit, however, will heal the wound, but the injury tag never clears, and remains a bandaged bruise for, to my current counting, over an hour past the initial injuries' full heal.

It's unverified whether ointment/burn kits have similar issues, but they probably do.

**Comment by Geevies** [comment]
Fixed, I think.
