### ISSUE TITLE
It's impossible to give event hosts game panel perms without giving them +ADMIN

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#208]
Issue is self-explanatory. Game panel is critically important (not entirely but it makes things way freaking easier) in the set-up of events, but adding game panel to a user is seemingly impossible without giving them +ADMIN.

**Comment by skull132** [comment]
Requires a rewrite of perms to be implemented effectively enough. Reference #69

**Comment by skull132** [comment]
Closed due to issue clearance.
