### ISSUE TITLE
Cannot dismantle Protolathes, autolathes, and circuit printer

### ISSUE THREAD

**Issue by xTrainx** [Aurorastation/Aurora.3#2080]
If you try to dismantle any of those machines with a crowbar once it has been uncrewed, it just tries to load it and not dismantle it

**Comment by Lohikar** [comment]
Works fine in testing. Were the machines empty?

**Comment by xTrainx** [comment]
no, they had materials in

**Comment by Lohikar** [comment]
Bug confirmed for Protolathe and Imprinter, although Autolathe deconstruction appears to work fine.
