### ISSUE TITLE
Grab+ throw Bug

### ISSUE THREAD

**Issue by EthanMalakay** [Aurorastation/Aurora.3#2082]
So this happened, i was going inside my hoverpod, but one guy had me grabbed agressively or passively, when i gone inside, he threw me (ctrl + R) away and the hoverpod bugged, i had intercoms on both and it was like if i was inside the hoverpod, in the same tile, i tried to go in and it said "it is already occupied" and it is supossed that it was by me. So, that's all.

**Comment by MarinaGryphon** [comment]
Hoverpods have been replaced, this is likely not an issue anymore.
