### ISSUE TITLE
DEATH RIPLEY

### ISSUE THREAD

**Issue by EthanMalakay** [Aurorastation/Aurora.3#2085]
This is a list of ítem:DEATH_RIPLEY

First, this ítem is an exosuit that is spawned at cargo bay, not warehouse, BAY, it automatically removes its KILL CLAMP when spawned, bug too, when you get to enter in the exosuit, the red and black pain goes off and it is all yellow (the actual bug)
and when painting it with an exosuit RIPLEY modkit for example "Burning Chrome" it will get off the description of death Ripley, the current description is this:

That's DEATH RIPLEY, it is a normal ítem.
OH SHIT IT'S THE DEATHSQUAD WE'RE ALL GONNA DIE-

That was the description when u click "Examine" in it

**Comment by Alberyk** [comment]
Exosuits have a chance of spawning without a tool, not a bug.
And the modkit is also not a bug.

**Comment by EthanMalakay** [comment]
i meant the fact that when you get to enter, the red and black Paint dissapears, and it turns into a normal yellow Ripley
