### ISSUE TITLE
ERT shuttle will immediately launch when the 'Cancel Launch' option is activated.

### ISSUE THREAD

**Issue by ShameOnTurtles** [Aurorastation/Aurora.3#2099]
Haven't tested at all, but discovered this issue when there were 45 seconds left on the shuttle timer to leave ERT base, I tried to cancel it using the option in the console and it gave the radio message that launch was aborted but then it immediately after gave the message that the shuttle had launched, and it did.

**Comment by Geevies** [comment]
Should be fixed.
