### ISSUE TITLE
Laptop Vendors Borked

### ISSUE THREAD

**Issue by Ornias** [Aurorastation/Aurora.3#2100]
When purchasing a laptop from a vendor, selecting the higher level of each component will increase the price, but will not add the parts to the machine (with the exception of the card reader).

**Comment by Arrow768** [comment]
The laptop vendor can equip equips your laptop with the following components depending on your selection:

Component Type | Standard | Upgraded
Battery | micro battery | standard battery
Hard Drive | small hard drive | basic hard drive
Processor | standard microprocessor | standard processor
Network Card | basic NTNet network card | -
Card Reader | RFID card slot | -
