### ISSUE TITLE
Issue with security barriers.

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#2101]
https://i.gyazo.com/85067c52ea8f71d2fe787b5eee0c94e2.png

As you can see here, there appears to be an adjacency issue with barriers.  Someone was able to walk up to the corner here, open the blocked off door, and take every gun inside from a diagonal angle.  My beautiful secure armory, ravaged by a bug.

**Comment by printer16** [comment]
Can not replicate. There was an issue with the air that moved the guns to the other storage container. (I think.)

**Comment by Arrow768** [comment]
Just tried to reproduce it.
![grafik](https://cloud.githubusercontent.com/assets/1331699/26501170/0a7e5bc6-4239-11e7-8e99-bb4cf265b5e2.png)
Could not grab any of the items in there or open the windoor
