### ISSUE TITLE
Command and Communications software cannot be used on laptops

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#2113]
Attempting to use this after downloading the software gives the following error:

> The laptop computer flashes an "Hardware Error - Incompatible software" warning.

This is with a laptop that has every possible selection enabled.

**Comment by Lohikar** [comment]
The command and communications software can only run on stationary consoles (excluding wall consoles).

**Comment by SierraKomodo** [comment]
I'd recommend making it something that doesn't end up on laptops then

**Comment by Arrow768** [comment]
Yyour browser doesnt prevent you from downloading software that is not compatible with your devices. 
I.e. you can download android apps on your PC and vice versa, but you wont be able to run them. (Generally speaking)

The same principle applies here.
The downloader or provisioning application is just used to get the software onto the device.
Whether the device is able to run the software or not, is a different question that is answered with a clear error message to the user should the user attempt to run said software.
