### ISSUE TITLE
ED-209 attempts to arrests punpun

### ISSUE THREAD

**Issue by xTrainx** [Aurorastation/Aurora.3#2116]
a newly spawn ed-209 robot recognize punpun to be doing a level 4 infraction and starts shooting at it for some reason

![image](https://cloud.githubusercontent.com/assets/4187822/25116886/db0667f6-23e5-11e7-9562-265a778e782e.png)

**Comment by skull132** [comment]
PunPun dindu nuffin.

**Comment by Fire-and-Glory** [comment]
Security robots probably should stop trying to beat up PunPun because he has no crew ID.

**Comment by Alberyk** [comment]
Lack of security records, just set the settings or give pun pun security records.

**Comment by printer16** [comment]
Confirmed not a bug.

**Comment by skull132** [comment]
PunPun indeed dindunuffin.
