### ISSUE TITLE
You can't cut meat into cutlets with the knives provided by the kitchen vendor.

### ISSUE THREAD

**Issue by LorenzoTheMarauder** [Aurorastation/Aurora.3#2117]
The knives that are stocked by the Dinnerware kitchen vendor are "steel knives" not "kitchen knives" if that makes any difference in the code. You can cut raw dough into slices but you can't cut the meat that spawns in the fridge roundstart. It just doesn't work whether you click on the meat with a knife while it's in your hand or on the table. And doing it on a tray just adds the knife to the tray.

EDIT: It'll cut literally anything else except the meat in the freezer.

**Comment by Alberyk** [comment]
I am nearly sure it is because regular knives are just silverware like forks, while kitchen knives can do all kitchen related work.

**Comment by ToasterStrudes** [comment]
At round start, sometimes extra knives spawn, some of them do not work, but at least two of them are able to in the vendor

**Comment by Alberyk** [comment]
Not a bug, use the kitchen knife.
