### ISSUE TITLE
pAI Crew Manifest is broken.

### ISSUE THREAD

**Issue by cha0s5150** [Aurorastation/Aurora.3#2124]
If a pAI downloads the crew manifest program they are not able to view the crew manifest. I took a screenshot last time I tried this.

![capture](https://cloud.githubusercontent.com/assets/8349369/25311054/0ca90858-27bb-11e7-8e4f-9b0f804b9747.PNG)

This is what I got last time I tried to use the crew manifest as a pAI.

**Comment by Karolis2011** [comment]
Todo for #6814

**Comment by Geevies** [comment]
I believe this was fixed.
