### ISSUE TITLE
[Newmap] Supply shuttle is missing its top wall

### ISSUE THREAD

**Issue by Ezuo** [Aurorastation/Aurora.3#2132]
Basically, when the supply shuttle is called, it doesn't have a top. This means the entire cargo bay gets vented, as in the picture below.

http://puu.sh/vxYsw/bed1630e4b.png

**Comment by Lohikar** [comment]
Still seems to be happening.

**Comment by LordFowl** [comment]
Yes, I accidentally forgot to fix this, despite remembering it as if I did. Easily remedied, nonetheless.
