### ISSUE TITLE
Robot Brain/MMI Bug

### ISSUE THREAD

**Issue by Jboy2000000** [Aurorastation/Aurora.3#2136]
Game ID: b0d-aRd4

A robot self destructed, somehow, and spawned one of these.

That's a robotic intelligence circuit. It is a normal-sized item.
The pinnacle of artifical intelligence which can be achieved using classical computer science.

I was hoping to see see if I could somehow how check their laws with this, so I left clicked the item, and got this message.

You upend the MMI, spilling the brain onto the floor.

And then, a brain spawned, there was an invisible MMI in one of the hands, and then boinks happened, and I was asked to make this.

**Comment by SirFruitcakes** [comment]
I was told this bug has been fixed, and so I comment here so this issue can be closed or... well, fixed.
