### ISSUE TITLE
You can't convert security officers to cult.

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#214]
It seems it is impossible to convert security officers, or other rules; need testing, using the cult rune.

Also; it shows that messages, while not bring up the option to join or resist;

AAAAAAHHHH!
Your blood pulses. Your head throbs. The world goes red. All at once you are aware of a horrible, horrible truth. The veil of reality has been ripped away and in the festering wound left behind something sinister takes root.
And you were able to force it out of your mind. You now know the truth, there's something horrible out there, stop it and its minions at all costs.

**Comment by Kaedwuff** [comment]
You were a cultist just last night, and went crazy over ir.

**Comment by Alberyk** [comment]
An admin changed my status to cultists using admin commands, that is why.
