### ISSUE TITLE
Mech Internal Air tank still causes IPC's to overheat

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#2148]
if you set up the Internal air tank to fill the cabin with pressure, it still causes IPC's to overheat. Even when you empty the Mechs original tank, and fill it with a super-cooled gas, as soon as it goes into the cabin, it is heated to ~290k.

**Comment by EJDenton** [comment]
I can add to this. After ToasterStrudes and I tried altering the internal tank temperature, I made a glass chamber around the mech, cooled the air within it to -130 Celcius and had the mech use the environmental atmosphere. In the exosuit stats it showed the cabin temperature match the external temperature at about -130 celcius. Then, with the internal tank already cooled to -130 as well, I turned on the internal tank and watched the cabin pressure go right back to 293K/20 Celcius.

I should note that when the exosuit was using the cooled external air, my IPC did not overheat. When I went to the cooled internal tank I began to overheat. It seems like regardless of the status of the internal tank the cabin pressure and temperature revert to station norms.

For reference, ToasterStrudes is a baseline IPC and I am a shell. He overheated slower than I did which seems to be appropriate but we both overheated in the end.
