### ISSUE TITLE
Runtime (the cat) being lazy.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2159]
So it seems to be an issue with Runtime, that whenever she lies down, she wont get back up again for the longest of times. She will even go to great lengths of mice chasing while laying down, but she'd be too lazy to actually attack them, letting them drag her along the floor.

Make Runtime git gud please. Medbay needs its rodent exterminator.

**Comment by NanakoAC** [comment]
already fixed internally by #2131

**Comment by skull132** [comment]
Bug reports should be kept active until the PR/commit ends up in master, @NanakoAC :l

**Comment by Lohikar** [comment]
Associated PR seems to be stalled; reopening.
