### ISSUE TITLE
Circadian Rhythm.

### ISSUE THREAD

**Issue by LR001** [Aurorastation/Aurora.3#2190]
I was playing AI one round and every time I disabled the night lighting after the Circadian Rhythm dimmed it, Five minutes later it re-dimmed. I tested this four separate times just to make sure it was me doing it. And it was.. So if you undim the lights with the lighting console after the Circadian Rhythm thing plays five minutes later it re-dims them playing that loud noise and announcement.

**Comment by Juani2400** [comment]
I can confirm this happens like described.

**Comment by Lohikar** [comment]
[internal screaming]

**Comment by Lohikar** [comment]
Fixed in development which should be merged soon:tm:, so not going to bother with a fix for master.
