### ISSUE TITLE
[Newmap] Solars are statically lit

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2192]
![2017-05-07_13-14-20](https://cloud.githubusercontent.com/assets/7097800/25783755/1f6f796e-3327-11e7-94b4-20dfd1a4885f.png)

**Comment by OneOneThreeEight** [comment]
Question. If the surface is completely dark around the solar panels, how do the solar panels gather light to turn into raw power?

**Comment by Lohikar** [comment]
¯\\\_(ツ)_/¯

They could probably be made to emit light to make them less immersion breaking.

**Comment by OneOneThreeEight** [comment]
It'd be less work in coding some random moving light bullshit that simulates nearby starlight.

**Comment by Lohikar** [comment]
Less work in a moving light, or less work in making the solars emit light?

Making the solars themselves emit light is a lot simpler.

**Comment by LordFowl** [comment]
Optimally the surface level would be lit fully periodically or persostently as it is open to space. In reality, it's all a little confusing.

**Comment by OneOneThreeEight** [comment]
Less work in an actual light cycle as proper as the station will be based on one side + the interior of an asteroid.

**Comment by Lohikar** [comment]
Unfortunately a very large light such as would be used to simulate a sun is
expensive performance-wise. While not as realistic, having solars emit
light is much much cheaper.
