### ISSUE TITLE
IPCs don't have brains, or something

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#221]
After a mishap with an ion rifle as an IPC, someone attempted to remove my brain a while later, and there wasn't a brain inside of the head. They tried keeping the head attached at first, no brain. Then, removing the head. No brain. Re-attaching the head? Still no brain.

This just adds on to the pile of how much bay hates IPCs and how much we lost in the port.

**Comment by Talkarcabbage** [comment]
I think that was actually fixed in bay dev branch and may have been merged into master since, but I believe if we wanted to use it we'd have to also merge some sort of organ rework that they did. Believe skull planned to address this using polaris androids, though.

**Comment by skull132** [comment]
Fixed.
