### ISSUE TITLE
[NEWMAP] Can't enter sleeper pods in medical

### ISSUE THREAD

**Issue by VikingPingvin** [Aurorastation/Aurora.3#2212]
HoP. No right click menu to enter sleepers. Left click opens the sleeper interaction UI.

**Comment by Juani2400** [comment]
Not related to the map. This has been happening for a while. You need to drag yourself into the sleeper.

**Comment by VikingPingvin** [comment]
So...it is an intentional "feature" to remove the right click option?

**Comment by skull132** [comment]
Baydevs were fucking idiots when removing right click interaction, but it's not a bug. Closing, possibly reimplementing at some point.
