### ISSUE TITLE
[NEWMAP] Tranquilizer cabinet showing into the brig lobby -JUANI

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2216]
![bug](https://cloud.githubusercontent.com/assets/24979527/26028389/68e6d68a-37ed-11e7-9ff2-5e34d4ec6e97.png)

**Comment by LordFowl** [comment]
It is also accessible from the lobby.

**Comment by Juani2400** [comment]
Handling.
