### ISSUE TITLE
[NEWMAP] New possessions box is bigger on the inside then on the outside

### ISSUE THREAD

**Issue by Weer6** [Aurorastation/Aurora.3#2219]
1. Go into Autolocker
2. Get possessions box filled with your things
3. take aall the garbage out, put small/tiny things of immense value.
4. Notice how it holds more then four small things.
5. cackle in glee.

**Comment by LordFowl** [comment]
All boxes work like this. Boxes do not have defined slots amounts.

**Comment by skull132** [comment]
Not really avoidable with the way the system is written.

A minor evil.
