### ISSUE TITLE
[NEWMAP] Issues With XenoFloral -JUANI

### ISSUE THREAD

**Issue by Dawsinn** [Aurorastation/Aurora.3#2220]
In the New map XenoFloral is missing a crucial part of it's utility: XenoFloral Disks

Also, The atmospherics control area in XenoFloral needs to be touched up with a Canister of air, An atmospherics Control computer, and a buffer between the air controlled area and the Xenofloral Lab.

**Comment by Juani2400** [comment]
Handling.
