### ISSUE TITLE
[:NEW: :MAP:] No guest pass terminals -JUANI

### ISSUE THREAD

**Issue by xTrainx** [Aurorastation/Aurora.3#2222]
was trying to look for a guest pass terminal to see if my access have changed, but i couldn't find a single one. Were they removed on porpouse?

**Comment by Juani2400** [comment]
Handling.

**Comment by Juani2400** [comment]
You didn't look properly, gotta say. There were 4 existing terminals at the time of the testing: Command, Medical, Engineering and in the HoP's office. However, I've added more. One in every department, and two accessible by anyone on the hallway.
