### ISSUE TITLE
[Newmap] Lift doors immediately close when called.

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#2224]
The lifts should wait some time to allow for disembarking before going down/up to a call that has been made.

**Comment by skull132** [comment]
Code issue.

**Comment by Lohikar** [comment]
Caused by increased delay accuracy from lifts being converted to timers.

Simply increasing the delays on the elevator datums should suffice.

**Comment by Geevies** [comment]
I think this is fine by now.
