### ISSUE TITLE
Logistical suggestion with Kitchen/Hydro

### ISSUE THREAD

**Issue by YuriDaruski** [Aurorastation/Aurora.3#2225]
Previous station gave the ability for Hydroponics to place items in the space fridge regardless if a chef was present. Current station requires Chef to be present. In the new system Hydroponics will have to leave all of their products laying about on the ground. Suggest placing a Space Fridge in an accessible area for both the chef and gardener to access.

**Comment by LordFowl** [comment]
Both kitchen and hydro have their own fridges. Once a chef joins hydro can remove things from their fridge to give to the chef. Not much better solution available beyond giving them both communal access.

**Comment by YuriDaruski** [comment]
Alright, couldn't see much into Hydro when I went by, had spawned with no ID at all
