### ISSUE TITLE
[NEW MAP] Anesthetic tanks don't work properly

### ISSUE THREAD

**Issue by ariever** [Aurorastation/Aurora.3#2229]
((I JUST NOTICED I FUCKED UP)) Anesthetic tanks don't distribute anesthetic properly. I was doing surgery on someone with broken legs, and first, it tool a good thirty seconds for them to go under, and during the surgery they woke up again. It was like they had a burst lung, without any lung damage. Soporific seems to work, though, and I gave him that instead.

**Comment by ariever** [comment]
((I JUST NOTICED I FUCKED UP)) Anesthetic tanks don't distribute anesthetic properly. I was doing surgery on someone with broken legs, and first, it tool a good thirty seconds for them to go under, and during the surgery they woke up again. It was like they had a burst lung, without any lung damage. Soporific seems to work, though, and I gave him that instead.

**Comment by LordFowl** [comment]
Fill out the form properly.

**Comment by LordFowl** [comment]
Probably not a new map bug? Uhh.

**Comment by Lohikar** [comment]
I made changes to potable tanks' air fill in development, likely cause.

**Comment by skull132** [comment]
Duplicate of #3095.

Closing this one as the newer one is assigned and has more information.
