### ISSUE TITLE
[NEW MAP] All bugs noted by the AI at time of leaving.

### ISSUE THREAD

**Issue by Jackmason558** [Aurorastation/Aurora.3#2230]
~* Awkward lines everywhere outside of camera range
http://i.imgur.com/vUGpyta.png
http://i.imgur.com/DCbSIrI.png~
~* No quick way to swap levels, or easy ways of knowing the labels of which levels in the camera network are where. Either add a hotkey for layer swapping, or relabel camera networks to be easier to understand~
* Engineering does not have access to cameras on the engine.
~* Tranq Cabinet in HoS office can be seen and touched from the outside, albeit locked.~
~* Vault Elevator = No Atmospherics.~ (Cannot confirm)
~* Chem dispenser and Sulphuric Acid dispenser in Science are without any chemicals at all.~
* Engineering has access to robotics via substation
* Medbay fore entrance button not connected to door.
~* Cargo tech has no access to warehouse~
~* No cameras leading to vault (Intentional?)~
~* Chauncy may starve behind secure windows. Add food chute?~ (There is a door.)
~* Holodeck non-functioning~
* EMT no EVA access
* Missing cameras in a lot of different locations, disallowing helping of many people. Example: Almost no cameras to any sort of EVA access.
* Generator supplied to Engineering runs on Tritium. No tritium available.
~* Hydroponics supplie north door errored access.~ (Cannot confirm)
* Maintenence tunnels appear to connect to a LOT of places, giving access where they should not.
~* Power does not transfer over Z levels.~ (? It does?)
* Interior access button to arrivals docking exterior access doesn't work

**Comment by Lohikar** [comment]
There is already verbs for switching between Z-levels as AI.
IC tab -> Move Up / Move Down.

**Comment by LordFowl** [comment]
I'm just going to cross out the duplicates/false flags.
