### ISSUE TITLE
Differance with R&D - Forgot? - Containment Shutters

### ISSUE THREAD

**Issue by YuriDaruski** [Aurorastation/Aurora.3#2232]
Previous Station's R&D included a Containment Shutter system, allowed for walling off R&D incase of a mass slime outbreak, golden slime core release, or other things that may endanger R&D from within or outside. New R&D department does not seem to include this aspect. Unsure if it was overlooked or was a design choice.

**Comment by LordFowl** [comment]
aka turn RnD into a fortress simulator. Will need to review this with other mappers.

**Comment by YuriDaruski** [comment]
That was the main reason I assumed it may have been a design choice
