### ISSUE TITLE
[NEW MAP] Robotics won't sync With RnD servers

### ISSUE THREAD

**Issue by xTrainx** [Aurorastation/Aurora.3#2234]
I'm not sure if it's that Robotics can't synch into the Research server, or if RnD can't synch into the research server or both, but synching up RnD labs with with the server while having researches doesn't let Robotics synch their database with Then to get the research as well. I have not been able to try the other way around.

**Comment by xTrainx** [comment]
Update: Exosuit fabricators wont sync either

**Comment by MarinaGryphon** [comment]
I know how to fix this, I believe. I fixed it in-game as a maintenance drone. The access settings on the Robotics server are all off by default, need to add access rights.
