### ISSUE TITLE
[NEWMAP] Telescience starts with only one crystal.

### ISSUE THREAD

**Issue by MarinaGryphon** [Aurorastation/Aurora.3#2236]
This means it has an absolutely pitiful distance. And I don't believe you can get more through research?

**Comment by LordFowl** [comment]
You can get more TC through both research and xenobio.

**Comment by MarinaGryphon** [comment]
Oh, really? So this is intended?

**Comment by LordFowl** [comment]
No. TC should start with 3 crystals iirc.

**Comment by MarinaGryphon** [comment]
It had 4 on oldmap, which gets it up to 25 like normal.
