### ISSUE TITLE
[NEWMAP] Forensics Technician and Detective Have Identical Accesses

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2244]
Title, unsure if it's intentional.

**Comment by LordFowl** [comment]
Intentional.

**Comment by skull132** [comment]
They're the same job, still, no?

Alt title based access isn't a thing currently allowed by code.

**Comment by Alberyk** [comment]
They had difference access in old code, so, I will get on this

**Comment by Alberyk** [comment]
Fixed in #2260
