### ISSUE TITLE
Spiders grow faster then Alberyks lust for crushing dreams.

### ISSUE THREAD

**Issue by Weer6** [Aurorastation/Aurora.3#2251]
Step1: get spiderlings
Step2: oh shit, they became real spiders, FUCK!
step3: beat htem to death before they maul you.
Step4: note how it took under five secons for baby spiders to become real spiders after they leave whatever infected person.

**Comment by MarinaGryphon** [comment]
This is known. They start growing when they're inside you, I believe.

**Comment by skull132** [comment]
I'm meant to be looking into spider code this cycle, so will tag it as mine.

**Comment by Juani2400** [comment]
The few spiderlings that spawn around the station on map generation should be removed, as well. One of them turned the second OR into a massive nest.

**Comment by skull132** [comment]
Deemed a non-issue.
