### ISSUE TITLE
[NEW MAP] Arrivals Shuttle Override Needs to be Locked Away

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#2254]
Only badmins at CC should be able to override the arrivals shuttle. Otherwise regular nubs will crash it.

**Comment by skull132** [comment]
Add to this:

Move the autlocker dealies so that everyone going to the shuttle is squarely confronted with them. As testing demonstrated, too easy to miss with them being tucked away to the left.

**Comment by LordFowl** [comment]
Indeed. I am planning to change them to autogateways. More efficient that way, too.
