### ISSUE TITLE
[NEWMAP] Buttons / Consoles being visible through walls

### ISSUE THREAD

**Issue by Arrow768** [Aurorastation/Aurora.3#2256]
There are a few buttons / consoles being visible through the walls.

The ones I remember:
- HoP Privacy Button, at the bridge Entrance doors
- Various consoles and buttons at HoP Maint
- Medbay treatment shutter button from the hallway

**Comment by Lohikar** [comment]
This still happening?

**Comment by Arrow768** [comment]
Yes, I think the one from the HoP are still around.

**Comment by Geevies** [comment]
Think this has been mostly fixed.
