### ISSUE TITLE
Spiderbots cant die

### ISSUE THREAD

**Issue by NewChromia** [Aurorastation/Aurora.3#226]
As a spiderbot, one appears unable to die. Only tested with repeated accidental shocking of oneself.

**Comment by SoundScopes** [comment]
Lessick and I used to abuse spiderbots with admin commands. Never been able to kill one.

**Comment by Bedshaped** [comment]
Drones can't die in certain situations either. To be more specific; try being a drone vs. a carp. The carp will just keep attacking the drone who will sit in minus somenumber % integrity.
