### ISSUE TITLE
Blobs spawning infinite amounts of metal.

### ISSUE THREAD

**Issue by Butterrobber202** [Aurorastation/Aurora.3#2296]
Alright so, when a Blob tries to destroy the HoP's console, it can't. But it does.

To explain, the blob 'breaks' the console and the message appears, as well as the metal drops. But, the console is not deleted/removed so the blob just keeps breaking it, spawning more metal.

**Comment by printer16** [comment]
Not just blobs. Seems to be anything that can break consoles. Confirmed.

**Comment by OneOneThreeEight** [comment]
This is a console-specific issue. Not with walls or such. Anything that does damage to a console does not properly delete it but rather damages it over and over, wherein it outputs leftover metal from its destruction.

Specifically witnessed from derp pylon AI not properly acquiring its targets and repeatedly hitting the console over and over, making metal on the tile the console was located on.
