### ISSUE TITLE
Certain cult runes when activated repeatedly cause their effect until the user steps away from/is interrupted in using the rune. 

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#2297]
This causes immense amounts of spammy cult actions, in one such case cultists spammed a sacrifice rune on a person three times, causing the three cultists to chant 3 times a second per person until one of them stepped away from the rune.

This also caused nar'sie's first recorded octo-summon on the server, creating a record total of eight nar'sies which had to be individually deleted. Hilarious, but unfortunately it created approximately 5700~ mobs across all of the applicable z-levels. Also crashed the controller that handles nar'sie summoning like three times and both the obj and mob processer were hung indefinitely until the round was over, as the summoned mobs did not properly attack non-cultist enemies.

**Comment by Lohikar** [comment]
Technically the mob processor was still responsive, it was just taking multiple seconds to complete a tick.

**Comment by NonQueueingMatt** [comment]
Fixed
