### ISSUE TITLE
PDA messenger returning undefined when opened

### ISSUE THREAD

**Issue by KepQwet** [Aurorastation/Aurora.3#2302]
Round-ID: `bOx-bzxG`

![Relevant image](https://i.gyazo.com/345efb3911b535b068d8701c1651b742.png)

Tried clearing cache and reset-PDA verb, neither worked.

**Comment by skull132** [comment]
Do you remember if you used any of the filters before this, and are you able to reproduce this issue at all?

**Comment by KepQwet** [comment]
What do you mean by filters? Also, no, I have not seen the issue occur again since the round in question.

**Comment by skull132** [comment]
Closed during issue clearance.

Unable to replicate.
