### ISSUE TITLE
Closed crates can be pushed into barriers

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2306]
![mk0wez](https://cloud.githubusercontent.com/assets/7097800/26229566/47f2ce2e-3c08-11e7-9f7c-7438395379e9.gif)

Bug present on both master and development.

**Comment by Arrow768** [comment]
Most likely related to @NanakoAC´s update that allows pushing closed created under tables

**Comment by Alberyk** [comment]
Also works with racks.
