### ISSUE TITLE
Machine overload with APCs

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#2317]
Basically, when you wish to machine overload one APC, instead of destroying a room. IT DESTROYS A ENTIRE FUCKING DEPARTMENT.

https://gyazo.com/c80a9167983f042791d726cd66d6d516

**Comment by printer16** [comment]
equation for overload for ref: explosion_intensity = 4 + round((A.cell.charge / CELLRATE) / 100000)

**Comment by printer16** [comment]
PR relating to the issue: #2425
