### ISSUE TITLE
[NEW MAP] Autodrobes make assistants naked.

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2329]
The new autodrobes are broken for assistants, just removing all their clothing and replacing it with nothing.

**Comment by skull132** [comment]
GOOD.

**Comment by LordFowl** [comment]
The issue appears to be purely graphical - the assistant is equipped but they appear naked until the next icon update.

**Comment by skull132** [comment]
Was this fixed?
