### ISSUE TITLE
[NEW MAP] All northen tank injectors need to be set to injecting by default

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#2330]
![Image](https://tzli.me/i/qgMn3CH7N4)
As it stands they are all set to 'on hold'.

**Comment by Moltenkore** [comment]
This still is not fixed fully, the tanks are now set to output but not inject meaning gas will just stop flowing when the mixed air tank empties. This also applies to the nitrogen and oxygen tanks.

**Comment by LordFowl** [comment]
Perhaps the fact that the issue is not closed should indicate that we are aware that it has not been solved fully?

**Comment by Moltenkore** [comment]
@LordFowl perhaps the additional comment is indication of an update to the current issue from an external body that has zero knowledge of your internal discussion or awareness as to the state of the issue as it stands at the moment.

**Comment by LordFowl** [comment]
It is quite simple;
Issues that are open have not been solved, and do not need further update unless it is to expand on the issue.
Issues that are closed have been solved.

**Comment by Moltenkore** [comment]
@LordFowl Although I don't want to pollute this steam of unneeded comments any further it has to be said that your attitude in general is appalling (both here and most other places that I've seen you interact). There was literally no need to reply to my comment in the first place as it was completely unnecessary. The comment I made at the beginning of this chain could be seen as an expansion to the current issue because it has changed in state since the issue was reported in the first place. Anyone working on it whom has not worked on the issue prior would know exactly where it stands right now. Perhaps it doesn't really matter as the issue is rather small in comparison to anything major however the same thought process applies.

**Comment by skull132** [comment]
Ladies, chill. plz.

It'll be fixed whenever Fowl, Juani, Keknar, or Alberyk get around to sweeping up more minor bugs and hit this one as well. There's no priority queue or set order of execution for any fixes other than major ones, so when it gets fixed is up to the devs and where they start on the issue tracker.

**Comment by Juani2400** [comment]
We got a new atmos room. Not needed anymore.
