### ISSUE TITLE
[New Map] Various AI Issues

### ISSUE THREAD

**Issue by Arrow768** [Aurorastation/Aurora.3#2331]
During round bOz-cV5R I noticed a few things while playing AI:
 ~~* Moving up or down a z-level via the IC-> Move Up / Move Down verbs, moves the eye up or down, but only shows static.~~
~~* After a certain duration, I was no longer able to move the eye around and was stuck to the view of the core. Carding and uploading again into the core fixed the issue. (Itzal / Skull might know something about the cause)~~
~~* The AI Eye is moved up and down with the elevator~~
~~* If the AI Eye is moved up and down with the elevator, cameras are working as expected~~
~~* It seems the AI eye is crushed by the elevator. (The AI Eye was under a downward moving elevator. When the elevator reached the floor of the AI Eye, the screen went black)~~
* I have experienced multiple client crashes, especially when moving up or down z-levels

**Comment by Arrow768** [comment]
IC -> Move Up / Move Down works. Was a user error.

**Comment by skull132** [comment]
Lazy fix is inplace.

**Comment by Arrow768** [comment]
After playing some more rounds, I found that the client crashes usually happen when moving up from the research sublevel / xenobio to the main level.

If I try to move up above the AI core area, then it works fine
But moving up at xenobio often results in a client crash (for me)

**Comment by Arrow768** [comment]
@HetNeSS Can you reproduce this aswell ? (Client Crashes when moving up from xenobio to main, but not when moving up from ai core to main)
Or are you crashing when moving up / down at different areas ?

**Comment by HetNeSS** [comment]
No, I cannot reproduce this. There is people being had to reconnect while playing as an AI, happened almost each round. It can happen like, once, or 12 times in a row. Ask players, maybe they can tell more.

**Comment by Arrow768** [comment]
Looks like thats resolved
