### ISSUE TITLE
[Newmap] Garden in the surface receives all trash

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#2344]
The bin in the Surface Garden throws out all the trash that's thrown in the upper level.

**Comment by Alberyk** [comment]
This is still happening.

**Comment by Juani2400** [comment]
Given that I'll possibly not be able to map until Thursday, I'll explain
why this probably happens.

When trash gets to the next junction in their path, and can't pass because
the junction is wrongly mapped or set, the trash will go back again and
take a turn in the next non-restricted direction. That is, if the junction
that is behind has an arrow pointing the way the trash is returning from,
it will turn. If this happens, the trash will just spill out at the bin,
end of the line.

So. Figure out if it's a junction problem, or if the trunk going to the
lower level is not properly mapped. It's almost safe to say it has to do
with this.

**Comment by Juani2400** [comment]
Remind me not to answer a comment from my email ever again.
