### ISSUE TITLE
[NEW MAP] Mine turfs sometimes lose their sprite

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#2346]
If an explosion happens it leaves a black tile which when right clicked just shows up as sand, rods cannot be placed on top of so a lattice and floor are impossible to create.

**Comment by Lohikar** [comment]
This is caused by an error in the icon smoothing engine. It is still possible to place lattices on the turfs by dropping an object on the tile and alt-clicking on it to bring up the Turf menu; the turf is now selectable at the top of the list.

**Comment by skull132** [comment]
@Lohikar You touched smoothing. Is this fixed?

**Comment by Lohikar** [comment]
Not fixed, haven't gotten around to investigating. Recent PR to smoothing only affected diagonal smoothing, which is not used by mine turfs.

**Comment by Moltenkore** [comment]
A way to trigger this is making a decent sized explosion and then placing lattice on the sides of the remaining floor, the adjacent sand tiles will then lose their sprite.

**Comment by Lohikar** [comment]
I'm *fairly* sure I've fixed this, closing.
