### ISSUE TITLE
[NEW MAP] Arrivals air canisters should be attached to distro to prevent shuttle non-dipartures

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#2355]
![image](https://tzli.me/i/DejUnhfnFf)

A simple blue to universal then a pump to refill the canisters is all that's needed so that the arrivals shuttle doesn't get stuck in an infinite airlock cycle.

This also applies to some airlocks however I assume most are intentionally not refilled by default.

Edit: Also includes departures shuttle

**Comment by LordFowl** [comment]
Infinite airlock cycles are caused by people getting impatient and hitting overrides when they shouldn't. As the arrivals airlock is not used to go EVA, this should not be a common occurrence.
