### ISSUE TITLE
[NEWMAP] Robotics has no eye protection.

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2357]
The robotics lab doesn't spawn with any welding masks or welding goggles, you have to beg from cargo or engineering to get one of your most essential tools. 

Also the robotics vendor spawns with something like 12 high capacity cells which kind of trivializes a lot of the early-mid R&D development stages for robotics.

**Comment by Alberyk** [comment]
I fixed  this in my last mapping update, should be in the same place with the wire toolboxes.
