### ISSUE TITLE
[New Map] Mining Issues

### ISSUE THREAD

**Issue by AllyBearsley** [Aurorastation/Aurora.3#2366]
I have done the search and apologize if I missed something. I have never used github before, so if this is a duplicate then feel free to delete.

Anyway two problems with Mining:
1. Girders around the "crashed ship" will disappear once they reach the sand of the asteroid. One girder was already in the sand so although it was there to prevent me from moving I could not interact with it or move it away.

2. The mining airlock access will not open once the button is pressed. I pressed the button and waited about five minutes. Didn't even see the air begin to cycle. It seems the center console inside the actual airlock is the only way to open or close the door. For one miner this might not be much of an issue but when multiple miners are present it could be very troubling.

**Comment by VikingPingvin** [comment]
Regarding 2)  I think it is the outer button that does nothing.

**Comment by LordFowl** [comment]
Issues are obsoleted by upcoming PR
