### ISSUE TITLE
[NEWMAP] Litterally Half of atmos is turned off

### ISSUE THREAD

**Issue by Grant4455** [Aurorastation/Aurora.3#2379]
The Mixed Air Tank drains to 0.3 KPA after a short time on the station. The system is set to mix the gas, but the actual input valve is set to 'on hold'. So you get a retartedly high kPa in the mixing pipe, an empty mixing tank, and after like, two hours, the whole station would start to die.

Literally just flip the Mixed Tank input to 'injecting' instead of 'on hold'.

On further inspection, The N2 and 02 tanks are also set to 'on hold'. The entire return loop will break the first time anyone adds any 02 or N2 to the lines.

**Comment by LordFowl** [comment]
https://github.com/Aurorastation/Aurora.3/issues/2330

**Comment by Grant4455** [comment]
Ah sorry, only checked four pages back. Will happily close.
