### ISSUE TITLE
[NEW MAP] MegaSeed Servitor does not accept seeds or mycelia as expected

### ISSUE THREAD

**Issue by Synnono** [Aurorastation/Aurora.3#2386]
All MegaSeed Servitors on NSS Aurora II map cannot be restocked like Exodus map counterparts. Attempting to restock seeds by hand, whether maintenance panel is open or closed, results in an attack. Attempting to restock seeds from a plant bag into a MegaSeed Servitor also results in an attack.

Behavior was consistent. With no place to put them there can be large stacks of seeds piling up on the floor.

**Comment by LordFowl** [comment]
Likely because the MegaSeed Servitor is a different machine entirely from the Exodus seed fridges. I'll need to investigate the exact differences.
