### ISSUE TITLE
[Newmap] Virologist Cannot Lock Down Virology

### ISSUE THREAD

**Issue by NoahKirchner** [Aurorastation/Aurora.3#2388]
The button outside of the virology airlock to lock down virology is not accessible by the virologist.

**Comment by LordFowl** [comment]
The virologist/MD accessible one is inside. The one on the outside is mostly designed for lifting a lockdown, which only the CMO should be able to do from the outside.

**Comment by Juani2400** [comment]
Intended, as described above. Closing.
