### ISSUE TITLE
[Newmap] Mining Drones spawn active.

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#2404]
Mining Drones spawn active, and when you swipe them, they die. After dying, they can't be rebooted and can only be refunded. This makes playing a Mining Drone currently impossible without being forced into the mob by an Admin.

**Comment by printer16** [comment]
I can swipe them to reactivate just fine.

**Comment by SirFruitcakes** [comment]
Printer, that wasn't the issue, you can swipe them but they won't bring it back to life.
