### ISSUE TITLE
[Newmap] Mining Drones are unable to drag Ore Crates and other Objects

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#2405]
This may not be a bug, but it makes it very hard to do what you're meant to do, since you're unable to smelt Ore for Mining. It makes Mining Drones unable to independently mine.

**Comment by LordFowl** [comment]
You do not need an ore box for smelting - the ore just needs to be infront of the belt machine

**Comment by SirFruitcakes** [comment]
If that's true, disregard this report unless you see it being relevant later.
