### ISSUE TITLE
[New map] Shields appear to not be multi-level, also no hull shield spawned in hard storage

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#2406]
Old map had 2 bubble shields(why 2?) and 1 hull shield spawned into hard storage. Newmap only has two bubble shields.

You can imagine that you don't want to have to install a shield generator on every level because of meteors

**Comment by Lohikar** [comment]
Meteors should only be able to hit the top surface level and the roof.

**Comment by LordFowl** [comment]
No hull shield is a bug, rest is not
