### ISSUE TITLE
Scanner bed collision getting switched with console

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#241]
This issue may have existed before the recent update which changed sleeper console collision, i hadn't paid it much attention until now so can't say

There's two kinds of medical beds, the Sleeper and the Scanner, both have a console on them in the adjacent tile, filling two tiles in total. a recent update fixed it so that the console's tile was not obstructed, allowing people to walk on it and be closer to the console. This was good. 

I did some testing today, and it seemed to be working well. The expected behaviour is that the bed is solid and obstructs movement, while the tile does not.

However frequently in practise, especially when bringing in wounded patients, i'm seeing an odd issue with the scanner bed. It may or may not affect the sleepers too.

The issue is, the bed stops obstructing movement, and the console starts obstructing movement again, essentially the two of these swap their collision status.

I've not dound a reproduction to cause this switching yet, i will update this if i can find one?

**Comment by skull132** [comment]
The issue isn't as you describe it.

I accidentally edited the scanner's density, as opposed to the scanner console's density var. They aren't ever switched, they just are bad from the get go.
