### ISSUE TITLE
Parallax not working as intended

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#2412]
It simply does not work when you're playing, you see nothing moving in space. It does work when you are a ghost for some reason.

**Comment by skull132** [comment]
@Lohikar

**Comment by SleepyWolfe** [comment]
This is weird because I had the same issue, but reversed. I saw it in game, but not when I died as a ghost - it just reverted back to old non-parallax space.  Toggled preferences to try and fix it, did not work.

**Comment by Lohikar** [comment]
This is a BYOND bug; restart your client and it should fix itself.

**Comment by AgentWhatever** [comment]
For a bug this is a consistent issue I've been having since the implementation of it on oldmap and now on newmap

**Comment by Lohikar** [comment]
Does lighting work for you?

**Comment by AgentWhatever** [comment]
Had no issues with the lighting

**Comment by Lohikar** [comment]
If this is a new bug (newmap), probably related to a parallax image caching change made in development.
If the bug is on the Exodus, I have no idea.

**Comment by AgentWhatever** [comment]
The issue is exactly the same on both oldmap and newmap. I have done everything I could to remove the bug client-side

**Comment by Lohikar** [comment]
To double check, you have at least BYOND 510 (preferably 511), @AgentWhatever?

**Comment by AgentWhatever** [comment]
Yes. Yes I do

**Comment by Lohikar** [comment]
This was fixed at some point with one of the parallax bugfix PRs, I believe.
