### ISSUE TITLE
[New map] (not sure if intended) By default the engineering sublevel will have some of its APC's not charging due to the power network layout

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#2413]
Maybe put in a circuit breaker somewhere? Or leave it be and expect engineering to be smart enough to fix it.

**Comment by Lohikar** [comment]
The APC in the tesla room is supposed to be charged by its own SMES, which is supposed to start pre-charged like the Supermatter engine's SMES.
