### ISSUE TITLE
[Newmap] Leg breaking teleportation. And space breaking

### ISSUE THREAD

**Issue by ForgottenTraveller** [Aurorastation/Aurora.3#2416]
When using a hand teleporter. I was shifted to a different area then desired. Upon arriving on the space only Z level. Both my legs broke and I was put into crit.

I have also noticed similar events where people falling off ledges into space z levels, will 'hit' the open space at the bottom. Break their legs and fly off at an angle.

**Comment by printer16** [comment]
"When using a hand teleporter. I was shifted to a different area then desired"
Intended most likely.
"I have also noticed similar events where people falling off ledges into space z levels, will 'hit' the open space at the bottom. Break their legs and fly off at an angle."
Hitting space and getting hurt is a bug.
