### ISSUE TITLE
[Newmap] Janitor's access is a bit funny in some areas

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#2417]
Janitor's really have an impressive range of access on newmap.

Also rather eccentric in some cases.

Pictures inbound.

![image](https://cloud.githubusercontent.com/assets/19973802/26304467/96cc9252-3f3f-11e7-91ae-dbe9cdf13f66.png)
Janitors can access drone fabrication (meh, they can't use the consoles anyway) and then enter waste handling through there, and get into the engine room from _there_.

![image](https://cloud.githubusercontent.com/assets/19973802/26304537/dd6b14c2-3f3f-11e7-9b59-e6069d30f627.png)

Janitor's can't get through this maintenance door that's south-ish of the engine even though they can get into there by taking a different maint door.

![image](https://cloud.githubusercontent.com/assets/19973802/26304678/6fab0f72-3f40-11e7-9201-f772f3b3f0d9.png)
![image](https://cloud.githubusercontent.com/assets/19973802/26304682/76cc4708-3f40-11e7-8c98-3adc49ce07e0.png)

As far as I can tell, janitors can get anywhere that remotely matters on the engineering outpost.

![image](https://cloud.githubusercontent.com/assets/19973802/26304900/2d6814ba-3f41-11e7-8ab5-f26f2d3b0b23.png)

Janitors can also get into medical's storage on their outpost.

[No more pictures]

As far as I can tell, janitors can access any and all medical substations even though they can't access others. (These medical substations being the one on the main level and the one on the sublevel, I don't know if any others exist)

It also seems that janitors cannot access any maintenance doors connected to security, even though they can get onto the other side of at least one of those doors, mayhaps look into that.

Janitors can also get EVA by using the airlock in the under-development level (with the bolted IT door), I don't know if that's intentional or not.

**Comment by OneOneThreeEight** [comment]
I hope their security or research access isn't as terrifying as the amount of leeway they get into engineering.

**Comment by Fire-and-Glory** [comment]
Actually! That reminds me.

Janitors can get into security's interrogation room (both parts of it), looking at the amount of access (the lack of it, rather) they get for everywhere else in security, this seems a bit odd.

Rest assured, janitor's are suitably restricted from moving about in those departments and on engineering's main level they are also restricted aside from getting into the engine through a windoor.

**Comment by Juani2400** [comment]
#2438 should fix all the janitor access issues in Engineering.

**Comment by Fire-and-Glory** [comment]
@skull132  Juani only fixed issues with engineering access, no?

 I would very much like to be able to get in and out of security without having to use the front door every time.

Or be told that that's silly and has been thought about, at least.
