### ISSUE TITLE
Paper form limit is TOO DAMN SMALL

### ISSUE THREAD

**Issue by AllyBearsley** [Aurorastation/Aurora.3#2446]
Yield form is showing signs of being glitched. Not being able to fill in certain parts including: Osmium Wafers, Tritium Bars, Hydrogen Wafers, Additional Notes, and Signature.

I found this error in Game ID: bOD-c8wj at around 15:24 CST 24/5/2017 

Image to show what is wrong: http://i.imgur.com/2s9LVxK.jpg

**Comment by Lohikar** [comment]
@skull132 Related to #2316?

**Comment by skull132** [comment]
Yes.
