### ISSUE TITLE
Recursion - Giant nurse spiders make infinite amounts of cocoons out of another giant spider corpse.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#2448]
The original corpse doesn't disappear. Recursion happens. Hilarity ensues.

**Comment by printer16** [comment]
Related to https://github.com/Aurorastation/Aurora.3/issues/1442

**Comment by OneOneThreeEight** [comment]
Might've been the core issue to begin with. Spider corpses, compared to any other corpse, seem to be the exception when the nurse spider attempts to wrap the corpse up in a cocoon. It creates a cocoon on the tile the dead spider is on, but unsuccessfully. The corpse remains so the AI decides, "ok, it isn't wrapped, so I should try again."

**Comment by skull132** [comment]
Fucking. Spider PR inbound Soon:tm:
