### ISSUE TITLE
IPC wizards possible

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#245]
I'm pretty sure this was specifically written out at some point in bays history, because it makes no sense to have robot wizards, and also they don't get access to the full spell complement, because one of them causes them to _destroy their own electronics_.

Probably should be fixed.  Probably also Vaurca, since they're half robot as is.

**Comment by LordFowl** [comment]
Just like IPC traitors don't have access to EMP grenades, IPC wizards don't have access to EMP - it's not a bug it's just what you get when you pick a race; disadvantages. For the entire course of old-code we also did not ban IPCs from being wizards. So while Bay may have coded it out, it's not a bug as far as we're concerned.
