### ISSUE TITLE
Characters on SQL - skills insert query broken

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#246]
```
[11:40:51]DEBUG: update skills
[11:40:51]DEBUG: insert skills
[11:40:51]DEBUG: INSERT INTO characters_skills (char_id, Command, Botany, Cooking, Close_Combat, Weapons_Expertise, Forensics, NanoTrasen_Law, EVA, Construction, Electrical, Atmos, Engines, Heavy_Mach, Complex_Devices, Information_Tech, Genetics, Chemistry, Science, Medicine, Anatomy, Virology) VALUES ('5', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '')
[11:40:51]DEBUG: SQL Error: 'Incorrect integer value: '' for column 'Command' at row 1'
```

Issue is most likely derived from the fact that `''` is regarded as an empty string. The values should be input as `NULL` or straight up integers in the query.

**Comment by skull132** [comment]
Tagging @Mahzel 
A solution may be to use the `parseArguments()` function. Changing the query to use, effectively a prepared statement with placeholders, like this:
```
	TextQuery += "Construction, Electrical, Atmos, Engines, Heavy_Mach, Complex_Devices, Information_Tech, Genetics, Chemistry, Science, Medicine, Anatomy, Virology) VALUES "
	TextQuery += "(:char_id, :skills_man, :skills_bot, :skills_cook, :skills_comb, :skills_wep, :skills_forens, :skills_law, :skills_eva,"
	TextQuery += " :skills_const, :skills_electr, :skills_atmos, :skills_eng, :skills_pilot, :skills_dev, :skills_comp, :skills_gen,"
	TextQuery += " :skills_chem, :skills_sci, :skills_med, :skills_anat, :skills_viro)
```

And then passing a list into the `query.Execute()` function, which uses those placeholders as keys, and their assigned values as well, values. It will automatically identify `null` and replace it with the SQL equivalent `NULL` value. Note that integer `0` will remain as it is, however.

The `query.Execute()` function would look something like this, then:
```
	query.Execute(list(":char_id" = text2num(char_id),
				":skills_man" = skills["management"],
				":skills_bot" = skills["botany"],
				":skills_cook" = skills["cooking"],
				":skills_comb" = skills["combat"],
				":skills_wep" = skills["weapons"],
				":skills_forens" = skills["forensics"],
				":skills_law" = skills["law"],
				":skills_eva" = skills["eva"],
				":skills_const" = skills["construction"],
				":skills_electr" = skills["electrical"],
				":skills_atmos" = skills["atmos"],
				":skills_eng" = skills["engines"],
				":skills_pilot" = skills["pilot"],
				":skills_dev" = skills["devices"],
				":skills_comp" = skills["computer"],
				":skills_gen" = skills["genetics"],
				":skills_chem" = skills["chemistry"],
				":skills_sci" = skills["science"],
				":skills_med" = skills["medical"],
				":skills_anat" = skills["anatomy"],
				":skills_viro" = skills["virology"]))
```

**Comment by SoundScopes** [comment]
Also if anyone downloads your codebase and can't be bothered to write a config or setup a SQL database (Ie: me when bored) You get a load of runtimes because there is no default db object to pass into the system.

**Comment by skull132** [comment]
Different issue, and related to my code and not Mahzel's, if you mean
errors from establish_db_connection().

**Comment by SierraKomodo** [comment]
Personally think that all DB queries should use prepared statements, if possible. Solves this problem usually, at least with PHP. I'm not certain if byond code supports prepared statements, although you did imply it with a previous response.

**Comment by skull132** [comment]
BYOND uses mySQL's libraries in .dll format, with the functions called up via BYOND being only able to return strings. They do not come with prepared statements attached, and the DM wrapper for those functions is written to not use prepared statements.

The best I could manage is a form of automatic parsing: variable recognition, sanitization/escaping, and insertion, as I demonstrated above, by modifying the DM wrapper.

**Comment by skull132** [comment]
@SoundScopes - check #255 for your report.

**Comment by skull132** [comment]
Fixed in dev.
