### ISSUE TITLE
Maintenance dsposals conveyer does not move objects downwards when turned on

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#247]
When the disposals conveyer is running, everything gets moved to the upper left corner, and then stops there. Nothing moves down toward the inlet leading to the mass driver.

**Comment by OneOneThreeEight** [comment]
Ref #92

**Comment by SierraKomodo** [comment]
@OneOneThreeEight I think you tagged the wrong issue.

**Comment by OneOneThreeEight** [comment]
@sierrakomodo fuck
