### ISSUE TITLE
Brig area air control console cannot connect to brig scrubbers

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#2475]
The area air control console in the small atmos maintenance room to the west of the brig isn't connected to the scrubbers inside the brig itself. Clicking 'Scan' presents a message saying 'No scrubbers were found'.

**Comment by skull132** [comment]
For ref, discussion is about the mahoosive scrubbers.

**Comment by LordFowl** [comment]
The Area Air Control console is simply the wrong type of console, as we figured out on mapdev
