### ISSUE TITLE
[NEW MAP] Shuttles do not dynamically generate a shuttle roof when moving.

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora.3#2485]
If a room isn't properly covered with a roof in the z-level above, anyone can move upwards from outside the room with a jetpack and move down once above and inside the room if it isn't properly covered with a roof tile.

**Comment by LordFowl** [comment]
Provide a location of one such room.

**Comment by Keinto** [comment]
Arrivals shuttle, mercs shuttle, and a room east of the Holodeck, which I checked once again as a ghost another round and there were asteroid tiles  in the z level above it. Are the asteroid tiles randomized every round?

**Comment by LordFowl** [comment]
Shuttles not having a roof is a tracked issue, the rooms east of the holodeck were a bug that was fixed.

**Comment by Alberyk** [comment]
I am sure this is fixed.
