### ISSUE TITLE
Evidence Bag Box does not display content slots when 'opened'

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#249]
When you click on an evidence bag box/drag it to yourself to open it, it plays the 'Open' sound effect, but does not display the UI slots showing the boxxes contents. Regular boxxes appear to work fine (And can be used as a reference for expected results). Items can still be taken from the box by right clicking and choosing 'Empty Contents', and you can still insert items back into the box by clicking the box with the item in your active hand.

**Comment by OneOneThreeEight** [comment]
ref #92 i did it right this time
