### ISSUE TITLE
Changing a Tablet's Hardrive after it's been registered breaks it forever.

### ISSUE THREAD

**Issue by Grant4455** [Aurorastation/Aurora.3#2490]
Don't know if this applies to other  computers but;

Install and start a fully functional tablet.

Charge and power on.

go to 'NTOS Client Manager' 

Enroll as a work device for any job.

Pop out harddrive and install a new one.

Still registered as a work device, Cannot reset. No programmes installed at all. Device broken forever.

**Comment by Arrow768** [comment]
Do you have the same issue if you register it as private device ?

**Comment by Geevies** [comment]
I think this has been fixed.
