### ISSUE TITLE
{NEW MAP} - Mining airlock will lose air and then stop cycling in.

### ISSUE THREAD

**Issue by KepQwet** [Aurorastation/Aurora.3#2491]
It doesn't seem to be properly connected to its canisters. Possibly mapping-ralated.

**Comment by SierraKomodo** [comment]
Not sure why this is closed. This exact issue is happening in the current round and I was about to post a new bug report for it.

Round ID bOH-zVYf

**Comment by LordFowl** [comment]
I close issues as I solve them when bugfixing, as they do not automatically get closed when they merge into dev.
