### ISSUE TITLE
[NEW MAP] Supply department lack access

### ISSUE THREAD

**Issue by ariever** [Aurorastation/Aurora.3#2494]
The second CT spawns in the break room at round start, which they don't have the access to get out of. I had to ask the QM to get me out.
Nether the QM or the CTs have access to the door leading to the warehouse. Had to hack the door open to get inside.
![2017-05-27_22-47-20](https://cloud.githubusercontent.com/assets/26043258/26525715/836c2f22-432e-11e7-8a5e-68dda2c34a16.gif) [Me, a CT. Can't open the door to the warehouse but can open the shutters.]

![2017-05-27_22-51-10](https://cloud.githubusercontent.com/assets/26043258/26525737/1dfaec68-432f-11e7-94ce-57e87c11cf98.gif) [The QM. Can't open the door either.]

**Comment by LordFowl** [comment]
Duplicate #2480
