### ISSUE TITLE
Maintenance drones cannot drag pipe meters

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#2497]
This seems somewhat inconsistant with normal behavior, as maintenance drones can drag ever other type of pipe, even disposal pipes.

**Comment by Baa14453** [comment]
can confirm, "you are too small to pull that."
![image](https://user-images.githubusercontent.com/9057997/79082075-f28a6800-7d1a-11ea-8e28-af33ed111ebf.png)
