### ISSUE TITLE
[NEWMAP] Maintenance drones cannot climb up/down ladders

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#2498]

**Comment by CyberstormFox** [comment]
So far, if the turf above or below is open, the can ascend or descend using jetpacks and the "Move Upward" and "Move Downward" verb in the IC tab.

**Comment by SierraKomodo** [comment]
@CyberstormFox Maintenance drones don't have jetpacks. Also, jetpacks aren't relevant to ladders.

**Comment by Lohikar** [comment]
No, you should be able to go up a ladder with a jetpack now that they're openturf based.

**Comment by SierraKomodo** [comment]
Wouldn't you be able to climb up or down a ladder regardless of if you have a jetpack?

**Comment by skull132** [comment]
Ladders and jetpacks are indeed not tied. Anyways, PR is up. Side-effect is also fixing another bug which we encountered way back.
