### ISSUE TITLE
[NEWMAP] Black floortiles

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2502]
Came across a black floor tile, unable to interact with it in any way, made a second one by removing an adjacent tile. The tile removed was possibly damaged.
On further examination, it appears the black tiles were indeed sand, and constructing a wall on one of them gave them the texture back, allowing repairs to be made.

**Comment by LordFowl** [comment]
https://github.com/Aurorastation/Aurora.3/issues/2346 duplicate
