### ISSUE TITLE
[NEWMAP] Multiple Research (Sub-Level) Bypasses on RCON

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#2519]
<img width="264" alt="2017-05-28_16-13-55" src="https://cloud.githubusercontent.com/assets/24210359/26531866/d5490df0-43c0-11e7-9312-9f043fdb203c.png">
There are two Research (Sub-Level) Bypasses

**Comment by Juani2400** [comment]
Plus. The Tesla Containment SMES' RCON tag is labelled as "**Testa** - Containment".
