### ISSUE TITLE
[New Map] Non-autonomous bots icons missing

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#2531]
The bots (at least in the case of cleanbots and medibots), including their assembly stages, have missing icons. They can still be interacted with using the right-click context menu and the alt-click turf menu.

**Comment by Alberyk** [comment]
Just build them in the test server, seems to be fine.

**Comment by Mwahahahaha** [comment]
Hm. Perhaps it could be client-side? I was never able to get anyone else to comment on it; they were either too busy or had their own issues regarding icons.
Or maybe it was just rectified somehow.
