### ISSUE TITLE
SMC: Mapped in power connections do not appear to be updated properly

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#2532]
Okay. Long story short.

We've been running into issues in new map meme where connections that are valid, and exist since round start, are not flagged properly until an admin invokes `make-powernets`. Example cases of this:
* Tesla setup. This is all mapped in to be 100% functional (as far as wiring goes). However, after starting the engine, power does not flow until `make-powernets` or a local powernet update (I presume, haven't tried) is invoked.
* #2345 . Where mapped in z-wires do not move power until `make-powernets` is invoked. In this case, not even remaking the wires helps reliably, thus it's possible that local updates fail at times. Whether or not this is specific to z-wires should be confirmed.
* Possibly #2520 . Needs confirmation.

@Lohikar since this is something you've worked on, could you investigate during the week?

**Comment by Lohikar** [comment]
Investigating.
