### ISSUE TITLE
[NEW MAP] Heat pipes lose too much efficiency

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#2533]
The SM heatpipes are meant to work in either an atmosphere, or in space (whereby dark matter/energy zaps their heat off). The asteroid has neither: it is not in space, so dark matter calculations aren't ran, and they're in an atmosphere of near 0 moles of air, so heat capacity of that air is 0. This leaves them in limbo: they cannot put off heat efficiently. Which makes them quite useless.

There are two fixes I can think of: a cooler array to cool the waste instead of using heatpipes, or modifying the calculations so that they can discard heat faster even when not in an atmosphere.

**Comment by LordFowl** [comment]
Considering just moving them down to the bottom z and connecting them with z-pipes.

**Comment by skull132** [comment]
This may require further testing and confirmation, FYI, before action is taken. It seems to be conditional.

**Comment by Lohikar** [comment]
Did some testing, happens even when ZAS zone rebuilds aren't occurring (idle server, no shuttle movement).

**Comment by skull132** [comment]
Turns out. Mapping doesn't solve it because we have no direct access to space tiles.

Coding is required instead. Make them disperse heat more efficiently in 0 mole conditions I guess?

**Comment by LordFowl** [comment]
> Considering just moving them down to the bottom z and connecting them with z-pipes.

**Comment by skull132** [comment]
Fixed in #2893
