### ISSUE TITLE
Beakers and medical borg grippers

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2535]
Seems you're unable to fill or empty a gripped beaker when using a sink.

**Comment by Arrow768** [comment]
Do you get any messages when you try this ?
If so, what messages do you get.

**Comment by Pratepresidenten** [comment]
You get the prompt window asking if you want to fill, empty or cancel the action. You'll get the message that you either fill or empty the beaker, but the content status of the beaker remains unchanged.

**Comment by Pratepresidenten** [comment]
With the rolled out updates as of a few days ago, you now get the prompt when using sulphuric acid dispensers in science. Which makes research incredibly tedious, as you need to expend the acid from the scichem dispenser instead.
