### ISSUE TITLE
Kitchen food changes

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#254]
This is an official push for some method to make food items (i.e. prepared food, not fruits and veggies) renamable and redescrible.

Also, please remove the feature that causes you to shove objects inside of large slicable food items such as pizza, cakes, and breadrolls.  It's kind of stupid and doesn't currently serve any usable purpose other than to force you to slice the item to retrieve it.  I think at one point the idea was sort of the 'hide something in your prison food' gag, but no one ever uses it for that, ever.

**Comment by Bedshaped** [comment]
This kind of post should be made in the suggestions forum.
