### ISSUE TITLE
Runtimes from null dbcon

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#255]
Within the `initialize_database_object` proc, 0 was returned if the config was not detected or not properly set up. This resulted in a series of runtime errors whenever a test server (or any server) without a database hooked up was started.

Reason was simple: var/dbcon was set to equal 0.

**Comment by skull132** [comment]
Fixed in commit 3f1c460632dbec7066a8322fb5b601acd2724689

Awaiting pull into dev.

**Comment by SoundScopes** [comment]
Yay no runtimes
