### ISSUE TITLE
[Newmap] Nuke detonates on Centcomm instead of the station

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2552]
The ticker's nuke is hard-coded to destroy Z1, which happens to be centcomm now.

Creating this issue so I don't forget to fix it.

**Comment by skull132** [comment]
Future proofed solution: either make it use a custom list from config which
defaults to the station Zlevels list, or just make it use the station
Zlevels list from config.

**Comment by SirFruitcakes** [comment]
What a way to lose CC.
