### ISSUE TITLE
[NEWMAP] Warden's office lacks a Fax machine

### ISSUE THREAD

**Issue by Butterrobber202** [Aurorastation/Aurora.3#2556]
it lacks a fax machine.

**Comment by Juani2400** [comment]
I don't think the Warden's office requires a fax machine given than you can fax all of the Heads of Staff using the request console. A Warden shouldn't need to contact CCIA.

**Comment by Pratepresidenten** [comment]
I do agree, there shouldnt be a need for a warden to have a fax machine. They're the same rank as officers, and the officers does not have one.

**Comment by Butterrobber202** [comment]
Used to Fax the Armory Inv. to the HoS and Captain depending on whos there.

**Comment by Lohikar** [comment]
You can send faxes to heads of staff using a request console.
