### ISSUE TITLE
Vampire as Positronic Brain

### ISSUE THREAD

**Issue by NoahKirchner** [Aurorastation/Aurora.3#2566]
I, after dying as a maintenance drone and cryoing before that due to poor occupation settings, became a vampire as a bodyless positronic brain.
Alberyk helped me out and removed my vampirism.

Even after having my vampirism removed, I maintained the "Vampire" tab, but only the "Show help" verb was available.
Game ID: bOL-daRf

**Comment by skull132** [comment]
@Alberyk Was this a random event or what? Midround vamp isn't a thing usually.

**Comment by Alberyk** [comment]
Yes, it was.

**Comment by skull132** [comment]
da fuck.

**Comment by JohnWildkins** [comment]
This probably isn't an issue anymore, and if it is we'd need a slightly more current issue regardless.
