### ISSUE TITLE
[Newmap] Oil tank can spawn in a bad spot

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2569]
![2017-06-01_19-55-21](https://cloud.githubusercontent.com/assets/7097800/26706609/5218fac0-4704-11e7-8786-8e7362a39d83.png)

**Comment by Alberyk** [comment]
Nearly sure this is on purpose, in the same way the oil tanks in the exodus spawn in the maint as well

**Comment by Lohikar** [comment]
The Exodus' tank did not block the Kitchen's MULEbot delivery point though.
