### ISSUE TITLE
[NEW MAP] Floor B.O.B. sleeps in life

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#2578]
`DEBUG: SSmob: Type '/mob/living/bot/floorbot/floorbob' slept for 49.5 ds in Life()! Suppressing further warnings.`

**Comment by LordFowl** [comment]
Probably more likely floorbots in general sleep in life.

**Comment by Lohikar** [comment]
Most bots seem to sleep in life; likely from usage of `do_after` or `do_mob`.
