### ISSUE TITLE
Eternal Floating Syndrome

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#258]
When you go out into space without magboots on, you begin floating.  This is fine, except that this graphical effect persists long after you actually leave 'space' tiles, and even admins have a hard time turning it off, apparently.  Sometimes it randomly goes away after a long period, for reasons I don't know, but it should stop when you are on solid ground.  Seeing people floating around on the station constantly because they went EVA once is kind of silly.

**Comment by SoundScopes** [comment]
Info, this is a graphical client side(most of the time) glitch. On the old code I wrote a command to reset the "floating animation/process on all mobs" which activated randomly and could be reset with a verb.

**Comment by MarinaGryphon** [comment]
For what it's worth, it's now common knowledge that disarming someone stops the floating animation. Trying to investigate what causes it to stop.

**Comment by MarinaGryphon** [comment]
Also, it's not clientside, as it showed for all players. It was an issue with the animation.
