### ISSUE TITLE
[NEWMAP] Massive borg construction issues.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2584]
The posibrain that spawns in robotics appears to break a newly built cyborg shell.
Once inserted into the shell, the name is defaulted to whatever module is inserted plus a -0 to the name and the shell that was used is duplicated.

The borg shell cannot understand or speak ceti basic, binary or EAL, it cant hear anything on any radio frequency.

It registers the powercell as gone and it can turn and talk in Sol or Tradeband regardless if it has a cell inserted or not. It doesnt drain battery charge when its idle or is using its light, and it cannot move around apart from turning to face a different way.

You are able to pick a module, but you cannot access any module components, and a module reset does nothing other than reset the module.

You have no interface access to the objects around you, and trying to access an airlock will give you a red "Access Denied!"

Trying to pry apart the shell to recover the brain doesnt work either, as you cannot access the wiring window by using either the multitool or wirecutters.

The shell cant be damaged or injured in any way it seems.

**Comment by Lohikar** [comment]
Fixed by #2632.
