### ISSUE TITLE
Parralax Replaces Blind Spots

### ISSUE THREAD

**Issue by NoahKirchner** [Aurorastation/Aurora.3#2585]
I was a second AI during a malf-AI glitch, and when I respawned, everything that would normally be out of view and solid black, became space.
https://gyazo.com/712bd8c144125845a61c1b5f1cca7a29

**Comment by chaoko99** [comment]
Not reproducable. Really pretty though.

**Comment by Geevies** [comment]
Think this doesn't happen anymore.
