### ISSUE TITLE
[NEWMAP] Forensic Technician Autolocker

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2586]
Walking through the autolocker put one of the really REALLY old armor items on my person, There's also still issues with duplicates, it gave me two labcoats and two oxygen boxes as well.

![armor](https://cloud.githubusercontent.com/assets/24979527/26754622/368c3184-484c-11e7-95ad-1eae4efa24f5.png)

Was using the CSI alt title if that ends up making any difference.

**Comment by LordFowl** [comment]
CSI alt titles gets an old armour vest.

**Comment by Alberyk** [comment]
I will get something to replace/fix this.

**Comment by LordFowl** [comment]
That defeats the point. It is meant to be a different armoued vest than the ones sec or the warden get.

**Comment by Alberyk** [comment]
The code has some csi unique armor sprites, those can be used.
