### ISSUE TITLE
Vox leaping doesn't work

### ISSUE THREAD

**Issue by printer16** [Aurorastation/Aurora.3#2597]
Nothing happens. Probably related to @skull132 leg actuators PR.

**Comment by OneOneThreeEight** [comment]
Did you try to leap at a person? It's a Vox free stun and a passive grab, not a chasm-jumper.

**Comment by printer16** [comment]
It doesn't work for Vox. Vox lost their ability to leap.

**Comment by skull132** [comment]
Will investimagate at some point.
