### ISSUE TITLE
[NEWMAP] Tinted windows not working

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2603]
The far right row of windows in the captain's office doesnt tint normally. The window type is correct, they just dont work.

**Comment by Juani2400** [comment]
Needs confirmation. I remember them working fine when I played Captain last time.

**Comment by Pratepresidenten** [comment]
Joined a round just now, the problem seems to be oposite. https://puu.sh/wawKn/86a4f7ed8c.png
Its constantly tinted, and I cant turn it off, as opposed to never tinting as the first issue stated.
