### ISSUE TITLE
[NEW MAP] Detective Office's Camera Console Does Not Work

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora.3#2604]
The console is set to the 'civilian east' network and cannot be changed to anything else nor can one check any of the cameras in that network.

**Comment by Arrow768** [comment]
Replace it with a modular computer on security preset ?

**Comment by Lohikar** [comment]
Wouldn't fix the core issue though.

**Comment by Alberyk** [comment]
Tested and it seems to work just fine.

**Comment by Keinto** [comment]
Yeah. I just played another round and it seems the issue was I was trying to use the console while buckled to the chair. I guess that's the bug?

**Comment by skull132** [comment]
Duplicate of #2246
