### ISSUE TITLE
Traitors are not getting their code phrase and response when selected.

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#2612]
They don't get their code phrase and response in their memories when they are select as antag it seems.

**Comment by skull132** [comment]
This is ooooold. Dating back to old Aurora v2 code. I'm not sure if it's a bug or bad gameplay design, but the codewords are given by chance. Sometimes you don't get responses, only codewords. Sometimes you get neither. It's fucking odd.

**Comment by SonicGotNuked** [comment]
This is like every single traitor, no one gets any words.

**Comment by Lohikar** [comment]
> bug:confirmed

> flag:not a bug

🤔

**Comment by Alberyk** [comment]
Fixed.
