### ISSUE TITLE
AI's 'Track with camera' function isnt working as intended

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2628]
Seems when you click the track with camera button, you only get a list of the four monkeys at the research outpost, and you cannot click someone's name to track them either, as you get the error message "Follow camera mode terminated."

Update: Attempting to track someone through the suit sensor software will spit out "Unable to establish a connection: You're too far away from the station!"

**Comment by Butterrobber202** [comment]
_Accidently_ ended up testing all this. Its true, Link Names, Track Camera, and suit sensors are all a bust.

Location (Area) Camera Teleporting works.

**Comment by skull132** [comment]
Newmap or old map?

**Comment by Pratepresidenten** [comment]
Oldmap

**Comment by skull132** [comment]
That is. Really odd.

**Comment by printer16** [comment]
Did you happen to switch your camera network to the RnD outpost?

**Comment by Pratepresidenten** [comment]
Didnt touch any network controls. But at some point, I got a fifth entity up on my scanner, which was a disposaled slime that ended up on the telecomms sattelite.

I just asked an ingame AI, and it seems that they have no issues tracking anyone either through the "Track with camera" function.

**Comment by Lohikar** [comment]
This happened again, or just an isolated incident?

**Comment by Pratepresidenten** [comment]
Seems to have been an isolated incident. Havent had any further issues with it.
