### ISSUE TITLE
[Exodus] Ninja can not teleport on station Z-level

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#2639]
I tried to teleport on station Z-level, could not. 
https://i.gyazo.com/a75ef3a420e5e2dcf418a6eedff85e84.png

**Comment by Synnono** [comment]
This maybe has to do with ninja and antag stuff not working so great on Z1 by default?
_Thanks CentComm_

**Comment by skull132** [comment]
Config option error. Will be fixed shortly.

Not a bug.
