### ISSUE TITLE
CRUSHER

### ISSUE THREAD

**Issue by LordLag** [Aurorastation/Aurora.3#264]
http://i.imgur.com/P5gWFqY.png?1
Waste would eject from the disposals chute on the right, whereas maintenance and custodians can enter through the maintenance hatch on the left.

During operation the maintenance hatch would preferably bolt shut for safety. The console controlling the compactor would be on the other side of the windows.

The tiling on the top and the bottom would be the crusher pistons. They would preferably play a sprite animation where they extend to the middle of the middle row of tiles, and the destruction of items would be in synch with this animation.

I intend to acquire sprites for a more advanced multi-tile looking machine, but coding-wise right now all I am concerned about are the crusher pistons and the control console. The console would preferably have control over whether the hatch is bolted or not (Although again it would automatically bolt during operation), and whether the machine is in operation or not.
- [ ] Create base objects. (Console, pistons)
- [ ] CONSOLE, Sync, Crush, status of crusher
- [ ] CONSOLE, Door control
- [ ] PISTONS, Obliterate everything they touch.
- [ ] Console Sprite
- [ ] Piston Sprite
  [crusher.txt](https://github.com/Aurorastation/Aurora.3/files/405027/crusher.txt)

**Comment by NanakoAC** [comment]
why is this an issue and not a PR?

**Comment by Bedshaped** [comment]
Closing due to @LordLag no longer being part of the dev team.

**Comment by printer16** [comment]
Implemented to dev.
