### ISSUE TITLE
Admins refuse to report bugs on github

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#2648]
Whenever you report for any bugs to adminhelp, they are more likely about to give report mute, than to report any information themselves.

**Comment by HetNeSS** [comment]
Tested on some buddy with nickname starting on letter "A", from higher admins

**Comment by Juani2400** [comment]
No. Please.

**Comment by Juani2400** [comment]
For future reference, admins are not the ones who need to report a bug of it gets reported via AdminHelp. Whoever finds the bug is expected to report it themselves. You were told to stop reporting bugs via AdminHelp after being told this. You will most likely be spoken to in the server for this, again.

**Comment by skull132** [comment]
Point one, policy discussion is to take place on the forums. Github is not the proper time and place for it.

Point two, nowhere in the rules does it state that admins are required, or even expected to report bugs on github if a player encounters them and ahelps. Yes, they will most likely report the severe ones and also inform me or the devs of said bug personally if it's gamebreaking enough. But it is the responsibility of the playerbase at large to help keep this tracker updated.

The policy is also concerned with raising the playerbase. As already stated, we want the playerbase to assist with the bug reports. Having admins relay bugs would be counterproductive towards this end goal.

The admin may also have been busy. Who knows.

Anyways, bring this to the forums, general discussion if you wish to actually even attempt to have this policy changed. Github is for development related issues only.
