### ISSUE TITLE
How Vamp's literally broken

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#265]
* Rejuvinate doesn't work properly.
* Shapeshift is broken. Doesn't work.
* Summon Bats summons 2 groups of space bats that attack the summoning vampire. like wtf
* Shadowstep doesn't work at all.
* Grave Fever doesn't transmit any disease at all.
* Enthrall does not add anyone to antag lists.

**Comment by Kaedwuff** [comment]
I've never had the problem with bats attacking me (though honestly bats are pathetic, they deal barely any damage and die to a stiff breeze, making them barely more than a distraction for half a second, which is way too little for their high blood cost of sixty.  Needs to summon more bats, cost less and be more spammable, or the bats need to be tougher) , nor with rejuvinate not working - it gets me back on my feet in a pinch just fine.

All the other stuff though, yes. Needs definite fixing.

**Comment by LordLag** [comment]
We are well aware of the issues, and this is the third post regarding them.
