### ISSUE TITLE
CE's RIG sprite slightly bugged

### ISSUE THREAD

**Issue by Pyrociraptor** [Aurorastation/Aurora.3#2673]
The Chief Engineer's RIG is missing/not loading(?) the chestpiece.

Picture of a fully deployed RIG for reference.
![missingchest](https://user-images.githubusercontent.com/6706637/27009947-56616070-4e9a-11e7-9df3-1905f9389ff0.PNG)

Edit: Seems to be related to all hardsuits.

**Comment by Lohikar** [comment]
Might be a caching issue on your end; has it happened again?

**Comment by skull132** [comment]
Closed during issue clearance.

No further information provided.
