### ISSUE TITLE
Issues With Dionaea Spawning

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#268]
Dionaea have only slots for headgear, a single earpiece, a suit, and an exosuit. If they spawn with a custom loadout item that does not fit into one of these slots, the game bugs out and does not send them to the arrivals shuttle. Instead it directly puts the player into the game on the start-screen, resulting in this:
http://i.imgur.com/lGmqk1n.jpg?1

This includes prescription glasses.

**Comment by NanakoAC** [comment]
Baymerge seems to have fixed this, closing
