### ISSUE TITLE
PAI RIGsuit Movement Control is Given to the Pilot

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2687]
PAI's are not able to take movement control of the normal ERT RIGsuits and perhaps some others, the deathsquad suit appears to be the exception and allows you to take full movement control at any time. With the other suits you will stop the pilot from falling over and if they lose consciousness they will remain upwards, however instead of the pAI being able to move them, they are still in control of it. 

As tested, a trooper in the ERT-S suit was knocked unconscious with a high dosage of Chloral yet was able to move around as normal, just not pickup or interact with anything, when the pAI ghosted, control was lost and the person fell over once again. It looks like on those suits the control feature meant for the pAI is just being incorrectly given to the pilot of the suit.

**Comment by OneOneThreeEight** [comment]
That actually begs the question as to why the hell they're even able to pilot the suit.

**Comment by LordFowl** [comment]
pAIs and I believe carded AIs are designed to be able to pilot the suit if their master becomes incapacitated.

**Comment by verywhiterabit** [comment]
Carded AIs and pAIs had about the same suit functionality when tested.

**Comment by OneOneThreeEight** [comment]
Wouldn't that make someone completely invincible, since the suit can still be operating regardless of the damage that the wearer of the suit is taking, or does this not matter of the suit wearer is dead?

**Comment by Lohikar** [comment]
This is supposed to require the wearer be dead or unconscious to activate.

Each step consumes 300 charge, and the (p)AI is incapable of opening doors or generally doing anything other than walking or manipulating the suit.

**Comment by printer16** [comment]
Works fine the last time I tested it.
