### ISSUE TITLE
(NEW MAP] The escape shuttle don't dock properly

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#2688]
When the shuttle docks on the station, the airlocks on departures don't open. It also seems you can't cycle the airlocks by clicking their access buttons.

**Comment by LordFowl** [comment]
Are you sure this was not just the issue of a single round? It is strange for it to be reported only now.

**Comment by Alberyk** [comment]
I don't think so, it seems it happened all the rounds I observed today.

**Comment by Alberyk** [comment]
Seems to work fine now.
