### ISSUE TITLE
Remove Virology and Xenobiology X-ray cameras

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#269]
Due to what I suppose is carryover from some thought process in bay design, the cameras in the containment double doors in virology and xenobiology (you know, the ones that bolt and unbolt alternatively at a button press) both have the X-ray vision property. This has, on two separate occasions, managed to screw over a sneak attack by raiders that I was personally involved in.  I know now that these exist, and just tested them with the camera consoles in-game, but I don't see any reason why they should be there.  The only x-ray camera on station should be in the AI's chamber, because that is a logical place for one to be - it's a very high security area and the AI sees everything from their cameras, so it allows them a little bit of a vantage point for the bridge if all the cameras are cut.

Please remove this property from the cameras in those locations.

**Comment by LordLag** [comment]
http://forums.aurorastation.org/viewforum.php?f=18&sid=077b07d330b4c4090c068108f4446d01

**Comment by ArcBotSS13** [comment]
I feel the vault needs an x-ray camera to.

**Comment by Bedshaped** [comment]
You should make posts like this in the forum, and link the thread back to here for this kind of post.
