### ISSUE TITLE
Travis migration validation randomly fails

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2693]
It seems that sometimes the Travis flyway validation sometimes fails for no apparent reason, restarting the build on Travis without making any changes passes it.

@skull132

**Comment by skull132** [comment]
Can you link me a build as an example?

**Comment by skull132** [comment]
Found one, will investigate in a bit: https://travis-ci.org/Aurorastation/Aurora.3/builds/242804101?utm_source=github_status&utm_medium=notification

**Comment by skull132** [comment]
Well, seems to have been fixed by moving the DB init earlier. Closing until it pops up again.

**Comment by JohnWildkins** [comment]
travis is dead, long live travis
