### ISSUE TITLE
[NEWMAP] Genetics builds up lag over time

### ISSUE THREAD

**Issue by TrickingTrapster** [Aurorastation/Aurora.3#2695]
Now, I am not sure if this is user specific or not, but I have found that at least for me, the longer I use genetics, at some point, my game starts freezing for up to like 2 to 3 seconds every time I hit a button on the genetics console. This builds up over time though. Relogging fixes this, but I don't think we should have to relog just to be able to use genetics. Used the newmap prefix because genetics is only on newmap.

**Comment by SierraKomodo** [comment]
May not just be genetics; I recall hearing various people mention increasing lag as the round goes on in newmap.

**Comment by Lohikar** [comment]
Is it at all alleviated by restarting your client?

**Comment by SierraKomodo** [comment]
Not known, would have to ask people the next time newmap rolls around, I didn't notice any significant issues on my end but I've got a relatively beefy computer compared to most people if there's some kind of caching issue or resource leak causing this.

**Comment by TrickingTrapster** [comment]
Yeah, like I said, the lag is gone once I reconnect, but then the cycle just restarts and it lags again after a while of using genetics. When I am not using genetics everything is fine.

**Comment by skull132** [comment]
Genetics can actually cause this. There's an issue in BYOND where adding and removing verbs bloats client memory. This is worsened by being an admin.

Update your client to 511 and wait for us to upgrade the server as well. That should alleviate it, if not solve it.

**Comment by printer16** [comment]
Since genetics is RIP again time to put this to rest.
