### ISSUE TITLE
[New Map] The Supermatter Engine Cooling Pipeloop Doesn't Cool

### ISSUE THREAD

**Issue by K0NFL1QT** [Aurorastation/Aurora.3#2698]
The issue is caused clearly by the cooling pipes being on sand tiles and not space, or 'open space'. This leads to an eventual, inevitable and seemingly unstoppable delamination. I have confirmed that going out to space and digging out the sand tiles to open space lets them cool properly again.

**Comment by printer16** [comment]
Duplicate of #2533

**Comment by Arrow768** [comment]
Closed as duplicate.
