### ISSUE TITLE
Unathi cannot devour monkey, farwa, and other mobs that they should be able to

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#2717]
You can't eat that type of creature! - is given when I try to devour a monkey or farwa, or naera. I can't eat tindalos either. Unathi used to vore them, and they'd be alive for a while being digested fully. Please fix, let me vore Pun Pun.

**Comment by Lohikar** [comment]
Devour code in general needs a few fixes, I'm fairly sure the proc used to get a mob's type is broken in some way, and the human-type damage is very very broken.

**Comment by Lohikar** [comment]
This should be fixed now, pls comment if it isn't and I'll reopen.
