### ISSUE TITLE
Placing new floor tiles on space tiles causes lighting to break/glitch out

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#2726]
When building new floor tiles over a space tile by dropping rods then a floor tile, and covering enough area where the lighting system would start to cast the tiles in shadow, lighting gets really glitchy/non-functional. This includes areas where tiles were originally, but were destroyed by bombs. See attached screenshots for visual example.

Game ID bOZ-cXJh (That O might be a 0, a little hard to tell)

Server revision: master - 2017-06-15
0ac742be4d676fdb99fbb88eed06fa4337b0d557 

Still have a fun bug where I can't attach screenshots to github no matter what browser or computer I use, so here, have imgur: http://imgur.com/a/HfDKU

**Comment by Lohikar** [comment]
This is probably fixed in dev due to changes with how the lighting engine processes turf changes.

**Comment by Geevies** [comment]
Fixed.
