### ISSUE TITLE
Unathi cuff-resisting is peculiar while buckled to a chair

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#2729]
I'm not sure if we want Unathi to be able to break handcuffs while buckled to a chair or not, but either way, things are a bit funny right now.

If we do:Unathi currently cannot break handcuffs while buckled to a chair, the timer just runs out and then you have to wait 2 minutes to unbuckle.

If we don't:When Unathi  _do_ unbuckle from a chair, they're still cuffed, so they need to then break them, unlike other entities who ditch the chair and the cuffs in one move.

The whole thing can either be called a feature or a bug but right now it's in limbo, thus, I'm reporting it.

**Comment by Geevies** [comment]
Fixed.
