### ISSUE TITLE
[New Map] Smart Fridge Placement / Access

### ISSUE THREAD

**Issue by Arrow768** [Aurorastation/Aurora.3#2741]
Due to the placement of the smart fridge, any person passing by can get items from the smartfridge.
Ideally it would be restricted to Chef and Botany Access

**Comment by Alberyk** [comment]
It seems the fridge has access set already?

**Comment by LordFowl** [comment]
Have you confirmed someone who shouldn't have access removing items from the fridge?

**Comment by Arrow768** [comment]
There was a incident last round where an assistant walked up to the fridge and emptied out its contents.

**Comment by Arrow768** [comment]
Hm. Seems to work. Closing then
