### ISSUE TITLE
[Newmap] Maintenance drones can't push atmospherics canisters or pipe dispensers.

### ISSUE THREAD

**Issue by MarinaGryphon** [Aurorastation/Aurora.3#2742]
Not exactly mapping related but it's on the dev branch: Maintenance drones can't push canisters or pipe dispensers, as well as I'm sure a bunch of other stuff, which makes repairing atmospherics extremely tedious. Add that to the lack of atmospheric technicians, and a few small explosions could leave all of the Aurora II without atmospherics, making breaches a lot more deadly.

I get that preventing them from pushing lockers was intended, but perhaps an exception could be made for canisters and pipe dispensers? I can't think of anything else that would be that important.

Additionally, it's a lot easier to push stuff than pull it, so I thought it was intentional for drones to only be able to push lockers and other similar-sized objects.

**Comment by LordFowl** [comment]
If it's not about the new map, it's not a newmap issue. This is an unrelated change that hust happened to be in dev.

**Comment by Hugo14453** [comment]
If drones has some kind of pipe fabricator that would be nice, or at the very least if they could hold pipes in their magnetic gripper, currently you have to drag individual pipes all the way from atmos and open all the doors on your way there...

**Comment by Geevies** [comment]
I think this may have been fixed. Not a problem either way.
