### ISSUE TITLE
[New Map] Atmos Issues

### ISSUE THREAD

**Issue by Arrow768** [Aurorastation/Aurora.3#2746]
* Waste in pump is disabled start of the shift.
* The distribution and waste Monitor in the Atmos Control Room shows that Mix In / Out / Supply / ... can not be found
* The pipe adapters are not labeled, as requested in the pull.

**Comment by Lohikar** [comment]
I only requested the adapters be labelled if the plating was left as-is, but it was removed to expose the pipes.

**Comment by Juani2400** [comment]
Fiiixed in my last PR.
