### ISSUE TITLE
NEWMAP Mining conveyor belt issues

### ISSUE THREAD

**Issue by Stauto** [Aurorastation/Aurora.3#2766]
While using the mining conveyor, a majority of the resources were moving up, towards the smelting area, and then moving back, This issue was also noticed during the shift by the QM, Jake Miller, and the engineer, Oliver Roadman.

This caused mining to be running at a snail's pace, as barely any of the materials were being processed at once, the rest rocking back and forth like a wave.

**Comment by skull132** [comment]
@Lohikar Timer woes or mapping woes?

**Comment by skull132** [comment]
fixed now.
