### ISSUE TITLE
Newmap Holes Old version of BYOND vs New Version Note

### ISSUE THREAD

**Issue by gdudding** [Aurorastation/Aurora.3#2768]
Just for reference, my version of BYOND was *barely* out of date, and this is how holes appeared.  No one had mentioned to update BYOND in any of the places I mentioned the falling in invisible holes thing until the github issue was posted:

https://puu.sh/woaDz/771e750a0c.png     This is version 509, January of last year, so fair enough, fairly old but sometimes updating BYOND breaks stuff, too, so I tend to only do it when the need is apparent, like this.

After updating they look like this:
https://puu.sh/woaWb/53afb20c1b.png - version 511

So, maybe instead of all the commentary in OOC/Discord/etc about how dumb someone is for falling into a hole, maybe remind them to update BYOND because the holes are almost invisible otherwise.  Also, the Announcement MultiZ Survival guide should definitely make note of this.

I've seen at least 5 or 6 people say they saw no hole of any sort that they fell into, myself included.

**Comment by skull132** [comment]
Updated the server config to forbid entry to all players who use an outdated version of BYOND, as the graphics code we use is no longer backwards compatible with anything below 510.

Right now it was just warning players. Which I guess isn't enough.
