### ISSUE TITLE
[NEWMAP] Tesla shenanigans

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#2769]
After leaving the tesla alone for a while, it produced some permanent shock sprites.
https://puu.sh/wojqM/716085de85.png
People may also already be aware that the tesla does not work without admin intervention when the basic setup is completed after 3 hours.

**Comment by skull132** [comment]
For ref, sometimes (not always), the arcs lagging coincides with timers crapping out and resetting their buckets. All arcs are cleaned a few ticks after that.

**Comment by AgentWhatever** [comment]
2 hours later https://puu.sh/wonx1/771f9387e0.png
