### ISSUE TITLE
pAI Bugs (Character Setup)

### ISSUE THREAD

**Issue by bug924411** [Aurorastation/Aurora.3#2772]
**Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.**
* **Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!** N/A
* **Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.** In character setup, you can set your pAI name, description, roles, and OOC comments. However, when I was selected for a pAI these were not auto filled, I had to copy and paste them in. 
* **Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!** This has happened over two rounds. 
* **All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera.** Admin: Alberyk   Round ID: bO4-c9ZW

**Comment by Karolis2011** [comment]
Todo for #6814
