### ISSUE TITLE
Default cyborgs can't understand all langauges

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#2781]
The title, pretty much. Now, I don't know if this is intended or not, but I feel like it's not. Could be one of those things where it's supposed to be motivation for them to pick a module as soon as possible, so they are pretty much useless until they do, but I think it will work either way.

**Comment by SoundScopes** [comment]
As far back as I can remember the default cyborg without a module has never been able to understand all languages

**Comment by skull132** [comment]
I forget, can all other borgs understand all other languages, or are they restricted to clerical? Or was it speaking that's restricted to clerical?

**Comment by SoundScopes** [comment]
Old code:
 Service & Clerical Borgs were able to speak all languages, others could only listen.

Current code:
 Service Borgs can speak all languages except SIIK-TAJR (Guessing there is a lore reason)
 Syndicate Borgs can speak (Common, Tradeband, Unathi, Siik-Maas, Skrellian, & Gutter)
 Construction Drones understand only basic.

All Borgs not mentioned above should be able to understand (Unable to speak):
  Common, Tradeband, Unathi, Siik-Maas, Skrellian, Guteter, Vaurcese, & Rootsong
