### ISSUE TITLE
Antibodies not working as intended.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2788]
Seems you cannot draw blood with someone that has antibodies and inject said blood into someone else with the same viral strain to cure them.

**Comment by skull132** [comment]
I'm uncertain how this worked years ago, but it seems like mostly intended behaviour.

Gotta isolate them, and then distribute that.

**Comment by Geevies** [comment]
Fixed, or intentional. Hasn't been a problem recently.
