### ISSUE TITLE
Not Spawning with Skrellian Headtails

### ISSUE THREAD

**Issue by NebulaFlare** [Aurorastation/Aurora.3#2794]
The item, "skrell silver headtail bands" does not always spawn with the character.

It is not manually removed from the loadout. However, when starting a new game, character setup does not include it within the loadout. After it is added back in, it appears to remain and will spawn, but will eventually revert back to not spawning with the character.

Unknown if this works with other Skrellian head items.

**Comment by Alberyk** [comment]
Fixed.
