### ISSUE TITLE
[NEW MAP] The Uncaged Beast

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#2799]
Lamarr isn't in his cage and can literally jump through the windows and windoor to get at your face. 

To see the obvious bug in work here, press the URL below to see the video.
https://i.gyazo.com/93c15744ed4ea01e33cf145f5d76db7d.mp4

**Comment by Lohikar** [comment]
Fixed by #2785.

**Comment by LordFowl** [comment]
Nobody ever bothered to code Lamarr properly so we avoid the issue by pretending our darndest that he doesn't exist.
