### ISSUE TITLE
Painkiller Overdose Hallucinations don't work.

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#280]
File: Chemistry-Reagents-Medicine.dm

Three medicines have Hallucinations defined as an overdose effect: Paracetamol, Tramadol, and Oxycodone.

The strength of these hallucinations is 2, 2, and 3 respectively. These values are being set properly
However, in Hallucination.dm, the check to trigger actual hallucinations depends on the Hallucination variable being higher than 20. Therefore, these lower values trigger no hallucination effects. They need to be increased.

It's also important to note that the hallucination strength is repeatedly refreshed as long as the drug stays in the mob's system, so it's not necessary to set really high values (like 400) for fear of it wearing off too soon.

My personal suggestion would be 25/40/60 respectively for the strength of these hallucination effects

**Comment by skull132** [comment]
Fixed in #326 .
