### ISSUE TITLE
[NEW MAP & OLD MAP] Loadout Prescription Glasses Spawn

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#2804]
You are unable to spawn in with Prescription Glasses loadout. I've attempted this for the last two days and was not successful.

**Comment by Alberyk** [comment]
Seems to work fine, however, might be related to #2762 if your job has glasses as their round start job gear.

**Comment by UnknownMurders** [comment]
Mine does not as Research Director.

**Comment by Geevies** [comment]
Fixed.
