### ISSUE TITLE
[NEW MAP] Radiation Storm Access

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#2806]
After a false radiation storm, maintenance access are immediately re-added to the doors, leaving people without access trapped in maintenance to meet their certain fate.

**Comment by Mwahahahaha** [comment]
Doesn't this happen on Exodus-era code as well?

**Comment by SoundScopes** [comment]
Both codes give you time to escape the tunnels, from what I can tell the current code doesn't give you enough.

Old code used to sleep for 600 ticks after the storm.
Current code only waits (from what I can math) about 220 ticks after the end of the storm.
