### ISSUE TITLE
Skrell don't float or fall during gravity outages

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#2815]
Skrell are not affected by gravity outages at all, and can walk fine and will not fall when gravity comes back on.

GameID: b00-cldj

**Comment by Pacmandevil** [comment]
Did you have magboots?

**Comment by XanderDox** [comment]
No. I did not. My Skrell do not wear magboots because they find them hard to move in.

**Comment by XanderDox** [comment]
boop

**Comment by Sindorman** [comment]
Could not replicate. Skrell also loose gravity
