### ISSUE TITLE
[Newmap] Females in character set-up preview look like males of their species.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#2823]
Nitpicking if anything else but it looks weird.

https://cdn.discordapp.com/attachments/232661041690050560/328760861558702082/unknown.png

(also idk what the metallic stick lookin' thing is and i wish i knew so i'd stop thinking it looks like something else)

**Comment by Mwahahahaha** [comment]
![image](https://user-images.githubusercontent.com/3950115/27525909-56376d7a-5a74-11e7-90de-dd10825e0720.png)

**Comment by AgentWhatever** [comment]
Still an issue, also any prosthetics that another slot has will copy over in the preview

**Comment by Lohikar** [comment]
Interestingly enough this applies to admin verbs too. A `/mob/living/carbon/human` that has had its gender set via. verb will draw with a male icon. Seems to be related to human icon caching & DNA?

Either way, this is a flaw with human icons themselves, not character setup.

**Comment by MarinaGryphon** [comment]
Still an issue. Not sure if anyone wants to touch human icon caching.
