### ISSUE TITLE
[NEW MAP] Robotics laboratory corner conveyor to op room

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#2827]
There is a conveyor belt which leads from the robotics laboratory to the robotics operating room.
The conveyor belt which acts as a corner seems to be moving items back into the previous belt, making items get stuck in a back-and-forth limbo until someone picks it up through the flaps.

**Comment by Alberyk** [comment]
Seems to work fine in live, try again when possible/with the latest dev build?
