### ISSUE TITLE
[NEW MAP] Lack of light switches

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#2828]
Not sure if this was intentional or not but I've noticed how there is a distinct lack of light switches in areas around the new map. Some places do, like the captain's office, HoP office, and RD office. Command break room, captain quarters. Operating Theatre 1 and 2.

Pretty much every other area doesn't. This includes the head of security's office and the detective's office.

**Comment by Alberyk** [comment]
I added more light switches, report if it seems to be enough or places it is missing.

**Comment by Mwahahahaha** [comment]
That must've taken quite a bit of time and effort. Sorry to put you through that.
I'll check on it.

**Comment by Mwahahahaha** [comment]
I don't think the following areas have light switches that won't necessarily need them but it's up to your own discretion:

Aurora-2
- Telescience
- Xenobiology
- Engineering Outpost - Meeting Room (none on the Exodus)
- Research Sublevel - Xenoarchaeology EVA (none on the Exodus)

Aurora-3
- Cargo Warehouse Storage (none on the Exodus)
- Research Misc Lab
- Research Break Room
- Research Server Room (none on the Exodus)
- EVA Storage (none on the Exodus)
- CE Office
- Engineering SMES Room
- Engine Monitoring Room
- Engineering Access Airlock to Engine Room
- Engine Room
- Armoury (none on the Exodus)
- Medbay ICU
- Medbay EMT Quarters
- Medbay Cloning Laboratory
- Medbay Reception
- Medbay Chemistry Lab / Medicine Storage
- Chapel main area
- Waste Disposal / Trash Compactor

Aurora-5
- Cargo Bay Loading / Delivery Office
- Custodial Closet
- Locker Room
- Auxiliary Tool Storage

Aurora-3 and Aurora-5's dormitories also have two light switches but I'm assuming that's intentional given the fact that they're both big rows of beds where people sleep in.
Similar design with Exodus' dorms.

Tcomms have no light switches either on Aurora-5 but that's a similar design with Exodus.
Tcomms on Aurora-6 though doesn't have a light switch although Exodus' Tcomms break room didn't have any either.

Thanks for your help!

**Comment by LordFowl** [comment]
Offices, such as the detective's offices need light switches.
Utility rooms, such as the custodial closet or the warehouses, that are only used to store objects, can have lightswitches.
Workstations, such as xenobio, should not have lightswitches.
