### ISSUE TITLE
Mining Drones cause intense lag through Ore-bag shenanigans.

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#2831]
There needs to be some sort of alteration to how Ore dropping and depositing functions, as it stands it backlogs to the point of mass lag. It seems infrequent but when it happens, it's crippling to the entire server. Please fix.

**Comment by Fire-and-Glory** [comment]
It is truly awful.

**Comment by Lohikar** [comment]
Investigated a bit; looks like it might be an issue with quick-pickup/quick-empty in ore bags themselves. Lag seems to match something in that proc using way more CPU than it should be before hitting the tick-check.

**Comment by SirFruitcakes** [comment]
Updating to expunge inaccurate information, none of the upgrades touch the Ore capacity.

**Comment by skull132** [comment]
Implementing a fix which limits the capacity of storage objects. Anything with a large enough storage capacity breaks a whole lot more things (some of which I'd rather not tick check) than they're worth.

**Comment by SirFruitcakes** [comment]
Well, the reason they had 400 capacity is because they're unable to drag crates, is there anyway to make up for that if they're losing it?

**Comment by skull132** [comment]
Nooot without really fuckey code I'm afraid. Or writing an entirely new subclass.

I'm hesitant to put delays into functions which generate UIs, and one of the loops that gets stuck is responsible for doing exactly that.

**Comment by Jalleo** [comment]
How about giving them multiple ore bags instead?
