### ISSUE TITLE
[NEW MAP] Photocopying Machine doesn't print desired amount

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#2836]
In a similar regard to:
[#1494](https://github.com/Aurorastation/Aurora.3/issues/1494)
Select copies over 1 and they use up toner without actually printing that amount.

--

I've noticed earlier today though that it does suffer from another issue which I can only presume to be something much grander, important, and big for the entire game: it's when the speech bubbles freeze and don't go away when a character has said something, and when the airlocks fail to automatically close. A lot of things seem to hang for about half a minute while people can still move around and talk and do stuff. It sort of just happened when I pressed "Print" while it was still printing 1 copy.
I'm not sure if it's going to be worth opening another issue until further testing can be done. I don't know what actually causes that controller(?) to freeze up, but it may or may not be possible that the photocopier could be relevant to that as at least one factor. It's probably nothing, but, who knows right now?
Mind you, it still tracks toner levels when you press "Print" while it's still hanging. And then when it stops hanging, it might generate a paper copy but its behaviour is more or less like when you configure it to print more than 1 copy (i.e., it doesn't generate the number of copies a la the number of times you pressed "Print" while it was still hanging)

**Comment by Lohikar** [comment]
Yeah, this sounds like a timer controller hang-up. Will investigate further.

**Comment by Juani2400** [comment]
This is still going on.

**Comment by ProbablyMenown** [comment]
This is still happening lmao.
