### ISSUE TITLE
Necrotic Organ Repair surgery is broken

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#284]
A surgical procedure on the baywiki, which our codebase mostly supports: https://wiki.baystation12.net/Guide_to_Surgery#Necrotic_Limb_.26_Organ_Repair

Making the incision, clamping bleeders, and retracting the incision all work fine, of course. Those are standard.

Cutting away the dead tissue with a scalpel works, that's specific to this procedure.
The next step is to use a dropper full of peridaxon on the target area. This fails:

> You start applying medication to the affected tissue in Arnie Garratt's left leg with Dropper.
> Nanako Magojiro is trying to squirt something into Arnie Garratt's eyes!

The procedure to regenerate the tissue starts, but it ends with squirting into the patient's eyes, instead, and never properly finishes. The surgery is stuck at this step endlessly, and the dead part cannot be regenerated

**Comment by OneOneThreeEight** [comment]
The organ has to be septic for this procedure to work.

**Comment by NanakoAC** [comment]
i'm aware, and it was when i tested it. the feature is bugged.
if you can get it to work, i'd love to see it

**Comment by NanakoAC** [comment]
i'm aware, and it was when i tested it. the feature is bugged.
if you can get it to work, i'd love to see it
