### ISSUE TITLE
Cyborgs have mastered the art of Translucent Photography

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#2857]
If you use your innate Camera tool to take a picture, then go to a Photocopier, and print that picture, it is missing its sprite. This makes you completely unable to use your camera function how it was intended. I have a feeling it lost its sprite back when Picture images were broken and were being fixed, I bet someone changed the default Photo sprite and forgot to update the 'borg sprites. Anyway, it just needs to be updated or something. Here's image proof. https://puu.sh/wwfMp/b6664a574a.jpg

**Comment by SoundScopes** [comment]
Duplicate bug #1928

**Comment by skull132** [comment]
Closing as dupe.
