### ISSUE TITLE
Laptops don't have record programs

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2858]
They used to and it was a big bonus for getting laptops. Being able to access records without running over to one of the few consoles. Not sure if it was just an oversight in transferring over all the relevant programs to the new system or if someone had a problem with records being too accessible, but it would be nice to have them back.

**Comment by Doxxmedearly** [comment]
Very old bug, records have been working fine on laptops for some time now. Closing.
