### ISSUE TITLE
Unstable Mutagen mutation chance is set too low

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#286]
Chemistry-Reagents-Toxins.dm, line 233, reads:

if(prob(removed * 0.1)) // Approx. one mutation per 10 injected/20 ingested/30 touching units

It seems that whoever wrote this line falsely believed that prob() tests against a random value in the range 0..1. This is a reasonable belief since it's often how random numbers are done in many other languages and environments, and with that belief it would mean a 10% chance per unit.

However, prob() actually tests against a value in the range 0..100, making this event far less likely than intended.

To fix it, change the line to:
if(prob(removed * 10)) // Approx. one mutation per 10 injected/20 ingested/30 touching units

**Comment by ArcBotSS13** [comment]
Nanako, if you know how to fix it then you should make a fork and commit a PR referencing this issue. You seem to have knowledge about coding.

**Comment by skull132** [comment]
Fixed in #343 .
