### ISSUE TITLE
Stealthed Ninjas are not invisible to the AI(?)

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#2868]
I finished an AI round where the AI had several situations where it should probably not have been able to see me, but it clearly reported my location to people I had just passed while stealthed.  After the round, the AI claimed it had never actually seen me activate stealth and disappear. 

Of course, It's difficult to confirm without testing, but it should be looked into.

**Comment by SoundScopes** [comment]
Duplicate report with less info #1863
