### ISSUE TITLE
[NEW MAP] Solar Array Wiring

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#2870]
Aurora-6's solar arrays have five power cables that are facing East instead of West.
![image](https://user-images.githubusercontent.com/3950115/27680199-8e9ec836-5ced-11e7-96a0-27a3a0caeb40.png)

Aurora-5's Beta arrays on the Tcomms have five solar panels that don't seem to have wiring on them.
![image](https://user-images.githubusercontent.com/3950115/27680136-5e268aea-5ced-11e7-818b-ca1794843ba7.png)

Both of these result in the panels not being detected on the console in their respective maintenance rooms.

Thanks for the good work!

**Comment by LordFowl** [comment]
Sounds like a task for engineers to fix themselves. What do we pay them for, except their shitty sarcasm in issue reports?
