### ISSUE TITLE
Construction cyborg module list

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#2876]
Construction cyborgs are missing a blueprint "scroll" > to create new areas, floor tile dispenser > to put new tiles over the metal lattice and... something else, i've already did forgot what

**Comment by SoundScopes** [comment]
I've checked along a few code bases, bay-code has never had a cyborg with blueprints.
Instead of the floortiles they have an RCD which is faster and doesn't require you to make lattice first.

**Comment by HetNeSS** [comment]
I've got something coming up on that theme now.. It took like 3 hours of real time.. Another pull request will be up soon

**Comment by SoundScopes** [comment]
I get the idea, I think there was a reasoning behind it but I'm not high enough up the chain to be able to remember what it was. I've poked the guy who is.

**Comment by SirFruitcakes** [comment]
The Construction Module also can't install APCs/Light tubes AFAIK. It doesn't have any Cable Coil or any means of getting any. The Blueprints would help set up APCs/Areas but it's really not that helpful for the Cyborg itself without the means to do all of that anyway.

**Comment by SoundScopes** [comment]
Related PR #2880
