### ISSUE TITLE
The AI core SMES does not power the APC in the same room

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#288]
For whatever reason, the SMES behind the core does not directly power the APC it is supposed to be hooked up to. If the main engine under any circumstance ends up failing, intentionally ejected or blown up, the AI has a few precious minutes before their APC drains due to no external power hooked up to the network.

**Comment by skull132** [comment]
Not seeing how this is possible. The core's APC is linked to the SMES behind it directly.
http://puu.sh/oT1F6/404ee23512.png

And I'm unable to replicate this, as well. I tried disabling the master SMES in the engine room, and the APC kept charging (as expected).

**Comment by OneOneThreeEight** [comment]
What about hacking the adjacent APC in the AI core? Is there any specific behavior that occurs for hacked APCs in terms of powernet?

**Comment by skull132** [comment]
Shouldn't be, no. Was is possible that the engineers hooked an emitter up
to the AI internal power loop? The drain there might have just kicked your
APC out, as there was not enough available power?

**Comment by Bedshaped** [comment]
Please provide more information. Reopen if this is a persistent issue.
