### ISSUE TITLE
[Newmap] Funky shuttle walls

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2881]
![2017-06-30_18-57-46](https://user-images.githubusercontent.com/7097800/27757334-05e4ad06-5dc6-11e7-9d2a-4aa9dc52c2b5.png)

**Comment by LordFowl** [comment]
What is funky about this?

**Comment by SoundScopes** [comment]
The parts next to the door have icons that look like they connect to another wall

**Comment by Lohikar** [comment]
This shuttle is supposed to be orange; it's not meant to be using the smoothed walls.

**Comment by Alberyk** [comment]
This is fixed.
