### ISSUE TITLE
Sterilizine does not sterilize wounds

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#289]
The ingame description of sterilizine says this:
"Sterilizes wounds in preparation for surgery and thoroughly removes blood."

I'm taking that as a sign of developer intent.
Sterilizine is a medicine that's applied by touch, the best way of administering it seems to be using a spray bottle. or i guess you could splash a beaker on the patient.

Sterilizing wounds is a thing, it happens when you dress a wound with bandages/ointment/advanced kits, although not instantly (a bandaged wound has a small chance to become disinfected each tick)

Sterilizine does not sterilize wounds. All it does, is lowers the patient's main/general germ level, and cleans visible blood off of them. It does not affect the germ level of wounds, or organs. For a reasonably complete explanation of the infection/germlevel system, see here: https://aurorastation.org/wiki/index.php?title=Guide_to_Medicine#Infection

 This seems like missing functionality for sterilizine.

Recommended fix: Add a loop into its Affect_touch function, that cycles through all wounds on the patients body. 
For each wound,

- Set its germ level to zero
- Toggle the disinfected flag.

**Comment by skull132** [comment]
Implemented in #330.
