### ISSUE TITLE
[Newmap] BYOND Crashes on compile in some cases

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2902]
Map `maps\aurora-2\aurora-7_derelict.dmm` causes BYOND on Linux to crash, and BYOND on Windows to behave strangely.

Unincluding this map fixes it.

**Comment by Alberyk** [comment]
Also, the map seems to be broken even when running on windows, as you can't jump or teleport to the derelict

**Comment by skull132** [comment]
Fixed in #2913 .

Might have been caused by me running TGM merge twice.
