### ISSUE TITLE
Exodus-development issues

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#2904]
List of things that need to be fixed/moved-to-config for the Exodus to work properly on development.

- [ ] Shuttles do not function.
- [ ] Antag shuttles have incorrect areas.
- [ ] Plasmacutter's path has been changed; parent_type hack works to get it to compile.
- [ ] Arrivals spawn spawns you at station, but only with gear from `EquipPersonal`.
- [ ] Asteroid gen Z-levels are not set.
- [ ] Detective office needs to be updated to work with FT?
- [ ] Some missing areas that Exodus uses but are stripped from Development.
- [ ] `border_only` fire doors.

**Comment by chaoko99** [comment]
Still relevant?

**Comment by Lohikar** [comment]
Some of this will be fixed with the WIP maploader changes, so I wouldn't do any work on it just yet.
