### ISSUE TITLE
[NEWMAP] Airlock console not updating.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#2907]
Engineering sub-level airlock console isnt updating when you cycle in or out. Its constantly stuck at 101 kPa.

**Comment by HetNeSS** [comment]
That airlock at the west maintenance to the south from engine room at the main level? Yea.. always being forced to keep it unbolted for the use. Mining main airlock sometimes have the same problem, just stucking somewhere at 20kpa and that's all. Neither pumping air or syphoning it
