### ISSUE TITLE
Potassium Chloride/Chlorophoride do not stop hearts.

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#291]
Global.dm, line 208:
var/list/heartstopper  = list("potassium_phorochloride", "zombie_powder") // This stops the heart.
var/list/cheartstopper = list("potassium_chloride")                       // This stops the heart when overdose is met. -- c = conditional

This indicates these chemicals are intended to stop a patient's heart. Descriptions imply this too, and there's code to implement it:

mob/living/carbon/human/Life.dm
Line 1540, handle_pulse function.

There are two bugs here, and i'm not certain why they happen:

1. Potassium Chlorophoride has no effect on the heart at all. This is because the heartstopper list in global.dm uses the wrong ID. It should use"potassium_chlorophoride" instead of "potassium_phorochloride"

2. Potassium Chloride, when overdosed, sets the patient's pulse visibly to zero, but does NOT actually stop the heart. There are no ill effects of this besides analysers reading their pulse as zero bpm

**Comment by skull132** [comment]
Fixed by Akrilla.
