### ISSUE TITLE
[NEW MAP] power between z-levels

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#2910]
Power is not transferring between Z-levels
3.29288e+006W in power network. on main level
The cable is not powered. on other ones

After some manipulating with up-goes and descending wiring, power seems to be fixed up itself. Not sure what was the problem though

**Comment by skull132** [comment]
Can you post the exact location of this? Most likely a mapping error.

**Comment by HetNeSS** [comment]
Maintenance tunnels, somewhere at the south part, where the wiring goes up between levels. An image gonna be shortly

**Comment by HetNeSS** [comment]
Main level - 109,62,4 - https://www.dropbox.com/s/kpoo57h3zuiw8zs/1.jpg?dl=0
Sub-level - 109,62,5 - https://www.dropbox.com/s/44j0imhfa9jtflk/2.jpg?dl=0
surface level - 109,62,6 -  https://www.dropbox.com/s/vrc35bkid7tter3/3.jpg?dl=0

**Comment by skull132** [comment]
Thank you! Will have a mapper investigate.
