### ISSUE TITLE
[NEW MAP] No Atmos Technician Jumpsuits or Red Hard Hats in Engineering

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora.3#2911]
There are two wardrobe closets in the engineering lobby and neither of them have atmos jumpsuits nor their red hard hats. The atmos lockers inside Atmospherics also don't have them.

**Comment by Lohikar** [comment]
What about the lockers in the sublevel locker room?

**Comment by Keinto** [comment]
Not there in the washroom either. But even if they were, atmos techs shouldn't have to go all the way down there just to get a jumpsuit and red hardhat.
