### ISSUE TITLE
[Newmap] Space-wind is particularly intense now

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#2917]
On the other new map tests it wasn't that bad. But now miners will often find themselves tripping over once, twice, and maybe three times at random intervals before they can get back to work again.

**Comment by Lohikar** [comment]
Probably caused by #2892.

**Comment by Jalleo** [comment]
Something also causes a pressure buildup outside of the solar array above arrivals. It got up to 20Kpa at least and there was a edge to it somewhere between the airlock and the end of the solar arrays. May help in debugging.
