### ISSUE TITLE
Miner drone thermal drills don't regenerate their shots.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#2920]
Thermal drill also doesn't recharge in a cyborg recharger.

Buuuuugs.

**Comment by SirFruitcakes** [comment]
It will recharge automatically, even outside of a Charger, but you have to select it. It's the same way for the Security 'borg/Combat 'borg Laser Rifles. I really wish it did recharge in chargers though, that'd be convenient.
