### ISSUE TITLE
Maintenance Drone Airlock Access

### ISSUE THREAD

**Issue by CyberstormFox** [Aurorastation/Aurora.3#2933]
This bug was first noticed today  (7/2/17) but as a maintenance drone, it does not have access to interact with or open the "Door Controls" panel on any airlock that has limited access (Such as Engineering or Research). Same with such windoors of limited access. 
I get the error "Access Denied" in red text.
There's no problem with public access airlocks such as in the primary hallways.
In the past,  Maintenance Drones, like all other synthetics, had all access.

**Comment by Juani2400** [comment]
I tried this today. Drones seem to be able to access all doors. I'll be closing for now. Create another issue if this still persists.
