### ISSUE TITLE
[NEW MAP] PDA Message Bug

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#2935]
Reported this to Alberyk over adminhelp. Attempted a shortfix to relog and see if that'll fix it, but unfortunately, it did not. 

 I have no clue why and how this happened. I just received the message like any ordinary person would. 

![image](https://user-images.githubusercontent.com/12143105/27777136-d04d629e-5f75-11e7-9e58-4530c468e87a.png)

**Comment by Pratepresidenten** [comment]
What was the issue exactly? To me it looks like the sender bypassed the occational PDA spam filter settings being set to filter out messages containing any spaces, AKA. [ ]. Servers will refuse any messages containing spaces, hence other means of spacing needs to be used.

**Comment by skull132** [comment]
Are you or @Alberyk able to confirm that you were the only one effected or not?

**Comment by SoundScopes** [comment]
Looks to me like it's the message box being really small compared to the size of the window

**Comment by skull132** [comment]
That's him resizing it, I think.

**Comment by Lohikar** [comment]
That box shouldn't be resizable; looks like a template error.

**Comment by skull132** [comment]
More like a CSS fault. If you compress the window enough, it has no choice but to shove it into scroll-boxes.

Plus, that's not even what the report is about :P

**Comment by UnknownMurders** [comment]
Lohikar got the message and seems to know the error.

**Comment by skull132** [comment]
Next time doing as the template describes and actually describing what's wrong would be nice. Shoving a picture in doesn't really help much.

Anyways. CSS/HTML error, not much that can be done about it until we force HTML5 onto people. For ref: the dynamic height is not taking into account the height of the scrollbar. So it spawns enough height to contain 2 lines of text, but scrollbar takes up .8 of those 2 lines.
