### ISSUE TITLE
Two Wizard bugs

### ISSUE THREAD

**Issue by NebulaFlare** [Aurorastation/Aurora.3#2939]
1. Any polymorph spell, when used, will remove your ability to be a wizard when you turn back. It's not wholly removed and you retain your spells, it just doesn't register you as a proper wizard.

2. When granting a contract to an individual, if they hold a spell that does not require them mage garb (hat and robes) it still demands these items.

**Comment by skull132** [comment]
> When granting a contract to an individual, if they hold a spell that does not require them mage garb (hat and robes) it still demands these items.

Passage confirmed as an example.

**Comment by Alberyk** [comment]
I know what is causing the first issue and I have a fix, but, I tested a fireball contract and it worked fine without the wizard garb. You probably did something wrong, this is what you gotta do to use a contract right;

1-buy the contract version in the book
2-pick up the contract and use it to bind to you
3-give to a non magical spessmen to accept
4-non magical spessmen gets spell, you get spells that can reward/punish/etc the spessmen

**Comment by NebulaFlare** [comment]
That's exactly what I did. The spell I used was Passage - it's not a garb spell, and my apprentices couldn't use it because it demanded wizard garb.

**Comment by Alberyk** [comment]
Except it needs a wizard garb: https://github.com/Aurorastation/Aurora.3/blob/development/code/modules/spells/targeted/projectile/passage.dm#L17

**Comment by NebulaFlare** [comment]
If such is the case, then it states 'no wizard garb' in the spellbook.

**Comment by Alberyk** [comment]
![wizardspell](https://user-images.githubusercontent.com/11579997/27831992-65facb6e-60a3-11e7-8f20-496d38694bf9.png)
