### ISSUE TITLE
Latejoin AIs spawn in the Central Command elevators.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#2942]
Seen this twice today, wasn't sure if the first time was just a one-off case.

**Comment by skull132** [comment]
:ree: Lohikar.

Or was it Printer.

**Comment by Lohikar** [comment]
> tfw you're the first person blamed for everything

**Comment by Lohikar** [comment]
> tfw it turned out to actually be my fault
