### ISSUE TITLE
Longer Fringe and Long Hair Alt are the same icon; ditto with Long Fringe and Shoulder-Length Hair Alt

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#2979]
As the title:

![image](https://user-images.githubusercontent.com/3950115/27990304-dc279cba-6484-11e7-99b2-6fb0c1c8fece.png)

—

![image](https://user-images.githubusercontent.com/3950115/27990305-e1c0ad06-6484-11e7-9cc4-26e9b6a357ab.png)

**Comment by Mwahahahaha** [comment]
![image](https://user-images.githubusercontent.com/3950115/27990342-3571434c-6486-11e7-82b3-9edab87eafbb.png)


—

![image](https://user-images.githubusercontent.com/3950115/27990338-0e1e63ec-6486-11e7-98d1-f3844be48024.png)

**Comment by MarinaGryphon** [comment]
Is this in preview only, or actually in-game?

**Comment by Mwahahahaha** [comment]
Both.

**Comment by Alberyk** [comment]
Still an issue in the master branch
