### ISSUE TITLE
[NEWMAP] Formatting on spawned papers are utterly fucked

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#2986]
![image](https://user-images.githubusercontent.com/19973802/27992595-96ec687a-64ec-11e7-84b5-20adcaf590c5.png)

The armory inventory form in the warden's office and the CMO's note both look like this, more papers also look like this probably.

**Comment by skull132** [comment]
Paper's Initialize() doesn't appear to be doing its thing.

**Comment by Pratepresidenten** [comment]
Confirmed to be an issue with the outgoing CMO's notes aswell. It also references the Exodus in its text.
