### ISSUE TITLE
Engineering Sub-Level EVA airlock does not cycle

### ISSUE THREAD

**Issue by Hugo14453** [Aurorastation/Aurora.3#2988]
[This airlock](https://a.pomf.cat/qqoele.png) (pictured circa 2017 colourised)
Does not seem to cycle correctly, upon attempting to cycle to external it will never open the doors, the chamber pressure on the keypad constantly shows 101kPa so I suspect it is an issue with the pressure sensor.

[This image](https://a.pomf.cat/nvohly.png) (modern day) displays the airlock forced open and exposed to space but 101kPa are still displayed.

**Comment by Pratepresidenten** [comment]
The airlock cycles, and the pressure drops when forced. The airlock controller is just.. Broken. Doesnt update.
