### ISSUE TITLE
Error Message When Opening PDA

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#2990]
Only happened once, but here it is. 
![pda error](https://user-images.githubusercontent.com/24979527/27994602-3dc1b898-648f-11e7-9f2b-0b073d190819.png)
No clue how to recreate, though I figured I'd log it anyway.

**Comment by skull132** [comment]
Cache hadn't failed to download yet perhaps. How long had you been in the game before opening the PDA?

**Comment by verywhiterabit** [comment]
About 20 minutes probably.

**Comment by skull132** [comment]
No, it should have downloaded again. Has this happened before as well?

**Comment by verywhiterabit** [comment]
Never happened before, just as well I haven't seen it happen again. It was an odd, one off bug.
