### ISSUE TITLE
{NEW MAP} PDA deletes itself when selected from inventory while resting

### ISSUE THREAD

**Issue by KepQwet** [Aurorastation/Aurora.3#2991]
Steps to replicate:
1. Put your PDA in your ID slot
2. Use the 'rest' verb (happened to me while I was on the holodeck, not sure if location's relevant)
3. click your PDA
4. curse the gods of bluespace magic, as your PDA has just been condemned to the land of loc(0)

May also apply to other inventory items.

**Comment by Lohikar** [comment]
PDA's not deleted, just somehow being transported inside your mob.

Applies to all inventory items iirc.

**Comment by Alberyk** [comment]
Not only in new map

**Comment by skull132** [comment]
Dupe of #1616
