### ISSUE TITLE
[NEW MAP] Fax Receiver

### ISSUE THREAD

**Issue by UnknownMurders** [Aurorastation/Aurora.3#2993]
![image](https://user-images.githubusercontent.com/12143105/27997296-f6c67588-64ba-11e7-8bc6-07f2a51879f2.png)

You know when you go to a fax and pull up a list of fax receivers and click on the Unknown as receiver. Though, you would be unable to send it to the Unknown because when you attempt to send it to Unknown, you would get this message.

"The fax machine beeps, "Error transmitting message."

**Comment by Juani2400** [comment]
Possibly related to the Derelict.
