### ISSUE TITLE
[NEW MAP] Cult runes are not working correctly

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#2998]
I was playing a cult mixed with wizard round on the new map and I was unable to get any form of research past the basics done. It seemed that the word for blood was different from my point of view and the server's point of view. I know this because I was able to get the words for travel, blood and self to cast a boil rune. The issue came when I needed to get past this tier of research but the word for hell wasn't working, so I contacted ahelp about it and it turns out on the admin end, the word for blood was completely different to what I had therefore, using the admin's blood word didn't work at all for me.

Another thing was that I had the correct word for hell on my end because it was given to me at the start of the round, yet it didn't work in combo with the others either (astral projection / ghost self).

**Comment by Mobman1999** [comment]
Wittnessed the same problem

**Comment by SonicGotNuked** [comment]
Bay merge added a little thing I noticed in the cult ruin research, sometimes ruins would pulse when they should not pulse. I am still able to complete the research, but I forget what ruins do this due to me not playing cult in a while.

**Comment by skull132** [comment]
Rune code hasn't been touched in aaageees. Could be what Sonic said.

**Comment by SonicGotNuked** [comment]
Yeah, it would be extremely confusing and bad when cult all gets the wrong words because of this.

**Comment by Alberyk** [comment]
This is fixed with the removal of cult research.
