### ISSUE TITLE
{NEW MAP} Stacker releases cyborg glass

### ISSUE THREAD

**Issue by KepQwet** [Aurorastation/Aurora.3#2999]
Glass does not release from the stacker as glass, but instead releases as a cyborg glass module.

**Comment by MarinaGryphon** [comment]
This should be impossible. Looking into it.

**Comment by HetNeSS** [comment]
True. To prevent anyone filling autholate or such things from cyborg material dispencer.

**Comment by skull132** [comment]
Has this been replicated at all?
