### ISSUE TITLE
The Miner Cyborg Basic Sprite (Originally Classic) is missing.

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#3051]
At the moment, if you choose the 'Basic' Sprite, you will be an invisible Robot wandering around. Noone can see you. I believe it's something to do with the recent Sprite name changes. 

https://puu.sh/wKAVP/35ec4c565e.jpg

^ In that screenshot, i'm standing in the top tile.

**Comment by AgentWhatever** [comment]
ffffffuck. Must be a typo by me

**Comment by AgentWhatever** [comment]
which module specifically?

**Comment by SirFruitcakes** [comment]
Mining, but it might be the other Modules too, would be a good idea to check.

**Comment by AgentWhatever** [comment]
Capitalisation is a bitch
