### ISSUE TITLE
Spacecleaner Vs Slimes

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#306]
Much like water, Space Cleaner can damage slimes on contact. However, there are two oddifies:
1. Damage is only applies when spacecleaner is sprayed on the floor tile under the slime. It does NOT have any effect when sprayed on a slime directly. It should have the same effect whether direct or not.
2. The damage dealt on application is randomly chosen between 5-10, regardless of the volume used. Damage should scale with the quantity of spacecleaner that is applied

Also a recommendation: If sprayed directly on a slime, it should still affect all slimes on the tile. they often stack up

**Comment by Bedshaped** [comment]
Please reopen if you want to continue this.
