### ISSUE TITLE
Doing anything with the floor (removing/laying wires, tiles, etc) automaticly points the character to the west

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#3071]
This goes for anything you do on the floor your character is on.
This also results in always laying a knot-cable going to the west edge if you lay it down on your tile.

**Comment by skull132** [comment]
Can confirm. This is the weirdest shit ever. FUCK I KNOW WHAT DID THIS :ree:

**Comment by AgentWhatever** [comment]
Addendum: ANY enviromental interaction on your own tile points you west

**Comment by skull132** [comment]
or not. wtf am i on.
