### ISSUE TITLE
Regular people can disarm the organic blades of of changelings.

### ISSUE THREAD

**Issue by Weer6** [Aurorastation/Aurora.3#3072]
How to reproduce this bug.
1. Get a changeling to sprout a organic arm blade.
2. activate disarm intent, and click on him until he has been dis-armed.
3. laugh as his arm blade splats into gore and hsi arm has been disarmed.
4. sob as he punches u.

Also, With the Changeling Terminator/whatever form, you can pet them without immediate punishment. I believe there should be a punishment for petting the changeling murder form.

**Comment by AgentWhatever** [comment]
Changeling murder form is cute.
Don't take away hugging senpai, you b-baka

**Comment by Weer6** [comment]
You don't hug it. you pet it like some sort of friendly dog.
