### ISSUE TITLE
Tesla SMES Issues

### ISSUE THREAD

**Issue by ParadoxSpace** [Aurorastation/Aurora.3#3074]
The tesla SMES units still sometimes show up as undefined kWh, and I don't believe even admin jiggling can fix it.

**Comment by Juani2400** [comment]
Do you have a screenshot of what is happening?

**Comment by ParadoxSpace** [comment]
I don't right now, but it just displays the SMES's charge as undefined kWh

**Comment by skull132** [comment]
Smells more like a code than a map issue? Specially if it's random.

**Comment by Juani2400** [comment]
I'll have to look into it. That SMES has a set percentage of charge it is supposed to start with. May be borked map-wise

**Comment by HetNeSS** [comment]
Tried to set it up right now.

> 2.26595e+006W in power network.
> 1.73147e+006W in power network.
> The cable is not powered.

Power is jumping between those 3. Might be because of tesla charges being pulsed to the output wiring, while supermatter TEC's have more or less stable output. So, those moments between tesla pulses are tracked by machinery, I suppose, can bug out a bit.

**Comment by skull132** [comment]
That's because of how Tesla works, yes. An old bug would be where there's no power at all in the network, ever. But since it spikes, it's fine.
