### ISSUE TITLE
AI containment area shielding being unsecured

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#3085]
Four field generators at the corner of AI lobby entrance room are unbolted, which restricts players to turn them on.

**Comment by HetNeSS** [comment]
Also, two of them are missing wiring under it
https://www.dropbox.com/s/e1tnwgc2rhx8i6n/15.png?dl=0

**Comment by Juani2400** [comment]
Wire has been fixed. We'll leave them unanchored, as part of balancing, so they cannot convert it into a fortress without a borg/engineer.
