### ISSUE TITLE
Hull Shields Deploying Incorrectly

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#3096]
Hull shields are deploying on top of the exterior hull instead of just outside it. Because of this, carp can still attack windows with a shield deployed. I'd imagine meteors will also impact the windows before the shield as well like this. 

![shield](https://user-images.githubusercontent.com/24979527/28316128-83ff65ba-6b8f-11e7-9cbe-9d7ff4df6a0c.png)

There's also an issue with how they deploy in the hallway to the pool, as seen here.

![shield 2](https://user-images.githubusercontent.com/24979527/28316171-b522754c-6b8f-11e7-9535-255bf3e06359.png)

**Comment by skull132** [comment]
ayy lmao.

**Comment by Jalleo** [comment]
It isnt just that it can also randomly go in a line out away from the arrivals area towards tcomms.

**Comment by Pratepresidenten** [comment]
The shields forms around all possible, non-existant shuttles aswell. All arrivals docks, an escape pod aft of the holodeck and the front end of the merc shuttle below mining.
