### ISSUE TITLE
Wizard teleport bug

### ISSUE THREAD

**Issue by MasterJJ99** [Aurorastation/Aurora.3#3104]
Using teleport spell to bridge location, Teleports you out side the bridge with no atmos

**Comment by Alberyk** [comment]
Might not be a bug, if I recall, the teleport spell has a chance to fail or something.

**Comment by SoundScopes** [comment]
I do not believe that is possible from what I just read.
Did you appear in one of the three highlighted tiles? http://puu.sh/wNJs2/5594a5dc8c.png

**Comment by MasterJJ99** [comment]
Yes the right one
