### ISSUE TITLE
Borg chassis spawned in Cargo will keep creating copies.

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#3107]
So. This round, I was playing Roboticist. At some point into the round, Cargo brought us a fully built borg chassis. I assume it had spawned in the warehouse. I activate our posi-brain and found someone - great. I proceed to place the brain into the borg Cargo had given us.

To my surprise, once I put the brain into the borg, a new empty brain spawned right next to me, and the borg with the player spawned on top of the chassis. In other words, we still had the chassis Cargo had given us, and the brain, but we also had a cyborg (albeit without a battery, that we had to add).

I tried this again after finding another host for the brain, and the same happened. We didn't lose the brain or the chassis.

I have not tested this outside of that round.

**Comment by Mwahahahaha** [comment]
[1141](https://github.com/Aurorastation/Aurora.3/issues/1141)

**Comment by Alberyk** [comment]
Fixed already.
