### ISSUE TITLE
Tajara markings either not working or not showing in the preview.

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#3110]
As said. When selecting body markings on Tajara, they do not show up in the character setup images. The feature is possibly not working, at all.

**Comment by Alberyk** [comment]
what marking are you using? Because, they do work fine here;

![camopants](https://user-images.githubusercontent.com/11579997/28386392-c8fc4c6a-6ca1-11e7-8c25-9cb93eb3555c.png)

**Comment by Fire-and-Glory** [comment]
I and another guy:tm: are having problems with this too.

The preview doesn't actually include any changes to markings, if I try to remove markings I had already added to the character in the past or add new ones, nothings happens.

![image](https://user-images.githubusercontent.com/19973802/28417491-7305007a-6dac-11e7-91c2-eb3e91cfa252.png)

**Comment by Juani2400** [comment]
An issue similar to Fire's was reported today via ahelp, as well. The same issue that Fire has happened to me yesterday during my tests in the test server, just after restart.

It does not matter which markings you pick, all of them are affected for me.

**Comment by Lohikar** [comment]
I'm not sure what could be breaking the preview for just _some_ people, that preview is rendered server-side and just sent as a single image to clients.

I doubt this is an issue with human overlay compile either considering that gear seems to work.

Maybe caused by recent changes to human icon caches?

**Comment by Lohikar** [comment]
Looks like this might be a caching issue with human icons, investigating further.
