### ISSUE TITLE
Auto-mute issue

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#3111]
![image](https://user-images.githubusercontent.com/11053780/28386706-6889e95c-6c9a-11e7-9888-35448fbd4807.png)

Skull probably already knows this is an issue and doesn't quite have a fix, but I do believe I know the actual reason as to why it trips and auto-mutes a dude.

I started getting used to using the auto-say command for the command bar and using the arrow keys for movement. Out of mild curiosity, I held down the enter button when the above showed up.

Even though Skull has apparently added exceptions regarding empty say " messages being sent, Auto-Mute doesn't care what Skull thinks shouldn't be possible and enacts its tyranny upon the unfortunate playerbase.

![image](https://user-images.githubusercontent.com/11053780/28386839-e0545990-6c9a-11e7-9d3a-cd9aa3c3c08a.png)

Food for thought, anyway. Seems to only really occur when holding down the enter key when the auto say " button is selected.

**Comment by SoundScopes** [comment]
Spam protection doesn't check if the message is null, just how many times it's called by x client.
The say verb doesn't immediately return if the message is null.

**Comment by skull132** [comment]
Apparently some say verbs don't, some do. Fucking APIs.
