### ISSUE TITLE
HoS' office may be missing a disposal pipe under the door

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#3117]
Opening this issue for confirmation purposes. Saw a missing pipe under the airlock, and someone said that it had happened in other rounds. Need to confirm and fix.

**Comment by SoundScopes** [comment]
http://puu.sh/wOIwP/cb5e6b83ce.png

**Comment by Juani2400** [comment]
Thank you. o.o)b

**Comment by HetNeSS** [comment]
Flush your litter onto a warden like a badass
