### ISSUE TITLE
Navigation beacon paths

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#3118]
Occasionally bots with access that use the navigation beacon may open up the security back entrance to try and shortcut their way through.

I caught one in the bloody act itself red-handed.
![image](https://user-images.githubusercontent.com/3950115/28428334-accddf3a-6dab-11e7-96a7-6e7545cae7eb.png)

Cheeky little bastard.

![image](https://user-images.githubusercontent.com/3950115/28428414-ee47545a-6dab-11e7-8996-d556b9107629.png)

Works both ways.
Officer Beepsky has a bad influence on other bots too and this behaviour can also be observed with its younger sibling ED-209 (although sometimes it's a little rarer and they don't do it — perhaps this is because they get 'offset' a little as mobs don't move past them unlike Securitrons and they can't move past mobs. Or maybe it's the beacons).
Cleanbots don't do this because they don't have access so they go through the hallway like law-abiding citizens.

**Comment by Mwahahahaha** [comment]
Okay so after a bit of further observation I've now noticed that Beepsky and the ED-209 seem to be alternating back and forth between the same two beacons.
They keep going to beacon A before going to beacon B before going back to beacon A again, in a constant endless repeat, resulting in them not actually covering a larger area of the main level on their patrols.

Specifically:

Beacon A (just by the aforementioned brig entrance)
![image](https://user-images.githubusercontent.com/3950115/28429121-2d37fc8a-6dae-11e7-9434-ab01044b818b.png)

Beacon B (just south of the holodeck)
![image](https://user-images.githubusercontent.com/3950115/28429167-5bc9ae0e-6dae-11e7-8fbc-5e9297f573ec.png)

Bearing in mind that by this point I had 3 bots on patrol mode:
1 Cleanbot
1 Securitron
1 ED-209

**Comment by Mwahahahaha** [comment]
Turning them on and off again seems to reset their patrol paths occasionally back to expected.

**Comment by Mwahahahaha** [comment]
So I've noted they go to beacon "S3" without going to beacon "Com", where they then go to beacon "CP1" instead of "S4". Then beacon "CC1" (aka beacon B) before going to beacon "S4" (beacon A) and then cue endless loop.

Cleanbots do this as well.
So in a sense, they go on this semi-wild tour before eventually settling with the endless loop of going back-and-forth between one corridor.
I'm going to watch what their full patrol path will be like.

**Comment by Mwahahahaha** [comment]
Note: "S3" is at the corner just 8 tiles north from "S4". "Com" is the beacon directly west of the AI holopad just outside of the bridge entrance.

![image](https://user-images.githubusercontent.com/3950115/28429937-30efe5f6-6db1-11e7-9553-76c724f67bf3.png)
Variables as it's moving from Beacon A (S4) to Beacon B (CC1).

Activated Beepsky near "CP1" (beacon at the intersection near robotics, EVA, north lift, and glass airlocks leading to engineering hallway).
Watched a path go to "CP1", then through to the brig back entrance and to "S3", then back through the brig the same way it came from back to "CP1", then back to "S3". Back and forth repeat.

**Comment by Lohikar** [comment]
@Juani2400

**Comment by Juani2400** [comment]
I revised all the paths the other day, and they were properly mapped. I will check again tomorrow, just in case I missed something. But this may not be map-related.

**Comment by Geevies** [comment]
I haven't seen this happening recently, re-open if it reoccurs.
