### ISSUE TITLE
Telecommunications Satellite and Vault Turrets

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#3122]
The turrets in the Tcomms satellite do not seem to adhere to either of the turret control panels.
Disabling them on one of the two or both panels does not disable them.
Trying to change the controls does not change their behaviour.

Furthermore, the inner turrets are not set to lethal. This is because they're still on the default behaviours.

The Vault seems to have a similar issue.

The AI core turrets are functioning just fine though.

**Comment by Mwahahahaha** [comment]
For the record, this control panel configuration represents what seems to be the default behaviour of any turrets that do not seem to be working as intended.

![image](https://user-images.githubusercontent.com/3950115/28447974-069fc0fe-6e07-11e7-82f4-ee5ad4db354a.png)

**Comment by Lohikar** [comment]
The inner telecomms turrets (ones guarding control panel for outer) are not supposed to be set to lethal - only stun.

**Comment by Mwahahahaha** [comment]
Bit of a mishap of communication on my part:
By inner turrets, I meant the ones that are located out in space that cover the glass corridor; the second set of turrets.

**Comment by OneOneThreeEight** [comment]
@skull132 Sorry for pinging but I saw this wasn't touched. You can't enter telecomms or the vault without being murdered by the autoturrets. At all.

**Comment by Arrow768** [comment]
You cant enter tcoms if you dont have access.

If you have access you can just walk through without any issues.
I enter it regularly as CE.

**Comment by Lohikar** [comment]
They're not supposed to behave like that, Exodus had them set to shoot all non-silicons.

**Comment by TheGreatJorge** [comment]
Just noting that the issue is most apparently caused by list of all areas not initializing early enough. Which causes turret terminals that are not in the same area as the turret they control to not become linked.
