### ISSUE TITLE
Aggressive caching appears to cause crashes

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#3128]
Ever since PR #3078 was merged, reports of clientside crashes have increased.

One instance of this was a medical record where a preview icon would crash a client for unknown reasons during initial viewing. Oddly enough, on the record, the character later appeared naked. (Which shouldn't really happen.)

@Lohikar your domain and input welcome.

**Comment by Lohikar** [comment]
I feel like this is an issue with conflicts in the human caching code, will look into further when I have time.

**Comment by skull132** [comment]
Appears to be ded. Closing.
