### ISSUE TITLE
Forcibly removing someone from an exosuit passenger compartment doesn't work

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#314]
There's no internal option to eject someone from a passenger compartment. An oversight maybe.
The only way to get someone out, apparently, is to forcibly extract them.

To do this, you swipe your ID on the exterior of the mech, and select Initiate Maintenance Protocol.
Then you select the Remove Passenger option that appears there, and it brings up a popup list of passengers. Select a name and hit ok.

This displays a message, "You begin opening the hatch on the passenger compartment..."

And nothing else, ever. This operation never finishes, the passenger is never ejected.

**Comment by NanakoAC** [comment]
I decided to work on this today, and fixed it http://pastebin.com/Gu18GVMe

Much talking and testing with akrilla was involved. The problem ultimately is that mecha.dm has a locally defined version of do_after, and it intercepts all calls to functions of that name. The function call there had variables designed for the global version, and was silently failing due to them being invalid.

To correct it, i've changed it to only pass the delay. It calls the local version, waits 4 seconds as designed, then successfully executes and removes the passenger

**Comment by skull132** [comment]
Fixed in #334 .
