### ISSUE TITLE
Lich wizards may use manifest ghost to murder manifests and create almost infinite amounts of skeletal minions.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#3145]
So, mild discussion should be had here. Should liches be able to do this? As amazing as it was to summon a discount army of the undead and cultify all of them for their words without having to actually kill other players, it led to a snowball effect where security was immediately overwhelmed by the sudden proxy skeletal cult minion deployment. While hilarious... security was very much caught off guard, the entire station was either slaughtered or herded into the safety of their own department lockdowns. Which did not save them given the presence of artificiers complicating this as corpses appeared due to the proxy skeletal army.

I should point to a particular feature we have where cultists are not permitted to soul-stone manifested that are dead, for obvious reasons. 

I will say as a matter of feedback, this was great and fun on my end and on the end of the cult, but this was a curbstomp, nothing more. This was okay to do maybe once just to show off how powerful antagonists of different mixed types can be when they cooperate...

But this specific combo is extremely strong. Cultist dies? Might as well skeleton + convert them. Skeleton dies? Might as well soul-stone them. (which worked from the one time I did it, another issue there.)

Personal opinion: We should probably keep watch if someone tries to repeat this, but otherwise it seemed extremely OP to pull out as a hand to be dealt to the station by the cult-necromancer-wizard. It was fun for the first time because this was never done before on the server, but I fear for whoever has to deal with this the next time around. It's very powergamey as it stands and it gives the cultists superior numbers just from observers being around, which they will be.

**Comment by Butterrobber202** [comment]
I was the one who conjured this plan in this round.

We were trapped in Xenobio with the Wiz, so I pretty much went, 'Fuck it, let's make an army.'

It _was great fun._ But I see what delta is getting at.

**Comment by Alberyk** [comment]
I already have an idea to handle this.
