### ISSUE TITLE
Misspelled Coffee

### ISSUE THREAD

**Issue by Muncorn** [Aurorastation/Aurora.3#3152]
The Cafa Ma'Lounge or whatever it's meant to be called, honestly not sure, is spelled ingame as: That's A mug of CafÃ© MÃ©lange. The name as it appears when you hover over it is different as well.

**Comment by Lohikar** [comment]
Probably an encoding issue; code files are UTF-8 and BYOND expects Windows-1252.

thanks BYOND

**Comment by MarinaGryphon** [comment]
In my client, it showed up as 'Caf Mlange' and 'Caf au Lait'. I might be able to fix this by just changing the encoding when I save the file.
