### ISSUE TITLE
Moving the AI eye around makes footstep noises

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#3156]
As the title says

**Comment by Lohikar** [comment]
...I don't see how this could be possible, footstep sounds are defined only on `/mob/living/carbon/human`.

**Comment by skull132** [comment]
This constant or a one time thing?

**Comment by Pratepresidenten** [comment]
Ill check when playing AI another time, but it was constantly happening when I moved around.

**Comment by Arrow768** [comment]
I have been playing AI quite a bit and I did not notice that

**Comment by Pratepresidenten** [comment]
Hilarious revelation. My keyboard keys sometimes makes the **exact** same noise as footsteps in spessmen. Case closed, luls had.
