### ISSUE TITLE
The bar sign obscures an air alarm.

### ISSUE THREAD

**Issue by HouseOfSynth** [Aurorastation/Aurora.3#3157]
Pretty self explanatory really.

Barsign on it's own: http://puu.sh/wTcOS/d27c36ae22.png

Barsign on right click: http://puu.sh/wTcOo/8eec098e60.png

**Comment by Juani2400** [comment]
I added the new air alarm in its new location, but seems I forgot to delete the one below. Won't change much, as the other alarm has the same functions, but will be fixed soon.
