### ISSUE TITLE
Corrupt Form spell creates duplicates.

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#3160]
The spell found in the necromancer spellbook for the wizard antagonist called Corrupt Form allows you to briefly change into a shade and utilize a couple of spells normally reserved for cultist constructs.

This is fine, except that it runs into some issues if you end up in a wall and the game cannot figure out how to move you out properly.  Rather than shunting you out of the wall, as I assume it should, it creates both a duplicate of your shade form and a non-interactive sprite of a wraith called 'water' on the same tile, while allowing you reside safely in the wall. 

https://i.gyazo.com/a280ad7b8aa4d1a7ec3e9b12f3ef322e.png

As far as I am aware, this seems to be an inconsistent issue.  It works sometimes by shunting you out of the wall, and other times it does this.  It usually seems to occur when you are deep enough inside a wall that it confuses whatever code moderates this.

**Comment by Alberyk** [comment]
It should be fixed now.
