### ISSUE TITLE
Duplicating Custom Items

### ISSUE THREAD

**Issue by Ornias** [Aurorastation/Aurora.3#3165]
**How to replicate:**
 - Add custom items (eg. deck of cards).
 - Spawn at the NTCC Odin.
 - Wait for 10 minutes to pass so you teleport to cryogenics.
 - Check inventory.

This can also fill bags above their maximum capacity.

**Comment by MarinaGryphon** [comment]
Also happens with autodrobes, primarily with loadout items.
