### ISSUE TITLE
IPC have organic damage type

### ISSUE THREAD

**Issue by NebulaFlare** [Aurorastation/Aurora.3#3168]
![a robot](https://user-images.githubusercontent.com/29672079/28666833-b33e03c8-7264-11e7-9bf2-19df120e36e0.png)

Took damage from overheating while fighting a blob - upon examination, I had 'fresh skins' injury. Repair could not be performed to remove these injuries.

Interestingly, I think I actually 'healed' overtime from the damage. I was near-crit and was brought out to stable before getting any repairs.

**Comment by MarinaGryphon** [comment]
I think that may be related to the issue of IPCs randomly acquiring organic limbs. Needs testing to see if it can be reproduced now.

**Comment by Geevies** [comment]
Believe this has been fixed.
