### ISSUE TITLE
There's a dayum wall smack in the middle of security's interrogation

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#3169]
![image](https://user-images.githubusercontent.com/19973802/28670366-6f2553f8-732c-11e7-80e3-d3f60b1d09a4.png)

This is why you do not hire a bunch of random-ass Tajarans to do station-construction with no humans sprinkled in.

**Comment by Juani2400** [comment]
Pff... Damned Tajaran. Will be fixed.
