### ISSUE TITLE
Non-functioning airlock

### ISSUE THREAD

**Issue by NebulaFlare** [Aurorastation/Aurora.3#3173]
The airlock in the picture below (below sublevel, by the engine's cold loop) are not functional. I confirmed this in a prior round.

1. Pressing the button on the wall does not activate the cycling.
2. I cannot cycle the air from the internal Airlock Controller, both for entering and exiting the station.
3. While inside the airlock, I cannot force the exterior door from the air controller panel. Only the interior can be forced open.
4. Pressure inside the airlock reads 110 kPa. regular pressure should only be 101.9 kPa.

By forcing the exterior door open (from drone controls) and releasing some of the air, the airlocks appeared to work as intended. I then shut the airlock and tried to cycle back inside. It did not complete the cycling. I forced the interior door open to re-stabilize the pressure, and it returned to 110 kPa. Airlocks ceased to function once again.
![airlocks](https://user-images.githubusercontent.com/29672079/28715584-5c41fef0-7334-11e7-9c8e-7692d1ad9a5f.png)

**Comment by SoundScopes** [comment]
Related to #3213
