### ISSUE TITLE
Cargo Overhaul - Order Application

### ISSUE THREAD

**Issue by Arrow768** [Aurorastation/Aurora.3#3177]
Various improvements to the order application

- [x] Tracking of Cargo Orders with the order id and the tracking code
- [x] List the preliminary shuttle fees on the details page
- [x] Fix the submit order button icon at the status area
- [x] Ask the user for a description / reason for the order

**Comment by deGurkin** [comment]
The orders if printed also spawn behind the Cargo Order Console

**Comment by Arrow768** [comment]
Right now the order application does not print anything.
