### ISSUE TITLE
Machine Construction Issues

### ISSUE THREAD

**Issue by mappel6** [Aurorastation/Aurora.3#3179]
Gas coolers and gas heaters will always be built facing downwards when completed. Not only does the wiki state that they can face other directions, but the gas cooler in Toxins Mixing spawns facing to the right. As of right now there is no way to have a gas machine that doesn't spawn in on round start face any direction other than downwards, as even with admin intervention to make it face a different direction, the machine will not connect with any other pipes, even if the pipes are then unfastened and replaced.

On top of this, deconstructing a machine that spawns on round start will result in the machine giving a full coil of cables instead of the amount that should be in the machine. While definitely a useful way to get more cables, it is technically also a bug.

**Comment by SoundScopes** [comment]
Take out the circuit board, use a screwdriver on it, that should allow you to change the direction of the finished coolers & heaters.
