### ISSUE TITLE
Alarm monitoring console under the AI Subsystems tab has scrollbars around camera buttons

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#3182]
Here's what the AI subsystems alarm monitor looks like when there's an alarm: 
![aeef](https://user-images.githubusercontent.com/11140088/28755969-99f377be-751a-11e7-8d25-d1aa1cf6fba5.PNG)

Here's what the console alarm monitor looks like: 
![356](https://user-images.githubusercontent.com/11140088/28755971-a422ed82-751a-11e7-984c-7cee93790087.PNG)

Note that in the first example, the scrollbars would not let me scroll up or down, limiting me to only using the first two camera buttons on any alarm.

**Comment by Alberyk** [comment]
That is due to resources of other server, mostly likely baystation.
