### ISSUE TITLE
Dropping grab in crate.

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#319]
https://gyazo.com/852aa3a2105029a5135e21761d196336

This is what happened when I tried to stuff a mouse into a crate.

**Comment by Akrilla** [comment]
What's happening?

**Comment by NanakoAC** [comment]
'Grab' seems to be implemented as an item you hold, with attack effects based on clicking on stuff.

It seems one isn't properly defined for crates, and it goes to the default, which is putting whatever you're holding into the crate. which is the 'grab'

**Comment by skull132** [comment]
@NanakoAC that's a negative. Bad way.

Check if the grab item deletes shortly after being placed in the crate. If it does, then the report is invalid and everything works as intended. If not, then it warrants further review.
