### ISSUE TITLE
Bridge corridor camera is shown twice in the security cameras list.

### ISSUE THREAD

**Issue by Hugo14453** [Aurorastation/Aurora.3#3204]
![image](https://user-images.githubusercontent.com/9057997/28822281-9bfd7f4a-76b0-11e7-87da-44a1a91fa411.png)

**Comment by Alberyk** [comment]
It seems fine in the live server;
![camerabridge](https://user-images.githubusercontent.com/11579997/28975861-0708f90a-7912-11e7-8c74-dc3ba80b8bc7.png)

**Comment by Hugo14453** [comment]
Huh, that's odd, this was on the live server... Maybe someone broke it IC somehow

**Comment by Juani2400** [comment]
Seems okay.
