### ISSUE TITLE
gas masks and infections

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#3205]
Being supplied from an oxygen tank via gas mask do not protect you from being infected by an air-spreading (muscus) disease. Did not step at muscus at all. And, i suppose, muscus can infect through footwear too

**Comment by SoundScopes** [comment]
What was the type of disease? Mucus can spread through contact if the disease type is also contact.
There are checks in place for if you are being supplied air from internals and immediately returns

**Comment by HetNeSS** [comment]
No idea what disease it was.

**Comment by SoundScopes** [comment]
From what you have said and from what I have looked at in code, there must have been another reason for you to be infected.
Gloves give a little protection against on contact diseases but won't negate it completely.
If you had a mask on and are running on internals there is no way you could be infected through airborne diseases.

I'll do some testing and reply with what I find.

**Comment by HetNeSS** [comment]
![dreamseeker 2017-08-01 23-26-15-214](https://user-images.githubusercontent.com/18286472/28849669-8e88c014-7731-11e7-83b5-e77e283a2619.png)
All I can help you is this

**Comment by SoundScopes** [comment]
After much looking and reading I'm lead to believe that the virus was a "contact" type.

When a new virus is made the infection type has a 70% chance of being Airborne and a 30% chance of being Contact.
The symptoms are also random and have no relation on the infection type.
Contact viruses can be passed just by being touched by someone with the virus, that includes bumping into someone

**Comment by HetNeSS** [comment]
Did not bumped into someone either. Just walked through hallway from engineering to meadbay, after them, the sympthom messages did start to pop up on the screen

**Comment by SonicGotNuked** [comment]
Gas masks do not block contact, hardsuits and bio suits will.
