### ISSUE TITLE
Maps manipulation

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#3209]
How to change a map which is being runned on local server? Like, I want to change map from "aurora" to custom one, how to do that?

**Comment by SoundScopes** [comment]
Uncheck the maps in dream maker to stop them being compiled and check the maps you do want.
Example to change over to the Exodus map the browser would look like this http://puu.sh/wZhHL/9c452fef9a.png bear in mind that some editing might be required as the code was heavily modified for the Aurora map.
That shouldn't affect new maps made using the current code

**Comment by HetNeSS** [comment]
Thanks
