### ISSUE TITLE
Tiles made wet by spills never dry up

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#321]
If a tile is made wet by a large water spill, it becomes slippery, and stays that way forever.
This may also apply to lube and corn oil, which also create slippery tiles.
Slipping created by recent mopping doesn't have this bug, it dries up after a while

The code that governs the drying up, uses spawn, and has an odd comment: 
spawn(800) // This is terrible and needs to be changed when possible.

Possibly a redesign is expected here.
the purpose of checking the tile's wet level is unclear, as all forms of slipping seem to be set to make the tile slippery for the same duration.

**Comment by ArcBotSS13** [comment]
I think it's only beakers that currently make infinite water tiles, could you provide some other objects that do this?

**Comment by NanakoAC** [comment]
You're correct, only splashing beakers onto the floor causes it. But the bug occurs with a beaker containing either water, space lube, or corn oil. Splashing any of them out from a beaker creates a permanant wet patch that never dries.

Spraying these substances on the floor creates a temporary slippy patch which dries up correctly

**Comment by Akrilla** [comment]
I got this bug myself when I poured out a beaker of a random solution next to me, I think it's just anything in a beaker.
