### ISSUE TITLE
The AI core airlock vents air.

### ISSUE THREAD

**Issue by Hugo14453** [Aurorastation/Aurora.3#3213]
There is an airlock to enter and exit the AI Core.
When exiting the AI core the airlock is vented and air is removed despite there being a normal atmosphere on both sides of the airlock.

![image](https://user-images.githubusercontent.com/9057997/28895846-f12b3b0c-77d1-11e7-96dd-8da5fc0e7a37.png)

**Comment by SoundScopes** [comment]
Most airlocks are missing sensors on the exterior doors, this is a bug with most airlocks.
There needs to be a sensor on the outside of both doors and one inside the airlock or the airlock will always assume the interior has pressure and the exterior doesn't, even if they do/don't
