### ISSUE TITLE
Staff of Change is Broken.

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#3216]
The staff of change seems to be broken. All it does it make you various humans, a slime, or a robot. You can become a Diona but you're still just a human with diona abilities avalible.

**Comment by Alberyk** [comment]
Not related to the staff of change, since, if you are a dionae and have your species changed, the power remains for whatever reason it is.

**Comment by DronzTheWolf** [comment]
The reason I am calling it broken is that is simply randomized a human instead of changing to a new species/creature, other than station cyborg and slime.

**Comment by Bygonehero** [comment]
Can confirm that the staff is broken.
