### ISSUE TITLE
Unable to create artificial bluespace crystals.

### ISSUE THREAD

**Issue by MarinaGryphon** [Aurorastation/Aurora.3#3218]
Despite having the necessary tech levels, artificial bluespace crystals can't be made in Research. I recall that you used to be able to make them, and since they're artificial, one would expect to be able to make it.

It lacks a recipe datum, so. 😕

**Comment by Alberyk** [comment]
Just steal it from the station's safe.

**Comment by MarinaGryphon** [comment]
They should be able to be made, though, and not require theft.

**Comment by printer16** [comment]
They should be able to be made and not just stolen. They aren't high value enough to warrant requiring  theft from the safe + relying on RNG for it to the in the safe.
