### ISSUE TITLE
Phoron, not Plasma

### ISSUE THREAD

**Issue by NebulaFlare** [Aurorastation/Aurora.3#3233]
A poster still refers to the orange substance as Plasma. See attached.
![phoron](https://user-images.githubusercontent.com/29672079/28994954-98e7f438-7977-11e7-8567-7213de8e9c96.png)

**Comment by Alberyk** [comment]
Plasma is still a valid alternative name for phoron.

**Comment by printer16** [comment]
Not a bug.
