### ISSUE TITLE
Paper planes work in space.

### ISSUE THREAD

**Issue by Hugo14453** [Aurorastation/Aurora.3#3240]
I'm no expert, but I don't think they should work like they do when in a vacuum... but i'm not sure exactly what it is they _should do_...
![image](https://user-images.githubusercontent.com/9057997/28998308-6d081110-7a1f-11e7-8f07-245ee50efbf7.png)

**Comment by verywhiterabit** [comment]
Considering there's no wind resistance it should still be throwable, it just wouldn't be able to glide on the air. It's like throwing a rock, no distance gained from being aerodynamic or anything.

**Comment by Hugo14453** [comment]
If I threw it straight would it ever land?

**Comment by Hugo14453** [comment]
I've sent a request to NASA for an explanation, hoping they get back to me soon.

**Comment by Pacmandevil** [comment]
I don't really think this is a bug, though.

**Comment by Lohikar** [comment]
Not a bug.

**Comment by Hugo14453** [comment]
OK we have our first reply, from ANGKASA:

Greetings,

 

Dear Sir/ Madam,

 

Gravity on the surface of the earth is equal to 9.8 m/s2.

Gravity of the moon on the lunar surface is only 1.63 m/s2.

Every person is falling towards the Earth at an accelerating rate of 9.8 meters/second². Gravity basically depends on mass. The amount of gravity reduces gradually with the reduction in distance. As a result, the force of gravity that one feels on the surface of Earth, is much different from what one would experience at the distance of the Moon, or at a distance further from it. Gravity on the Moon is much less. The moon is smaller and has much less mass which it pulls with less gravity. Actually, if one could stand on the plane of the Moon, he/she would experience only 17%  force of gravity that one would experience on Earth. In order to helps you understand better, please refer to this link https://www.youtube.com/watch?v=5T1aenrWgZ0​ .

 

Thank You.


Unit Komunikasi Korporat

Agensi Angkasa Negara.

**Comment by chaoko99** [comment]
So basically it'd be like throwing it in a vacuum but just a little further.
