### ISSUE TITLE
Cloning bug

### ISSUE THREAD

**Issue by deGurkin** [Aurorastation/Aurora.3#3242]
I've been playing a character with a robotic arm,that's problably half the stations population at any given point,it was a Zeng-Hu pharmaceuticals right arm.
after beeing cloned I was of course without the arm,when trying to put on a backpack with my right arm it would instead drop the backpack
this was reproducable multiple times
I did not test it with other arm specific interactions as the round ended shortly after in a crisis

**Comment by LadyFowls** [comment]
The cloning pod wont clone robotics limbs
