### ISSUE TITLE
Cyborgs have 'jetpack' listed in parts, don't actually have it.

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#3268]
When performing a self-diagnostic as a cyborg, one of the parts listed is a 'jetpack.' However, it is not a component you can toggle, or a tool in the borg inventory, and apparently cannot be used in any way. Either the jetpack needs to be made actually functional, or the 'extra' part needs to be removed from the self-diagnostic list.
![image](https://user-images.githubusercontent.com/22651198/29181912-80c6cf7e-7dc2-11e7-9c63-aec978a3db20.png)

**Comment by Pacmandevil** [comment]
I think that's there for the jetpack upgrade: It's can't be damaged or anything untill you have one.

Not sure if this is an easy fix, as the Jetpack IIRC is just a part like armor, just that borgs don't spawn with it.

**Comment by Sindorman** [comment]
Yeah, not a bug
