### ISSUE TITLE
Odin camera coverage.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#3277]
There is a conflicting issue near the Odin arrivals shuttle. There is an AI holopad present, yet when you are pinged to it, you do not have the camera coverage to activate the holopad.

A fix would be to either install a camera to allow visual of the holopad (Would be nice for people to ping the AI to get a status on the shuttle), or simply to kill the functionality (Or remove) the holopad itself.

**Comment by SoundScopes** [comment]
The Station's AI shouldn't be able to reach the CC level so removing the functionality or holopad is probably best
