### ISSUE TITLE
Duplicate Starting Items

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#3286]
I don't know _**EXACTLY**_ how this happened, but I do vaguely recall what I did before it for reproduction. In my general loadout, I selected a medical tajara coat and then spawned in. On my way down to the shuttle, I took off my hoodie and put the jacket on instead, because it was in my satchel. Later on in the round, I checked my personal collection box and found _gasp_ another medical jacket.

**Comment by SoundScopes** [comment]
Duplicate of #3165
