### ISSUE TITLE
Skin tone issue in character creation. 

### ISSUE THREAD

**Issue by ejundersc0re** [Aurorastation/Aurora.3#3303]
Character preview in character creation has very fair skintone (listed as -84 on the web client when I checked), even when saved as 119. 119 skin tone will remain white in preview even when changed, though appears fine ingame. This works without fail every round for me, and persists even if saving at a different value (I generally swap between 118 and 119).

**Comment by Lohikar** [comment]
Probably related to the character preview showing all characters as male - the organs are not properly being synced when something that affects them is changed.

**Comment by LadyFowls** [comment]
Cant replicate this
