### ISSUE TITLE
Double load out / missing items when being forced spawned.

### ISSUE THREAD

**Issue by Karolis2011** [Aurorastation/Aurora.3#3304]
So, when I got forced spawned at cryo, I got double load out (Two pAis, two boxes, etc.) and didn't get by work suit and coat (Medical suit, science). 
To try to reproduce: 
* Get power down at station
* Spawn at Odin
* Wait 10 minutes to get forced out of Odin and spawn at Cryo.

**Comment by SoundScopes** [comment]
Duplicate of #3165
