### ISSUE TITLE
Mapping issue: EFTPOSes are nowhere to be found in locations that need them.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#3308]
The brig badly needs one.

The HoP badly needs one.

The bar badly needs one.

Not sure if the kitchen has one.

**Comment by Juani2400** [comment]
Except the Brig, which is the one that may need it the most, all of those locations already had a scanner. I've added a few more EFTPOS around the station for the next update, anyways.
