### ISSUE TITLE
Seismic Charges arm but never detonate when placed on sand 

### ISSUE THREAD

**Issue by Synnono** [Aurorastation/Aurora.3#3319]
/obj/item/weapon/plastique/seismic from the mining vendor will allow you to set a timer like C4 and will give you messaging that the bomb is armed when you plant it on the wall or on the ground, but if placed on the asteroid sand outside it will never detonate. A mining charge should probably be able to blow up there.

Can replicate this 100% of the time on my test server which is running a fairly recent version of Master. Would recommend either allowing the charge to explode or giving the player some sort of failure check/messaging when they try to plant on sand.

**Comment by Synnono** [comment]
Update on this, I had fine finally blow up after setting several. Not sure what's failing.

**Comment by Geevies** [comment]
seismic charges can't be placed on sand anymore, dunno when that got tweaked, fixes this issue tho
