### ISSUE TITLE
Invisible Masks if Wearing Security Helmet

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#3326]
If you put something on your face while wearing a security helmet, it won't be visible.

You have to wear the helmet after you put on the mask for it to be visible. 
![](https://i.gyazo.com/4c86f084e5ba72004a4df95a01c6e259.png)

**Comment by Alberyk** [comment]
I think it is related to nanako's last change to icons generation.

**Comment by Fortport** [comment]
Hmmh. Well, I've noticed it for a long time. Months. It has never been fixed, so I figured it hasn't been noticed.

**Comment by Lohikar** [comment]
Odd that this survived my icon refactors, I'll look into this.
