### ISSUE TITLE
Flour outbirsts during scrubbers backpressure surge

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#3340]
Flour do penetrate windows during scrubbers backpressure surge. Is this a feature or a bug?
![default](https://user-images.githubusercontent.com/18286472/29638780-c69d6cf6-8871-11e7-9791-eac2ad44cf86.png)

**Comment by chaoko99** [comment]
Can't reproduce thus far. But also holy what.
