### ISSUE TITLE
Glass stacking is fukt

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#3344]
Any amount of glass sheets you eject from the mining stacking machine turns into a stack of zero as far as I can tell.

**Comment by KepQwet** [comment]
Think it's related to #2999 
I have no idea whether it's _actually_ cyborg glass, but whatever's coming out isn't right. Might want @LordFowl to look into it, as LF was the one who engineered newmining.

**Comment by Lohikar** [comment]
LF is no longer a developer, someone else will have to do it.

**Comment by Pratepresidenten** [comment]
The glass that pops out is cyborg glass, yes. This needs to be fixed.

**Comment by alexpkeaton** [comment]
Pinging @Arrow768 

This issue is still present and presents a significant issue as research and robotics are both regular glass users.
