### ISSUE TITLE
Engine room is missing its ventilatory control button.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#3345]
Kind of a key thing to be missing.

**Comment by SonicGotNuked** [comment]
The CE office has it, just break into it.

**Comment by Pratepresidenten** [comment]
The lack of a vent control in the engine room is an oversight afaik. When the engine is critical, or there is a breach in the core chamber, there is no time to dick around by running across the entirety of engineering to get the hatch open for repairs/venting.

**Comment by Juani2400** [comment]
I'll mark this as an issue, but it is probably intentional. I will add a ventilatory control inside,  but I'm not really a fan of it. I will probably just place it behind a glass.
