### ISSUE TITLE
Telescopic batons weaken cyborgs

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#3349]
Aiming at the leg area with a telebaton and striking a cyborg (despite having no particular body parts to aim at on a borg) will weaken it, causing a similar stun state as what happens when you stun a cyborg with a flash.

my bad

**Comment by Pacmandevil** [comment]
the telebaton obviously just crippled the Borg's nonexistent legs.

**Comment by Alberyk** [comment]
Fixed.
