### ISSUE TITLE
Cyborg Beakers are hugely buggy

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#335]
Certain cyborgs have a beaker in their equipment which allows them to do chemistry.

This beaker can be placed into any machine that normally takes one, though this is allowed even if the cyborg isn't holding it. The beaker can exist in an infinite number of places at once, though they all reference the same object.

If ejected from a machine, the cyborg cannot pick up the beaker, and if someone else picks it up, they break.

I intend to fix this by adding a Chemistry Gripper that holds beakers, and replacing beakers on cyborgs with it

**Comment by skull132** [comment]
Fixed in #338
