### ISSUE TITLE
Cryo Tubes Put IPCs to Sleep

### ISSUE THREAD

**Issue by NoahKirchner** [Aurorastation/Aurora.3#3352]
If you are put in a cryo tube (In medical) as an IPC, you are rendered unconscious despite not being organic.

**Comment by SoundScopes** [comment]
I'd argue that this isn't a bug. If you lower a CPU below a specific temperature it will hang (in computer terms) and won't start running or boot up until the temperature has risen.

I can't give exact values since I lost the video where it was demonstrated.
