### ISSUE TITLE
IPC, atm tech, Odin

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#3372]
IPC atmos techs do start via odin spawnpoint with all of their gear in place, and passing through an auto-drobe just duplicates all the items, including PDA and ID card
![default](https://user-images.githubusercontent.com/18286472/29803466-772e5176-8c95-11e7-8545-59b4c8eb436c.png)

**Comment by SoundScopes** [comment]
Most likely related to #3165
