### ISSUE TITLE
pAI can't control ERT members rigs

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#3382]
Swiping the ERT ID over the pAI yields a non-matching DNA message and when you try to enable data-spike on the rig, it spits the pAI out.

Unsure if this applies to other rigs with other access requirements.

**Comment by Butterrobber202** [comment]
For a PAI to work with a RIG, you must imprint Master DNA, Swipe your ID, then enable AI Control.

**Comment by Moltenkore** [comment]
Yes as I said, it seems that ERT are unable to swipe pAI after imprinting their DNA due to a non-matching DNA message.

**Comment by printer16** [comment]
pAI was able to control just fine last round. Just imprint master DNA, place into suit, and activate AI control. Place into suit by directly clicking on the suit with the pAI in hand. Closing issue.
