### ISSUE TITLE
Holy water and jaunting 

### ISSUE THREAD

**Issue by printer16** [Aurorastation/Aurora.3#3386]
Holy water sprayed on the floor is supposed to stop a wizard from jaunting and teleporting away, presently it just gives the wizard the MESSAGE that they cannot trespass over this area, but the blocker to actually stop them isn't working

Reported by XanderDox

**Comment by Butterrobber202** [comment]
yeah, but. why would a wizwoz care about holy water? He is a magic man, not a wristing cutting sinner.

**Comment by Pacmandevil** [comment]
something something witchcraft

**Comment by XanderDox** [comment]
I am reviving this because it is still true. Plz fix, or confirm that this will not be a thing anymore.
