### ISSUE TITLE
Camera Naming Bug

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#3391]
At round-start, the camera title for the Security forensics lab is typoed.
![image](https://user-images.githubusercontent.com/22651198/30000853-1d61a932-9040-11e7-830b-65428b8e6b03.png)

**Comment by Juani2400** [comment]
It is also an office. Don't see an issue here.

**Comment by Lohikar** [comment]
The apostrophe here is not valid grammar. It should be `Forensics Office`.

**Comment by Juani2400** [comment]
And I didn't notice. Great. Will be fixed.
