### ISSUE TITLE
Maintenance drones cannot pull disposal pipes.

### ISSUE THREAD

**Issue by MarinaGryphon** [Aurorastation/Aurora.3#3394]
While I understand wanting to avoid power creep, they were able to before, and as most engineers don't bother to repair busted disposal pipes I don't think it's much of an issue. This is just a side effect of not allowing them to pull or push large objects, and one that doesn't make much sense.

**Comment by Sindorman** [comment]
They are small and pipes are big, they shouldn't be able to

**Comment by Geevies** [comment]
Fixed.
