### ISSUE TITLE
Shell Frame's Heat Warning Text Doesn't Show Up

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#3397]
heat_discomfort_strings = list(
        "Your CPU temperature probes warn you that you are approaching critical heat levels!",
        "Your synthetic flesh crawls in the heat, swelling into a disgusting morass of plastic."

Never seen this ever show up, even did some testing on a private server and overheated myself for a few minutes and got nothing.

**Comment by NonQueueingMatt** [comment]
Should be fixed now
