### ISSUE TITLE
Mechanical Security Records

### ISSUE THREAD

**Issue by Moonyman** [Aurorastation/Aurora.3#3400]
So, the issue is, mechanical sec records, that can be found in forensics office in the filling cabinet are not working properly. Using the cabinet gives you a menu with a single option "Sheet of paper". Every sheet you pull is a record of a crewmember that is alphabetically the first. I have no time to actually check if it was a one-round issue or if it was consistent. Tomorrow when i'll have time for one more shift and i'll be right back with an update. For now, to be safe, here's the round, where the bug occured: bQj-cAwJ

**Comment by LifesDisciple** [comment]
Neeevermind. It was a one-round issue it seems. Still worth taking a look at as i suspect the disappearence of physical sec records might be somehow connected with the wipe of the digital sec records (which shouldn't be happening)
