### ISSUE TITLE
Camera <-> Ghost desync (Observe inactive AI eye bug)

### ISSUE THREAD

**Issue by moonheart08** [Aurorastation/Aurora.3#3407]
Expected:
Watch a inactive AI eye
Result:
Camera desynced from ghost after observing inactive AI eye.

EDIT: I somehow got my camera stuck in Null (empty Z level with no tiles). Cant reproduce, but just so its there.

**Comment by moonheart08** [comment]
Im a moron. This is intentional. 
Closing.

**Comment by moonheart08** [comment]
Or not. I cant unobserve.

**Comment by moonheart08** [comment]
If this is all intended, i need slapped.

**Comment by Butterrobber202** [comment]
there is a way to de-sync your camera from your character, but I have no idea how to do it. Generally you want to use the 'Follow' Command, then re-observe your own character. Observe =/= Follow

**Comment by SoundScopes** [comment]
There is a command in the OOC tab called "Cancel-Camera-View" that should reset your "eye" to your current Mob.
