### ISSUE TITLE
Sprite error - Chief Engineer RIG has no lights from back view

### ISSUE THREAD

**Issue by cl234** [Aurorastation/Aurora.3#3415]
[Facing left](https://puu.sh/xuwUO/6f4af4a1a5.png)
[Facing right](https://puu.sh/xuwU2/f7fcca56ee.png)
[Back view with no blue light sprite](https://puu.sh/xuwUv/a1d4f06747.png)

**Comment by Juani2400** [comment]
I don't think those are lights. I think those are intended to be the thrusters. And, those are on the sides of the back, not directly on the back. Think of it like a turtle's caparace with thrusters on the sides. They would be visible from the back.

**Comment by cl234** [comment]
Ahh, that makes sense actually. I was always picturing them similar to the Dead Space RIGs.
