### ISSUE TITLE
People in wheelchairs slip on water. Help needed!

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#342]
People on chairs, or in wheelchairs, slip when they move over wet floor tiles. This shouldn't be happening because the slipping code checks if the mob is buckled

The relevant code is in:
/game/turfs.dm line 84
and
/modules/mob/living/carbon.dm line 446 (the slip function)

In both of these places, it checks if the mob is buckled. But this check always returns null. I've confirmed with variable viewer that the mob is buckled immediately before and after the slip happens, the buckled variable is populated with an object. But these files seem unable to read it.

Possibly, something is unbuckling and then re-buckling the mob quickly. I can't find it, requesting a consult.

**Comment by OneOneThreeEight** [comment]
Why not just add a NO_SLIP modifier when you're buckled to a wheelchair? And then it's removed once you're unbuckled. Etc.

**Comment by Bedshaped** [comment]
Was this fixed? Reopen if not
