### ISSUE TITLE
Girder sprites don't appear on sand

### ISSUE THREAD

**Issue by cl234** [Aurorastation/Aurora.3#3425]
[The tile I threw a plasteel sheet on has a girder on it](https://puu.sh/xwdoG/ff17699e43.jpg)

I've noticed this happens on all sand tiles as well, as far as I can tell.

**Comment by MarinaGryphon** [comment]
I've seen this before, might be a layering issue. Should be an easy fix.

**Comment by Lohikar** [comment]
Issue is likely from the fact that sand turfs are slightly above other turfs, I believe they draw at `TURF_LAYER + 0.1`.

**Comment by Fire-and-Glory** [comment]
#2756 pls fix sand

**Comment by chaoko99** [comment]
Resolved..? I see that girders work, at least.

**Comment by MarinaGryphon** [comment]
Issue was resolved along with #2756. Closing.

**Comment by Lohikar** [comment]
Fix not merged into master.
