### ISSUE TITLE
Dragging buckled people into machines bugs out

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#344]
http://i.imgur.com/XYxBcpL.png

Dr Eliza is in the cryopod, on the rollerbed, in both sleepers, and in the scanner simultaneously.
Dragging and dropping buckled people onto machines without unbuckling them, causes them to teleport back to the bed whenever it is moved.

**Comment by skull132** [comment]
Fixed in #345 .
