### ISSUE TITLE
Sec consoles emit the wrong color of light

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#3446]
![2017-09-13_19-21-10](https://user-images.githubusercontent.com/7097800/30406664-dd6b4d0c-98b8-11e7-8033-9fea27c20613.png)

Orange consoles should probably emit orange light.

**Comment by Juani2400** [comment]
#3448 @Lohikar

**Comment by Lohikar** [comment]
Whoops.
