### ISSUE TITLE
Obsessive ammounts of Plasteel walls in general

### ISSUE THREAD

**Issue by Pacmandevil** [Aurorastation/Aurora.3#3476]
holy hell the entire science/engineering sublevel is like 90% rwalls

These should probably only be used for the _high security_ areas, like the vault, armory, etc.

**Comment by Juani2400** [comment]
Rwalls for exterior walls in the sublevel was a design decision by the lead mapper, simulating the structure that basically holds the stations in place. I will, however, revise the interior walls soonish. The exterior ones will remain reinforced.
