### ISSUE TITLE
Virus Sample is shattering

### ISSUE THREAD

**Issue by MorrisLmao** [Aurorastation/Aurora.3#3487]
So I'm here playing the virologist right? I put some samples into the disease analyzer, it spits them back out with the report and the sample. I pick up the report, read it, pick up the sample and it shatters.

Okay that's kinda weird, I do it with a different one, same thing happens. As soon as I clicked to pick them up, the sample shatters.

The round ID is bWx-aftL.

**Comment by MorrisLmao** [comment]
Something new I've just noticed, it's acting as if I have an item in my right hand for all of this. I'm not sure if the item is invisible or my hand is just glitched.

**Comment by MorrisLmao** [comment]
Mkay so as it turns out, there was an invisible piece of paper in my right hand that was shattering all of my samples. Thanks byond.

**Comment by skull132** [comment]
Invisible paper it is.
