### ISSUE TITLE
Numerous Diona Issues in need of fixing

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#349]
In continuation of a previous issue report I made (which I have now closed to replace with this one) there are a number of issues with diona right now. I'll list the ones I've seen so far succinctly.

1) When diona nymphs become full diona, it assigns them a random name from the human naming list, and when they split apart, they are given a generic diona (XXX) name. Perhaps give them an option to pick a name like borgs/certain antags do?  

2) The merge with gestalt/split from gestalt command does not function properly right now.  In one particular case, a full diona forcibly merged with the nymph I was playing, and I was stuck with the 'merge with gestalt' command.  Then, after that diona split to release me and the other nymphs in the gestalt, it changed to 'split from gestalt', before vanishing as an option forever, rendering my nymph unable to merge period.  It's all very buggy.

3) I'm not entirely certain that nymphs are affected by darkness.  I've spent roughly 5-7 minutes being accidentally locked in a room that was completely lightless, with no ill effects.  It is potentially possible that I'd have to wait longer to start wilting, but if lack of light takes that long to actually adversely affect diona, what is the point of the mechanic at all?

**Comment by NanakoAC** [comment]
Assign this issue to me please, i'm working on diona and will fix all of these in the process

**Comment by NanakoAC** [comment]
these are all fixed in #442

**Comment by NanakoAC** [comment]
this was never closed when these issues were fixed, closing now
