### ISSUE TITLE
Service Borg bucket filling issue.

### ISSUE THREAD

**Issue by ForgottenTraveller** [Aurorastation/Aurora.3#3495]
Service borgs can only fill their buckets from water tanks and not sinks, which quickly depletes water tanks.

You get the fill option but it just does nothing.
Grabbing buckets with the service grabber does not work as a loophole either.

Combined with farmbots not refilling sometimes in ponics, water is a massive issue for gardener borgs.

**Comment by Urthrem** [comment]
This issue is still present in the game, please try to fix it.
