### ISSUE TITLE
Applying nanopaste on IPCs gives the wrong message

### ISSUE THREAD

**Issue by NonQueueingMatt** [Aurorastation/Aurora.3#3498]
"IPC applies some nanite paste at 	 heHephaestus Integrated Limb right foot with the nanopaste."

It should be:

"IPC applies some nanite paste at the Hephaestus Integrated Limb right foot with the nanopaste."

Again, just a typo. To reproduce, apply nanopaste on an IPC.

**Comment by osiato** [comment]
Confirmed, fix here https://github.com/Aurorastation/Aurora.3/pull/3504

Not sure what else to put here. Was just a couple of typos.
