### ISSUE TITLE
Jetpack causing no momentum in space, even after loosing jetpack.

### ISSUE THREAD

**Issue by vx10000222** [Aurorastation/Aurora.3#3518]
Round ID: bQC-dEbH
During this round there was a trip which spaced a character of mine, the character had a jetpack which was turned on AFTER going into the Space Z-Level (Forgot to turn it on at the astaroid), i could not move up or down with the jetpack in the correct slot with it turned on with stabilisers and could not move in any direction.

After accidentally loosing my Jetpack (Was trying to throw items and accidentally threw the pack when it was in my hand) i tried to throw items to gain momentum and, even though the jetpack was no longer there they could only move 1 tile per item as if they were still being stabilised and there in died soon after, I ghosted to find out if my body was moving at all and it was not making any movements.

Don't know if it was an issue with the item or the Z-level or just the way i turned the jetpack on first but its best to put it up here and i don't intend to re-create it because that will just be a suicide.

**Comment by skull132** [comment]
Unable to replicate this. Jetpack works fine, it just needs to have air and be on your back (or suit storage on certain suits).
