### ISSUE TITLE
A sudden rush of air knocks you over!... In vacuum. On the asteroid.

### ISSUE THREAD

**Issue by chaoko99** [Aurorastation/Aurora.3#3541]
Every now and again, you get air moving around in the asteroid. In a vaccum. At sub 10kpa. Knocking you over. This is outstandingly annoying... It should neither hold and atmosphere nor push you around!

Server revision: delayed-reaction - 2017-09-24
b5ac9b0b1bde2741883bb28f03eac6b02802c37b

**Comment by skull132** [comment]
Let's play a game of whether or not this has been posted or not.

It's not a bug. It's an oversight. Mining away space on the asteroid generates pockets of air which then disperse and clear into space.

**Comment by Pacmandevil** [comment]
I'm not sure if it's intended behavior though, surely mining in a vacuum wouldn't generate air, as any air would be displaced by rock?

**Comment by Lohikar** [comment]
It's not intended behavior, but it's not a bug either as ZAS is technically behaving as it should.

**Comment by chaoko99** [comment]
Nitpicking.

How do we *fix* it?

**Comment by Lohikar** [comment]
The easiest way might be to simply not knock over mobs if the zone is larger than a (fairly large) threshold, however, I suspect this might lead to strange behavior regarding forcing airlocks.

**Comment by chaoko99** [comment]
I'd happily trade strangeness if I'm losing stupidity.

**Comment by Alberyk** [comment]
This is fixed.
