### ISSUE TITLE
Cyborgs guns stop recharging out of nowhere

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#3550]
It seems that cyborg mounted guns, like the combat modules lasers and the syndicate cyborg smg, stops recharging out of nowhere. Might be related with timers.

**Comment by Lohikar** [comment]
Yeah, this is probably timers, gun recharge of all types is timer-based. Firing the gun or proc-calling `try_recharge` should work for jumpstarting it via. bus until this is fixed.
