### ISSUE TITLE
Hacked APC sprites do not update if hacked when not in view of a player.

### ISSUE THREAD

**Issue by Cairo283** [Aurorastation/Aurora.3#3554]
It seems that, when hacking an APC as a malf AI, the blue screen of death sprite doesn't get applied to the APC when the hack is finished, instead it stays as a normal blue charging screen if it is still charging, or to a normal fully-charged green screen if fully charged.

Best I can tell, this is due to a player's camera view not being within a certain about of tiles of the APC when it finishes hacking, so it remains unloaded, and un-updated. I managed to test this theory by hacking the armory APC, which had a lot of people nearby at all times, and an APC in maintenance, which had no one near it. The APC in the armory updated to the hacked sprite correctly, and the one in maintenance remained normal.

**Comment by printer16** [comment]
The chance of an APC blue screening when hacked is not 100 percent.
