### ISSUE TITLE
Nanopaste bypasses IPC self-repair restrictions

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#3566]
Not sure if this is a bug or not, but it should be given some consideration.

**Comment by OneOneThreeEight** [comment]
Nano-machines, son. Nanites have minds of their own. Unlike welding fuel, though, they're expensive to reproduce from R&D, they are quite costly per nanopaste can.

**Comment by CakeIsOssim** [comment]
Not really self-repair. The IPC is engaging other machines to repair it, and the nanomachines won't make modifications to the IPC, only fix it. Whereas an IPC could modify itself.

**Comment by Pratepresidenten** [comment]
Alb commented that this is infact intentional.
