### ISSUE TITLE
Gravity Generator Should Emit Light

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#3583]
The gravity generator should probably emit light when on (and maybe a little while charging).
Looks a bit strange with the lights off:
![2017-10-04_11-14-22](https://user-images.githubusercontent.com/7097800/31187242-ef05e13c-a8f6-11e7-95f2-1a6879914679.png)

Here's `LIGHT_COLOR_CYAN` with range `4`:
![2017-10-04_11-15-16](https://user-images.githubusercontent.com/7097800/31187272-011f4980-a8f7-11e7-94c1-5f21ca42fc32.png)

**Comment by chaoko99** [comment]
Will handle in like an hour or two.
