### ISSUE TITLE
MindSwap Wizard Spell

### ISSUE THREAD

**Issue by Biolock1** [Aurorastation/Aurora.3#3592]
On every other server I've ever played on. When playing the role of the wizard, should you choose to select the situational tool, MindSwap (Allowing you and a fellow to be forcibly changed Ckeys), you will be able to play as that character for as long as you like until you are ready to return to your own body (And only your own body, it's not like meme where you just jump between bodies). However, the way it currently works on Aurora is you will swap bodies, and that's it. You've now swapped bodies, you have lost all your powers, and you're now just a different Ckey. The power has extremely limited utility as it is on other servers. On Aurora it is a ridiculous choice because why would you ever willingly give up your wizard powers? Some might say, "Oh well if you're about to die you can use it", but the thing is, even if that WAS the case, most people would rather die than just become a crewmate, and on top of that, it knocks you out for like 30 seconds so it's not exactly a viable combat tactic anyway. The most game breaking part of the bug is that players coming from other servers who have never played as a wizard on aurora (such as myself) will mistakenly use the butchered spell and totally blow their round causing them to go create a github and report the problem. There's no way this is an intended feature, it makes no sense.

**Comment by NonQueueingMatt** [comment]
Mindswap is already getting removed, though.

**Comment by Arrow768** [comment]
Mindswap will be removed in a upcoming pr #3565
