### ISSUE TITLE
Shell frames have red eyes and mouths by default.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#3603]
Tried changing it in the character setup, tried reloading the slot, even tried changing it ingame. Seems to be stuck at a hard red color for all shells.

**Comment by verywhiterabit** [comment]
Red eyes are trash, if we're forcing eye color again at least do the old blue.

**Comment by Lohikar** [comment]
We're not forcing eye color, this is a bug.

**Comment by MarinaGryphon** [comment]
Can't reproduce on development branch. Possibly fixed.
