### ISSUE TITLE
Wizzard transformation bug. ((can see AOOC))

### ISSUE THREAD

**Issue by SebkillerDK** [Aurorastation/Aurora.3#3607]
Right, so i was transformed by a wizzard in a conflux round. (id is bQQ-dhHm). and shortly afther that, i noticed that i was able to see AOOC for no apperant reason, i Ahelped, and Theoctdoct looked into it. he found out this. 
https://i.imgur.com/36E0LQo.png
i was still a human, i had just had my look altered several times by the wizzard, with his staff of polymorph.

**Comment by Alberyk** [comment]
That is because you were turned into a xenomorph and they are antag due to game reasons, and being turned into something else did not change your mind/antag status.
