### ISSUE TITLE
Player Panel.

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#3628]
If you keep player panel open cross rounds, the links will direct you to shit that sometimes you do not have access to inside server permissions.

Aka trail mods and fucking virus editor and the ability to release a virus.
https://i.gyazo.com/843a2f377ac4b6d7fa99652c889cf16e.png
(If you are asking, all it was able to infect was Vaurica breeder and all it had was waiting syndrome) 

Robo had confirm aids.

**Comment by Sindorman** [comment]
Interesting, what do you think @skull132 ?

**Comment by Geevies** [comment]
probably fixed
