### ISSUE TITLE
Cameras cause lag

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#363]
7x7 camera shots will freeze everything for a couple of seconds when taken.

**Comment by SoundScopes** [comment]
This loops 49 tiles 3 times, and loops all the objects on the tiles twice. That's 147 + 50+.
Needs a rewrite to either process over longer which would mess up the picture.

It also has the function of spawning a blank /mob at 0,0,0 for every tile it copys even if there is no mob there.

**Comment by skull132** [comment]
Is fixed now with enough lag checks.
