### ISSUE TITLE
Engineering Sublevel HOLES

### ISSUE THREAD

**Issue by AllyBearsley** [Aurorastation/Aurora.3#3631]
Game ID: bQT-dy02
Staff Spoken to: Juani

There seems to be an issue with the Engineering Sublevel being filled with reoccurring holes. I only have pictures of the second time this happened. I figured during the first event with these holes it was antag related, but didn't witness it so I just went about fixing it with another engineer. Well we basically finished patching it up, only to discover that all the holes were right back where they were. It only affects the area south of the elevator, including the maintenance tunnel. In fact basically all of the maintenance tunnel was breached. The round was Crossfire and both Merc and Raider ships were on the station, so maybe something they were doing caused the holes to keep forming, I do not know. If I have enough time to play more rounds I'll see if this bug crops up more. 

Photos to help see damage. It was recurring in the same places (at least from what I noticed.)

![broke](https://user-images.githubusercontent.com/28829986/31475661-b65f6b42-aec7-11e7-9d4a-7d7ea676ede7.png)
![broke2](https://user-images.githubusercontent.com/28829986/31475668-bc60ef66-aec7-11e7-9171-e7363e1f844f.png)
![broke3](https://user-images.githubusercontent.com/28829986/31475672-c0ed9502-aec7-11e7-8659-c37b57da4873.png)
![broke4](https://user-images.githubusercontent.com/28829986/31475678-c4675fb0-aec7-11e7-868c-ab567e64185a.png)

**Comment by Juani2400** [comment]
Occasional bug. May be related to landing sites of the merc/raider ship. To be checked.
