### ISSUE TITLE
Repaired and rebooted IPCs comes back blind.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#3645]
As the title says.
Regardless of attempts to repair the optical sensors with a screwdriver, or even removing-->reinserting them wont work.

**Comment by verywhiterabit** [comment]
I've managed to get around this before by reconnecting to the server.

**Comment by MarinaGryphon** [comment]
I'm pretty sure this is an issue with the `life()` proc not being called? This was/is an outstanding issue with Polaris- it's why they have an IPC-specific defib.

**Comment by MarinaGryphon** [comment]
Attempted to replicate on live, couldn't reproduce. Was able to reproduce it by putting an IPC's head on an organic body, but that's an unrelated issue.

**Comment by Pratepresidenten** [comment]
I suppose this is now irrelevant as IPC revival has been completely reworked!
