### ISSUE TITLE
Some limbs on Zeng-Hu cybernetic limbs stay black with IPC chassis color change

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#3655]
As stated above
![ss 2017-10-14 at 06 48 30](https://user-images.githubusercontent.com/24210359/31579998-5c28e51c-b111-11e7-874a-08e02a9bd1d4.png)

**Comment by ToasterStrudes** [comment]
addendum, it appears that some limbs do not change with body color, only certain limbs with certain prosthetics (I.E this one)
 ![](https://puu.sh/xZesm/6e26e8b787.png)

**Comment by Lohikar** [comment]
The new prosthetics optimally would not change color at all, looks bad imo.
