### ISSUE TITLE
Holocomms

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#3656]
Holocomms have been bugged/broken on Bay for a year, they were never fixed, and it is beyond me why the Dev Team EVER ported them and merged them into master without fixing it.

They leave the call up regardless of severing the connection.

**Comment by XanderDox** [comment]
http://puu.sh/xYgDk/1ae1564da6.jpg

**Comment by Juani2400** [comment]
The holocalls work fine on Bay, but they do not here. The call should take the caller's view to that of the other holopad, and make him able to emote and see emotes, like Bay's does. Currently, our system does not only not do that, but when closing the connection, it leaves the hologram active. @printer16
