### ISSUE TITLE
Cargo Ringer

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#3657]
It doesn't work. At all.

**Comment by printer16** [comment]
They do work. It has a delay.

**Comment by XanderDox** [comment]
Cargo's does not work, you can click it 100 times, it will never make a send and will never send PDA alerts.

**Comment by printer16** [comment]
Are you sure it wasn't on a delay?

**Comment by XanderDox** [comment]
I am sure.

**Comment by XanderDox** [comment]
I found the issue, you can only use it diagonally of the button it seems.

**Comment by XanderDox** [comment]
works now, don't know if there was IC debugging but yeah.

**Comment by printer16** [comment]
Are you sure it wasn't on a delay?

**Comment by Juani2400** [comment]
Other buttons seem to work oddly, as well. Security's worked for another person, but never did for me. I also tried the Medical one, which doesn't work. The HoP's seems to work fine, and so does Cargo (as reported). Not sure what is going on about the buttons.

**Comment by Arrow768** [comment]
Related to #3630

**Comment by Alberyk** [comment]
Fixed it
