### ISSUE TITLE
Holopad holograms do not move with AI eye when holopad is activated and hologram does not dissappear when deactivated

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#3658]
![](https://puu.sh/xYgza/a335902901.png)

This allows the AI to stack holograms

**Comment by Mwahahahaha** [comment]
![image](https://user-images.githubusercontent.com/3950115/31849029-5b7e0842-b66e-11e7-8210-3c93b94aedbd.png)

Lighting works as if it is there when the holopad is enabled. It just seems to be the image itself.
To clarify, this also occurs with hologram camera movement enabled.

**Comment by OneOneThreeEight** [comment]
Think there's a lack of a trigger for it to close ever since the holocall system got ported in.
