### ISSUE TITLE
AI core broken lights

### ISSUE THREAD

**Issue by TheGreatJorge** [Aurorastation/Aurora.3#3659]
Lightbulbs on either side on the tile right next to the AI core spawn seem to have changed vars in mapeditor, making them kind of broken with the new system.

**Comment by AgentWhatever** [comment]
You should read tickets from about 30 minutes back before you post a new one, m8

**Comment by TheGreatJorge** [comment]
Ah, well. Though nobody would report it that earlier. Alright then.
