### ISSUE TITLE
Strange Blast Doors in Xenobiology

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#3671]
Button in red closes and opens the doors in blue for some reason. 
![blast doors](https://user-images.githubusercontent.com/24979527/31588572-0c9932ac-b1c2-11e7-8eb2-262642d28b1b.png)

**Comment by SirFruitcakes** [comment]
It's the new Blast door sprite. https://github.com/Aurorastation/Aurora.3/issues/3690

**Comment by Butterrobber202** [comment]
Rabit is talking about the red button changing THOSE doors instead of the ones by it, and the fact that the blast doors are out of place.

**Comment by SirFruitcakes** [comment]
I was referencing the issue based on the 'Strange Blast doors', comment.
