### ISSUE TITLE
Holocalls persist after you end it

### ISSUE THREAD

**Issue by ben10083** [Aurorastation/Aurora.3#3672]
When you do a holocall to a room close or right beside you ((for science!)).... Even if the call isnt accepted it will act like you can hear them from other room ((see screenshot))  
ADMIN: Alberyk
ID: bQX-c3cB

![fjbsabn](https://user-images.githubusercontent.com/31709901/31588661-4e60cbb8-b1c3-11e7-81a8-53cd3e9dc0b9.PNG)

**Comment by printer16** [comment]
Where were the holopads?

**Comment by XanderDox** [comment]
My call was between Cargo and the HoP office, the captain's office also does it for sure.

**Comment by ben10083** [comment]
The holopads were at cargo office and cargo lobby

**Comment by Juani2400** [comment]
When you talk to a holopad, you don't whisper to it or anything. You speak out loud. Which is why you can hear the other person talking to double, because between the Cargo office and the Cargo Lobby there is nothing more than windows. As long as you see them, you will hear them double.

**Comment by ben10083** [comment]
Problem is that the call that caused it was over and the connection was said to be terminated
