### ISSUE TITLE
Integrated Electronics: Memory Circuits + Demux

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#3683]
I and a few peers seem to be coming across an issue where the output pins in memory-related circuitry (constant chips, memory chips, memory circuits) cannot transfer its data to any other components.

This leads to situations happening where connecting a memory chip output pin to a subspace transceiver's input pin leads to the memory chip output pin data being overwritten to be the same as the subspace transceiver input pin value upon having the memory chip's "set" activator pulsed.

(Pulsing "set" without any data wires in the output pin)
![image](https://user-images.githubusercontent.com/3950115/31597627-fe943192-b27b-11e7-9997-291dc2f248f4.png)

(Pulsing "set" while having a data wire connected between the output pin of the memory chip and the input pin of the subspace transceiver)
![image](https://user-images.githubusercontent.com/3950115/31597653-2815ad16-b27c-11e7-9591-c7f75f19f0a6.png)

![image](https://user-images.githubusercontent.com/3950115/31597657-34ab556c-b27c-11e7-8cf4-6e31c72b75c1.png)

![image](https://user-images.githubusercontent.com/3950115/31597664-42ba5770-b27c-11e7-832f-96be0eb7fbf7.png)

~~Pushing data on a constant chip just sets it to null and its output data is lost.~~ This is because you have to set it internally by activating the chip in your hand. Push data then takes that internal data and sets it to output data. So, no multitool/debugger usage here.

![image](https://user-images.githubusercontent.com/3950115/31597691-5abf0294-b27c-11e7-9624-55c445167d30.png)

![image](https://user-images.githubusercontent.com/3950115/31597695-6027c7de-b27c-11e7-8466-fa45225a3815.png)

(Connected to a subspace)
![image](https://user-images.githubusercontent.com/3950115/31597707-6e66492e-b27c-11e7-9159-aa96b6301931.png)

(After pulsing "receive" activator on the subspace transceiver/"push data" activator on the constant chip)
![image](https://user-images.githubusercontent.com/3950115/31597722-86b86656-b27c-11e7-92ac-96070bdf9fec.png)

![image](https://user-images.githubusercontent.com/3950115/31597728-8e787192-b27c-11e7-96a1-6a514e1d7a29.png)

'Data which cannot be overwritten', huh?
What I'm trying to say here is that there does not seem to be any way to use output data in memory components, and I am assuming that this is not intended. I am not entirely sure about that though. It just seems to defeat the purpose of having memory if you cannot even (seem to) make use of its stored data.

**Comment by Mwahahahaha** [comment]
Similar ordeal with demultiplexers, where its output data (upon receiving it from input) cannot seem to be used for anything else.
I am beginning to think I am missing something here, but again I am not sure whether this was intended or not.

**Comment by Lohikar** [comment]
This issue came up in testing too, but I wasn't able to find a cause. @MarinaGryphon might be able to investigate further, they know more about the issue than I do.

**Comment by Mwahahahaha** [comment]
Another instance is being unable to use the local locator's output data for another component's input either. I suppose this can apply to many other components too.
