### ISSUE TITLE
Rapid Part Exchange Devices don't work properly.

### ISSUE THREAD

**Issue by Cairo283** [Aurorastation/Aurora.3#3685]
Edit: Alright, after some testing, which can be seen in the comments below, the problem lies with RPEDs, not the parts. The RPEDs, while they do change out parts properly, don't actually update the machine or some shit, so the machine doesn't realize the parts have been upgraded, unless the entire thing is deconstructed and rebuilt with the new parts.

Upgraded R&D parts, or upgrades to any machines that use R&D parts, like manipulators and matter bins, don't get any benifit from upgraded parts. An autolathe doesn't produce faster with a pico manipulator, a protolathe doesn't hold more with a super matter bin, etc.

**Comment by MarinaGryphon** [comment]
They _should_ work like that... I thought manipulators lowered how much it takes to make things, and matter bins increased capacity?

**Comment by Cairo283** [comment]
Right, just tested it. The first picture is before I put a pico manipulator and three super matter bins, and the second is after I did that. No, they are not the same picture, the parts literally do nothing.
[https://puu.sh/y5Twd/7735dfdde5.png](url)
[https://puu.sh/y5TyL/0e2ce7be23.png](url)

**Comment by echotango23** [comment]
Thanks to the tireless efforts of the lovely jakmak, I believe that using the RPED doesnt apply upgrades, but if you dismantle the machine and build it by hand (no RPED) it applies the upgrades.

built this autolathe by hand with T1 components, upgraded to T3 via RPED, no change
[https://i.gyazo.com/566e084374f6cdd271961887ebf82068.png](url)
dismantled and inserted T3's by hand and it applied upgrades
[https://i.gyazo.com/03f4a6c6e4132d23c06489502ca99d90.png(url)

**Comment by echotango23** [comment]
thanks to the tireless efforts of jakmak I believve the RPED doesn't apply upgrades, but if you dismantle the machine and build it by hand (no RPED) it applies the upgrades.

built this autolathe by hand with T1, upgraded to T3 via RPED, no change
![t1](https://user-images.githubusercontent.com/17462271/32408677-bfb93fca-c172-11e7-8f8a-07c5420a461a.png)

dismantled and inserted T3's by hand and it applied upgrades
![t3](https://user-images.githubusercontent.com/17462271/32408678-c2420aa6-c172-11e7-87a1-7cce540cb098.png)

**Comment by MarinaGryphon** [comment]
Did you get confirmation that the RPED actually upgraded it? It needs to have a screwdriver used on it first.

**Comment by CdrCross** [comment]
I can confirm that this bug is definitely a thing. The RPED successfully replaces the components inside a device, but those new components have no effect on the machine's function until you crowbar it apart and install them manually.

**Comment by CdrCross** [comment]
@skull132
