### ISSUE TITLE
Blast doors in the Supermatter Engine Core look off.

### ISSUE THREAD

**Issue by SirFruitcakes** [Aurorastation/Aurora.3#3690]
https://puu.sh/xZRhy/b8c8b09733.jpg <= That's how they look at the moment. I was told it was a bug, so i'm reporting it here instead. Original thread here. https://forums.aurorastation.org/viewtopic.php?f=18&t=9329&p=86237#p86237 <= Original thread.

So, the bug is that they are positioned awkwardly and so the new sprites look very off. They could flow into the next door and look very polished and nice, but instead it's like someone made no attempt whatsoever to build them into the windows and just threw them over it. Here's my idea on how they could look.

https://puu.sh/xZSif/3e6585a42b.jpg <= Idea.

I was told that all that needs to be done is they need to be rotated some, but I can't confirm nor deny this.

**Comment by OneOneThreeEight** [comment]
>So, the bug is that they are positioned awkwardly and so the new sprites look very off. They could flow into the next door and look very polished and nice, but instead it's like someone made no attempt whatsoever to build them into the windows and just threw them over it. Here's my idea on how they could look.

Not really, it was an oversight as these are some of the few areas where blast doors are organized in such a fashion. Department lockdowns should also be looked at in-game to check for other minor mapping issues in which the blast doors do not align horizontally.

**Comment by SirFruitcakes** [comment]
You're looking for something that isn't there in that reply. I said what it looks like, not what it is.

As for the lockdowns, i'll have to play more for that.

**Comment by OneOneThreeEight** [comment]
>They could flow into the next door and look very polished and nice, but instead it's like someone made no attempt whatsoever to build them into the windows and just threw them over it.

It just comes off as an accusation of laziness and not necessarily understanding what the reality actually is, and it's that nobody thought of that very specific case.

**Comment by SirFruitcakes** [comment]
It doesn't matter what it 'comes off as', it matters what it is, and noone had touched these Blast doors since the sprite was changed. That's not laziness, that's an oversight. But I just figured the sprite was busted initially. You actually accused ME of accusing somebody else when I had accused nobody and was just trying to present the bug in a humorous manner.
