### ISSUE TITLE
Plant (diona nymph) that joined from spectator can become auto-traitor

### ISSUE THREAD

**Issue by soryy708** [Aurorastation/Aurora.3#3696]
Spoke with Garnascus. This should not be happening.
Server revision: master - 2017-10-17
dcf6bba66d94f65a2a13cd010811dc45386dee41

**Comment by Pacmandevil** [comment]
Considering drones can become autotraitor, I think this is actually "intended" behavior

**Comment by OneOneThreeEight** [comment]
Drones can go on the fritz for whatever reason, however, but nymphs have literally no sense or benefit to become conscripted by the syndicate on the spot to do evil deeds. They were just born on that day and have no IC reason to instantly be a terrorist.

**Comment by Kaedwuff** [comment]
Some diona... are just born evil.

They were a bad seed.
