### ISSUE TITLE
Mule-Bot not enough destinations

### ISSUE THREAD

**Issue by Maskss** [Aurorastation/Aurora.3#3705]
I don't know if this is a bug but there are only 7 destinations and 4 of them are at the QM place. The rest is the kitchen, bar, and Hydroponics. This sort of makes the mule-bot useless as you can't even set a custom coordination. Nor do you have the option to even have it bring cargo to places that actually need delivery.

**Comment by JohnWildkins** [comment]
Mulebots are deprecated content and are no longer used on the Aurora.
