### ISSUE TITLE
Forensics kit has only 7 storage spaces

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#372]
Increase this back to 14, please. Evidence collection is cumbersome and a detective already has to carry a lot in terms of inventory.

**Comment by Arrow768** [comment]
The crime scene kit already has a capacity of 14 small items (Such as swab kits, ...)
Medium items (such as the fiber collection kit, the UV Light, or the fingerprint powder count as two small items)

**Comment by OneOneThreeEight** [comment]
Fingerprint cards, fiber bags, swab samples.

**Comment by Arrow768** [comment]
This is fixed with #665
Shame on me for forgetting about this issue.

**Comment by OneOneThreeEight** [comment]
SHAME
