### ISSUE TITLE
Bearded female characters

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#3724]
###### I kind of really didn't want to report this because _just think of the possibilities_

Could I first just say that I accidentally discovered this when I was planning to create an anomalist character.
As you can see, we were off to a great start.
Anomaly indeed.

![image](https://user-images.githubusercontent.com/3950115/31853273-6dea4960-b6b8-11e7-8b0e-3800f1b84b00.png)

![image](https://user-images.githubusercontent.com/3950115/31853276-77cc2e58-b6b8-11e7-9cde-61d5c03e30d8.png)

Anyways, this has to do with how the character setup works, I suspect.
As I'm sure many of us have noticed when you create a character, save it to a slot, then click on new character, what happens is that the new character actually copies some of the setup of the previously loaded character.
What also happens is that the new character defaults to female, I believe.

I couldn't replicate this using the non-database-based player save system because all the character slots are already there as blank setups:
1. Load up a character with balding hair and a goatee
2. Click "Load Slot"
3. Click "New Character"

The result would end up with you getting a female character that has the same age and hair styles as the previous character.

**Comment by Mwahahahaha** [comment]
![image](https://user-images.githubusercontent.com/3950115/31853485-c7fc8eec-b6bb-11e7-92c8-ae41ff5a087d.png)

Alternatively:

1. Switch character to male
2. Select facial hair
3. Switch character to female

**Comment by OneOneThreeEight** [comment]
Traps aren't gay.
