### ISSUE TITLE
Mercenary game mode isn't in the secret rotation

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#373]
Issue: yes, no? Heist is, so I don't see why mercenary wouldn't be.

**Comment by Arrow768** [comment]
Since this is not really a bug, I think this should be put into a suggestion thread.

There are already suggestion threads for multiple gamemodes to be added to secret.
So I would do that all in one go if people want the secret modes changed

**Comment by skull132** [comment]
Config thing, haven't had time to update the .txt on the server. (Plus, wanted to see how merc works with the changes done before shoving it into regular rotation.) And, not a code related issue, so closing issue.
