### ISSUE TITLE
Vampire doesn't become feral on 0 blood

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#3740]
Probably tied in with #3739

On hitting zero blood you don't become feral like you should do.

Also, as far as I remember, sustaining a large amount of damage also should triggered feral vampire however I could be wrong.

**Comment by skull132** [comment]
It does happen, it just takes way longer than it used to for some reason. And the warning messages were buggerinod.

I've fixed the warnings and bumped the rate, also increased the rate at which frenzy dissipates if you've drained a full human (90+ blood).
