### ISSUE TITLE
Resonator is Broken

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#3743]
There is no other thing for this.

The Resonator should be busting rocks and the like, but it doesn't work when used on rocks. It does work on walls, however it doesn't damage them.
I've done it every round I got them, not working.
The Resonator needs to be fixed, please, for Cargonia and the Mining Legion

**Comment by skull132** [comment]
![Uploading 2017-10-28_14-41-34.gif…](Works just fine?)

Unable to replicate, tested both upgraded and standard. Doesn't work on walls in that it doesn't destroy them, ye, as is intended.
