### ISSUE TITLE
Welding Helmets don't protect your eyes

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#3751]
As it says.  Goggles seem to work, but the helmet, it does nothing.  You'll burn your eyes right through it.

Might carry over to other things that are supposed to protect from welder light.

**Comment by Alberyk** [comment]
Perhaps you were wearing thermals?

**Comment by Kaedwuff** [comment]
I was, actually, now that I think about it. Is that some kind of overlay conflict?

... Did someone actually design a code so nitpicky as to punish people for welding with thermals on, irregardless of a welding helmet?  Because that's a really weird place to try and push for enforcing 'realism'.

**Comment by Pacmandevil** [comment]
It does. and it's intentional behavior
