### ISSUE TITLE
Kinetic accelerator in Mining rig broken

### ISSUE THREAD

**Issue by SodaPopBob** [Aurorastation/Aurora.3#3753]
so i pressed the kinetic accelerator and inserted it into the mining rig. i figured out how to fire it, and it makes the fire sound, and i can even charge it, but when it fires, there is no projectile, and it doesnt break any rock.

**Comment by skull132** [comment]
Tested, works fine.

There is no "projectile" to the kinetic accelerators: all they have is the sound and the impact effect. And it does break rock in my testing. So unless you're able to replicate it and tell me how to do that exactly, I'm unable to fix anything.

**Comment by MarinaGryphon** [comment]
The projectile appeared when I pressed a kinetic accelerator with a tracer installed. It also broke rock. It works fine.

If there are any other issues, tell me, otherwise I'm going to close this in a few hours.

**Comment by MarinaGryphon** [comment]
I jinxed it. As soon as I sent that, I saw the issues you're describing. It didn't fire, even though I was able to charge it. The tracer didn't appear and no rock was broken.

**Comment by MarinaGryphon** [comment]
Something tells me this wasn't intended. https://i.imgur.com/JQsi4X5.png
It's adding the projectiles to its contents.

**Comment by Pratepresidenten** [comment]
You can probably close this as the new modular KAs cant be rigpressed.
