### ISSUE TITLE
carpet smoothing borked

### ISSUE THREAD

**Issue by sdtwbaj** [Aurorastation/Aurora.3#3757]
![image](https://user-images.githubusercontent.com/5306508/32086998-63fde0c6-ba9e-11e7-9a0a-8908a4b40593.png)

to reproduce: place carpet

this is in the Cargo lobby, if you think that makes a difference.

when I lever up a piece of carpet, all of the carpet around it smooths normally, but it won't smooth new pieces of carpet into it.

**Comment by Cairo283** [comment]
It also does this with grass tiles. Sometimes they connect, most of the time they don't.
