### ISSUE TITLE
Mailing system custom locations don't work.

### ISSUE THREAD

**Issue by ben10083** [Aurorastation/Aurora.3#3759]
When I wrapped a pen and set a custom location, "Detective" (detective's office airlock name) I mailed it. It went back to sorting office, so I try "Research and Development" (RnD lab), same result. I even tried the Quartermaster office, but it never worked, I told a admin about it and he told me to github it.

Admin:  SirCatnip
RoundID: bQ0-cYF5

**Comment by SoundScopes** [comment]
The detective's disposal system doesn't have a sorting pipe attached.
The Research and Development sorting tag is just "Research"

**Comment by ben10083** [comment]
Well how am I supposed to know stuff like that

**Comment by SoundScopes** [comment]
Good question, I had to look it up to be able to help you.
The destination tagger should give you a list of valid locations which gets updated when a new sorting pipe is constructed.
I personally don't know why the option for custom location is there when it should list all the locations available.

**Comment by ben10083** [comment]
The admin said it was a mapping error.

**Comment by SoundScopes** [comment]
The sorting pipes don't go off the airlock names, they go off tags defined in the sorting pipes.
The Quartermasters office doesn't have a sorting pipe either.

I'll poke the mappers about the missing pipes.
Best bet is to use the predefined tags listed on the tagger as the custom tags will just send items back to you.

**Comment by ben10083** [comment]
Ok, make sure to see of HoP has one as well, as a drone I would just end up back in sorting office.

**Comment by Juani2400** [comment]
Custom locations won't work. Only a few predefined areas have sorting pipes, and those are listed in the tagger. The Detective's office and the Research and Development lab are not supposed to have a separate tag; the "Research" tag leads to the disposal in the Research Department's break room. Not a bug.

I checked the Head of Personnel's tag, as well. It seems fine and working. Reopen this issue if any problems show up.
