### ISSUE TITLE
Warden doesn't start with a handcuffs box in their locker.

### ISSUE THREAD

**Issue by Keinto** [Aurorastation/Aurora.3#3760]
Not sure if it was intended, but it's odd that the only place they can get more is in the armory and the sec equipment room.

**Comment by Juani2400** [comment]
I am personally fine with the Wardens not getting a box of handcuffs in their office. Doesn't make too much sense, as they can easily get them from the Armoury.

**Comment by printer16** [comment]
Not a bug.
