### ISSUE TITLE
The plasma cutter is garbage for mining.

### ISSUE THREAD

**Issue by chaoko99** [Aurorastation/Aurora.3#3764]
https://github.com/Aurorastation/Aurora.3/blob/378f7a7f52e4030697cb51cfa7465f2afe28dc77/code/modules/projectiles/guns/energy/mining.dm#L328 Please don't link shit like mining tools that aren't area saturation based to random chance.

**Comment by MarinaGryphon** [comment]
This is known, and despite my protests I was told it was intentional. If we buff it, it'll need feedback and testing.
