### ISSUE TITLE
Round instantly ends when conditions are met

### ISSUE THREAD

**Issue by Karolis2011** [Aurorastation/Aurora.3#3765]
So, this issue I am going to describe today is about round instantly ending when:
- There is only player dying pre-game period and it has preferences set to allow spawning as captain and allows to be traitor.
- Game mode is traitor (set via voting, or using game panel)
When round starts with such conditions it instantly ends, probably it is good for testing but not best thing to have in code.
I think that is all.

**Comment by SoundScopes** [comment]
There is a config option `CONTINUOUS_ROUNDS` which disables rounds ending instantly when conditions are met

**Comment by Alberyk** [comment]
Not a bug then.
