### ISSUE TITLE
SMES settings window is not opening after assembling

### ISSUE THREAD

**Issue by Winged03** [Aurorastation/Aurora.3#3769]
**Steps to reproduce are as follows:**

1. Assemble the SMES as said on the wiki
2. Click on the fully assembled unit with an empty hand

It won't open SMES settings window.

I talked about this issue with an admin named Garnascus.

**Comment by TrickingTrapster** [comment]
It goes beyond that. Even when adminbussed in, the interface works but you can't bring up the wires. And in neither case can you add new coils.

**Comment by EJDenton** [comment]
I ran into this issue today. After building the SMES unit I named it in RCON and went to the console. When I tried to set the charge levels it gave a message saying to set the charge level between 0 and 0. Like it didn't recognize it had ANY capacity at all. Hope more info helps.

**Comment by EJDenton** [comment]
Additionally. I built the SMES. I opened the panel. I added cables to connect the terminal to the power line. Then when I was having issues accessing the interface I tried to cut the cables for the terminal. The first time I tried it said I just hit the SMES with the wire cutters. I tried it again and it removed the terminal from the SMES.

**Comment by soryy708** [comment]
Reproduced recently. Game ID bUF-cFld
Arrow said it has something to do with division by zero.

**Comment by soryy708** [comment]
Workaround: VV capacity to 1
