### ISSUE TITLE
Mining drill brace ordered twice from mining supply vendor, did not appear on the shuttle.

### ISSUE THREAD

**Issue by alexpkeaton** [Aurorastation/Aurora.3#3785]
Round ID: bRb-dyAk

Miners purchased drill braces from the mining equipment vendor, but the brace did not appear on the shuttle.  This was attempted twice.  Admin Juani2400 responded and spawned a drill brace in to assist.

The shuttle was called each time empty (with no cargo requests).  An initial call for the drill and one brace arrived successfully.  Subsequently to this order, miners attempted on two separate occasions to order additional braces. The second and third shuttles which were supposed to contain additional braces were empty.  When replicating this issue, be advised that on none of the three cargo shuttle calls were there any crates from standard cargo orders (made through the usual console).  

If I had to guess, I would say that the issue may lie in ordering braces without a drill head on the same shuttle.

EDIT: This issue has been edited to wholly conform with the comment from @nerodrusus below.

**Comment by nerodrusus** [comment]
I was one of the miners involved (Zohra). The mining drill was ordered with one brace, initially, which arrived without issue. However, two of us seperately ordered braces at various points. These were the ones that vanished.

**Comment by JohnWildkins** [comment]
Still an issue. After ordering the first brace and receiving it, braces will no longer appear on the supply shuttle.
