### ISSUE TITLE
Collection of map issues

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#3790]
# Current count is 31
# Surface level

Extra disposal pipe
![](https://puu.sh/ybQUj/874f4c49d8.png)

There is an area inconsistency on the right side. You can see the window on the left included into the tcom sat entry area
![](https://puu.sh/ybQLR/596904a00e.png)

# Main level

## Areas 
Entire section of wall not included into proper area
![](https://puu.sh/ybP9Z/e158c333f8.png)

Section of wall sticking out, could be deleted
![](https://puu.sh/ybPjb/dbd772d2c8.png)

Wall not included into area
![](https://puu.sh/ybPkL/b76d932f9c.png)

Piece of astroid included into area
![](https://puu.sh/ybPlT/319acbdc89.png)

## Cables

Extra cable
![](https://puu.sh/ybPuy/7b764d5c88.png)
![](https://puu.sh/ybPvb/d6628a38a0.png)

## Scrubber pipes

Entire branch going towards atmospherics ends in nothing
![](https://puu.sh/ybPAL/cc83aff1a5.png)

Extra pipes
![](https://puu.sh/ybPCJ/313e8dacb4.png)
![](https://puu.sh/ybPDD/7d7c82b461.png)
![](https://puu.sh/ybPF3/a88210576a.png)
![](https://puu.sh/ybPFF/c3e31a66c1.png)

## Supply pipes

As above, entire branch going towards atmospherics ends in nothing.
![](https://puu.sh/ybPId/5852a29d68.png)

Extra pipes
![](https://puu.sh/ybPJn/7bf3360cfd.png)
![](https://puu.sh/ybPKH/c6067451ad.png)
![](https://puu.sh/ybPMs/677a74af57.png)

## Disposal pipes

Extra pipes
![](https://puu.sh/ybPRy/2ecfcd8146.png)
![](https://puu.sh/ybPST/a3b4a1f747.png)
![](https://puu.sh/ybPTL/72d415c3dd.png)

Chute missing in CMO's office
![](https://puu.sh/ybPVa/98a20f2872.png)

# Sub level
## Areas

Section of wall not included into area
![](https://puu.sh/ybPZx/03f37cfd78.png)
![](https://puu.sh/ybQ1J/31f2330528.png)

This one is debatable, though the left section should be included
![](https://puu.sh/ybQ66/251d7eb9c7.png)

## Wires

Extra wires, also strange change in color
![](https://i.imgur.com/zket77X.png)

## Supply pipes

Extra pipes
![](https://puu.sh/ybQa4/2833939ff6.png)
![](https://puu.sh/ybQb6/9e10edbf50.png)

## Scrubber pipes

Extra pipes
![](https://puu.sh/ybQia/34fa15205c.png)
![](https://puu.sh/ybQmJ/35c7eb05a2.png)
![](https://puu.sh/ybQrJ/83492a1d87.png)

## Disposal pipes

Extra pipes
![](https://i.imgur.com/6wT5pDz.png)

That concludes my finds for now

**Comment by TheGreatJorge** [comment]
I'll go ahead and fix these today, if there are no objections to that.
