### ISSUE TITLE
Quantum Cryo sleep 2: Space time boogaloo

### ISSUE THREAD

**Issue by FatCat1978** [Aurorastation/Aurora.3#3797]
Interrupting the do_after when shoving someone into cryo sleep, still updates the cryo pod, but doesn't put them in it. this allows you to teleport them to it at will later.

part 1:
https://cdn.discordapp.com/attachments/302201161044328450/375413267704840204/unknown.png

part 2:
https://cdn.discordapp.com/attachments/302201161044328450/375413279713132545/unknown.png

**Comment by MarinaGryphon** [comment]
This also occurs with wheelchairs and cyborg chargers, I believe.
