### ISSUE TITLE
Plant bag bugs out when loading things into biogenerator

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#381]
if you have a plant bag open with lots of things inside it, the icons aren't properly removed when the items are taken out and moved to the biogenerator.

This can result in icons that stay persistently stuck on screen, like this:

http://i.imgur.com/kqBEydk.png

To reproduce:
Gather a ton of things in a plant bag
have it open so you can see the contents
use plant bag on biogenerator

**Comment by skull132** [comment]
Fixed by #388 .
