### ISSUE TITLE
Aggressively grabbing a nymph gets you stuck in an invisible grab that you can resist out of, but not break, and you're stuck forever unless someone pulls you

### ISSUE THREAD

**Issue by NonQueueingMatt** [Aurorastation/Aurora.3#3817]
Pretty much title. What happens is you get a blue grab on a diona nymph, and then you can either toss them or table them or whatever, and you're stuck in place. You can turn, but not move. You can resist, and it says:

"Urist McRobust gets out of  's grip!"

But it doesn't actually free you. You can keep resisting and you'll get out, but the grip is always there, and you're stuck forever unless someone pulls you away.

**Comment by MarinaGryphon** [comment]
This is the exact same as https://github.com/PolarisSS13/Polaris/pull/4247, I think. I can fix this really quickly, assuming it's the same issue.
