### ISSUE TITLE
Farmbot - No water collection.

### ISSUE THREAD

**Issue by Urthrem** [Aurorastation/Aurora.3#3822]
Recently due to known issue for borgs with buckets I tried to use farmbot to help with the crops only to discover that it will try to water everything despite having the option disabled, ignoring the idea and need to refill its tank. If left alone it will try to spam water one of the trays, returning to it even if dragged away.

Turning it off and back on doesn't help...

**Comment by BurgerLUA** [comment]
Another bug is that it will try watering stuff for eternity despite not having any water in the tank.

**Comment by Sindorman** [comment]
Fixed
