### ISSUE TITLE
List of outstanding issue in integrated electronics modules

### ISSUE THREAD

**Issue by Dunkhan** [Aurorastation/Aurora.3#3823]
I have found some issues with the integrated electronics module but I am either unable to fix them myself, or simply dont feel they need to be done right away. Either way I feel like it is a good idea to put them here so they don't get forgotten.

1. Button output pulse pin does not work on medium assembly (mechanism). I looked over the code and I can see no reason for this. It is possible that there are a number of other components that are also behaving differently based on which assembly they are in.
- Reproduce:
.Create a device assembly and a mechanism assembly, two buttons and two text to speech components
.in each assembly, wire the button to activate the text to speech component
.add a random string to the text to speech component
.press both buttons
note that pulsing the output pin also does not work, so the issue is with the pin not the button itself

2. The balancing values of the components need to be redone in a complete balancing pass. As it stands the values are all over the place and are not even set in many components. As there are ongoing efforts to expand the system this should either be left until that is more complete, or added as requirements for the code review of this module so that it does not need to be constantly rebalanced.
Values are size, power_draw_per_use and complexity
Currently it is possible to fit 30 large screens in an implant. Balancing this should be done with player feedback from those using the module on a regular basis

3. Strings in the system are being sanitized at multiple places in the code, the default sanitize function removes leading and trailing spaces. This can cause headaches, especially in the concatenator where it is nice to be able to concatentate "[playername]" + " : " "message" for example, which results in "bob:message" without the spaces. The default sanitize call looks like 
sanitize("mystring")
this needs to be changed in each case related to the electronics module with
sanitize("mystring", MAX_MESSAGE_LEN, 1, 0, 1)
the fourth argument defines whether spaces should be stripped or not
I have done this in all the places I can find, but it is still stripping. With my changes if you add multiple spaces some of them dont get stripped.

4. the ability for machines to arbitrarily grab items adjacent to them should be reduced in my opinion, it seems to go against the flavour of the devices which are simple soldered together electronic components. An adjacent grabber module could be implemented so that the functionality can be retained but it should be large and complex and require a lot of power. This is a controversial issue and many do not agree with my position on this.

**Comment by JohnWildkins** [comment]
Buggy behavior can no longer be reproduced. A bit late, but the suggestions would be better served on the forums.
