### ISSUE TITLE
Trying to implant stuff into IPCs does not work

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#3830]
The surgery type of implanting stuff, with drills. It just gives this

You start making some space inside Nymphaea's  cavity with the surgical drill.

and then you can't put ANYTHING inside that cavity, and it makes that same response for everything

**Comment by Lohikar** [comment]
I don't think that normal implant surgery should even work on IPCs, it doesn't make sense. This should get its own IPC-specific surgery.

**Comment by MarinaGryphon** [comment]
Since IPCs always have a robotic torso, this should be an easy fix: A check to make sure the limb (the torso in this case) isn't robotic, and then a different, IPC-specific surgery that's a subtype of robot surgery steps.
