### ISSUE TITLE
Nitroglycerin wont explode

### ISSUE THREAD

**Issue by SodaPopBob** [Aurorastation/Aurora.3#3831]
bRk-b7g0
Mod: exia352

i spent the round making the precursors for Nitroglycerin. i had all three, and set up a grenade with 30u of each precursor, activated it, and attempted to test it. when i primed the grenade (there was a message in chat saying i did) the light on the grenade did not blink, and when i threw it, it never exploded. No damage to surroundings.

i then tried again, and same result

then i tried mixing all three precursors in a beaker by hand, since i was confused as to why it wasn't working, thinking maybe it just wouldn't work in a grenade. i mixed 5u of each of the three precursors into one beaker, and i got a message saying the mixture violently exploded, but there was no explosion, no damage to me or the surroundings. confused, i then took apart the grenade i made, and mixed those together (30u each) thinking that 5u each just wasn't enough to explode, maybe it just poofed or something. but nope, no explosion, just the chat message. no damage either, to me or surroundings during any of these tests.

i then ahelped Exia, and told them what was going on. i had them watch me mix the chems by hand so they could see for themselves, and got the same result. Exia suggested filling out a bug report, and here i am.

**Comment by printer16** [comment]
Seems to be working.

**Comment by printer16** [comment]
Closing. Works as far as I'm concerned.
