### ISSUE TITLE
Falsified Centcomm Announcements Do Not Display From C&C Consoles

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#3841]
They don't print out of them or show up on the program's announcement history. 

Should be acting the same as any normal announcements. Has been used for easy meta.

**Comment by Arrow768** [comment]
Falsified from the AI or using the traitor announcements ?

**Comment by verywhiterabit** [comment]
AI announcements, traitor announcements, and rev announcements if they are any different from the normal traitor ones.
