### ISSUE TITLE
Vampire dominated victims doesnt get their commands.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#3848]
Seems to be a recurring issue. People are not getting the dominate commands issued to them.

Might be a byond issue, might not be. Worth posting I guess.

**Comment by Pacmandevil** [comment]
I've got this bug to reproduce ONCE on a test server, no clue what causes it, very well might be a byond issue.

**Comment by Geevies** [comment]
I assume it's something akin to byond swallowing your messages. Nothing to be done, I think.
