### ISSUE TITLE
Disposal mail system.

### ISSUE THREAD

**Issue by Sindorman** [Aurorastation/Aurora.3#3854]
As a maintenance drone I set my tag to go to HOP's office, and I started my journey in Security's lobby office disposal unit.
I have made three loops around station passing by HOP's office, never got there. Eventually disposal system dropped me off at Cargo trash outlet.

**Comment by Mwahahahaha** [comment]
This happened to me as well not so long ago. HoP's office as well. I looped around the station main level three times before I was sent up to the surface level and came out through a broken pipe.

I'm wondering what would happen if you were to try setting the mail tag while in the system?
