### ISSUE TITLE
Security bots target guard dogs (including Lt. Columbo)

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#3858]
Officer Beepsky targets Lt. Columbo and begins chasing them. Includes ED-209s, where they start shooting their tasers at the dog.
It's a good thing he's wearing that armour vest.

May have to do with how security bots treat hostile simple animals?

**Comment by dragoslava** [comment]
This was fixed along the line by @Sindorman , gonna leave this open for abit however
