### ISSUE TITLE
Farmbot watering loop stuck bug

### ISSUE THREAD

**Issue by leprasorium** [Aurorastation/Aurora.3#3868]
Made farmbot (plant analyser is not used I don't know why plant analyser was not used in creation, but it was added at last in queue)
Everything was turned on but unlocked by roboticist.
Game id bRu-aSEx
station time 18:37
round duration 02:28
The farmbot constructor confirmed a bug is Diamond With Flaw (Mechatronic Engineer)
After empty water tank 0/1000 it forever looping action
Farmbot starts watering the tray (#57).
Farmbot waters the tray (#57).
Farmbot starts watering the tray (#57).
Farmbot waters the tray (#57).
Farmbot starts watering the tray (#57).

**Comment by leprasorium** [comment]
Locked/unlocked it with settings
Watering controls:
Water plants : No
Refill watertank : No

Weeding controls:
Weed plants: Yes

Nutriment controls:
Replace fertilizer: Yes

Plant controls:
Collect produce: Yes
Remove dead plants: Yes
It unstuck but still unable to refill watertank. Now works well but never watering

**Comment by leprasorium** [comment]
Watertank used in construction was about 760/1000

**Comment by Sindorman** [comment]
Fixed
