### ISSUE TITLE
Genetics and/or Cloning can be used to turn positronic brains into organic ones

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#3890]
Could I just first clarify here that I don't mean to be a salty sailor so green with envy and seasickness when I'm reporting this — personally I think that this little experiment that was done on the main server was pretty damn cool and creative, albeit it has some serious lack of consideration for RP and for other people as well. I'm not mad, I'm just concerned about the telltale signs.

With that said:
Currently, it is possible to attach a robotic head to an organic body if you were to amputate the original organic head. Then you can place an MMI or, in this instance, a positronic brain inside which would then allow the player controlling said brain to then control the body.

This is all pretty neat and all, but then you can take things steps further:
What you can then do is kill this new body and then clone them, and out pops a new organic clone with the consciousness of the positronic brain. Now maybe you can argue that the cloning machine prints out new clones with new consciousnesses and it's not actually a transferral of the old one — but that's just a grey topic for something else and here I can introduce an alternative method that I've discovered with my own experimenting:

Instead of cloning the body, you can instead place a body into a genetics modification machine and turn them into a monkey, and then turn them back into their original organic being. Said entity being 100% organic with no artificial or assisted internal or external organs. So, the result is that you now have a positronic brain's consciousness inside an organic brain.

Now, this is all fine and dandy in terms of bringing up lots and lots of questions and theories and philosophies as to how positronic brains work and bla bla bla and all that, and can potentially be used creatively for RP with all sorts of 1950s sci-fi body horror experiments;
but, as it stands right now it just seems like an oversight and well, if you think about it just shouldn't really be possible (at least in the case of the alternative method).

**Comment by Alberyk** [comment]
Fixed.
