### ISSUE TITLE
Winter coat hood

### ISSUE THREAD

**Issue by woody41** [Aurorastation/Aurora.3#3918]
Toggle-coat-hood command doesn't work properly. 
Job: Medical Doctor; Wearing: Medical winter coat;

When I try to call command from "Object" tab it wrote "You must be wearing the medical winter coat to put up the hood!"

Standard right click on coat and select "Toggle Coat Hood" works properly.

**Comment by MarinaGryphon** [comment]
Were you standing next to or on another coat that you weren't wearing, even if you had it on? This is an issue where it's ambiguous what atom you're referring to, so it just calls it on one that may not be the one you're wanting.

**Comment by woody41** [comment]
No, I was wearing coat and tried it on many places with only one coat.
