### ISSUE TITLE
Missing sprites

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#392]
So, I came across a psychiatrist wearing the following items: A helmet that resembles a security helmet, but with no sprite.
A suit that had the simple sprite of "Suit"

http://puu.sh/pmtfJ/7a117a4236.png
http://puu.sh/pmtji/df04d06ccd.png

**Comment by OneOneThreeEight** [comment]
Chameleon gear, most likely.

Chameleon gear can morph into the base paths of items which may have a item state but not an iconstate.
