### ISSUE TITLE
NTSL Scripting Functions to a Limited Extent

### ISSUE THREAD

**Issue by Youbar** [Aurorastation/Aurora.3#3939]
This probably isn't very surprising. NTSL scripts, from what I can gather, seem to be a relic from the past. Regardless, I'll outline a few issues I've encountered.

elseif, and else statements, do not function. You will be met with a syntax error, that goes very much along the lines of "expecting '{', saw '{'". Only if statements work.

The time() function does not retrieve the time. You will receive a null value.

$source = $source + " (" + $job + ")";, one of the most basic scripts in the game, does not work. It takes the source transmission, and modifies it by adding the name of their job from the crew manifest. The only instances in which this appears to work are when the AI speaks. It may actually be working, but if it has, the crew isn't communicating that fact with me.

That's the extent of my findings so far. Some things do work on a limtied basis, but other parts are completely broken. All of these can be reproduced in-game. I've put some code below to quickly test these:

$time = time();
broadcast($time);

Output: "*beep*" (time() does not return a value)

if($time == null)
{
broadcast("Time is invalid.");
}
elseif($time != null)
{
broadcast("The time is " + $time + ".");
}

Output: numerous syntax errors relating to elseif. You can try with else, too, and get the same result.

I'd be very happy if the coders here were willing to continue to update NTSL scripts, but it seems like it might just be better off disabling them entirely. As it stands, it's incredibly buggy, and it'd take a long time to restore it to its prior state.

**Comment by MarinaGryphon** [comment]
Did you try having the curly braces on the same line as the elseif?

**Comment by MarinaGryphon** [comment]
There is also no `time()` function, to my knowledge. It's not documented anywhere, nor is it in the relevant file. It could probably be implemented, but as it stands it's technically not a bug. I'm investigating the elseif and else issues right now.

**Comment by MarinaGryphon** [comment]
Elseif is also not a valid keyword. It's not defined. Only `else` and `if` are. These could possibly be implemented, but as it stands it's also not a bug.

I'm also tentatively saying the `$source = $source + " (" +$job+ ")"`  script only working on silicon types is intentional? As it stands, you can't change the source, period, of any human-type (perhaps even any non-silicon) speaking over the radio. You have to set `$pass = 0` and then broadcast the message with the new source as a workaround.

**Comment by Youbar** [comment]
> Did you try having the curly braces on the same line as the elseif?

No, I did not.

> There is also no time() function, to my knowledge.

The scripts I made were based on TG Station's NTSL Scripting Guide. Time is listed as a function here, wherein it returns the "realtime value of the server". It's fairly useful for cycling through a set of messages.
https://tgstation13.org/wiki/NT_Script#Miscellaneous_Definitions

> Elseif is also not a valid keyword. It's not defined. 

Again, this was based on the guide I was looking at. I'm aware it's different for each server, but NTSL seems like, as I said prior, a relic, that'd sort of stay the same across the codebases.
https://tgstation13.org/wiki/NT_Script#Conditionals

> I'm also tentatively saying the $source = $source + " (" +$job+ ")" script only working on silicon types is intentional?

I don't see much point in that. If what you said is true, then it doesn't really change anything - you just end up implementing a much longer set of code for the same result.

On another note, I'm not sure whether this is a bug or not, but if you do a broadcast of any type, and assign it the name of something like "Automated Alerts System", it'll show as "AUTOMATED ALERTS SYSTEM" in the chatbar. Just try this snippet of code:
broadcast("Please ensure that your suit sensors are at their highest level", 1459, "Automated Alerts System", "AI")
This then means that even if you implement the workaround you've suggested above, everybody who speaks will have their name and job capitalised within the chatbar.

**Comment by Youbar** [comment]
Adding further to this, there seems to be a glitch that occurs when selecting the option to edit the code, in that after a while, the option doesn't respond. You can click it, but no interface appears to allow you access to the scripting screen.

I can't really figure out a way to reproduce it, but the last time it happened, it was when I was fiddling around with the channels that were allowed to execute the code. I ended up enabling it for one channel, inputting the code, and then disabling that channel again, and then when I went back to edit the code, it wouldn't allow me back in. Disconnecting and reconnecting seems to fix the issue, so maybe the window isn't properly closing when I exit out of it? Or it might just be a client side error.

**Comment by MarinaGryphon** [comment]
Oh, right, I'm aware of that issue actually. It's existed for a very, very long time, since even CM has that bug. I'll fix it soon.

**Comment by Geevies** [comment]
Outdated, since NTSL2+ released.
