### ISSUE TITLE
Cargo Items Misnamed/Missing Descriptions

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#3963]
Some names of cargo items have been cut off, for example 'PDA' is 'DA', as well, some item descriptions are completely missing. I am not on as Cargo ATM so I do not have more examples, but a quick join as a CT and looking at the lists should show which items have issues

**Comment by Pacmandevil** [comment]
have you tried resizing the nanoUI window

**Comment by XanderDox** [comment]
@Pacmandevil Yes, and even so, it would not change the fact that cargo items (multiple) are lacking descriptions.

**Comment by printer16** [comment]
Has this occurred again?

**Comment by Arrow768** [comment]
That is a config issue and not a bug in the code.
Please report any issues with the config in the proper thread on the fourm.
