### ISSUE TITLE
Telecomms turrets have buggy sprite

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#3980]
https://i.gyazo.com/ad81435533e613b51f56d7a75a3ba6f1.png

**Comment by Sindorman** [comment]
It seems like T-comms turrets are different turret, that is set to lethal by default, and it has nothing set to stun interaction, so I guess that is the problem.

**Comment by LordFowl** [comment]
I believe centcomm uses laser cannons, which indeed have no stun setting and so no stun icon.

**Comment by Sindorman** [comment]
Solution to it is either keep the control on lethal only or switch turrets to the one that use carbine, hence it will have both settings.

**Comment by TheGreatJorge** [comment]
I could also add a sprite to the rifle set for stun-mode.
