### ISSUE TITLE
Cargo Control program not updating synthetic names

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#3992]
https://i.gyazo.com/7390f55c115b7f86deb7ddd05febb10c.png

As seen here, the default name you are given at roundstart or spawn as an AI is used on this program, irregardless of whether you change it to a custom name afterwards.  Might be happening with borg too.

**Comment by Arrow768** [comment]
First guess is that this is an issue with the name on the synthetic id not being updated when a borg renames itself

**Comment by MarinaGryphon** [comment]
Fixed in #4000. (Presumably. Closing this.)

**Comment by MarinaGryphon** [comment]
Fix was merged into development, this bug occurs on master. Reopening for now.
