### ISSUE TITLE
Vaurca Internal Surgery is broken.

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#400]
I officially have no idea what the hell is going on. All I know is this:
All surgical operations for Vaurca work EXCEPT for any operation included in organs_internal.dm.
This was NOT the case in old-code.
As far as I can tell oldcode surgery and newcode surgery are identical.

I will be moving on from this bug, and working on other Vaurca features. Anyone is welcome to try their hand at fixing it.

**Comment by LordFowl** [comment]
I've figured out the root cause: The ORGAN_ADV_ROBOT status breaks surgery somehow. Will investigate further.

**Comment by skull132** [comment]
This was fixed, aye, @LordFowl ?

**Comment by Bedshaped** [comment]
¯\_(ツ)_/¯
