### ISSUE TITLE
Dropped dead, all limbs missing, carrying a metal foam grenade.

### ISSUE THREAD

**Issue by ghost** [Aurorastation/Aurora.3#4007]
Was carrying a metal foam grenade, and then I collapsed and dropped dead, all my limbs missing, within the space of a couple of seconds. 
Possibly related to metal foam grenade since it had polytrinic acid in it, but I checked the contents of the beakers after being rejuve'd, all the beakers were completely full of their original contents still. Leading me to believe that wasn't the problem.

**Comment by MarinaGryphon** [comment]
Is there a round/game ID for this so that logs can be pulled? As it stands, I don't think there's enough information to go off of.
