### ISSUE TITLE
Consoles fail to load

### ISSUE THREAD

**Issue by MMRichardson** [Aurorastation/Aurora.3#4010]
Occasionally, opening some consoles throws this error.  (Template Engine failed to load)
![image](https://user-images.githubusercontent.com/4001866/34282026-abc5d7c4-e690-11e7-81fd-90a3c449f8e3.png)

After closing the dialogue, it looks like this. 
![image](https://user-images.githubusercontent.com/4001866/34282042-bd5c47e8-e690-11e7-801a-42f9bbefe30f.png)

It seems to affect any console using the fancy graphics.  Doesn't affect stuff like the prisoner management console, but does affect fridges, chem dispensers, APCs, etc.

**Comment by Sindorman** [comment]
Hmm, never had that. @MMRichardson what version of byond are you using?
