### ISSUE TITLE
Minor issues on Form NFC-0505 

### ISSUE THREAD

**Issue by Asheram** [Aurorastation/Aurora.3#4011]
The Request Console Form NFC-0505 has two errors.
Date is automatically inserted as Local IRL date and not ingame date.
The coordinate is hardcoded as Z-level 05 even though anomalies are found on 03 (same as Xenoarchaeology)

**Comment by Lohikar** [comment]
Issues with forms should be forwarded to CCIA. If the date issue applies to other paperwork as well, please submit a separate report.
