### ISSUE TITLE
*halt says robot's name twice

### ISSUE THREAD

**Issue by ben10083** [Aurorastation/Aurora.3#4030]
As a cyborg if you equip security module you can do things like *law and *halt. But if you do *halt it does this: B.O.B B.O.B's speakers skreech, "Halt! Security!". It should not have the first B.O.B (robot's name).

Admin: MattAtlas
RoundID: bR9-cT7g

**Comment by MarinaGryphon** [comment]
Confirmed, easy fix. One moment.
