### ISSUE TITLE
Cargo ordering limits

### ISSUE THREAD

**Issue by YuriDaruski** [Aurorastation/Aurora.3#4033]
When ordering a large surplus of items, it will only fill one crate, making it that any items beyond a crate's limit is not delivered or added or a new crate, causing a loss of credits, and time really. Honestly this has only ever come up once for me now, after Johnny Styles won the lottery. Total order price was about 7916 credits, so certainly not unheard of in price ranges, especially with say, Operations funding. Not sure if there would be an actual fix for this with the current Cargo system but, something to look into I guess

**Comment by Arrow768** [comment]
This should not be possible.

When adding a item to a order it is checked if:
- The item can be grouped with other items
- The item has the same container type as the items already in the order
- There is space in the container for the item

If any of these conditions is not met, a message is displayed to the user that the item has not been added.

To reproduce this, I need to know what has been ordered and what has not been delivered (that was listed in the order details)

**Comment by Pratepresidenten** [comment]
I was asked about a similar issue. An order of 4 regular armor vests + 4 silenced pistols was ordered.
However, one crate was shipped and only the armor vests was delivered. Shuttle re-launch did not help.

On a similar note, ordering up 2 drill braces and an industrial drill head from mining seems to fail to ship most of the time. They just dont show up.

**Comment by Arrow768** [comment]
I just tried ordering 40 items in a crate and they all arrived.
If this happens again, then please make sure to note down the round id, what has been ordered and what has been shipped in this issue.
Then I can investigate the logs and find out what happened.

**Comment by Arrow768** [comment]
Could not reproduce the issue.
