### ISSUE TITLE
Ninja/wizard spawn in the depths of space.

### ISSUE THREAD

**Issue by AttyZ** [Aurorastation/Aurora.3#4042]
Running a downstream server with DEV BRANCH, no real modifications have been made to anything, i've only configured files. The ninja and the wizard seem to spawn in the depths of space as of latest version of dev.

**Comment by Arrow768** [comment]
The same thing seems to happen to malf ais

**Comment by Alberyk** [comment]
Might be an issue with landmark/start

**Comment by Arrow768** [comment]
Please fix this issue. Its caused by one of your changes

**Comment by Arrow768** [comment]
Caused by #3977

**Comment by skull132** [comment]
Note. If caused by #3977, then the most likely source I can find at a glance is misc_first running _before_ map load, which might cause a race condition?

**Comment by skull132** [comment]
ded now.
