### ISSUE TITLE
non-sprited items spawning in Cargo warehosue. 

### ISSUE THREAD

**Issue by YuriDaruski** [Aurorastation/Aurora.3#4047]
Been a problem in the past that I thought was fixed but, the items, "Christmas" "Wreaths" and "Christmas lights" all spawn in the warehouse. They can be picked up but have no sprite what so ever. Not much else to it.

**Comment by TheGreatJorge** [comment]
Kind of same with #3855 
I also guess it's because they're all decals. And all decals spawn in warehouse, or something.
