### ISSUE TITLE
Heist game mode does not automatically end upon crew transfer/evacuation competition.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#405]
For round type consistency's sake, it's best if we just revert to the good old system of "when the shuttle arrives at CentComm the game should probably end and prepare to restart" to avoid delayed shenanigans on the part of the antagonists intentionally or unintentionally stretching the round out past what's reasonable.

Allowing it to end like the other game modes due upon the shuttle arriving at CC would prevent unnecessary circumstances from occurring and requiring a server restart from an administrator. Makes secret-heist rounds during periods of low staffing less annoying.

**Comment by LordLag** [comment]
Already fixed fix is awaiting merge.
