### ISSUE TITLE
Spaceacillin syringes refill when re-inserted in the vendor.

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#4054]
Apparently Spaceacillin syringes get refilled when inserted empty into the Medical Vendor.

Steps to reproduce:
1) Empty the vendor of all its loaded syringes (Spaceacillin ones).
2) Empty one of the syringe's contents into a beaker or yourself.
3) Re-insert the now empty syringe into the vendor.
4) Take out the just-inserted syringe.
5) Rejoice with the infinite source of antibiotic.

**Comment by verywhiterabit** [comment]
Works with most things actually. Any of the bottles also refill along with brute/burn kits.
