### ISSUE TITLE
Physical and digital records connection

### ISSUE THREAD

**Issue by Moonyman** [Aurorastation/Aurora.3#4071]
Mechanical records (in the filler cabinets in forenscs office) get deleted if the corresponding digital records are deleted (be it due to person going to cryo or manual deletion), which makes no sense and defeats the purpose of having them in the first place

**Comment by skull132** [comment]
Not a bug.

It's a bit of a hack, but the record cabinets are basically re-sprited record computers. Were this not the case, you'd have to also simulate yourself adding in the record of every new arrival and so on. So basically, this is done for convenience.
