### ISSUE TITLE
You can inject people from afar with mounted chem injectors

### ISSUE THREAD

**Issue by NonQueueingMatt** [Aurorastation/Aurora.3#4074]
Pretty much as the title says, go 6 tiles away from a dude, middle click him, he's injected with what you selected in the hardsuit modules tab. The chems also work properly.

**Comment by Pacmandevil** [comment]
thanks rigs.

**Comment by NonQueueingMatt** [comment]
what, you don't like being injected with radium from 6 tiles away?
