### ISSUE TITLE
Fix Food Sizes

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#4106]
Not sure if this is already in the github, I couldn't find anything.

But a bunch of (read: all) the foods nanako coded in that are created via putting (an) item(s) into a machine and getting a generic preset food item out of it (as opposed to food that is made via specific recipe ingredients) do not fit inside containers. Regardless of their actual size, the game registers them as 'too long' to fit in a bag.  

This should be corrected.  Maybe they should scale in size based on how much food reagents are in them? I don't know.

But it needs to be changed, because being told I can't fit a tiny lollipop or pie in my bag is pretty dumb.

**Comment by Sindorman** [comment]
I shall investigate and try to fix it for you, sir.
