### ISSUE TITLE
Borg module failing to install

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#4112]
It has come to my attention that the "Rapiud taser cooling module" for the borg cannot be installed, as it prompts an "Upgrade error" message whenever you try to put one in.

Apparently this is a known bug, but not reported. smh

**Comment by Mwahahahaha** [comment]
![image](https://user-images.githubusercontent.com/3950115/36729242-8138eb06-1bfe-11e8-95b7-1b05d674cdd4.png)

(code\modules\mob\living\silicon\robot\robot_modules.dm)

Seems to get overridden by the subtype it plays into.
May also be worth mentioning that on lines 350 and 365 both define the same variable for the same object.
