### ISSUE TITLE
Layering be Broke

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#4114]
Layering for items is broken, here are a few examples:

Pens now hide under laptop consoles (the ones that spawn at roundstart)
Some items when put into lockers will go under the locker sprite, displaying an empty locker
If you put a corporate regulations book on every bed in the security cells, only Cell #1 will have the book ontop of the bed, the rest will be under

This is a minor issue but still a pet peeve at times.

**Comment by robovelcro** [comment]
Just to confirm, as of 15th December 2019, this bug _still happens._ I've seen it with crates and lockers, and it's both unsightly and a pain to deal with.
![image](https://user-images.githubusercontent.com/17680257/70858163-2af87180-1ef4-11ea-8ac9-259afc6862e3.png)
