### ISSUE TITLE
Telecomms machinery doesn't work when rebuilt/built anew

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#4116]
When rebuilt, or constructed anew, Telecomms machinery supposedly doesn't work. Even if linked properly with multitools.

Requires investigation and fixing.

**Comment by Lohikar** [comment]
Destroyed prefab array using explosives and built another using bare minimum setup:
- 1x Broadcaster
- 1x Receiver
- 1x Bus
- 1x Processor

Broadcaster <=> Bus
Receiver <=> Bus
Processor <=> Bus

Network and IDs set, tried with no filtering freq and filtering freq set to 145.9 (Common).

No radio function.

**Comment by SonicGotNuked** [comment]
I've made a list comparing the VV mode with each other with map spawned processor to created processor.
Mapspawned vs created
Delay: 7 vs  Delay: 8
In use: 0 vs In use: 1

Maybe this will help, idk.
