### ISSUE TITLE
Using Noise while whispering capitalises the first letter

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#4119]
Using the ! prefix to use an audible emote (i.e., switch to Noise language) capitalises the first letter following the prefix, which can cause minor issues like this:

![image](https://user-images.githubusercontent.com/3950115/35047447-e84a20ac-fbd4-11e7-93d8-ea0bc4c02880.png)

I suppose on that note, one could also see that there is a missing speech verb when whispering normally.

**Comment by NonQueueingMatt** [comment]
Should be fixed
