### ISSUE TITLE
Unathi being poisoned by animal protein/synthflesh

### ISSUE THREAD

**Issue by cheap31** [Aurorastation/Aurora.3#4121]
Recently [over the past few days], I've been playing chemist and making synthflesh when I get hungry. After eating a single slab, toxin starts to build in my bloodstream. This effect continues for the rest of the round requiring constant dialysis and dylovene.

I tested this several times to see how I could replicate it. It seems to only happen with synthflesh and its animal proteins. I have tried to recreate the effect with vendor items, to no avail. It only seems to occur with synthflesh and pill forms of animal protein.

I am gaining nutrition to affect my hunger and fill me up, but I am also consistently getting this toxin effect. 

Ipecac was used to remove anything from my stomach that would be metabolizing into my bloodstream to create toxin and the effect continued even with an empty stomach.

I'm trying to pore over code to isolate the issue, but I am a coder neither by profession or hobby, so I'm not very good at it or sure what I'm exactly looking for.

**Comment by Arrow768** [comment]
I am not sure if this is a bug, and you should even be able to eat raw synthflesh.
