### ISSUE TITLE
please send help

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#4122]
Previews are very broken

![](https://puu.sh/z3Vr7/d8663faa31.png)

![](https://puu.sh/z3VAR/2f261c0270.png)

![](https://puu.sh/z3Vt8/65eb016445.png)

![](https://puu.sh/z3Vp8/73c7d0d57a.png)

**Comment by Lohikar** [comment]
Memory issue, not code issue.
