### ISSUE TITLE
Newscaster Breaking News icon when unpowered

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#4129]
_DOODOOT-DOO-DOOT-DOOTOO-DOOT-DOO_
![image](https://user-images.githubusercontent.com/3950115/35182969-e6bcd072-fe18-11e7-9bd4-d196ab5bcacf.png)

Good evening, and welcome to Romanovich Reports at 6; I'm Christopher Chrinsington.
Earlier this morning, NanoTrasen employees have been baffled to discover **that on-station newscasters are still capable of displaying the notifications banner despite having no power to operate.**

![image](https://user-images.githubusercontent.com/3950115/35182982-4aa71b24-fe19-11e7-9019-7326c48667f5.png)

Technicians have discovered that **this only seems to occur when newscasters receive feed updates just before remaining unpowered**, and that **this phenomenon does not occur if the newscaster was unpowered before receiving a feed update.**

And now: the weather.

**Comment by Mwahahahaha** [comment]
Thanks, Chris.
Hi, I'm Tristan Trinsington, and I hope you brought your jackets out because it is going to be dark and gloomy all throughout the week. As you can see here, we've got a straight overcast with no chance of sunshine perhaps until the end of the season with about 100% humidity and precipitation. I hope you folks stay safe out there now — because it looks like this spell ain't going to be ending anytime soon, haw haw haw!

**Comment by NonQueueingMatt** [comment]
Fixed now, I'm pretty sure
