### ISSUE TITLE
Duplicating Items

### ISSUE THREAD

**Issue by YouJustGotOwened** [Aurorastation/Aurora.3#4130]
When an item is clicked on twice very fast it will sometimes just create a new item. I've only noticed it with papers and energy guns.

Able to be done with paper when you pick it up and it attach it to something quickly, then suddenly there are two pieces of paper. Same with the gun, when you pick it up and put it in your holster immediately after that, another one remains on the ground that you can pick up and fire. Happens infrequently, but it has definitely occurred more than once. 

Game ID: bSx-aD0V
Reported it to Alberyk

**Comment by Sindorman** [comment]
I do not see it now.

**Comment by dragoslava** [comment]
Did some testing around with this and couldnt replicate it, if it happens again somehow please make a report and outline how it happened
