### ISSUE TITLE
Acids dissolve Integrated Circuits' Hypoinjector circuit

### ISSUE THREAD

**Issue by LanceLynxx** [Aurorastation/Aurora.3#4141]
Acid reagents (Like Polynitric and Sulphuric) can normally be held by IE's Reagent Storage circuit, as well as be pumped by Reagent Pumps. But as soon as the acids are loaded onto the Hypoinjector circuit, the board vanishes into thin air.

Tested by manually loading acid from a beaker directly to the hypoinjector, as well as moving acid from Reagent Storage to Hypoinjector using the Reagent Pump. In both cases, the circuit simply vanishes. So there is no way to inject acids.

Since 3 Reagent boards can hold or manipulate acids just fine, and only the Hypoinjector dissolves, I assume this is a bug of some sort.

EDIT: I have since found out that some boards in the Reagents section will, in fact, dissolve. When more than 10u of a Sulphuric acid is added to any reagent board, such as reagent storage or cryo beaker circuit, said circuit will simply vanish from existence. So I guess, perhaps this has been an oversight, since reagent boards have to.. well... deal with reagents? Or not? I don't know if it is intended behavior or not.

**Comment by Geevies** [comment]
Intentional.
