### ISSUE TITLE
Science Sublevel external airlock air cannisters (Xenoarcheology, Toxins)

### ISSUE THREAD

**Issue by LanceLynxx** [Aurorastation/Aurora.3#4145]
Xenoarcheology and Toxins airlocks leading to the asteroid have air cannisters that are not fully filled with air. This leads to airlocks cycling at most two times before the cannisters run out of air, and then airlocks won't properly cycle and usually have to be forced or hacked open. Or someone will have to go to Atmos to get new Air cannisters. Same behavior is not seen in other cycling airlocks such as Mining, so I believe this is a mapping oversight.

**Comment by TheGreatJorge** [comment]
Doesn't seem to be an oversight. There is subtype of air canister for use in external airlocks which seems to be used indeed, everywhere where airlocks are.
While normal air canisters are set to hold `start_pressure = 45 * ONE_ATMOSPHERE`
The airlock ones have `start_pressure = 3 * ONE_ATMOSPHERE`

I guess the difference has something to do with piping itself? How long are the airlock pipes to canisters. How many vents there are. And such. I'm just guessing on that front though.

**Comment by Asheram** [comment]
To my knowledge the vents doesn't _quite_ empty the room before opening outwards either, I might be mistaken, but it's one way to keep losing air

**Comment by GutsySS13** [comment]
I can confirm that this is still an issue. I get around it partially by getting the air cannister from anomoly storage and replacing one of the tanks. I think the big issue is that the airlock does not cycle correctly. Yesterday when i went out there was 6kpa left in the air, and when i came back in about a min later the reading was up to 26kpa.... very strange. I went in and out again and took this snapshot of the kpa left (4) and you can clearly see the vents have stopped cycling. https://raw.githubusercontent.com/GutsySS13/shared-stuff/master/airlock1.jpg

This seems to be the case wether you use the console to cycle external or press the pressure censor (that also performs a cycle).

This small amount of air seems to keep knocking you over randomly, although that takes a couple of mins to start happening (I guess the air is distributing all over the place).

**Comment by Sindorman** [comment]
This does not seems to be an issue, as the pipe leading to both canisters and airlock is connected to the main air supply pipe, which will re-supply it with air all the time. I can say it can be closed

**Comment by Sindorman** [comment]
![2018-04-30 1](https://user-images.githubusercontent.com/25555314/39441179-f6a4b486-4c61-11e8-94c8-6858bc2ed21f.png)
