### ISSUE TITLE
Exodus mine mixes rocky and non-rocky ash

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#4152]
Doesn't really cause any issues, just looks ugly.
![2018-01-26_09-21-51](https://user-images.githubusercontent.com/7097800/35446446-5ceac80c-027a-11e8-9956-85c37b3feb62.png)

**Comment by LordFowl** [comment]
Isn't rocky ash dynamically generated? I don't see how this is mapping related.

An another note, maybe natural smoothing tiles could smooth into one another?

**Comment by Lohikar** [comment]
Well, it's mapping related in that the non-rocky path could be updated to the rocky variant. I forget if exodus got updated with the new asteroid turf path. Might look into smoothing between the two.
