### ISSUE TITLE
IPC's can feel bullets in their chest moving and causing damge.

### ISSUE THREAD

**Issue by SebkillerDK** [Aurorastation/Aurora.3#4167]
I was messing around in the thunderdome with the admins testing the new IPC's i was then shot and had a bullet imbed in my chest as the new mobility frame. when i moved, it said i could feel the bullet in my chest moving, and irecieved damage.

Game ID: bSD-dm3F

**Comment by skull132** [comment]
Not a bug.

Shrapnel will still hurt IPCs. Suppose the message is a bit wonky, but you still have pieces of led embedded inside of you and your components, moving around and causing damage while doing so.
