### ISSUE TITLE
pAI inserted into a suit can't see output from toggled suit functions

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#417]
Basically if you swap the RCD as a pAI in a suit, you can't see the mode change in text.

Also it would be nice if the pAI could use the chemical injector as the host is the only one that can activate it once selected.

**Comment by LordLag** [comment]
Hardsuit AI stuff is kinda borked to all hell afaik. Will need to have a serious look at it.

**Comment by NanakoAC** [comment]
I'm thinking this should be fixed via a wrapper function, message_suit, which should replace most user <<  messages

it'd send the message to both the user, and the installed AI, if any

**Comment by NanakoAC** [comment]
I found a better solution. Fixed in #869

**Comment by NanakoAC** [comment]
long since fixed, closing
