### ISSUE TITLE
Modular science lasers start with an electronic pin

### ISSUE THREAD

**Issue by Ezuo** [Aurorastation/Aurora.3#4172]
With the new modular science laser weapons, and the introduction of electronic firing pins, it would make sense that weapons built in science start with the test firing pin, or the science firing pin. This isn't the case, as any weapon created using the modular system has a regular electronic pin in it that can be fired anywhere. Tested on Lohikar's test server.

**Comment by Pacmandevil** [comment]
probably because Alberyk put `pin = null` in it?
