### ISSUE TITLE
Dr. Gibb's/soda shaken status reverts when put back into vending machine

### ISSUE THREAD

**Issue by alexpkeaton** [Aurorastation/Aurora.3#4178]
I shook up a can of Dr. Gibb.  I then placed it back into the vending machine via product receptor.  Then I bought the entire stock of Dr. Gibb.  None exploded on me.

Expected result: First/last/random purchased Dr. Gibb would explode on me.
Actual result: No Dr. Gibb exploded on me.

**Comment by Pacmandevil** [comment]
goes to the top, and presumably has enough time to deshakify.

**Comment by OneOneThreeEight** [comment]
imagine buying out an entire vending machine's stock of soda just to prank people who buy it

**Comment by Arrow768** [comment]
This is a design issue with the vending machines.
Before the item is vended / after it is reinserted it doesnt exist -> It only updates the item count.

I am not sure if its worth changing that.

**Comment by skull132** [comment]
Not worth fixing.

This is done to lower the amount of instances required. Changing it would waste too much memory to be worth it.
