### ISSUE TITLE
Merc shuttle dock exposed to space at roundstart

### ISSUE THREAD

**Issue by alexpkeaton** [Aurorastation/Aurora.3#4183]
In a round post-devmerge, the merc shuttle dock was exposed to space at roundstart - a window was missing.

Admins appeared to notice this issue as a window was eventually adminspawned in place for that round.

**Comment by alexpkeaton** [comment]
I just saw #4182.  That's what I'm referencing.

**Comment by Juani2400** [comment]
Alright. Closing then!
