### ISSUE TITLE
Nymphs cannot vent crawl

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#4187]
With the new update came new bugs!

When trying to vent crawl, it says 'This vent is not connected to anything'.  It most surely was, and it happened with every vent I tried. May be a round-based issue, we'll have to test if it happens every round.

**Comment by BurgerLUA** [comment]
Happened to me too as a mouse this round.

https://github.com/Aurorastation/Aurora.3/blob/94fe548cf7c331d05d08868b8b0d251ea763dc87/code/modules/ventcrawl/ventcrawl.dm#L165

Relevant code.

**Comment by Sebbe9123** [comment]
Bump since this is still a huge issue.

**Comment by MintyGums** [comment]
Bumping again

**Comment by TheTailson** [comment]
Adding to this. Was able to vent crawl no problem UNTIL I went to the AI core and ended up in the closed white-pipe loop behind the core. Since I got out of the white pipes, I kept getting the "This vent is not connected to anything" message.

**Comment by Geevies** [comment]
I believe this has been fixed. The message only pops up if the vents are no longer on.
