### ISSUE TITLE
Dionaea still do not regrow limbs

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#4188]
I cut off my hand first with a hatchet to test, waited about 10 minutes. It never repaired itself, I then cut off my full arm and waited again, it still refused to repair. I'd eaten plenty of nutriment to try and get it to activate as well.

**Comment by LordFowl** [comment]
After testing this is confirmed to be false. Please remember that for limbs to grow back you need to be irradiated as well.
