### ISSUE TITLE
Seeing Hivenet in Lobby, not ghosted

### ISSUE THREAD

**Issue by savvyII** [Aurorastation/Aurora.3#4195]
I have not tried to replicate this issue.
I was sitting in the lobby working on a new character when I noticed that in my chat I was seeing the Hivenet chatter. Here is a picture.
![dreamseeker_2018-01-28_13-52-29](https://user-images.githubusercontent.com/19510472/35486377-c4803880-0432-11e8-99ba-a4e6ad8963bc.png)
I had not ghosted at any point during the round and had been in the lobby since round start. I'm not sure what causes this, but my guess is something relating to whether or not you're considered dead in the lobby or if you're a ghost.

**Comment by LordFowl** [comment]
Likely broke something trying to make hivenet code more sane. Woops.
