### ISSUE TITLE
Cloned individuals have traumas incurable via surgery.

### ISSUE THREAD

**Issue by alexpkeaton** [Aurorastation/Aurora.3#4196]
Probably in addition to #4194.  Cloned individuals with traumas cannot be cured with surgery.  They likely have Alkysine on board but since I do not believe that alkysine affects traumas, this shouldn't have the effect #4194 is referencing (namely, if a chem is suppressing the trauma, surgery cannot cure it).  

I would suggest testing this by taking a cloned individual with a trauma and taking them immediately to surgery (before alkysine) and seeing if surgery worked.

Citalopram can suppress the traumas of a cloned individual, however when providing citalopram to a patient who had both a fear of skrell and an damage to the language center, citalopram only cured the fear of skrell and not the language barrier.  Not sure of this is a bug or not.

**Comment by LordFowl** [comment]
Citalopram is not a bug. Citalopram only cures minor traumas. First problem is possibly because there was no brain damage. Was surgery successfully performed, or merely impossible to perform?

**Comment by alexpkeaton** [comment]
I am not sure.  The players who know of this first hand include those who play Ali Holmes, B.O.B and Michael.

They attempted brain surgery, and I am not sure they could use the trauma kit on the brain.  However, they would be able to tell you for sure.

Does Paroxetine, the more powerful drug, work for major traumas in the way citalopram works for minor traumas?

**Comment by alexpkeaton** [comment]
It would make sense that there was no brain damage as they would have been given alkysine post-cloning and prior to surgery.

**Comment by HunterRS** [comment]
I was the one they were operating on, I was cloned and couldn't do anything for 30 minutes and then they asked to put me in cyro because all methods of surgery weren't working.
