### ISSUE TITLE
Xenomorph neurotoxin spit is unreliable

### ISSUE THREAD

**Issue by NonQueueingMatt** [Aurorastation/Aurora.3#4198]
It seems to randomly not work, also is quite bad since it brings up a popup menu asking you who to shoot at.

**Comment by Alberyk** [comment]
Might be related to armor, and no idea how to handle the popup in a better manner.

**Comment by LordFowl** [comment]
Xenomorph spit should be handle via middle-click, like eyeball lasers. I had this working sometime ago, where the ability would actually just toggle the middle-click functionality. It's relatively simple to implement @Alberyk

**Comment by Geevies** [comment]
Die, xeno, die.
