### ISSUE TITLE
Vote noise is both old and new sound

### ISSUE THREAD

**Issue by Killerhurtz** [Aurorastation/Aurora.3#42]
The old sound (the shitty alarming alarm) and the new one (the soft chime) play at the same time any time a vote is called.

**Comment by skull132** [comment]
Caching issue, I think. Not something we can fix by code. Delete your BYOND's cache under my documents/BYOND, I do believe. Lemme know if it works.

**Comment by skull132** [comment]
Cache issue, not a bug.
