### ISSUE TITLE
In inventory, bloody clothes/accessories do not appear clean after washing in a sink.  However, when worn or examined, they appear fine.

### ISSUE THREAD

**Issue by alexpkeaton** [Aurorastation/Aurora.3#4208]
My clothes became bloody after a melee fight.  I both sprayed the clothes with space cleaner, then washed them in a sink.  Neither appeared to clean the clothes/accessories.  However, on my body they appear fine.  If they are loose on the ground, they appear bloody.  The examine text does not indicate they are bloody, either examining my person or the specific items.  They just smply look bloody in my inventory.

See photos below.

![image](https://user-images.githubusercontent.com/15083944/35493680-243fca38-0483-11e8-90d5-108ea7dc5a6a.png)

![image](https://user-images.githubusercontent.com/15083944/35493699-3f3cf78e-0483-11e8-9b11-d74a52cdbec0.png)

![image](https://user-images.githubusercontent.com/15083944/35493723-698b6dcc-0483-11e8-931f-7678a68904dc.png)

What I expected: spraying clothes with space cleaner or washing in a sink would clean them
What actually happened: When worn, the clothes appear clean on my body, but still look bloody in my inventory or loose on the ground.

**Comment by skull132** [comment]
Update to reproduce. Probably fixed or otherwise resolved.
