### ISSUE TITLE
Some cell timers show the bluescreen of death and don't work.

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#4216]
The timers that show the blue screen don't work at all, although they still eat the paper with all the information on the subject's charges.

EDIT: The timers start the round like this.
![imagen](https://user-images.githubusercontent.com/6277887/35543311-5beadade-055c-11e8-8fe2-22a1e8a7d544.png)

**Comment by Arrow768** [comment]
The target list of the cell timers is empty.
Could be a mapping issue -> Please check if the .id variable of the door, flasher and locker and timer is set properly

**Comment by Arrow768** [comment]
Another option is that its a race condition caused by the recent changes to the startup order.
-> The lookup of the locker, door, flasher has to be changed to LateInitialize
