### ISSUE TITLE
Prototype laser weapons absorb firing pins.

### ISSUE THREAD

**Issue by Candelaio** [Aurorastation/Aurora.3#4217]
Make a prototype laser weapon, no longer has the normal simple electronic firing pin, understandable. 
The issue comes in when you insert a testing range firing pin, you insert it, fire a few times, find out the design you made is dog shit. Then you disassemble the weapon and the firing pin is gone. I expected it to be another component that would be in the pile of stuff that was the gun but it just disappears. 

In essence, adding a firing pin to a prototype gun means you will not be able to get it back when you disassemble it.

**Comment by Pacmandevil** [comment]
if it's a testing pin you can remove it with a screwdriver. but this isn't viable for non test pins.

**Comment by Lohikar** [comment]
Removing pins with screwdrivers is intended to be an in-case-of-emergency thing, no? There should be a better way for research guns.

**Comment by Alberyk** [comment]
Should force the pin to drop when you dismantle the design then.

**Comment by Pacmandevil** [comment]
Yeah, I was saying that more as a "Do this until it's fixed" thing. Proto. guns should probs drop the pin instead of destroy on Qdel/whatever it uses

**Comment by Candelaio** [comment]
Well, you see to disassemble the protoguns, you use a screwdriver so that means you cannot actually get the firing pin out before disassembly. Since using it just disassembles the weapon and the firing pin is nowhere to be seen. It used to be that when assembled they had a 'simple electronic firing pin' but now you must put a firing pin in and as stated, it doesn't drop on disassembly
