### ISSUE TITLE
RCON Interface not working properly

### ISSUE THREAD

**Issue by ElohiAdanvdo** [Aurorastation/Aurora.3#4218]
When I attempt to use the RCON console and select something from the list, it'll activate something _below_ what was selected, and if you try to move to what was turned on and reverse the activation, nothing happens. I've attached a screenshot to illustrate.

https://i.gyazo.com/981bae00e68ea712dad5d80728cf8c09.png

In the image, were you to select the first Substation - Medical Input, it would instead activate the second one's Input. And if you would try to turn off the second one's input, nothing would happen. You have to instead move back to the first one to do it, and go around and manually activate each Substation SMES manually. As you can see, it's a repeating pattern- no matter what, the second medical substation SMES cannot be messed with. Go to the first Substation - Research to try and turn it on, and it'll just activate the second instead. It's rather irritating, especially in a hurry at times to do a quick fix.

**Comment by flimango** [comment]
This is actually because the SMES' are named the same despite being on different levels. Previously, [F.3 - Research Substation] and [F.4 - Research Substation] are now both Substation - Research. Trying to modify either one will only modify the "primary" one.
