### ISSUE TITLE
Farwa / Monkey can't understand basic

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#422]
Perhaps it's intentional, but if someone is made into a farwa or monkey by virus means they cannot understand basic. They can however still use secondary languages like sign.

It is a little annoying to see 'bla' spam. Maybe they could -like on the old code- understand it but not speak it.

**Comment by skull132** [comment]
This all sounds fine. Language mechanics work like this.

Though my question is: how did you become a monkey/farwa who knew sign language?

**Comment by darkrising** [comment]
A monkey virus on one of my Tajara, they turned into a Farwa with sign.
