### ISSUE TITLE
Get Duty Log not working

### ISSUE THREAD

**Issue by sdtwbaj** [Aurorastation/Aurora.3#4223]
I select duty log.
I select my name
I select the log to grab
hit OK
nothing happens.

Apparently happens to @Alberyk too.

**Comment by skull132** [comment]
BYOND issue.

Usually what helps is setting a default program to open `.log` files with. You can do this by creating a `.log` file on your desktop, it should appear as an unidentified icon, and then double clicking it. Set it to open with something like notepad. If, after doing this and restarting BYOND, it still doesn't work. Then there's not much we can do atm.

I'll do some BYOND forum scouring and will issue a bug report there over the weekend.
