### ISSUE TITLE
Diner Wall Chairs

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#4225]
![image](https://user-images.githubusercontent.com/3950115/35613752-e37b6db4-06a7-11e8-94b1-6ebd2e6e0e1c.png)
![image](https://user-images.githubusercontent.com/3950115/35614020-9d06c5f8-06a8-11e8-8073-1bc5c1d403ce.png)

There are no tables.
Only walls.
We eat with walls now.
No tables.
With walls.

**Comment by Juani2400** [comment]
Being fixed in the next update.
