### ISSUE TITLE
Ability to walk on openturf as mech when elevator is missing / delaminated / gone.

### ISSUE THREAD

**Issue by Zelmana** [Aurorastation/Aurora.3#4244]
When entering engineering's elevator in a Durand, via blasting a hole in the elevator shaft, the mech was able to walk around on the openturf. When the elevator was called, the flooring (or what was left of the elevator flooring) rose to the main level. This resulted in the mech crashing. The elevator suffered from supermatter delamination, which may be a factor.

The lower level of the elevator shaft looked like so: https://puu.sh/zfshm/4a7f6847d9.png.
(Courtesy of prate who assisted mere
For log purposes, if you'd like to look at them, the round was: bsJ-dH2k

**Comment by NonQueueingMatt** [comment]
fixed by newmechs
