### ISSUE TITLE
Camera locations wrong on monitor's map.

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#4251]
As the title says, the camera locations are always misplaced.
The image shown below is the Security tab, which shows all camera in the Security network. Misplaced and shown to be in the middle of the station instead.
![imagen](https://user-images.githubusercontent.com/6277887/35773490-419108c2-094c-11e8-8c19-c1dd4f0e502f.png)

**Comment by KepQwet** [comment]
Also affects locations on the suit sensor monitor's tracking map.
