### ISSUE TITLE
Flamethrowers do not fire consistently

### ISSUE THREAD

**Issue by MobiusWon** [Aurorastation/Aurora.3#4253]
After creating a flamethrower and lighting it, regardless of pressure set the flamethrower is sporadic at best with spitting flame. Often times it will not even fire at all.

**Comment by JohnWildkins** [comment]
Unfortunately this is a ZAS issue, and unless someone wants to go through and completely rewrite atmospherics code, this is how it has to be.

**Comment by JohnWildkins** [comment]
okay actually I lied there is a definite issue with flamethrowers that isn't related to ZAS, fixing now
