### ISSUE TITLE
E-Sword Cigarette-lighting Incorrect

### ISSUE THREAD

**Issue by Ornias** [Aurorastation/Aurora.3#4258]
Using an E-Sword to light a cigarette will always display the text that implies the cigarette is in your mouth, regardless of where about it actually is on your person.
![330fc791067cdd76d1b5012508373900 1](https://user-images.githubusercontent.com/20852677/35844233-57f4e5bc-0b71-11e8-9a70-cc3652d33f99.png)

**Comment by OneOneThreeEight** [comment]
GEE I THOUGHT E-SWORDS WERE HARDLIGHT 🤔
