### ISSUE TITLE
Drinks made of "nothing", probably needs deletion?

### ISSUE THREAD

**Issue by soryy708** [Aurorastation/Aurora.3#4268]
Looking through https://github.com/Synnono/Aurora.3/blob/092e35d34c08e4d4df5d7a6a9e1d373d501fdd93/code/modules/reagents/Chemistry-Recipes.dm
looks like there are a few drinks whose ingredient is "Nothing".

Is that intentional?
If not, perhaps it should be removed.

**Comment by Pacmandevil** [comment]
It's intentional

**Comment by Alberyk** [comment]
It is a reagent, not a bug.
