### ISSUE TITLE
RIG Thermal Drill bug

### ISSUE THREAD

**Issue by YuriDaruski** [Aurorastation/Aurora.3#4271]
Should a miner mod-press a Thermal Drill to be used in a RIG suit, and then move during the charging process, the drill becomes stuck in a never-ending charging cycle, never to be fired again. A message of "The mounted thermal drill is already charging" will flash across the screen no matter how long one waits. switching in-between modules of the RIG, such as to a different drill, does not fix the issue. I for one like the fact that you can now cancel the charge, having accidently shot people trying to switch hands with middle mouse, however it now makes the drill unusable. While the KA remains the most cost effective, and effective entirely really especially with the upgrades. the thermal drill is an interesting alternative.

**Comment by YuriDaruski** [comment]
Removing the module and reinserting it doe not fix the issue either.

**Comment by Lohikar** [comment]
This is true of the non-mounted thermal drill as well, I believe.

**Comment by skull132** [comment]
Fixed by now.
