### ISSUE TITLE
Cannot actually upgrade thermoelectric generators properly

### ISSUE THREAD

**Issue by Cairo283** [Aurorastation/Aurora.3#4286]
It seems that you can't actually upgrade the thermoelectric generators, or even deconstruct them, like you would most other machines that use parts. Since the addition of build-able advanced thermoelectric generators some months ago to R&D, I assumed that you would be able to deconstruct the ones in engineering that are already present to replace their parts and circuit boards with the advanced versions, but attempting to use any tool on them will simply result in the person trying to use the tool hitting the generator, doing nothing.

**Comment by Lohikar** [comment]
I don't believe they were added to RnD? You might be thinking of the radioisotope generator, which is completely unrelated.

**Comment by Cairo283** [comment]
Ah, pardon me, I am mistaken, yes. If I knew how to delete these threads I would.

**Comment by Lohikar** [comment]
Can't delete issues, just close them if they're invalid or fixed.
