### ISSUE TITLE
miners earn a ridiculous amount of income from spending all of their mining points on credit vouchers and lottery tickets

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#4288]
this creates a disproportionate income issue. might be wise to tilt it into the house favor more to further drive miners into statistical squalor

**Comment by Sindorman** [comment]
Agreed - miners have choice of either buy a lottery ticket for 200 points or use 1000 points to get 100 credits. If they choose to buy lottery ticket on average they get 200-700 credits. Which makes 1000 points for 100 credits useless at all. 
**At this point according to 1000 to 100 credit. 10 points is 1 credit. That is the ratio**
Then lottery ticket winning credits should range from 20 to 150 credits?

**Comment by Alberyk** [comment]
Best solution would just removed money and maybe tickets from the vending machine, or limit them.

**Comment by Arrow768** [comment]
Its somewhat dealt with in #4294
