### ISSUE TITLE
Xion frames can't wear voidsuits when they should be able to

### ISSUE THREAD

**Issue by ghost** [Aurorastation/Aurora.3#4308]
After trying to EVA as a Xion with an engineering voidsuit I got 'Your species cannot wear the engineering voidsuit.' This doesn't apply to the generic spacesuits and its the only way I've found to EVA with this frame.

**Comment by Lohikar** [comment]
Xion frames (nor any industrial frame) aren't supposed to be able to wear voidsuits. It working on spacesuits is a bug.

**Comment by MasterJJ99** [comment]
I've tested it with only a suit cooler and it caused an overheat. Both the wiki and the blurb says it should be able to

**Comment by Lohikar** [comment]
The blurbs are incorrect then. The intended design is that industrials cannot wear normal EVA suits, with the eventual plan being to add specialized ones.

**Comment by SirFruitcakes** [comment]
As per Cakes words when I asked them this is a bug and Xion Industrials are meant to be able to wear Voidsuits and so the wiki is correct at the moment. Chada1 here.

If being an Industrial is an issue (My own suggestion) you could make them a subspecies of regular and just called 'Industrials' in Lore even though they are more like regular IPC frames with heightened mobility and armor.
