### ISSUE TITLE
Building a table frame produces a plastic table, inflating the plastic economy due to the ability to create infinite plastic sheets

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#4310]
When you build a table frame, the table becomes a plastic table right off the bat, you can then wrench it to get a plastic sheet, and again to get a steel sheet, which you can continue to do until Tau Ceti no longer as a dependency on making plastic.

**Comment by Alberyk** [comment]
Duplicated.
