### ISSUE TITLE
Wiring to the Surface Level's roof does not line up, surface level solar maintenance not powered.

### ISSUE THREAD

**Issue by EJDenton** [Aurorastation/Aurora.3#4311]
The Surface Solar Maintenance, the one above the cargo bay, never connects to the powernet. I followed the cables and removed the lattice on the south end of the roof where the cable turns down. Looking down I saw a steel wall below me. I went to the surface level and verified by moving up and down with a jetpack that the wire turns down into an exterior steel wall.

EDIT: Additionally, where the red main line runs past the yellow solar line just outside of the maintenance room, the two wires are actually registering as connected. So if the solars are online they will provide power straight into the main line in addition to just going to their SMES.

**Comment by Arrow768** [comment]
Would you post some pictures of the issue please.
Mapping issues are usually explained best with pictures

**Comment by EJDenton** [comment]
OK. I was able to get some pictures.

This first picture shows the wiring from the roof going down into the surface level of the station.
https://imgur.com/a/8LhUe

In this second picture, I stood where the cable ended in the first and moved down a level. You can see that there is just a wall beneath the wire.
https://imgur.com/a/ORLiW

This last picture shows where the solar and main wires cross. I did some troubleshooting and verified that they are counted as connected in this configuration. This means that solar power will go directly into the main grid and bypass the solars' SMES unit.
https://imgur.com/a/yhKHO

**Comment by ProbablyMenown** [comment]
This is still broken.

**Comment by Sindorman** [comment]
Was fixed
