### ISSUE TITLE
The effects of tourettes are not even close to how it works in real life.

### ISSUE THREAD

**Issue by chaoko99** [Aurorastation/Aurora.3#4315]
I work along several people with Tourettes symdrome,  and have had a history with them for quite some time. People with tourettes don't cuss constantly, they screech and bellow and make unpredictable movements.

The tourettes stereotype comes from an episode of south park, wherein Cartman fakes "symptoms" in order to get away with cussing teachers out.

I'm not trying to white knight the tourettes folk, but I did put input forwards on the traumas system so that it may be at least mildly accurate.

**Comment by Pacmandevil** [comment]
keep in mind that the brain damage system is supposed to be exaggerated.

**Comment by LordFowl** [comment]
As this issue report does not even border on being an actual code issue, I recommend posting a suggestions thread post. The github is designed solely for fostering discussion on bugs and oversights in the code, whereas the forum is designed for discussion on content change.

**Comment by MarinaGryphon** [comment]
This concern was brought up and ignored before the PR was merged. I don't think you'll get much from Fowl in the way of realism, as this was an issue before with the cyborgification-preparation surgery, even when several members of staff agreed on it.

**Comment by Alberyk** [comment]
I believe that tourettes should be disable from the random traumas you can get with brain damage.
