### ISSUE TITLE
Chemmaster 3000 may not be available in circuit imprinter

### ISSUE THREAD

**Issue by alexpkeaton** [Aurorastation/Aurora.3#4320]
I asked for a Chemmaster 3000 (pill machine) board at R&D and despite research apparently being completed, the board was not available to be printed.

**Comment by dragoslava** [comment]
In the future they can print these boards but as of current, they aren't able to.

Its a feature being added here for in the future https://github.com/Aurorastation/Aurora.3/pull/5976
