### ISSUE TITLE
Gravity checks are inconsistent

### ISSUE THREAD

**Issue by Lohikar** [Aurorastation/Aurora.3#4323]
There seems to be 2-3 different ways to check if an area is affected by gravity, but only one is actually controlled by the gravity gen. These should be merged.

**Comment by MarinaGryphon** [comment]
I can confirm this. It's resulted in the undoing of one of my previous fixes for a very, very old bug.

**Comment by MarinaGryphon** [comment]
May actually be fixed by #4591.
