### ISSUE TITLE
After many a hour of searching for the Surgery Holosigns, I finally find it invisible, when pressed, doesn't stay on.

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#4327]
After it is pressed once, it shows again, but doesn't stay on, clicking it again enables the sign, makes the button invisible, and then turns off the sign revealing the button again.

![](https://i.gyazo.com/e9d28a95d0e7c2920032ce78e0fd68ec.gif)
EDIT: AFTER SPAMMING the button a bunch of times by alt-clicking the tile, it finally works and stays on. very finicky

**Comment by XanderDox** [comment]
Are surgery holosigns still a thing on numapmed?

**Comment by dragoslava** [comment]
Works fine as of now, the new map also does not have these signs
