### ISSUE TITLE
Telepathy not working correctly?

### ISSUE THREAD

**Issue by alexpkeaton** [Aurorastation/Aurora.3#4328]
I was a blood raged vampire and was in a cryotube during a rad storm, gaining telepathy.  A mod (ToasterStrudels) confirmed this on my player panel.  However, I was unable to use the ability.

Here is a screenshot of the tabs I saw.  I wonder if "Vampire" overrides "Powers" in the code.  I should have had both tabs.

![image](https://user-images.githubusercontent.com/15083944/36655493-fdedd734-1a90-11e8-814e-025c64383ace.png)

What happened: Picked up telepathy during a rad storm, was not able to use it.  Was also hulked and a vampire.

What should have happened: Able to use telepathy, despite being a (hulked) vampire also.

**Comment by Pacmandevil** [comment]
I don't think that telepathy gives a powers tab. you might be thinking of the radio mind thing that viro can get.
