### ISSUE TITLE
Cancel option does not seem to work for CCIA/DO functions

### ISSUE THREAD

**Issue by Bedshaped** [Aurorastation/Aurora.3#433]
When you try to use "Create Command Report" and "Spawn CCIA Agent" in Special Verbs and press Cancel it seems to just do it anyway.

**Comment by Bedshaped** [comment]
For the "Create Command Report" you have to say Ok to the message body, but Cancel for the title body for it to send anyway.

**Comment by skull132** [comment]
Resolved.
