### ISSUE TITLE
Uninsertable circuit board - sleepers

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#4334]
![default](https://user-images.githubusercontent.com/18286472/36705996-af22978a-1b89-11e8-90d3-f8f98e0c5362.png)

circuit board (sleeper) - is not being supported either by machine frame or computer frame. On both variants sends a "This frame does not accept circuit boards of this type!" message as a result.

Talked to a dronedmen via looc, did receive a recommendation to report this over github.

**Comment by printer16** [comment]
Not really a bug. It's not meant to be built.

**Comment by HetNeSS** [comment]
Why is there a circuit board for it then?
