### ISSUE TITLE
Tajara Hulks Can't Send People Flying

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#4353]
Vampire round. Went hulk as m'sai tajara and relied on knockback effect to escape, clawing two dudes that were chasing me. It literally did nothing and got me killed eventually as I spammed it, bewildered.

If it matters, I broke my handcuffs two seconds before this. Humans and so on can hulk smash just fine. But tajaras? They just scratch. What gives?

**Comment by Pacmandevil** [comment]
Inferior tajara muscles

**Comment by Alberyk** [comment]
I tested and it does happens, you only had bad rng luck.
