### ISSUE TITLE
The Corporate State of NanoTrasen Brutally And Excessively Inhibits Its Citizens From Rudimentary Privileges

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#4355]
_DOODOOT-DOO-DOOT-DOOTOO-DOOT-DOO_
![image](https://user-images.githubusercontent.com/3950115/36934147-f80375a2-1f1f-11e8-9a6c-5c507ceede84.png)

Good morning, and welcome to Romanovich Reports at 8; I'm Sarah Sarington.
After numerous complaints from civilians and workers across the system, the Corporate State of NanoTrasen Corporation is faced with legal claims held against them by its people. The complaints entail the **UTTER, _DISGRACEFUL_** lack of mechanism to access the Automated Teller Machine (ATM) machine located in Odin Point. Elizabeth Elizabethington reports from the field:

![image](https://user-images.githubusercontent.com/3950115/36934280-ea9d1fba-1f21-11e8-939b-e6c55e60f03b.png)

Hello, yes! I am Elizabeth Elizabethington. As you can see, I am on the unsimulated ground here at the Odin Point departure arrival checkpoint, and here we have the heinous Corporate Banner that represents the State _maliciously_ obstructing convenient means of using this poor, innocent wall-mounted device.

![image](https://user-images.githubusercontent.com/3950115/36934313-64b5b758-1f22-11e8-9335-92d7e11abe31.png)

As you can see in clear view, such an impugnable act has been enacted upon the actors of the Corporate State whereupon they are outright **INCAPABLE** of accessing the Automated Teller Machine machine _with any form of convenience._ People are **FORCED** to attempt to use the hapless machination THROUGH the banner! Unbelievable!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Back to you, Sarah.

Oh, how horrible, Elizabeth Elizabethington! What an absolute moment of barbarism from the Corporate State! There is no mistake about it: the Corporate State of NanoTrasen is LITERALLY barring people from acquiring their innocent, virtuous money, lest they make such deposits and withdrawals through the corporate schemes!

What-... What's this...?!
...It seems I have just received breaking news from the field team. It seems that not only is this oh-so-called glorious nation preventing its denizens from managing their monetary assets, but they have also failed to place such means of access to its hard-working workers at the departure ports. We will now switch to LIVE! footage of the scene. Elizabeth?

![image](https://user-images.githubusercontent.com/3950115/36934196-e8a38eac-1f20-11e8-943e-8063c301896a.png)

Hi, yes! I'm Elizabeth Elizabethington. Thank you, Sarah! As you can see — not even a mere twenty metres away lies the sacred grounds of Odin Point's arrivals departure checkpoint — NanoTrasen Corporation has FAILED to place any means of financial aid or system within the area, forcing its citizens to go through **PAID LABOUR!!!!!** before they may be allowed to utilise any of these vending machines they have placed here.

![image](https://user-images.githubusercontent.com/3950115/36934436-4fd440aa-1f24-11e8-85e4-60bdda91a8bb.png)

It is a shameful, cruel torment that the Corporation has placed, without a doubt a contemptible way of TAUNTING depraved individuals, for they have no choice but to paw helplessly at the vending machine, unable to pay for any of its delightful, oozing products beyond the glass. It is a **WASTE** of resources, and a **WASTE** of basic morality! What has this galaxy become?!

Oh my, Elizab--

**BUT THAT'S NOT ALL, SARAH!**
A quick walk-around reveals how such individuals are _not even granted the privilege of privacy!_

![image](https://user-images.githubusercontent.com/3950115/36934548-7ecbb918-1f26-11e8-9574-28cd63305781.png)

As you can BLATANTLY perceive, this airlock has been modified to allow any horrific voyeur to lay their beady eyes into the bathroom, where not even any legislation has been taken to supply the bathroom with curtains from the shower!

![image](https://user-images.githubusercontent.com/3950115/36934578-df778d5a-1f26-11e8-9f76-7d47f325be9a.png)

_OH THE HUMANITY!_ WHAT HAVE WE BECOME?! Humiliated persons have to _CLOSE_ the airlock before there is even a _CHANCE_ of FINALLY achieving opaqueness with this devious, evil airlock!

_My God._ What have we become indeed, Elizabeth. What have we become...
...And now, Gucck Guccksington with sports!

**Comment by kevinz000** [comment]
This is amazing.

**Comment by SirFruitcakes** [comment]
I appreciate your humor Mwahaha.

**Comment by Mwahahahaha** [comment]
Good noon. I'm Gucck Guccksington.

The 21th JWF Skrellian Oil Wrestling Deathmatch tournament has just kicked off here in Tau Ceti with a one-on-one match between all-time champion Morlan Aramaud and newcomer felon Trysh Vu. Here we can see the match going on right now, as you can see.

![image](https://user-images.githubusercontent.com/3950115/38458379-52f54636-3ad0-11e8-8abe-0b714a4e4694.png)

Crowds from all around the system have flocked to witness the tournament, with tickets _already_ being sold out. Not to worry though, folks: you can tune in to our exclusive channels for continued footage! That's on channels 56af, 56b0, and 56b1. That's 56af, 56b0, and 56b1!

In other news, the 2460 Annual Spelling Bee competition between the Wanna-Bees and the Succu-Buzzes is underway.

![image](https://user-images.githubusercontent.com/3950115/38459031-2cec1bf2-3ad7-11e8-962f-1a47638e0956.png)

As you can see here, contestants are engaged in an intense Spelling Bee session with the initial Gunfight stage. Just to remind you folkerinos of what the rules of play here are: each team is required to engage in a firefight with the other team, and the remaining two survivors are then selected to determine who will officially be the next Hive Master, serving as a bee capable of high intellect as well as high combat efficacy.

![image](https://user-images.githubusercontent.com/3950115/38458863-7522f500-3ad5-11e8-88d6-7a4de856153a.png)

...Aaaaaaaaand that's really about it for the news because who needs sports when you've _got holographic virtual reality full immersive dash- I mean it's not like we need to be exercising our physical bodies or anything or keep our ganglia from turning into goop who even still watches sport news these days honestly I mean what is there even to sho-_

**Comment by soryy708** [comment]
Shouldn't this be in the "minor map suggestions" topic in the forums?
