### ISSUE TITLE
IPC Limb Re-attachment Causes Crashes.

### ISSUE THREAD

**Issue by BathSaltsAddict** [Aurorastation/Aurora.3#4363]
Encountered a strange bug where re-attaching a Zeng-Hu Mobility Frame's limbs causes a client-side crash of all online players. Unknown how to replicate exactly aside from braining a Zeng-Hu IPC and cutting off all it's limbs. Traitor roboticist did some weird shit.

**Comment by Alberyk** [comment]
I think this was fixed, due to being a byond issue.
