### ISSUE TITLE
Crematoriums not opening after being blocked

### ISSUE THREAD

**Issue by JoeTheBroseph** [Aurorastation/Aurora.3#4364]
If a crematorium is blocked from being opened, it will never ever open again unless it is replaced or the round restarts. This is in xenobiology, I'm not sure if it's occuring anywhere else but I haven't heard of it happening elsewhere yet. This has happened twice in two different sessions, so I don't think it was an exclusive glitch.

**Comment by SebkillerDK** [comment]
I can confirm this being a thing, i have seen it happen multiple times.
