### ISSUE TITLE
Security helmets mess with baseline IPC screens.

### ISSUE THREAD

**Issue by BathSaltsAddict** [Aurorastation/Aurora.3#4365]
Putting on a a security helmet as an IPC makes your screen disappear, which did not previously. Possibly a side effect of some change involving human hair and helmets.

For reference, an IPC without a helmet:
![image](https://user-images.githubusercontent.com/23310890/37183123-25371e56-22fa-11e8-961d-fd92f03a0c75.png)

An IPC with a helmet:
![image](https://user-images.githubusercontent.com/23310890/37183135-354d8d16-22fa-11e8-9aad-4f8b4c032905.png)

An IPC with a helmet wearing glasses:
![image](https://user-images.githubusercontent.com/23310890/37183151-452b93fe-22fa-11e8-8f6f-66d42000b8d0.png)

**Comment by Alberyk** [comment]
Fixed already.
