### ISSUE TITLE
Hardsuits / Rigs / Gloves (Covering Items) eat shoes / rings

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#4379]
After using a hardsuit or rig your shoes will vanish into bluespace. They leave a ghost icon (and ghost code) of shoes-past on the UI and game logic however by all purposes they're gone.

Equipping another pair of shoes over the ghost shoes does work aswell.

**Comment by Alberyk** [comment]
Also happening with magboots, and rings with gloves.
