### ISSUE TITLE
Machine Attack Types Missing

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#4392]
Machines are unable to access more than one attack type. Realistically, all of them should be able to stomp and kick. Shells should arguably be able to use bite as well. 
![attack types](https://user-images.githubusercontent.com/24979527/37258694-e4203f7e-2551-11e8-9e0a-d734cc095505.png)

**Comment by JohnWildkins** [comment]
Fixed by #6986
