### ISSUE TITLE
Xenomorph Queens, and possibly all Xenos do not properly heal damage.

### ISSUE THREAD

**Issue by Bygonehero** [Aurorastation/Aurora.3#4394]
Xeno queen or all Xenos, in general, retain burn damage and don't heal it, also doesn't count towards being in unhealthy but counts towards crit. This means if you ever get shot by anything and heal the actual damage, your pain remains the same. So when UristMc Loser hits you with his stun stick its as if you had all that pain damage and you get stunned FOREVER.

**Comment by Alberyk** [comment]
That is probably due to alien queen having more hp than your regular spessmen.
