### ISSUE TITLE
pAIs can understand Vaurca hivenet without an universal translator

### ISSUE THREAD

**Issue by Joonasm** [Aurorastation/Aurora.3#4401]
While playing as a pAI you can see the vaurca hivenet regardless of having universal translator on or off

**Comment by XanderDox** [comment]
The Hivenet is meant to be intercepted by station synthetics, such as androids, the AI, cyborgs, etc etc.

It is possible this is a leak of the code for those roles leaking into the pAI.

**Comment by Karolis2011** [comment]
Test & Todo for #6814
