### ISSUE TITLE
CMO Office Missing Utilities

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#4403]
The CMO's Office is currently missing its request console, and it's emergency swiper (for code red/ERT) .

This obviously is making it impossible for CMO's to make desk announcements (forcing a run to the bridge) and makes it impossible for them to help call for code red or ERT.

**Comment by Alberyk** [comment]
![cmooffice](https://user-images.githubusercontent.com/11579997/37301512-82b4c26c-2607-11e8-9669-7d51130e75fd.png)

Seems to be fine on live.

**Comment by XanderDox** [comment]
Must've been fixed in a hotfix since the last time I played. Good to know. This can be closed then!

Although the request console should be moved or rotated considering the sprite is faced the maintenance tunnel :P
