### ISSUE TITLE
Admin Spawn for Walking Mushrooms doesn't work

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#4408]
Admin tried to spawn me one, the only available mob for it either didn't spawn, or spawned invisibly. See Flimango for more details.

**Comment by tedwood3** [comment]
I'm not able to replicate this issue?
![image](https://user-images.githubusercontent.com/2719189/37573705-ecb3cba6-2b6e-11e8-90ff-389f4eb70d59.png)

**Comment by tedwood3** [comment]
Was this and #4408 patched already? I'm unable to replicate.
![image](https://user-images.githubusercontent.com/2719189/37574013-bd6f5dc6-2b71-11e8-9a0c-9adb85c82ca3.png)
![image](https://user-images.githubusercontent.com/2719189/37574015-c052a214-2b71-11e8-9b86-1c8299cfd7bf.png)

**Comment by XanderDox** [comment]
Contact Prate. He was the admin online at the time.

**Comment by Arrow768** [comment]
Seems to have been resolved.
