### ISSUE TITLE
Virology Analyzer Report: Baystation Species Names

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#4418]
When printing out a virology report for a virus, sometimes the report will say that the virus affects:
Grav-Adapted Humans
Vat-Grown Humans
Space-Adapted Humans

These are bay-species of humans and do not exist in the Auroraverse.

**Comment by XanderDox** [comment]
Would be fixed by Virology Report Fix #4452
 Will be mostly fixed by this. Since Vaurca breeders technically do exist in our lore, I suppose it's OK for them to be recognized under our system.

**Comment by Lohikar** [comment]
Issues are closed when the fix is merged, not before.
