### ISSUE TITLE
Grass and Carpet Tiles

### ISSUE THREAD

**Issue by Urthrem** [Aurorastation/Aurora.3#4426]
Hi, so I have noticed that carpet and grass tiles do set rather odd pattern when you place them, not joining together when placed next to one another, even if with admins help and instead they appear as if they were badly combined together.

https://gyazo.com/01b1e60d512b567b371d2161e2c6f686

**Comment by JohnWildkins** [comment]
Still an issue. Best solution would be to port the Bay version of carpet/grass.
