### ISSUE TITLE
Farmbot issues

### ISSUE THREAD

**Issue by Moltenkore** [Aurorastation/Aurora.3#4428]
- Sometimes get stuck doing one task such as watering without any water in the tank. (same issues #3868 #3822 #3456), turning the farmbot on and off doesn't solve this as it'll still try and do the same task it was doing.
- Ignore settings such as the on/off watering plants (perhaps the other settings too?).
- Sometimes try to get to an impossible target (through an airlock or window).
- Refilling nutriment option doesn't actually do anything (Probably settings issue).
- Weeding plants option doesn't do anything (Probably settings issue).

**Comment by Sindorman** [comment]
All of issues are fixed. Except getting to a target which is a generic problem of all bots, but farmbot uses Astar so it should not be an issue
