### ISSUE TITLE
Basic webbing issue

### ISSUE THREAD

**Issue by AmoryBlaine** [Aurorastation/Aurora.3#4439]
Basically the basic webbing is slightly off. So basically the front view of the basic webbing should be slightly moved over to make it line up properly with the basic human sprite.

**Comment by Mwahahahaha** [comment]
Dim b As String = "To basically demonstrate: the basic north icon is basically a basic pixel off the base of the human's base on the basic human icon, if I am not off base."
MsgBox(b)


![image](https://user-images.githubusercontent.com/3950115/41988601-3fae1d4e-7a6f-11e8-831f-ee8b9af07b27.png)
