### ISSUE TITLE
Unathi cannot wear brass knuckles.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#4440]
Title. Unless there is some lore thing where unathi have 4 or 6 fingers, this is likely a bug.

**Comment by Alberyk** [comment]
Not a bug. Unlike other gloves, you can't really clip a brass knuckles, neither they would really fit the alien hands since they were clearly made for more human like hands.

**Comment by BurgerLUA** [comment]
Unathi can't wear human gloves because of the fingertips, hence the fact that you can cut off the fingertips off of gloves and they fit fine without penalties.
Seems to be 0 reason why Unathi or other races can wear brass knuckles.

**Comment by Alberyk** [comment]
Not a bug, but a design choice.
