### ISSUE TITLE
Winning the jackpot from a lottery ticket says you win 0 credits, not 50,000

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#4441]
![lottery](https://user-images.githubusercontent.com/31339047/37562265-ade15cf2-2a3a-11e8-8013-2e371da9f205.png)

What the title says, the card still holds 50,000. Done it twice, got the same result.

**Comment by BurgerLUA** [comment]
>done it twice

LOTTERY NERF INCOMING

**Comment by BurgerLUA** [comment]
This was fixed.

**Comment by LordFowl** [comment]
@BurgerLUA When you fix a bug in a PR it falls upon you to say in that PR:
"Fixes #4441" or the equivalent for the relevant bug.

This way github will automatically close the bug report.
