### ISSUE TITLE
horizontal people still won’t fall with active magboots

### ISSUE THREAD

**Issue by sdtwbaj** [Aurorastation/Aurora.3#4443]
trying to throw someone, shove someone, move someone off a ledge while they’re horizontal won’t work with active magboots

to reproduce:
activate magboots on dummy
kill/KO/drug/horizontal dummy
grab, try to throw over edge
doesn’t work

**Comment by tedwood3** [comment]
I feel like that's a feature. Someone wearing active magboots would still have them grab the floor, wouldn't they?

**Comment by JohnWildkins** [comment]
magboots are magboots
