### ISSUE TITLE
Shooting mouth does no damage

### ISSUE THREAD

**Issue by hackiemhan** [Aurorastation/Aurora.3#4447]
When firing a sawn-off double barrelled shotgun point-blank at another character, both shots hit the mouth. However, neither of them did damage. I am not sure if this changes with other weapons, or if there was another factor. I am not able to replicate it in-game because it happened during an antagonist situation, and these can be difficult to replicate.
[Game ID: bTs-aAXO]
![slugs](https://user-images.githubusercontent.com/25730804/37581104-3dac40bc-2b04-11e8-96f5-5c637320cd57.png)

**Comment by tedwood3** [comment]
I was able to replicate this. I'm gonna have a go at patching it.

![image](https://user-images.githubusercontent.com/2719189/37583876-69b3355a-2ba7-11e8-9eb2-50564c75d8da.png)
60 brute damage from head shot
0 brute damage from mouth shot

**Comment by tedwood3** [comment]
The issue isn't that you can't shoot the mouth. It's that you can!
