### ISSUE TITLE
Pipes visible in the Security boxing training room.

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#4450]
![imagen](https://user-images.githubusercontent.com/6277887/37624067-c78714c8-2bbe-11e8-8290-7f8518e25157.png)

I remember checking for this bug, and the pipe type seemed correct. Not sure what the issue might be now.

Update as per Lohi's comment: Floor type seems to be the problem. If it's not clear enough, the floor shouldn't be holofloor. It would be appreciated if whoever fixes this readds the fake-stairs on the two tiles in which the firelocks are, given that I removed them to see if that turf type was causing the issue.

**Comment by Lohikar** [comment]
![2018-03-19_16-50-47](https://user-images.githubusercontent.com/7097800/37624324-c0fdecea-2b95-11e8-887b-10fa86a0a0e3.png)

**Comment by Arrow768** [comment]
Reported as fixed
