### ISSUE TITLE
Imaginary friend trips mute for say AND ahelps

### ISSUE THREAD

**Issue by resilynn** [Aurorastation/Aurora.3#4454]
It seems that, as imaginary friend, every fourth thing I say trips the spam filter, no matter how much time I put between what I say.  If I try to ahelp about it, that gets tripped too.  NursieKitty, ShameOnTurtles, and Euzo helped me get through about 30 minutes of one round like this and had to keep unmuting me as I cried for help over discord.

**Comment by SebkillerDK** [comment]
I remember this happening on another round, Flamingo and myself had to constantly unmute the imaginary friend because it kept tripping the automute by simply talking, no matter how slow or fast they were speaking.

**Comment by tedwood3** [comment]
TehFlaminTaco and I are looking into a fix. Current theory is last_message_time isn't being set for imaginary friends, making all messages come through at once (at least as far as the server's concerned. )

**Comment by Juani2400** [comment]
Bumping this. Still happens, and makes the role unplayable, plus it's a nasty chore for the modmins to unmute a person every minute. @skull132 If you guys can take a look at it, please.
