### ISSUE TITLE
Character preview prosthetics not updating

### ISSUE THREAD

**Issue by gelza1** [Aurorastation/Aurora.3#4459]
While trying to set up a new character, I discovered that, despite my settings, my character was being displayed (in the "Preview") with prosthetics.  However, I had explicitly set all limbs to being "normal", and the text display reflected the proper settings as well.  In an attempt to force-solve the issue, I changed the limb's setting to "amputated".  Now I can't give my character a limb, normal OR prosthetic!  I've restarted my game twice, and this hasn't done anything to solve the problem.
![ss13 character preview bug](https://user-images.githubusercontent.com/12755016/37742528-3c88f5a6-2d23-11e8-9a9a-d64d52d275c5.PNG)

**Comment by gelza1** [comment]
The problem appears to have been solved following an end-of-round server reset.

**Comment by NonQueueingMatt** [comment]
Fixed
