### ISSUE TITLE
The Zippo Problem

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#4460]
If you have a lighter in your cigarette pack and you take a cigarette out by clicking your mouth with the pack in-hand, it seems to turn your lighter into a cigarette instead of taking a cigarette out. This is bad for any and all smoking characters.

**Comment by KepQwet** [comment]
True for cheap lighters as well, and presumably anything that can fit in a packet.

**Comment by tedwood3** [comment]
![image](https://user-images.githubusercontent.com/2719189/37909177-f37bd392-3155-11e8-9ea0-d5fe96713cd6.png)

I stuck the Zippo in the packet like so. Then started placing the packet to my mouth. The zippo stayed, but now my screen has ciggies stuck on it.

![image](https://user-images.githubusercontent.com/2719189/37909207-09e7f534-3156-11e8-8664-85535d9995a9.png)

**Comment by tedwood3** [comment]
![image](https://user-images.githubusercontent.com/2719189/37910117-7c0b02e4-3158-11e8-8f41-5b4d88b2a683.png)
It appears that happens every time you get a cigarette while the inventory is open.
