### ISSUE TITLE
Ventcrawl bugged for nymphs

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#4465]
What the title says, "There are no pipes that you can ventcrawl into within range!" would display each time 
vent crawl was used on a functioning scrubber or vent as a nymph.

**Comment by Yonnimer** [comment]
this is still a issue.

**Comment by Arrow768** [comment]
Unable to reproduce -> Tested it on the server and ventcrawl seems to work fine.
Inform me (or any other dev) if that issue occurs
