### ISSUE TITLE
Insufficient Camera Coverage

### ISSUE THREAD

**Issue by Arrow768** [Aurorastation/Aurora.3#4474]
The following areas have insufficient camera coverage:
Cryo at Cargo:
![grafik](https://user-images.githubusercontent.com/1331699/37869312-c98f92b8-2fb5-11e8-94f1-ccf99b7955ba.png)
Main Hallway south of visitation:
![grafik](https://user-images.githubusercontent.com/1331699/37869318-d9d956e0-2fb5-11e8-8679-34b1b441bbab.png)
Medical Cold Storage:
![grafik](https://user-images.githubusercontent.com/1331699/37869325-e8973cf6-2fb5-11e8-9af9-9078b2169161.png)
Firing Range:
![grafik](https://user-images.githubusercontent.com/1331699/37869353-5c89e0c8-2fb6-11e8-891d-3c87f879d2a7.png)
Ladder to the authentication terminal:
![grafik](https://user-images.githubusercontent.com/1331699/37869362-8c2fb276-2fb6-11e8-9eb4-c4f4304e3f9e.png)
Data compilation Office:
![grafik](https://user-images.githubusercontent.com/1331699/37869366-a5070470-2fb6-11e8-945b-b59e2c6ff3b7.png)
Cryogentics control room:
![grafik](https://user-images.githubusercontent.com/1331699/37869453-213f1d74-2fb8-11e8-9f30-ad35cfcca783.png)

**Comment by Pacmandevil** [comment]
I don't think having blind spots is necessarily a __ bad__ thing

**Comment by Juani2400** [comment]
The authentication ladder one is intentional.  AI

**Comment by Juani2400** [comment]
The authentication ladder one is intentional.  AI
