### ISSUE TITLE
Mice Skeletons do not fall down Zlevels.

### ISSUE THREAD

**Issue by EJDenton** [Aurorastation/Aurora.3#4491]
This hinders my ability as a drone to dump them in the crusher.

**Comment by Baa14453** [comment]
Can confirm they do not.
![skele](https://user-images.githubusercontent.com/9057997/79122584-f3111600-7d8f-11ea-92c4-0edcc0f42b35.gif)

If any large mob clicks the skeleton it will turn into dust, this doesn't work for drones not sure why.
Not sure if it's best to let the remains drop a Z-level or make it so drones can dust them

**Comment by JohnWildkins** [comment]
"Fixed" by #8669
