### ISSUE TITLE
Brig Processing Consoles will Enter the name of the Person a Changeling is shapeshifted as instead of the name on their ID

### ISSUE THREAD

**Issue by EJDenton** [Aurorastation/Aurora.3#4492]
A changeling was in solitary. I went to process them on the consoles.

When I used their ID to enter the Convict it would enter the name of whoever they were currently shapeshifted into.

**Comment by tedwood3** [comment]
The code takes the convict's mob off the ID, instead of the ID's name. I'm looking into rewriting how this works now.

**Comment by tedwood3** [comment]
I was wrong by how it works. Instead of having to rewrite it, I just have to add a new variable for the incident to hold the ID. Easy peasy
