### ISSUE TITLE
Some of the RCON SMES choices are duplicated.

### ISSUE THREAD

**Issue by Chada-1** [Aurorastation/Aurora.3#4495]
What should happen is to look through the RCON list and there is only one SMES for each area. What happens is that there is a duplicate of each one, and if you click to toggle an option on the duplicate, it toggles the one below it as if it's a fake option.
[Here's a picture for you.](https://puu.sh/zSy5v/bd26dc1316.png)
I don't know what is up with this but it seems bugged, even if it's not gamebreaking.

**Comment by MarinaGryphon** [comment]
They were originally named slightly different things. Someone changed it and now it doesn't work.
I believe they had [F.3] and [F.4], for example.
