### ISSUE TITLE
IV drips broken.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#4505]
Cant use the "Set transfer rate" verb anymore. Nothing pops up when you use it.

**Comment by Sindorman** [comment]
I have checked it, it works just fine. Verb pop up and rate is being set properly.

**Comment by soryy708** [comment]
Try setting the transfer rate to 0. Does it break the IV?

Try setting the transfer rate with a empty blood pack inside. Does it break the IV?

**Comment by Sindorman** [comment]
@soryy708 Both cases seems to be working.
