### ISSUE TITLE
suit sensors tracker map and security camera console map are out of alignment with actual locations

### ISSUE THREAD

**Issue by KepQwet** [Aurorastation/Aurora.3#4509]
![image](https://user-images.githubusercontent.com/28516036/38169097-475e3512-3526-11e8-82a1-e1c3676e08cb.png)
those camera icons should be showing up on the bridge on the map, but it's offset down and to the left. same issue on the suit sensor tacking map iirc, where tracking icons show up farther down and left than they should.

**Comment by Juani2400** [comment]
#4251
