### ISSUE TITLE
Circuit Imprinter Glass Bug

### ISSUE THREAD

**Issue by bug924411** [Aurorastation/Aurora.3#4510]
When moving a circuit imprinter with glass inside of it to another location, the glass disappeared. The acid stays in the beaker, but I unfortunately lost all the glass. If there was a fix for this, I'd appreciate it.

**Comment by tedwood3** [comment]
Steps to reproduce? When disassembling the circuit imprinter to move it, the glass is supposed to pop out.

![image](https://user-images.githubusercontent.com/2719189/38179139-ebc19120-3662-11e8-8d1a-db2d023bbdd7.png)

**Comment by dragoslava** [comment]
Cant reproduce this happening
