### ISSUE TITLE
Tape recorder acts as universal translator

### ISSUE THREAD

**Issue by TheGreatNacho** [Aurorastation/Aurora.3#4516]
![image](https://user-images.githubusercontent.com/2719189/38223985-2868a7ac-3731-11e8-8605-c3f10d13ed5a.png)

As a nymph, I only know rootsong by default. Using a tape recorder lets me understand any language.

**Comment by Lohikar** [comment]
Arguably the tape recorder should only work with some languages and only translate to TCB, but it is acting as designed.
