### ISSUE TITLE
Science Testing Range Firing Pins Missing

### ISSUE THREAD

**Issue by SaudusAurora** [Aurorastation/Aurora.3#4521]
I have checked it multiple rounds and finally ahelped. Sircatnip assisted me, confirmed there were no firing pins and suggested that a recent remapping that added the gun charger to the range might have accidentally removed the firing pins. Due to test pins being unprintable as far as I know, this unfortunately shuts down a minor branch of science.

**Comment by Arrow768** [comment]
Firing pins can be ordered in from cargo.
However there still should be some mapped in
