### ISSUE TITLE
Imaginary Friend can eject people from cryo cells, flip tables, and rotate chairs.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#4529]
Round ID:  bTJ-alSR

What the title says. Ended up getting imaginary friend, decided to see if I could eject my host from cryo, I can by right clicking cryo and hitting eject. I can also flip tables and rotate chairs using the verb.

Even after getting removed via surgery, I could reconnect and still flip tables.

**Comment by Lohikar** [comment]
Guess it's time to change some `isobserver()` checks to `isabstractmob()`.
