### ISSUE TITLE
The Weapon Check on turrets, if toggled on, allows turrets to shoot downed and resting people.

### ISSUE THREAD

**Issue by Geevies** [Aurorastation/Aurora.3#4531]
I was told this by a very reputable source [Citation Needed], I'll post an update once I confirm.

**Comment by Sindorman** [comment]
That could be normal if it is on stun settings, as it pins dangerous people down. However I can see your concern about it, does it shoot dead people as well?

**Comment by Geevies** [comment]
Ah shit, sorry. I didn't come back to you on this. I don't think it shoots dead people.
