### ISSUE TITLE
healthHUDs don't work

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#457]
@NanakoAC HealthHUDs, even with the proper jumpsuit settings, do not display any green status bar.

**Comment by OneOneThreeEight** [comment]
This seems to be intentional. They fade out and show no bar when the subject's health restores to 100% healthy. Try damaging someone and then healing them.

**Comment by skull132** [comment]
Indeed. Though, I need to review that code update again. It may be causing runtime errors for the mob processor.

**Comment by NanakoAC** [comment]
1138 is correct, healthbar not showing is by design

ive not seen runtimne errors so far, and cant see anything that would cause them, except perhaps the more frequent update rate. though i'm not sure why that would be a problem
