### ISSUE TITLE
Janitor cyborg's trashbag does not pickup broken bottles

### ISSUE THREAD

**Issue by Sindorman** [Aurorastation/Aurora.3#4571]
Just like the name says, the trash bag module says that there is nothing to pick up, and that the bottle is too far away even if you are on the same tile

**Comment by Kaedwuff** [comment]
You can't pick up broken bottles in a trash bag, they are considered too large of an item.  The message is probably displaying incorrectly, but the net effect is the same.

**Comment by Sindorman** [comment]
Yes you can, in real world you can fit around 6-8 broken bottles in regular size trash bag. Janitor trash bags are usually big, so I am pretty sure you should be able to fit it

**Comment by Doxxmedearly** [comment]
Issue has since been fixed. Did it plenty of times in round and just tested again for good measure. Picks them up just fine.
