### ISSUE TITLE
Security Camera List Incomplete or not working

### ISSUE THREAD

**Issue by EJDenton** [Aurorastation/Aurora.3#4577]
When viewing cameras, new catagories have been added or renamed. The catagory Civilian Main only shows the crusher camera listed when it should show all public hallways and other civilian areas.

The catagory Service is completely empty and no cameras show for hydroponics, the bar, kitchen, or library.

**Comment by EJDenton** [comment]
Additionally, Cargo Main Desk and Cargo Main Lobby do not show up under the supply catagory.

**Comment by skull132** [comment]
My bad, forgot to merge a fix to live. I merged it just now.

@EJDenton please re-check and see if the bug is resolved.
