### ISSUE TITLE
Asteroid generates openspace above station rooms, resulting in instant depressurization (no ceiling). 

### ISSUE THREAD

**Issue by flimango** [Aurorastation/Aurora.3#4578]
Issue in title. Hilarious results. I am unsure if it is limited to the security wing, but I assume not. 

https://puu.sh/zZlV1/572e94fe72.jpg

http://puu.sh/zZlVa/f756573d28.jpg

**Comment by LordFowl** [comment]
![image](https://user-images.githubusercontent.com/11169120/38494477-0e587396-3bc4-11e8-916a-096a0935d914.png)

Those two tiles have the wrong area for some reason.

**Comment by flimango** [comment]
probably a misclick when remapping the floors to be not holofloors.
