### ISSUE TITLE
Objects made in lathes and printers spawn behind all layers

### ISSUE THREAD

**Issue by LanceLynxx** [Aurorastation/Aurora.3#4580]
When printing parts or circuits, I've had the lathe finish the object, but spawn the object behind the machine, so I couldn't see it or pick it up without right clicking or alt clicking.

This is inconsistent, sometimes it will send to top, sometimes to bottom. It makes unaware players reprint the same thing many times because they simply cannot find the item they just made.

**Comment by Doxxmedearly** [comment]
I've been having this issue with printing books from the library computer, when I remove books from the scanner, and when binding new books. Sometimes they end up on top, and sometimes to the bottom. I can't see a pattern to this.

**Comment by soryy708** [comment]
I've had this happen to me with seed extractors.
