### ISSUE TITLE
PR #4463 Incompatible with Return To Mob verb

### ISSUE THREAD

**Issue by Synnono** [Aurorastation/Aurora.3#4584]
CCIA Agents use the Return To Mob verb to return to an observer or player character once they are done performing staff functions. As an ERT Commander character, this verb does not appear, leaving the staff member stuck in the ERT commander mob.

The ideal functionality would allow CCIA team members to use this verb as an ERT Commander in the same way they can as a CCIA Agent character.

**Comment by Lohikar** [comment]
@Ezuo

**Comment by Ezuo** [comment]
Hotfix PR up
