### ISSUE TITLE
Cleaning impossible.

### ISSUE THREAD

**Issue by AmoryBlaine** [Aurorastation/Aurora.3#4598]
Was unable to remove blood and soil from items. Tried washing machine, sink, space cleaner and soap bar. Unsure as to how or why this was how it was. Blood was Vox.

**Comment by EJDenton** [comment]
I have also had this problem with non-vox blood. I think it has something to do with the sprites of the clothing not updating. I notice that if you remove accessories from clothing the sprites do not update either.

**Comment by soryy708** [comment]
It happened to me as surgeon multiple times.
Operating on humans gets the gloves bloody. Washing hands or the actual gloves usually cleans it off.
Sometimes it gets stuck and I can't clean it no matter how much I try.

**Comment by dragoslava** [comment]
Wasnt able to reproduce this with a multiple set of items, all seemed to be working.
