### ISSUE TITLE
Paroxetine not mixing properly

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#4603]
Was a report that the ingredients does not mix at all.

10u Mindbreaker
10u Acetone
10u Inaprovaline

**Comment by untrius** [comment]
The wiki currently lists the wrong recipe for Paroxetine.  
![image](https://user-images.githubusercontent.com/7697956/39078528-15b41cbc-44d9-11e8-8d84-cef695c7b1e1.png)
![image](https://user-images.githubusercontent.com/7697956/39078532-24f52554-44d9-11e8-8463-8cb40bce8822.png)

**Comment by untrius** [comment]
Chada1 has updated the wiki.  
![image](https://user-images.githubusercontent.com/7697956/39086419-d9d829c8-455e-11e8-98f3-471bf757bb0a.png)
