### ISSUE TITLE
iPatch eye oddities

### ISSUE THREAD

**Issue by Spacemanspark** [Aurorastation/Aurora.3#4606]
It would appear that the iPatch accessory causes the eye color on the right eye to permanently stay white until the patch is taken off, regardless of what side the patch is on.
![Picture](https://i.imgur.com/wW8UCRZ.gif)

**Comment by DronzTheWolf** [comment]
It does this with all the other patches. I also had a problem with my eye staying blue after I removed the meson patch.

**Comment by Spacemanspark** [comment]
Has this been fixed?

**Comment by Alberyk** [comment]
@Spacemanspark No.
