### ISSUE TITLE
Records in PDAs

### ISSUE THREAD

**Issue by Moonyman** [Aurorastation/Aurora.3#4607]
The records editing window in character setup menu is set in size and starts a new line automatically if the line is to long. However records accessed via PDA do not reformat text according to the size of the PDA window. Which means that if the person that wrote records did not bother to manually put return line in them by pressing enter, the PDA version of it will show as one loooooooong line. If it goes long enough no amount of stretching your PDA pop-up window will uncover the whole record effectively making it impossible to read on the fly because text ends up somewhere outside your screen even if you increase the side of a PDA window to the maximum.

**Comment by Moonyman** [comment]
![example1](https://user-images.githubusercontent.com/24357252/39549745-a7a5622e-4e67-11e8-8b54-931678428188.PNG)
![example2](https://user-images.githubusercontent.com/24357252/39549746-a7c3680a-4e67-11e8-921f-56c379e6b7ec.PNG)
 Exhibit 1 is how you format your records in order for the issue to occur. Exhibit 2 is the resulting record on PDAs

**Comment by JohnWildkins** [comment]
PDAs are dead, so is this
