### ISSUE TITLE
No baselines purchasable from cargo

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#4622]
Baseline is not listed under the cargo order menu, therefor you're not able to get them at all.

**Comment by Sebbe9123** [comment]
Isn't baseline IPC's just cyborg parts with a multitool use on the head?

**Comment by ToasterStrudes** [comment]
Nope that would be the shell frame, which is the default borg looking sprite

**Comment by Alberyk** [comment]
Fixed.
