### ISSUE TITLE
Weapon Firing Mechanism not fitting RnD Weapon Prototypes - Integrated Circuit Printer Issue

### ISSUE THREAD

**Issue by SaudusAurora** [Aurorastation/Aurora.3#4628]
Haven't tried with regular guns, but with the largest assembly size (and drone as well) a RnD prototype gun does not slot in when a weapon firing mechanism is fit.

**Comment by SaudusAurora** [comment]
Also tried with a laser tag gun, didn't fit either

**Comment by MarinaGryphon** [comment]
It doesn't fit into the assembly or into the weapon firing mechanism?
You put it into the firing mechanism and then put the firing mechanism into the assembly. You can't put an empty firing mechanism in and then put a gun into the assembly, that's not how it works.
