### ISSUE TITLE
Cow not-really-but-still dupe.

### ISSUE THREAD

**Issue by Asheram** [Aurorastation/Aurora.3#4638]
I encountered a strange bug while feeing a cow that was given to the kitchen. 

As you feed the cow by hand, the item you feed the cow will become invisible in your hand, but it will still be there. It can be manipulated, but not eaten once more. 

For example: 
I fed the cow a "Vanilla cake slice." from my right hand.
The cow ate the cake slice and an empty plate appeared beneath the cow
My right hand appeared empty, but I couldn't pick anything up with it. 
As I used a nearby counter with my right hand I placed a "Vanilla cake slice" on it, now suddenly visible.
This cake slice could be interacted with, but not eaten once more.

This was repeated thrice with another vanilla cake slice, a piece of bread, and a taco. 

All items became invisible in my hand but could be placed to become visible once more once dropped or placed. Neither could be eaten, and those who spawned plates once eaten did so beneath the cow. 

The bug was reported to Secondary Admin "ShameOnTurtles" before reported here.

The game ID was bTW-bb2o for logs.

**Comment by Alberyk** [comment]
Fixed.
