### ISSUE TITLE
New Firing Angles Are Inconsistent

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#4672]
Firing angles give an advantage if walls are placed to the sides and a disadvantage if walls are placed above or below. After testing on old code, it appears to be a new issue brought along with a ballistic update.

Pictures for reference on new firing angles. 
![fire1](https://user-images.githubusercontent.com/24979527/39410600-d3757192-4bc8-11e8-88d9-906caf8f8cde.png)
![fire2](https://user-images.githubusercontent.com/24979527/39410601-d38483d0-4bc8-11e8-9237-f25e5b7e9765.png)

**Comment by Sindorman** [comment]
I believe that was fixed
