### ISSUE TITLE
Mesons/material/thermal glasses/devices are screwed with security cameras view

### ISSUE THREAD

**Issue by Sindorman** [Aurorastation/Aurora.3#4679]
If you are wearing mesons/material/thermal glasses/devices, and look at security cameras, it would allow you have same effect as you are wearing them.

Example:

- BST glasses lets you see everything around through security camera.

- Mesons lets you see through walls other structures through security camera

- Material scanner lets you see other objects through security camera

- Thermal lets you see mobs through walls through security camera

**Comment by JohnWildkins** [comment]
Duplicate of #1186
