### ISSUE TITLE
Slimes glitching out

### ISSUE THREAD

**Issue by Butterrobber202** [Aurorastation/Aurora.3#4693]
Slimes eat a monkey and fail to split. They then refuse to eat any more monkeys and you are forced to kill them since they are now useless. Pretty annoying to lose my rare slimes to this glitch

**Comment by HeyBanditoz** [comment]
Details are important to an issue report. Does this happen all the time, or is there a special case?

**Comment by Butterrobber202** [comment]
Sorry for a late reply! It seemingly happens at random!
