### ISSUE TITLE
Broken piping near Beta Solar Array

### ISSUE THREAD

**Issue by Hugo14453** [Aurorastation/Aurora.3#4696]
Also something wrong with the APC and SMES unit sprites they have no lights, although they seem to function fine.

![image](https://user-images.githubusercontent.com/9057997/39673646-05598062-5138-11e8-829c-7b774d4f27a8.png)

Finally, there are nobulbs in the lights next to the SMES unit and my sprite

**Comment by Hugo14453** [comment]
The APC sprite
![image](https://user-images.githubusercontent.com/9057997/39673648-12feef7c-5138-11e8-8016-49ff10349a8f.png)

**Comment by Sindorman** [comment]
That could you your loading issue or runtime byond weirdness. If it repeats let us know.

**Comment by Hugo14453** [comment]
yeah it's fine this round, probably just me
