### ISSUE TITLE
Secure Safes Appear Through Walls

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#471]
Secure Safes appear to be visible from any side of a wall, no matter if you have direct line of sight to their tile or not. This is not a mapping issue, so my best guess is that it has something to do with 510. Other items that use a similar mapping placement method, such as newscasters or buttons, appear to be unaffected,

**Comment by OneOneThreeEight** [comment]
Penlights and the nuke disk are included in this.

**Comment by skull132** [comment]
Define "similar mapping placement method"?

**Comment by OneOneThreeEight** [comment]
I think he's referring to sprite alignment for "wall-mounted" devices. Airlock control interfaces are actually placed on a singular tile and then visually shifted to a nearby wall or surface so it doesn't look like it's floating in the middle of the room.

**Comment by Pratepresidenten** [comment]
Light switches and window tint controls in Sub-Acute A and B can be seen through the wall in genetics.
