### ISSUE TITLE
Tourettes will cause your mob to attempt to express their mental condition while dead.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#4730]
Because your mob is supposed to be dead, they'll instead remark, ";COCKSUCKER" to deadchat, completely outside of the control of the player.
This stops when you ghost.

**Comment by Lohikar** [comment]
NPCs with tourettes will attempt to do the same, though runtime in the process.

**Comment by Geevies** [comment]
I think this has been fixed.
