### ISSUE TITLE
Imaginary Freinds - IC Automuting

### ISSUE THREAD

**Issue by YuriDaruski** [Aurorastation/Aurora.3#4731]
I've noticed that I tend to trigger the IC auto-mute very easily as an imaginary friends, even if the statements are a second or more apart from each other. They can be two long full different statements, but it will still trigger it. Perhaps the threshold is off, but currently I trigger it the second phrase more often than not.  While I don't have the opportunity to play an imaginary friend often, I do recall trigging it in the past as well.

https://gyazo.com/8b0bcb946a2bb22fffed65adf0948547

**Comment by Moonyman** [comment]
#4454 already submitted
