### ISSUE TITLE
Truffle Recipe does not work

### ISSUE THREAD

**Issue by YuriDaruski** [Aurorastation/Aurora.3#4753]
Recipe calls for the baking of x1 chocolate bar, however this action yields only a baked chocolate bar. not much else too it.

**Comment by LordQuailius** [comment]
https://i.gyazo.com/b070f5d25c64c46dd8a9419eb5d3c168.png

As the code stands, you have to put the chocolate bar in the microwave along with 5u of sugar and cream. If anything, food and drink wiki needs to be updated or code changed to fit the wiki.
