### ISSUE TITLE
Clicking on a visible mess while holding soap no longer immediately cleans it unless you use alt-click

### ISSUE THREAD

**Issue by Matthew951** [Aurorastation/Aurora.3#4759]
Before the most recent dev merge, if you used a bar of soap on the exposed pixels of a stain/mess (oil spill, bloody footprints, flour...), it would immediately clean up the mess and say "you scrub out the [whatever]." Now, if you click on the mess, it will behave as though you are merely clicking the plating under the mess, which begins a progress bar to clean the tile. HOWEVER, if you alt-click to bring up everything on that turf, and use the soap on the mess THERE, it returns to the old behavior of immediately cleaning it.

It seems as though it should either go back to the old behavior or make it so alt-clicking doesn't work either, as it doesn't make sense for one mode to be able to immediately clean it while the other cannot.

**Comment by MarinaGryphon** [comment]
Unable to reproduce. https://i.imgur.com/DaX3Pgb.png
