### ISSUE TITLE
Sweater Woes

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#4761]
It seems the colorable 'sweater' accessory is broken (Or was slightly bugged for me)
It didn't display the selected color on my character, just in-hand. I don't know how hard this would be to fix but I figured making you aware would make it a bit easier to do so.

Server revision: master - 2018-05-17
bdd58ea0c984d3e4345d5a9e1cc498c8164ecaf2 
 
Game ID - bUp-dGFZ

**Comment by Alberyk** [comment]
Might be an issue with accessories as whole when colored.

**Comment by Alberyk** [comment]
This is fixed.
