### ISSUE TITLE
Girders are under the layer of sand and, literally plating now

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#4766]
When you cut down a wall sometimes the girder sprite is there, but when you select it with your mouse it just says 'plating'. You can't do anytihng without doing alt+click.

**Comment by BurgerLUA** [comment]
I have this bug too. Don't know why this happens, but I've noticed that there have been, in general, a lot of layering issues lately.

**Comment by Alberyk** [comment]
Old bug, related to the layer of the asteroid sand.

**Comment by SleepyWolfe** [comment]
It's not happening with just sand, it's happening with plating too. Literally just plating, you can't click the girder.

**Comment by Kaedwuff** [comment]
This is probably related to why it's hard to select runes when you place them down in maintenance.

**Comment by Moltenkore** [comment]
It's not just girders either, sometimes if you place items down on racks or eject suits from suit modifiers the item will go to the bottom of the list under everything else.
