### ISSUE TITLE
Starting a round has a 50% crash chance in the first 4.5 minutes

### ISSUE THREAD

**Issue by Ornias1993** [Aurorastation/Aurora.3#4776]
Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.
[x] Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!
[x]  Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.
[x]  Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
[x] All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera.

Today every restart has a 50% change on crashing within the first 4 and a half minutes. It's one crash round, one non-crash round most of the time (but It may happen multiple times in a row).

Admins found nothing they could do, which was to be expected.
In terms of logs, you can look at all the logs for the previous 6 hours or so and you'll find it.

The time of crash is suspiciusly similar, so prob something that has a delayed load after round start.

*edit 21/05 10:21 Amsterdam Time*
it is not one crash round, one non-crash round as became clear yesterday, it really is a flip-of-the-coin chance. But 50% seems about right.

**Comment by Sindorman** [comment]
I am not sure, but judging from Skull's messages in code channel - it is probably byond version having fuckery(as always) also VM on which server is hosted has run out of allocated disk space for it, which is an easy fix that was done.

**Comment by Ornias1993** [comment]
Yeah I didnt notice it yesterday anymore, So i guess the VM space was the most noticable culprid.
