### ISSUE TITLE
Pickaxes Take 2 Spaces in Explorer Webbing

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#4796]
Makes them even less likely to be taken. Not sure of any other item that does this.

**Comment by Ornias1993** [comment]
A webbing is designed for extremely small items: GPS units, Radio's and so on.
It litterally a front pocket.

Most items of significant size can not be put into it anyway, so actually pickaxes should actually be removed from webbing completely.

You complain about QoL on a subject that is actually designed inconsistant to give you more QoL 👍 
Not a bug.

**Comment by verywhiterabit** [comment]
Yet kinetic accelerators, an item that should be about the same size and are infinitely more useful take up only a single slot. 

The argument that they shouldn't fit in the webbing at all doesn't really hold up considering that:
A. It's not the same form of webbing you stick on a vest, it's much heavier and reflected in that it takes up a belt slot. 
B. Larger objects still show on the belt so it's not hard to assume that they just stick in loops. 
C. If it's not designed to hold all of the actually important equipment, there's literally no point in taking it because it takes up the same slot that you would normally store that equipment in. 

I don't even take the pickaxe since, as I said above it's horribly undertuned compared to other equipment, so this isn't "designed to give me more QoL", it just makes no sense balance or logic wise that one tool has been arbitrarily made to take up extra space than any other.

**Comment by Ornias1993** [comment]
@verywhiterabit I didnt know it also takes the belt slot, okey in that case it should fit.

**Comment by dragoslava** [comment]
This isnt a bug, however if this needs changed, make a suggestion
