### ISSUE TITLE
Oxygen candles cannot be moved into disposals by borgs (standard/burnt).

### ISSUE THREAD

**Issue by Lemonylight** [Aurorastation/Aurora.3#4801]
What it says on the tin. Borgs cannot move oxygen candles into disposal units.

**Comment by Sindorman** [comment]
Why would they? borgs have no hands

**Comment by Lemonylight** [comment]
Except borgs are also able to move every other trash, including deceased mobs like spiders and bats, into disposal units.

**Comment by Sindorman** [comment]
I cannot even move dead spiders into disposal units, can you tell me steps to repoduce it?

**Comment by Lemonylight** [comment]
Alright. Was not aware oxygen candles are not considered trash, but device. As for the steps, insert a giant spider, kill it, control-click to drag it as a borg, move borg near a disposal with the corpse on the tile just next to disposal, click-drag corpse onto disposal sprite.
