### ISSUE TITLE
Gamebreaking assortment of slime issues for xenobiology

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#4810]
Referencing the following issues as consistent with problem number 1: #4451 #4693 

* Slimes occasionally runtime and don't latch off of their target after they've killed it through genetic draining effects. This breaks the slime AI afterward and they'll stop seeking targets to eat, period, even if it is monkeys.
* Slimes get way too much nutriment from latching onto a mob and then being thrown off said mob, even if the mob uses grab intent to throw off the slime in the first try, the slime will immediately grow to be an adult instantly. This creates a problem where a slime with a larger healthpool, pounce stun duration and better chance to land a pounce or electrocute you is able to kill you incredibly quickly even if you manage to throw it off you. The latter problems are not so much an issue as much as when combined with the initial issue.
* Slimes don't need to tackle you to latch onto you. This is more a balance issue than it is a bug issue, but I'm listing this as an issue regardless.
* Throwing off a slime ranks incredibly low in chance. This would be less of an issue if the aforementioned other factors didn't exist.

**Comment by Geevies** [comment]
i don't think this is a problem anymore, i've redone slimecode a wee bit, re-open if it's still fucky
