### ISSUE TITLE
CCIA can't manage their tickets created from Pming someone

### ISSUE THREAD

**Issue by JMJ99** [Aurorastation/Aurora.3#4815]
This isn't exactly a bug more of an oversight. Using admin pm creates a new ticket, which for CCIA can't be closed or viewed in the ticket panel, would be extremely helpful if they were.

**Comment by soryy708** [comment]
Wouldn't that create an open ticket that would delay round end automatically unless closed by mod/admin?
What if there's no staff online at the time? Will everyone be stuck on Odin?

**Comment by JMJ99** [comment]
pretty much yes
