### ISSUE TITLE
Virology- Methods of Infection

### ISSUE THREAD

**Issue by Biolock1** [Aurorastation/Aurora.3#4819]
Currently, according to the wikipedia (https://wiki.aurorastation.org/index.php?title=Guide_to_Virology) there are three methods of infection with a virus. Those three being airborne, direct contact, and direct infection. Airborne being self explanatory, direct contact being through touching, and direct infection being through blood contact. 

I have played countless rounds as a virologist and have gone through examining hundreds of virus samples and mutations, and not once have I ever seen a virus that is transmitted through blood contact. I do not know if this is just a misprint of the wiki, blood contact being mislabeled as "direct infection" in the game as an oversight, or if the variables are just so skewed that it is incredibly unlikely that blood contact is a method of transmission.

If it is the third option I would like to see that blood contact is the most likely method of contact to display on any virus, and airborne being the least common.

**Comment by Ornias1993** [comment]
Direct infection is the act if INJECTING the virus INTO the subject.
"The infection has been forced into the infected crew member"
and
"getting the patient's blood directly into another crew member"

Ergo.
Not a bug

It could be writhen a bit more clear, but no bug here.

**Comment by Biolock1** [comment]
But there's no way to differentiate between the two methods of infection in the game, they're both referred to as "Contact".

**Comment by Biolock1** [comment]
Bump

**Comment by Doxxmedearly** [comment]
Virology has been removed
