### ISSUE TITLE
Cargo office vents for no reason

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#4824]
The little room that leads into the cargo warehouse, between the initial airlock and the shutter keeps draining atmos very slowly for some reason. There is no immediate hole to be found up or down, over the shutter or plastic flaps.

**Comment by BurgerLUA** [comment]
I looked in code and apparently disposals inlets (all types) suck out pressure, and disposal outlets check out pressure.

It explains why disposals is always over pressurized all the time, and explains why that room is under pressurized. This will be fixed.
