### ISSUE TITLE
Truffles Recipe is broken

### ISSUE THREAD

**Issue by LordQuailius** [Aurorastation/Aurora.3#4837]
When you try to cook truffles according to the code, you get your reagents back plus a free fortune cookie. Tried to make infinite fortune cookies but the chocolate bar portion got baked, so I guess that isn't an issue...

**Comment by BurgerLUA** [comment]
Wiki is wrong. 

Recipe is 5 sugar, 5 cream, 1 chocolate bar.

**Comment by LordQuailius** [comment]
Didn't use the wiki. Used the code. Put a chocolate bar, 5 sugar, 5 cream into an oven pan and bake it and it makes a fortune cookie with the other ingredients unaffected.

**Comment by BurgerLUA** [comment]
Fortune cookies require dough to make. This shouldn't happen, but I will look into it.
