### ISSUE TITLE
NTSL causes issues when blank strings ("") are sent to compile.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#4843]
What the title says. Don't know why it does this, but it does this. The UI says that it cannot locate the machine anymore when any compiler button is pressed, and all attempts to Edit Code does not work as the UI cannot open once it's closed. Rejoining allows you to use NTSL again.

**Comment by BurgerLUA** [comment]
Also it seems like missing arguments in functions such as only sending replace("Hello","There") will cause errors too.

**Comment by BurgerLUA** [comment]
Correction: Seems to happen a lot as AI. Likely because I'm not near the console or something. Will have to test locally and see what errors come up.

**Comment by printer16** [comment]
if it runtimes it breaks.
