### ISSUE TITLE
Panotoxin doesn't work (pain affect).

### ISSUE THREAD

**Issue by LordQuailius** [Aurorastation/Aurora.3#4844]
According to the changelog (BurgerBB), panocelium mushrooms contain a newish toxin called Panotoxic (typo?) that "causes intense amounts of pain".

In character, I tested exposure to panotoxin via spraying in the eyes, injecting, and consumption, and not any of those resulted in any pain whatsoever(the psylocibin works just fine though). Tested on both human and skrell, no results from either tests.

**Comment by Alberyk** [comment]
That is because this chemical does not exist.
