### ISSUE TITLE
Dying in elevator keeps playing elevator music when you're a ghost

### ISSUE THREAD

**Issue by soryy708** [Aurorastation/Aurora.3#4846]
No way to turn off the music either.

Game ID: bUF-blBt

**Comment by Mwahahahaha** [comment]
Toggling ambience doesn't work then?
What happens if you reconnect?

**Comment by Juani2400** [comment]
OOC tab -> Stop all sounds. Should work as a temporary fix for you.

**Comment by deGurkin** [comment]
Seems like a Feature as well as a bug, I like it.
