### ISSUE TITLE
Infinite duplication of plastic when deconstruction a rack (Or: Plastic transmutation.)

### ISSUE THREAD

**Issue by Aceofspades1228** [Aurorastation/Aurora.3#4871]
Racks can be deconstructed (wrench twice, get one plastic, one metal) then rebuilt with the metal then deconstructed again forever for infinite plastic (plastic keeps popping off despite not being used to build racks).

**Comment by MarinaGryphon** [comment]
Working on this. Current fix will be just dismantling when it attempts to remove the material.
