### ISSUE TITLE
Runtime error with process scheduler

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#488]
Popped up while i was testing with mobs today, It hapepned when i was a nymph, and assumed direct control of an unathi i'd just spawned. Can't replicate though. Maybe a safety check is needed in there?

You start swallowing the mouse (438), this will take approximately 3 seconds
The mouse (438) protein quantity is 2
Tom squiks.
ADMIN LOG: nanakoac/(diona nymph (283)) created 1 /mob/living/carbon/human/unathi
ADMIN LOG: nanakoac/(diona nymph (283)) assumed direct control of Reshlasreshsh Reshresh.
  Squeek!
runtime error: Cannot read null.gcDestroyed
proc name: doWork (/datum/controller/process/mob/doWork)
  source file: mob.dm,17
  usr: null
  src: mob (/datum/controller/process/mob)
  call stack:
mob (/datum/controller/process/mob): doWork()
mob (/datum/controller/process/mob): process()
/datum/controller/processSched... (/datum/controller/processScheduler): runProcess(mob (/datum/controller/process/mob))
You scoop up the diona nymph (283).
You are unable to equip that.
ADMIN LOG: nanakoac/(Reshlasreshsh Reshresh) assumed direct control of the cow.

**Comment by skull132** [comment]
Are you using `del(mob)` at any one point? It looks like consume code may
be hard delling the mob, instead of using qdel.
