### ISSUE TITLE
Animals Exiting Holders Under Bad Conditions

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#489]
Basically, what happens: if you put a mob holder (say a mouse) into a backpack, the holder is deleted next tick of the processor, and the mob "exits" into that backpack (container). This breaks backpacks, as they are unable to deal with having mice or other living mobs in them.

What's curious is that all of this worked before.

@NanakoAC please figure out how it worked before, and reimplement what is necessary. Or make it better, idc, as long as it works.

**Comment by NanakoAC** [comment]
already fixed by #510
