### ISSUE TITLE
Hextrasenil does not react upon mixing.

### ISSUE THREAD

**Issue by LilahNovi** [Aurorastation/Aurora.3#4890]
Upon mixing the three components of Hextrasenil together, they did not mix. I re-mixed them once more just in case, and could not get a reaction.
![screenshot 2018-06-15 16 06 46](https://user-images.githubusercontent.com/19613432/41489977-8f9da87c-70b7-11e8-8e7c-e06b3865cb00.png)

Just in case, I also added phoron, and didn't get a reaction either, even though the wiki doesn't call for it. Thanks!

**Comment by LordFowl** [comment]
That is because hextrasenil does not exist. Did anything in-game implicate that it does? If so, then that is the real bug.

**Comment by LilahNovi** [comment]
That's strange. On the Guide to Chemistry, it is a chemical under
psychiatric medication. I was requested by the psychiatrist that shift to
make it. I looked it up, and it's right there. I'll post a link tomorrow.

**Comment by LilahNovi** [comment]
![screenshot_20180616-031707](https://user-images.githubusercontent.com/19613432/41497098-f41857e6-7113-11e8-92ac-240839ae343a.jpg)

Sorry, just a little confusing!

**Comment by LordFowl** [comment]
The wiki team is independent of the dev team. I will forward this issue to Chada1.

**Comment by Chada-1** [comment]
This issue should be resolved. I removed references of Hextrasenil from the wiki.
