### ISSUE TITLE
Borg energy weapons that are supposed to auto recharge are broken completely when EMP'd

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#4897]
As in they don't recharge after emptying the weapon capacitor.

This makes them completely useless with that weapon for the rest of the round. Irreversible damage should never be a thing.

**Comment by Sindorman** [comment]
After digging into issue I found out that there are easy IC means to fix it. Simply get in recharging station and it will reboot your gun, and make it self-recharge.

**Comment by OneOneThreeEight** [comment]
Forgot this issue was still up. It was addressed in a patch that added that.
