### ISSUE TITLE
Power Cable in Journalist's Office not connected to APC

### ISSUE THREAD

**Issue by SoapyCup** [Aurorastation/Aurora.3#4902]
The power wire proceeds in under the door, down and across, and has a missing section under the desk. This requires the carpet to be removed and placing of a wire, or else the APC will run out of power. This seems to happen every round.

**Comment by fernerr** [comment]
Here's a picture of the missing wires for clarity. https://i.imgur.com/gUn8X3U.png
Relatedly I think it should've been wired to a sub-grid too, as now it's intended to be wired up to the main power grid.
