### ISSUE TITLE
Newscaster 'Attachment' feature borked

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#4907]
Attachments are great in that they let you bypass the character/word length restriction of the newscaster.

But right now, they don't recognize line breaks (using the ENTER key) OR using the [br] bccode for breaks. Meaning you get one obnoxiously long (horizontal, not vertical) paragraph that's illegible.

**Comment by MarinaGryphon** [comment]
I think that's because I used the `<CODE></CODE>` tags. Changing it to blockquotes with a border, now. Should probably work.

**Comment by XanderDox** [comment]
@MarinaGryphon New similar issue. It's impossible to properly remove photos you've attached unless you're attaching a brand new photo. if you try to remove one without a replacement, you'll dupe the photo, OR teleport the removed photo across the station to you if you try to remove it again (it'll say it's still in the console AND print with your story)
