### ISSUE TITLE
Laceup Shoes Let Socks Clip

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#4909]
My immersion is shattered so hard it might never recover. I might need a few hours of hyperventilating to calm down. 

Pretty minor really, but if it's an easy fix then here it is. 
![dreamseeker_2018-06-18_16-40-37](https://user-images.githubusercontent.com/24979527/41560924-8afa1628-7316-11e8-8364-0e6c9660214c.png)
![dreamseeker_2018-06-18_16-40-42](https://user-images.githubusercontent.com/24979527/41560925-8b0daa26-7316-11e8-91ea-ff75efd8e2b3.png)

**Comment by Geevies** [comment]
i think this got fixed, hopefully
