### ISSUE TITLE
The Airbubble is a Cablecuff fabricator.

### ISSUE THREAD

**Issue by Chada-1** [Aurorastation/Aurora.3#4911]
The wiki team, very happy to finally get to work on the new dev cycle, begins experimenting with some items. Suddenly, on wrapping the Airbubble with wire, and wirecutting it open, they discover a horrible reality, the Airbubble can fabricate an infinite supply of Wire loops. Think of the applications!

Wirecutters generate an extra pair of cables on cutting an Airbubble. You can also wirecut it regardless of if it's wrapped in wire or not and it does the same thing. This bug was reported by BurritoJustice on the Staff Discord while testing.

**Comment by Burrito-Justice** [comment]
Sorry, what I meant to say was using wirecutters on the bubble - whether it's locked up with cable restraints or not - will lock and unlock it anyway, and then proceed to spawn a pair of cable cuffs seemingly out of no where on the same turf. Quite silly.

**Comment by Chada-1** [comment]
Updated to be accurate.

**Comment by Sindorman** [comment]
I shall fix it

**Comment by Sindorman** [comment]
I looked at code and found an issue right away - it doesn’t check if we already cut them or not. Same goes for outing restrains. So it doesn’t spawn extra cables, it just lets you keep cutting even when they are not there.
