### ISSUE TITLE
Airbubbles are a marvel of temporal displacement.

### ISSUE THREAD

**Issue by Chada-1** [Aurorastation/Aurora.3#4912]
As the wiki team continue their scientific testing of the magical airbubble, they realise, not only does it generate an infinite supply of wire utilities, it also harnesses the power of temporal displacement. Certainly a marvel of Bluespace engineering.

If you close an Airbubble and walk in another direction while inside of it, you'll appear beside it in the direction you chose, but the bubble won't open.

This was reported on the Staff Discord by BurritoJustice during testing for wiki purposes.

**Comment by Sindorman** [comment]
Interesting, this shouldn’t happen as airbubbles are lockers and in my testing I did not see it. Let me investigate and fix it
