### ISSUE TITLE
New red dock lacks full hullshield coverage.

### ISSUE THREAD

**Issue by fernerr** [Aurorastation/Aurora.3#4915]
When enabling the hull shield it mysteriously leaves some gaps around the new red dock. Here's some pictures of it for clarity.  (bottom) https://i.imgur.com/dETsbwi.png (top) https://i.imgur.com/YTvkujX.png

I've both tested this on the live server and on my own local server and the result is the same.

**Comment by BurgerLUA** [comment]
I'll look into this. I'm going to fucking scream if hullshields are defined by some hardcoded value instead of something flexible.

**Comment by BurgerLUA** [comment]
while i am screaming, it is because im a dummy
