### ISSUE TITLE
Throwing items at windoors leaves prints.

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#4923]
I threw a grenade at a windoor or something, and it apparently left a print which linked me to the explosion.

**Comment by Arrow768** [comment]
Do you have a round id ?

**Comment by verywhiterabit** [comment]
Couldn't get it to work for windoors, but after testing it does seem to happen on normal airlocks. Appears to happen with any object grabbed without gloves on, not just grenades.
