### ISSUE TITLE
Items randomly layer under vendors, oxygen tank dispensers, etc

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#4956]
![image](https://user-images.githubusercontent.com/19973802/42124974-6372c01e-7cc1-11e8-8d3d-40c7f29323af.png)

_Also illustrated, dispensed goggles layering on top of the RIG press._

![image](https://user-images.githubusercontent.com/19973802/42124976-997c04f4-7cc1-11e8-8e8a-dd618c60e798.png)
_While the jetpack layer under the press._

![image](https://user-images.githubusercontent.com/19973802/42124980-b4c13c5c-7cc1-11e8-88bd-c687df6fcbc7.png)

Round ID:bU8-bMGu

I'm pretty sure this didn't happen a few months ago, anyways it's an annoying occurrence.

**Comment by Fire-and-Glory** [comment]
Probably related to #4580 .

**Comment by Alberyk** [comment]
It might be due to the newest byond version.
