### ISSUE TITLE
Character preference bag resets

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#4978]
The preference for the generic gray bag never saves between rounds. It keeps resetting to the departmental bag. In my case the issue is the gray dufelbag, as a shaft miner.

EDIT: Dont remember having made a similar report, but this one is more.. Informative.

**Comment by Mwahahahaha** [comment]
Still a thing even today.

**Comment by Mwahahahaha** [comment]
I should point out that using the legacy save system (typical for if you quickly set up a test server without using SQL), it saves.
But on the main server, which would be using SQL databases, it doesn't.
