### ISSUE TITLE
Cyborg Laser Rifle Glitch

### ISSUE THREAD

**Issue by ben10083** [Aurorastation/Aurora.3#4986]
Problem; When a borg is dead and ghosted if it comes back it's laser rifle or any weapons that has charges will not charge anymore
Reproduce; 1. get fucked as borg (combat module or emagged sec module)
2. get revived
3. see how you cant get any more charges in weapons

Game ID; bVh-dlkL
Admin; ornias

**Comment by Sindorman** [comment]
Have you tried using recharging station?

**Comment by ben10083** [comment]
Tried clicking on recharger, nothing. Not even sure borgs can even use it

**Comment by Sindorman** [comment]
I meant recharging station for cybrogs. The one you used to recharge your power cell and materials. It is supposed to recharge your weapons and start recharge cycle for them if they are bugged.

**Comment by ben10083** [comment]
Oh I did that, didnt work either

**Comment by Sindorman** [comment]
It wasn't a bug, everything works. However borg revive throught admin magic is broke. Will fix it.
