### ISSUE TITLE
Internals/welding goggles (bug)

### ISSUE THREAD

**Issue by Domic2** [Aurorastation/Aurora.3#4997]
If you were to click on the internals mask, or the welding goggles, while they are in the character's hand, they get moved "out of the way", however, if you click on them again (right mouse button > adjust internals or pressing the icon in the top left for welding goggles doesn't work either) they do not return to their original state.

I tried this several times and it breaks without compromise, making these items unusable. Do note it works perfectly fine if you are actually wearing them, but did not hold them while they were 'unset' in hands.

Steps to reproduce: 
-hold internals mask or welding goggles in hands
-click on them to unset
Or:
-have internals mask or welding goggles equipped
-toggle them (right mouse menu)
-put them in hands

-should be broken now

**Comment by JohnWildkins** [comment]
Cannot replicate _except_ that masks cannot be toggled via verb, only action button.
