### ISSUE TITLE
Inhalers not transferring reagents to target mob

### ISSUE THREAD

**Issue by Burrito-Justice** [Aurorastation/Aurora.3#5012]
Hi. Inhalers are **B** r o k e

**What Should Have Happened**
An inhaler full of Dexalin should have transferred its reagents from the cartridge to the mob.

**What Actually Happened**
The item activated, the sound played, but the text mentioned that there were five units remaining in the cartridge, and the mob never received the Dexalin.

**Reproduction**
Take inhaler, click on self. This happens with or without a mask.

**Comment by BurgerLUA** [comment]
i got dis
