### ISSUE TITLE
Some cargo bounties do not work.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#5015]
The chainsaw bounty does not work. I ordered a chainsaw from central command, then shipped it off.
The soup bounty does not work. The chef made 3 wish soups and it did not work.
The soap bounty does not work. 3 bars of soap were sent to central command and it did not work.

**Comment by XanderDox** [comment]
To update this, a large amount of bounties do not work and I think the issue may go deeper than it being item-based, and it's getting frustrating to go through the work only to get nothing out of it in the end.

**Comment by Arrow768** [comment]
The issue with bounties not working has already been resolved. (A day ago)
If you are aware of any specific bounties that are not working, please let me know.
But a general "a large number of bounties do not work" is not helpful

**Comment by DronzTheWolf** [comment]
The APLU "Ripley" bounty has stopped working.

**Comment by JohnWildkins** [comment]
Quite a few bounty changes since this issue, and "Ripley" mechs are no longer a thing more or less. If anyone comes across this issue again, feel free to open a new issue, ideally with a round ID.
