### ISSUE TITLE
.getserverlog not working.

### ISSUE THREAD

**Issue by NonQueueingMatt** [Aurorastation/Aurora.3#5023]
Using .getserver log brings up the prompt for year, then month, then day. Confirming the option to get the logs result in an admin log about getting the logs being created, however there is no confirmation window and the logs simply don't get downloaded or shown.

Some other admins have been getting this bug as well.

**Comment by printer16** [comment]
@skull132 said this was likely a BYOND issue in #4518

**Comment by Arrow768** [comment]
Closed as duplicate
