### ISSUE TITLE
Cardox does not appear to follow damage calculations

### ISSUE THREAD

**Issue by Bygonehero** [Aurorastation/Aurora.3#5041]
When designing the bound Za, it was estimated that 45 units of Cardox injected was more than enough to kill one. During testing, however, 30 units of Cardox only caused 2 toxin damage. If this is the case then perhaps Cardox is not metabolizing correctly?

In normal Vaurca, unless this changed recently, Cardox does 15 units of toxin damage before modifiers per unit, 
meaning 1 unit of Cardox does 30 toxin damage to normal Vaurca. 15 units, 450. The Bound Za's modifier is low, but it shouldn't be doing this little damage to one.

**Comment by BurgerLUA** [comment]
There is literally nothing special about how cardox deals damage so it is purely to do with the race.

**Comment by LordFowl** [comment]
30u of cardox to a bound Za deals 60 points of toxin damage, although the metabolism of Cardox is slow.

**Comment by MarinaGryphon** [comment]
Cardox deals twice the reagent's `strength` variable, whereas in non-Vaurca it deals just the variable itself. This means that it is incredibly weak, as cardox's `strength` is **1.** It deals 2 damage total, per unit, before modifiers. Vaurca receive double toxin damage from other sources, as well, meaning that the total is **4 damage.**
It also metabolises extremely slowly. The default is **0.02 units per tick.** The server ticks 30 times a second. That is 0.6 units per second. 30 units of Cardox would deal 120 toxins, and take 500 seconds. @Bygonehero If you would like to see about increasing the metabolism rate, I can do that.
