### ISSUE TITLE
New fax UI makes it hard to identify click points

### ISSUE THREAD

**Issue by Juani2400** [Aurorastation/Aurora.3#5087]
![imagen](https://user-images.githubusercontent.com/6277887/43689294-18cb790c-98f0-11e8-8bbc-48db595584c6.png)

As the title says, the new UI makes it really hard to distiguish between text and links that you are able to click.

**Comment by Juani2400** [comment]
Similar issue as #5086.

**Comment by Karolis2011** [comment]
I blame resource manager for not sending all resources. Relog fixes it
