### ISSUE TITLE
the new fire extinguishers cant be refilled at the new extinguishes tanks.

### ISSUE THREAD

**Issue by NortonDK** [Aurorastation/Aurora.3#5088]
This is a bug i hope

**Comment by BurgerLUA** [comment]
Not a bug.

**Comment by NortonDK** [comment]
okay i've figured it out, it could need more explaining though. atmos techs has extinguisher refiller. that are a one time use. fill it with foam and twist then put into the fire extinguisher.

Does it also cools the room its used in like water?(if the room is above 100c)

Also 1000units in the big tanks is a little small maybe double it

**Comment by NortonDK** [comment]
I found the room cooling effect to be lacking, compared to water

**Comment by BurgerLUA** [comment]
they're exactly the same

**Comment by NortonDK** [comment]
also the foam landing on tiles, do they also "fizzle" because its over 100c?
I know the "emote" dosent show but does the foam also have the same effect?

(sorry for draggin it out, just want to make sure fire ext. gets too nerfed)
