### ISSUE TITLE
Pressure on the asteroid is fucked sometimes

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#5097]
I was playing mining after the new update and pressure kept fluctuating between 37 and 58 kPA, it's bizarre. As far as I can see the asteroid was never totally depressurized.

I didn't even need to keep my suit cooler running to survive in those pressures as a G2 IPC.

Round ID bVI-asNm

The round afterwards doesn't seem to have any pressure issues so I guess you need to trigger it somehow.

**Comment by Alberyk** [comment]
It seem to be due to the bluespace leak ruin, I might just remove it.
