### ISSUE TITLE
Random Open Ceiling when there isn't One

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#5098]
After spawning in as a bartender, I moved a little to find an open ceiling mark on my hud in this spot. 
![c0f7e9d1b7f01c34684fba5890b3b987](https://user-images.githubusercontent.com/12206154/43711187-8b15f090-9937-11e8-8785-0e0c630bc2fa.png)

I moved to doublecheck it, but after that, it disappeared from my hud.

**Comment by Alberyk** [comment]
It is just due to the initial state of the icon itself.
