### ISSUE TITLE
Spam filter triggering for adminhelps when it is not spam.

### ISSUE THREAD

**Issue by SharpAurora** [Aurorastation/Aurora.3#5103]
The spam filter seems to be muting people who aren't spamming. Sometimes when they want to make an adminhelp or in the middle of a discussion. 

Example 1: PoZe was part of a open ticket, he wanted to send something but he got muted, we had to unmute him so he could send it. So this wasn't a case of too many messages in a short time. Around 15 minutes from that question being sent to the previous pm sent.

Example 2: Amory is the same as well, except it was an ongoing discussion in an open ticket.

This doesn't seem limited to a singular round, but the round that I got my examples from is bVJ-aRVM

From observation, this isn't an issue everyone faces, but some.

**Comment by SoundScopes** [comment]
Most likely related to issue #4454
