### ISSUE TITLE
Cannot Shoot Turrets?

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#5107]
I went into the ai core and was gunned down. While I was being shot, I pulled my pistol and had it on lethal while it was fully charged. I clicked the turret repeatedly, but it didn't fire despite having no preferences for safety at all. I know this for a fact because I gunned down a spider not fifteen minutes before.

Eventually, I died after switching over to my baton and whacking the turret with it. What gives?

**Comment by Arrow768** [comment]
Unable to reproduce.
Do you have a roundid ?

**Comment by Fortport** [comment]
Afraid not. I am sorry.

**Comment by Arrow768** [comment]
Closing it then
