### ISSUE TITLE
Cargo Shuttle Destroys itself.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#5114]
https://i.imgur.com/ZZC3wNK.png

It's been happening a lot lately, though I believe it may be due to chance. When it occured to me, it was likely caused by me canceling a cargo shuttle launch, and then sending it again.

**Comment by SoundScopes** [comment]
This has been a bug since forever ago

**Comment by Sindorman** [comment]
Usually shuttle crashes like that when something is blocking it like a turf? Also if the shuttle is bigger of area than landing area.

**Comment by BurgerLUA** [comment]
In my experience it happens every time the shuttle is forced.

**Comment by Cnaym** [comment]
Happened to me when the shuttle was canceled with a delivery on it. It basicly forced itself, which lead to the big boom.

**Comment by Sindorman** [comment]
That occurs when shuttle cannot process the moving of shuttle from one area to another. When some element on it crashes in the loop, it will not finish transition of all object/s turfs resulting part of shuttle on Odin and part on station

**Comment by BurgerLUA** [comment]
I don't know how many god damn times I've said this in the past year but this happens when the shuttle is forced twice in quick succession. Whatever loops exist are being run twice so the end result is probably runtime errors and a broken shuttle as it was being processed twice.

I'm closing this ticket because I don't want anymore github notifications on this issue. I've given the problem and the solution multiple times in the coder discord yet it's being ignored again for the nth time.

**Comment by Sindorman** [comment]
Don't close it, just unsubscribe from it

**Comment by skull132** [comment]
Likely invalidated by Matt's rework of the shuttle system.
