### ISSUE TITLE
Bar Sink causes Floor to get Wet???

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#5118]
The one behind the counter, not sure if this applies to all sinks. Is this intentional? The tile gets wet as if a janitor mopped it. Specifically noticed this when using a damp rag and filling it.

**Comment by Tbear13** [comment]
I'm not 100% sure, but could this be caused by the sink's transfer amount? If it's set to transfer more than the rag can store, 5 units I think, it may spill onto the floor due to the sink not having anywhere to keep the extra water that was created.
