### ISSUE TITLE
People sometimes drink food rather than eat it.

### ISSUE THREAD

**Issue by Nexusuxen** [Aurorastation/Aurora.3#5125]
In short: Rather than normally eating foodstuffs, they'll be drunk instead. It would appear as though it functions almost exactly like eating, as it fulfills you with nutriment, but has the sound and text of drinking.

I'm unsure as to how to reproduce it. However, this wasn't active the whole round. People ate normally, but only a single person managed to drink the food (and drank all the food I had prepared in the bar - several dozen different items). Also, I did cook food that required reagents to be baked in them. This _may_ have resulted in some foodstuffs containing reagents and borking whatever process is responsible for saying "X person takes a (drink/sip) from the Z!" or whatever, but I'm unsure of that. 

Here is an image of part of the scene where someone decided to drink all my food upon discovering she drinks food.

![stop drinking my food](https://user-images.githubusercontent.com/28785926/43933282-c8e6b30a-9c16-11e8-8f20-7f6f4c11987d.PNG)

I apologize if this is a pretty crap issue report, I don't really write them often and I'm unsure of what other details to add.

**Comment by BurgerLUA** [comment]
Honestly a little peeved that Ava Hazel did not submit a bug report herself because this would make things a million times easier. I'm not angry at you since you brought the bug to light, but it would certainly help if Ava Hazel told us how they did this so I don't have to scan the code.

**Comment by BurgerLUA** [comment]
Bug was easier to fix than I thought.
