### ISSUE TITLE
lunchboxes don't spawn with chosen drinks inside.

### ISSUE THREAD

**Issue by alsoandanswer** [Aurorastation/Aurora.3#5139]
desired result : food item, snack, drink.

outcome : food item, snack. drink is missing.

replication : lunchbox in loadout, saved.

seems to work for the first few rounds, then stops giving me the drink altogether.

**Comment by jmlop0** [comment]
Can confirm that it happens with graple soda

**Comment by CodenameBear** [comment]
This still happens with Dr. Gibb. Will experiment with other sodas sometime. Maybe.
