### ISSUE TITLE
Flashes actually don't blind people

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#5140]
Flashes don't blind people, they just put a giant overlay on the screen. People can still click on things, examine them, view them normally, but visually they just get a 2 second flash and that's it.

**Comment by ProbablyMenown** [comment]
That makes sense. The objects don't disappear, you just can't see them. I'd wager this isn't a bug.

**Comment by MarinaGryphon** [comment]
I believe this is intentional, after the flash rework.

**Comment by Arrow768** [comment]
Nope, the flashes should definitely blind people. Just not stun them

**Comment by Geevies** [comment]
Intentional, wildly swinging should still work.
