### ISSUE TITLE
Javascript file load error when using Supply Control consoles in Atmospherics.

### ISSUE THREAD

**Issue by ProfligateShampoo** [Aurorastation/Aurora.3#5151]
Action: Clicking on a supply control console, located in lower Atmospherics.
Desired result: Supply control interface opens.
Actual result: Use of a Supply Control console in Atmospherics can be blocked by an error. The error reads "Javascript file has failed to load." There is a button that reads "Click here to force load resources", but this button does not appear to do anything.

![Screencap of the actual result.](https://user-images.githubusercontent.com/27918519/44115015-ace369e0-a004-11e8-9b94-65ed92529b0d.png)

How to reproduce: Click on any supply control console. According to ahelps with MattAtlas, this error does not occur for all users. Reproduced consistently using the latest version of BYOND, with cache cleared and re-downloaded.

**Comment by Karolis2011** [comment]
This is issue with your OS / browser. VueUi dropped support for IE8. This means we officially do not support Windows XP any more. I am sorry for your inconveniences. (In future I will probably make text better at explaining what can also cause this issue).
This force load button was meant to send resources if they failed to send, if they successfully were send by failed to work, then this show up.

**Comment by ProfligateShampoo** [comment]
I investigated the issue further based on the previous comment. It actually had nothing to do with the OS - I am running Windows 7 (with the Classic theme enabled), not XP. However, I had not updated the base Internet Explorer that the OS shipped with, and upon updating to IE11 this issue was rectified.

**Comment by Karolis2011** [comment]
Please note: Support for Windows XP is dropped because Microsoft failed to update Internet explorer to a newer version for XP, And yes, i you use outdated Windows 7, then it will also not work. It's dependent on IE and IE is dependent on Operating system. (Tho it seems you had updates disabled if you had IE8 on Windows 7 what is still a security hazard)
