### ISSUE TITLE
Vendor bug is tied to new GUI, not Byond?

### ISSUE THREAD

**Issue by Bygonehero** [Aurorastation/Aurora.3#5155]
Whenever the vendors break, the biomass machine in hydroponics does not use the newest GUI. It is still useable even when all other vendors are broken. Those vendors use the newest GUI. I believe the newest GUI is the issue with most of the vendors, not byond.

**Comment by Karolis2011** [comment]
Newest GUI - VueUI
Older GUI - NanoUI
Oldest GUI - HTML snowflakes.
and I am pretty sure I didn't port vendors to VueUi in initial implementation and another DEV -> MASTER didn't happen.
It would be helpfull if you actually explained _What broke_ not just go around and pointing fingers a things.

**Comment by BurgerLUA** [comment]
I don't know exactly the problem but when I emagged a vendor during the vendor glitch, it's contraband section did not update. I need to try this again, however, to confirm it.
