### ISSUE TITLE
Core Slime Mechanics Not Working

### ISSUE THREAD

**Issue by Komotez** [Aurorastation/Aurora.3#5159]
I'll keep it short and sweet:

- Slimes rarely split at full growth
- Previous method of entering the pen when the slimes don't show a face to ensure safety has gone out the window

These two issues are making it nigh impossible to get anything done as xenobio.

**Comment by MarinaGryphon** [comment]
`Previous method of entering the pen when the slimes don't show a face to ensure safety has gone out the window` I don't believe this has ever been a feature, but I may be wrong.
`Slimes rarely split at full growth` This is a known issue, and I'll try and dig up the other issue it was in.
