### ISSUE TITLE
Power networks not seperated by breakers

### ISSUE THREAD

**Issue by Ornias1993** [Aurorastation/Aurora.3#5165]
For ages (months to a year) now, the powernetworks does not seem to work as they should.

What should happen:
- Disabling the breaker should seperate the network behind the breaker, from the main grid (or the network before the breaker to be more precise). This is the case on upstream (bay) and on most of the breakers currently there.
- This should mean that the power network monitor should only show the APC's on the seperated network behind the breaker

What does happen:
- Some of the networks tend to stay connected with APC's outside their powernetwork, even when the breakers is disabled. 
- More interesting it seems that even when all breakers are disabled, some breakers tend to connect to APC's on other powernetworks that should be blocked by two disabled breakers!?

What research has been done:
- I checked the map for wires interconnecting said networks, and there are none.
- tested it ingame, time and time again.

Above behaviour is a shame because it limits the ability of engineers, antags and AI player to influence the powerflow in a more creative maner.

**Comment by Arrow768** [comment]
If that happens again, try to ahelp and ask them to run the "make Powernets" command.
See if that fixes it.
