### ISSUE TITLE
The Cake is a Lie (Cakes can't be baked for some reason)

### ISSUE THREAD

**Issue by CommanderXor** [Aurorastation/Aurora.3#5194]
So for some reason cakes cannot be baked. I've only tested it with the carrot cake but I've done it twice with both results.

The wiki says to combine 5u milk, 15u sugar, 15u flour, 3 carrots and 9u egg yolk in a baking dish and bake it in the oven to produce a carrot cake.

However, when attempting to make it, it bakes shortly after. It produces a 'snack', which is an invisible waffle with no sprite when placed.

It's quite easy to reproduce, you simply combine 5u milk, 15u sugar, 15u flour, 3 carrots and 9u egg yolk in a baking tray and place it into a heated oven, it'll cook a 'snack' item shortly after.

**Comment by NortonDK** [comment]
I made a cheesecake no less than 24 hours ago with no problem

**Comment by dragoslava** [comment]
Tested this, couldnt reproduce it
