### ISSUE TITLE
Korlaaskak cannot be ate

### ISSUE THREAD

**Issue by CrowOfBourbon** [Aurorastation/Aurora.3#5195]
It's apparently slicable, yet when you slice it, nothing happens. It just keeps saying "You sliced the Korlaaska!" and it doesn't actually divide into portions. 

You cannot eat the Korlaaska unsliced. 

You can "poke it with a fork" and the sprite of food shows up on said fork, however, when you go to eat it, it says nothing is on the fork.

The Korlaaska also has a set transfer amount, but that doesn't do anything either.

**Comment by Alberyk** [comment]
Probably caused by #4793
