### ISSUE TITLE
IPCs occasionally become immortal

### ISSUE THREAD

**Issue by Sytic** [Aurorastation/Aurora.3#5227]
Asked to report this by Juani2400.

IPCs, when damaged sometimes, even to their upper bodies, take no damage. This is an extremely odd bug and I've heard of it being done before, but have not seen it in action until today (roundid: bWa-di1J)

![weirdbug1](https://user-images.githubusercontent.com/42949753/45003334-b82bf580-b024-11e8-86bd-8e14543575ae.PNG)
![weirdbug2](https://user-images.githubusercontent.com/42949753/45003338-beba6d00-b024-11e8-8975-5acdbf661aa8.PNG)
As you can see, after the fight ODIN had suffered no damage before any repairs. I ahelped and was then asked to make a bug report.

I don't know how common this is, nor how it triggers, but it's best to keep an eye on this if someone can replicate it.

Thanks!

**Comment by Alberyk** [comment]
Or the other guy was probably at disarm intent.

**Comment by Sytic** [comment]
Does disarm intent completely limit the damage you do at all?

As far as I've seen, other people were being taken down in the fight (Like Muhawir, who got shanked immediately) just fine.

**Comment by BurgerLUA** [comment]
Disarm intent should only do half damage but it's worth looking into. Like I mean throwing a crayon at someone will give them minor bruises, it should show some signs of damage.

**Comment by NonQueueingMatt** [comment]
Fixed
