### ISSUE TITLE
Revolver Cartridge sometimes loads only five instead of six rounds

### ISSUE THREAD

**Issue by Nantei** [Aurorastation/Aurora.3#5229]
Unfortunately I have found this bug incredibly hard to reproduce, but I have at least finally caught it on video. I unloaded lethal rounds, and put in rubbers and it only put in five of six. I later found out it had only put in five by testing it on the firing range. Hopefully the video helps you reproduce or otherwise find the problem. 

https://www.twitch.tv/videos/305689926

**Comment by BurgerLUA** [comment]
Not a bug, actually.

The .357 autoloader or whatever it's called contains 7 rounds, as the weapon it's designed for, the traitor .357, holds 7 rounds.

Your detective revolver only holds 6 rounds.

**Comment by Nantei** [comment]
Issue is I was using 38 autoloader. Also this doesn't happen consistently.
It only loads five out of six rounds, the other transforms into a lethal
round for some reason I think. The second round in the chamber wasn't
loaded, but the other four were. If there were more rounds than space it
probably should be leaving one in the autoloader.
