### ISSUE TITLE
Pathogenic Isolator is all boogered up

### ISSUE THREAD

**Issue by CakeIsOssim** [Aurorastation/Aurora.3#523]
Not a big bug, but the formatting for the isolator is all messed up.

![delet this](https://cloud.githubusercontent.com/assets/15650378/16547442/ed68d628-413b-11e6-8414-3361576faba7.png)

**Comment by CakeIsOssim** [comment]
Actually, it appears that only the first virus logged gets all messed up like that.

**Comment by skull132** [comment]
Closed due to issue clearance.

Not confirmed.
