### ISSUE TITLE
Last transfer vote is still broken

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#5237]
![image](https://user-images.githubusercontent.com/11579997/45133755-4c08d900-b16d-11e8-96cb-93ba1863aec1.png)

**Comment by MarinaGryphon** [comment]
What was the station time?

**Comment by Alberyk** [comment]
![image](https://user-images.githubusercontent.com/11579997/45270254-c25d5200-b471-11e8-89d5-fd2a33e9dd01.png)
Similar case.

**Comment by NonQueueingMatt** [comment]
Seems fixed
