### ISSUE TITLE
Human damagetype checks are not caching

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#527]
all living mobs have vars for things like bruteloss and fireloss, which should be used to track damage totals to the mob.

Right now for humans, these vars are not being used. The functions for getBruteLoss and getFireLoss (and probably some others) work by iterating through external organs and totalling the damage on them. This is done every time these are checked - at least once every life proc. This is unnecessary

These vars should be populated and kept updated when a mob's damage changes, and functions to check damage values should read the cached value in most cases

**Comment by skull132** [comment]
Closed due to issue clearance.
