### ISSUE TITLE
Borgs cannot view security monitor cameras on the console.

### ISSUE THREAD

**Issue by Lemonylight** [Aurorastation/Aurora.3#5301]
What the tin says. As borg, you have full access to each of the cameras - except, when you click on one, your viewscreen/sight is not transported to that camera. Basically, nothing happens when you click each camera node. I've tried relogging, but the issue persists. 

First I've heard of it. Medical borg, Android, normal security camera monitor. Tried on multiple.

**Comment by Arrow768** [comment]
This is intentional to avoid a cyborg playing ghetto ai by getting a security camera and then remote-controlling things through the camera view.
