### ISSUE TITLE
The personal lockers on the surface can be locked from the inside

### ISSUE THREAD

**Issue by Nantei** [Aurorastation/Aurora.3#5302]
As the title says, I am assuming this is a bug because the same behavior does not work on other lockers, although I didn't test comprehensively. 
Steps to reproduce:
1. Unlock the personal locker with your ID.
2. Hop on into that bad boy, then close it up with you inside.
3. Use your ID on the locker again (I specifically used my ID inside a PDA if this ends up mattering), and it will now be locked. It can be similarly unlocked the same way.

**Comment by Sindorman** [comment]
I would say that might be an intentional behavior designed so that you don't get locked inside?

**Comment by Sindorman** [comment]
It is a feature

**Comment by Nantei** [comment]
You can always resist to get out of the locker, and other lockers do not exhibit this behavior. Hence why I submitted it as a bug. If you try and do this with other lockers you get the, "You can't reach the lock" message.
