### ISSUE TITLE
A plethora of turret bugs

### ISSUE THREAD

**Issue by ShameOnTurtles** [Aurorastation/Aurora.3#5328]
- No matter what settings are enabled, turrets will not fire on rested mobs who enter their AOE while resting, via the crawl mechanic. This leads to people being able to crawl past turrets, or up to them to destroy them.

- Doors can be placed over turrets, while turrets can still fire while under the door, leading to them being untargettable by most ranged weaponry.

- Closets are indestructible by turrets, leading to them being used as a barricade that is, well, indestructible and blocks LOS of turrets.

...So maybe not a plethora, but 3.

**Comment by Sindorman** [comment]
- Point 1 can be changed, originally it was to prevent turrets from gunning someone down entirely(before crawling was a thing)

- Point 2 We can fix that easily

- Point 3 is a problem that there are number of things that just simply `don't know` how to be destroyed by being shot. I would note that projectile and pulse turrets can destroy closets and even other things.

**Comment by Geevies** [comment]
I believe this has been fixed.
