### ISSUE TITLE
Disposals area overpressurizes again

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#5374]
The disposals chute in disposals releases gas a lot and overpressurizes without it being removed by a vent. Also, no camera in disposals.

**Comment by BurgerLUA** [comment]
The camera part is fixed however I don't know how to fix the overpressurization without removing overpressurization code.

**Comment by SleepyWolfe** [comment]
It was repaired last time by making the uvent vent downwards to 101.3 kpa as well as venting up, idk how that was done. Lohikar, Fowl, or Juani probably know, i think one of them fixed it last time.
