### ISSUE TITLE
Nutrition is going down way too quickly.

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#5387]
I especially notice it when playing paramedic, where you have to run *a lot*. It was always going down a bit too fast but since the last merge cycle on the 6th of October its really bad now. I was fully nourished, ran literally one time around the general treatment area in the medbay, about 5-7 seconds of running and was back to red (critical) nourishement. I dropped from fully nourished to critical five times in the timespan of 90 minutes.

**Comment by BurgerLUA** [comment]
Thirst/Hunter levels is currently misleading at the moment. There is a fix that's merged, yet to be uploaded to the server.
