### ISSUE TITLE
Weird Issues with Events since slime spawning was added.

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#5397]
![1ca269762a13151a62c8654c3bf474a6](https://user-images.githubusercontent.com/12869074/46681780-98eb2f80-cbb1-11e8-91dc-ada846cdcd62.png)
![411efa849a5db1d4bd8220799519174b](https://user-images.githubusercontent.com/12869074/46681783-9be62000-cbb1-11e8-9664-36e44029921c.png)

Seems to have lost the location of spawn and also probably shouldn't be reporting 'Moderate Vermin Investations', that sounds like a tag that shouldn't be seen by players.

**Comment by BurgerLUA** [comment]
Easy fix. Turns out fake events run differently than real events so I'll just disable fake infestation events.
