### ISSUE TITLE
Latex/sterile gloves don't stop fingerprints

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#540]
Basically what the titles says. If you're wearing latex/sterile gloves and you touch something, your fingerprints appear on it as if you weren't wearing any gloves at all

**Comment by LordFowl** [comment]
Not a bug. Latex gloves transfer fingerprints because they are very thin. In real life they do the same, also.

**Comment by skull132** [comment]
Black gloves are the only things that don't stop prints.

Have always been in SS13.
