### ISSUE TITLE
Security camera monitors have no ID restrictions

### ISSUE THREAD

**Issue by VTCobaltblood** [Aurorastation/Aurora.3#5403]
My main grip with this is that science has very easily available access to them, and legitimate reasons to build them (it's handy to have a camera-gps circuit for telesci, I've also ran other mildly useful gimmicks with circuited cameras), despite this thing being able to overlook high-security areas such as the bridge. There are two options to fix this issue:
1. A separate "research camera monitor" which only has access to the research network, with security monitor circuits being available on illegal research level one, or...
2. Security camera monitors should require you to present your ID before viewing them, opening networks according to your role (everything for wardens and heads of staff, everything except the bridge for common secs, research only for science)

**Comment by Arrow768** [comment]
The solution to that would be much simpler.
Just remove the security camera board.
Modular computers already have the ability to view cams and check for the requires access.

**Comment by shedya** [comment]
Might as well, yeah. Or make them illegal research instead of just being there all the time like it's nothing. The issue is more of a RP one than a balance one, because the security monitor doesn't transmit sound, limiting its usefulness, and nobody cares what's going on in the bridge if you can't actually listen to conversations.

**Comment by shedya** [comment]
Also, now that I've seen how modular computers work - the research configuration doesn't include a camera monitor program in it. Just a notice.
