### ISSUE TITLE
AI cannot change security records rank

### ISSUE THREAD

**Issue by Lemonylight** [Aurorastation/Aurora.3#5405]
An AI cannot change an individual's security records rank (say, from Unassigned to Assistant) as you get a 'rank insufficient'; but the odd thing is that an AI has enough rank to create Captain-access from thin air, but not set security records straight? Ahelped led to a discussion, with the conclusion of: bug. So, here I am.

**Comment by FluffyGhoster** [comment]
I don't believe this is a thing anymore, all you can set in the security records is the arrest status - Feel free to resubmit with an howto if this is still relevant
