### ISSUE TITLE
Advanced batteries don't fit into laptops

### ISSUE THREAD

**Issue by shedya** [Aurorastation/Aurora.3#5410]
![image](https://user-images.githubusercontent.com/17379794/46804711-0b077400-cd6c-11e8-89df-836039946235.png)
nuff said

**Comment by Arrow768** [comment]
Intentional.
Even sais in the description that its too large to be fitted into smaller devices.

**Comment by dragoslava** [comment]
fixed in pr

**Comment by dragoslava** [comment]
https://github.com/Aurorastation/Aurora.3/pull/5338
