### ISSUE TITLE
NTOS copyright has expired

### ISSUE THREAD

**Issue by shedya** [Aurorastation/Aurora.3#5412]
In modular computers, 
![image](https://user-images.githubusercontent.com/17379794/46821636-ec1bd880-cd91-11e8-8228-935aae45c8bf.png)

**Comment by Sindorman** [comment]
Time toey pirate NTOS

**Comment by shedya** [comment]
mfw when can't pirate sudoku onto a research tablet :(

**Comment by dragoslava** [comment]
fixed in pr

**Comment by dragoslava** [comment]
https://github.com/Aurorastation/Aurora.3/pull/5338
