### ISSUE TITLE
The Hydrogen loading KA loads with uranium.

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#5416]
The hydrogen loading KA loads in uranium, and I have a feeling this is a mistake. 
That or it's meant to mislead, in which case nice. Either way, it should be fixed to load mhydrogen or be renamed to uranium loading.

**Comment by shedya** [comment]
There already is a uranium loading KA, so it's definitely a bug

**Comment by dragoslava** [comment]
Fixing this

**Comment by dragoslava** [comment]
https://github.com/Aurorastation/Aurora.3/pull/5338
