### ISSUE TITLE
Maintenance drones cannot enter robotic storage units.

### ISSUE THREAD

**Issue by Aurum22** [Aurorastation/Aurora.3#542]
As the title states. I tried both dragging myself and using right click actions. I did not attempt to type a verb however. I also tried while being hidden.

**Comment by skull132** [comment]
Not a bug.

Drones (unlike cyborgs) are unlimited. If you want to stop playing as one, you're expected to either just ditch yourself near the fabs, or explode yourself via the console. The storage unit is only meant for cyborgs.

**Comment by NanakoAC** [comment]
In addition, its possible for qualified staff (ie, roboticists) to reset a drone by scanning their ID on it.

IIRC this kills the drone if its active, and then requests a new player from ghosts, which should allow an empty/SSD drone shell to be re-filled without needing to spawn a new one, Assuming it's functioning properly, i'd say just go SSD at robotics
