### ISSUE TITLE
Possible Bug: Walking Slow.

### ISSUE THREAD

**Issue by TheLoneWolfer** [Aurorastation/Aurora.3#5422]
Hello All.

This is my first post so be gentle with this one.

I've been experiencing for multiple shifts/rounds that my character always walked slower then any other, 1 second to be exact, some say it's like a Diona Speed (Don't know if i said that correctly). Basically, it only affects your walking speed, even if you have with the 'adjusting' just walk speed on tab on 'No Limit', one of the Admins told me to report this potential 'bug', as i'm doing right now, here's the problem i'm having and I hope also others so it would be checked sooner then later.

Walking speed:Slower then the 'No Limit' setup, even if you change it and go back to 'No Limit' or any other walking temp, your character still walks slower then any other.

Sadly I do not have pictures or clips/I cannot do clips because i'm using a very ancient laptop, I hope people will read this and find a possible solution, thank you.

**Comment by dragoslava** [comment]
@TheLoneWolfer  @skull132  is this still a known issue?

**Comment by Arrow768** [comment]
Were you sufficiently fed / drank sufficiently (the hunger and thrist indicators absent on the right side) ?
