### ISSUE TITLE
Briefcases don't show a sprite when facing the direction opposite of your hand.

### ISSUE THREAD

**Issue by aleXanderDox** [Aurorastation/Aurora.3#5426]
Ideally, the briefcase should be partially visible despite being in the hand opposite of the 'camera' view.

Not visible while in left hand, facing right.
https://puu.sh/BL8oz/3a6e6d8209.png

Visible while in left hand, facing left.
https://puu.sh/BL8oY/85e2833b06.png

Not visible while in right hand, facing left
https://puu.sh/BL8pg/341fc44259.png

It just disappears.

**Comment by aleXanderDox** [comment]
P.S. I made a new Github account because my last one got hacked and then locked. :^)

**Comment by dragoslava** [comment]
Will work on this, pretty easy fix

**Comment by dragoslava** [comment]
fixed in bug fix pr

**Comment by Sindorman** [comment]
@dragoslava just write in your PR somewhere this `Fixes #1234` with number of issue. It will automatically close it when PR is merged. Remember to use "Fixes" or "Fixed"
