### ISSUE TITLE
The Kitchen SmartFridge causes some plant products to disappear.

### ISSUE THREAD

**Issue by Aurum22** [Aurorastation/Aurora.3#543]
I don't know the complete list, but items such as potatoes and fly amanita are able to be placed into the fridge, but no entries are made to withdraw them after.

**Comment by Aurum22** [comment]
As an update, I have attempted to reproduce this bug but I was unable to.

**Comment by Bedshaped** [comment]
Please repost with more information if this is a persistent issue.
