### ISSUE TITLE
The Chemmaster eats reagents

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#5432]
Don't know what exactly happens, but fill a bluespace beaker up with water and put it in the chem master. Hit the "All" button on add to buffer. It will only hold 120 units in the buffer and remove the rest.

**Comment by Doxxmedearly** [comment]
Had this happen to me as well as a chemist. It seems to max out at 120 and the rest just disappears.

**Comment by dragoslava** [comment]
Fixed in https://github.com/Aurorastation/Aurora.3/pull/5338
