### ISSUE TITLE
"owo daddy bars" are not a thing suitable for a HRP server

### ISSUE THREAD

**Issue by shedya** [Aurorastation/Aurora.3#5441]
"owo" is a meme that will die in a month, if not less. Implementing obviously meme-y items and low humor like that really hurts the immersion. Absolutely no-one liked them being added, even as a "halloween gag", because it isn't obvious at all that this is a halloween gag, seeing how it has no relation to sp00ks and stuff. Honestly, the "it's a halloween gag i'm going to remove it" feels like a really tenuous excuse.

**Comment by BurgerLUA** [comment]
They will be renamed in the November 2019 merge.

**Comment by shedya** [comment]
Okay
