### ISSUE TITLE
Character set-up preview displays female characters as male.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#5446]
![image](https://user-images.githubusercontent.com/11053780/47124919-8ffffb00-d24e-11e8-9626-058272793c8f.png)
I don't know why it does this either.

**Comment by verywhiterabit** [comment]
im sorry i cant tell what you mean please give more arrows

**Comment by OneOneThreeEight** [comment]
This is a **preview-specific bug**, not a **gameplay-specific** bug.

**Comment by OneOneThreeEight** [comment]
This is a **preview-specific bug**, not a **gameplay specific bug.** Please read context of issue titles before making an assumption that they are duplicate issues and 100% related to one another.

**Comment by Karolis2011** [comment]
It's same underlying issue - sprites are gender ambiguous. We don't have enough of spriting power to fix it or want to fix it.

**Comment by NonQueueingMatt** [comment]
Fixed
