### ISSUE TITLE
Ninja suit species sprites sheet list does not include all species

### ISSUE THREAD

**Issue by Sindorman** [Aurorastation/Aurora.3#5448]
Ninja suit sprite_sheet list only includes Tajaran and Unathi, Skrell but not Vaurca

**Comment by Alberyk** [comment]
![image](https://user-images.githubusercontent.com/11579997/47158406-fbcf7b80-d2c1-11e8-9ada-8c3f45596f1d.png)

![image](https://user-images.githubusercontent.com/11579997/47158470-1bff3a80-d2c2-11e8-83df-efa6df81da32.png)

The xeno species sprites are working, this is not really a bug. The suit will adapt the sprites for the user.

**Comment by Sindorman** [comment]
@Alberyk Tested it - the problem is that individual piece `sprite_sheet` list only contains Tajaran and Unathi, somehow Skrell still is fine even though it is not there. Adding Vaurca to the list and pointing to the right file fixes it.
