### ISSUE TITLE
Cacoa is missing from the MegaSeed Servitor, packets are bugged to be nameless, spriteless, and have no contents

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#5463]
![1](https://user-images.githubusercontent.com/44004468/47291504-e617ca00-d5d1-11e8-8a04-03478b76ca77.png)
![2](https://user-images.githubusercontent.com/44004468/47291506-e7e18d80-d5d1-11e8-8031-76069af5adf8.png)
![3](https://user-images.githubusercontent.com/44004468/47291509-e7e18d80-d5d1-11e8-93a3-3a23344d370a.png)

**Comment by dragoslava** [comment]
I can take a look at this rela quixck
