### ISSUE TITLE
Significant pressure/temperature difference in the doorway and interior of the kitchen's freezer

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#5464]
![mobldxt](https://user-images.githubusercontent.com/44004468/47306589-dcef2300-d5fa-11e8-8dd3-a671a1304d2a.png)
![knatorz](https://user-images.githubusercontent.com/44004468/47306606-e7112180-d5fa-11e8-84b4-74c8c2ed2373.png)

**Comment by Arrow768** [comment]
I was unable to reproduce that in the second kitchen rework.
