### ISSUE TITLE
Vampires don't retain their standard powers upon cloning

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#547]
Don't think this has been reported yet.

If a vampire is cloned, the only power they keep is the vampire help thing, if they frenzy then they'll also have grapple, but they won't retain their most basic powers, most notably being, Drain blood.

As a note to people inclined to edit variables, this can be fixed by manually adding the verb to the vamp in question.

**Comment by OneOneThreeEight** [comment]
@skull132 Should vampirism even be considered a genetic defect?

**Comment by Geevies** [comment]
Fixed.
