### ISSUE TITLE
Teleportion near Arrivals

### ISSUE THREAD

**Issue by Tbear13** [Aurorastation/Aurora.3#5471]
So, when you're EVA outside arrivals, there appears to be an area that causes you to teleport away from the station, into open space. I encountered it once today, and I've seen at least one other person encounter the same issue.

**Comment by Sindorman** [comment]
Are you sure it was not a hole?

**Comment by Tbear13** [comment]
It wasn't a hole.

**Comment by BurgerLUA** [comment]
Possible cause is that there is a teleport marker there brought over by the centcomm level.
