### ISSUE TITLE
Vaurca sprite bug(s)

### ISSUE THREAD

**Issue by JamOfBoy** [Aurorastation/Aurora.3#5484]
The sprite when vaurca face left is offset slightly, along with what appears to be an elongated foot. I'm not sure of the specifics since it'd be a lot of work, but the easiest way to see what I mean is to compare the very top pixel on the vaurca's head to the cross on floor tiles. On south, north and east, the top pixel is in line with the darkest part of the floor tile cross. On west, however, it is not. Aside from this, the sprite seems to have a lot of issues in general, however I don't know how many, which is probably a bad sign.

I don't really expect this to get fixed - since everyone seems to be already aware of it.

**Comment by OneOneThreeEight** [comment]
Link some screenshots and I'll fix this.

**Comment by OneOneThreeEight** [comment]
It's weird that nobody didn't just use "flip" to create the west facing Vaurca sprite state.

I'll check this out, but you'll have to show me the voidsuit sprites and why they're problematic as well.
