### ISSUE TITLE
Cigarettes blinking

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#5493]
When looking left or right, and using the hand that would make the cigarette visible, the cigarette has a bad habit of blinking out of and back into existence.
This is more than likely a bug.

**Comment by Fortport** [comment]
Can confirm this is a bug after investigation. Icon/sprites are identical for both sides, there's no real reason why it should be blinking.

https://cdn.discordapp.com/attachments/157531783779319808/583926888783937536/f5752ee7d5b47124457150fb0110aab8.png

And here's the bug in action.
https://gyazo.com/fd7e28ccce5deada43dff1a9f95fbcf1
