### ISSUE TITLE
Inhaler issues

### ISSUE THREAD

**Issue by JamOfBoy** [Aurorastation/Aurora.3#5510]
The inhaler vaurca spawn with doesn't actually 'inject' anything on use. Not sure if this applies to other inhalers. Should inject 5 units.

**Comment by BurgerLUA** [comment]
this bug should've been fixed ages ago, I am waiting for a confirmation on if people are using it right or that something went wrong

**Comment by BurgerLUA** [comment]
I found the problem, fixing
