### ISSUE TITLE
Nitroglycerin Cargo Bounty

### ISSUE THREAD

**Issue by Conspiir** [Aurorastation/Aurora.3#5518]
Actually cannot be fulfilled. It explodes immediately on mixing. Like having "napalm" as a bounty.

**Comment by shedya** [comment]
Cryostasis beakers don't help?

**Comment by Conspiir** [comment]
They do not. They only prevent it from mixing period. You'd just have the reactants in a beaker.

**Comment by Arrow768** [comment]
I am slightly wondering if someone tried to mix it in chemistry and got suprised by the resulting explosion.

But yeah. That should be fixed
