### ISSUE TITLE
Bar and Kitchen Camera networks

### ISSUE THREAD

**Issue by JamOfBoy** [Aurorastation/Aurora.3#5524]
Bar and kitchen cameras are in the civilian main network and not service. They are part of the service department, so they should be in service, as the janitor cameras are.

**Comment by BurgerLUA** [comment]
A little bit subjective. I asked around and it was about 50/50 to as where the cameras would be. I suggest making a suggestion thread.

**Comment by Arrow768** [comment]
The service network should contain all the cams in the bar/kitchen/hydro/chapel.
Civilian Main / Service should only contain general areas that dont belong to a specific department
