### ISSUE TITLE
Invisible Walls in Medbay

### ISSUE THREAD

**Issue by Doxxmedearly** [Aurorastation/Aurora.3#5525]
There are invisible walls by two nanomed vendors in medbay; one by the chemistry lab, and one by the door to library maintenance. You can vend items onto these squares and pick them up, but you cannot pass through them. 

Note that this issue existed before today's merge. I was hoping it would be fixed, but it seems to persist. 

Locations:
https://i.gyazo.com/e37e8ae3ed9348bf45703b013aaab5c0.png
https://gyazo.com/8bf8fbc48cfb07aa7318a971198243a9

**Comment by Alberyk** [comment]
Those are the vendedor having their density var set to true, instead of false.
