### ISSUE TITLE
The booze-o-mat dispenses lukewarm drinks instead of cold

### ISSUE THREAD

**Issue by shedya** [Aurorastation/Aurora.3#5531]
Drink in question is the mountain wind, assuming it's the same for other drinks

**Comment by shedya** [comment]
Soft drinks dispensers seem to dispense lukewarm drinks as well

**Comment by shedya** [comment]
Perhaps have a temperature setting on it, maybe even for each particular drink? I don't want my cola lukewarm.

**Comment by BurgerLUA** [comment]
Put ice in it. That's the intended solution.

**Comment by shedya** [comment]
Well, I guess.
