### ISSUE TITLE
Surface-level dorm bathrooms open to space

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#5534]
![image](https://user-images.githubusercontent.com/22651198/47972152-f2cf0000-e05e-11e8-8f44-c0e8d23f3ba9.png)

This is the area on the roof, above the new dorm-level bathrooms. The asteroid surface is randomly generated, and could vent any or all of the three bathroom stalls.

**Comment by BurgerLUA** [comment]
wew, fixing

**Comment by BurgerLUA** [comment]
oh, I thought this was the main level bathrooms, I will still fix even though it ISN"T MY FAULT
