### ISSUE TITLE
R&D spawns with no steel

### ISSUE THREAD

**Issue by carpevenenum** [Aurorastation/Aurora.3#5537]
![image](https://user-images.githubusercontent.com/17379794/47973052-0310ca80-e0b3-11e8-8dd2-a6175b7ad650.png)

i literally can't do anything in r&d now unless i'm let into robotics

**Comment by shedya** [comment]
who even thought that cutting down r&d space is a good idea

**Comment by BurgerLUA** [comment]
I'm starting to get irritated of your remarks inside github as well as on discord. If you wish for bugs to be fixed in a speedy manner, trim the fat. Just go straight to github and report the issue.

**Comment by shedya** [comment]
you're writing it literally under my github issue

**Comment by Sindorman** [comment]
Github is not a place to express personal problems with other people. Please stick to the code/game issues, your comments are fit for either forums or administration.
