### ISSUE TITLE
Surface Power Bug

### ISSUE THREAD

**Issue by flimango** [Aurorastation/Aurora.3#5550]
Surface power was bugged. It was this cable (the corner, going South->West). After cutting and replacing it, then remaking powernets, the entire grid worked fine. Not sure if it's isolated or not. I suspect a similar issue to the roof solars wire bug. 

![image](https://user-images.githubusercontent.com/32926873/47995055-01daa000-e0a9-11e8-8b77-4463be89f308.png)

**Comment by Sindorman** [comment]
Yeah, issue is that someone made their own version of cable on map that uses wrong direction vars
