### ISSUE TITLE
Gmod levels of a glitched mining dungeon

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#5557]
![capture](https://user-images.githubusercontent.com/31339047/48020170-32e7be80-e103-11e8-92e8-d2960236d4aa.PNG)
It was only this dungeon, everything else was fine. Tried logging and clearing cache, other people could see it. was still there. Dungeon was on the construction floor, if it helps.

It also contained  items like "random coin" and "random maintenance loot items" as actual items. Being a coin with  a 1 on it and present respectively. It seems most items were the "random-itemtype".
![capture](https://user-images.githubusercontent.com/31339047/48020399-d1741f80-e103-11e8-8d61-705295152b93.PNG)

**Comment by BurgerLUA** [comment]
Do you have CSS installed?

**Comment by Sindorman** [comment]
It looks fixed by Arrow's PR.
