### ISSUE TITLE
Maintenance drone hatches misplaced

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#5590]
Maintenance drone hatch sprites are all bungled up, they pop up on the right side of the airlock, and in the middle of multitile airlocks.

Issue seem to be on all horizontal mutlitile airlocks and on newly constructed single tile airlocks.

**Comment by BurgerLUA** [comment]
Part of my airlock update. I'll investigate this issue sometimes this week and see what I find.

**Comment by Sindorman** [comment]
![image](https://user-images.githubusercontent.com/25555314/48443387-d52c2580-e745-11e8-9d06-48e9e708f8c1.png)

**Comment by Mwahahahaha** [comment]
![image](https://user-images.githubusercontent.com/3950115/50199994-de389400-038e-11e9-84e7-30c0c2a71525.png)

Another one in the kitchen east connected with diner.

**Comment by Sindorman** [comment]
@Mwahahahaha They are generated, so they are not hard-coded.

**Comment by Pratepresidenten** [comment]
Seems when you create new airlocks, the drone hatch is generated on the right side aswell.
