### ISSUE TITLE
Electrical gloves not protecting against hardsuit shocks

### ISSUE THREAD

**Issue by SimonTheMiner** [Aurorastation/Aurora.3#5592]
When attempting to fix/work on hardsuit modules people still get shocked (same amount of damage, regardless of if wearing gloves or not, about 16 to hands)
https://gyazo.com/4f65d9259da798ad5da82eeb23d0c34b (without gloves)
https://gyazo.com/f1bef66c5c7fb5430d622395ab99cfb5 (with gloves, hand had not completely healed before taking damage again).
Gloves being worn were tajaran electrical gloves.
Another issue is hardsuit modules (unsure if just AMI or all hardsuit modules) will occasionally swap over to electrified without any prior warning, even after they have been put on and deployed safely without an issues before.

**Comment by Pratepresidenten** [comment]
Can confirm, its a pretty nasty shock aswell.

**Comment by dragoslava** [comment]
Fixed in https://github.com/Aurorastation/Aurora.3/pull/6067
