### ISSUE TITLE
"NO ICON" - Body temperature?

### ISSUE THREAD

**Issue by Conspiir** [Aurorastation/Aurora.3#5593]
https://puu.sh/BZNK2/c7a43ab675.png

Hovering over it tells me its body temperature. It appeared when no particular thing was happening. Room temperature was still a happy 20C.

**Comment by Conspiir** [comment]
After another round, I can say that this MIGHT be connected to smoking.

**Comment by Doxxmedearly** [comment]
https://i.gyazo.com/a56c807d0e56ae4a7de477f7af3198e6.png

Same issue. Right after I started smoking. Didn't go away the whole round.

**Comment by BurgerLUA** [comment]
Were you taking any damage?

**Comment by BurgerLUA** [comment]
Follow up question, what exactly were you smoking?

**Comment by Doxxmedearly** [comment]
I was not taking damage. Regular cigarette pack.
