### ISSUE TITLE
Power loss doesn't turn off grav gen

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#5602]
The gravity generator doesn't seem to be to turning off when power is shut down in the area. Fixing this would add a lot of roleplay and cool potential, as well as atmosphere and tactical power use.

**Comment by Pratepresidenten** [comment]
Doesnt shut off when toggled off either.

**Comment by Sindorman** [comment]
![dreamseeker_CtTO1GloS5](https://user-images.githubusercontent.com/25555314/55268973-16802600-524c-11e9-9ecd-bbf618fc6c9f.png)
