### ISSUE TITLE
WELDpatches burns your eyes.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#5625]
Tried welding using the protection matrix and tried welding without. Singes your eyes either way, doesnt protect at all.

**Comment by Sindorman** [comment]
According to code the protection flags are set, and note that the patch does not protect 100%, it is not meant as replacement for googles. It only protects 50% of damage, so you still take it

**Comment by Sindorman** [comment]
If you do not have protection - you get 2 to 4 damage. With patch you get 1 to 2, it was not meant to be used as regular thing.
