### ISSUE TITLE
Two things about meteors

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#563]
Related to PR #562
* The moderate severitry meteor event doesn't showcase a contact warning, unlike the high severity one.
* Please add an admin log for a meteor impact.

**Comment by NanakoAC** [comment]
A contact warning? Do you mean the 'your 3 minutes are up get rekt now' ? Because the lower severity one not having that is intentional

Also, are you sure about the admin log? Thats gonna get spammy, each meteor hits 2-4 times before it explodes as it burrows through objects a bit

**Comment by NanakoAC** [comment]
Disregard earlier comment RE contact warning, i misremembered. It wasn't intentional, it should have had one, and a bug was borking it. Fixed in #573

**Comment by skull132** [comment]
Merged.
