### ISSUE TITLE
New vaurca antenna styles and warriors

### ISSUE THREAD

**Issue by JamOfBoy** [Aurorastation/Aurora.3#5645]
It turns out that, while you can have nice braided antenna, you also retain the regular pre-update ones no matter what, if you are a warrior.

AKA, workers have the hairless sprite, warriors don't, @ParadoxSpace

![image](https://user-images.githubusercontent.com/43283937/48794322-86583000-ecf1-11e8-990a-d7770019122b.png)

**Comment by ParadoxSpace** [comment]
fixin'
