### ISSUE TITLE
Hatches stay during open animation of hazard shutters

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#565]
Related to PR #562 
The door hatch overlay should be cleaned up _before_ the open animation is showcased. That way, you don't have a hatch floating in the middle of the door.

**Comment by NanakoAC** [comment]
Only applies to hazard shutters. Normal airlocks work fine

**Comment by skull132** [comment]
Nooope, they don't.

Any airlock on the test server does its open animation, and _then_ cleans up the overlays. This leaves the hatch standing out from the ground as if it's some kind of odd codpiece.

![Bad opening animoos.](http://puu.sh/q0cjC/7950da7370.png)

**Comment by skull132** [comment]
Merged. Above reply seemed to be a clientside issue with using a BYOND version below 510.
