### ISSUE TITLE
Ballistic weaponry in circuitry weapon firing mechanisms has infinite ammo

### ISSUE THREAD

**Issue by VTCobaltblood** [Aurorastation/Aurora.3#5650]
Specifically, tested on .45 pistol

**Comment by Arrow768** [comment]
I am inclined to say this is not a bug, as the firing mechanism would otherwise be quite limited if it could only shoot 6 times before having to be reloaded.

So far this isn't abused (to my knowledge).

Do energy weapons also have infinite ammunition ?

**Comment by MarinaGryphon** [comment]
Make sure you weren't using a chameleon gun set to a .45 pistol.

**Comment by MarinaGryphon** [comment]
This is, in fact, a bug. It doesn't drop casings, they remain in the magazine, allowing them to be re-fired.

**Comment by MarinaGryphon** [comment]
It is NOT infinite ammo. Instead, after the ammo is used, it continues to fire without producing a projectile.
