### ISSUE TITLE
Changelings suffer irreparable mental traumas on death

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#5654]
When a changeling suffers damage to the point of gaining mental traumas and then death, the trauma becomes bugged in a way that it is unable to be cured either by regular medicine or even admin commands, possibly due to the fact that they are technically dead. This can also leave them unable to use abilities such as reviving when dead, effectively leaving them locked in death despite not having "really" died as a ling.

**Comment by Doxxmedearly** [comment]
Closing since brainmed update removed traumas happening due to damage.
