### ISSUE TITLE
Engineering Tool Vendors still have limited stock

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#5660]
A little while ago PR #5316 was meant to stop making the vendors in Engineering suffer randomized stock, however it only affected the EngiVend machine, and not the YouTool machine, which still has random and often annoyingly low levels of stock.

**Comment by Arrow768** [comment]
That was intentional.
Youtools are placed in multiple locations throughout the station.
They definitly should have a random stock.

However, I am not opposed to changing *only* the youtool in engineering to have a constant stock.

**Comment by furrycactus** [comment]
That would be godly
