### ISSUE TITLE
Skrell randomely loose telepathic ability

### ISSUE THREAD

**Issue by Sindorman** [Aurorastation/Aurora.3#5662]
Was reported by several players and witnessed by me that some skrell do not have telepathic ability. They assumed to spawn with it and at some random point loose it. I checked one of the victims and they were missing the proc, I couldn't find the cause yet

Edit: also skrell who lost telepathic ability receive message from another skrell who used telepathy as if they are non-skrell.

**Comment by Kaedwuff** [comment]
Clearly, this is a natural phenomenon - Some skrell simply have weaker minds than others, or suffer psi-sleep disorder.
