### ISSUE TITLE
Synth gasping

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#5664]
Shell started to gasp, and not be able to say full words after being strangled on kill intent.

**Comment by TheOrleans** [comment]
If this is going to be changed, I suggest adding some kind of accumulative damage to the voice synthetizer (or however the part of the synth that produces words is called) and at some point, it starts having failures or even finally not working at all.

**Comment by LadyFowls** [comment]
Duplicate
