### ISSUE TITLE
Teleporting HoverPods

### ISSUE THREAD

**Issue by TheOrleans** [Aurorastation/Aurora.3#5673]
I tried going upstairs (from Security Main Level to the Level with the firing range) while inside an hoverpod

It teleported me to outer space, a bit to the right of red dock

https://i.gyazo.com/baa925e410a782c6bb5c480eff40d4d1.png

**Comment by TheOrleans** [comment]
Up

**Comment by JohnWildkins** [comment]
hoverpods are gone
