### ISSUE TITLE
General Ballistic Weapon - No Sprite

### ISSUE THREAD

**Issue by TheOrleans** [Aurorastation/Aurora.3#5675]
Easy.

There's an item called ''general ballistic weapon'' without sprite. I bought it as Merchant. Pratepresident told me it probably was a mounted weapon

https://i.gyazo.com/d81bca497d0e79cd5061e2068fd2ce43.png

**Comment by LordFowl** [comment]
The item should not be available at all.

**Comment by TheOrleans** [comment]
> The item should not be available at all.

Found it in a Vox Merchant that only wanted trading (not credits). The description of the shuttle was something like UNIDENTIFIED SHUTTLE or something like that. And the name was a vox name, something like AXAKAPAKRMANK xD
