### ISSUE TITLE
Hydroponics Bot - Auto Water/Fill Issue - Weeding

### ISSUE THREAD

**Issue by StationCrab** [Aurorastation/Aurora.3#5677]
The Hydroponics bot that is made by the Roboticist is refusing to fill it's water tank, and is endlessly trying to water a tray without having any water in it's tank.

It also seems to refuse to weed trays.

All glass enclosures are retracted, and the issue persists. Harvesting appears to work fine.

Pictures of settings and a log of it's activity: https://i.imgur.com/P4SNSMg.png

Further testing shows removal of dead plants is functioning, but weed removal is not working.

**Comment by Sindorman** [comment]
Issue with tank is that some code made bot have two tanks, so basically it would try to fill the other tank and not use the main tank. I will fix!

I will test more about weeds removal

**Comment by Sindorman** [comment]
Tested weed, it cleans weeds perfectly. It just cleans them actually before they even appear as an alert on the tray. I have bumped it to clean only when tray shows alert
