### ISSUE TITLE
New Phoron Salt Chemicals not Working

### ISSUE THREAD

**Issue by resilynn** [Aurorastation/Aurora.3#5698]
Injected 30 units of mutone, followed by 30 units of venenum.  Got flavor text about them working, but no mutation and no change in my appearance.  They don't appear to be working.

**Comment by BurgerLUA** [comment]
What was your species? What messages specifically displayed?

**Comment by BurgerLUA** [comment]
Found the bug. It is a fault of float point precision in temperature calculations and not an issue with the chemicals themselves.
