### ISSUE TITLE
Cocktail temperatures are too high

### ISSUE THREAD

**Issue by VTCobaltblood** [Aurorastation/Aurora.3#5702]
Tested on the following:
Cuba Libre - 2 rum, 1 cola - strength 10 - comes out lethally hot. (doesn't seem to actually damage the character)
Syndicate Bomb - 1 part whiskey cola, 1 part beer - strength 65 - comes out burning hot.
Pousse-Cafe - 1 brandy, 1 green chartreuse, 1 yellow chartreuse, 1 creme de menthe, 1 grenadine - strength 15 - comes out molten hot. (does not damage the character)
Sbiten - 1 capsaicin, 10 mead - strength 40 - comes out warm, which is correct! though can be a tad bit higher, up to hot (unrelated, but it also got incorrect flavor text - "warm hot and spice")
Gargle Blaster - 2 vodka, 1 gin, 1 whiskey, 1 cognac, 1 lime juice - strength 50 - comes out burning hot.

**Comment by Conspiir** [comment]
Also true for Cactus Tea (1 part Xuixi Juice, 1 part iced tea) - Comes out lethally hot without damage.

**Comment by MarinaGryphon** [comment]
Requires confirmation that this is still a current bug.

**Comment by MarinaGryphon** [comment]
Okay. Fix incoming.
