### ISSUE TITLE
Farmbots still aren't fixed.

### ISSUE THREAD

**Issue by Menown** [Aurorastation/Aurora.3#5718]
Despite numerous attempts to fix, they still aren't filling themselves at the hydroponics sink.

**Comment by Sindorman** [comment]
![2018-12-06_li](https://user-images.githubusercontent.com/25555314/49630968-21653100-f9a5-11e8-889a-11aa3ab6359b.jpg)
I am 99% sure that this *dense* rack is a cause.

**Comment by Sindorman** [comment]
Remember that farmbots need to see the sink, it must be in field of view in order to use it. They see only 7 tiles, which is I think 1 tiles less than mobs, and obstacles also close stuff.

**Comment by Menown** [comment]
> Remember that farmbots need to see the sink, it must be in field of view in order to use it. They see only 7 tiles, which is I think 1 tiles less than mobs, and obstacles also close stuff.

https://i.imgur.com/h777C8W.png
The rack being there or not being there. I dragged the empty bot to the sink and it continued to ignore the sink and go try to fill a tray while empty.

**Comment by Sindorman** [comment]
Yeah, I know. That is because it was coded in to attend to the trays before doing anything else

**Comment by Menown** [comment]
@Sindorman I see the newest pull. Thanks, Poze <3
