### ISSUE TITLE
I can give myself unlimited power (watts/energy)

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#5730]
I was AI. I assume one of the traitors cut the power to the vault because it wasn't working and the power itself drained. I do not know why I tried this, but I spammed the APC on button hoping that it would come on or give me 3-4 frames of power.

Turns out it gave me power despite the APC having no charge. I do not know if there was any incoming power but this is what was happening. It would be nice if someone could reproduce this bug.

**Comment by Sindorman** [comment]
The issue name is misleading, I though you meant yourself as in admin power
