### ISSUE TITLE
Hatch layering issue

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#574]
![Image of bad layer](http://puu.sh/q0bOS/572e40e9a5.png)
This seems to happen whenever an emergency shutter is down with a firelock as well.

Fortunately, movement is properly restricted. So it's just a layering issue.

**Comment by NanakoAC** [comment]
Already fixed in #573

**Comment by Arrow768** [comment]
Closed since related pull has been merged already
