### ISSUE TITLE
The Tesla Power Generation Device Does Not Produce Rotund 3-Dimensional Spheres of Orbital Energy As Expected 

### ISSUE THREAD

**Issue by ParadoxSpace** [Aurorastation/Aurora.3#5749]
The tesla has a feature in which it generates orbiting mini-tesla balls. If it has enough energy, it may even perform fission. Yet, it does not do this. It plays the noise that signifies it will, but it only freezes for a half second and proceeds to not do that.

**Comment by HetNeSS** [comment]
It was been removed for the server FPS purpose, as far as I've remember, as being a little bit heavy in the matters of server memory

**Comment by Huenererschrecker** [comment]
Not true actually. I've seen the Tesla form orbiting balls a few times, they do vanish however the moment the ball shoots a lightning. It happens, just very very rarely.

**Comment by HetNeSS** [comment]
I've heard it's the one the balls rotation that matters

**Comment by ParadoxSpace** [comment]
This is still an issue.
