### ISSUE TITLE
Vamp round started without vamps.

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#5756]
What the title says. On a lowpopish round, vamp was chosen by secret, but there were no vampires.  So the round started without antags.

**Comment by BurgerLUA** [comment]
Right so I'm not entirely sure if my PR actually fixes this considering there are a ton of factors, some intentional, that could cause this issue.

More information is needed for this bug report and I cannot say whether or not its fixed because of this.
