### ISSUE TITLE
winter coat hood doesn't work

### ISSUE THREAD

**Issue by nursiekitty** [Aurorastation/Aurora.3#5762]
attempting the "toggle coat hood" command displayed this message

You must be wearing the hydroponics winter coat to put up the hood!

only tested with hydroponics coat. alb tried to fix the issue on the server to no avail.

**Comment by VTCobaltblood** [comment]
Can't reproduce. You do need to wear the coat when putting up the hood - and when it's worn, the hood is being put up just fine.
![image](https://user-images.githubusercontent.com/17379794/50216962-5b1c3b80-0398-11e9-8028-388121b4092e.png)

**Comment by makkenhoff** [comment]
Also having this issue at the moment. it's not the first time, but it was the first time I bothered to report it, after asking around in OOC to see if anyone had suggestions.
