### ISSUE TITLE
Visitors not starting, even with enough antagonists ready

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#5772]
18+ people readied, we got the message not enough antags were ready. At least four people said they had wizard + ninja enabled. Seems a possible glitch with the wrong message, or not starting.
![capture](https://user-images.githubusercontent.com/31339047/50047816-66672280-008b-11e9-8351-bc1e0335f35b.PNG)

**Comment by BurgerLUA** [comment]
This is fixed by #5761

The bug had nothing to do with my new system, but an error of a previous system.
