### ISSUE TITLE
Cameras dead spots

### ISSUE THREAD

**Issue by Sindorman** [Aurorastation/Aurora.3#5795]
Here are screens of all dead spots for cameras
![2018-12-17 4](https://user-images.githubusercontent.com/25555314/50139060-6ca8fa80-0255-11e9-89d5-a86ef6f86e3e.png)
![2018-12-17 6](https://user-images.githubusercontent.com/25555314/50139061-6ca8fa80-0255-11e9-91e2-a3f12faefa05.png)
![2018-12-17 8](https://user-images.githubusercontent.com/25555314/50139062-6d419100-0255-11e9-95d8-5ee357b76fcc.png)
![2018-12-17 9](https://user-images.githubusercontent.com/25555314/50139063-6e72be00-0255-11e9-83f4-29c34ac50c2b.png)
![2018-12-17 10](https://user-images.githubusercontent.com/25555314/50139064-6e72be00-0255-11e9-9ddd-ba0d8c0b7e25.png)
![2018-12-17 11](https://user-images.githubusercontent.com/25555314/50139065-6f0b5480-0255-11e9-839d-9da0b04447fb.png)

**Comment by Sindorman** [comment]
![2018-12-18](https://user-images.githubusercontent.com/25555314/50140183-ba733200-0258-11e9-8e1b-bd58f68257e2.png)

**Comment by VTCobaltblood** [comment]
intentional functionality :^)
