### ISSUE TITLE
Chameleon projectors can make their user invisible if used on an item without a valid itemstate to the base item

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#5798]
This includes cases such as clothing without actual item-states and mutated plants in particular. The former case is easily understood as there are clothing items in the game with invalid item sprites whether because the path is written incorrectly for the specific item or the sprite itself that it tries to reference doesn't exist in the dmis.

Only a few clothing items suffer from that issue, however. In the latter case this is far more abuseable because a "mutated apple" for instance does not seem to change the intended displayed holoprojection as what the "mutated apple" is adopting as part of its own individual icon. You'd think the holoprojector would display the mutated apple's base itemstate such as for the apple that the mutated apple is supposed to take on as part of its appearance.

In either case, this can be abused to make an individual **completely invisible** to everyone else. Nothing short of throwing objects around or shooting the thin air will reveal these people.

**Comment by Sindorman** [comment]
Or just ahelp it, because that is powergaming - abuse of bugs.

**Comment by OneOneThreeEight** [comment]
My hope was that this could be fixed somehow rather than having to leave it open-ended just for the admins to deal with.

But the answer is understandable since I don't see an easy way to fix this

**Comment by Sindorman** [comment]
I mean, the only proper way is to somehow be able to check that sprite states that we are trying to safe actually is in the DMI. And that still does not guarantee that the sprite the item is used for has good sprite, it could be like a pixel - and it technically is legit but a sprite bug. Restricting chameleon project to certain things is not a good idea either, given that it already has a psuedo-whitelist

**Comment by OneOneThreeEight** [comment]
Closing issue. No sane fix to this issue without a comprehensive overhaul to the camo projector.

And who even has time for that, really?
