### ISSUE TITLE
Captain PDA's cart is NULL

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#5821]
The captain's PDA on roundstart has a cart called NULL.
![capture](https://user-images.githubusercontent.com/31339047/50372752-4ad7ac80-05a2-11e9-9fce-822630c20816.PNG)

**Comment by Geevies** [comment]
Is this still a thing?

**Comment by Yonnimer** [comment]
Not anymore. I'll close this.
