### ISSUE TITLE
Janitors don't get access to the general cargo area. 

### ISSUE THREAD

**Issue by verywhiterabit** [Aurorastation/Aurora.3#5822]
Janitors are restricted from entering the main level cargo office, and the surface cargo dock. This is contrary to janitor's basic access to security, science, engineering, and medical. I'd assume this is an oversight unless cargo is for some reason meant to be an exception to this trend.

**Comment by dragoslava** [comment]
https://github.com/Aurorastation/Aurora.3/pull/5852 Fixed in this
