### ISSUE TITLE
Line breaks are missing from the pAI screen for security/medical records

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#583]
When using the Medical Records and Security Records modules as a pAI, the information listed under 'Important Notes' (Basically the player entered records) are missing all line breaks, making it a relatively unreadable jumbled mess of text.

Here's what a pAI sees: http://imgur.com/4blL8Ol
Here's what that record looks like with proper line breaks: http://prntscr.com/bsxc9l

**Comment by Bedshaped** [comment]
This issue is also present for the printed medical records that appear in the filing cabinet in Med Lobby.

**Comment by skull132** [comment]
Fixed in #1987
