### ISSUE TITLE
Misleading text colour for Vampire ability (Dominate)

### ISSUE THREAD

**Issue by GMR25** [Aurorastation/Aurora.3#586]
The ability noted in the title, Dominate, uses the same colour for it's message to the 'victim' as the OOC colour for Moderators. This can naturally be very confusing if you've learned to filter out OOC chat with your eyes, and with how the preceding message is coloured red.

Preferable fixes would be Red + Bold to be noticeable and match the preceding message, or Purple + Italics to match the messages from the Alien whisper ability and to be very visibly unique.

**Comment by skull132** [comment]
Shit, I forgot about this when I was doing my vampire shit.
