### ISSUE TITLE
Prevent char names from being changed

### ISSUE THREAD

**Issue by Arrow768** [Aurorastation/Aurora.3#588]
Once you create a character with a given name, you should not be able to change that name anymore without proper reason.

Background Info:
Every char got a unique id. Should CCIA file a action against a char, the id of that char is linked to the id of the action.
Should the name of the linked char be changed, this messes up the ccia actions and causes actions to be associated with different chars.
Therefore char name changes should be prevented and only be done by contacting ccia.

**Comment by Bedshaped** [comment]
Making it like it is on Apollo where names can't be changed would be a good step IMO.

**Comment by skull132** [comment]
Question, what if accidental mistype, or what have you? Maybe a grace-period of roughly 72 hours where you can change stuff like that. Easy enough when you implement a `created_at` column, and then, whenever a character is downloaded, use something like this:

`SELECT ... DATEDIFF(DAY, created_at, NOW()) AS character_age ...`

And when binding columns:
`can_modify_name = text2num(query.item[whatever]) > 3 ? 0 : 1`

This requires `var/can_modify_name` for datum/preferences.

**Comment by Bedshaped** [comment]
Delete and start again? Name is usually the first thing I set when making a
char so I doubt stuff is lost with a mistype.

**Comment by skull132** [comment]
Delete and start again is kinda crude, and would populate the database with junk characters relatively often.

It's very unlikely that a character gains tangible punishment within the first week, really, so I don't see a reason for _not_ doing this.

**Comment by NanakoAC** [comment]
i'm not liking this idea personally, people often want to rework and severely edit their characters
if theres problems with people abusing namechanges to evade CCIA, i'd rather see that dealt with as it arises, with admn action

**Comment by Bedshaped** [comment]
I don't expect people would namechange to evade CCIA, but it still messes up the fact that there are character IDs which could have specific actions against a specific character, not to mention the fact that characters have separate CCIA records now. You can't have a CCIA note in someone's record for Joe Bloggs and have that person start playing as John Smith on the same character ID. The only way to stop this happening is to make character names as permanent as character ID numbers.
