### ISSUE TITLE
Qdel of power cable does not update powernet propely through Z level

### ISSUE THREAD

**Issue by Sindorman** [Aurorastation/Aurora.3#5883]
When you cut/delete/remove cable, it does not properly update the powernet. Making one side of the net still connected to the other side, but the other side looses a chunk of net that creates a third it's own net that is not connected to anything.

Steps to reproduce:
Best example is to cut cable on the T-comms level that connects main grid to the T-comms. The T-comms side remains connected, while 10 cables that go to maingrid will create their own net that is not connected code-wise to the main grid(physically is).

**Comment by Sindorman** [comment]
This is creates the issue of #5165  and #5655

**Comment by Ornias1993** [comment]
You my sir, did some good work!

**Comment by Sindorman** [comment]
Update, after digging deeper I assume that the issue is in the `cut_cable_from_powernet()` which does not account for Z levels in my theory
