### ISSUE TITLE
N2O Scrubbers do not deploy or are not accessible by the warden

### ISSUE THREAD

**Issue by shyzus** [Aurorastation/Aurora.3#5898]
This is related to issue #2409.

The huge air scrubbers in the communal brig are not operable by anyone.
This renders the N2O system as useless and more or less an accident waiting to happen.

Please add a console or button to enable/disable the huge air scrubbers.

**Comment by Sindorman** [comment]
There is a console for next to Borg's charging station
![2019-01-05_li](https://user-images.githubusercontent.com/25555314/50731739-fcd5b380-1120-11e9-9f13-060f0ca024df.jpg)
