### ISSUE TITLE
Double Clicking

### ISSUE THREAD

**Issue by coolbc2000** [Aurorastation/Aurora.3#590]
I have no idea if it is just me, but I have to fucking double click everything, this also applys to when I have to search/strip someone, it won't open the tab. It also applys to when I am shooting, so I have to double click to shoot... It's random when it wants to be that way

Yesterday (16/07/2016) I was having no problems, Yet today, I am having this double click problem.

**Comment by skull132** [comment]
There were no modifications done to the server inbetween yesterday and today.

It could be latency, or your computer related.

**Comment by coolbc2000** [comment]
Very possible, Internet is always good... Maybe a Byond problem.

**Comment by skull132** [comment]
Well, whatever it is. It ain't a bug.
