### ISSUE TITLE
Headphones are able to be infinitely replicated

### ISSUE THREAD

**Issue by Chen-Yakumo** [Aurorastation/Aurora.3#5935]
The headphones that can be spawned with in the loadout menu are one item that take up two equipment slots (LEar and REar). One headphone is tiny, and one is huge. If you try to replace one of the headphones with another ear-wearable item, you'll unequip that headphone and equip the other item, which seems to have a high likelihood of vanishing forever. However, you now have two headphones that work as two separate items. Putting either pair on results in another headphone spawning to take your other ear. You can repeat this indefinitely.

I found this out because I was trying to see if I could combine my comms headset with them to be cheeky and have both comms and the music icons while being a miner.

**Comment by alsoandanswer** [comment]
i think an easy fix would be to replace headphones with airpods

**Comment by Geevies** [comment]
I believe this was fixed.
