### ISSUE TITLE
Librarians-Book Bags

### ISSUE THREAD

**Issue by SilverTalismen** [Aurorastation/Aurora.3#5944]
Librarians spawning in tend to not spawn with the book bags, I've noticed it as my Librarian over two shifts played as her that I've not spawned with the Book bag after passing through to board the arrivals shuttle. I'm not sure if it's due to a loadout issue or something else.

**Comment by dragoslava** [comment]
Cant replicate this, did multiple tests and I havent had this happen, even on the normal server. Open if it starts happening again
