### ISSUE TITLE
TCFL pods are bugged to all heck

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#5962]
TCFL pods are super janky. Apparently as a 'vehicle', you're capable of buckling onto them but you can't unbuckle from it. The buckling feature should be removed.

The single-click feature seems to work OK, but it also bugs out and traps people into the pod if they try to enter a pod with another occupant inside it already.

Furthermore, you can 'throw' objects while contained within the drop-pod, which will inevitably contain the item in a pocket dimension in the void.

They have no eject feature from the outside, which makes matters worse if you're trying to help someone trapped in one without admin assistance.

**Comment by NonQueueingMatt** [comment]
Seems fixed now
