### ISSUE TITLE
Damaged RIG Control Modules Shocking Through Insulated Gloves

### ISSUE THREAD

**Issue by SeniorScore** [Aurorastation/Aurora.3#5968]
As title states. Makes repairing them an _absolute bitch_. Easily reproducible with randomly spawned hardsuits that are damaged. I would assume otherwise damaged ones as well, but I've never had it come up in other cases outside of spawned ones.

**Comment by Pratepresidenten** [comment]
There's already a report up for this: https://github.com/Aurorastation/Aurora.3/issues/5592
