### ISSUE TITLE
Non-wizards using wizard gear

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#597]
The above should fail. But it should fail in a spectacular fashion, IMO.

Teleport scrolls simply spoofing up smoke, or taking you to a random direction.
A staff of change changing you.
The crystal ball should burn you and probably give you messages about your mind being RIP.
Etcetera. Etcetera.

**Comment by Serveris** [comment]
Brain/eye damage to the orb would be interesting as well. This is p long overdue. Tired of yelling at security officers that touch all the wizard's shit after taking possession of it.

**Comment by OneOneThreeEight** [comment]
Deal 30 brainloss to anyone that makes an attempt in gazing beyond the physical world with an untrained mind. Sounds fine to me!

**Comment by NanakoAC** [comment]
fixed in #650
