### ISSUE TITLE
Missing walkway/stairway

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#5987]
![image](https://user-images.githubusercontent.com/22485266/51772796-f3ee5700-20ba-11e9-9853-941879bc7382.png)

There's a walkway that was there, but is now just a wall. This mapping error has irked me one too many times, and I'd like it fixed. It is clearly still meant to be a walkway.

**Comment by dragoslava** [comment]
where is this exactly

**Comment by fernerr** [comment]
It's the place behind the curtains in the east side of the bar.
