### ISSUE TITLE
Broken cloak sprite

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#6007]
The taj gruff cloak seems to be missing sprites on the front-facing ones. Looks fine on the back, nopes out on the front. The MES patch is all over the place aswell, but its under a separate report iirc.

![bilde](https://user-images.githubusercontent.com/20225964/52063271-93f02880-2572-11e9-89dd-7f8a28756dc6.png)

**Comment by VTCobaltblood** [comment]
It's a flat icon issue, pretty sure. It should look fine ingame
