### ISSUE TITLE
Manifest issues

### ISSUE THREAD

**Issue by JamOfBoy** [Aurorastation/Aurora.3#6041]
As it stands, manifests on PDAs do not update once you spawn in. They do not even update to include your character.

![image](https://user-images.githubusercontent.com/43283937/52525475-3d859700-2ca2-11e9-92d4-918d96db7029.png)

In this example, aside from me being a security officer that wasn't showing on the manifest, there was also an assistant.

**Comment by Geevies** [comment]
I believe this doesn't happen anymore.
