### ISSUE TITLE
Records are now so secure you cannot print them anymore.

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#6042]
What the title says. The update to records makes it impossible to print them, due to the absence of a print button.

**Comment by Sindorman** [comment]
That is not an update, it is part of test-merge PR that is in testing live.

**Comment by Karolis2011** [comment]
#4878 is where you should have contained.

**Comment by soryy708** [comment]
Now the sec' records console update is live, and this regression is present in the live version of the game.
