### ISSUE TITLE
The balaclava sprite sits overtop of hoodie hoods

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#6044]
![bwmqmnw](https://user-images.githubusercontent.com/44004468/52544925-e820b700-2d81-11e9-9cba-1afe8465107f.png)
![self22n](https://user-images.githubusercontent.com/44004468/52544926-e951e400-2d81-11e9-84d6-aeef68f62427.png)
 
Haven't tested it on anything else, there could be other conflicts.

**Comment by VTCobaltblood** [comment]
Does this persist with winter coats?
