### ISSUE TITLE
When unbuttoned, the rear hoodie sprite clips through your entire character sprite

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#6045]
![pqenk95](https://user-images.githubusercontent.com/44004468/52545016-5bc2c400-2d82-11e9-8383-74c628628474.png)

Seems to just be an alignment issue.

**Comment by sheeplets** [comment]
@VTCobaltblood

**Comment by VTCobaltblood** [comment]
FUCJ
