### ISSUE TITLE
AOOC deactivated by genetic powers?

### ISSUE THREAD

**Issue by RyanFalco** [Aurorastation/Aurora.3#605]
AOOC was used at the start of the round, but when a genetic anomaly gave me powers mid-roundish, it disabled AOOC talk for me. I could still hear it, but I couldn't speak it.

( I'm not 100% the genetic powers were the cause. But I had the see-through-walls power. )

**Comment by skull132** [comment]
AOOC cannot be de-activated by genetic powers.

It can only be de-activated by relogging, which most likely happened. Closing issue due to invalid report.
