### ISSUE TITLE
Shell Pronouns

### ISSUE THREAD

**Issue by ParadoxSpace** [Aurorastation/Aurora.3#6082]
Shell pronouns are automatically set to 'it' instead of 'he' or 'she'.

**Comment by Sindorman** [comment]
More detail? Where exactly is it. In Examine?

**Comment by Pacmandevil** [comment]
any use of it's gender - probably getting overwritten at the species level or something due to IPC

**Comment by ParadoxSpace** [comment]
In examine, yes.
