### ISSUE TITLE
Laser prototype bugs/oversights

### ISSUE THREAD

**Issue by VTCobaltblood** [Aurorastation/Aurora.3#6087]
* **Laser prototypes break *absurdly* fast.** 3 shots is enough to make them short-circuit every single shot afterwards, if you're really lucky and it doesn't do that just straight away. In testing, capacitor condition never rose up from 0 in VV. You can't even make a laser tag gun that doesn't immediately break down. It might be worth it to revise reliability/criticality mechanics completely, because it's nigh impossible to make guns that would be in any way superior to what security already has (which is point of RnD, no?) purely because all of them jam constantly; such as only making guns fail if they're modified.

* A lot of protogun parts are still not printable in RnD, even though they probably should be, like the enhanced grip or whatever the flayer modulator is. 

* The name symbol limit is restrictively small. Could appreciate a 5-10 symbols increase.

**Comment by LordFowl** [comment]
The first point, aka the bulk of this issue, cannot be replicated. As per your request, I've successfully both tested out a laser tag gun that lasted over ten shots and created a weapon where the capacitor condition increased above 0.
