### ISSUE TITLE
Melted Monkey Re-Appears

### ISSUE THREAD

**Issue by schwem00** [Aurorastation/Aurora.3#6088]
Round ID bYW-dfSu

I was the xenobotanist and made unstable extremely potent death nettle. Basically a cloud of polynitric acid when thrown. I tested it on a monkey in xenobiology. Strapped him to an office chair, put him in one of the slime chambers (an empty one, no slimes involved), and threw the death nettle at him. As expected, he melted into grey goo.

However, the monkey re-appeared a few tiles from me. I couldn't interact with him in any way (no pulling him around, for example). Examining him said he was still in the office chair and had severe burns, which is how I knew it was the same one.

Here's a picture of the situation. You can see what happens when examining the monkey.
[Monkey](https://imgur.com/a/77Nljx4)

**Comment by dragoslava** [comment]
I actualy found the issue with this.

	// Bluespace tomato code copied over from grown.dm.
	if(get_trait(TRAIT_TELEPORTING))

You had this trait which acts like its melted but just teleports them, I assume its glitching with the chair. I can see about fixing this

**Comment by Ratvar** [comment]
Yes, this is "teleportation doesn't unbuckle mobs" bug
