### ISSUE TITLE
Doctors not spawning with advanced first aid kits

### ISSUE THREAD

**Issue by Meltharas** [Aurorastation/Aurora.3#6116]
Whenever I log in on my doctor character, they no longer spawn in with the red advanced first aid kit. This is unusual, as lower ranked medical personnel like EMTs and Paramedics still do. The kit is not even in my character's inventory, it is simply not given to me anymore.

**Comment by Warbidon** [comment]
I can confirm that I also experienced this as a surgeon.

**Comment by Sindorman** [comment]
Not a bug, It was intentional change. Doctors are not EMT, so they do not have medkit by default, so they don't run around save people instead of EMT. ask @Arrow768
