### ISSUE TITLE
Ice Instantly Melting

### ISSUE THREAD

**Issue by Meltharas** [Aurorastation/Aurora.3#6119]
I have noticed that ice has been instantly melting when dispensed. This has been a constant issue where the moment the ice leaves the machines it is instantly water. Is there some way this can be fixed so that drinks can be more than lukewarm and iced drinks can be properly chilled and not taste of water?

**Comment by niennab** [comment]
I wanted to add to this in that because the ice melts too quickly, there are actually some drinks in game that are impossible to make. IE: Bahama Mama
