### ISSUE TITLE
Sprites for Itanimulli cyborgs (COFFIN) not registering when name is entered.

### ISSUE THREAD

**Issue by NiftyBaby** [Aurorastation/Aurora.3#6123]
bY0-dL2g

Attempted to put in name; sprite did not appear. Yonnimer helped verify that it was a bug by respawning player and assuring that the issue was not simply a misspelling of the name by providing a respawn and then looking into the issue themselves.

This leads to modules lacking the custom category and therefore keeping the player from selecting anything but pre-existing sprites.

Unknown if this is present for others.

**Comment by dragoslava** [comment]
Moreso a clerical error with the config

![notepad_tap6jbn3to](https://user-images.githubusercontent.com/43487478/54009203-cb786480-411e-11e9-9325-9de405ed465c.png)

He has a invalid name in the config which is a simple fix Arrow or Skull can perform, however this isnt a bug really
