### ISSUE TITLE
Chemistry Bug - Breaking the Law of Conservation

### ISSUE THREAD

**Issue by Smithead** [Aurorastation/Aurora.3#6144]
Bug occurs following this procedure:

* Make 60 units Inaprovaline
* Add 60 units of Potassium (all other chemicals checked, no reaction)
* **All 60 units of Inaprovaline are now gone. No potassium. Beaker is empty.**

WhEre dRugs gO?

**Comment by BurgerLUA** [comment]
I found this bug too. I want to know why it does this as it causes issues every time I want to make Tricord.
