### ISSUE TITLE
Dismanting traps deletes their contents and traps do not visually display contents

### ISSUE THREAD

**Issue by Menown** [Aurorastation/Aurora.3#6150]
Animal traps show themselves as empty. Had to LOOC some people so they knew I accidentally trapped myself in one because you can't see what's inside them visually as the sprite is shown empty, unless you examine the trap itself.

**Comment by Sindorman** [comment]
You can still talk from trap. They work same way as closet. Also if you press resist you will be able to get out of it yourself just like locked closet. 

Making traps display visually what's inside is part of future update.

**Comment by Sindorman** [comment]
It is not a bug because anyone can get out of it by pressing resist

**Comment by Menown** [comment]
Forgot to mention. Dismantling the traps with something inside them deletes the object inside. Be it a person, animal, whatever.
