### ISSUE TITLE
Telsa ball can't spell.

### ISSUE THREAD

**Issue by sphaxticatedmelon** [Aurorastation/Aurora.3#6158]
"All 8 energize for a second, sending their energy to the main ball, which redirects it at the nearest object! Sacraficing one of its miniballs!"

"Sacrificing" is the correct term here.

**Comment by Corsaka** [comment]
Adding to spelling issues: 
![image](https://user-images.githubusercontent.com/23699128/54482095-fc028180-4835-11e9-93c7-94c559a7d3b7.png)
"You wrenches the top cap shut" "you unwrenches the top cap open"
Not only should these be the other way around (wrenching it shut actually opens the dispenser, and vice versa), but the spelling is hurting me physically.
"You wrench the top cap open." "You wrench the top cap shut." would work.
