### ISSUE TITLE
Hoods Require You To Be Rested To Toggle Them

### ISSUE THREAD

**Issue by Menown** [Aurorastation/Aurora.3#6175]
You need to be resting to toggle hoods, for some reason. Obviously not working as intended.

**Comment by MarinaGryphon** [comment]
Found the issue. `use_check` returns true if you CAN'T use it, not if you CAN. `!use_check()` checks if you CAN'T use it. This means that you can toggle your hood while dead, I think. Yikes.

**Comment by Alberyk** [comment]
Looks to be fixed.
