### ISSUE TITLE
Xenobotany has service headsets in the lockers

### ISSUE THREAD

**Issue by cha0s5150** [Aurorastation/Aurora.3#6179]
I've always assumed this was intentional so the Xenobotanist can communicate more effectively with other botanists or chefs but I've been informed by vtcobaltblood that this is not the case. They say that the lockers that contain the service headsets in xenobotany are just copies from botany. I did find it a pain to always have to get a screwdriver to pull and move encryption keys to combine them in one headset because if you have a headset equipped on your right ear it doesn't seem to work. I'm unsure if this is intentional or not, but I said I would report it just in case.

**Comment by fernerr** [comment]
I'll work on fixing this.
