### ISSUE TITLE
Crew manifest during changeling round reveals which crewmembers are currently shape-shifted into monkeys

### ISSUE THREAD

**Issue by Matthew951** [Aurorastation/Aurora.3#6186]
https://i.imgur.com/K6jHn1h.png

Saw this in the crew manifest from the lobby in a changeling round. Alice Gough, the forensic technician there, was a changeling. A monkey, at the time. So I figured this was probably some kind of oversight.

**Comment by Geevies** [comment]
i believe this has been fixed by the records subsystem
