### ISSUE TITLE
Supermatter Engine generates infinite amounts of carbon dioxide

### ISSUE THREAD

**Issue by fernerr** [Aurorastation/Aurora.3#6191]
https://i.imgur.com/selvd7E.png

https://i.imgur.com/Yyi8862.png

https://i.imgur.com/P4HkUCG.png

On two different rounds after each other, the SM has been producing limitless amounts of carbon dioxide, completely filling the core and waste loop.
I suspect it may have to do with the changes to fire in PR #6129 though I'm not sure.

**Comment by Sindorman** [comment]
That makes total sense. Darn it! I did not thought of SM making fire.
