### ISSUE TITLE
Various atmospheric, power and disposal things

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#6196]
It is that time again where I update the map pictures for the wiki and discover some interesting stuff.

It mostly boils down to things that were added by accident that were not removed, things that got edited which left pieces in, or inconsistencies.

First I'll start with airlocks that aren't connected to the supply pipes to replenish their storage.

There is only one airlock on the roof, and it's not connected to the supply network.
Should it ever deplete, it would be next to impossible to get the air cannister up there refilled/replaced.

On the surface level the following are not connected to the supply system:
The telecoms airlock leading outside
![javaw_2019-03-23_12-06-54](https://user-images.githubusercontent.com/16565113/54865333-415a0e00-4d64-11e9-9aba-7e9409f7a39e.png)

And the bay connecting various ships to the command section of the surface level
![javaw_2019-03-23_12-08-17](https://user-images.githubusercontent.com/16565113/54865338-66e71780-4d64-11e9-8399-b960eda2fdde.png)

On the sub-level strangely enough the airlock leading to the AI core is not connected
![javaw_2019-03-23_12-12-47](https://user-images.githubusercontent.com/16565113/54865380-1cb26600-4d65-11e9-8c6d-c6a4e16ba74c.png)

And last but not least the small area under the station has its airlock not connected.

Now for the various pipes n cables that are left over

On the construction level:

This vent at the firing range is not connected, 129, 179
![javaw_2019-03-23_12-41-37](https://user-images.githubusercontent.com/16565113/54865665-2342dc80-4d69-11e9-9376-88ae65ecefe9.png)

Should anything happen to the upper level of the vault, it's not connected to supply or waste line
![javaw_2019-03-23_12-43-26](https://user-images.githubusercontent.com/16565113/54865754-aca6de80-4d6a-11e9-83ca-81e99b0bac19.png)

On the main level;

There is a random supply pipe in the chapels office, at 94, 83
![javaw_2019-03-23_12-18-23](https://user-images.githubusercontent.com/16565113/54865432-e2959400-4d65-11e9-96ba-2b558ed52265.png)

There is this leftover bit of supply and waste pipe here with a piece of cable at hydrophonics, 188, 103
![javaw_2019-03-23_12-20-23](https://user-images.githubusercontent.com/16565113/54865459-3b652c80-4d66-11e9-9819-bc073f4e9d68.png)

There are two misplaced disposal pipes near cloning and the CMO's office at 153, 120 and 167, 115
![javaw_2019-03-23_12-22-36](https://user-images.githubusercontent.com/16565113/54865510-a878c200-4d66-11e9-9f12-f9817eba5c53.png)

There are two leftover pipes in the vault, 159, 159
![javaw_2019-03-23_12-24-36](https://user-images.githubusercontent.com/16565113/54865515-bd555580-4d66-11e9-827b-1dbd76afdc83.png)

There's a leftover piece of disposal pipe in the medbay breakroom, 150, 129
![javaw_2019-03-23_12-26-40](https://user-images.githubusercontent.com/16565113/54865537-fab9e300-4d66-11e9-839b-f134ecd6b849.png)

There's a leftover piece of disposal pipe in the library, 108, 97
![javaw_2019-03-23_12-27-55](https://user-images.githubusercontent.com/16565113/54865706-0ce95080-4d6a-11e9-8aec-9991ab7709bf.png)

On the sublevel:

There is this leftover pipe in the carbon dioxide container, 100, 183
![javaw_2019-03-23_12-48-56](https://user-images.githubusercontent.com/16565113/54865715-2c807900-4d6a-11e9-9cee-57d5d323a307.png)

And last but not least: There is this piece of cable in the patient observation wing, not connected to anything, 173, 101
![javaw_2019-03-23_12-51-40](https://user-images.githubusercontent.com/16565113/54865748-808b5d80-4d6a-11e9-8f6e-32a13ec20c8d.png)

**Comment by fernerr** [comment]
This is very valuable, thanks.

**Comment by skull132** [comment]
Fixed in #6286
