### ISSUE TITLE
Atmospherics main line suggestion

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#6197]
While I was nosing around with filters in fastdmm, I noticed that the main supply and waste line running to the main level has no redundancy, shown in the red circle
Ideally, I'd expect it to run up somewhere in the green circle as it would be further away from the singularity engine, should anything happen to it.

But an alternative would be connecting it redundantly via the maintenance hallway that runs down from the main entry point, also running one up to directly connect with engineering, and maybe run pipes to  connect it from the atmospherics section to the maintenance hallway next to it, all shown in green lines.
![lg4sVns 1](https://user-images.githubusercontent.com/16565113/54865837-18d61200-4d6c-11e9-8295-2f15c6af3578.png)

**Comment by Doxxmedearly** [comment]
Not a bug. This is a suggestion.
