### ISSUE TITLE
Wait - That's illegal. You can sit backwards (or any direction) in a rolling chair, when buckles.

### ISSUE THREAD

**Issue by the-og-gear** [Aurorastation/Aurora.3#6227]
![image](https://user-images.githubusercontent.com/9438930/55050004-14884e00-5025-11e9-8345-9eb46a2832df.png)

Yup. That's me. Sitting in a chair. Backwards. While also buckled.

This should be able to be reproduced. I used `Alt + Arrow Keys` to face a different direction, I have no idea how this affected the issue, when clicking to face a different direction works as intended and rotates the chair.

Well, unless it's a _F E A T U R E_, that is.

**Comment by alsoandanswer** [comment]
i mean, you CAN in real life. When you contort your body like an idiot.

I don't really think this is a game-breaking bug, TBH. It doesn't really affect anyone, so.

**Comment by Sindorman** [comment]
Yeah, It is not of big of deal. Like some people sit on chair backwards intentional.
