### ISSUE TITLE
Gravity Generator can not be turned off

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#6236]
Can't turn it off and it doesn't turn off when power is cut.

**Comment by Sindorman** [comment]
How long did you wait? It has Charging and discharging time. Which usually is 1-3 minutes

**Comment by SonicGotNuked** [comment]
The thing is, it never discharges. You can't interact with the UI.

**Comment by Sindorman** [comment]
duplicated of #5602

**Comment by Sindorman** [comment]
The interface only responds if you stand from the South of it
![dreamseeker_CtTO1GloS5](https://user-images.githubusercontent.com/25555314/55269000-6232cf80-524c-11e9-8c66-503d6ab9e8a6.png)
