### ISSUE TITLE
Picking up a dead runtime (the cat not the CS term)

### ISSUE THREAD

**Issue by Bedshaped** [Aurorastation/Aurora.3#624]
I just killed Runtime on a local server and when I tried to pick him up, he flew off into a random direction.

Countdown to being told this is a feature. Cat corpse desecration protection.

**Comment by skull132** [comment]
I cannot replicate on live.

**Comment by skull132** [comment]
Actually, I lied.

Sometimes, when runtime dies, his corpse will somehow gain momentum. This can also be tested if you kill a bunch of cats right next to a door. A few of them will bug out like this, and start bumping the door (making an annoying sound as a result).

Though, I cannot replicate this bug 100% of the time?

**Comment by NanakoAC** [comment]
this bug is both confirmed and cannot reproduce. I have no idea how or why it happens, yet, but it definitely does

**Comment by NanakoAC** [comment]
I believe I've found and fixed this in #782

**Comment by skull132** [comment]
Fixed in #891
