### ISSUE TITLE
Offworlders don't have high tolerance for low oxygen

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#6243]
on the wiki for offworlders it says
'Only require bare minimum air to reliably breathe - somewhere around 15kpa ingame.'
but you get lung ruptures even with just 1 point under 21kpa like a normal human

**Comment by Alberyk** [comment]
This is really not ideal to implement right now due to how our organs work, since breathing is not handled by the lungs themselves, but by the mob.
