### ISSUE TITLE
Traffic Control Console is Restricted from AI Access

### ISSUE THREAD

**Issue by Youbar** [Aurorastation/Aurora.3#625]
Easy enough to reproduce.
Start as an AI,
Jump to network tcommsat,
Interact with Traffic Control Console,
Specify "tcommsat" as network to replace [NULL],
Observe as nothing happens.

According to Skull132, this is because it's AI restricted.

**Comment by Bedshaped** [comment]
Yeah this annoys me too. 

In order to get around it you have to rename your servers to NULL to get it to work.

**Comment by skull132** [comment]
Indeed, @Bedshaped, it's a bug/oversight.

On old code, I forgot that we made a minor adjustment to permit AI shenanigans.

**Comment by Youbar** [comment]
I've attempted to rename the network to [NULL] on the telecommunications monitor and the telcommunications server monitor. Both are unresponsive. You can scan and all that, but you can't enter a new network name. This might just be my inexperience with game mechanics, however.

**Comment by Bedshaped** [comment]
@Youbar if you find the servers that manage the channel you want to do things with. Find those servers in the cold room and set their network to NULL, then scanning them on the traffic control console set to NULL will cause them to appear and you can add scripts.

Just a work-around until it's fixed.

**Comment by Dalekfodder** [comment]
The problem is that you need to be physically next to the console in order to get it to work.

So if you go near it as cyborg you can change it but if you stay away you can't.

**Comment by NanakoAC** [comment]
fixed by #694
