### ISSUE TITLE
penny's rest sprite is not used/not working properly

### ISSUE THREAD

**Issue by nursiekitty** [Aurorastation/Aurora.3#6257]
when penny rests, the calico sprite is shown. the rest sprite IS in the code and should work properly as it has in the past, but something seems to have broken.

when an animal is dropped, it momentarily shows the resting sprite. this is the only time when penny's proper resting sprite works.

**Comment by Sindorman** [comment]
It looks like penny's rest states was not defined in code. That would explain why it partially works.
