### ISSUE TITLE
Synths cannot repair airlocks

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#626]
Trying to apply metal on an airlock does nothing as an engineering borg.
It works when playing a humanoid.

**Comment by Dalekfodder** [comment]
Why would you apply to an airlock? And I don't understand how that does anything?

**Comment by Alberyk** [comment]
You can break airlocks by attacking them/firing at them, if they are not fully broke you can use metal and a welding tool to fix the damage, something that borgs are unable to do atm.
