### ISSUE TITLE
Cybersuit/stealth suits from robotics ID locked

### ISSUE THREAD

**Issue by kyres1** [Aurorastation/Aurora.3#6280]
What the title says. I'm not sure if it's intentional or not, but the printed illegal RIGs are impossible to use by station personnel because of this.

**Comment by Sindorman** [comment]
Obviously, it is intended to be used by Antags. If you have Agent ID from uplink - you can unlock it. Illegal suits were intended for antags.

**Comment by kyres1** [comment]
Why though? There's plenty of other illegal things R&D can use - even illegal mech parts. This just seems like they'd never get used - especially considering there's no reason to really pick an unequipped stealth suit/cybersuit over a combat RIG that is cheaper.

**Comment by Sindorman** [comment]
Both stealth come with stealth module, and full vision module which is a lot already good modules, just stealth itself. Cybersuit comes fully equipped with all modules required for suit.
```
/obj/item/rig_module/ai_container,
		/obj/item/rig_module/power_sink,
		/obj/item/rig_module/datajack,
		/obj/item/rig_module/electrowarfare_suite,
		/obj/item/rig_module/voice,
		/obj/item/rig_module/vision
```

Both suits support installation of general, light combat and special modules.
