### ISSUE TITLE
Oven-baked bacon is impossible to remove from baking tray

### ISSUE THREAD

**Issue by Eonoc** [Aurorastation/Aurora.3#6283]
Game ID: bZl-a7lC

As above. Making oven-baked bacon via six raw bacon and butter did not allow it to be removed from the tray after the recipe was completed.  You could only remove the tray, not the bacon itself. I am unsure, but it may possibly be because the oven doesnt know how to output multiple things from one recipe?

_...I might also just be stupid and didn't realize how to do it properly. If so, delete this, obviously._

**Comment by JohnWildkins** [comment]
After the cooking update, Alt+Click seems to work.
