### ISSUE TITLE
Hooch cannot be made

### ISSUE THREAD

**Issue by Eonoc** [Aurorastation/Aurora.3#6288]
The drink, Hooch, (2 parts ethanol, 1 part welding fuel, 1 part sugar) is unable to be made in any mixing order, as there is a drink, known as Fringe Weaver (2 parts ethanol, 1 part sugar) that is always made first in the mixing order. I tried mixing the drink in every different order imaginable, to no success. I recommend either a change to Fringe Weaver's recipe, hooch's recipe (perhaps to just ethanol and welding fuel?) or somehow fixing the mixing order check, though that seems like it'll be much more effort than its worth.

**Comment by cha0s5150** [comment]
Hooch isn't made with ethanol. It uses moonshine. Here, take a look:

/datum/chemical_reaction/hooch
	name = "Hooch"
	id = "hooch"
	result = "hooch"
	required_reagents = list ("sugar" = 1, "moonshine" = 1, "fuel" = 1)
	result_amount = 3

**Comment by Alberyk** [comment]
The wiki might be out of date.
