### ISSUE TITLE
Lack of pAI personality showing.

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#629]
So Ive configured my pAI settings, toggled it on, and checked for two rounds now, yet my personality doesnt show up on any pAI devices for some odd reason.

**Comment by SierraKomodo** [comment]
Are you a ghost when someone searches for a personality? Do you receive the pop-up asking if you want to be a pAI when someone tries to use a pAI device to find a personality?

**Comment by Pratepresidenten** [comment]
Oh yeah, forgot about this report. Apparently you needed to toggle your pAI role candidacy on within the preferences tab. Fixed it right up.
