### ISSUE TITLE
Viral outbreak event is outdated

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#6304]
Viral outbreak checks for the wrong job, so there is never actually any level 7 virus outbreaks.
`var/has_virologist = FALSE`

We don't have virologists anymore, we have biochemists

**Comment by Sindorman** [comment]
That is the name of the var, not what it is looking for
![Code_ySWRx826vi](https://user-images.githubusercontent.com/25555314/56087554-6a7d3400-5e22-11e9-860c-ea1bba77c53d.png)

**Comment by Sindorman** [comment]
As you can see from picture above it is Looking for "Biochemist"

**Comment by Sindorman** [comment]
Tested on test server and it works.
