### ISSUE TITLE
Three xenomorph bugs

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#6308]
1. Ventcrawl is broken, completely. 
2. Mechs can open resin doors and go exterminator mode.
3. Larva that is inside someone doesn't appear on the health scanners. (Sneaky worms)

**Comment by Sindorman** [comment]
About point 3, iirc larva is supposed to appear on in Advanced medical scanner, the one you climb inside.

**Comment by SonicGotNuked** [comment]
> About point 3, iirc larva is supposed to appear on in Advanced medical scanner, the one you climb inside.

That's the scanners I'm talking about, it says there is nothing wrong, even though the giant worm popping from a chest.

**Comment by Alberyk** [comment]
It should show as an organ.
