### ISSUE TITLE
Robotics spray cleaner is always empty

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#6312]
![image](https://user-images.githubusercontent.com/19973802/56182770-c97fba80-6067-11e9-9fdf-f15028d3bbf2.png)
![image](https://user-images.githubusercontent.com/19973802/56182805-ef0cc400-6067-11e9-93b0-bbd33c69afb4.png)

Inb4 working as intended.

But why have it in robotics at all then? Chemistry has spare bottles.

**Comment by Sindorman** [comment]
Just mapped wrong kind. Easy to fix.
