### ISSUE TITLE
Kinetic Accelerators shooting self in foot even if is wielded

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#6314]
As said in title, KA fired while wielded would hit the foot any time it was used

**Comment by ToasterStrudes** [comment]
Addendum: Thermal Lances also do this as well.

**Comment by ToasterStrudes** [comment]
Addendum 2: Every ranged weapon does? Laser rifle does it as well.

For details, my current equipment is
https://puu.sh/Dfw47/f51435f6dc.png

**Comment by Soultheif96** [comment]
I would also say that this still persists.

It is very limiting on our jobs as miners and so on.
