### ISSUE TITLE
Chili peppers have been consumed by the void

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#6332]
![nX3VIZO](https://user-images.githubusercontent.com/44004468/56460235-8b3b1180-636d-11e9-8eb2-059229783863.gif)
![chili1](https://user-images.githubusercontent.com/44004468/56460236-8bd3a800-636d-11e9-9dee-282992024881.gif)

All chili peppers behave like this, even ones spawned in with admin powers, according to Prate.

**Comment by alsoandanswer** [comment]
Must be a sprite bug, I'll go check on it
