### ISSUE TITLE
Roof solar air alarm is called "surface solar"

### ISSUE THREAD

**Issue by Sindorman** [Aurorastation/Aurora.3#6354]

**Comment by MarauderW** [comment]
Hi @Sindorman , I want to see if I can fix this issue, I went to the roof solar array but I can't find the alarm, where exactly is it located? 

Thank you.

**Comment by Sindorman** [comment]
Hey, the air alarm itself won't have name. You would need to rename the area in that room entirely.

**Comment by MarauderW** [comment]
Ohh I see, it's a bit beyond what I know atm, I will try to learn more to see if i can make that change locally first.

Thanks for responding!

**Comment by Sindorman** [comment]
No problem. You can text me on discord in code_dungeon channel if you want me to explain how to fix this bug. my username on discord is PoZe

**Comment by MarauderW** [comment]
Will do, thank you! :)
