### ISSUE TITLE
Nymphs/Drones get stuck inside deconstructive analyzer

### ISSUE THREAD

**Issue by Youbar** [Aurorastation/Aurora.3#639]
As it says in the title.

Grab a diona nymph or a maintenance drone.
Put them inside a destructive analyser.
Observe that it gives tech, but they **cannot**
a. be released
b. be destructively analysed
leaving them in a bugged state. The only way to clear it is through deconstructing and reconstructing the machine.

**Comment by skull132** [comment]
Title updated to better describe the issue.

Intended feature: you can deconstruct drones and nymphs.
Unintended bug: they get stuck and bug the machine.

**Comment by Bedshaped** [comment]
Deconstructing nymphs is an intended thing?

**Comment by Alberyk** [comment]
Yes.
