### ISSUE TITLE
Clawed Gauntlets Not Working

### ISSUE THREAD

**Issue by Ornias** [Aurorastation/Aurora.3#6407]
The clawed gauntlets (available from the Traitor loadout) do not work when worn, only when held in a hand. I do not think this is their intended function.

**Comment by Ornias** [comment]
I have used these gloves twice now on-station (several months apart, the latest being today). If they are working, do they give any form of feedback to the user? My character kicked instead of using any kind of clawing verbs, and there was no option available in the attack verbs menu to change this.

**Comment by Alberyk** [comment]
That is not supported right now, but, as I said, they do increase the unarmed damage and cause cuts.
