### ISSUE TITLE
Asteroid turf vents 

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#6414]
Based on the Test Merge PR to unsimulate asteroid Turf. If a bomb goes off, and it exposes the Turf, It'll vent the room regardless of where it is located on the station.

For example: Robotics had an explosive implant go off, it vented the entire room until engineering placed floor down.

**Comment by Sindorman** [comment]
That make sense, the asteroid turf currently suck the air in. Not really a bug, but rather question if we want to keep it. @Arrow768 ?

**Comment by SonicGotNuked** [comment]
Yeah, I understand the new behaviors, but perhaps instead of generating an asteroid turf, maybe it would be better to generate a hardened simulated version of the turf bellow where the floor was knocked out.

**Comment by Sindorman** [comment]
Problem will still remain if that turf somehow is neighboor to asteroid turfs. We are looking for solutions in dev chat

**Comment by Arrow768** [comment]
We discussed that internally and consider it a feature, as it adds additional danger to explosives in the form of venting potential.
