### ISSUE TITLE
Putting a maglight on a vest causes a broken sprite to appear. 

### ISSUE THREAD

**Issue by flimango** [Aurorastation/Aurora.3#6418]
Step 1. Don an officer's armor vest.
Step 2. Put a maglight in your suit slot.
Step 3. Break immersion.

![image](https://user-images.githubusercontent.com/32926873/57503142-c9a85a00-72a3-11e9-94a8-3b26c4d2946f.png)

**Comment by flimango** [comment]
This appears to happen when putting a flashlight onto an exo-stellar rig as well.

**Comment by tomekkiel** [comment]
Also happens for me with the warden's jacket
