### ISSUE TITLE
Toeless jackboots failing to save in the loadout

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#6422]
This is an Aut'akh

[![Screenshot from Gyazo](https://gyazo.com/ca4cfd634e27a37bf458bd2c494d181b/raw)](https://gyazo.com/ca4cfd634e27a37bf458bd2c494d181b)

It is failing to save and keeps disabling itself so I would have to go in after every round and enable it.

**Comment by Alberyk** [comment]
Might have to do with #6380

**Comment by Alberyk** [comment]
You can get your loadout back by using the reload fuction on the character setup menu.
