### ISSUE TITLE
Justice Hat - Object Bugged

### ISSUE THREAD

**Issue by TheOrleans** [Aurorastation/Aurora.3#6427]
Well, there's an object called ''justice hat''

It's a hat, in fact, you can put it in your head slot.

It makes you go shaved and bald instead of being an actual hat, this is not how it is supposed to work I guess

The item: ''Justice Hat''
https://i.gyazo.com/c879991bb76a474084dd5f7db7d56390.png

Me before wearing it:
https://i.gyazo.com/00bf2fe7f606c73d863e20efa3aa2f89.png

Me after wearing it:
https://i.gyazo.com/a27f705c88ad9977a36f4676e0a92d39.png

**Comment by TehFlaminTaco** [comment]
This hat seems to reference an icon_state that simply does not exist.

**Comment by XanderDox** [comment]
This bug has existed for eons. Definitely 5 or more years.
