### ISSUE TITLE
You can't resist out of welded lockers

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#643]
Welding someone inside a locker traps them forever, since resisting don't breaks you out of it.

**Comment by Dalekfodder** [comment]
You put the confirmed tag but perhaps you aren't meant to resist it at all?

But of course, I'm only asking.

**Comment by Alberyk** [comment]
It means that it is a confirmed bug, already tested, you should be able to resist out of welded lockers, but you can't due to such bug.

**Comment by LordFowl** [comment]
This is a bug. The game tells you you are about to break out, and then forgets before the first locker-shake.

**Comment by NanakoAC** [comment]
Fixed by #649
