### ISSUE TITLE
Character Records and Flavour Text not Saving

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#6445]
Pretty much what the title says. Each time I fill in character records or flavour text for some of my characters, they go blank again the next round. I tried saving them specifically through the web interface and only my employment records saved, medical and security records went blank again, as did flavour text. 

http://prntscr.com/nntgot

Apostrophes in the employment records also turned into those series of symbols too.

http://prntscr.com/nnthrp

**Comment by Arrow768** [comment]
Should be fixed now

**Comment by MarinaGryphon** [comment]
This was from using fancy apostrophes, I believe.
