### ISSUE TITLE
Mercenaries with Too Many Sec Records Appear on Roundstart Command Report

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#6456]
If someone spawns as a Mercenary using a character slot with more than three charges on their security record, they will show up as:

'Mercenary [Character's Last Name]' on the shift-start command report.

Evidence:
![uhm](https://user-images.githubusercontent.com/8857246/57803911-790f8180-7727-11e9-94fa-b30466d5fef7.PNG)

**Comment by Kaedwuff** [comment]
That's hilarious.  I guess we need to add an antagonist exception.
