### ISSUE TITLE
New Away Mission Supermatter

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#6473]
One of the new away mission locations (the one with the diona walls) has a supermatter that spawns in it.

This supermatter can/will eventually begin degrading, possibly from round start, and broadcasting alarm messages to the station.  The station has 0 way to determine they are not coming from their own core, instead of a supermatter on a distant away mission that they haven't even seen, and it results in illegitimate ejections and evacuations.

Remove it or somehow fix it, please.

**Comment by Alberyk** [comment]
Fixed already
