### ISSUE TITLE
The loadout does what it wants

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#6478]
The loadout likes to remove xeno apparel that has been selected, claiming I am not whitelisted for X species, which is a blatant lie. This happened to Skrell and Tajara (I think), it also does not happen every time, but pretty often.

![aSASDFCV](https://user-images.githubusercontent.com/43940569/58135313-3b7c8e00-7c2a-11e9-9126-12dc92863b44.png)

**Comment by TehFlaminTaco** [comment]
This is already being addressed in #6422
