### ISSUE TITLE
D100 is bugged

### ISSUE THREAD

**Issue by TheOrleans** [Aurorastation/Aurora.3#6481]
The object 'd100' (the gaming dice) is not a d100 but a d10.

https://i.gyazo.com/0f16c398dcda2208f64d7fa0d1b41c82.png

**Comment by Kaedwuff** [comment]
This is not a bug, but perhaps inadequate communication - when rolling d100, it is common to roll two d10s, one that has 1-10, and another that has 00-09.  Both dice together create a d100 roll, because making an actual hundred sided die is very hard.
