### ISSUE TITLE
Spiders Target AI-Eyes

### ISSUE THREAD

**Issue by Muncorn** [Aurorastation/Aurora.3#6488]
Spiders will target the AI eye if it is within distance, same as it would a normal person. I don't think it tries to attack the eye, but I'm not 100% sure. I wasn't in hologram form at the time, and it charged 3 times before it got killed by some officers.

https://gyazo.com/0f87ce9a7888fc5d267dba0563f87b9f

**Comment by Sindorman** [comment]
Did you click on them before they attacked?
