### ISSUE TITLE
Boerer headwear issue

### ISSUE THREAD

**Issue by AmoryBlaine** [Aurorastation/Aurora.3#6502]
The boerer is incapable of penetrating headwear- the most notable example being the beret, thus incapable of aquiring a host, with any number of hats- even if they do not protect the ears. This is obviously an issue since most hats aren't sealed, nor are they even likely to cover the ears. No real idea as to how it can be fixed. Would suggest checking over what is and isn't protected by hats individually.

**Comment by alsoandanswer** [comment]
Technically, we could find another proc instead

for example : 
if it's vacuum tight against space
it's a helmet with some modicum of defense

and then make every other hat penetrable. 

borer isn't a very common thing anyway, so it's going to be a while.
