### ISSUE TITLE
Something is borked with surgery

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#6503]
As per request from Arrow here a detailed description on what happened (it was the round **before** the one with the ID "b1s-dkzR"):

I was doing surgery (as a Tajara) on another doctor (a human). I wanted to extract some shrapnel, that showed up on the scanners as abnormal mass in the upper body of him. So I put him down on the table, attach a anesthetic tank on his back and a mask and turn on internals. Before I did this surgery he was operated in the upper body before, fixing a burst lung, which all went fine. I then performed the following steps:
- open the surgical site in the upper body with a scalpel
- clamped the wound with the hemostat
- lifted the skin with the retractors
- sawed the ribcage with the bone saw
- bend the ribcage back with the retractors

here, one normally would use the hemostat again to start poking around and find the shrapnel. Yet, when doing that it only said "you can't seem to find a useful way to use the hemostat on [patient] right now". The shrapnel could not be removed at all, no matter what. Arrow then intervened and did some admin thingys to restore the patients health.

**Comment by NonQueueingMatt** [comment]
fixed
