### ISSUE TITLE
Speech slur persisting after trauma fix.

### ISSUE THREAD

**Issue by RighteousBacon** [Aurorastation/Aurora.3#6506]
Some times when a brain trauma is treated, the patient still slurs their speech, even though scan reports indicate perfect health. I've seen it happen 2 times, no idea how it happened or how to reproduce it. Prate says that our guy should be perfectly healthy.

The first time it happened I heard talks about the trauma continually increasing the slur stat, so maybe that's one thing to look into. Don't have the ID for that round.
Round ID: b1u-brQI

**Comment by Pratepresidenten** [comment]
Rejuving does nothing for them either.

**Comment by TheOrleans** [comment]
I was the victim, I can confirm it.

**Comment by Pratepresidenten** [comment]
Spesifically bus-curing traumas doesnt work either, despite of the concussion trauma being erradicated from the var list.
