### ISSUE TITLE
Fucking COOL Strange Double Magnetic Lock Bug

### ISSUE THREAD

**Issue by TheOrleans** [Aurorastation/Aurora.3#6508]
Hello, this is a bug that happened, Prate was there to see it, I laughed a bit cause it was so strange.

How to repeat it.:

Get to the armory or to a double airlock place 
https://i.gyazo.com/b9639b7fbaea33bf2ff935d91c48f59f.png

Grab two maglocks, both have to be locked (red light), one in each hand
https://i.gyazo.com/e2674d9dd593155b9f6d6264a47bebd1.png

Start placing one in one of the airlocks, and when you get this message, swap to the other hand before accepting it.
https://i.gyazo.com/b847ca36f8295c2cac995547627384f1.png

Then accept it. One maglock will be attached and the other one will fall to the ground, just like this
https://i.gyazo.com/f0b292da3ad88493a397ea9205e430cf.png

The thing is you STILL have the maglock which is attached in your hand, although you can't see it, so move away and press Q to drop it. It will be still locking the door, but not there. When you press the Q it will attach to the square next to your character, you can bring it wherever you want it. Check this images
https://i.gyazo.com/4840d6a1b1766b2b164c63ace0f1086e.png
https://i.gyazo.com/cce514f5a2569a9b6a7fe4dfd2159264.mp4 (GIF)
https://i.gyazo.com/80c6bb037246c63f08f5d0df999ec8fe.png

And it's always locking the doors
https://i.gyazo.com/c511c509bb534bdf228c9b4fcf6d9e2b.mp4 (FINAL GIF)

You will need to unlock the maglock to remove it from the ground or from wherever it is though.

Give me a cookie for putting such an effort on investigating this cool thing

EDIT: It also works with other airlocks, triple airlocks for example 
https://i.gyazo.com/03cabd8930ea8ced89b283098b74019d.mp4

**Comment by Sindorman** [comment]
I know reason. Easy bug to fix

**Comment by TheOrleans** [comment]
> I know reason. Easy bug to fix

Man fucking hell I hoped it would be a difficult bug or something :( So much investigation for an easy bug?

GIMME A COOKIE

**Comment by Sindorman** [comment]
Your step-by-step guide and explanation helped me narrowed down issue and conclude that it is easy fix. Thank you

**Comment by TheOrleans** [comment]
That's a good cookie  🥇
