### ISSUE TITLE
Ore Summoner teleports interact with Kinetic Accelerator blasts, causing teleportation failures and explosions when used together

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#6512]
Round ID:
b1w-cOQV

- Performed using an accelerator with a medium frame, professional core, kinetic charger, and an AOE chip.

![11](https://user-images.githubusercontent.com/44004468/58729853-7912b100-83b8-11e9-8ef2-1bccae5388eb.png)

When you use an ore summoner to gather ore with a kinetic accelerator's "blast" effect still active you will cause a teleportation failure and explode. It's kind of like the bike bug but worse. Thanks Fowl.

**Comment by Sindorman** [comment]
You managed to combine two performance worse things in the world and is surprised bad things happen? Both KA and ore summoner have special check set to make them not cause server freezes during their usage, as they just iterate over large areas. Now that check is what cause them to be slow but still stable. I would not recommend using both at the same time, there is really no way to stop what happened to you possibly

**Comment by skull132** [comment]
@Sindorman in theory you can delete the projectile and make the proc that iterates the objects headless with `INVOKE_ASYNC()` and making sure they don't reference the bullet anymore.

**Comment by AIMMO2001** [comment]
Having similar Issues and have to say that an AOE KA is one of the few things that makes using an Ore Summoner worth. 
I don't know the spaghetti code that is Aurora too well but maybe its reasonably possible to either: Have KA explosions not be considered solid for Bluespace Teleportation (If its possible code-wise I don't see a reason, not to)
 Or  what might be more tricky, have Ore Summoners be excluded from blue space  disposition, after all, it only can teleport Ore and only can teleport it to a place where a player can stand, so there shouldn't be any issues with getting stuck in things like it is the case with telescience
