### ISSUE TITLE
Untagged shells are showing up as neuter again

### ISSUE THREAD

**Issue by kyres1** [Aurorastation/Aurora.3#6514]
Defeats the point of untagged shells entirely. Even when untagged, they show up as "it" and their records say "neuter" according to players.

I have heard in passing that it won't be possible to change this without having to address tagged shells by proper gender pronouns in flavor text. I'm fine with this, if this was being avoided in any way.

**Comment by Alberyk** [comment]
Any shell suffer from this, I think.
