### ISSUE TITLE
full beakers inside machine construction wipe contents

### ISSUE THREAD

**Issue by veraknocks** [Aurorastation/Aurora.3#652]
self explanatory

**Comment by NanakoAC** [comment]
@veraknocks no its not. explain it more

**Comment by veraknocks** [comment]
1. add liquids to device (for example, circuit imprinter.) 2. identify there's liquid in the device. 3. deconstruct the imprinter, notice a beaker has fluid in it as it should. 4. insert beakers back into the device. 5. the liquid is gone

**Comment by skull132** [comment]
Fixed in #1987
