### ISSUE TITLE
Can't spawn in with Xenowear

### ISSUE THREAD

**Issue by CrystalClearCC** [Aurorastation/Aurora.3#6520]
Having a slot with xenowear (both general and unathi) selected when connecting to the server gives the following message;

![image](https://user-images.githubusercontent.com/20048255/58762901-806ac380-854c-11e9-8694-d9f6329b08a1.png)

**Comment by Chen-Yakumo** [comment]
+1. I have to update the loadout every time the server reboots in order to spawn in with caligae on my tajara.
