### ISSUE TITLE
Wizard's raise dead, gibs instead!

### ISSUE THREAD

**Issue by BinaryEvolved** [Aurorastation/Aurora.3#6534]
Playing a round the other night when I died and the wizard attempted to use their raise dead spell. Instead of bringing me back to life and allowing me to contribute to the culling onslaught with my overlord- it gibbed me- sending my liver out a hole in the side of the station. _Rest in peace little guy_

Contacted Garn who manually was able to get a new mob setup for me to possess. It happened again later in the round to someone else as well.

Edit: I failed to mention it doesn't seem to spawn the skeleton either.

Round ID# b1z-bOmq

**Comment by Alberyk** [comment]
Raise dead gibs the old body and creates a skeleton for a ghost to take, it is not granted to the user of the old body will be the skeleton's owner in any way.

**Comment by BinaryEvolved** [comment]
>
> 
> Raise dead gibs the old body and creates a skeleton for a ghost to take, it is not granted to the user of the old body will be the skeleton's owner in any way.

Wait so its meant to just make a skeleton but not actually allow someone to play it? The wiki says it's meant to make a 'servant' which seems to imply a minion who will assist you throughout the round. 
Besides that, it doesn't seem to make the skeleton either way.

**Comment by Alberyk** [comment]
If it does not make any skeleton, that is a bug, and I will take a look into it. But, if you want to play as one, you should enable your preferences and be around in ghost chat.

**Comment by Alberyk** [comment]
Tested this and seems to work fine, the thing is that skeleton bodies can vanish away if no one takes the choice to be a skeleton.
