### ISSUE TITLE
IPC cant spawn with Harness

### ISSUE THREAD

**Issue by AIMMO2001** [Aurorastation/Aurora.3#6535]
I can't spawn anymore with a Gear Harness (Xenoware), as far as I am aware it should be available for both IPCs and Dionne. It was until recently. It may be important to note that I don't get a message that says "You can't spawn with x" or something like that when joining as my IPC char.

**Comment by Sindorman** [comment]
Please explain step by step what happens if you can.

**Comment by AIMMO2001** [comment]
Was fixed July 14th
