### ISSUE TITLE
Crystal Therapy Pod Issues

### ISSUE THREAD

**Issue by Minijar** [Aurorastation/Aurora.3#6537]
**So crystal Pods are plagued with various issues**

1. Despite locking the crystal therapy pod's door, you can still leave it when shoved inside
2. Whenever you attempt to run a scan, the value of abnormalities found doesn't seem to change despite treatment.
3. Attempting to run the cycle mod (the thing that cures abnormalities), it will ALWAYS fail, claiming the subject wasn't recognised.

**Comment by runecap** [comment]
Interesting, I haven't had a single problem with this. For issue 2, it could be that you're just doing the wrong type of treatment. For issue 3, you have to put a specific amount of cycles, going over by just 1 can contaminate the patient (mechanically, contamination means nothing).
