### ISSUE TITLE
Mismatched ID Sprite When Worn

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#6538]
This is what our ID looks like at its most basic level. All IDs follow a similar color scheme. Aqua, white, and blue/red.

![bce4f52f28e439154100c2bd95db19e0](https://user-images.githubusercontent.com/12206154/59123483-eaa3af80-8922-11e9-9803-de1006d9b1b4.png)

When you wear it, however, you see that the sprite for when it's worn is outdated. It's still the very old grey and green aesthetic, which we may have used long ago but no longer do.

![55f46266caca4d89f4085e88a6cdf2dd](https://user-images.githubusercontent.com/12206154/59123609-3c4c3a00-8923-11e9-9f0f-80a9c493e643.png)

I suggest updating this very small sprite to match what it's supposed to look like, which will be much more pleasing to look at anyway.

**Comment by KingOfThePing** [comment]
I recommend making a suggestion on the forums, instead of a bug report, since there is, technically, nothing wrong here.

**Comment by fernerr** [comment]
I believe this was fixed when the lanyards and all that was added. Re-open if not.
