### ISSUE TITLE
The Chef still has morgue access?

### ISSUE THREAD

**Issue by Chada-1** [Aurorastation/Aurora.3#6544]
Issue reported on Discord second hand; Still needs verification.
What should happen is quite simple, the Chef shouldn't have access to the morgue.

**Comment by Geevies** [comment]
Just tested on my server. Chef doesn't seem to have access to either of the morgue doors, the autopsy lab, or the temp morgue.

Seems to be all clear here.

**Comment by Chada-1** [comment]
Alright, thanks, I'll close this.
