### ISSUE TITLE
Slimes 'feed' and grow off IPCs

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#655]
There appears to be a small bug with slimes, where they will 'feed' and grow off of IPCs they are latched on to, despite a complete lack of organic/genetic material to feed off of and a lack of damage done to the IPC. This, combined with the fact slimes seem to not bond to IPCs when being fed, is resulting in some very amusing but annoying situations in xenobiology as an IPC.

**Comment by K0NFL1QT** [comment]
Can corroborate. Slimes do no damage to IPCs, but still feed on them and grow. They DO recognise IPCs as friends though, but hasn't it always been the case that friendly slimes will still glomp you?

**Comment by SierraKomodo** [comment]
I recently found out that being next to a red slime causes other slimes to go hostile; That wasn't noted in the wiki that I saw and I wasn't aware of it. That clears the part about slimes not bonding to IPCs (I was working with red slimes at the time), but the feeding off IPCs part is still an issue.

**Comment by Alberyk** [comment]
Fixed in #1478.
