### ISSUE TITLE
Engine room emitter bugged

### ISSUE THREAD

**Issue by Leudoberct1** [Aurorastation/Aurora.3#6551]
Not sure if this extends to all emitters, but.

The engine room emitter does not fire, even when supplied power. The first time this issue occurred, replacing it with a new one worked. The second time, it did not. An admin spawned emitter had to be used, which then worked. This is a pretty glaring issue that could prevent the engine being set up, with no fix if an admin isn't present.

**Comment by fernerr** [comment]
Couldn't replicate. Might be special circumstances.

**Comment by Leudoberct1** [comment]
It's happened in two rounds now. The only thing different that's been done is I've swapped out the pumps by the hot/cold ports with high power ones, and restructered the waste management pipes. All of that's atmos, nothing to do with power cables.

**Comment by Leudoberct1** [comment]
I've just had the bug occur again, so I've decided to map out every single change I've made to have this issue occur.

First thing is the hot/cold loop.
https://gyazo.com/452ad343d060130b46bee02082e7087b
Four nitrogen tanks into the hot port, four phoron into the cold. Pumps were replaced with high power ones.

Next is the engine room SMES. Input and output were both set to 100,000. No other changes.

Next is waste handling.
https://gyazo.com/e661ce50e369cbcea7ae3545e9730378
System was restructured to this. 
Filters have been set to this- https://gyazo.com/920deb46dee54d29244c01fdbcaf04b4 and https://gyazo.com/b0dc47a249c9d66aa8b1fed216f0e387
Coolers were all set to 193k target and turned on.

These are all the steps I've taken before trying to activate the emitter and then having it not work.

**Comment by fernerr** [comment]
If you're lowering the output on the engine room smes, there might not be enough power for the emitter.

**Comment by Leudoberct1** [comment]
I'm fairly certain that's not the issue. The newly spawned emitter works just fine and has enough power.

**Comment by Geevies** [comment]
I've not seen this happen, ever, so I will be closing this. Re-open if it re-occurs again.
