### ISSUE TITLE
Using 'suicide' but not using 'succumb' or being saved causes you to be stuck in a state of dying but not dead

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#657]
When an antag uses the 'suicide' verb to kill themselves, but doesn't actually die (I.e. they do not 'succumb', or medical manages to keep them alive), they remain in a statement of forever gaining suffocation damage. Medical can keep them alive indefinitely through dexalin plus and/or cryo, and no damage/injury shows up on the full body scanner to indicate a source or cause of the suffocation damage. The antag is also able to actually be awake and speak/emote/act during this. There doesn't appear to be any way to stop the suffocation damage.

**Comment by skull132** [comment]
No longer relevant due to things.
