### ISSUE TITLE
Body Scanner screen does not pop up

### ISSUE THREAD

**Issue by AceAlvie** [Aurorastation/Aurora.3#6572]
While trying to scan a patient, they were put in into the body scanner but when me and an MD tried to activate it to see the console screen of the scanner nothing happened, nothing showed up so we can't scan anyone. I even put my own character in a scanner and tried to have them scanned.
Same problem occurs then

**Comment by Geevies** [comment]
Must have been a once-off issue with BYOND. This does not occur anymore.
