### ISSUE TITLE
Cryopod sprites not working as intended

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#6575]
They half-close for a brief second when entering it before they pop back open, making it impossible to see if anyone's inside.

And they also close properly when the person flushes and there is items to recover. If you open the pod, the recoverable item will pop out of the pod.

**Comment by Pratepresidenten** [comment]
The crystal therapy pod is also flicked the wrong way and the glas is all mis-matched.

**Comment by alsoandanswer** [comment]
Crystal therapy pod is something the mappers are going to have to fix.

the original sprite only had right and left sprites, so that wouldnt be a problem...

until i added up and down ones.
