### ISSUE TITLE
RPED does not pick up certain machine assemblies parts

### ISSUE THREAD

**Issue by Soultheif96** [Aurorastation/Aurora.3#6613]
The Rapid Parts Exchange Device does not appear to pick up the parts for mech rechargers, telepads, and other devices. That also includes the rumored upgradable Sleepers

Either an oversight or purposely left there as a reason. It would be helpful to read them for those who wish to upgrade devices across the station.

**Comment by Geevies** [comment]
What do you mean? Is it incapable of upgrading these devices?
