### ISSUE TITLE
IAC uniform cannot have rolled up sleeves,

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#6619]
I never noticed in all the time but you cannot roll up the sleeves of the IAC uniform, despite me providing the nessecary sprites back in the day. Not really a bug but a oversight, maybe.

![IAC compilated](https://user-images.githubusercontent.com/43940569/60036333-4a35e500-96af-11e9-87cd-fd6b4e89845c.png)

**Comment by LadyFowls** [comment]
PM me on discord the sprites, I remember the exact issue why
