### ISSUE TITLE
Maint drones cant pass under atmos-locked fireshutters

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#6637]
Usually a drone can slide under these as any door, but if the room is depressurized, the shutter becomes impassable.

The shutters encountered for this report is portside in the arrivals dock and the shutters in the cargobay, all exterior firelocks that were actively blinking. It didnt apply to entering the arrivals dock, I could pass through those without issue.

Although, the dock access shutters were blinking yellow, while the exterior shutters were blinking blue (Impassable)

**Comment by MarinaGryphon** [comment]
Please make sure that they were over airlocks, and not windows.

**Comment by Geevies** [comment]
They can, I assume this was a mistake. Re-open if issue persists.
