### ISSUE TITLE
Mining Door can not be opened by miners.

### ISSUE THREAD

**Issue by Chen-Yakumo** [Aurorastation/Aurora.3#6652]
Problem: Miners do not have access to mining. In the same update that pushed the Paramedics having Mining access, Miners can no longer open the door to mining, coming from the Cargo Lobby and break room. I saw the problem last night, but I thought it might have been an IC issue due to the on-going situation, so I ignored it and worked it out ICly. Tonight has the same issue, but right at round start. So it can't be an IC thing.

**Comment by fernerr** [comment]
This is already fixed on the master build, but the update has not yet been pushed to the server actual.

**Comment by fernerr** [comment]
This was fixed with #6646 Thanks for reporting the issue.
