### ISSUE TITLE
CentCom Status Summary Reveals Off-Station Antags

### ISSUE THREAD

**Issue by Allakai** [Aurorastation/Aurora.3#6663]
During a round of voted cross-fire, the CentComm Status Summary had sent its normal thing. Though funny enough it gave several character names and their job positions. One such was a normal character (before the name change) and hilariously put their position down as a mercenary.

Round ID is "Game ID: b14-cUAR"

Picture to help:
![CentComm Image](https://user-images.githubusercontent.com/48839578/60631349-b8239000-9dc4-11e9-8f0e-77b099142d31.JPG)

**Comment by nicemoreoften** [comment]
duplicate of #6456 probably

**Comment by Sindorman** [comment]
Duplicated
