### ISSUE TITLE
Lamarr missing/incorrect floor/hand sprite

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#669]
Screenshot for reference: http://i.imgur.com/5WOlHsc.png

**Comment by skull132** [comment]
Lamar doesn't have a holder, maybe.

**Comment by Alberyk** [comment]
![lamarr](https://cloud.githubusercontent.com/assets/11579997/17376666/e4a1a196-598c-11e6-838a-e4818120b0f8.png)

The regular one is working fine, is it one from a chameleon kit?

**Comment by SierraKomodo** [comment]
Not sure; It was being tossed around on the shuttle. It might have been a dead lamarr sprite or something else, I don't think it latched onto anyway else after I pulled it off Grant

**Comment by skull132** [comment]
No longer a bug.
