### ISSUE TITLE
Several firelock issues.

### ISSUE THREAD

**Issue by flimango** [Aurorastation/Aurora.3#6693]
1. Firelocks have broken welded sprites:

![image](https://user-images.githubusercontent.com/32926873/60800415-01a80e00-a12a-11e9-9535-cce0f0503404.png)

2. You can also harvest as many wires as you can click on it during deconstruction:

![image](https://user-images.githubusercontent.com/32926873/60800468-17b5ce80-a12a-11e9-9a30-02569edb4769.png)

![image](https://user-images.githubusercontent.com/32926873/60800479-1dabaf80-a12a-11e9-9c79-1c53cd528b92.png)

![image](https://user-images.githubusercontent.com/32926873/60800498-27351780-a12a-11e9-8b2d-a70b625bb806.png)

This has actually been around for a while but I just noticed it still hasn't been fixed. 

3. You can entirely skip cutting the cables while disassembling the firelocks and just unwrench + weld them.

**Comment by MarinaGryphon** [comment]
`You can entirely skip cutting the cables while disassembling the firelocks and just unwrench + weld them.` I remember this, this is because of a weird thing with some vars not being properly set, specifically on mapped in firelocks? Not sure.

**Comment by Geevies** [comment]
I believe this has been fixed. Re-open if it happens again.
