### ISSUE TITLE
Integrated Eletronic 'Implants' won't print

### ISSUE THREAD

**Issue by XanderDox** [Aurorastation/Aurora.3#6708]
![roej](https://user-images.githubusercontent.com/8857246/61080932-1ae3df80-a3f4-11e9-8146-2759e1ee1135.PNG)
Pressing implant here does nothing, it will not print.

**Comment by XanderDox** [comment]
Also, I just found out Electronic Devices also don't print.

**Comment by LadyFowls** [comment]
Fixed already
