### ISSUE TITLE
Construction Borg has Unlimited Access to the Odin on Spawn

### ISSUE THREAD

**Issue by Bygonehero** [Aurorastation/Aurora.3#6710]
The construction borg can access the Odin by deconstructing the Odins airlocks, giving access to the areas beyond.

**Comment by Sindorman** [comment]
That is something that should be moderated, not a bug tho

**Comment by Alberyk** [comment]
It is a bug, because central command airlocks are their own type that has a lot of interactions that are different from regular airlocks that stops people from opening them, such as attacking them, using an emag and etc.

**Comment by Geevies** [comment]
i believe this got fixed
