### ISSUE TITLE
Duplicated items from nano-med plus.

### ISSUE THREAD

**Issue by remona-minett** [Aurorastation/Aurora.3#6711]
Round b2c-dpfQ. Latejoined into a lot of lag, and when I made my way to the nano-med plus, it contained 3 advanced burn kits. I dispensed two, but recieved three, and there was still 1 in the machine. In total I recieved four, from a total amount of 3, when I wanted 2. The game stuttered right as I was vending the burn kit.
This was round Round Time 00:51-52. BYOND key jrphoenix303. Afterwards, the game delay picked up and was much more bearable.
![image](https://user-images.githubusercontent.com/50187357/61161708-edfa0000-a4b9-11e9-91f6-a8330cde6f22.png)
![image](https://user-images.githubusercontent.com/50187357/61161717-f6ead180-a4b9-11e9-8b62-97f216fd46e1.png)

**Comment by JohnWildkins** [comment]
probably fixed but probably also BYOND lag anyway
