### ISSUE TITLE
Universal recorders don't work with voice changers

### ISSUE THREAD

**Issue by alexpkeaton** [Aurorastation/Aurora.3#6719]
While a universal recorder is recording a speaker using an active voice changer, a transcript will display the true identity of whoever is speaking, not the changed voice.  

This works regardless of how far the recorder is away.  Tested while recorder is in hand and also while the recorder was three meters away.

Game ID b2d-c69h.

**Comment by Kaedwuff** [comment]
Is recorder magically reads your ID rather than the voice, bad code.
