### ISSUE TITLE
HUDsunglasses make you see cloaked people

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#6723]
Sadly I dont have a picture but it's easy to imagine:

When wearing HUDsunglasses you can see the little boxes that show one's profession (you know, like with all other HUD overlay items: heart for medical, A for assistant, and so on) when they are cloaked. So you can perfectly track them while they think they are invisible. Arrow said this is not intended.

**Comment by OneOneThreeEight** [comment]
This is for specific kinds of cloaking, such as the loadout of the assassin who spawns in IAA clothing and their hand-held stealth generator device. Ninjas, and formerly heisters in the knock-off stealth suit -- have "true" stealth.
