### ISSUE TITLE
Microwave Duplication

### ISSUE THREAD

**Issue by Code2200** [Aurorastation/Aurora.3#6728]
The med bay break room microwave (if that makes any difference at all) duplicated a Donk-pocket.

I put a pocket into the microwave and turned the microwave on. I waited a bit and got impatient and ejected the contents. The Donk-pocket ejected and I ate it. The microwave then dinged and another Donk-pocket was ejected.

**Comment by Sindorman** [comment]
Right, will fix

**Comment by sheeplets** [comment]
F
