### ISSUE TITLE
Fake gravity failure exists while not disabling gravity

### ISSUE THREAD

**Issue by nicemoreoften** [Aurorastation/Aurora.3#6730]
The announcement of a gravity failure is a potential choice for the false alarm event. However, the gravity is not actually disabled, making it immediately apparent that it is a false alarm. 
(Logically, gravity would be disabled, as it's a reaction to the detected feedback surge that would be the sensor glitch.)

**Comment by Sindorman** [comment]
That's the intent?

**Comment by nicemoreoften** [comment]
It's immediately apparent as a false event, removing the purpose of the "false alarm" event. Additionally, similar events, such as false radiation storm, have affects such as actually providing the maintenance access and the fluff of both events support that the gravity generator should be temporarily disabled.

**Comment by HiddenKn** [comment]
Actually disabling the gravity generator would turn it from a false alarm into an actual problem.
I still believe the false alarm serves a purpose as it has scared me several times into temporarily dropping what I was doing before continuing my work.

**Comment by Geevies** [comment]
Fixed.
