### ISSUE TITLE
pAI in RIGS cannot hear sound while worn

### ISSUE THREAD

**Issue by xContextual** [Aurorastation/Aurora.3#6735]
What it says on the tin. Suspect it's linked to the new/fixed audio code.

Produced using CE hardsuit, worn by a M'Sai Tajara. Sounds work when in the rig IIS and not worn, worn but not in the rig, and when moving about normally. Sounds stop working as soon as the RIG is held or worn.

**Comment by xContextual** [comment]
Correction. pAI cannot hear at all while held or worn, regardless of RIG.

**Comment by Sindorman** [comment]
I think it has to do with pAI not being considered in gaming world while held/worn?

**Comment by Karolis2011** [comment]
Test & Todo for #6814
