### ISSUE TITLE
prescription eyewear that have a meson overlay dont actually let you see anything unless the mesons are activated.

### ISSUE THREAD

**Issue by ghost** [Aurorastation/Aurora.3#6737]
all of them do this. aviators, prescription mesons, everything. 

this is very frustrating because A: it makes zero sense, if they are prescription lenses they should always allow you to see through them, and B: you cant do most jobs without wearing proper eyewear and a character that needs prescription glasses has a hard time functioning. with jobs that require mesons, your only option is too either not be able to see anything that isnt 2 squares ahead of you or choose a prescription meson in the loadout. 

for glasses like the aviators, where they can function as both a normal worn item and an efficient tool, this is worse. at first i just ignored the issue with the mesons and simply also chose prescription glasses in the loadout, but when i chose the aviators i had assumed it would work better but its the same problem. 

i just want a pair of glasses I can both wear and use. if they are prescription lenses they shouldnt lose their effect simply because they arent turned on.

**Comment by Doxxmedearly** [comment]
Don't have these anymore
