### ISSUE TITLE
Syndicate borgs have a broken description on the uplink

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#674]
![image](https://cloud.githubusercontent.com/assets/11579997/17386719/a59467fe-59c3-11e6-89cf-a281b0569aeb.png)

**Comment by skull132** [comment]
woups. I think I know where I fucked it.

**Comment by Alberyk** [comment]
Also, due to it, you can summon more than one gank-bot.

**Comment by skull132** [comment]
I was dumb and didn't read the New() args correctly. Falling back onto named args fixes this.

Pushed onto dev and live on the test server pending restart.
