### ISSUE TITLE
Alarms can reveal SAT core camera

### ISSUE THREAD

**Issue by nicemoreoften** [Aurorastation/Aurora.3#6740]
![image](https://user-images.githubusercontent.com/16868528/61410129-90d6c380-a898-11e9-820b-4edb6b5ad9d2.png)
Everything is working as intended, but it has the potential to become "Captain, what is that nuke in the vault if we don't have a nuke?" Round 2

**Comment by OneOneThreeEight** [comment]
Won't fix, not directly anyway. That thing needs to be less obvious. Nuke sign's gotta go.

**Comment by Doxxmedearly** [comment]
Closing since not a bug
