### ISSUE TITLE
Fade Hairstyles have been kidnapped by the system

### ISSUE THREAD

**Issue by Mwahahahaha** [Aurorastation/Aurora.3#6745]
**STOP RIGHT THERE!**
HAIR POLICE!

There seem to be five different hairstyles which are all named "Fade", making only one of them accessible on the setup.

![image](https://user-images.githubusercontent.com/3950115/61430241-ed4ee700-a95b-11e9-93d5-6ca97f16f20a.png)

That's ten penalty points each.
_It's people like you that make me sick._
What have you got to say for yourself? Punk?

**Comment by Mwahahahaha** [comment]
![image](https://user-images.githubusercontent.com/3950115/61430499-87169400-a95c-11e9-9d97-6f61411c248d.png)

**Comment by Mwahahahaha** [comment]
(Complimentary music)
https://www.youtube.com/watch?v=yB92M5vYN_Q

**Comment by Sindorman** [comment]
Bad code

**Comment by OneOneThreeEight** [comment]
Will fix.

**Comment by Mwahahahaha** [comment]
_A few split ends spoil the bunch._
🔫😠☝  Not IN TMy CITY!!!!!!1
_I'm going to take you down to the shithole you piece of shit come from.
**MY TREAT.**_

**Comment by Mwahahahaha** [comment]
_i;M gonna  TEach you some manners down town._
**_LEt'S SEE WHAT YOUR BAD CODE CAN DO FOR YOU THEN_**

👊 **HYAH!**
Think you're _bad_, huh? _Bad_ code, huh?
🤜 **KAPLOW!**
By the time we're done with you, you're gonna be walkin' these streets STRAIGHT and CLEAN.
💇 **H'YAH!**
_let's see you try to be bad now._
