### ISSUE TITLE
A few dionaea issues.

### ISSUE THREAD

**Issue by flimango** [Aurorastation/Aurora.3#6756]
A few issues I ran into while experimenting with the new dionaea changes. 

1. It is possible to re-absorb a nymph into your gestalt using the incorrect absorb command (the one used for absorbing SOMEONE ELSE'S nymph into your gestalt. This results in you NOT regaining a limb, and instead just missing one. You cannot re-detach, though you can still switch to the nymph and do... well, nothing. 

It got progressively buggier after this. Detaching another nymph and re-absorbing it correctly, then detaching, caused me to be inspected as not missing any limbs, while missing both limbs. I was also able to exponential growth as a nymph. I am not sure if this is always available or if I bugged out later and don't have it available anymore. 

EDIT: I now see that i was missing exponential growth while in a nymph at one point. I also could not use other abilities such as Hide or Vent-Crawl. 

2. Aghosting and then re-entering your gestalt, then swapping to your nymph causes your nymph to fall down in the SSD/Disconnected state. When swapping back, you will take several seconds to wake up. 

3. I regrew a limb that I already had. So to re-iterate, I regrew my right grasper and tendrils twice. 

To expand on this, re-merging with my detached nymph after the phantom regenerating limb caused me to... not get my other limb back. I had to ahelp for a rejuv :(

**Comment by Sindorman** [comment]
For 1: How did you manage to do that? I tried to use wrong verb but it would not let me.

2. That is normal, given how Aghost works and how switching works.

3. This should be already fixed

**Comment by flimango** [comment]
1. I believe it involved clicking on the nymph while in the gestalt form. 

2. Also I am pretty sure that they just stood in place before I broke it. 

3. Awesome!
