### ISSUE TITLE
Energy pistol doesn't charge after cryo

### ISSUE THREAD

**Issue by Nantei** [Aurorastation/Aurora.3#6770]
I retrieved the Warden's energy pistol from cryo storage, noticed it didn't have a firing pin for some odd reason, and installed one. After doing that and trying both a wall mounted charger and floor mounted one, I found it wasn't charging, wasn't changing modes properly (from stun to lethal and vice versa), and wasn't able to fire. 

Game ID: b2n-cEy1
Relevant Staff: Karolis2011

**Comment by Karolis2011** [comment]
Details: Most notable issue - power cell is missing from gun. (Aka = null) Runtime logs need to be investigated.

**Comment by Karolis2011** [comment]
I am sorry, I am unable to find source of issue. This migth have been once off hickup in server.
