### ISSUE TITLE
Dionae Gestalt Detatched Nymph Death

### ISSUE THREAD

**Issue by ArtofWASD2** [Aurorastation/Aurora.3#6780]
Hi! I am aware that a Gestalts ability to detach a limb such as an arm to become a controllable nymph is a relatively new addition to the mechanics. But i have discovered an issue. Whilst playing as said nymph, If the nymph is killed you are sent into ghost mode. Your character is completely dead and you are unable to just die as a nymph and return to your LIVING gestalt body. 

Note: I have only died as a nymph whilst crawling through the vents on station and being sucked into a valve or scrubber. But im pretty sure the bug applies to any nymph death.

**Comment by Sindorman** [comment]
You are able to switch to gestalt by re-entering your nymph dead body and using "Switch to Gestalt". I tested it, let me know if it does not work

**Comment by Xelnagahuntr** [comment]
I had this happen last night, my nymph died when I vent crawled into a scrubber as is spit out lethal gas of some sort. When I tried to *re-enter body* it told me I didn't have one, so I got locked out of the round after that.

**Comment by ArtofWASD2** [comment]
Just double checked. When a nymph dies via scrubbers OR a tank filling
valve their corpse is completely removed from the map. Thus there is
nothing to re inhabit.
