### ISSUE TITLE
Record consoles missing key features

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#6789]
When interacting with employee/security/medical records consoles (which were recently transferred to the VueUI system), the console no longer produces typing sounds as it should. This appears to be the case with VueUI consoles in general, but specifically no longer occurs when it used to for records consoles.

![image](https://user-images.githubusercontent.com/22651198/62001161-631b2700-b0af-11e9-82da-3172c106202a.png)

Edit: Also missing:

- Any form of sorting. Apparently random.
- Record printing.
- Creating new records.

**Comment by Karolis2011** [comment]
If you mean when search is used - it won't induce sounds. VueUI allows to reduce Client -> Server communications. Sounds should still be present when you select record, or edit it, or delete it, or create it.

Please clearify do they occur during those cases or not?

**Comment by TheDocOct** [comment]
I can confirm that they do not occur in any of these instances, and on top of that, should be present during log in/out and exiting the view of a record. On top of that, creating a new record doesn't appear to function at all, and the list of records are also not sorted in any reasonable way (alphabetical, by department, etc.), if that is not out of the scope of this report.

**Comment by Karolis2011** [comment]
New record feature and was there since day 1. 
![](https://user-images.githubusercontent.com/11229891/64759087-ea790880-d53e-11e9-8f4c-b9801d05a519.png)

Sorting: Originally records didn't have sort, so now there isn't sort.

Printing - yes, needs to be addressed
