### ISSUE TITLE
Donk-pockets don't receive reagents while heated

### ISSUE THREAD

**Issue by VTCobaltblood** [Aurorastation/Aurora.3#6802]
Donk-pockets are supposed to get 5 tricord when microwaved, while sin-pockets are supposed to give some powergaming chems upon activating their box. Neither works, and honestly the code for them is shit. Please fix?

**Comment by alsoandanswer** [comment]
I'm pretty sure some shitcode has been gutted by accident over the years

or maybe some undocumented nerf in a certain patch which removed the healing properties of tea...
