### ISSUE TITLE
Tajara - Faster When Thirsty/Hungry

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#6815]
As a normal tajara, as soon as I get thirsty I appear to be going faster. This has been consistent across several rounds, and I'm positive I'm not lagging or something. 

![10776403e7eedd385feb9eb7f23930f1](https://user-images.githubusercontent.com/12206154/62400752-ffc54500-b545-11e9-9e95-f97009ea463c.png)
This is around when it starts happening.

Being starved definitely has the same effect.

**Comment by Kaedwuff** [comment]
Are you sure this isn't intentional? I've heard furries get very motivated by thirst.

:3

**Comment by Fortport** [comment]
> Are you sure this isn't intentional? I've heard furries get very motivated by thirst.
> 
> :3

It's a bug,, dork.
