### ISSUE TITLE
Unfulfillable bounties

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#6816]
![image](https://user-images.githubusercontent.com/11053780/62400788-82520280-b54e-11e9-9b62-5ec492217ca2.png)

-3 burst is not attainable and no weapon attachments modify burst delay to be less than 1.

@Arrow768

**Comment by VTCobaltblood** [comment]
Enhanced grip modifies it to less than 1 iirc, but yeah.

**Comment by OneOneThreeEight** [comment]
That's just for fire_delay, which influences single shot guns only. The enhanced grip enables for less heavily capped semi-auto fire rates.
