### ISSUE TITLE
R&D synthetics cannot deconstruct some items

### ISSUE THREAD

**Issue by veraknocks** [Aurorastation/Aurora.3#682]
items may include
1. advanced mass spectrometer
2. pico manipulator
3. hyper capacity cell (appears to not work)

AMS and manipulator require usage of an upgraded machine-version deconstructive analyzer, but cannot be deconstructed by the analyzer module R&D synthetics are outfitted with

**Comment by skull132** [comment]
Closed due to issue clearance.

Not confirmed.
