### ISSUE TITLE
Idris Battle Chefs

### ISSUE THREAD

**Issue by NotSchwann** [Aurorastation/Aurora.3#6820]
EXPECTED RESULT: Idris Incorporated detective
Result: I spawned as a detective IRU wearing a full chef's uniform. Also I still had detective access.

@VTCobaltblood 
![Battle Chef](https://user-images.githubusercontent.com/45934768/62419636-418fe180-b653-11e9-8dab-4af4f24a702b.png)

**Comment by VTCobaltblood** [comment]
this is incredible
Will fix though. Thanks reviewing devs.
