### ISSUE TITLE
Rubber Bullets Have Same Hit Effect As Real Ones

### ISSUE THREAD

**Issue by Fortport** [Aurorastation/Aurora.3#6823]
When you shoot someone with rubber bullets, the effect makes it look like you shot them with a real one. Blood sprays out, and makes it look much worse than it actually is. This is an oversight that should have been addressed when they were integrated.

If you're worried that there's not enough visual feedback from shooting someone, you could make it so that a smacking sound is played from the rubber hitting them and then bouncing off. Or just remove the effect entirely and leave it as is.

**Comment by Geevies** [comment]
Rubbers do damage, it's less-than-lethal. The hit effect is a fine visual indicator.
