### ISSUE TITLE
I can hold my breath underwater

### ISSUE THREAD

**Issue by bs0599** [Aurorastation/Aurora.3#6827]
Simple fix for many a person who has been ailed by the mechanic of resting in the pool: give a good thirty second delay before popping somebodies lungs underwater. Because I can hold my breath underwater without popping lungs, and my character should be able to too.

Considering a popped lung can easily cause severe brain damage which can kill someone, and take you out of a round permanently, I believe this is a reasonable request.

**Comment by sheeplets** [comment]
Totally agree, but this is the wrong place to post this. The Issues hub is just for bugs and oversights. Make a thread here instead.

https://forums.aurorastation.org/forum/4-suggestions-ideas/
