### ISSUE TITLE
Cyborgs can't be moved into charging stations

### ISSUE THREAD

**Issue by NanakoAC** [Aurorastation/Aurora.3#683]
If a cyborg runs out of power, it can only be fixed by installing a new powercell, which requires certain access to open it.

You can drag a drained cyborg to a recharging unit, but there's no way to push, pull, hoist or drag it in to start charging, and it cant move under its own power.

pushing a cyborg into a charger should be possible

**Comment by veraknocks** [comment]
i believe a synthetic can load itself into the recharger if placed nearby, they just have to be aware of their surroundings

**Comment by LordFowl** [comment]
A synthetic with a drained battery cell can still technically move, and thus can put themselves into the charger if brought there.

**Comment by AgentWhatever** [comment]
Damaged borgs however can't. I just had that happen. Could right-click the charger and press enter, but nothing happened.

**Comment by NanakoAC** [comment]
fixed in #980
