### ISSUE TITLE
Corporate Liason lack of access to expected rooms in command

### ISSUE THREAD

**Issue by Nerrathiel** [Aurorastation/Aurora.3#6838]
Corporate Liason doesn't have access that you'd obviously expect to be able to get into, as they are 'civillian' portion of the command area. Namely:
 - Break Room [Main level]
 - Conference Room [Main Level]
 - Auxiliary Office [Main Level]
 - Command Study [Surface Level]
 - Randomly doesn't and does have access to bits and pieces of command maintenance. [No access in command surface, has access to main level maint.]

Suggestions: 
 - Allow access into all specified rooms [NOT CRYOGENICS Room - They have their own cryo aboard NTCC Odin].
 - Allow access into command maintenance. They have access to command, and access to maintenance, but not command maintenance. It's unintuitive derp.

**Comment by KingOfThePing** [comment]
They are no command member. They do not need access to these rooms.

**Comment by Arrow768** [comment]
Not really a bug, since they are not a command member.
They only need to pass through command to get to/from their shuttle (which they can do)

**Comment by Geevies** [comment]
Closing, this is intentional.
