### ISSUE TITLE
Rescue Pod Survivor / Visitor Ghost Spawn IDs don't work properly.

### ISSUE THREAD

**Issue by VisVirific** [Aurorastation/Aurora.3#6847]
Through the use of the Ghostspawn as Visitor, I did not have access to my bank account and couldn't buy anything from the vendors.

While as a "Rescue Pod Survivor", my ID did not have the access it properly should have as a Liason, as it couldn't open the door to the Representative Office, nor did it have access to a Personal Bank Account.

I have not attempted to reproduce the issue as both times were their technical first times of using the Ghost Spawn to spawn as Visitor and Rescue Pod Survivor.

Seeing as I wasn't aware this might be a bug, I didn't save the Visitor Game ID, but after Ahelping as the Stranded Corporate Liason, Arrow helped me by orienting with filling out the Github Issue.
**Rescue Pod Survivor game ID:** b2G-bYq4

**Comment by VTCobaltblood** [comment]
You are not a liaison attached to NSS Aurora. You were going elsewhere (Mendell City in your case), so it makes perfect sense that you can't access anything on the station.

**Comment by runecap** [comment]
Why would you have access to the station if you're a random person who crashed, not even meaning to go to the Aurora? This isn't a bug, it's, unironically, a feature.
