### ISSUE TITLE
blood_dna for bloodsplatter not populated

### ISSUE THREAD

**Issue by K0NFL1QT** [Aurorastation/Aurora.3#688]
Additional to #186 

Swab kits fail to get DNA off dried blood, or they fail to get any DNA at all off 'special' mob blood. Tested that a swab kit did successfully pick DNA off my own characters blood that I intentionally spilled, so it's not completely broken. However, that same swab kit couldn't be inserted to the electron microscope, it instead gave the message 'this swab has already been used'. You can transfer the used swab to a microscope slide but using the microscope on that slide scans for gunshot residue instead of DNA.

Additional to #98 
Microscope still doesn't have right click eject option, although alt-click isn't that bad. It's just not obvious.

**Comment by skull132** [comment]
Issue: the blood_dna variable of blood-spatter does not get populated in some cases. This makes the swabs not work.

Issue #186 was observed due to the same thing (the dried blood lacked blood_dna). The state of the blood has nothing to do with it.

**Comment by K0NFL1QT** [comment]
Swab kits that do have blood on it can't currently be inserted into the microscope.

**Comment by NanakoAC** [comment]
i touched on this a bit with devour code, and ill probably be involved in it again in future

**Comment by skull132** [comment]
Did a decent amount of testing into it, and I've yet to find an instance _during testing_ where the DNA field of blood splatter isn't populated. Both with round start mobs (proper DNA generation) and non-round start mobs (potentially dubious/lazy DNA generation).

It happens, I know that much, but the conditions seem to be tricky and not generalized.

**Comment by FirinMaLazors** [comment]
It looks like you can just use the DNA analyzer now to get DNA?  I tested this with regular spatters, drips, and arterial streaks, from skrell and human.  DNA analyzer appears to work.  Electron microscope seems to be for fingerprints and fibers.  Probably worth closing this issue, unless we've heard about this before in the recent past?
