### ISSUE TITLE
Medical's Main Storage request console is mislabeled as "Psychiatrist's Desk"

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#6909]
![Untitled](https://user-images.githubusercontent.com/44004468/63643979-f5145080-c6aa-11e9-9eda-abe56ed2f0bd.png)

In addition, there's like three other request consoles in the main floor that are all labeled as "Medical Bay" except when I try to send a fax to one I can't find the other end for the life of me. Something is goofy here.

**Comment by CodePanter** [comment]
I'll look into this. With a bit of luck I can fix this after I get home.
