### ISSUE TITLE
Dionaea not regaining limb when nymph rjoins them

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#6932]
Had a dionae split a nymph and it rejoined later, but it said the limb was still missing, and didn't work.

EDIT- Admin-readded one, and this happend 
![Capture](https://user-images.githubusercontent.com/31339047/64057281-f93be480-cb68-11e9-8c34-4d6b8804d6da.PNG)

The status bar for it regrowing did not show before or after adding the new hand.

**Comment by Sindorman** [comment]
Probably because admin readded one

**Comment by Sindorman** [comment]
Explain how you added the limb

**Comment by Yonnimer** [comment]
Had a arm spawned in, reattached it with surgery.

**Comment by Sindorman** [comment]
That won't work for Diona intentionally iirc
