### ISSUE TITLE
Taped paper can't be removed from surfaces anymore

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#6948]
![image](https://user-images.githubusercontent.com/11053780/64214086-0e708600-ce7d-11e9-9f4f-ccaa607ad0b4.png)
this is what i mean

can't remove it from any angle

only resolution is to delete the paper via admin powers

**Comment by MarinaGryphon** [comment]
Shoot. For some awful reason, taped paper is anchored. I mean, I get why, but... ugh. Okay. This can be fixed but it'll be annoying.

**Comment by Geevies** [comment]
Fixed.
