### ISSUE TITLE
Non-human wizards cannot wear the gem-encrusted voidsuit

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#695]
When you 'buy' the gem-encrusted voidsuit to wear as a wizard, if your species isn't human, you cannot wear it. Running it through a suit cycler to make it fit your species completely replaces it with whatever type of hardsuit the cycler would make.

**Comment by skull132** [comment]
Fixed in #744 
Will be pushed live tomorrow.

**Comment by skull132** [comment]
Fixed, closing.
