### ISSUE TITLE
CCIA HUD

### ISSUE THREAD

**Issue by UnknownMurder** [Aurorastation/Aurora.3#697]
CCIA doesn't have their own hud. 
![image](https://cloud.githubusercontent.com/assets/7517616/17464761/2705d8a0-5cac-11e6-86b6-f7994316e629.png)

Here's .dmis to help your repair go faster.
https://github.com/Aurorastation/Aurora.3/blob/master/icons/mob/hud.dmi

But, I cannot find where the code is.

**Comment by LordFowl** [comment]
This is being tended to in Nanako's HUD overhaul.

**Comment by NanakoAC** [comment]
yep already working on it, ill try to get it done for the next patch (later this month, not tomorrow's patch)

**Comment by skull132** [comment]
Fixed now.
