### ISSUE TITLE
IPCs Affected By Flashbangs (and go deaf too)

### ISSUE THREAD

**Issue by runecap** [Aurorastation/Aurora.3#6980]
IPCs are affected by flashbangs. This makes no sense as the sound from the grenade wouldn't do anything to disorientate. They also go deaf, which also makes no sense because a flashbang wouldn't disrupt their eardrums because they have none.

round ID initially found: b3a-c4Hs

**Comment by SebkillerDK** [comment]
They can also seemingly go deaf from explosions.

**Comment by Geevies** [comment]
I rule it as it blowing out their sensors, as a similar thing can be seen from flashing a stationbound. Doesn't make a lot of sense, but it's for balance reasons.
