### ISSUE TITLE
Placing stackable items down on a surface randomizes their position as if they were thrown

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#6984]
@fernerr 
![whZSaEk](https://user-images.githubusercontent.com/44004468/64738721-0092b480-d4be-11e9-9c12-584df28684e4.gif)

Also affects refined ore coming out of the sheet stacker in mining.

**Comment by fernerr** [comment]
Undecided if I'll be changing this as it can become problematic to place down a bunch of stacks on the same surface.

**Comment by sheeplets** [comment]
If you run out of real estate to click on the tile then just throw them, or use the turf tab to click the table directly.
