### ISSUE TITLE
Maintenance drones cannot see emotes/actions while worn as a hat or held in a hand

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#700]
When you're a maintenance being held in someone's hand or worn as a hat, you cannot see emotes or any other form of sight based action/line/etc, not even your own. You can still emote, and others can see it, however.

**Comment by NanakoAC** [comment]
this is a bug, passemotes should be making this work. Ill fix it

**Comment by NanakoAC** [comment]
Fixed in #869

**Comment by skull132** [comment]
Fixed in #891
