### ISSUE TITLE
Necropolis Scientists spawning in the wrong uniform

### ISSUE THREAD

**Issue by NotSchwann** [Aurorastation/Aurora.3#7000]
Issue: NI scientists (I'm not sure on alt titles yet) spawn wearing their old research uniform, and not the updated version. I have not had time to test the tan uniform yet, but I can confirm the black research uniform does not work. I had to get Alb to spawn a new uniform for me.

Evidence: 
![NI Uniform Bug](https://user-images.githubusercontent.com/45934768/64928320-a313a600-d7e4-11e9-8fa7-bec8414152da.png)

**Comment by ParadoxSpace** [comment]
Looking into it.
