### ISSUE TITLE
Tacticool Sprite Displacement

### ISSUE THREAD

**Issue by EvilBrage** [Aurorastation/Aurora.3#7004]
The sprite for the tacticool turtleneck, when viewed from the side, is displaced too far down - this is most readily apparent when switching the shoe layer, as any footwear becomes invisible when wearing a tacticool and viewing it from the side.

Easy enough to fix, just shuffling the side view of the tacticool up a few pixels will solve everything.

**Comment by Haldreithen** [comment]
Fixed in PR #7062, only has to be approved

**Comment by EvilBrage** [comment]
The sprite's placement is fixed, but now boxers show through the pants.
