### ISSUE TITLE
Maintenance drones cannot see LOOC when inside a container that's inside a second container (I.e.: Box inside a backpack)

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#701]
Similar to the emote issue. Maintenance drones cannot see LOOC from other players or themselves, but can still see LOOC messages (We just can't see our own message making it seem like it doesnt work) while inside a container that's inside a second container, such as being put into a box that is in turn inside a backpack.

**Comment by NanakoAC** [comment]
I'm aware of this, and a number of other related problems.

This one might be the easiest of them to fix, will see what i can do

**Comment by NanakoAC** [comment]
Fixed in #869

**Comment by NanakoAC** [comment]
fixed months ago, closing
