### ISSUE TITLE
Sometimes modular weapons makes broken projectiles

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#7012]
There is a chance someones that it could spawn a broken projectile that if stepped on, shoots you.

**Comment by fernerr** [comment]
Is it reproducable? Is it completely random or with a specific set of components?

**Comment by SonicGotNuked** [comment]
> Is it reproducable? Is it completely random or with a specific set of components?

The gun seemed to have fell apart in a failure I think. I didn't fire it. The projectile was invisible, but if you stepped on it, it'll calculate a chance to hit you.
