### ISSUE TITLE
Surgical Borgs don't have anesthetics/painkillers.

### ISSUE THREAD

**Issue by SomeoneOutThere** [Aurorastation/Aurora.3#702]
http://forums.aurorastation.org/viewtopic.php?f=18&t=6720

Pretty much sums it all up,surgery borgs don't have any means to put patients in need of surgery to sleep unless someone else sets up the anesthesia.

**Comment by NanakoAC** [comment]
fixed by #714 
This doesn't mean i like you >.>

**Comment by skull132** [comment]
This was implemented. Closing.
