### ISSUE TITLE
Mining drill heads can be remotely activated by the AI

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#7026]
This essentially causes the drill to blow up if its not secured, making mis-clicks literally death if you're unlucky.

Probably applies to borgs aswell. Might be a feature, but its a dumb one to say the least.

**Comment by Sindorman** [comment]
It would make sense for mining borgs

**Comment by Geevies** [comment]
It's useful for mining borgs, as well as for the AI to be able to activate drills for lazy miners if they somehow get camera access. I'd rule this not an issue.
