### ISSUE TITLE
North Crystal Therapy Door on Exodus not Working

### ISSUE THREAD

**Issue by TheBurninSherman** [Aurorastation/Aurora.3#7029]
On the returning Exodus map the door on the north side of the crystal therapy room of medical is not opening for doctors or psychs. Its not a horrendous problem but its a problem I thought I should mention, as it is probably a bug and was talked as such when I asked about it in LOOC.

**Comment by fernerr** [comment]
Should be fixed in the latest Exodus bugfix, thanks for the report.
