### ISSUE TITLE
Syringe bug, chemistry

### ISSUE THREAD

**Issue by LobbyZ** [Aurorastation/Aurora.3#704]
So basically, http://i.imgur.com/BdmoikZ.png 

It happened when I injected liquid into the implant but I guess I clicked too fast? Because it kept saying that it kept adding the solution even though it had none and the syringe it self looked "full" so to say but when I drew more liquid from the bottle, it reset and worked fine untill empty again when it was buggy again.

**Comment by skull132** [comment]
:ree: autoclose.
