### ISSUE TITLE
Announcements Not Heard on Centcomm or on Departures Shuttle

### ISSUE THREAD

**Issue by SleepyWolfe** [Aurorastation/Aurora.3#7063]
Announcements Not Heard on Centcomm or on Departures Shuttle, they should be visible because the consoles allow you to make announcements and frequently command makes end-of-shift announcements.

**Comment by runecap** [comment]
This is probably because removing announcements from non-station zlevels includes the main zlevel where all the small maps are (which is z1 aka centcomm).

**Comment by Geevies** [comment]
This is intentional, I believe.
