### ISSUE TITLE
You can move-down inside closets, allowing you to travel through any floor.

### ISSUE THREAD

**Issue by Menown** [Aurorastation/Aurora.3#7098]
You're able to move-down through flooring anywhere just by utilizing a closet. This allows you to kill yourself, access the sub-level, and other fun stuff that shouldn't be possible.

**Comment by Sindorman** [comment]
I was unable to replicate it. Can you give me an example of when it happened. Tell me what mob you were playing and what species and which closet type? That would help a lot

**Comment by Menown** [comment]
@Sindorman This still exists. It works inside body scanners.
