### ISSUE TITLE
Holder runtime error

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#710]
[13:56:20] Process obj caught exception processing /obj/item/weapon/holder/mouse/white (the mouse) (0,0,0): Cannot read null.loc in mob_helpers.dm, line 934

**Comment by NanakoAC** [comment]
I KNOW i've fixed this before
This PR hasn't been merged properly, and is possibly related. I think something's gone wrong in the repo 

https://github.com/Aurorastation/Aurora.3/pull/691

**Comment by skull132** [comment]
https://github.com/Aurorastation/Aurora.3/commit/468243db7ed91f913b472a6741c7d9f8f0a8f2ce

It ain't missing. This is from the master branch log.

**Comment by NanakoAC** [comment]
fixed by #731
