### ISSUE TITLE
Game: b3w-ajX1 | Mining / RIG - Thermal Drill, broken.

### ISSUE THREAD

**Issue by Cevet** [Aurorastation/Aurora.3#7104]
Hello! 
So I acquired a Thermal drill from the point vendor, placed it through the RIG module cycler, attached it to the RIG and everything, along with a jet pack. Later on, once outside, I tried to use the Thermal Laser and was unable to do so, no matter what. It would always say I am "attempting to engage the thermal laser" while it was my primary selected module. But would never actually engage or do anything. 

I Ahelped this, and was assisted by Simon_The_Minor ? I think is the full name. We spent a good five minutes or so trying different things, but nothing worked. Eventually they just asked me to open up a bug-report on the issue (which I'm doing now) and got another admin to give me a regular Thermal Drill, which did work perfectly fine with no issues. (Hand-held, not RIG module)

If there's anything else I need to post or say, just let me know I guess? But really it's all there.

**Comment by JohnWildkins** [comment]
Unable to replicate. Is it possible you were trying to engage it instead of firing it (middle mouse button)?
