### ISSUE TITLE
Mindbreaker or space drugs causing muteness

### ISSUE THREAD

**Issue by JMJ99** [Aurorastation/Aurora.3#7108]
This just happened to two medical staff after being exposed to it from a scrubber over pressure. To my knowledge they aren't meant to cause this. told to make a bug report by prate after ahelping

Round ID: b3x-aIWP

**Comment by VisVirific** [comment]
It was a Red Gas that had Rainbows Hallucinations like Space Drugs without any other effects or toxins, although did not have _any_ taste text or traces of whatever it was in the blood. Pulmodeiectionem through an Autoinhaler didn't fix it, and it was _probably_ fixed via Isolation Therapy or something.

The Muteness wasn't detected as a Brain Trauma in the Health Analyzers or Body Scanners.

**Comment by MarinaGryphon** [comment]
Fixed in #7109
