### ISSUE TITLE
Broken airlocks with bolts dropped cannot be fixed or deconstructed

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#712]
If you have an airlock with its bolts dropped, and you break the panel/circuitboard, it seems to be impossible to repair or deconstruct the door. Deconstructing requires having all wires except the bolt wire cut with the bolts up - Otherwise, trying to crowbar the circuit out tells you the bolts are in the way. There are seems to lack any method to repair a door like this without removing the circuit board and replacing it with a new one.

It is also impossible to lift the bolts on the door when the circuitboard is broken.

**Comment by Alberyk** [comment]
Did you try welding it and then removing the whole airlock out of place with a crowbar?

**Comment by SierraKomodo** [comment]
That is not something I was aware was an option.
