### ISSUE TITLE
The new age restriction system doesn't recognize the minimum for alternate jobs. 

### ISSUE THREAD

**Issue by GillianDaemon** [Aurorastation/Aurora.3#7122]
So Nurse is the only job title in medical doctor that isn't required for your character age to be atleast 30 yet it still crosses out the job when my character is below 30. maybe separate Nurse from the medical doctor slot? since Nurse is grouped together with Medical Doctor the new system doesn't recognize the minimum age for alt jobs.

* Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!
* Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.
* Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
* All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera.

**Comment by TrickingTrapster** [comment]
An additional note. If you try to latejoin as nurse now, it doesn't show up in the join game window.
