### ISSUE TITLE
Chem dispenser freezes if a bucket is used to mix chems.

### ISSUE THREAD

**Issue by raywindz64** [Aurorastation/Aurora.3#7146]
Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.
* Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!
* Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.
* Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
* All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera.

--------

Issue: Used a bucket at Exploratory Chemistry in science. The interface froze when the chemicals mixed.

Chemistry dispenser was despawned and respawned but problems persisted.

Game ID: b3E-bAvR
Assisted by: Pratepresidenten

**Comment by JohnWildkins** [comment]
Can't replicate. Do you happen to remember the particular mixture you used? Was it just an normal bucket?
