### ISSUE TITLE
Zo'rane fire un-mixable.

### ISSUE THREAD

**Issue by Dark1Star3s** [Aurorastation/Aurora.3#7148]
You cannot make Zo'rane fire. 

The recipie is, ("nitroglycerin" = 2, "pyrosilicate" = 2, "phoron" = 3, "zoragel" = 3) <Direct from the code.
However the issue here is. Nitroglycerin explodes upon mixing. So you can't even finish step one for Zo'rane fire. I have tried Cryostasis beakers too, but Nitroglycerin mixes and explodes, before it can mix with the rest of the ingredients for Zo'rane fire. Meaning it deletes the rest of the ingredients on mixing because it literally explodes them.

Desired Outcome: A nice unit of Zo'rane fire.
Current Outcome: An explosive death from Nitroglycerin.
Possible Fix: Change the recipie for Zo'rane fire. My suggestion. (Liquid Fire OR Phosphorous, Inert Gel, Phoron.)

**Comment by MarinaGryphon** [comment]
I'd suggest replacing the nitroglycerin with phoron salts. :)
