### ISSUE TITLE
Antag selector system is borked

### ISSUE THREAD

**Issue by Butterrobber202** [Aurorastation/Aurora.3#7150]
During round ID: b3F-ajUl

the game decided there were not enough antags readied up for the Ninja gamemode, but.

https://gyazo.com/96dc5996a54d4d96a45c864fc65cf59d

https://gyazo.com/3f451ae7879e0c2b99beac7a3e495af1

Me and Kyres both have the pref on, yet we were not selected, and I'm sure in a lobby of 40+ more than two people had it enabled.

**Comment by Talkarcabbage** [comment]
It's also seemingly been broken at least for some rounds for malf and some others. (wizard I believe?)

**Comment by Geevies** [comment]
I think this has been resolved with the antag fix PR, and skull's further config tweaking. Please keep an eye out though, I'm keeping this open.

**Comment by Talkarcabbage** [comment]
Noted again at  #7275 for slightly different behavior. Admittedly I have also noticed an obscene number of ninja+/-wizard rounds but haven't kept track enough to see if any other gamemodes have shown up much, so it _could_ be a coincidence.

**Comment by Geevies** [comment]
Reverted PR that caused this.
