### ISSUE TITLE
Slot Machines Don't Work?

### ISSUE THREAD

**Issue by Loneguyfly** [Aurorastation/Aurora.3#7157]
Round ID: b3H-aAPL

Description of Issue: Slot machines don't seem to work? I've tried taking out cash, I've tried a credit chip, I've tried my ID, I've tried it all. I cannot get the slot machine to let me play it, I just get the "The slot machine has been hit by [player name] with the [item]." message regardless of what I try to shove into it. 

Length of Issue: At least one round. I've not really tried to use them before.

**Comment by Alberyk** [comment]
You need to use coins
