### ISSUE TITLE
Mech Instant destruction

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#7160]
Round ID was b3H-bvvT
Kyres was having two mechs punch the  shit out of each other, so we decided to bring in the Marauder as a NT prototype and show the smoke and it's strength. Couple punches later me and the other mech pilot activated crash at which point the two mechs sprint into each other taking the marrauder down from 97% to 0% in a seccond without explosion or anything. Pretty baffling moment and requires serious fixing, because otherwhise the Oddy can take out any combat mech with one punch.

**Comment by NonQueueingMatt** [comment]
Fixed by new mech update most likely?
