### ISSUE TITLE
Ovens seem to not cook until they reach at least 40% efficiency (80°C), candy machines and cereal makers don't work at all

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#7190]
@JohnWildkins 

Whatever you put into an oven before this point will stay at the "It is cold" phase, and anything made in the candy machine or cereal maker will stay at that point for an indefinite amount of time.

**Comment by sheeplets** [comment]
Update, I am an idiot and now realize that this is what preheating is. Shitcode has spoiled me rotten up until now.

**Comment by JohnWildkins** [comment]
On it.

**Comment by JohnWildkins** [comment]
Speaking of shitcode, in my efforts to make ovens calculate cooking power properly, I accidentally made it so mixers literally never had cooking power. Easy fix, sorry about that. I've lumped it in with the other tweaks to circuits and the like since it touches the same code.

**Comment by StationCrab** [comment]
@JohnWildkins Would it be possible to speed up the heating time on the oven just a smidge? During power fluctuations it can be very hard to get the ovens back up to speed. We are in the future shouldn't we have a bit faster ovens! :)

**Comment by JohnWildkins** [comment]
> 
> 
> @JohnWildkins Would it be possible to speed up the heating time on the oven just a smidge? During power fluctuations it can be very hard to get the ovens back up to speed. We are in the future shouldn't we have a bit faster ovens! :)

I'll think about it. #7174 means the minimal operating efficiency is now 70% so it shouldn't be nearly as painful, but I'll agree that the times - even nerfed from what they were planned to be (like, a 30 minute preheat) - are still a bit long and tiresome. If I ever free myself from #7180 my next planned UI overhaul is for the oven, and when I dig into the code then there'll no doubt be room for other improvements (including making the whole heating system actually make sense)
