### ISSUE TITLE
Some Load-Out Items will not load in unless named.

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#7203]
With the addition of being able to name our loadout items, it seems that some (but not all) loadout items won't load into the round if unnamed. Two examples being workboots and the winter coat, hydroponics.

I have heard of another player having this issue although I did not ask what items they had trouble loading in.
There is a chance that you have to either save or reselect their items.

**Comment by Geevies** [comment]
@Mwahahahaha

**Comment by Alberyk** [comment]
Try removing and readding them?

**Comment by Geevies** [comment]
I believe this was fixed. Re-open if not.
