### ISSUE TITLE
Using a Welding Tool to cut open a steel trap with someone inside causes them to be deleted.

### ISSUE THREAD

**Issue by Fandilicious** [Aurorastation/Aurora.3#7210]
Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.
* Do a quick key word search of the git for duplicate reports. If you find any, simply post a reply onto that issue instead!
* Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.
* Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
* All additional details help. Such as round ID, an admin you talked to if the issue required immediate fixing, etcetera, etcetera.

Using an industrial welder as an engineering cyborg I attempted to cut out a player from a steel trap. When the weld completed, the trap vanished and so did the person inside it. The player that was inside it ended up as a ghost. 

Round ID: b30-bCeS
I spoke with secondary admin Pratepresidenten when the issue occurred. I haven't attempted to reproduce it as it would involve another player.

**Comment by JohnWildkins** [comment]
Can't replicate normally, however there are enough problems around the code responsible for this that I don't doubt that this happened on a weird edge case. Will try for a refactor soon.
