### ISSUE TITLE
Taking a mech up stairs caused teleportation two Z-levels up.

### ISSUE THREAD

**Issue by Brutishcrab51** [Aurorastation/Aurora.3#7212]
Now. I attempted to walk up stairs in a Durand from Security on the main level, to the firing range on the construction level. What occurred was, I went on the stairs, and was suddenly on the surface outside of the Red Dock. No rhyme or reason. Sonicgotnuked asked for me to file a bug report.

b3O-cvfo was the round ID.

**Comment by fernerr** [comment]
Duplicate of #6036
