### ISSUE TITLE
When multiple people are trapped in the large trap, using release on the trap only frees the most recent person and bugs the others into being stuck to the floor

### ISSUE THREAD

**Issue by synystersparx** [Aurorastation/Aurora.3#7219]
Checklist before you submit an issue! Feel free to partially or fully delete this in your eventual report.
* Please be specific in your description of the issue. Explain the desired result (what should be happening) and the actual result (what is happening). Simply stating that [something happens] is not very helpful at describing what's wrong.
When at least two people are in a trap, and a third enters, when someone else comes along and releases them using the verb "Release Animal," only the most recent person is released, and the others are stuck to the floor forever. Ideally it should unstick all that were in the trap. I believe this would happen even if there were only two in the trap and a third person released. The first person trapped would be stuck. Haven't witnessed firsthand, however.
* Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
This has happened to me twice now.
Both times I was the third person in the trap and a fourth person came to release us.

The biggest question is, should multiple people/mobs be allowed to fall into the same large trap? Preventing multiple mobs from entering de facto fixes this. If not, captured needs to be a list.

**Comment by Sindorman** [comment]
Traps are intended to contain one person at a time. This is the source of this bug
