### ISSUE TITLE
(Broken) APC deconstruct procedure not the same as APC construct.

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#723]
Doesn't make sense also. APC deconstruct is (knock down broken door,) remove cell, unscrew, remove terminal ??, crowbar out circuit and then weld the frame.
Why would you have to remove the terminal before inserting the circuit?
APC construct is make APC frame, attach to wall, create terminal, insert circuit, secure circuit, insert cell, close cover

**Comment by Spoopy11** [comment]
You don't have to remove broken frames, I thought this was the case too.
Once you've removed the electronics, simply click the broken frame with a new frame.
So it'd go:
Break frame > Cell > Wires > electronics > replace > Wires > electronics > Cell
This method will restore it to how it was functioning before, i,e if the equipment is manually set off, the new APC will also be switched off.

**Comment by skull132** [comment]
Methods work as coded. Reworking them would be a suggestion, and needs to go into the forum.
