### ISSUE TITLE
Right-clicking on any turf as the AI shows a "flash" option.

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#725]
Has been there since ever. I decided to finally post something about it.

http://puu.sh/qxqEX/d4d67e005a.png

**Comment by skull132** [comment]
Not a bug, oversight.

I do believe Nanako is looking into a fix, but it's not damaging to gameplay. It's most likely to do with what the AI's examine verb accepts as an argument.
