### ISSUE TITLE
Not getting a camera feed from any type of borg (So not limited to command modules only)

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#726]
As a clarification: Normally you'd see what the borgs are able to see from their viewpoint. As in, the map clears of static. This doesn't happen anymoe

**Comment by skull132** [comment]
I've started spotting runtime errors around the AI eye and cameras. I'll look into getting a few from the server and posting them here.

**Comment by Arrow768** [comment]
Fixed in dev.
Ai gets feeds from borgs now
