### ISSUE TITLE
Sound range bork as fuck

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#7267]
You can hear a gunfight from a mile away.
Range and place where issue was found:
Stationed at port command maintenance access (By starboard sec entrance) --->Command elevator firefight. Heard it perfectly well as I was present.

Played borg, had mesons active.

**Comment by Kaedwuff** [comment]
I can confirm it's really borked. As an AI being emitter memed, I was unable to actually hear the emitter going off until I was already dead, despite it burrowing through three walls to reach me.

**Comment by fernerr** [comment]
I'll look into the emitter issue also when I get around to fixing the gun ones. Let me know if there's any sounds that are inaudible that really shouldn't be.
