### ISSUE TITLE
It's been basically nothing but Ninja and Wizard for the past week.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#7275]
This is probably the stupidest fucking bug report ever but for the past week or so, it's been back to back Ninja and Wizard rounds. Given that there were issues with gamemode picking another week ago, I think the issue is still here. No way in hell that the game is picking Ninja, wizard, or both this much.

**Comment by Geevies** [comment]
PR's been re:b:erted.
