### ISSUE TITLE
Maintenance Drones Cannot Place Camera Assemblies

### ISSUE THREAD

**Issue by Aurum22** [Aurorastation/Aurora.3#728]
After a drone grabs a camera assembly with the magnetic gripper, it cannot place it on a wall- it simply tries to push the wall every time with the message "You push the wall, but nothing happens." The camera remains in the gripper during this time and is not placed.

**Comment by SierraKomodo** [comment]
Cameras aren't installed by placing them on a wall. You drop the camera assembly on the tile in front of the wall, then use a wrench on the assembly to attach it to the wall.

**Comment by skull132** [comment]
https://wiki.baystation12.net/Guide_to_construction#Security_Camera

> Place the camera assembly on the **tile** where'd you like the camera to be.

Not wall. The tile. Not a bug, closing.
