### ISSUE TITLE
IPCs are able to replace their limbs with human limbs in the character setup screen

### ISSUE THREAD

**Issue by Crosarius** [Aurorastation/Aurora.3#7286]
In the Character Setup screen an IPC can select the Limbs: Adjust option, and if they select "Normal" as their limb state that limb will be Human in game. The limb appears on all inspections to be a regular IPC limb to examination, inspection and internal diagnostics and on the sprite, however it is Human: It generates pain damage when hit, it slowly heals itself, it cannot be welded or repaired with cable coils, and when examined after being damaged it has tiny bruises or patches of fresh skin, does NOT appear on a roboticist's analyser and its maintenance panel can't be opened.

As side effect of this, **I am also able to self repair my other limbs as an IPC.** I have no idea as to why this might be because I am not a mighty adonis-esque coderman. I can only speculate that *perhaps* it's seeing me as a Human with prosthetic limbs? 

HOW TO REPRODUCE:
Make an IPC character, adjust limbs, and set limbs to Normal. Load into the game and enjoy your fleshy limbs and ability to repair your non-fleshy limbs.

![image](https://user-images.githubusercontent.com/30341877/67661037-e77d8e80-f9ab-11e9-861d-9241ae14633f.png)
![image](https://user-images.githubusercontent.com/30341877/67661064-f82e0480-f9ab-11e9-9b5c-ce0a73dc13dc.png)
![image](https://user-images.githubusercontent.com/30341877/67661129-23b0ef00-f9ac-11e9-8eb1-b230836dc710.png)
![image](https://user-images.githubusercontent.com/30341877/67661152-33303800-f9ac-11e9-8f28-efbe08cf8f79.png)
![image](https://user-images.githubusercontent.com/30341877/67661159-39beaf80-f9ac-11e9-9620-6f99ba68e36a.png)
![image](https://user-images.githubusercontent.com/30341877/67661213-56f37e00-f9ac-11e9-84d7-b656071bf986.png)
![image](https://user-images.githubusercontent.com/30341877/67661238-65da3080-f9ac-11e9-96fd-8acf8e2ca5aa.png)
![image](https://user-images.githubusercontent.com/30341877/67661269-7a1e2d80-f9ac-11e9-86bf-aa7ee3a4b5e5.png)

**Comment by TehFlaminTaco** [comment]
F e a t u r e

**Comment by MarinaGryphon** [comment]
The self-repair check probably checks for `issynthetic()` which returns false at the first instance of an organic limb.
These IPCs have organic limbs and are, technically, organic. So they can repair themselves.
:agony:
