### ISSUE TITLE
Pathogenic Isolator Breaks when inserting a Syringe With Viral Blood from a Blood Bag 

### ISSUE THREAD

**Issue by VisVirific** [Aurorastation/Aurora.3#7293]
* When a Syringe with the Blood from a Blood Bag has been Bred with a Virus and is inserted into the Pathogenic Isolator, the Pathogenic Isolator freezes with no way to remove the Syringe asides complete deletion of the machine. It only breaks if the Syringe with the Blood from a Blood Bag has a Virus, otherwise it functions normally.  The desired behavior for the Pathogenic Isolator is to open its screen with the blood sample revealing the sample to be infected with a strain.

* Have you tried reproducing the issue? If yes, steps to reproduce it would help immensely!
Reproduction steps are the following:
1. Take a Blood Bag from one of the freezer in the Sample Storage, place it in the All-In-One Grinder, grind it to get the blood from the Blood Bag.
2. With a Syringe, take the Blood from the Large Beaker. Place the Syringe in the Pathogenic Incubator with a Virus at sufficient Growth Density and Breed the Virus into the sample.
3. Take the Syringe out of the Pathogenic Incubator and place it into the Pathogenic Isolator.

* Game ID: b3X-bRkz
I have ahelped the issue 2 times. TheGoret took both tickets and we learned what exactly was causing it to break after some mild trial and error.

**Comment by Doxxmedearly** [comment]
Closing since virology was removed
