### ISSUE TITLE
Disconnecting and reconnecting disables AOOC

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#730]
I'm not an experienced antag so this may be limited to just revolution, which is where I noticed it.

If you quit the game and reconnect, then you lose the ability to speak in AOOC, you can hear everything there but you can't use it.

Again, might just be revolution.

**Comment by skull132** [comment]
No, it's for all gamemodes.

Will be looking into it over the weekend.
