### ISSUE TITLE
Cigarette vending machines display the 'unpowered' sprite despite being powered and operational

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#732]
Screenshot for reference, showing the wire and vending panel for the machine to show it is powered, despite the game showing the dimmed/unlit 'unpowered' sprite:
http://i.imgur.com/SN5neXb.png

What causes this, I'm not entirely certain. I have a theory that this happens if the machine becomes unpowered for any reason, then regains power, but the sprite doesn't update. However, I haven't had the chance to test this in-game yet.

**Comment by SierraKomodo** [comment]
And for reference, this is what a powered sprite should look like: http://i.imgur.com/0Jkwzvj.png

**Comment by Arrow768** [comment]
Do you have further details how this can be reproduced ?

**Comment by SierraKomodo** [comment]
This report was posted nearly a year ago which was before the baymerge IIRC, I'm not sure if the bug in question even still exists.

From memory, it seemed to happen primarily if an APC's power output was shut off, then turned back on (I.e., a power shut-off event). The usual place I noticed this was the cigarette vending machine in the bottom right corner of the central primary hallway.

**Comment by skull132** [comment]
Closed due to issue clearance.

Not confirmed.
