### ISSUE TITLE
Mobs not being able to ventcrawl went a pipe somewhere breaks

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#7375]
Usually, if a pipe breaks somewhere (usually an explosion) simple mobs are unable to vent crawl with the message "This vent is not connected to anything.". This includes scrubbers and vents

**Comment by TheDilShawn** [comment]
Bumping this. For whoever sees this, you can fix it by detaching a vent and mounting it on the floor again, any vent fixes the entire map until the pipes bug out again.
