### ISSUE TITLE
NT Troopers are not properly recognized by SecHUD

### ISSUE THREAD

**Issue by FiePhi** [Aurorastation/Aurora.3#7380]
GameID: b39-deJ4

Issue: Security ERT Troopers do not have NT logos, or LI's showing above their heads when using SecHUD. Likely the same for other types of NT Troopers. These Troopers were spawned via the distress beacon system.

**Comment by NonQueueingMatt** [comment]
No LI is intentional

NT logo not showing up isn't, will be fixed
