### ISSUE TITLE
Modular omputers don't close the GUI when shut down

### ISSUE THREAD

**Issue by NonQueueingMatt** [Aurorastation/Aurora.3#7387]
The GUI should close. It does not.

Looks weird because then you can use the computer as normal while it has the shutdown sprite, whereas if you open the GUI while the computer is off there's a different sprite.

Should be a simple fix.

**Comment by mikomyazaki** [comment]
Couldn't reproduce. GUI shut properly across multiple players using the same console when one of them hit the shutdown button.
