### ISSUE TITLE
Blank cigarettes extinguish immediately

### ISSUE THREAD

**Issue by alsoandanswer** [Aurorastation/Aurora.3#7390]
I'm 100% sure it's because it was originally coded to have 0 reagents in it but still smoke, so it was a cigarette which burned and looked cool but did nothing reagent wise

Since now it's linked to reagents, having no reagents basically means it always dies as soon as you light it

**Comment by Menown** [comment]
Yes. That's how they work. They're blanks for you to fill with other things.
