### ISSUE TITLE
Xenoarchaeology Depth Analysis Scanners 

### ISSUE THREAD

**Issue by runecap** [Aurorastation/Aurora.3#7393]
Depth Analysis Scanners are a critical tool in xenoarch for finding out what depth certain items are, and to know if there's even anything there- however. Right now, if you look at Depth Analysis Scanners, they have no sprites, meaning that you can't select them from bags or Xenoarch belts if you put them in there. The only way to use them right now is to keep them in your hand.

Steps for Replication
----------------------
1. Go to Xenoarchaeology
2. Open lockers
3. Alt-click turf and see sprite-less Scanners
4. Put in bag
5. Unable to remove without using Empty Contents verb

**Comment by fernerr** [comment]
This is addressed in #7384

**Comment by XanderDox** [comment]
The PR to fix this issue appears to have been closed w/o merge.

**Comment by fernerr** [comment]
> The PR to fix this issue appears to have been closed w/o merge.

This was adressed in #7414 instead.
