### ISSUE TITLE
Changeling Arm Blade can't hurt borgs

### ISSUE THREAD

**Issue by Vizendel** [Aurorastation/Aurora.3#7430]
As the title says, changeling armblades can't hurt borgs even on harm intent.
It gives a constant crowbar message about not being able to open their cover, and additionally pulls tiles off of the floor.

**Comment by Nero-07** [comment]
Well, for whatever reason, an armblade is a crowbar

/obj/item/weapon/melee/arm_blade/iscrowbar()
	return TRUE

**Comment by Doxxmedearly** [comment]
Should have been fixed in #7481 
Probably a duplicate bug report.
