### ISSUE TITLE
Shells (and possibly all IPCs) can eat crayons.

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#7439]
Shells can eat crayons. Hilarious as it is and as much as I don't want to report it, it should be addressed. As a side effect to the bug, shells can actually gain energy nutrition from eating crayons. It's possible that all IPCs can eat crayons as well, although I have not yet tested it.

![mmgrayons](https://user-images.githubusercontent.com/56227386/69003361-8c541180-0943-11ea-9a61-cd365e7e23e0.png)

**Comment by JohnWildkins** [comment]
intended, closing

(it's probably just missing an isipc check)

**Comment by Doxxmedearly** [comment]
Yeah. It gets around that since it's handled differently from eating it. Will fix
