### ISSUE TITLE
Atmos Tech PDA doesn't spawn with cartridge.

### ISSUE THREAD

**Issue by Doxxmedearly** [Aurorastation/Aurora.3#7476]
Round: b4k-dz2d
Pretty much right after the PDA update.

Atmos tech PDAs don't spawn with the cartridges. I was readied up and spawned at round start. Not sure if it happens for other jobs.

**Comment by Aboshedab** [comment]
Tested this.

Can't replicate it.

**Comment by Doxxmedearly** [comment]
Was fixed in wezzy's latest PR. Report wasn't closed. Resolved.
