### ISSUE TITLE
Persistent lung damages after operation

### ISSUE THREAD

**Issue by Shelkad** [Aurorastation/Aurora.3#7513]
I had a patient with 30 lung damages and collapsed coming into medical, after proceeding to an operation to fix it the damages were persistent despite being unable to fix anything else on the operation table and showing N/A on the medical scanner. 

Admin intervention was necessary to fix the issue.

**Comment by MarinaGryphon** [comment]
What species were they?

**Comment by Shelkad** [comment]
All people involved were humans

**Comment by Alberyk** [comment]
Might have to do with peridaxon.

**Comment by Shelkad** [comment]
I can't confirm or deny that any was given. 
I did not gave peridaxon as the damages were over 10 and we had to operate anyway. But it is possible that someone else injected some as it is frequent in medical to have people injecting a lot of stuff without saying anything.

**Comment by NonQueueingMatt** [comment]
Fixed
