### ISSUE TITLE
Idris Cap doesn't show on player sprite

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#7524]
My character was offered the cap, however in putting it on we quickly discovered it doesn't show in game on the character sprite. The player of the contractor thought it was an issue unique to their character due to a hairstyle however it persisted on my shell as well. Removing my antenna did not change anything.

![idriscapgithub](https://user-images.githubusercontent.com/56227386/69770936-3fd3c600-11ce-11ea-8be3-b9ee8077cd54.png)

**Comment by Aboshedab** [comment]
https://github.com/Aurorastation/Aurora.3/pull/7535

Fixed here.
