### ISSUE TITLE
Contractor IDs cannot unlock cyborg/robot chassis.

### ISSUE THREAD

**Issue by StationCrab** [Aurorastation/Aurora.3#7525]
I encountered an issue where a Roboticist with a Hepht contractor ID received an access denied message when attempting to unlock my chassis. 

I have not tested this with other contractor IDs to see if it is an issue with all.

Asked in the Posi discord if this was intended and was told no, and to make this bug report, so here it is. May require further testing/investigation.

**Comment by Aboshedab** [comment]
Tested. No issue with ID's swiping.

This is most likely a result of them using their PDA to swipe, which has always been a thing. A PDA with a ID that has enough access won't work. You need to use the ID by itself.
