### ISSUE TITLE
Medical residents dont have morgue access

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#7533]
Not sure if bug or oversight. They have access to the cloning bay (Not machinery), but neither of the morgues.
Makes little sense that they would not have this.

**Comment by KingOfThePing** [comment]
I don't know, interns or residents probably (realistically) should not handle bodies alone anyway. Has always been like this and it rarely, rarely matters at all, for example when you tell an intern to throw a body into the perm morgue.
