### ISSUE TITLE
Robots cannot place camera assemblies using the Magnetic Gripper.

### ISSUE THREAD

**Issue by Arzion5** [Aurorastation/Aurora.3#754]
When trying to put a camera assembly on a wall using a magnetic gripper, it shows the "you push the wall but nothing happens" message twice.

**Comment by skull132** [comment]
Similarly to #728 : not a bug.

You don't place assemblies on the wall. Please refer to the guide: https://wiki.baystation12.net/Guide_to_construction#Security_Camera

> Place the camera assembly **on the tile** where'd you like the camera to be.
