### ISSUE TITLE
Pulling A Gun You Hold Removes The Firing Pin

### ISSUE THREAD

**Issue by MedLit** [Aurorastation/Aurora.3#7544]
If you hold ctrl and click your gun with the same hand that holds it, the pulling icon appears. If you click around, you will find that your gun cannot fire. The trigger will be locked and the gun will be missing its firing pin.

I took an energy pistol out of cryo, and did this after accidentally discovering that you can pull the gun while you hold it. Tried installing a firing pin, only for it to start click-clicking and telling me one was already installed after trying to insert another.

**Comment by Doxxmedearly** [comment]
No longer possible to do this.
