### ISSUE TITLE
Magnetic Grippers are unable to place objects into the R&D Destructive Analyzer.

### ISSUE THREAD

**Issue by Arzion5** [Aurorastation/Aurora.3#755]
Self-Explanatory. Robots are forced to use their own internal Destructive Analyzer, and they are unable to place objects into the actual Destructive Analyzer.

**Comment by skull132** [comment]
Intended design.

Enabling borgs to use the actual destructive analyzer would require borgs to be able to pick up **everything**, which is not going to happen.
