### ISSUE TITLE
Numpad keys don't change targeting doll zones, uses movement instead

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#7554]
Had to change all my macros today because none of the numpad keys are working for me. 8 goes north, 6 goes east, 4 goes west, 2 goes west.

**Comment by KingOfThePing** [comment]
Try pressing the "Num" key. Make sure the light on your keyboard is lit up.

**Comment by Nero-07** [comment]
Also you have to be in hotkey mode (press tab) to use just the numpad keys. Otherwise it's ctrl+numpad

Both work for me.

**Comment by OneOneThreeEight** [comment]
I'm just dumb then
