### ISSUE TITLE
Organ transplants - seemingly broken.

### ISSUE THREAD

**Issue by bearschwanz** [Aurorastation/Aurora.3#7555]
during the brainmed merge on the second round I'd discovered a bug when testing a lung transplant on a monkey where it would not accept its own lungs, instead having it say that the lungs had been successfully transplanted but they just plopped onto the floor instead. Someone who was watching said it was a bug they had on baystation when they ported brainmed.

Ahelped it and Matt took the ticket and noted the bug and said in ooc after he'd fixed it.

However now even without brainmed the same thing is happening with old med. I tried with two separate monkeys trying either pairs of lungs and despite them having the same blood type, same thing kept happening. I've done the process just before brainmed was merged and it worked fine so not sure what's up.
I was preserving the lungs with the freezer too.
Tried with the heart too and the same thing happened. Unsure if it's just monkeys.
![image](https://user-images.githubusercontent.com/58423464/69953026-8584eb80-154c-11ea-94a1-2cf00e61e0df.png)

**Comment by NonQueueingMatt** [comment]
fixed in brainmed
