### ISSUE TITLE
Pressure regulators

### ISSUE THREAD

**Issue by Leudoberct1** [Aurorastation/Aurora.3#7567]
On multiple rounds now I've noticed pressure regulators not functioning. Even when unlocked and the pressure available is equal to or above the target pressure, the flow rate remains a solid 0 L/s. Not sure what's causing it.

**Comment by Doxxmedearly** [comment]
Can you be more specific about the instances in where this happens? I've been using them lately without a problem. Need to know more about the circumstances.

**Comment by Leudoberct1** [comment]
Seems to happen at random when modifications to the supply line being made, these being a manual valve on the PaP line, a pressure regulator in place of the outpump with the target pressure being 900kPa, and the output on the mixed air console cranked up to max.

After some discussion in the Engie discord, other people have encountered it too, and said that just unwrenching a pipe on the supply line and putting it back fixes it. Seeing as it has an impromptu fix, it might be easier to just leave it rather than trying to get through atmos code.
