### ISSUE TITLE
Surgery: Internal Organs Decline Despite Treatment

### ISSUE THREAD

**Issue by MedLit** [Aurorastation/Aurora.3#7590]
At the time of this report, for the past few days and I have needed the help of admins more than once. I thought it was a brainmed test merge thing, but it has persisted even after the merge was over. I just finished around of SS13 at the time of this post, and it happened before round-end.

I'll give you a blow-by-blow of what happened.

- Patient comes in with fractured chest, 85% blood count, and 20 units of damage on both their heart and lungs. Their lungs are ruptured. They have no internal bleeding or foreign bodies. This should be easy.

- I proceed to take them to the operation room and after they are put to sleep, I start an incision in their chest, clamping bleeders and prying open the incision with retractors. I hook them up to the IV to refresh their blood. After that, I begin fixing their ribcage with the standard fracture steps. Bonegel, then bonesetter, then bonegel to finish. Looking good. I saw open the ribs and open them with the retractor to proceed to organ repair.

- I inject them with dexalin and inaprovaline to remove all suffocation damage and keep them stable during the operation. Their ribcage is still open, and they have **ABSOLUTELY ZERO** suffocation damage. I check their blood count, which is at 100%. Great.

- I mend their heart and lungs once. Then twice. Then three times. Then four times. The heart and lungs sustain damage despite constant mending, medication, and no other problems. I use a breath analyzer on them, and the breath analyzer notifies me that their lungs are ruptured. How? I just mended them with a trauma kit. I double-check to make sure there is no internal bleeding with a fix-o-vein, which unsurprisingly, doesn't do anything.

- I ahelp to confirm that they are bugged. It turns out they may be. Secondary admin Cnaym says the damage is "maxed out and yet they live," before rejuvenating them.

**Comment by NonQueueingMatt** [comment]
Fixed in #7502
