### ISSUE TITLE
Left ear and right ear are switched

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#7605]
It seems that in game, the left and the right ear are switched.

When I wear my left antenna, the game says it's on my right ear despite it being on my left ear on my character sprite.

![ear](https://user-images.githubusercontent.com/56227386/70253370-714c2300-17c6-11ea-8799-bbc3dc782d6e.png)

**Comment by alsoandanswer** [comment]
yeah, the left antenna is hardcoded in to be left ear.

the code isn't here yet for unique left ear and right ear sprites, like inhands.

so unfortunately it's a workaround.
