### ISSUE TITLE
Cult constructs also get hungry

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#761]
I saw this and forgot, sorry.

Anyways, I saw a Juggernaut getting hungry one day, I assume it applies to all constructs.

**Comment by skull132** [comment]
"One day" being when?

It seems to have been patched. If it happens after today's update (now live), let us know.

**Comment by Fire-and-Glory** [comment]
Before the update, though I assumed that fixing spider bots wouldn't fix the constructs, we'll see.
