### ISSUE TITLE
Unathi Can't Eat Dogs

### ISSUE THREAD

**Issue by WigglesworthJones** [Aurorastation/Aurora.3#7611]
From testing: I kill a dog.
I use the "Devour Creature" ability.
Standard text comes up. "You start devouring [DOG], this will take approximately [TIME] seconds. You and the victim must remain still to continue, but you can interrupt feeding anytime and leave with what you've already eaten."
The progress bar appears, fills, goes away.
Dog is still there.
I wait the approximate time. Nothing happens.
I start doing it again. Nothing happens.
I've had this happen multiple times on different rounds.

**Comment by NonQueueingMatt** [comment]
Pretty sure this is fixed now
