### ISSUE TITLE
Unable to make Antihistamine

### ISSUE THREAD

**Issue by sadkermit** [Aurorastation/Aurora.3#7616]
For a while now, _Diphenhydramine_ (made with cryptobiolin and inaprovaline), also called _antihistamine_, has been impossible to make in a chemical dispenser, the only way to get it is from the NanoMed dispensers from medical. This is because when you mix the reagents to synthesise diphenhydramine it bubbles but doesn't create a new chemical, instead leading to an empty beaker with all your ingredients gone. This hasn't been much of a problem until recently when, with the Brainmed merge, a new chemical requires diphenhydramine to be made (though this chemical is also broken, but that's another issue). 

I've reproduced this issue a number of times since diphenhydramine was added a while ago on numerous rounds, my most recent attempt being yesterday. Not hard to reproduce, just mix the aforementioned two chemicals.

**Comment by Doxxmedearly** [comment]
@nonqueuingmatt
```
/datum/chemical_reaction/antihistamine
	name = "Diphenhydramine"
	id = "diphenhydramine"
	result = "diphenhydramine"
	required_reagents = list("cryptobiolin" = 1, "norepinephrine" = 1)
```

missing result_amount =

**Comment by NonQueueingMatt** [comment]
fixed
