### ISSUE TITLE
[BrainMed Test Merge] Unable to make Ondansetron

### ISSUE THREAD

**Issue by sadkermit** [Aurorastation/Aurora.3#7617]
> rscadd: "Ondansetron, a chemical that prevents vomiting and nausea, is made with 1u antihistamine 1u synaptizine 1u water." 

During the recent BrainMed test merges, I've tried several times to make Ondansetron, failing each time, my last attempt being yesterday. I raised the issue with Moondancer Pony in LOOC who said a 5 unit Tungsten catalyst was required (I had already tried a tungsten catalyst, as seen below, a round or two before). The chemical doesn't react at all, leaving the ingredients as-is. I tried a phoron catalyst as well later on which also yielded no results.

Unless you're meant to use _exactly_ 1 unit of each reagent with the 5 unit Tungsten catalyst, I think there's something up with the recipe.

![Ondansetron Fail](https://user-images.githubusercontent.com/58568342/70336057-68983300-1840-11ea-949b-b944f2c9ccae.PNG)

**Comment by Doxxmedearly** [comment]
@NonQueueingMatt 
`/datum/chemical_reaction/ondansetron
	name = "Ondansetron"
	id = "ondansetron"
	result = "ondansetron"
	required_reagents = list("diphenhydramine" = 1, "synaptizine" = 1, "water" = 3)
	catalysts = list("tungsten" = 5)`

Missing result_amount =

**Comment by Doxxmedearly** [comment]
Also we have "diphenhydramine" in the required_reagents, but the reagent datum is reagent/antihistamine. That's why this didn't react at all. Changing it to antihistamine will fix it.

**Comment by MarinaGryphon** [comment]
> Also we have "diphenhydramine" in the required_reagents, but the reagent datum is reagent/antihistamine. That's why this didn't react at all. Changing it to antihistamine will fix it.

No. It was originally antihistamine.

**Comment by Doxxmedearly** [comment]
Shit whoops yeah I mixed up my reagents.

**Comment by NonQueueingMatt** [comment]
fixed
