### ISSUE TITLE
Unable to decontaminate clothing.

### ISSUE THREAD

**Issue by sadkermit** [Aurorastation/Aurora.3#7618]
Yesterday I tasked myself with decontaminating some phoron-soaked clothing (as in it had the huge biohazard symbol and caused toxins when holding it without a biohazard suit)  taken from a patient involved in a science phoron accident. I tried to use the washing machines in the Medical Sub-Level to decontaminate the clothing, one clothing item per washing machine, though after at least 3 spins the biohazard symbol remained (unsure if I was still dealt toxins, however). After A-helping, I was told to submit a new issue.

The clothing items I tried to decontaminate were black surgical scrubs and jackboots.
I haven't tried decontaminating any other clothing items.

I've not yet had the chance to reproduce this issue.

**Comment by skull132** [comment]
Unable to reproduce on current. So probably fixed/no longer relevant, considering issue age.
