### ISSUE TITLE
Autopsy isn't picking up lasers or bullets

### ISSUE THREAD

**Issue by Crosarius** [Aurorastation/Aurora.3#7649]
Backstory: A wizard got gunned down by laserfire and gunshots - they even had embedded shrapnel from lethal .45's However, when autopsied there were only some miscellaneous melee strikes recorded, and 5 baton strikes to the head. **No laser wounds or gunshots appeared.** I'm certain that he was shot because I saw it, he had embedded shrapnel and massive burns on the medical scanner. 

Problem: Lasers and bullets not showing up on the autopsy scanner.

Steps to reproduce: Shoot a dude with lasers and guns, do autopsy. I did some testing myself and confirmed this bug.

![image](https://user-images.githubusercontent.com/30341877/70603402-3755a380-1c42-11ea-90fa-e2f15f44aa2e.png)

![image](https://user-images.githubusercontent.com/30341877/70603369-23aa3d00-1c42-11ea-8337-c5e59b38f478.png)

![image](https://user-images.githubusercontent.com/30341877/70603556-87346a80-1c42-11ea-90ae-1d7107396b33.png)

**Comment by Geevies** [comment]
I believe you fixed this.
