### ISSUE TITLE
Using the fiber collection kit on objects applies your own fibers to the object

### ISSUE THREAD

**Issue by Crosarius** [Aurorastation/Aurora.3#7650]
When using the fiber collection kit on an object that you've NEVER touched before, sometimes you will find your own fibers on the item, because using the item on it in and of itself seems to apply fibers to the object.

![image](https://user-images.githubusercontent.com/30341877/70604281-1e4df200-1c44-11ea-9b4c-e6589edf1d40.png)
![image](https://user-images.githubusercontent.com/30341877/70604312-30c82b80-1c44-11ea-938f-8a4c4f1fa136.png)
![image](https://user-images.githubusercontent.com/30341877/70604382-548b7180-1c44-11ea-8f46-810158f8f1a2.png)

**Comment by Geevies** [comment]
I believe you fixed this.

**Comment by Crosarius** [comment]
Lmao so I did. I totally forgot to close my own bug reports when I fixed
that.
