### ISSUE TITLE
Diona healing process not working for all parts

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#7655]
Noticed that the diona core trunk does not heal at all, while other limbs (leg in this case) perfectly do. Not sure how or why, would just be very gratefull if someone could take a look at that. Thanks in advance.

**Comment by Cnaym** [comment]
Tested a bit more, issue seems to follow spider bites that include the diona getting toxins. Dialysis extracts pure blood and does not help / heal toxins. Trauma kit and radium manage to heal the brute damage really slowly. Hope it helps.

**Comment by NonQueueingMatt** [comment]
"toxins" are just organ damage. Did you check the internal organs?

**Comment by Cnaym** [comment]
Yep, it takes the brute from the core trunk and displays it as toxins, never healing the organ. Thanks again for fixing :3
