### ISSUE TITLE
Chess/Checkers board lag issues

### ISSUE THREAD

**Issue by ben10083-zz** [Aurorastation/Aurora.3#7658]
Chess and checker boards are unplayable as it stands, as there is a severe input lag to the board (long delay to the selection and movement of pieces).

How it is caused:
This one is troublesome, through some Q/A, I have formed a hypothesis. The code is, as Skull put it, Spaghetti. This italian factor to this code means that it updates the status of each individual peice of the board to every player in the game. As such, the more players there are on the server, and the more pieces on the board, the longer the input lag.

As it stands, this renders an entire element of the game unplayable, and makes chess and checker boards become a waste of a slot.

**Comment by Sindorman** [comment]
That's because chess don't use our UI system that uses events instead of having to re-render entire board

**Comment by Karolis2011** [comment]
Board has been rewritten in  #11035
