### ISSUE TITLE
Ian can eat through doors

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#767]
I'm not _quite_ sure how it works, but I've recently seen Ian eat a kitchen's supplies on the other side of a door, close a (see-through) door on Ian to stop him from eating, he'll hug the door and eat food adjacent to the door.

**Comment by Kaedwuff** [comment]
This is probably because Ian doesn't ever actually eat, he just periodically spams emotes about nibbling a food item.

**Comment by NanakoAC** [comment]
He actually does eat now, and will completely devour food he's given
