### ISSUE TITLE
PDA Halogen Scanner Broken, Shows Med Data.

### ISSUE THREAD

**Issue by Talkarcabbage** [Aurorastation/Aurora.3#7671]
Using a PDA with a halogen scanner enabled (or disabled) on it does not use the halogen (rads) scanner but uses some new medical scanner instead. Have not checked with irradiated person, just with 0 rads. Used on self. 

Expected behavior:  
`No radiation detected` or the rad level.
Observed behavior: 

```
You run the scanner over Brenden Donovan.
***
Scan results for Brenden Donovan:
Brain activity: normal.
Pulse rate: 71bpm.
Blood pressure: 116/77 (100% blood oxygenation)
Body temperature: 36.85°C (98.33°F)
No detectable limb injuries.
Reagent scan:
No results.

```

**Comment by NonQueueingMatt** [comment]
This was fixed at some point I am sure, reopen if it wasn't
