### ISSUE TITLE
Bottles and Beakers Break :b:iolently upon Complex Use

### ISSUE THREAD

**Issue by haydongus** [Aurorastation/Aurora.3#7704]
From what I've seen, during round b4J-ddoG, beakers and bottles broke when interacted with beyond picking them up, putting them down, and storing them in things such as bags and pockets.
- This has been every single time, not just once. I believe I heard mention of it happening to other people in medbay as well, so not singular to myself.
- Pouring bottles/beakers into other beakers, using the syringe/dropper to draw from a bottle/beaker, and trying to give it to somebody had this effect. The only exceptions I noted involved directly drinking from the bottle or beaker.
- Whenever I try to basically transfer reagents from one storage to another, I get "The ___ shatters with a resounding crash!"
- This was not the case the previous round to my knowledge, my game was working clientside and I could perform basic chem without any troubles. 
- It was a bother all round, I talked to Pratepresidenten and they were super awesome about it and directed me here. I believe Colette Rogers and Lusula Kazhkz may have also experienced these problems (sorry for not knowing OOC, still kinda new).

**Comment by Doxxmedearly** [comment]
Thanks for reporting. Was fixed in an emergency revert.
God I would have loved to see this in action.

**Comment by LadyFowls** [comment]
This was due to a bugged pr, it has been reverted.
