### ISSUE TITLE
Mecha arms layered under everything(again)

### ISSUE THREAD

**Issue by kyres1** [Aurorastation/Aurora.3#7705]
Title. The fix seen here https://github.com/Aurorastation/Aurora.3/pull/7662 didn't seem to work, with custom mecha still having the arms layered under the cockpit. As well, now they seem to be layered beneath the legs too.

**Comment by Alberyk** [comment]
It looks fine, can you show screenshoots?
![image](https://user-images.githubusercontent.com/11579997/71008702-d0b00a00-20c7-11ea-8d4e-ea1deaaaac8f.png)

**Comment by kyres1** [comment]
![image](https://user-images.githubusercontent.com/36868890/71026858-a82c0e00-20cf-11ea-8778-ff3122d474bb.png)
![image](https://user-images.githubusercontent.com/36868890/71026865-ac582b80-20cf-11ea-8487-0313f93ec3ff.png)
