### ISSUE TITLE
Item stripping issue

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#771]
High priority.

Under normal circumstances, if a character were to move or be moved while being stripped of worn items, the item strip would interrupt.

However, if person A, designated as the item stripper, were to stand in place and fully strip the equipment of person B, the victim, and person B were to walk X amount of tiles away, after the few seconds are over, their items will automatically unequip and drop on the ground. Person A MUST stand in place uninterrupted for this to work.

The end result is that person A has Mr. Fantastic levels of elasticity and is able to take off items from a distance.

Patch this out quick before it's abused, I say. Aside from Jackboot torturing me.

**Comment by skull132** [comment]
The code most likely uses `do_after` and only applies it to the stripper. A
more robust method would be to use `do_mob`, which requires both parties to
be uninterrupted.

Also, if abused, ahelp it.
