### ISSUE TITLE
Forensics Equipment Disappearing When Idle

### ISSUE THREAD

**Issue by krumpmeboyz** [Aurorastation/Aurora.3#7718]
When the DNA analyzer and/or microscope are idle, but contain a piece of evidence, the sprite disappears, rendering the microscope inoperable and the DNA analyzer unable to be used if the cover is closed and menu exited. When the analyzer is running, the sprite reappears, but the microscope, when any slide is put inside, just vanishes never to be seen again.

To reproduce, put anything in either object. The microscope will disappear immediately, and the analyzer will vanish upon closing the lid.

![9502ffdb9391abbc2c9bc38f761fddff](https://user-images.githubusercontent.com/35768639/71044790-ac245400-2100-11ea-9f03-c8998c3f8b85.png)
![8ac9975b6a6994b13fa90d0090cc018f](https://user-images.githubusercontent.com/35768639/71044791-ac245400-2100-11ea-9dd9-a0c544f9fd9d.png)

**Comment by TheBurninSherman** [comment]
Experienced the same problem described above. Can confirm this is an issue.
