### ISSUE TITLE
ATM interactions are bugged

### ISSUE THREAD

**Issue by Bedshaped** [Aurorastation/Aurora.3#773]
When security level is zero; if you walk up to an ATM with your ID in your card slot and click submit without entering your ID it still takes you to your account.

This can be frustrating if you are trying to access an account that isn't your own and you have to throw your ID a few tiles away from you in order to stop the ATM defaulting to your account when you hit "submit".

**Comment by Bedshaped** [comment]
It seems that in modules/economy/ATM.dm when authenticating a user it runs:
`/obj/machinery/atm/proc/scan_user(mob/living/carbon/human/human_user as mob)`

Which will authenticate from a held ID. This is weird because I would expect (at least according to the description for security level zero) that you atleast have to insert a card to access so this might not be a bug but the question is; is it something that should be changed?

I've already explained how it can be frustrating when trying to log into an account that isn't yours.

**Comment by SoundScopes** [comment]
From what I've read of the code, this doesn't seem to be a bug. Level 0 security means that the ATM will scan the user, if their account is level 0 then it will grant access. (Take off your ID and put theirs in your ID slot) Higher security levels will not allow access by scanning of the user. 
The ATM's don't care about who is holding the card, just that the card it finds in the ID slot has an account.
A fix for your frustration would be to set your own security level above 1, then the machine will attempt to use the card inside instead.
