### ISSUE TITLE
Maintenance drones cannot pickup cable that is any color other than red

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#774]
Currently, maintenance drones can 'refill' their wire synthesizer by picking up any red wire coils/loose red wires (Similar to picking up glass to refill the glass synthesizer, or rods/metal for the metal synthesizer). However, any cable that is not red (I.e. yellow, green) cannot be picked up by a maintenance drone.

**Comment by Alberyk** [comment]
#487
