### ISSUE TITLE
Greeting window malfunctioning

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#7845]
Anywhere from 1 to 10 seconds after initially joining the server and the greeting window containing announcements, warning notifications, test merges, etc., popping up- it closes, and I am given the following message.

![image](https://user-images.githubusercontent.com/22651198/71551630-36966e80-29b1-11ea-95c0-4e1debfced08.png)

The amount of time it remains open seems random. Sometimes I can check all of the announcements and test-merges, and then it closes. Sometimes it closes almost immediately after popping up, before I can even interact with it in any way. It doesn't seem to be triggered by any particular action on my part, and I don't see any pattern in when it closes.

**Comment by remona-minett** [comment]
It does this for most people. Not sure why, but you can use the reopen-greeting verb to look at it again. I'm not sure what causes it but it works sometimes and others it doesn't.
