### ISSUE TITLE
You can style hair while unconscious

### ISSUE THREAD

**Issue by alsoandanswer** [Aurorastation/Aurora.3#7855]
memes.

**Comment by Alberyk** [comment]
Using what?

**Comment by remona-minett** [comment]
I would hazard a guess at saying a mirror, because it opens the character customization dialog box, but I'm not certain.

**Comment by alsoandanswer** [comment]
No, literally using nothing. I think it's the tie hair verb.

**Comment by remona-minett** [comment]
Can you open the tie-hair dialog while unconscious, or does this happen if you leave the dialog open and <i>then</i> go unconscious?
