### ISSUE TITLE
T-ray scanner incorrectly displaying manifold pipes & failing to update when moving.

### ISSUE THREAD

**Issue by QuestioningMark** [Aurorastation/Aurora.3#7860]
Issues:
- The T-ray scanner does not properly display pipe manifolds. 
- The T-ray scanner lags when moving tiles and does not properly update - sometimes intermittently flashing.
Extra:
- [Feature issue] The T-ray scanner has such a short practical range it's hardly useful. 
Replication:
I have been able to replicate this issue on multiple rounds. 

EVIDENCE:
https://gyazo.com/ec311b1f8e6724136c742ae5f0b09e69

**Comment by Doxxmedearly** [comment]
The "flashing" is intentional; it only displays the pipes/wires in range whenever it "pulses." It's not a consistent effect. While perhaps an annoying feature, it's not a bug.

It might be a bug that pipe manifolds don't display their connection fully.
