### ISSUE TITLE
NTSL2 intepreter doesn't work anymore apparently.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#7865]
Round ID: b4y-apo0

I don't even know what the issue is or how it occurs, but the NTSL2 interpreter program doesn't work. You can't run the program regardless if you're an AI or a user. I don't know. For some reason I'm being told this despite there being 0 bug reports on this.

Regardless, it didn't work in the round above. A file with print("Hello World") can't be opened/run. I'm not even running byond beta so it's not that.

**Comment by BurgerLUA** [comment]
Related bug. NTSL doesn't work with telecoms. At all. Any code you give it just says there is one error. It doesn't state the error.

**Comment by Karolis2011** [comment]
NTSL deamon might have been down. Log investigation might be needed. But in general NTSL2 is awfull on multiple levels.

**Comment by skull132** [comment]
Fixed and confirmed as fixed on live with updates to the NTSL server.
