### ISSUE TITLE
Taser Beams Cause Explosions By Teleporting

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#7881]
Taser beams (and probably any other hitscan weapon) cause walls and objects to detonate if they are moved into an object via teleportation (i.e. fired into teleporter or hand tele portal)

This might make sense if it's some kind of high energy beam like an emitter or laser cannon, but it is nonsensical that a low energy taser beam would make an entire table explode and vent the room, like happened recently.

Maybe an exception?

**Comment by KasparoVy** [comment]
Lmao that sounds wonderfully ridiculous
