### ISSUE TITLE
You cannot set anyone to arrest anymore via the console.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#7883]
Okay so for some god damn reason the "Criminal" status is a string input and not a list input. Even if that was the intent, I cannot type "Arrest" in the console because it eats my inputs every other letter.

![image](https://user-images.githubusercontent.com/8602857/71647414-9a6bb080-2cab-11ea-9697-512639cbd44a.png)

This is infuriating. As AI you cannot set anyone to arrest status for Beepsky to chase.

**Comment by Kaedwuff** [comment]
While this is a problem, I question your priorities if being unable to set beepsky on people is the chief reason it upsets you. >:P

**Comment by Karolis2011** [comment]
You still can type out `*Arrest*` and it should work. Just it's nolonger a dropdown.

**Comment by Kaedwuff** [comment]
> You still can type out `*Arrest*` and it should work. Just it's nolonger a dropdown.

It's not supposed to be a string though. Not everyone's going to know what to type to use this basic function of security.
