### ISSUE TITLE
Container contents show up underneath the container sprite when moved

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#7899]
Initially. The contents of a closet and crate will appear on top of the container sprite when opened, which is the usual. If you close them, move them, and then open them. The contents of the container will be underneath the containers sprite, instead of above it. Which often forces alt or right clicking to get what was inside unless you move the container, since you can't click on them due to the container sprite enveloping every single item in most cases.

Tested this on multiple rounds.

Here's a picture showcasing it.
https://imgur.com/cURD0P7

**Comment by Geevies** [comment]
I believe this was fixed. Feel free to re-open if it still occurs.
