### ISSUE TITLE
Markup is messing with exclaim_verbs

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#791]
Doing: _ayylmao!_ won't trigger the exclaim_verbs, example:
![](https://i.imgur.com/W1eUCuG.png)

**Comment by nicemoreoften** [comment]
Also, crit/other stutter effects break markup.

**Comment by skull132** [comment]
Not exactly a bug.

It's shit hard to circumvent, though, as those verbs are assigned based on the very last symbol, **after** mark-up is already processed. (Even if done before, it'd catch the * instead of the !.)

**Comment by Geevies** [comment]
Fixed, I think.
