### ISSUE TITLE
Janitor's purple cap.

### ISSUE THREAD

**Issue by Brennuvargar** [Aurorastation/Aurora.3#7919]
When holding the Purple Cap found in the Janitorial lockers, the inhand sprite looks like an ODST helmet and not a purple ball cap.

**Comment by Doxxmedearly** [comment]
Yeah, found this in soft_caps.dm
`	item_state_slots = list(
		slot_l_hand_str = "helmet", //probably a placeholder
		slot_r_hand_str = "helmet"
		)`

Not teeeeechnically a bug but definitely something the spriters should look into.

**Comment by Cairo283** [comment]
Most colored caps use this sprite for in-hand, and have been for years now.

**Comment by alsoandanswer** [comment]
I'll fix it soon, don't worry
