### ISSUE TITLE
format of printed records (off the new laptops) is completely borked

### ISSUE THREAD

**Issue by KingOfThePing** [Aurorastation/Aurora.3#7929]
What the hecc, I can't look at this formatting:
![swefgerd](https://user-images.githubusercontent.com/43940569/71785409-6ff95a80-2fff-11ea-9f64-ccbf81e4c125.png)

**Comment by Karolis2011** [comment]
This is only issue with note line breaks... But bigger picture issue - notes should not contain so much information. Things should be placed in to other fields of records, and they should be editable.

Also other issue migth be - field sorting being odd.

**Comment by KingOfThePing** [comment]
Resolved in the meantime.
