### ISSUE TITLE
Synthetics can see AOOC chat.

### ISSUE THREAD

**Issue by Arzion5** [Aurorastation/Aurora.3#794]

**Comment by Alberyk** [comment]
No, that is probably due to synthetics being assigned as cultists but never being able to be due to job restrictions, so, they still have acces to it.

**Comment by AgentWhatever** [comment]
Still an issue

**Comment by MarinaGryphon** [comment]
`restricted_jobs = list("Chaplain","AI", "Cyborg", "Internal Affairs Agent", "Head of Security", "Captain")`
Do sub-jobs need to be added to this?

**Comment by Alberyk** [comment]
No, alt titles are not take in consideration, still, somehow ais and borgs are selected as cultists round start, don't get anything, but still have access to aooc for whatever reason it is.

**Comment by skull132** [comment]
I don't think this is an issue with job code.

The issue is that synths are sometimes picked as antagonists during roundstart, before antag code knows they're synths, and then later removed once job code kicks in and decides that they're synths. They're left with partial antagonist status after that.

**Comment by chaoko99** [comment]
This isn't a problem anymore.

**Comment by Pratepresidenten** [comment]
It is though. I just had to deal with two cases. One being a borg during a veilparty round, and one maint drone during an uprising round. All within the span of 24 hours.

**Comment by MarinaGryphon** [comment]
Maintenance drones are able to be autotraitored, though, and I think uprising includes autotraitor.  Borgs and AIs in rounds that involve the cult seem to be an issue, though.

**Comment by LadyFowls** [comment]
Cant replicate this, if it happens again we can re-open this
