### ISSUE TITLE
Vaurcae Can Fall Victim to K'ois Mycosis w/ Internals Off

### ISSUE THREAD

**Issue by runecap** [Aurorastation/Aurora.3#7940]
If a vaurca is around sporing k'ois with their internals off, they will suffer from all the symptoms of k'ois mycosis as well as gain toxins from the process.

Game ID found: b45-dgBc

Steps to Replicate:
1. Plant k'ois
2. Allow it to spore while your internals are off and you are vaurca
3. Wait to notice any messages about nausea/signs of liver damage & eventual coughing fits

**Comment by owivia** [comment]
This still happens, but it happens with internals on, too. You just get killed by micosis no matter what

**Comment by NonQueueingMatt** [comment]
fixed
