### ISSUE TITLE
Aghosted AIs do not appear on the lobby manifest

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#7941]
When a staff member is playing as an AI and they aghost, their AI no longer appears on the manifest.

Round ID: b45-dDLK
Server revision:  - 2020-01-06
3377a65b1fff83f7a08871ff14f25691b198fbb0 
Current Map: NSS Aurora

**Comment by mikomyazaki** [comment]
Failed to reproduce as a 'Host' role staff playing the AI. Still appeared on the lobby manifest for my guest account. *shrug

**Comment by JohnWildkins** [comment]
can't reproduce, probably fixed with the manifest rewrite
