### ISSUE TITLE
Medical records physical status cannot be changed.

### ISSUE THREAD

**Issue by Leudoberct1** [Aurorastation/Aurora.3#7946]
Medical doctors cannot change the physical status of a crewmember in the records, so they cannot set it to deceased. At the minute, they have to use the HUD to change it.

**Comment by Karolis2011** [comment]
Please be more descriptive as to make o easier to pin point the problem. Vague descriptions that it didn't can't change is bad. Describe what part fails, editing or saving change?

**Comment by Dunmeritude** [comment]
@Karolis2011 it is impossible to change the physical status or mental status from a console or laptop- or anything that uses medical records listing. The option just isn't there. 
![image](https://user-images.githubusercontent.com/9397405/72290175-7a1fe800-3601-11ea-9f66-38d38bbb3097.png)

**Comment by Karolis2011** [comment]
Oh. I see what is problem.

To understand problem you need to understand how so far records are structured and how it avoids hrdcoding it's fields.

Normal crew records consists of three parts, General, Medical and Security.

General contains common fields and employment fields, like ID, name age, sex and mental / physical status.

Medical contains Fields like blood type, disabilities and so on. 

So the dilemma arises that for security to see mental / physical status it needs to be in general record. If I moved it then only medical could see it, but also could edit it. Well, I could bodge snowflake checks but I don't really want to.

**Comment by Dunmeritude** [comment]
@Karolis2011 The issue remains then that an important feature is missing from the game until this is fixed in some way. Security cannot set someone to arrest from records anymore, which is a field that should only be visible from security records anyways. And Medical cannot change someone’s status to deceased or SSD without scanning them with an HUD, which is cumbersome and tedious.

**Comment by FlamingLily** [comment]
this (as is to be expected for a 3 year old bug), is no longer broken.
