### ISSUE TITLE
Beamcode is a mess (Emitters don't fire straight)

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#7951]
Right. So basically I wasted 20 minutes trying to an emitter to fire in a straight line but it never worked. I don't even know what the actual problem is, probably something to do with floating point precision, but the bug here is that no matter what, the beam doesn't fire straight sometimes when that's absolutely a crucial feature considering blobs exist and malf exist. I'm not insane here because several mods witnessed me and I helped it.

There are a million things that could go wrong here. I can't be bothered to dive through the code further because that's not my job. There are way too many proc calls it uses just to shoot a simple projectile. There are also a lot of useless shit being called such as it trying to get the mouse position of the emitter among other things.

**Comment by BurgerLUA** [comment]
The way it curves leads me to believe that it's trying to target the corners of the turf in front of it because of mistakes involving 16,16 being the center or 0,0 being the center, since byond is inconsistent and likes to use both.

**Comment by mikomyazaki** [comment]
Can you try and write a better bug report with steps to reproduce, or information about how you got it to curve / specific code lines you think are responsible?

Seems to be firing straight to me.

![emitter_shots](https://user-images.githubusercontent.com/47489928/72580816-277e4e80-38d5-11ea-9667-3c154200e829.gif)

**Comment by BurgerLUA** [comment]
> Can you try and write a better bug report with steps to reproduce, or information about how you got it to curve / specific code lines you think are responsible?
> 
> Seems to be firing straight to me.
> 
> ![emitter_shots](https://user-images.githubusercontent.com/47489928/72580816-277e4e80-38d5-11ea-9667-3c154200e829.gif)

Try dragging it around some more or bumping into it several times. It occured when I brought it down to the sublevel in EVA.
