### ISSUE TITLE
Glass to fill light replacer grossly over-priced

### ISSUE THREAD

**Issue by Cairo283** [Aurorastation/Aurora.3#7964]
Alright, so, the light replacer can be filled with glass sheets instead of straight light bulbs and tubes to refill it. The problem is, however, is that while making a light bulb/tube in an autolathe costs barely a half a quarter of a glass sheet, using glass sheets on the replacer uses up _five_ sheets to make one bulb/tube.

This seems horridly over-priced when compared with simply using an autolathe or even ordering a box from cargo. I feel that one sheet of glass on the replacer should grant five lights, instead of the other way around.

**Comment by alsoandanswer** [comment]
I think that was intentional that the light replacer is grossly inefficient - you're supposed to use the autolathe in the first place.

**Comment by Doxxmedearly** [comment]
Not really a bug. Make a suggestion if you feel it should be changed.
