### ISSUE TITLE
Bone breaking issues with fixing them surgically, and psionically.

### ISSUE THREAD

**Issue by homebass** [Aurorastation/Aurora.3#7969]
**Summarization of issue:** Manually fixing your ailed and fractured bones with psionics fixes the bone, but immediately breaks it again. (done by having masterclass in redaction, and clicking on the affected limb with psionics un-suppressed.) For the record, surgery steps used to fix bones leads to this same outcome.

**How it should work:** You should be able to psionically and surgically fix your broken bones and not have them instantly crack apart again for no discernible reason.

This issue seems to exist because bone broken states seem to be applied at a certain brute threshhold for a specific limb, so I'd imagine the game sees that you're still at that threshold and reapplies it because "nope, you can't do that." In "_insert-other-HRP-server-name_", I think bone breaking is done through some special equation instead of a hard threshold, so that's probably what's causing the problem here. If you lower limb damage under the threshold, the bone becomes fixable again.

Tested on the most recent version of the repo as of when I posted this issue report.

**Comment by NonQueueingMatt** [comment]
It breaks because your brute damage is still above the bone breaking threshold, so not really a bug? Autoredaction would be a bit too busted if it also healed below Paramount.

**Comment by homebass** [comment]
> It breaks because your brute damage is still above the bone breaking threshold, so not really a bug? Autoredaction would be a bit too busted if it also healed below Paramount.

If you say so, seems like a bit of an oversight though. To me, personally, it seems a bit jank to go through the steps of fixing a bone just to have it dissolve into a million pieces instantly because you didn't wait for the numbers to go down.

**Comment by Doxxmedearly** [comment]
@NonQueueingMatt it seeeeems like there's a check for this in psionics, but it's not working?
`
if(heal_internal && (E.status & ORGAN_BROKEN) && E.damage < (E.min_broken_damage * config.organ_health_multiplier)) // So we don't mend and autobreak.`
