### ISSUE TITLE
'tile' object with no sprite

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#798]
I've discovered a empty-sprite tile object, I'm not sure where it came from. I was not able to pick it up using the floor tile synthesizer while having space in the metal synthesizer thing to pick up tiles with.

Full object path of the spriteless object courtesy of IJ: /obj/item/stack/tile

Screenshot shows the examine description of this object, and the object as shown when alt-clicking the tile it exists on:

http://i.imgur.com/k1Z08dL.png

**Comment by SierraKomodo** [comment]
Addendum: I think this 'tile' object may have come from objects being ejected out of a broken disposal pipe that was under an intact floor tile

**Comment by skull132** [comment]
Closed due to issue clearance.

Not confirmed.
