### ISSUE TITLE
Interactions between compressed matter implants and storage items are buggy

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#799]
With how it works currently, if you try to put a compressed matter implanter in your backpack, or your backpack into your implanter, then the implanter goes into the backpack and the backpack goes into the implanter. 

The result of this paradox is that both your backpack and your implanter are gone forever.

There seems to be a special interaction between the implanter and 'box' storage items to make it go into the box and not vice versa.

You can also bypass this by filling the backpack to maximum capacity before using your implanter to store the pack.

**Comment by SierraKomodo** [comment]
Out of curiosity, would clicking on an empty slot inside the backpack instead of clicking on the backpack itself also bypass this bug?

**Comment by Fire-and-Glory** [comment]
It didn't when I checked, I didn't look into that factor _too_ much though.

**Comment by skull132** [comment]
Closed due to issue clearance.

Not confirmed.
