### ISSUE TITLE
Minimum reliability for destructive analyzer arbitrarily reassigned

### ISSUE THREAD

**Issue by dr-ehle** [Aurorastation/Aurora.3#800]
The destructive analyzer is initially given a minimum reliability on disassembling objects of `90`.

This value is arbitrarily redefined in the `RefreshParts()` proc. Minimum reliability is set to `93 - T` with `T` being a modifier based on current parts in the destructive analyzer.

This may have the effect of making research and development harder than was initially intended.

Affected file is destructive_analyzer.dm

**Comment by Alberyk** [comment]
Bay merge removed reliability, no more an issue.
