### ISSUE TITLE
Expedition Maps not loading on server restart

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#8004]
Basicly getting a log on roundstart that no expedition maps loaded.  Wildkins suggested it might be due to a conflicting PR that removed the /dir from existance, but since I am a big dumb dumb, I will post this here and let the pros handle it. 
Thanks in advance c:

Initialized Jobs subsystem within 0 seconds!
Map file derelict.dmm for ruin derelict does not exist.
Map file listening_post.dmm for ruin listening post does not exist.
Map file pra_blockade_runner.dmm for ruin pra blockade runner does not exist.
Map file sol_corvette.dmm for ruin sol corvette does not exist.
Map file scrapheap.dmm for ruin scrapheap does not exist.
Map file diona_gestalt.dmm for ruin diona gestalt does not exist.
Map file spacehulk.dmm for ruin spacehulk does not exist.
Map file kataphract_chapter.dmm for ruin kataphractchapter does not exist.

**Comment by Arrow768** [comment]
Not a bug.
Configuration Issue.
