### ISSUE TITLE
AI can't see cult runes through cameras or holopads.

### ISSUE THREAD

**Issue by ShameOnTurtles** [Aurorastation/Aurora.3#801]
As the title says. As an AI, I couldn't see cult runes through the cameras or when I appeared through a holopad. The runes in question was the teleport rune, and the invisible wall rune.

In this instance, there were invisible wall runes at each entrance to the chapel, and I think there were some teleport runes scattered around as well.
![image](https://cloud.githubusercontent.com/assets/21190338/17882501/e5ac6c2c-6960-11e6-879b-e6603173bb0f.png)

**Comment by Alberyk** [comment]
It is a feature.
