### ISSUE TITLE
Holding things up to cameras no longer works for AIs

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#8013]
Holding stuff up prompts the link, but clicking it yields nothing.

**Comment by mikomyazaki** [comment]
Can't reproduce. Any other info you can give about this? Is it still happening?

![paper_test](https://user-images.githubusercontent.com/47489928/88441916-8388d900-ce0a-11ea-9b09-495bd4151171.PNG)

**Comment by Pratepresidenten** [comment]
It might have been fixed since I reported it, but the main issue was just when you clicked the "view message" link, nothing happened. I could see the  X holds up a paper etc message, but the link was dead.
