### ISSUE TITLE
Transferring sulphuric acid to certain reagent containers (beaker to shaker, for example) disintegrates them

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#8019]
Title. This leads to horrible shenanigans when bartending with sulphuric acid because of this terrifying oversight.

**Comment by Kaedwuff** [comment]
I don't think that's a bug?  It's sulfuric acid, and it burns through whatever cheap metal the mixer is made of.  When bartending with dangerous substances, try using a glass container, it's safer.  I think even a glass would work.

**Comment by alsoandanswer** [comment]
Yeah, this is intentional.
