### ISSUE TITLE
Ghosts appear on the list of targets to give items to.

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#8030]
Ghost who are following you appear on the list of targets you can give an item to.

This becomes particularly noticeable when you're standing alone with someone and you try and give them an item, and there's 5+ people on the give option list.

**Comment by Kaedwuff** [comment]
It happened when I was playing a wizard who had a scrying orb, I'm not sure if that would cause an issue somehow, since you have the ability to basically aghost.

**Comment by mikomyazaki** [comment]
It shouldn't matter, the Give verb still works the same. Hmmmm.
