### ISSUE TITLE
<vui-input-numeric> struggles with ping

### ISSUE THREAD

**Issue by Talkarcabbage** [Aurorastation/Aurora.3#8040]
The vui-input-numeric template used by the atmospheric computers and whatever else, while improved over the original, still has issues. 

Some of the issues are easily visible in the recording below. Note that:
- I am testing with the server running in a virtual machine to simulate approximately 220ms ping (chosen as it's my approximate aurora server ping)
- When the mouse is hovering on the + or - buttons, it is being spam clicked multiple times per second (at least 4 per second) but the UI does not update reliably.
- When the mouse is briefly hovered onto and back off of the set button, the button is being clicked. I did this for illustration purposes because I have no idea where the sharex setting is to show my clicks.
- The actual value being applied is often not the same as the input field. The input field also sometimes reverts itself to the internally stored value after clicking +/-. 
- This was done on a testing local copy that contains the changes as of the 17th, including Karolis' update to the template.

I don't think the input field/buttons should ever need to be submitting any information to byond until it's ready to actually be applied. If the use of Topic() is less than ideal or a different method is in use, then state pushes should probably only be done via a submission button or enter key and the value should be stored locally. 

https://puu.sh/F0Zxk/91ecf403e5.mp4

**Comment by Sindorman** [comment]
Profile it, I suspect it is not the UI itself but the tank response is taking long time

**Comment by Sindorman** [comment]
Flow-rate has to be update on the machinery which is 2 seconds delay

**Comment by Talkarcabbage** [comment]
The actual tank value is shown on the GUI and afaik only applied when update is pressed; the value is also wrong when submitted sometimes. If that's wrong, then the client state is not being updated properly when the settings are applied. 

Regardless, the UI edit text box should not be bound to anything on the server, especially since it isn't bound to the actual setting unless apply is clicked (or, in theory, the enter key is pressed) anyway. 

There are UI synchronization issues regardless.
