### ISSUE TITLE
Maintenance drones cannot interact with broken APCs in any manner

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#805]
Referring to the broken do to being shot/exploded APCs, not the blue screened. The ones where you have to bash it until the panel falls off to fix it. Maintenance drones cannot attack these APCs to remove the panel and replace them.

**Comment by Bedshaped** [comment]
I'll get this

**Comment by Bedshaped** [comment]
I'm assuming you mean when the APC is broken and looks like this:
https://puu.sh/qNJrY/aeba94da5d.png

Have you tried using a welder? The interaction for me was:
https://puu.sh/qNJjA/d6d28574f3.png

**Comment by NanakoAC** [comment]
I fixed this weeks ago in #632
