### ISSUE TITLE
Changeling Sting doesn't mix

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#8065]
The drink, Changeling Sting, doesn't mix. I added all the needed reagents to the drink, and they stayed separate. I checked the ingredients on github to see if I did it wrong? Nope, all's right.

**Comment by mikomyazaki** [comment]
Worked fine for me.

Are you sure you were using "Lemon Juice" and not "Lemon Lime Juice" ?

**Comment by Doxxmedearly** [comment]
Changeling sting was changed to Gibson punch and tested working. Closing.
