### ISSUE TITLE
Cryoing a Dionae drops nymphs

### ISSUE THREAD

**Issue by Xelnagahuntr** [Aurorastation/Aurora.3#8077]
So I'm pretty sure that each time you detach a nymph and return it to you it just becomes an extra nymph. When you go to cryo, for some reason those extras fall off and just sit on the cryo pod.

**Comment by alsoandanswer** [comment]
![dreamseeker_X4GHSr9FSd](https://user-images.githubusercontent.com/42310821/73018340-6cb5f980-3e5c-11ea-9ec2-145719a2bc3d.png)
yep, it's confirmed
