### ISSUE TITLE
Malf AI's cannot be destroyed - Seemingly invincible

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#8086]
**What should happen**

Damaging the core, whether by shooting it, ioning it or the myriad other ways to deal damage to something should eventually destroy it. 

**What does happen**

You can appear to damage the core, and it will display messages saying it is damaged if you examine it, but the core can never actually die no matter what you do. The only way core destruction happens, is if the AI self destructs. Even without power and in its "worst" state, the AI can recall shuttles, do delta and utilize its other abilities like deploying shielding.

**Have I tried reproducing it**

Yes, at first I thought it might've not had enough damage the first few times, but it is certain things are bugged now. Try to destroy a malf AI through conventional means like ions and laser rifles. You'll end up with an AI that can't really see much due to the damage, but is still functioning.

**Comment by NonQueueingMatt** [comment]
Fixed.
