### ISSUE TITLE
Stamina Drains when running against a wall or a door despite not actually moving.

### ISSUE THREAD

**Issue by BurgerLUA** [Aurorastation/Aurora.3#8095]
Caused by incorrectly placing the stamina drain code in the Move() proc for living or in the Enter() proc for turfs. It needs to be placed on the Entered proc, or wherever footsteps are called.

**Comment by mikomyazaki** [comment]
Fixing this properly will include setting up movement handlers for mobs. (Currently they are only used for exosuits)

**Comment by Doxxmedearly** [comment]
Was fixed by  #11312
