### ISSUE TITLE
Spiderbots need to be refactored into mob/living/silicone

### ISSUE THREAD

**Issue by Bedshaped** [Aurorastation/Aurora.3#810]
They're currently simple_animals which is ludicrous.

**Comment by skull132** [comment]
Is it necessary to do this? Basically: can you reason the higher cost of `life()` that would come with it?

**Comment by Bedshaped** [comment]
Well all the functionality and features of drones could be easily added to spiderbots which is what I'm thinking without needing to write snowflake code I guess. Spiderbots don't have proper UIs or anything

**Comment by LordFowl** [comment]
Nor do they need one. They have no inventory.
