### ISSUE TITLE
Dionae Nymphs Unable to Sample DNA

### ISSUE THREAD

**Issue by runecap** [Aurorastation/Aurora.3#8180]
As the title suggests, nymphs are now unable to use the Sample-DNA verb on anyone. It will give them no targets- doesn't work on players or mobs like monkeys (which worked before).

This is specifically from nymphs that detached from a gestalt.

Game ID found: b5v-cWqP

**Comment by Juani2400** [comment]
Adding to this one, seems nymphs that grow from the plant also can't sample DNA, either.

**Comment by Doxxmedearly** [comment]
This has been fixed. Tested grown plants as well.
