### ISSUE TITLE
Integrated circuits: Light doesn't work on jumpsuit when you're wearing it.

### ISSUE THREAD

**Issue by RobertRoberts2020** [Aurorastation/Aurora.3#8185]
Steps to reproduce:

1) Use the integrated circuit printer to print a wearable jumpsuit, a toggle button and a light.
2) Attach everything to the jumpsuit and wire it properly.
3) If you hold hte jumpsuit on any of oyur hands and press the button, nothing happens, oyu have to actually place the jumpsuit somewhere ( Table, floor, etc) in order for the light to actually show up.
4) You can't wear your cool jumpsuit with a flashlight addon.

**Comment by runecap** [comment]
Not a bug iirc. Lights aren't meant to work when being worn or inside the use.

**Comment by RobertRoberts2020** [comment]
So I print out an integrated circuits jumpsuit, I attach a light, but I can't use the light while wearing the jumpsuit, does that make any sense? what's the logic behind it? It should work as expected, that's the point of attaching a light to a jumpsuit.
