### ISSUE TITLE
Cannot destroy iron doors with an emitter, but they can be deconstructed quite easily

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#819]

**Comment by SierraKomodo** [comment]
The 'deconstruction' method we used wasn't actually deconstructing. It involved bashing it with a fire extinguisher until it broke. As far as I'm aware there isn't a deconstruction method for those doors.

**Comment by Alberyk** [comment]
That is for airlocks, regular doors, made out of materials, can be dismantled with some simple tools, like drills.

**Comment by Alberyk** [comment]
This is fixed already.
