### ISSUE TITLE
Firing guns at point blank displays messed up text

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#8193]
![image](https://user-images.githubusercontent.com/11579997/73704575-4866e200-46d2-11ea-8f86-d8f221ba57de.png)

Likely caused by #8094

**Comment by OneOneThreeEight** [comment]
oh hey im in this image

Question, does this have to do with pronouns? Being in a full body covering suit conceals your gender iirc.

**Comment by mikomyazaki** [comment]
I don't think this is due to that issue. Didn't touch any related lines so far as I can tell.
