### ISSUE TITLE
Atmospheric Code Remnant Phoron Issues

### ISSUE THREAD

**Issue by Talkarcabbage** [Aurorastation/Aurora.3#82]
Specifically happened in research. After a toxins lab [fire? leak? depressurization? I think all of these happened] Phoron remained in the science hallway, enough to cause toxin damage, but would not clear out from the room via the air alarm scrubber nor a portable air scrubber without absolutely draining the pressure to zero. The solution, as the pressure of the entire hallway was not dropping below 3.6kpa when exposed to a space tile... was admin magic.

**Comment by skull132** [comment]
Fixed in #353 .
