### ISSUE TITLE
Aut'akh Adrenaline Organ Produces Unlimited Sprint

### ISSUE THREAD

**Issue by Snakebittenn** [Aurorastation/Aurora.3#8232]
Title. I have no idea why this is, but they can run forever using it with little cost.

**Comment by furrycactus** [comment]
This affects regular Unathi too, not just Aut'akh.

**Comment by Alberyk** [comment]
How can this affect regular unathi when they don't have the organ

**Comment by furrycactus** [comment]
I'm not really sure, but I've been experiencing occasional rounds where I have a nearly unlimited sprint while playing my regular Unathi, too. It's not a consistent every-round thing, though.
