### ISSUE TITLE
Diona Hyperzine Abuse

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#8313]
Hyperzine works for Diona, but is not processed in their bloodstream, so a single unit lasts forever.
Radium makes the diona have endless energy to sprint with, but is at least temporary.
You can abuse that pretty hard as medical, research or antag.
Yonni told me to open a ticket about it, so here we are.

Thank you in advance :)

**Comment by mikomyazaki** [comment]
Could not reproduce.

Hyperzine did not affect my Diona, just sat in its bloodstream never getting used up.

Tested by putting log messages in `on_mob_life()` and hyperzine's `affect_blood()`.

**Comment by NonQueueingMatt** [comment]
Seems to not be correct.
