### ISSUE TITLE
If there are two people with the same name and one is flushed down cryo, both persons are deleted from records and manifest

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#833]
Typically happens when someone joins the wrong job by accident, cryos, joins under the correct job, and an admin forgets to flush the body before the rejoin occurs.

**Comment by SoundScopes** [comment]
This requires a little rewite of the records system as the main identifiers in records are the names.
If someone would link it to the unique key that mobs get given for CCIA stuff (Is that done yet?), this wouldn't happen.

**Comment by Arrow768** [comment]
Characters already have a unique char ix in the database.

But as far as I know that ip is not used anywhere ingame

**Comment by skull132** [comment]
It actually is.

The current character's ID is accessible through the preference's datum
that's attached to each client. `prefs.current_character` I do believe,
provided that `src` is a Client object.

**Comment by SoundScopes** [comment]
If it's attached to the client then it will need to be moved or copied over somewhere else in the mob to be able to track it and match the record entry and would always get the right record for the right mob

**Comment by FirinMaLazors** [comment]
See the mentioned issue for my comments.
