### ISSUE TITLE
cyborg storage does not flush ghosted borgs

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#8344]
Borgo used the command borg storage unit (By the captains office), ghosted and nothing. They're ghosted while their former body just sits in the storage box, taking up space, but supposedly not a jobslot.

Default borg module
Cannot be ejected
Still shows up on the robotics control console as unresponsive

Round ID: b5R-dFHg

**Comment by Estutes** [comment]
I went into storage as a cyrbog in mechbay and closed the game. When I came back I was still in the game so I decided to get out of there. Hardly couldn't make it out of the cyborg storage and had to try different verbs. No HUD showed up even when getting out or restarting Byond and SS13.

**Comment by Pratepresidenten** [comment]
An addition: Despite the announcer stating the borgo has entered robotic storage, it still remains on the manifest in addition to the OP.
It applies to any storage pod, any module.
