### ISSUE TITLE
Xenarcheologists can no longer access their voidsuits

### ISSUE THREAD

**Issue by ghkiha** [Aurorastation/Aurora.3#8354]
Can't access voidsuit storage in the Xenoarcheology EVA access room. I assume it has something to do with the reason we can't lock the R&D console anymore either.

![](https://i.gyazo.com/fa59784eea56830ca2955af50ef897f8.png)

**Comment by furrycactus** [comment]
Fixed, it was because of a hiccup in attempting to restrict science officers from these things in #8209
