### ISSUE TITLE
Wrestleing manual item usage prevents you from punching or disarming regularly.

### ISSUE THREAD

**Issue by thetinybutler** [Aurorastation/Aurora.3#8364]
Hello! Im new to the whole traitor playstyle but the wrestling manual caught my eye, it is a shame that for some reason you cannot punch or disarm with the wrestling manual moves learnt as all non help intents force you to grab rather then doing the regular action like disarm and harm(punching). If this was the intent of the item feel free to close this report. Thanks.

**Comment by Alberyk** [comment]
That is on purpose. You can pretty much fight with grabs only for now, you can also check the moves by using the verbs the game gives you.
