### ISSUE TITLE
Click spamming runes

### ISSUE THREAD

**Issue by printer16** [Aurorastation/Aurora.3#837]
Clicking a rune more than once can cause it to be used more than once. This is can easily be seen when there are more than 1 nar'sies spawned. It can also be abused by using the sacrifice rune on a dead monkey/person/otherthing. If you click fast enough, it will gib the monkey/person/otherthing more than once, and will count as you sacrificing more than one monkey/person/otherthing

**Comment by skull132** [comment]
Time for click protection on runes. Though I swore I stopped the Nar'sie shenanigans in a previous patch <.<

**Comment by Geevies** [comment]
Think this got given a cooldown.
