### ISSUE TITLE
Holodeck door tiles are different

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#8371]
The holodeck door tiles appear to be different shades of grey. The doors further north are light grey where as the bottom left door is a dark grey.

![Screenshot 2020-02-28 23 09 51](https://user-images.githubusercontent.com/56227386/75620649-9afec580-5bce-11ea-891e-334784e09409.png)

**Comment by Geevies** [comment]
This was probably fixed by the station facelift. Re-open if not.
