### ISSUE TITLE
Job-Specific Bag Resets [Departmental Officer Testmerge]

### ISSUE THREAD

**Issue by MedLit** [Aurorastation/Aurora.3#8380]
My satchel/bag resets to the security one when I painstakingly saved and double-checked across more than a couple of rounds in my setup to make sure it would go through. Not a big deal, there are alternative ways to get the grey bag, but it's forcing me to take the security bag when it's set to do the opposite. Is this a bug, is it particular to department officers?

**Comment by Doxxmedearly** [comment]
Dep sec trial is over and not being used
