### ISSUE TITLE
Cult talisman not working

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#8383]
None of them. I managed to get one flash talisman that worked, but did not blind anyone, then I was unable to click the talismans for the entire round. Tried with flash, EMP, stund and teleport talismans.

**Comment by Geevies** [comment]
In testing, I've found that Talismans do work. You should use them in-hand by clicking them while they're in your active hand, or by pressing Z. Closing this, re-open and try to attach a screenshot if it occurs again.
