### ISSUE TITLE
APCS that are fully drained by EMPs state 'fully charged' and act as if on full charge, despite saying 0% charge

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#839]
If you drain an APC's cell by EMPing it repeatedly to the point it shows a charge of 0%, the APC will also say 'Fully Charged' and act like it has a full charge, providing power to everything without draining. Removing and replacing the power cell fixes this.

**Comment by Geevies** [comment]
Fixed.
