### ISSUE TITLE
Could hear whispers from four tiles away when Azza was speaking siik'mas

### ISSUE THREAD

**Issue by engiValk** [Aurorastation/Aurora.3#840]
https://gyazo.com/50f2d86e4aa21961c8c517e8ed93f2ce

I was sat about 3-4 tiles away from Azza but was completely able to hear her whispering. It also didn't have the "mrowls" text in the action.

**Comment by Spoopy11** [comment]
There's the possibility that I used an exclamation mark, which I think makes it actually a little louder and hearable from about four tiles.

**Comment by engiValk** [comment]
Well it still missed the mrowls, so that still needs looking into

**Comment by Geevies** [comment]
Fixed.
