### ISSUE TITLE
More food refactor invisible sprites

### ISSUE THREAD

**Issue by Doxxmedearly** [Aurorastation/Aurora.3#8405]
Caused by #8285

Noticed with Grenadine
grenadinebottle_empty wasn't added in the PR, so it turns invisible when empty. Discovered 3/8/20

This is going to happen with every bottle in the /obj/item/reagent_containers/food/drinks/bottle/ path if there isn't an iconstate_empty sprite since it's in the parent path's update_icon() that if the bottle has no reagents, the iconstate becomes "iconstate_empty." If there isn't one, it's invisible.

For example I already don't see any "_empty" states for space up, cola, or mountain wind bottles added in the PR so those will probably go invisible, too. Same with like every juice carton, since those are in that path.

Would fix it but I assume the PR author would like to add the missing empty sprites instead, and I'm not a spriter.

**Comment by Doxxmedearly** [comment]
@alsoandanswer

**Comment by alsoandanswer** [comment]
Is it possible to make it so that those without a closed state don't use the proc?

**Comment by Doxxmedearly** [comment]
Yes, a few that I can think of. You'd have to use vars, like setting a var/empty_icon_state to the icon name, or using special flags to make it not use it (Like var/flags = NO_UPDATE) and setting update_icon's check to check for both if it's empty AND has a special flag.

**Comment by Doxxmedearly** [comment]
Actually I got an idea, hold on

**Comment by Doxxmedearly** [comment]
I think I got a solution that'll organize bottles a little bit and make it easy enough to add sprites for empty states in the future
