### ISSUE TITLE
Duplicating items from pets eating them?

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#8414]
Left Bones alone for ages with a piece of cake and a sandwich, came back to the room with those items still on the table and fifteen empty plates also.

**Comment by Doxxmedearly** [comment]
Probably to do with my animal eating rework. I'll take a look.

**Comment by Doxxmedearly** [comment]
Yeah there are a few issues with both my rework and how simple animals handle trash/food since the food refactor. I will hopefully have a fix sometime in a day or two.
