### ISSUE TITLE
Cryo mix healing all organ damage.

### ISSUE THREAD

**Issue by SophieMint** [Aurorastation/Aurora.3#8468]
Exactly that. I'm fairly sure this was a bug that was supposed to have been fixed a while ago, but people seem split on whether or not it's intentional. Rn standard cryo mix without anything added fixes all organ damage types, including fully popped lungs. So the current 'meta' is anything other than arterial and extreme blood loss can be fixed by just using a tube. This includes mechanical organs.

**Comment by NonQueueingMatt** [comment]
Time to nerf.

**Comment by Geevies** [comment]
Fixed.
