### ISSUE TITLE
Disarming SSDs lacks attack message

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#8474]
[Aggressor] [Victim], but they do not respond... Maybe they have S.S.D?

The whole intent is lost between aggressor and victim. Only seems to be an issue with disarm.

**Comment by mikomyazaki** [comment]
Appears to be working properly.

![disarm](https://user-images.githubusercontent.com/47489928/89091957-93be2c80-d3a5-11ea-81bb-551a8174f526.PNG)
