### ISSUE TITLE
Medical/Rescue Module not able to recharge Medicine Synthesizer

### ISSUE THREAD

**Issue by StationCrab** [Aurorastation/Aurora.3#8475]
The Medical and Rescue Cyborg Module are unable to recharge their medical synthesizer fluid at the cyborg charging station.

https://i.gyazo.com/bb99f284deff4f879b758062fb81feba.gif

**Comment by Chada-1** [comment]
I've found the Cyborg code that handles this stuff and I plan to try to fix it soon:tm:
