### ISSUE TITLE
Medical/rescue borgs dont use medicine synthesizer to replenish hypo

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#8476]
Im prrrrrrrrretty sure this was a thing at some point, although useless as up until the recent-ish tweak to borgs where having 0 on your internal medicine synthesizer did shit.

**Comment by StationCrab** [comment]
I opened a ticket on this earlier. The medical synthesizer also is what allows them to use their trauma kits and such now. So not being able to replenish it really cripples them.

**Comment by Geevies** [comment]
they use power to recharge, so this is fine
