### ISSUE TITLE
Hearing aids incompatible with radios

### ISSUE THREAD

**Issue by Beewax623** [Aurorastation/Aurora.3#8490]
When playing a deaf character who is wearing a hearing aid, you seem to be able to hear everything besides radios, even the wall-mounted station intercoms. I tried using both a station bounced radio and the intercoms, yet would only receive the message "You feel your headset vibrate but can hear nothing from it!" despite not even wearing a headset.

Attached below is a screenshot of me wearing only a hearing aid, being able to hear people (in this case me, yet I had a conversation with multiple people beforehand,) yet only receiving this error dialogue from both my station bounced radio and the intercom.
![screenshot](https://user-images.githubusercontent.com/62533383/77283570-ace9fa80-6c9a-11ea-8aa6-4b7535995e34.PNG)

**Comment by Geevies** [comment]
The hearing aid amplifies ambient noise, so it not working for headsets is fine IMO. It not working for intercomms and handheld radios is a bug however.
