### ISSUE TITLE
Slipping bigger shoes over your sandals as wizard nullifies your powers as if you don't have the entire set.

### ISSUE THREAD

**Issue by Arzion5** [Aurorastation/Aurora.3#851]

**Comment by MarinaGryphon** [comment]
I believe this is intended and/or unavoidable. This will either be marked as "not a bug" or "won't fix", depending on which that is.
To be fair, if you're talking about magboots, it probably *could* be fixed, but for marginal gain. You could always just say that it interferes with the sandals' magical properties.

**Comment by Geevies** [comment]
Shoes don't matter for wizard garb anymore, it seems.
