### ISSUE TITLE
Multiple Ling Bugs

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#8550]
- If you succ someone, they still have a pulse despite being dead.
- The medical HUD shows a low pulse during revive.
- Despite reading no pulse in the scanners, you can still right click and read a pulse.
- If you are in lesser form, getting shot with a projectile could stop you from entering the vents.
- If you are in a locker and revive, the verbs do not update and you have to reconnect.
- Buying something while in regeneration fake death will suddenly pop up all your abilities again
- Transformation sting does not work, at all, husked or not, on anything.

**Comment by Doxxmedearly** [comment]
Will attempt to address

**Comment by Pratepresidenten** [comment]
Had an injured borer earlier that couldnt ventcrawl. They could after they got a rejuv. Damage seems to be the issue?
