### ISSUE TITLE
Emergency Response Troopers are not Loyalty Implanted

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#856]
Simply put, ERT do not spawn with loyalty implants.

It has been a while since I last went ERT but I did a search and there's no mention of Loyalty Implants for ERT on Git so I assume this hasn't been fixed yet.

I think we can assume those tasked with saving stations from their unpleasant messes they make would be implanted as much as a Head of Security would be.

**Comment by printer16** [comment]
Intentional. They would not be loyalty implanted and are not. Confirmed by CCIA to be cannon afaik.

**Comment by skull132** [comment]
Were they even LI-d in old code? From what I remember, they weren't? Or
I've never found it to be relevant. Hrm.

**Comment by Fire-and-Glory** [comment]
I can't say I remember ERT being loyalty implanted on old code.

I _guess_ hired mercs wouldn't submit to implants that enforce loyalty, but it doesn't _really_ seem like something NT'd risk, I mean, you've got a bunch of guns for hire stomping all over your stations looking and dealing with all your dirty goodies, and they can do whatever the fuck they want with it, seems off to me anyways.

**Comment by skull132** [comment]
Not necessarily.

Implants are relatively sophisticated, and do come with drawbacks.
Implanting en-masse sounds like a costly idea which can have unintended
consequences.

**Comment by SoundScopes** [comment]
They have never been LI'd.

**Comment by skull132** [comment]
Not a bug, closed.
