### ISSUE TITLE
Apparitions don't die when Summoner steps off rune

### ISSUE THREAD

**Issue by runecap** [Aurorastation/Aurora.3#8563]
As the title says. Apparitions don't die when the Summoner steps off the rune- which makes the rune OP as hell by virtue of a cultist not becoming stationary for it. The cultist DOES still take damage for having the apparitions around, however.

Game ID: b6q-dcwa

**Comment by Geevies** [comment]
This is not a bug, it is intentional. Damage can be increased for having a summoned apparition, though.
