### ISSUE TITLE
Breaking handcuffs makes you shout into your radio

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#857]
Cuff breaking, be it frenzied vamps, unathi dudes, or whatever else, causes you to go GWAAAAAAAARRRHHH!!!! on the radio, which, is dumb.

Doing it in person, fine sure, but I think people who are straining really hard against metal bindings are not turning on their radio so that everyone can know how beefy they are.

**Comment by Alberyk** [comment]
It is a feature, however.

**Comment by SoundScopes** [comment]
Silly feature since you know breaking out of cuffs requires both hands and to press the transmit feature of the radio also (should) require a hand to do.
4 out of 5 times they do shout over the radio, this is something that used to happen on old code.

Could you explain why it's a feature?

**Comment by Alberyk** [comment]
For the same reason people are able to speak over the radio when cuffed or without hands, and  from what I can see it is on the purpose that yelling over the radio happens when you break cuffs, or thing as hulks, however that don't means it can't be changed.

**Comment by Fire-and-Glory** [comment]
Feature or not, I for one think it is stupid, hence, it is an Issue.
