### ISSUE TITLE
At random points, AI's cannot examine mobs/objects

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#858]
At random points throughout a random, an AI cannot examine things via right click > examine; An error similar to this will crop up:

`Sorry, the following is not valid: Examine`

`usage: Examine`

`Sorry, the following is not valid: Thaeo-Runerinth.0x3000033`

`usage: Examine is not accessible`

`usage: Examine mob|obj|turf`

Using track with camera on someone seems to reset this and allow the examine verb to work again for a short while.

**Comment by skull132** [comment]
Some debug info: it somehow occupies the command bar with a the command and an object's ref. Basically, the data needed to call the command from the command bar on its own. Clicking examine again appears to take that and roll with it.

**Comment by MarinaGryphon** [comment]
This is due to verb visibility. I'm pretty sure it's not fixable; the issue is when something you try to examine goes offscreen, iirc.
