### ISSUE TITLE
Kinetic Accelerators are bugged (Again)

### ISSUE THREAD

**Issue by DronzTheWolf** [Aurorastation/Aurora.3#8600]
Apparently the new update broke KAs again so that the kinetic force becomes an invisible landmine for you to step on later. This can be extremely deadly with the better accelerators, essentially creating a landmine field that can't be seen.

**Comment by Sindorman** [comment]
I fixed it on Apr 7 in #8618. @DronzTheWolf Please reply here if it is still an issue
