### ISSUE TITLE
Unathi can't get Drunk

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#8606]
When Unathi drink butanol they don't feel any intoxication effects from it, but they'll still end up just vomiting when they reach what would normally be the threshold for drinking too much.

**Comment by Sharkatk** [comment]
I still seem to have issues with this as well. It can sometimes take forcing past 100 units of butanol and vomiting before it even begins to say intoxication effects and it is short lived.

**Comment by mikomyazaki** [comment]
Unathi specifically have a higher metabolism rate for butanol. This seems to be intended?

Try a different drink for your lizards.

**Comment by KasparoVy** [comment]
Lmao, goddamn. Life's complicated enough, why it gotta be hard to get crunk too

**Comment by mikomyazaki** [comment]
> Lmao, goddamn. Life's complicated enough, why it gotta be hard to get crunk too

Actually it seems they're supposed to get more drunk. I'll fix it... when I figure it out.

**Comment by mikomyazaki** [comment]
Think this is just an effect of the unathi's `ethanol_resistance = 0.4` being really good.

**Comment by KasparoVy** [comment]
@mikomyazaki Yeah these dudes have durasteel livers, damn son

**Comment by NonQueueingMatt** [comment]
should be fixed now
