### ISSUE TITLE
KAs are super weak

### ISSUE THREAD

**Issue by Shenaanigans** [Aurorastation/Aurora.3#8624]
Some recent tweak to KA code (I think the fix for invisible lingering force) made KAs much weaker than they were. The same area of effect is covered, but for some reason only a small line extending directly out of where you're shooting will actually have broken rocks. Even if you shoot to cover the same area multiple times. Including links to pics of the KA I was using and the tiny, 3 tile long line it cleared out when I used it.
https://media.discordapp.net/attachments/635914105668108316/697267565734658068/Capture.PNG
https://media.discordapp.net/attachments/635914105668108316/697267652892033034/unknown.png

**Comment by SonicGotNuked** [comment]
Same issue.
https://i.gyazo.com/3fa1e5bcc43bbe9ce23b20ead8635dfe.gif

**Comment by albert7076** [comment]
Yeah I have the same issue here
