### ISSUE TITLE
Changeling's using rejuvinate magically become un-cuffed when they wake back up

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#865]
When there's a changeling body that's cuffed, and wakes up from using the rejuvinate verb, the cuffs suddenly detach and fall to the floor without any form of warning or emote. The ling may also automatically unbuckle from whatever it's buckled to, but that's currently unconfirmed.

**Comment by Alberyk** [comment]
Not really a bug, seems to be more like a feature.
