### ISSUE TITLE
Firesuits are useless for their intended purpose, yet make great space suits

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#867]
Take this quote from in-game for example, after I watched this guy actually /test/ this. He lit himself on fire while wearing the suit and received a lot of burns. Going into space with the suit and internals, however, and he was completely unharmed.

> [Common] Joseph Aultman (follow) says, "Okay crew, your science team here. Firesuits are 100% space proof in low pressuries, and in high pressures. Though, they are NOT effective against high temperatures."
> 
> [Common] Joseph Aultman (follow) says, "So do not use them to fight fires.t"
> 
> [Common] Joseph Aultman (follow) says, "Use them as EVA suits"

**Comment by NanakoAC** [comment]
@SierraKomodo I'm not entirely sure how to make them not useable as EVA suits, i don't understand the physics of vacuum exposure enough for that. but making them properly fire resistant shouldnt be too hard.

There has been some discussion in the dev team of simply changing their sprites to reflect how they work - actually making them EVA suits.
