### ISSUE TITLE
Paramedic helmet fits in jackets.

### ISSUE THREAD

**Issue by Haveatya** [Aurorastation/Aurora.3#8678]
The helmet paramedics start with can fit inside coats and jackets, to my knowledge no other helmet can and it is weird that it can from a realistic perspective.

**Comment by Doxxmedearly** [comment]
This is because it follows the path of hardhats, not helmets. Lots of weird things can fit in pockets, though maybe I will look at increasing the size of these all. For now, not _technically_ a bug. But a helpful report nontheless
