### ISSUE TITLE
Service Borg Skin "Unbranded-MAD" Only Renders Eyes

### ISSUE THREAD

**Issue by TheTailson** [Aurorastation/Aurora.3#8685]
Quite a small one! There's something wrong with the Unbranded-MAD service borg sprite. You can only see the eyes - no sprite. They bob around quite happily like the eyes should. Like a happy little spectre.

https://imgur.com/AUcoTAv

**Comment by Chada-1** [comment]
I know what hte problem is and I'll rush a quickfix out real quick 👀
