### ISSUE TITLE
Foods that use carp meat/carp fillet are broken

### ISSUE THREAD

**Issue by ToasterStrudes** [Aurorastation/Aurora.3#8704]
As said in title, currently i've tested:
-Fillet -o- Carp Sandwich
-Cuban Carp (Only the deep fryer version works)
-Ouerean Carp Log
-Fish & Chips
-Fish Fingers
-Fish taco

None of them work besides the deep fryer version of the Cuban Carp

**Comment by Alberyk** [comment]
Tested this stuff, and it works just fine.
