### ISSUE TITLE
Microphone circuit not doing anything.

### ISSUE THREAD

**Issue by Yonnimer** [Aurorastation/Aurora.3#8708]
The microphone circuit from circuit printers is no longer doing anything, at all. Nothing is outputted or written when someone speaks.

**Comment by niennab** [comment]
The universal recording isn't receiving any input as well. Perhaps related?

**Comment by runecap** [comment]
To add, the microphone circuit seems to work inside circuit jumpsuits- but not inside implant assemblies.

**Comment by runecap** [comment]
Looks like this was shadow-fixed, should close the issue.

**Comment by Alberyk** [comment]
This was caused by a byond version issue.
