### ISSUE TITLE
Runes, blood, oil, etc are hidden under pipes and wires in maintenance tunnels

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#871]
http://i.imgur.com/KKiT5IC.png

Atmos pipes, disposal pipes, and wires are all laid over blood, runes, etc making it difficult to see them in an already dark area. There's a blood spatter on the same tile as the drone that's almost completely covered by the disposal pipe.

**Comment by SierraKomodo** [comment]
Same thing happens with vents and scrubbers anywhere on the station.

**Comment by skull132** [comment]
I'm inclined to believe this is fine, actually. Pipes in maintenance are
more pronounced, and probably elevated, so blood and so forth would end up
the floor. At its heart, though, it's a simply layering issue. Depending on
the desired result, it might be annoying to fix, though!

**Comment by Geevies** [comment]
Fixed.
