### ISSUE TITLE
Blobs keep spawning in the same area.

### ISSUE THREAD

**Issue by SimonTheMiner** [Aurorastation/Aurora.3#8714]
Having played a far bit of engineering, and watching a lot of rounds, I've noticed the blob almost always spawns in the same part of sublevel maintenance in engineering, the core always in a place, and the hallway for trying to fight the blob stupidly tight since the walls are reinforced. Not sure if this is a bug or I'm just seeing it in the same spot, but I think blob spawn locations are broken.

**Comment by WickedCybs** [comment]
Appears to affect vines as well, they are always spawning in the hallway outside of EVA at the moment.

**Comment by WickedCybs** [comment]
Noting that vines appear fixed (since about a month now, forgot to post this earlier, my mistake), so once that PR is merged this should be good to close.
