### ISSUE TITLE
Black Dress Flats remain bloody after cleanig them

### ISSUE THREAD

**Issue by DeadLantern** [Aurorastation/Aurora.3#8720]
When you get black dress flats, and get them bloody, cleaning them via a sink or soap does not change the sprite, though they do become clean in the inventory.

**Comment by sheeplets** [comment]
Tested with space cleaner and even the laundry machine as well, nothing works.

**Comment by SentientBowtie** [comment]
This also happens with purple hi-tops and oil; they're cleaned in the inventory but not on the sprite. I assume it's a general shoe/stain issue?

**Comment by Geevies** [comment]
Think this was fixed.
