### ISSUE TITLE
Voidsuits and hardsuits devouring footwear, for a time

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#8721]
Essentially, the action of magboots or hardsuit boots going over your shoes will sometimes make the shoes vanish once the voidsuit is off or the hardsuit boots are retracted. They're not gone forever, they simply appear back in the shoes slot after a random period of time, tends to be short. For a while though, you will be wearing nothing in that slot, and this is reflected in-game mechanically.

Noticed this after multiple rounds of a few people complaining about it, saw it in action too and had it happen to myself.

**Comment by Alberyk** [comment]
Likely caused by #8709
