### ISSUE TITLE
Unset Wristbound Computers can become set to any department, regardless of access.

### ISSUE THREAD

**Issue by jmlop0** [Aurorastation/Aurora.3#8743]
If you get a wrist-bound computer that isn't set to a department and set it to Company, you can then set it to any department, command, ect, and thus get the programs associated with them.

Byond ID is jmlop0

Moderator that was notified of the bug: ParadoxSpace

**Comment by Menown** [comment]
That's true regardless of it being a wristbound computer. The only difference is you can't access any of the programs itself.

**Comment by runecap** [comment]
I don't think this is a bug. You've always been able to do this, no matter what device- but it's pointless if you don't have access because you can't use the device nor reset it.

**Comment by Geevies** [comment]
Not a bug, this is just how modular computers work. The only difference between a pre-set wristbound and a generic one is that the former is pre-set and has a fancy paint job.
