### ISSUE TITLE
List of Available Spells incorrect formatting

### ISSUE THREAD

**Issue by Baa14453** [Aurorastation/Aurora.3#8765]
Inside the Wizard's hideout is a piece of paper called List of Available Spells (READ)
The text appears to be incorrectly formatted:

![image](https://user-images.githubusercontent.com/9057997/80320180-ca1b6700-880c-11ea-8a4d-a10281fa5ba6.png)

**Comment by Doxxmedearly** [comment]
Wizard is no longer an available gamemode. Closing.
