### ISSUE TITLE
Record programs unable to be opened

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#8791]
It seems every type of record program is bugged at the moment, saying "Access denied" if one tries to open them, even if you have the proper access. 

FT's can't open sec or medical records. Medical staff can't open medical records. RD's and HoP's can't open employment records. This is what I have observed so far, it might be the case for other roles as well.

**Comment by SenpaiShadow** [comment]
Can confirm, neither AIs nor BST can access records either.

**Comment by Karolis2011** [comment]
This issue was introduced in #8757 and latest commit adreses it. It was test merged.

**Comment by skull132** [comment]
Closed as resolved.
