### ISSUE TITLE
pAI unable to close program manager

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#8794]
pAI's are unable to close their program/file manager. I hit the X on the top right, go to open it again and it just... brings it back up.

https://gyazo.com/fad8fb0f9bd1d0910dfe5cd76ab88593

There is no option to exit program, thus getting into the other programs impossible.

**Comment by Karolis2011** [comment]
Part of test merge #8757. 
Addresed as of https://github.com/Aurorastation/Aurora.3/pull/8757/commits/044a5b2bc80b2a858d5856ca803303b976e7b24d
