### ISSUE TITLE
telecomm turrets try to kill you when they're deactivated

### ISSUE THREAD

**Issue by SonicGotNuked** [Aurorastation/Aurora.3#8810]
I was a scientist with tcomm access. Everything green, turned off, walking into a wall of death. Tcomms can't be accessed :(

**Comment by SonicGotNuked** [comment]
The turret controller doesn't have the individual turrets on them. I think the controller is disconnected from the turrets.

**Comment by XanderDox** [comment]
Went in today while the turrets were disabled and it was fine?

**Comment by SonicGotNuked** [comment]
It could be reading a job, I'm unsure. But people who get access and turn them off get shot. The turrets check access 1 and 19.
