### ISSUE TITLE
Fringe Weaver recipe prevents hooch from being made

### ISSUE THREAD

**Issue by Ultrazundy** [Aurorastation/Aurora.3#8812]
The Fringe Weaver recipe - Mix 2 parts ethanol, 1 part sugar prevents you from making Hooch which is - Mix 2 parts ethanol, 1 part welding fuel, 1 part sugar. Just leaves you with Fringe Weaver and welding fuel.  Also, Fringe Weaver has no flavour, just generic. Please alter the recipes (since as it stands there's literally no point in Hooch since Fringe Weaver is easier to make with the same strength and no downside compared to Hooch) and add a flavour. Thanks.

**Comment by Alberyk** [comment]
Hooch recipe is one part sugar, one part moonshine and one part fuel. The wiki is probably wrong.
