### ISSUE TITLE
Fuel tanks are resistant to wrenches

### ISSUE THREAD

**Issue by qwertypunch** [Aurorastation/Aurora.3#8824]
When attempting to do _crimes_ during a recent round (b63-doCn), I noticed that I was unable to open any of the fuel tanks below maintenance by using a normal wrench on it. I spoke with a moderator (SampleTex), but we were unable to get the fuel open. I used every single tool in the suspicious toolbox, but nothing worked. I have noticed this one other time, but assumed I was doing something incorrectly. I'm not sure why this has only happened to me (that I know of), so I don't know what specific factors caused this to occur.

**Comment by Geevies** [comment]
Were you on harm intent while using the wrench?

**Comment by qwertypunch** [comment]
I was not. I thought harm would just bash it. It appears I've been foiled by the most basic of all settings.

**Comment by Geevies** [comment]
Alrighty, give it a shot next time. If it doesn't work, feel free to re-open this and idk scream at me or something
