### ISSUE TITLE
The infamous "last transfer vote happened at 2200 hours in round duration" bug

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#883]
https://i.imgur.com/RwUKioY.png

Fairly self explanatory, apparently there's another 2 in place of where a zero should be. Somewhat disorienting and annoying and fairly minor. Still a bug.

**Comment by tedwood3** [comment]
![image](https://user-images.githubusercontent.com/2719189/38183852-e07336f6-3686-11e8-9573-1b36b86f411a.png)
This bug is still around it seems
