### ISSUE TITLE
Removing the airlock board from the Vault door permanently changes the sprite

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#886]
Steps to reproduce:
- Remove the airlock board from the vault (Following standard deconstruction steps on the wiki)
- The sprite will change from the Vault door to a normal secure airlock sprite
- Re-insert the airlock board and screwdriver to finish the door
- Sprite will remain as a secure airlock instead of a Vault door

This is primarily an aesthetic thing, and it seems it's impossible to make an airlock use the Vault door sprite. However, there is one mechanical difference between the Vault door and the secure airlock door - the drone maintenance hatch. The vault door does not have a usable hatch, while the secure airlock door you create following the above steps does.

Before/after screenshots: http://imgur.com/a/7tHFN

**Comment by AgentWhatever** [comment]
Sprites are missing, thus the code isn't here to create the vault door assembly
