### ISSUE TITLE
The deep fryer's sound effects loop infinitely

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#8860]
The only way to make the sizzling stop is to have an admin delete the deep fryer. Here's a small sample of the constant, never-ending hell I've had to endure ever since this was broken.

https://vocaroo.com/9MWRn70kYAa

**Comment by Meltharas** [comment]
I can attest that this is still an issue. It is so aggravating to work in or even near the kitchen like in the garden when all you can hear is the constant sizzling, even when it is turned off. The only fix has been for an admin to completely delete the fryer and replace it, which only stops it until it is used again.

**Comment by NonQueueingMatt** [comment]
fixed
