### ISSUE TITLE
Remote Signaler Devices Can't Be Detached From Wires

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#8867]
Title, basically. When signalers are placed on wires inside machines or airlocks, they can't be detached, no matter how much you mash that "Detach Signaler" button.

**Comment by aleksix** [comment]
Slight correction: They can't be detached with an empty hand. They can be detached when clicking the "Detach Signaler" button while having something in your hand. There's a problem with the conditionals.
