### ISSUE TITLE
Console Access bug

### ISSUE THREAD

**Issue by VeteranGary** [Aurorastation/Aurora.3#8926]
Game ID: b7f-cmlI
Issue Reported to: ShesTrying
Bug: Not game breaking, but definitely provides an unfair advantage when a department is understaffed. The R&D Console in the Research Lab can be deconstructed and re-assembled, causing it to briefly reset and connect all nearby machines, not the bug necessarily, but an effect of building the console just does. If you do this and open up the interface and quickly click a tab you are unauthorized to access, like settings or the destructive analyzer, it will let you in even with incorrect access. Once I found this bug I asked an admin for their judgement, and I reported it here.

**Comment by Karolis2011** [comment]
Did it allow you do to any changes while accessing forbidden pages?
