### ISSUE TITLE
K'ois mycosis does not show up on body scanners, at a glance.

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#8955]
I have seen this happen a few times and observed. K'ois mycosis does not display on body scanners. So someone showing the common signs can be missed if the medical department is not knowledgeable on how it works, and mycosis is not really a frequent thing anyway.

The mycosis will display on a printed scan, though. Not sure if this is intentional  to add an extra step.

**Comment by VisVirific** [comment]
K'ois Mycosis also show in Body Scanners thanks to [#10499](https://github.com/Aurorastation/Aurora.3/pull/10499)
![](https://i.imgur.com/giYoHW2.png)
