### ISSUE TITLE
Ventcrawl Bug #2

### ISSUE THREAD

**Issue by LordFowl** [Aurorastation/Aurora.3#898]
If, while ventcrawling, you come upon an object such as an omni gas mixer, you are immediately ejected out of the system. Strangely enough, your sight vars are not returned to you, so you are doomed to an eternity of blindness. Either make it so you die if you reach an omni gas mixer (Bad idea), or just pass through them (Better idea).

**Comment by Bedshaped** [comment]
Note to self: IIRC LF was a mouse at the time. Add sight defaults in Life().
