### ISSUE TITLE
Devouring Bug #1

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#900]
If  you devour something then it speaks it out loud as well as giving you a message.

Like so.

![untitled](https://cloud.githubusercontent.com/assets/19973802/18414107/61aca480-7812-11e6-8a43-b762ef016cb5.png)

**Comment by Alberyk** [comment]
I did it on purpose, just to show that the plaing tyrant would take one hour to fully devour.
