### ISSUE TITLE
Aliens can pilot exosuits

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#901]
As it says, Aliens can pilot exosuits while not being able to pick up and fire a gun, probably other things too, mayhaps make it so that the same flag that stops creatures from firing guns stops them from piloting suits as well.

**Comment by NanakoAC** [comment]
what aliens, do you mean the xenomorphs?

i'm not sure if this is a bug

**Comment by Alberyk** [comment]
Xenomorphs and monkeys can pilot exosuits, even if they are unable to use guns and more.
I think this can be easily fixed, since the has_fine_manipulation exists.

**Comment by Fire-and-Glory** [comment]
It's not a bug, it's an oversight.

And as Alberyk said, yez, Xenomorphs.
