### ISSUE TITLE
Door hacking tool no longer functions.

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#9024]
Caused by the PR that overhauled the airlock stuff.

**Comment by Geevies** [comment]
An attempt at a fix was made in https://github.com/Aurorastation/Aurora.3/pull/9010 I believe? @NonQueueingMatt

**Comment by OneOneThreeEight** [comment]
Specifying, my experience was with the adv. door hacker tool the ninja gets in their hardsuit.

**Comment by NonQueueingMatt** [comment]
should be fixed, reopen if not
