### ISSUE TITLE
Neuter sex set pose displays she instead

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#9027]
What the description says. When I set pose as neuter I get "She..." put before it. Not a big one, but a little off.

**Comment by mikomyazaki** [comment]
Worked properly for me. What species were you?

![neuter](https://user-images.githubusercontent.com/47489928/89091817-805e9180-d3a4-11ea-875f-8d6bee034f8c.PNG)

**Comment by Doxxmedearly** [comment]
Should no longer be an issue with the pronoun addition, and cannot replicate.
