### ISSUE TITLE
Rapid Fabrication Device - P Only works once

### ISSUE THREAD

**Issue by Brayyce** [Aurorastation/Aurora.3#9045]
The RFD-P currently only works once per device as far as I've tested.

Tested on: b7v-dLhv
It was first noticed on a different round. To duplicate just pick up the RDF-P summon a pipe, and then attempt to use it again. No feedback, or pipe comes from any successive attempts at activiation.

**Comment by aleksix** [comment]
I was unable to reproduce the issue. The only thing that I noticed is that the RPD must be clicked on a non-space, non-shuttle tile on a station level (surface, construction, main or sublevel). It fails when clicked on a pipe or some other object, it seems.

**Comment by Brayyce** [comment]
Join as an atmo tech go over to the RFD - P, and attempt to use it in atmospherics more than once. It simply won't. I've replicated both on server, and in an local instance downloaded this afternoon.

**Comment by aleksix** [comment]
Very strange. Still unable to reproduce in any capacity. Are you sure you are clicking on a tile adjacent to the character, and on the floor and not any pipes? Can't see any reason for the issue. Would it be possible to attach a screenshot showing multiple attempts on the same adjacent tile?
