### ISSUE TITLE
Slime wrecks Vaurca

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#9071]
Had a grey slime on me for a seccond, killed it with the shower, the result was all organs gone.
![image](https://user-images.githubusercontent.com/55027366/84084839-878ca300-a9e4-11ea-98cc-9da0f016f3d5.png)

**Comment by Geevies** [comment]
slimes do toxin damage and vaurca are weak to toxin damage, not really a bug
