### ISSUE TITLE
Cyborg crowbar unable to lift floor tiles

### ISSUE THREAD

**Issue by robovelcro** [Aurorastation/Aurora.3#9073]
While playing as the Construction module of a Cyborg, I was attempting to do some rewiring, where I suddenly noticed I was unable to use the Crowbar to lift up tiles. 

I tried using all tools. The only way to do it was to use the RFD to **Remove the entire floor down to space, and rebuilding the lattice and floor.** This is obviously less-than-ideal.

Even on the floor tiles I just made, crowbar does nothing. Tried also using all other tools, to no avail.
  _That's a crowbar. It is a small item.
An iron bar with a flattened end, used as a lever to remove floors and pry open doors._

**Comment by aleksix** [comment]
The bug was noted to be due to the user being on harm intent.
