### ISSUE TITLE
Weapon Analyzer deletes your weapon when inserting upgrades

### ISSUE THREAD

**Issue by robovelcro** [Aurorastation/Aurora.3#9080]
https://streamable.com/4vow8k

The clip above gives a good demonstration - You have your gun in there, you try and upgrade it (say, with a Capacitor Overcharge) and it just *replaces* the gun. Admin was able to make it appear by "editing the loc because it was stuck in contents" (whatever that even means) so I would assume the issue is related to that.

**Comment by aleksix** [comment]
One of the issues is that you're not supposed to be able to "upgrade" the finished gun. It's still a bug, but a different one, of the gun being replaced.

**Comment by Geevies** [comment]
I'll take a look at this.

**Comment by NerdyVampire** [comment]
I was just about to open this issue as well. Glad to see it's already being resolved.
