### ISSUE TITLE
AI nerf broke hacking tool

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#9089]
The hacking multitool is unable to bolt doors now, presumably due to the access permissions being identical to the AI's, which was recently changed to block them from bolting doors.

**Comment by printer16** [comment]
Note, the button still works. You can bolt doors still. The UI is just weird.

**Comment by Kaedwuff** [comment]
That needs to be fixed then, because a grey button indicates it is nonfunctional
