### ISSUE TITLE
Welding mask not functioning

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#9090]
I burned out my eyes cutting a wall with a welding mask on.  Something's wrong with the item.

**Comment by Geevies** [comment]
Did you flip it down, then immediately start welding?

**Comment by Kaedwuff** [comment]
I put it on and started welding several seconds later.

**Comment by printer16** [comment]
Unable to replicate with any variety of the welding masks or as different species. It's possible that the server was lagging behind when you started to cut and the goggles didn't register as down in time. As a rule of thumb, if your vision is not reduced by your mask, you are not protected from eye damage.

**Comment by Geevies** [comment]
unable to replicate, it was probably just lag + vision code shenanigans
