### ISSUE TITLE
Wizard's Body Change Bug

### ISSUE THREAD

**Issue by EvilBrage** [Aurorastation/Aurora.3#910]
Lately, I've been losing all of my spells as a wizard when switching bodies. It doesn't happen immediately - but a good five or six seconds after the change is made, the spells disappear from my list (and, if the orb of scrying was chosen, I lose my x-ray vision as well.) I got Garn to help me test a few things out and I've also figured out the following:
1. Removing and re-adding the wizard antag type does not fix the bug.
2. When adding new spells, the book acts as if you have not lost your old spells (i.e. if you had fireball and lose it via the bug and then attempt to re-take it, it will say you've improved your fireball spell.) Maybe the spells aren't truly removed, but just hidden or disabled somehow?

**Comment by Alberyk** [comment]
The spell has been removed, so, I doubt this is happening again.
