### ISSUE TITLE
New wirecoil sprites uncolored

### ISSUE THREAD

**Issue by Cnaym** [Aurorastation/Aurora.3#9109]
The new wire coil sprite is lacking color as icon and in hand.
![image](https://user-images.githubusercontent.com/55027366/84519484-738dbd80-acd2-11ea-9e74-65ecbd85aeab.png)

**Comment by Cnaym** [comment]
Same issue for screwdrivers:
![image](https://user-images.githubusercontent.com/55027366/84519880-f9aa0400-acd2-11ea-9a85-75ec67b5a282.png)

**Comment by Geevies** [comment]
fixed
