### ISSUE TITLE
Gravity not functioning properly at round start

### ISSUE THREAD

**Issue by Kaedwuff** [Aurorastation/Aurora.3#9112]
This has happened on two separate situations, so it is at this point as recurring issue.  I am not sure what is causing the issue, so I will describe it in detail because the scenario was identical.

Upon joining the round as a visitor, I spawned in the northern elevator on the ODIN.  Upon leaving and stepping into the hallway and next to the opposite wall, I found myself unable to move properly.  I could rotate my character, so the issue was not lag.  

The only method I was able to use was laying down dragging myself across the floor, but I noted that I was constantly pushed back to the west and back into the wall as if I was in space and experiencing forward momentum in that direction.

Upon reaching the door to the south, I was capable of moving properly again, but found my movements restricted as if I was in a 0 gravity environment, i.e. I continue to drift in whatever direction I begin moving unless there is a wall or other object to brace myself against.  

After some time of drifting around this way, my movement is restored normally, as if the game suddenly remembered that gravity exists for me.  

I hypothesize that the  walls in the first hallway are unsimulated or something and the game doesn't register them as walls that let me guide myself along them, so I am simply stuck in place, 'drifting' to the west until I drag myself down to a window and door that register as objects to brace myself against.  I don't know why gravity fails to function for me at round start, however.

**Comment by Geevies** [comment]
believe this has been fixed
