### ISSUE TITLE
Aurorastation/Aurora.3 The Deep fryer sound is still looping.

### ISSUE THREAD

**Issue by Meltharas** [Aurorastation/Aurora.3#9124]
This has been an issue for a while. The moment anything goes into the deep fryer, the sound effect of sizzling starts and refuses to stop even when it is empty. This issue was reported as closed and fixed, but it is still occurring. While turning off the fryer stops the sound now, turning it back on makes it resume. Originally, it played the sound once the first time anything was put in for the shift and never again. Is there a way to fix this?

**Comment by MarinaGryphon** [comment]
IIRC, it uses the sound loop system. The sound is the oil sizzling. It plays when the oil is being heated. This is intentional.

**Comment by mikomyazaki** [comment]
Yeah, this is intentional. If you think it's too loud / annoying or similar, let me know and we can address that. But I'll mark this as not a bug, @Meltharas
