### ISSUE TITLE
Engineering borgs have no wirecutters.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#9132]
Instead, they have an empty box.

https://gyazo.com/50ba8eed18bfdfbd92eff658bd0b24c3

Also, they shouldn't have an impact wrench as they already have a screwdriver and wrench built in. Two tools that serve the same purpose.

Edit: Apparently this was meant to be fixed at an a

**Comment by Geevies** [comment]
this has been fixed
