### ISSUE TITLE
Blood is Forever

### ISSUE THREAD

**Issue by SilverTalismen** [Aurorastation/Aurora.3#9150]
Blood stains on clothing, or anything never get washed out even if you wash the clothing with seemingly any means. [Spacecleaner, washing it in a sink or even a washing machine]

Blood also remains on your hands or bare feet forever, no matter what you do.

**Comment by Cairo283** [comment]
I can confirm that this is a bug. Heck of annoying.

**Comment by Geevies** [comment]
should be fixed now
