### ISSUE TITLE
Security can nullify the Changeling's arms 

### ISSUE THREAD

**Issue by emr9018** [Aurorastation/Aurora.3#9152]
- UnknownMurder
The security is able to nerf the changeling by grabbing and placing them in handcuffs which nullifies the changeling's arm swords which is a whole 20 chemicals.

**Comment by XanderDox** [comment]
... Don't get aggressive grabbed by security and actually fight them well then?

Sec cuffing was already nerfed by requiring an aggressive grab. Your sword would basically be useless after being cuffed anyways, and sprouting the arm sword breaks you out of cuffs.

**Comment by emr9018** [comment]
So, here's what really happened. While I was slashing an officer, he put me into aggressive grab and cuffed me twice in a row. Thanks for your _sarcasm_ response.

**Comment by emr9018** [comment]
So, here's what really happened. While I was slashing an officer, he put me into aggressive grab and cuffed me twice in a row. Thanks for your _sarcasm_ non-developer response

**Comment by emr9018** [comment]
The point is about the sword arms is, you wouldn't be able to cuff it if it were giant shaped knife that can easily cut through handcuffs.

**Comment by Doxxmedearly** [comment]
Not really a bug. Make a suggestion to change it. 
Also don't sass people on git, Xander. Unless you're replying to the issue itself, don't post.

**Comment by emr9018** [comment]
@Doxxmedearly 
Sure, no problem. I'll create a suggestion and include a link to this issue.

**Comment by emr9018** [comment]
That alright with you, Doxx?

**Comment by Doxxmedearly** [comment]
Yeah, all good.

**Comment by emr9018** [comment]
Got it. It's up. 
https://forums.aurorastation.org/topic/14622-rectify-changelings-blade-arms/
