### ISSUE TITLE
Reagent Spawning Test Merge -  Flasks from loadout spawn without certain selected reagents

### ISSUE THREAD

**Issue by sadkermit** [Aurorastation/Aurora.3#9239]
Just a small issue I've noticed that's similar to the saltshakers spawning without salt, I think (though that's been sorted).

Vacuum flasks from the loadout, depending on the reagent you choose to spawn with, will spawn empty without the selected reagent. I've only noticed this for _fatshouters milk_ (hopefully it's just this drink that fails to spawn), it works for other drinks such as Royal Jelly and Sarezhi Wine, but I haven't tested each individual drink selection to see if they all work.

![1](https://user-images.githubusercontent.com/58568342/86039577-86c2bc00-ba3a-11ea-897f-d801978d471b.PNG)
![2](https://user-images.githubusercontent.com/58568342/86039579-875b5280-ba3a-11ea-9943-2fa4d331bbbf.PNG)

**Comment by MarinaGryphon** [comment]
UUUUUUUGH. Fatshouters milk and fermented milk had weird IDs. Fermented fatshouter's milk was `/datum/reagent/drink/milk/adhomai/fermented` but had an ID of `adhomaimilk`. Fatshouter's milk was `/datum/reagnet/drink/milk/adhomai` but had some other weird ID that wasn't `adhomaimilk`. This is probably related to that.

**Comment by MarinaGryphon** [comment]
![image](https://user-images.githubusercontent.com/13442831/86298617-c4068580-bbc3-11ea-9737-e2647e40c9bf.png)
Gamer moment. Fixing now.
