### ISSUE TITLE
Reagent Spawning Test Merge - Can't refill hardsuit chemical injector

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#9245]
If you were to go to the Rescue RIG and attempt to fill its Norep/Tramadol/Tricord/Dexalin stores with one of the four chemicals, you will get a "None of the reagents seem suitable" message, which only ever displayed for reagents that were not one of the four, before. Seems it can't be filled at all for now even with the proper reagents.

**Comment by MarinaGryphon** [comment]
Should now be fixed once the testmerge is updated.

**Comment by WickedCybs** [comment]
Forgot to close this. Fixed indeed.
