### ISSUE TITLE
EMT role spawns in cryo at the start of the round

### ISSUE THREAD

**Issue by tomekkiel** [Aurorastation/Aurora.3#9252]
As the title says.

**Comment by mikomyazaki** [comment]
Couldn't reproduce. Spawned in the medical briefing room as a human nanotransen paramedic with the EMT alt-title at start of the round.

**Comment by tomekkiel** [comment]
Strange. I play Tajara, if maybe that is the issue?

**Comment by Sgtsammac** [comment]
I've been playing EMT for almost a week. 
Human Character - Nanotrasen - EMT Title

Each time I've spawned at roundstart, it drops me at wherever my "mid-game" spawn is. 

Both times i've played intern I spawned in briefing area.

**Comment by crimzonmartin** [comment]
Everytime I spawn as EMT or Paramedic, it spawns me in one of the two cryo spawns aswell
