### ISSUE TITLE
Atmos Techs/CE's/AIs could possibly vent an away site.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#9258]
Unsure if this is a bug or not, but the above mentioned roles could vent the Kataphract away site as they appear on the Atmospherics Control panel.

https://gyazo.com/963b7c3ff90c50d00e973115c0030d63

Again, if bug, please to delete. If not, coolio.

**Comment by mikomyazaki** [comment]
Couldn't reproduce by:

- Enabling Kataphract ghost role, and spawning in as one.
- Respawning as Chief Engineer and going to Atmospherics and looking at the Atmospherics Control program.
- Couldn't see the away site alarms on the list.

Not sure what else I need to do to get them to show up.
