### ISSUE TITLE
Server attempts to run merc/heist/etc game modes on secret without enough players readied up, then fails to start as a result

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#927]
Game ID where this occured: bG3TUf

My understanding is the system isn't even supposed to try those round types if the per-requisite Players Ready count isn't met.

**Comment by skull132** [comment]
Are you certain that it actually failed because of the player requirement? Usually what happens is that it fails because it cannot make enough antags.

**Comment by SierraKomodo** [comment]
There were 13 people readied up, and it specifically said not enough players, 15 are needed. Here's an exact log of the vote result message, then the failed-to-start message:

>Vote Result: secret
>The round will start soon.

>Unable to start Mercenary. Not enough players, 15 players needed. Reverting to pre-game lobby.
>Welcome to the pre-game lobby!
>Please, setup your character and select ready. Game will start in 180 seconds

It also called a new vote after this as well.

**Comment by skull132** [comment]
I may be able to fix this in my antag related PR. Should be simple enough.
Maybe.

**Comment by MarinaGryphon** [comment]
Skull says that this is a won't fix that is fixed via a workaround. Closing.
