### ISSUE TITLE
Librarians no longer spawn with their book bag

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#9280]
I haven't tested this if I spawn on the Odin, however. But as the title implies, when I come out of cryogenic storage I am lacking my book bag, which can be super helpful in moving books to the shelves.

**Comment by mikomyazaki** [comment]
Couldn't reproduce, got given my book bag as soon as I was spawned in cryo storage. Also got my book bag from round-start spawn on the Odin. 

![librarian_book_bag](https://user-images.githubusercontent.com/47489928/86536947-718ad900-bee3-11ea-9b8f-ffff9898bff4.PNG)

**Comment by mikomyazaki** [comment]
Some of the devs were talking on Discord about this. Apparently it is to do with items being dropped inside the cryo-pod because the character is sleeping. There are some plans to deal with this... apparently.
