### ISSUE TITLE
surgery issues with fixing a broken skull

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#93]
Though only attempted once by a potentially awful and very rusty doctor (pump), performing bone repair surgery in the head does not seem to properly fix the skull. Adminbus is required to fix the issue.

More testing is required, though, given pump probably had less than a fuzzy idea of what he was doing and the fault likely falls on him

**Comment by darkrising** [comment]
I can confirm that skull repair surgery does work without issue. There is an annoying chance of re-breaking the skull however, so the procedure sometimes has to be repeated a few times.
