### ISSUE TITLE
Cyborgs can't understand sign-language

### ISSUE THREAD

**Issue by AgentWhatever** [Aurorastation/Aurora.3#930]

**Comment by SoundScopes** [comment]
This was intentional as when it was designed not every cyborg could speak/understand every language.
The only borg that got it was Service and Clerical. It's also one of the few counters of them being able to understand everything anyone says

**Comment by skull132** [comment]
Not a bug, intended feature. Borgs don't need to know sign language outside of Service and Clerical.
