### ISSUE TITLE
Deaf+Hearing Aide = Silent Intercomms/Holopad comms

### ISSUE THREAD

**Issue by SilverTalismen** [Aurorastation/Aurora.3#9310]
Being deaf and using a hearing aid, or holopad comm or I imagine a hand held radio doesn't let you hear comms from those devices as if you are still deaf, meaning you can't use them either.

Expected to be able to use Holopads to communicate or intercomms or handheld radios.

Can't use any of these things.

**Comment by Hilary325** [comment]
I feel you. I've been wearing a hearing aid for several years, and I know what issues people with hearing loss might face. And I also would like to listen to the radio. The last time I visited the staten island audiological services, I was suggested to get a cochlear implant. It has internal t-coils available for use and available connectivity to FM systems or Bluetooth. Of course, this surgery is not cheap, but this is a lifelong solution.
