### ISSUE TITLE
Cult Talismans randomly lose their assigned rune

### ISSUE THREAD

**Issue by synystersparx** [Aurorastation/Aurora.3#9338]
I haven't been able to replicate this with a specific action. However, a few days ago I was cult, made talismans and examined them to make sure they were properly made, which they were. Near the end of the round, when I tried to use them, they all only gave the message "This talisman has no power." which means no rune is assigned. 

I've tried doing everything I did throughout that game (putting in and out of backpack, dropping backpack, renaming the paper) and nothing seems to directly trigger it. Seems like it happens over time.

**Comment by mikomyazaki** [comment]
@Geevies
