### ISSUE TITLE
Tail's cannot be partially obscured by clothing

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#935]
Example here.

![untitled6](https://cloud.githubusercontent.com/assets/19973802/18595977/36810250-7c9b-11e6-919b-6c6b51196ebd.png)

As can be seen on the image, the tail down the middle is showing fully, the coat displayed does not have a gap in the middle but the tail still show's.

All (Or at least all commonly available) clothing in-game does not draw attention to this fact as they all follow roughly the same shape and size.

However, if someone wants to make a custom item or simply a new item that deviates from the norm, this rears its ugly head.

Currently to my understanding there are only two options for tails, full view, or complete removal, neither of which works for clothes that are simply Long.

Ideally, for clothing such as this when facing south for example, would have the tail at the edge still visible and seen moving from side to side, but most of the tail in the gap between the legs obscured by the coat.

This is probably a lot of trouble but if it was dealt with then it would be appreciated.

**Comment by skull132** [comment]
Tails go under coats. As is illustrated.

Not a bug.
