### ISSUE TITLE
Atmos pipes vanishing/multiple scrubber on same spot?

### ISSUE THREAD

**Issue by Ottygen** [Aurorastation/Aurora.3#9357]
Was trying to mess around with atmos, and now the waste to filtering line is fucked up, so i tried to replace it. Whenever I try to place down a scrubber manifold (image 1) with either a wrench, impact wrench, or pipe wrench, it just disappears (image 2). 

One spot over, there was a case of two scrubbers pipes overlapping each other. I took off a single scrubber bent pipe, and seeing how I couldnt place another one down in the same spot, i crowbar up the floor and see there is another one on the same tile (image 3). Wild. Pipes are busted. Also the whole scrubber network is down because of these bugs.

edit: forgot images lol
![dreamseeker_2020-07-13_23-56-20](https://user-images.githubusercontent.com/67671333/87382821-df7b7400-c565-11ea-96e2-b783e05a6d5a.png)
![dreamseeker_2020-07-13_23-56-29](https://user-images.githubusercontent.com/67671333/87382825-e86c4580-c565-11ea-9b06-2b391ba25712.png)
![dreamseeker_2020-07-13_23-44-41](https://user-images.githubusercontent.com/67671333/87382830-eace9f80-c565-11ea-84ff-325f65183223.png)

**Comment by Ottygen** [comment]
Oh my god they aren't scrubber pipes

**Comment by mikomyazaki** [comment]
Couldn't reproduce. If this happens again, can you ahelp and see if the admin can check if the pipe still exists on the turf or not? It may just be failing to get a valid overlay *somehow*.

**Comment by Doxxmedearly** [comment]
I do remember this happening when I started to learn atmos. 
It might only be reproducable if you try to anchor a scrubbers pipe next to a regular pipe?

**Comment by JohnWildkins** [comment]
Can't reproduce and the pipenet refactor might maybe possibly fix it anyway
