### ISSUE TITLE
Emergency shutters require air alarm electronics instead of airlock ones

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#9366]
Upon building an emergency shutter (steel > airlock assemblies > emergency shutter (4 steel sheets) it requires air alarm electronics, instead of normal ones. It's the only type of airlocks that does require air alarm electronics instead of airlock ones, and it isn't mentioned anywhere, not even on wiki (https://wiki.aurorastation.org/index.php?title=Guide_to_Construction). We had sat there for a good 5 minutes, "what to do", before one of us jumped with idea to disassemble already constructed airlock to check what's there. Reproduceable. Mixed Secret Mode Odds: Server revision:  - 2020-07-15 a43d22eea6307bcf0778e880a0ea1dd73153dea4 Current Map: NSS Aurora

**Comment by fernerr** [comment]
I understand the confusion in the construction process, for emergency shutters however the functionality of air alarm electronics would be more relevant compared to airlock ones. With them detecting atmospheric disturbances.

**Comment by HetNeSS** [comment]
I agree that it's not relevant and more suitable at that, but could there be any record, at least on wiki, on specific way of construction of such thing?

**Comment by fernerr** [comment]
That is best asked of the wiki maintainers, try the #wiki_coordination channel on the discord.
