### ISSUE TITLE
IPC's can fit into Breacher Suits

### ISSUE THREAD

**Issue by coolbc2000** [Aurorastation/Aurora.3#937]

**Comment by Alberyk** [comment]
![ipcbreacher](https://cloud.githubusercontent.com/assets/11579997/18608807/ea962206-7cc9-11e6-864f-a5ca213c6acc.png)
Nope, it seems to work as intended, anyone can wear the module, but only unathi fully deploy it.
The game id or anything would help.

**Comment by coolbc2000** [comment]
Shit, can't help you there. Sorry fam
