### ISSUE TITLE
Windoors are not affected by power loss

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#939]
When an area loses power, any windoors in that area don't change behavior in any way:
- They still require ID access to open
- AI/borgs can still remotely open/close the windoors
- They cannot be toggled open/closed with a crowbar (Although for a windoor, I'd just make it openable without ID with an empty hand when there's no power)

**Comment by MarinaGryphon** [comment]
I believe this is no longer an issue, they can't be opened without power.

**Comment by FirinMaLazors** [comment]
It looks like they can be opened whether or not power is on.  Also, doors will automatically open when the power goes out, so... Not sure this is an actual issue?

**Comment by FirinMaLazors** [comment]
Hmm, the AI can still open windoors when the power is out, and crowbars of course don't open the windoors.  ID access is still required.
