### ISSUE TITLE
Cleanbot pathfinding errors

### ISSUE THREAD

**Issue by Lessick** [Aurorastation/Aurora.3#94]
http://puu.sh/n2AOH/2853a6cb6c.png

If a cleanbot can't get to where it wants to go, it starts making log spam until someone starts pulling it or turns it off/breaks it. I've seen this happen primarily at doors that they don't have access to (morgue, botany, kitchen doors), but once in a the hall outside the kitchen. 

Also, their patrol function only appears to work sometimes, and other times they'll just sit in one place for a few minutes despite the behavior being toggled on, until someone walks past and increases the floor's dirtiness. Dunno if this is just because we had a relatively clean floor and that's how it's _supposed_ to work, but if not it's worth noting.

**Comment by skull132** [comment]
They're silenced. Pathfinding will probably remain odd, but I'd say we can label that under NT being godawful cheap with its AI chips. (Plus, it's always been like that, and debugging AI code is not something on the sheets atm.)
