### ISSUE TITLE
Rats are borked (20.07.20)

### ISSUE THREAD

**Issue by HetNeSS** [Aurorastation/Aurora.3#9408]
> Game ID: b8e-ceSC
> Unable to find any safe, unwelded vents to spawn rats at. The station must be quite a mess!  Trying again might work, if you think there's still a safe place. 
> Unable to spawn: spawn_mob failed. Report this on GitHub

**Comment by Doxxmedearly** [comment]
Rat spawners were removed, no longer an issue
