### ISSUE TITLE
Excessive grinder malfunctions with certain hairstyles

### ISSUE THREAD

**Issue by Toasti3** [Aurorastation/Aurora.3#9421]
Attempting to use a grinder while wearing the Chrono and Vegeta hairstyles resulted in a hair-pulling arterial 100% of the time

**Comment by crimzonmartin** [comment]
Also, wearing a surgerical cap to tie down your hair does nothing, and the malfunctions happen even when the grinder is OFF and you're just putting things into it. You can wear PPE, and get mauled by a machine that's off. 

I was wearing one of the afro hairstyles.
