### ISSUE TITLE
After you are uncuffed, the handcuff sprite in your hands spots, does not go away

### ISSUE THREAD

**Issue by tomekkiel** [Aurorastation/Aurora.3#9457]
As the title says. The sprite doesn't exactly goes away, but it sort of "flickers" as you do things in that spot. and by hand spots I mean the ones in which you hold things.

**Comment by mikomyazaki** [comment]
![persistent_cuffs](https://user-images.githubusercontent.com/47489928/88773659-5033aa80-d17a-11ea-8c73-d96e1796e32b.PNG)
@Geevies
