### ISSUE TITLE
Bug with borg drone light sprites

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#9461]
It is quite faint but if you look closely, there's a thin green line hovering above the borg drone sprite.

![image](https://user-images.githubusercontent.com/19973802/88461760-8105ac80-cefa-11ea-9eb0-3b6a47949c06.png)
![image](https://user-images.githubusercontent.com/19973802/88461752-6cc1af80-cefa-11ea-85c7-434f2db1b294.png)

**Comment by Chada-1** [comment]
Uh oh. I'll PR a fix for this.

**Comment by Chada-1** [comment]
This can be closed
