### ISSUE TITLE
Fix/Revert HIDEJUMPSUIT

### ISSUE THREAD

**Issue by skull132** [Aurorastation/Aurora.3#949]
Issue caused by PR #758 .

HIDEJUMPSUIT flag appears to be causing scenarios where the jumpsuit is no longer drawn for clothing where it should be drawn (for example, riot gear).

This is further compounded by the fact that when removing these clothing items, icons are not properly updated, leaving the character naked until something forces an icon update.

Possible options:
* Remove flag for the time being
* Review all items with the flag and make sure they actually don't show any underlying skin of the mob. And also make sure that icons get properly updated whenever a suit is removed. Right now, this is not the case.

**Comment by NanakoAC** [comment]
second option is the one to do.

**Comment by skull132** [comment]
That's 45 references to look through, and one call stack adjustment.

**Comment by skull132** [comment]
Also, I lie. The proc to update the icons is most likely called at the proper time, but something might be messing with the results of the `check_draw_underclothing` proc. A simple debug message into it should yield more results.

**Comment by Bedshaped** [comment]
The proc to update icons was only updating with respect to the item of clothing being removed.

So a suit being removed with your jumpsuit undrawn was only redrawing the suit.

Also future note: I don't believe there's an `obj/.../on_u_equip()` just a `mob/.../u_equip()` could be helpful to have I think.
