### ISSUE TITLE
Can't use a health analyzer on people on a roller bed

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#9533]
AS it says on the tin. People lying down on a roller bed can't be scanned with a health analyzer _which is really bad for medical_.

**Comment by Melariara** [comment]
Also can't use them while they're on operating tables!

**Comment by Melariara** [comment]
Sorry to keep adding to this. You **can** do it but it needs to be on aggressive intent, which is annoying when you're meant to be helping people. Also, same with hyposprays. Can't hypospray unless you're on harm intent, which doesn't make much sense.

**Comment by WickedCybs** [comment]
Happens with Advanced Trauma Kits as well.
