### ISSUE TITLE
cannot craft a knife blade from steel

### ISSUE THREAD

**Issue by tomekkiel** [Aurorastation/Aurora.3#9534]
You are unable to craft knife blades for making a butterfly knife. it may be an issue with the new UI for crafting. (Or I'm just blind)

**Comment by mikomyazaki** [comment]
Blindness confirmed, try this option:

![blindness](https://user-images.githubusercontent.com/47489928/89091692-5193eb80-d3a3-11ea-8a94-743c2db7f192.PNG)
