### ISSUE TITLE
Mangled faces and dialogue 

### ISSUE THREAD

**Issue by WickedCybs** [Aurorastation/Aurora.3#9539]
It appears that if your face gets mangled you will now show up in the text log as "unknown" on radio and in person. Not sure if this is intentional as before, you would still show up with your name despite the damage on radio logs and such.

**Comment by mikomyazaki** [comment]
I think this is intentional, there's a comment in the code next to the relevant section saying that ability to vocalize gets messed up alongside your appearance. 

/mob/living/carbon/human/GetVoice()
...
if(face?.disfigured) // if your face is ruined, your ability to vocalize is also ruined
