### ISSUE TITLE
unable to scan people on a rollerbed with a health analyzer on help intent

### ISSUE THREAD

**Issue by SebkillerDK** [Aurorastation/Aurora.3#9544]
you are seemingly unable to use a health analyzer on someone on a rollerbed or a surgery table. you just get a redtext messege saying you are not quite sure what to do. although if you use any other intent it seems to work for some reason.

it happened in the round before this one: b8p-cNKU

how to reproduce:
step 1. buckle someone to a rollerbed or surgery table
step 2: try to scan them with a handheld health analyzer on help intent
step 3: fail at this for some unknown reason
step 4: try again on another intent than help and it works for some reason

**Comment by Doxxmedearly** [comment]
A fix was merged roughly 2 hours ago. Is it still occurring on current rounds?

**Comment by SebkillerDK** [comment]
it seems fixed now, thanks.
