### ISSUE TITLE
Head Re-attachment Surgery no longer working.

### ISSUE THREAD

**Issue by StationCrab** [Aurorastation/Aurora.3#9574]
Tried it a few ways, wiki included. Bluespace boi tried as well, could not get it working. 

Couldn't slap the head on, and also when trying to saw down the 'stump' per the wiki, the tool just misses.

**Comment by mikomyazaki** [comment]
Can you elaborate? It seems to work for me.

What type of mob were you trying this on?
Exactly what surgery steps did you try?

![head_attachment](https://user-images.githubusercontent.com/47489928/89123559-425a8e00-d4c8-11ea-812a-4d6dc0051d5a.PNG)

**Comment by StationCrab** [comment]
The head was removed outside of surgery, perhaps that makes the difference? It was done by a team of mercs. Unfortunately I am not exactly sure what they used to decapitate the guy, maybe a sword? Also the patient was deceased at the time.
