### ISSUE TITLE
Rat Spawn Bug

### ISSUE THREAD

**Issue by XChrisUnknownX** [Aurorastation/Aurora.3#9601]
I spawned immediately into turret fire and am not sure if this is an inherent thing / unintended bug or a modification made to the station afterwards. b8s-dobN was the round on August 3, 2020, approximately 6:15 p.m.  XChrisUnknownX227 is my user ID. 

I have a picture of the occurrence.  Not exactly the most pressing issue. It may be a simple fix if the rat spawns are "objects" that can just be moved. (I haven't done any SS13 coding, so I am unfamiliar.)

 https://imgur.com/a/WxzqeRK

**Comment by Arrow768** [comment]
The rat spawn points are not hard coded.
They are selected by randomly picking a open vent on one of the station z levels.

**Comment by XChrisUnknownX** [comment]
> The rat spawn points are not hard coded.
> They are selected by randomly picking a open vent on one of the station z levels.

I thank you for taking the time to teach me this. That makes a lot more sense imo. I'm going to try to close this.
