### ISSUE TITLE
Ore box (presumably anything you're dragging) getting stuck underneath a tile

### ISSUE THREAD

**Issue by crimzonmartin** [Aurorastation/Aurora.3#9602]
When you either cross a gap with a jetpack, it'll get stuck underneath the tile you're on, being inaccessible
 or you can walk over the downwards ladder tile outside mining and it'll be underneath the tile at the bottom of the ladder.

**Comment by MarinaGryphon** [comment]
This is not a bug. It falls down holes because it's heavy. That said, making things being pulled not fall could be *interesting,* as a feature change?

**Comment by fernerr** [comment]
I think what they mean, as I've seen it first hand in the past, sometimes things you're pulling that fall down holes keep being pulled, even though you're on the level above.
