### ISSUE TITLE
Can't pickpocket hats from drones

### ISSUE THREAD

**Issue by mikomyazaki** [Aurorastation/Aurora.3#9611]
I desire the hat. Hat does not appear on pickpocket menu.

![drone_hat](https://user-images.githubusercontent.com/47489928/89313523-81c3de80-d670-11ea-950f-974101667c88.PNG)

**Comment by StationCrab** [comment]
I don't think borgs/drones can even remove people's clothing/items anymore at all.

**Comment by Baa14453** [comment]
I think drones can just click another drone to remove their hat, I will find out
