### ISSUE TITLE
Wizard Familiar Spawn Bug

### ISSUE THREAD

**Issue by XChrisUnknownX** [Aurorastation/Aurora.3#9613]
When I came in from the menu, the ghost spawner option as a Wizard Familiar was available.  I clicked this mostly out of curiosity. It said spawn_mob failed, report this on Github, so I am doing that to assist with future rounds.

An image of what I encountered is here, which I will try to attach to this post: https://imgur.com/a/YZrfnTD 

This occurred on Game ID b8t-cZVf on August 4, 2020, at approximately 4:15 p.m. 

My BYOND name is XChrisUnknownX227. 

I'm unfamiliar with how to fix this type of bug so please let me know if you need other information.

Please also see my comment below: https://github.com/Aurorastation/Aurora.3/issues/9613#issuecomment-668807892.

 
![00000000screenshotbug](https://user-images.githubusercontent.com/39750269/89340871-69eb5b00-d66e-11ea-8c3e-4bce11a6d41a.png)

**Comment by XChrisUnknownX** [comment]
I tried again at approximately 4:25 p.m. EST and was actually able to enter as a Wizard Familiar. I do not know how to duplicate this bug.


![00000screenshotbug2](https://user-images.githubusercontent.com/39750269/89341340-26452100-d66f-11ea-89a4-8bcd2ee03165.png)

**Comment by Doxxmedearly** [comment]
Wizard is no longer an available gamemode. Closing.
