### ISSUE TITLE
Shells cannot take an amputated limb in the Character Setup page.

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#9625]
Testing this, every chassis except shells are able to take amputation as an option. Perhaps an oversight issue?

As an example, here's a screenshot of a shell paired beside a bishop, where the bishop who can take an amputated limb.
![shelllimb](https://user-images.githubusercontent.com/56227386/89496636-ac8b6f80-d7f5-11ea-9096-a951ae727012.png)

**Comment by mikomyazaki** [comment]
This was an intentional choice by LordFowl in #1327 and therefore not a bug.

I can't tell you why this is a thing though.

**Comment by niennab** [comment]
I thought we discussed this. Since shells can't be other species this should no longer be needed.

**Comment by mikomyazaki** [comment]
@niennab Yeah, I wrote that comment before I talked to you. 👍

**Comment by niennab** [comment]
@mikomyazaki Aah I see. Is there a chance it can be reopened then?

**Comment by mikomyazaki** [comment]
> @mikomyazaki Aah I see. Is there a chance it can be reopened then?

@niennab No need really. I've already got a PR up that solves this #9644

**Comment by niennab** [comment]
@mikomyazaki Oh! You're the best! <3
