### ISSUE TITLE
Mental focus and wand of force appear to be buggy as fuck

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#9626]
So I have been trying out wizard stuff on a private server, and noticed that the mental focus appears to be completely arbitrary in whether or not it'll work as it should.

Sometimes the projectile will dissipate on impact and the victim will be completely fine. Sometimes it'll hit like a freight train and fling them across the room. 

The projectiles should probably be dissipating less.

How to reproduce:Head into the bar and shoot someone with a wand of force a few times.

**Comment by Doxxmedearly** [comment]
Wizard is no longer an available gamemode. Closing.
