### ISSUE TITLE
Radiation Collectors Don't Seem to Function

### ISSUE THREAD

**Issue by furrycactus** [Aurorastation/Aurora.3#9679]
Title, basically. 

They don't function with Supermatter radiation (but this might be intentional?), but I think this has been a thing for a very long time. However, they also don't seem to function with Singularity generators, either. Not that Singularities _are_ set up often, but, still. It'd be nice if they could be looked at, rather than cast away and forgotten. If they were able to work with the Supermatter, it could give optional protects for engineering to work on if they feel like acquiring the stuff for them.

**Comment by SleepyGemmy** [comment]
hasn't been a feature for a long time.
