### ISSUE TITLE
Equipping Black Jeans Short Shorts in the Loadout does not spawn a uniform in your satchel

### ISSUE THREAD

**Issue by Vulcenus** [Aurorastation/Aurora.3#9693]
As the title says, having black jeans short shorts in your loadout doesn't spawn a uniform (Idris security uniform in my case) after walking through the transfer shuttle airlock thing.

**Comment by Hockaa** [comment]
I think the issue might actually be with spawning on the Odin and using the AutoDrobe in general - I tested it a moment ago and it didn't seem to work. Gonna work on a fix for it now.
