### ISSUE TITLE
Amputees with missing hands/arms show normal sprites from the sides

### ISSUE THREAD

**Issue by sheeplets** [Aurorastation/Aurora.3#9695]
![uAsY0tt](https://user-images.githubusercontent.com/44004468/90298342-f14f8000-de5f-11ea-97f8-ae4df323253e.png)
![zcpA3jr](https://user-images.githubusercontent.com/44004468/90298366-06c4aa00-de60-11ea-88cd-bfa685c7b05d.png)

M-Muh immershun.

**Comment by NonQueueingMatt** [comment]
This isn't a normal sprite, this is the result of clothing having to not cover the arm segment to not display over the arm

What you're actually seeing is your character's chest cut out to arm shape

This would take a pretty big amount of refactoring to fix
