### ISSUE TITLE
Taser gun safety icon overlap

### ISSUE THREAD

**Issue by TheDocOct** [Aurorastation/Aurora.3#9706]
![image](https://user-images.githubusercontent.com/22651198/90344453-93e23d00-dfdf-11ea-8ee5-892eefb6111a.png)

Disabling the taser's (potentially including other guns with safeties) under unknown circumstances (in this case, simply after taking it out of the security locker) will cause the 'unsafe' indicator to overlay the 'safe' indicator, which does not disappear as it should.

**Comment by Doxxmedearly** [comment]
Unable to replicate any circumstances. Examples would help if this is still happening.

**Comment by TheDocOct** [comment]
Can confirm that this still happens relatively frequently (when handling weapons), and doesn't _seem_ to be limited to any particular gun(s). In my personal experience, it happens with disruptors and pump shotguns. Still not certain what particular circumstances cause it, but it's usually relatively late in the round. I'll catalogue whenever I see it and when going forward, honestly forgot I reported it.

**Comment by Doxxmedearly** [comment]
Alright, might not be taking the right steps to replicate it then on my end, then. When I find time I will keep trying, just trying to make sure it was still relevant. Thanks!
