### ISSUE TITLE
Coat stand doesn't hold coats.

### ISSUE THREAD

**Issue by Estutes** [Aurorastation/Aurora.3#9718]
Coat  stand doesn't hold coats. When trying to put a coat on the coat stand of security, doesn't work. Other's have tried and couldn't. Maybe we are dumb and none of us know how to use it. Should at least be checked out.
Questions, ask Estutes via discord. I'm inside the group.

**Comment by fernerr** [comment]
Which coats was it? The coat stand doesn't have support for all of them.
