### ISSUE TITLE
The false alarm event doesn't actually need to send a false alarm to be in action

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#972]
Nothing actually got announced but after a while...

![untitled8](https://cloud.githubusercontent.com/assets/19973802/18668481/c52b0992-7f89-11e6-96d6-e694db85de6a.png)

A very alarming false alarm.

**Comment by NanakoAC** [comment]
hah, oops

This actually happens because we have a silent event called nothing, that does nothing, and just exists to vary the quantity of events slightly

**Comment by skull132** [comment]
Another event which causes oddities: random antagonist.

A blacklist of events contained in false alarm datum would probably be best solution.

**Comment by skull132** [comment]
Fixes in PR #1022 .
