### ISSUE TITLE
Cyborg chargers cause issues with the powernet, cyborgs upgraded with higher cells.

### ISSUE THREAD

**Issue by Denuvo** [Aurorastation/Aurora.3#975]
Basically, since the Cyborg charger nerf, cyborgs with higher cells and upgraded cyborg chargers cause issues. Here is an example : 

1. Cyborg obtains Vtec, hyper cell upgrades.
2. Cyborg heads to upgraded charger, as it nears an empty powercell.
3. Charger is rapidly emptied, only giving the cyborg ~10% of it's charge, and draining the charger entirely.
4. Charger then recharges using the powernet, maxing the Powernet's available capacity, until the charger is fully recharged.

Note that i have not tested this with multiple Cyborg charger upgrades or Cyborg upgrades. Should you wish me to, simply ask.

**Comment by NanakoAC** [comment]
I'll look into it to see if there's an issue here, but I would say that a cyborg with a hyper cell should also have access to a properly upgraded charger, its part of the support infrastructure they need to function. Changes may or may not be made

**Comment by skull132** [comment]
The charger drain to output ratio has been pretty shit ever since the Bay
update.

**Comment by NanakoAC** [comment]
tweaked in #980 

I've adjusted values a bit to slightly alleviate this - mostly increased the passive charging rate, and added a warning message so people can understand what's happening. But largely it's not a problem to be fixed. If you have a cell that's far more powerful than the one in the charger, and you're close to empty, you will experience some slowdown as the charger's capacitor runs out, that won't change.

@Denuvo An important thing that seems to be missing in your example scenario, is that the charger's internal cell can be upgraded like the rest of the parts. Putting a better cell in there is recommended. This problem does not occur if the charger is given a cell that's equivilant to what the active cyborgs are using, and i don't want to make an upgrade redundant

**Comment by Denuvo** [comment]
Copy. Thank you for your quick response and update.
