### ISSUE TITLE
Space Before Fullstop When Deaf

### ISSUE THREAD

**Issue by Geevies** [Aurorastation/Aurora.3#9764]
Image says it all: 
![image](https://user-images.githubusercontent.com/22774890/90983632-e1c2ec00-e56f-11ea-8222-f6f5aac6af7d.png)

**Comment by mikomyazaki** [comment]
Seems to be a pronoun macro that isn't functioning properly. Should be replaced with 'them' I guess.

**Comment by MarinaGryphon** [comment]
Yes, as shown in #9745, since there is no mob reference passed you cannot use a pronoun macro.

Fixed in #9745.

**Comment by NonQueueingMatt** [comment]
fixed
