### ISSUE TITLE
Limb targeting module doesn't appear to work for constructs

### ISSUE THREAD

**Issue by FirinMaLazors** [Aurorastation/Aurora.3#9813]
Constructs have three noticeable things in their HUD:  their spells in the upper right hand corner, their general health in the middle on the right, and the limb targeting module in the lower right hand corner.  This module, while looking different from the "/living/carbon" module, appears to be functionally the same:  you can target the head, eyes, left and right hands and legs, etc.

However, based on some experiments in my test server, it appears that the body part targeted in the module doesn't actually have any meaning in game.  Constructs effectively strike body parts at random.  I am unsure if this extends to all simple_animal mobs.  I am also unsure if this is intended behavior or not.

**Comment by NonQueueingMatt** [comment]
fixed
