### ISSUE TITLE
People using certain atmos equipment can phase around walls.

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#982]
Pretty much this is happening: https://github.com/PolarisSS13/Polaris/pull/2507

Confirmed by the round with the following game id: buejVf

Where the ce could phase around the walls after using a high pressure gas pump.

**Comment by skull132** [comment]
...How on Earth does vent crawl even do this...

**Comment by skull132** [comment]
Exact steps to reproduce:
Also, exact steps to replicate:
* Spawn as nekkid hunam
* Go next to a piece of pipe machinery (like a pipe)
* Left click to presumably open menu
* Try moving our, notice screen spaz
Also, key: try moving around in one step incriments.
The effect is more profound then.

Issue is somehow tied to the various attack procs that interactable pipe pieces have. Shouldn't be too hard, maybe.
