### ISSUE TITLE
West Solar "Access Denied"

### ISSUE THREAD

**Issue by Lordnesh** [Aurorastation/Aurora.3#9820]
Round ID: b8R-c2IA
Admin: Arrow768
PR test merged: PR #9624 Vision Cones
Character Role: engineering apprentice

Issue: Getting "Access Denied" at airlock for Beta Solar array. According to admin, door requires access IDs 10, 11, and 13, but I was missing 13. However, in the previous round (without the test merge) I had no issue accessing the airlock. Same role and character.

**Comment by JohnWildkins** [comment]
fixed
