### ISSUE TITLE
Adding the bowtie to a coat puts it in the coat pocket.

### ISSUE THREAD

**Issue by niennab** [Aurorastation/Aurora.3#9823]
When attaching the bowtie to my jacket (it shows better if it's on the jacket instead of the shirt), the game both adds the bowtie while putting it in my pocket. Moreover the bowtie cannot be removed unless I right click + remove accessory. The trick I've done so far is to fill my coat pockets and then add the bowtie.

I thought this was the case with all accessories on jackets until I added the trinary perfection pin to my jacket without this happening.

![bugg](https://user-images.githubusercontent.com/56227386/91640930-147f4f80-ea5c-11ea-8298-27656aa03d18.png)

**Comment by JohnWildkins** [comment]
cannot reproduce
