### ISSUE TITLE
Roundstart Spawn for Visitors results in duplicate PDA/ID/headset.

### ISSUE THREAD

**Issue by GMR25** [Aurorastation/Aurora.3#9826]
When readying in the lobby and roundstarting as a Visitor, you will spawn in Central/Odin in the elevator that leads to the arrivals shuttle. You spawn with your ID, PDA and headset already on your person. Passing through the machine before the shuttle spawns you *another set* of these things, duplicating your ID/PDA. The second PDA is fully functional and gets messages separately from the first. This results in either needing to ahelp for their deletion, or accepting that you have two PDAs and IDs now (as well as the dubious antagonistic benefits these confer).

A simple solution would be having roundstart visitors spawn on the station itself in some form.

**Comment by JohnWildkins** [comment]
Visitors aren't available at roundstart now, so in a roundabout way this fixes that problem.

**Comment by GMR25** [comment]
I've been spawning as a visitor at roundstart for the last month, so that's clearly untrue.
