### ISSUE TITLE
infinite sprint NYOM NYOM 

### ISSUE THREAD

**Issue by SebkillerDK** [Aurorastation/Aurora.3#9827]
i seem to be able to produce infinite stamina, by quickly toggeling between walk and sprint when my stamina bar is empty. as fun as INFINITE SPEED is this is also highly fucking broken for tajarans

happened round before this one: b8T-bRmR

how to reproduce:
1: empty stamina
2: quick toggle between run and walk
3:fucking code magic idfk
4: inffinite speed NYOM NYOM BITCH

**Comment by Doxxmedearly** [comment]
Been trying off and on to replicate this. Will need other information since I can't seem to make it happen.
