### ISSUE TITLE
Deleted records also get deleted from the 'hard file records storage' in the vault (Unconfirmed)

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#983]
Marked unconfirmed as I'm reporting this based on an LOOc discussion in a round earlier today, and this isn't something I can specifically try and test in-game (Can't get the code to run properly on a server on my end either).

**Comment by skull132** [comment]
Not a bug.

The hard copies are fake, they still rely on the same database.

Proper implementation would require hard copies be actually maintained, and is more of a feature than anything.
