### ISSUE TITLE
Species job restrictions are not working

### ISSUE THREAD

**Issue by Alberyk** [Aurorastation/Aurora.3#9835]
![image](https://user-images.githubusercontent.com/11579997/91675759-e6f5dd00-eb13-11ea-898d-a7195f63b0d1.png)

**Comment by Ben10083** [comment]
![image](https://user-images.githubusercontent.com/91219575/163442861-19c2603a-d799-43ab-9781-23589ac6af71.png)
Testing with Dionae and Vaurca show species restrictions, has this been fixed?
