### ISSUE TITLE
GoonChat when relogging breaks

### ISSUE THREAD

**Issue by TehFlaminTaco** [Aurorastation/Aurora.3#9837]
Round ID b8U-aKcY

When rejoining a round, after about a minute, GoonChat will break, causing new message to not appear.

Seems to self resolve if you leave it like this for several minutes, but reconnecting just starts the cycle over.

Relates to PR #9635

**Comment by NonQueueingMatt** [comment]
How many people were in round?
What's your connection like and how far away are you from Germany?

**Comment by TehFlaminTaco** [comment]
Australia, was saying ~150 ping till it crapped out. Didn't check but was relatively high pop. Multiple people reporting the same issue.

**Comment by niennab** [comment]
I am in Korea and I experience the same issue and seemingly at random.

**Comment by Doxxmedearly** [comment]
Experienced it just now. US. 56 players. Average ms around 80. b8U-dkHg
During this time overhead messages still appear.

**Comment by TehFlaminTaco** [comment]
Still occurs as of b83-ap50 (Pop 43)

**Comment by TehFlaminTaco** [comment]
![This](https://cdn.discordapp.com/attachments/302201161044328450/752740509704913006/unknown.png)

This fills the chat when the accent icons break.

**Comment by connorjg1** [comment]
I face the same issue in Australia average 150ms ping

**Comment by ClemTheDuck** [comment]
same issue in aus, average 170ms ping, i get the same downloading picture stuff when chat tries to load sprites and it causes major lag.
