### ISSUE TITLE
no feedback from selecting any of the title screen options

### ISSUE THREAD

**Issue by OneOneThreeEight** [Aurorastation/Aurora.3#9838]
the buttons do not work. there's no typical audio feedback from clicking anything like there was without using goonchat

other useful information: this is from experience trying to join into a round that has already started. The other test-merged PR that was active was the vision cones PR.

![image](https://user-images.githubusercontent.com/11053780/91691562-d5bdc800-eb35-11ea-8bf5-7e7fbe0639d5.png)

**Comment by JohnWildkins** [comment]
this only happens if byond topic calls are completely broken, which does happen to me occasionally but is a bug with BYOND more than anything else

just restart if it happens
