### ISSUE TITLE
Accent tags not showing in Goonchat testmerge

### ISSUE THREAD

**Issue by Doxxmedearly** [Aurorastation/Aurora.3#9847]
https://i.gyazo.com/2ca123aaba7e06abce16cc71325f0088.png

Happened yesterday as observer, today as a player.
b8U-dkHg. US, 56 players, average 80ms ping.
Reconnecting does not fix the issue. In fact more disappeared after reconnection. 
Byond version is latest. Could be the issue?

**Comment by NonQueueingMatt** [comment]
fixed
