### ISSUE TITLE
Diona spawn with no set default language

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#986]
Not sure if this is by design but you have to set the default language manually when you spawn.

**Comment by NanakoAC** [comment]
Intended behaviour.
They do spawn with a default language. Rootsong. You just have to switch to common as your default if you want that

As NT employees they have to be able to speak basic, but as aliens new to human space, they are still somewhat unfamiliar with it.

**Comment by darkrising** [comment]
@NanakoAC You could say that about any of the alien races yet they all spawn with their default as basic.
