### ISSUE TITLE
Ordering a hakhma always produces an AC unit instead.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#9868]
https://gyazo.com/c4423969fd711d9faf5b72760b3e672e

https://gyazo.com/fea268ec79ab3790bf10eea5829cef19

https://gyazo.com/5477ccbd863e1c79aababd76a4e1d5d4

Three rounds in a row I've had this happen, twice in one round even. Always the AC. Unsure if its a bug or something but its quite annoying.

**Comment by Alberyk** [comment]
Should be fixed next round
