### ISSUE TITLE
Nymph can't see if a borg is attacking them

### ISSUE THREAD

**Issue by darkrising** [Aurorastation/Aurora.3#987]
Basically no red text is generated and instead you get these weird scoop messages.
http://tzli.me/X8qsH

I've no idea what the borg was doing but they were security module, so perhaps a baton? No corpse was created either.

Maybe connected to #960 

Edit: As an additional note, I had absorbed all the nymphs that were created after my gestalt was split.

**Comment by NanakoAC** [comment]
Those messages are from them dragging you onto yourself and triggering pickup code. That's a different, and likely unrelated bug

There was a bug that i recently fixed, which caused nymphs to sometimes instantly die from a single hit, it's possible the borg only hit you once, at the end, and that bug caused instant death. although that fix should be live now.

The bug you linked is related to language and is not related to this issue,

@darkrising If possible, i'd like to know who the security borg was that did this, so i could ask them what happened.

**Comment by darkrising** [comment]
@NanakoAC I believe the borg's name was PYRAMIDION, I did ask in looc at the time but they didn't answer.
