### ISSUE TITLE
Joining as AI can give you Psionic Powers

### ISSUE THREAD

**Issue by Muncorn** [Aurorastation/Aurora.3#9882]
![image](https://user-images.githubusercontent.com/25222499/92281942-9657f880-eef4-11ea-9994-aa475f289f8b.png)

Had my Skrell captain selected in setup, and joined midway through the round and it gave the message saying I had psionic powers as I joined. Had no ingame buttons for it or usable commands anywhere.

**Comment by DreamySkrell** [comment]
irrelevant now that the psionics system changed
