### ISSUE TITLE
Limb replacement surgery as borg

### ISSUE THREAD

**Issue by Lordnesh** [Aurorastation/Aurora.3#9902]
Game ID: b81-dLSG

Issue: attempted to perform limb replacement surgery as medical borg, however, when I tried to attach the bishop left hand it wouldn't work. I had not issue picking up the hand, and when I tried it on another part of the body I got the "You aren't sure what you could do" message. Using it on the desired location yielded nothing.

**Comment by Melariara** [comment]
Hey! I also reported this one a few days back here!

https://github.com/Aurorastation/Aurora.3/issues/9834
