### ISSUE TITLE
You can now see LOOC through walls

### ISSUE THREAD

**Issue by Fire-and-Glory** [Aurorastation/Aurora.3#992]
I am not sure on the precise specifics, but since the new update I've seen LOOC coming from people who are not in sight but who I knew were in the vicinity.

I'm not sure if it completely phases through several walls or such, but it happens.

We probably don't need ninjas inside maint accidentally LOOCing to whatever person is in EVA storage, or such.

**Comment by SierraKomodo** [comment]
As far as I'm aware.. LOOCing going through walls has always been a thing.

**Comment by Bedshaped** [comment]
This has always been the case. And even if you read an antagonist using LOOC, you're expected to treat that information as having occurred outside of roleplay, your character has no knowledge.

**Comment by Fire-and-Glory** [comment]
I could've sworn it wasn't a thing, oh well.

**Comment by LordFowl** [comment]
This has not always been a thing - it was changed in Nanako's modifications to LOOC, where she stopped usung get_mobs_in_view. Whether it is a bug or not depends on her intention.

**Comment by Arrow768** [comment]
I am also quite sure this has always been a thing.
Maybe @Nanako can shed some light on it ?

**Comment by skull132** [comment]
Here's how it worked for LOOC:
- As a ghost, any mob in view, you can see their LOOC I think.
- As an actual IC mob, you should only see the LOOC from mobs you can
visually see. Otherwise, if you can see the LOOC of people through walls,
it makes no sense.

**Comment by SoundScopes** [comment]
Always been a thing. It's a mechanic designed to ask for help to anyone who can hear you nearby even if you can't see them.

**Comment by Geevies** [comment]
Intentional, at this point.
