### ISSUE TITLE
I turn invisible for myself if theres many people about.

### ISSUE THREAD

**Issue by IndirectCell** [Aurorastation/Aurora.3#9926]
![bilde](https://user-images.githubusercontent.com/60559077/92464850-0c4ab100-f1ce-11ea-8fd9-e689b3e17e00.png)

If i walk out of the room that has 4 people in it, then my sprite comes back, if i enter back in their field of view my sprite disappears, and its only in some directions.

![bilde](https://user-images.githubusercontent.com/60559077/92464969-4025d680-f1ce-11ea-9965-69010dc2674b.png)

Iv seen this happend before near botany when theres a few people about, and another time when there was many people and i was trying to apply bandaids to myself in a more critical situation.

**Comment by IndirectCell** [comment]
I think the problem happends when theres 5 or more people in one area.

**Comment by FirinMaLazors** [comment]
@IndirectCell does this still happen?  I get the feeling that this may have something to do with vision cones, have you seen this @mikomyazaki ?

**Comment by mikomyazaki** [comment]
Most likely vision cones. No idea why this happens, presently, I'll check it out though. Thank you.

**Comment by JohnWildkins** [comment]
vision cones are gone, and haven't heard a thing about this since
feel free to re-open if it occurs
