### ISSUE TITLE
Blind Talismans delete users from existence entirely

### ISSUE THREAD

**Issue by Karhast** [Aurorastation/Aurora.3#9933]
Round ID: b83-cWfL

As a cultist, I created myself several talismans for later use. A fight broke out, and I used my blind talisman.. Whereupon my character vanished. Completely. His body was gone, there was no gear, he just straight up went away entirely. I have no idea what could have caused this, but it got me extreme amounts of frustrated, and I'd be very happy to see it fixed.

**Comment by Doxxmedearly** [comment]
RIP to the funniest bug I've ever witnessed. Was fixed but this didn't get closed.
