### ISSUE TITLE
Farmbot just stops working after a while.

### ISSUE THREAD

**Issue by Melariara** [Aurorastation/Aurora.3#9935]
I'm unsure if this is a bug or not but after a certain point in the round, the farmbot just doesn't water, fertilize or anything. Ends up just... sitting there, while plants need watering, harvesting or fertilizing.

**Comment by FirinMaLazors** [comment]
Checking it out.

**Comment by FirinMaLazors** [comment]
Confirmed.  Forgot to time it exactly, but yeah, what you describe happens.  Toggling it on and off didn't do anything.  However, pulling it around a bit did, for some reason.

**Comment by Ultrazundy** [comment]
Can confirm that this happened to me and dragging it does indeed fix it.
