### ISSUE TITLE
wizard raise dead bugs

### ISSUE THREAD

**Issue by Pratepresidenten** [Aurorastation/Aurora.3#9944]
First issue: The initial skeletonized person does not get dibs on his corpse
Second issue: Noone can pick said skeleton as far as I know
Third issue: Upon forcibly putting them into the skeleton, the slot opens up(?) and someone can just force-insert themselves into the skeleton, kicking the original player.

**Comment by Doxxmedearly** [comment]
Wizard is no longer an available gamemode. Closing.
