### ISSUE TITLE
Calling a crew transfer vote as CCIA presents an error message

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#995]
> Error: You do not have sufficient rights to do that. You require one of the following flags: +ADMIN +MODERATOR.

**Comment by Alberyk** [comment]
Did you try to call it before the time/when it was on cooldown?

**Comment by SierraKomodo** [comment]
No, there were no prior votes and it was after the 2 hour mark. I should've clarified that the vote /did/ go through despite the error message.

**Comment by Geevies** [comment]
Die, CCIA, die.
