### ISSUE TITLE
Soda Dispenser not dispensing R&D Root Beer

### ISSUE THREAD

**Issue by Lordnesh** [Aurorastation/Aurora.3#9968]
Game ID b86-dmZa

Tried at a few amounts. Did not work. Dispenser was full (round start).

Didn't have any issue with Mountain Wind.

**Comment by FirinMaLazors** [comment]
I'll work on it!

**Comment by FirinMaLazors** [comment]
Found the issue, I think.  The & in "R&D Root Beer" makes NanoUI spit and cry whenever you try to dispense it.
