### ISSUE TITLE
Merchant Map's Walls are Unsimulated

### ISSUE THREAD

**Issue by honkel** [Aurorastation/Aurora.3#9977]
Server revision: - 2020-09-12
95263045f59017d633e3f5a83a1fff0c4571afa4
Current Map: NSS Aurora

Merchant map's walls are mapped as unsimulated whilst everything else is simulated. This means that if for whatever reason the merchant map ends up a warzone things will not properly breach. 

![Screenshot_10](https://user-images.githubusercontent.com/1912674/93003632-6d47f100-f50e-11ea-8286-aca9c973d999.png)

**Comment by Arrow768** [comment]
![image](https://user-images.githubusercontent.com/1331699/93003702-3dfea780-f541-11ea-99c9-6581b28268b4.png)
These are the unsimulated tiles
