### ISSUE TITLE
Emptying glasses/shakers into a sink doesn't work

### ISSUE THREAD

**Issue by SierraKomodo** [Aurorastation/Aurora.3#998]
>You empty the glass of water into the sink.
>  That's a glass of water. It is a small item.
>The father of all refreshments.
>The glass of water is almost full!

EDIT: It actually appears that nothing can be emptied in sinks anymore. I do recall this working a couple weeks ago.

**Comment by SleepyWolfe** [comment]
it does empty it, but at 5 unit intervals at a time. Kinda useless, and takes a lot of spamming to get a glass empty.

**Comment by skull132** [comment]
It works, it just empties 5 units at a time.

**Comment by Bedshaped** [comment]
!(to empty)[http://i.imgur.com/HLUIXaA.png]

I have to challenge the leader of the pack here and claim that the verb "empty" means to completely vacate the contents!!

**Comment by skull132** [comment]
"Empty in increments" is implied. Useful for when you "woupsed" a bit, but a difference in semantics that I couldn't care less about, I suppose.
