### ISSUE TITLE
Downloading ID Card Modification Program

### ISSUE THREAD

**Issue by Lordnesh** [Aurorastation/Aurora.3#9985]
Game ID: b88-c4Ht

Downloading ID Card Modification Program to terminals in AI core causes the terminal to completely bug out (become not intractable) upon opening the program.

Testing: Tested on multiple terminals with similar results. Downloading, and opening, other programs work fine (didn't test all of them).

**Comment by Lordnesh** [comment]
b89-aAmF

Firearm program fails to load, returning "Javascript file has failed to load." With a button next to it that says "click here to force load resources." Which doesn't work. Tested on two consoles.

**Comment by Geevies** [comment]
doesn't seem to be possible for them to download this program anymore
