### ISSUE TITLE
AI/Borgs and Chemistry

### ISSUE THREAD

**Issue by Soultheif96** [Aurorastation/Aurora.3#9991]
It appears that the beakers ejected from the Chemical Dispensers from Borgs and AIs usually end up ... disappearing into bluespace. I suggest looking into it, may be related to ejecting directly into hands of the handless.

**Comment by stobarico** [comment]
I had this problem once, the AI ejected the beaker for me (I was a borg) and instead it appeared at their core (Where the AI mob itself is located)
