### ISSUE TITLE
Chemical Dispensers become temporarily non-functional when creating Unstable Mutagen with a bucket

### ISSUE THREAD

**Issue by runemeds417** [Aurorastation/Aurora.3#9995]
Round ID: b89-aXsQ

Issue: Upon placing a bucket in to a chemical dispenser, the dispenser becomes unresponsive and it's interface refuses to open upon creating Unstable Mutagen. After a few minutes, the bucket inside the dispenser is destroyed/deleted and the dispenser resumes normal function. This happens every time you attempt to use it.

**Comment by FirinMaLazors** [comment]
Checking it out.

**Comment by FirinMaLazors** [comment]
Confirmed.  Happens whenever you dispense Sulfuric Acid or Hydrochloric Acid into a bucket.

**Comment by FirinMaLazors** [comment]
Transferring 50 units of Hydrocholoric Acid from a chemical cartridge dispenser makes the bucket disappear.

**Comment by FirinMaLazors** [comment]
Aha.  The bucket melts whenever you pour the HCl or Sulph into it when the bucket is on the ground.

**Comment by FirinMaLazors** [comment]
Ok, so buckets are specifically set to be not unacidable, as opposed to beakers.  Makes sense, they're plastic.  The only problem is that you don't get an alert about what's happening when it happens and it gunks up the chem machines.
